### ISSUE TITLE
Velocity bypass

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#100]
You should try to calculate the velocity of someone more accurate because instead of using Antikb you can modify your kb with 0.01 (or some other small value). It will bypass and be like a antikb as you can't even recognize the 1% kb.

**Comment by Janmm14** [comment]
As I tested antiknockback last time with someone it detected 10% and lower.

**Comment by Photon-GitHub** [comment]
Well, 10% ... that's still something to complain about.

**Comment by Photon-GitHub** [comment]
See #192 for a video example

**Comment by Rqcco** [comment]
Fixed by new Velocity re-code.
