### ISSUE TITLE
Setbacks revert teleports (again.....)

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#1001]
Gommelz failed Fly: moved unexpectedly: 0.0000 (0.0000->-0.0784 / -n-n16) [ping:54 tps:19.82] VL:18

AAC does revert teleports to other worlds, respawns etc.

**Comment by CeIebrimbor** [comment]
Relation to #939 (maybe) where a player can be setback thousands of blocks to where they initially mounted a horse.

**Comment by CeIebrimbor** [comment]
And #978

**Comment by Janmm14** [comment]
There is no relation to 978 for players on gomme
