### ISSUE TITLE
AAC does not account for Haste Potion Effect (Level II)

### ISSUE THREAD

**Issue by marint94** [konsolas/AAC-Issues#1005]
Server version: 1.8.8

AAC version: 3.3.3

ProtocolLib version: 4.4.0 (b389)

Plugin list: WorldEdit, WorldGuard, AAC

Special environment information

ViaVersion version: (1.3.0)

ProtocolSupport version: N/A

ViaBackwards version: N/A

BungeeCord plugins: N/A

Haste Potion Effect Level II gets kicked the whole time by "fastbreak" check.
Please fix this asap.

**Comment by Rerd** [comment]
Provide logs?

**Comment by CeIebrimbor** [comment]
This is unlikely and more likely you have another plugin conflicting (custom enchants, RPG plug, etc).

Please provide your _actual_ ProtocolLib version and _actual_ AAC version. Depending on where you got your download of ProtocolLib, "latest" may be the wrong version.

Better yet, use the reporting template that you deleted...

**Comment by marint94** [comment]
You guys are so skeptical :D 
Updated the issue with more information.

**Comment by CeIebrimbor** [comment]
Detection logs and/or video. Any pick with any level of efficiency or maybe a specific combination and block type?

**Comment by marint94** [comment]
Can be closed. As it seems this was only for one player the case.
