### ISSUE TITLE
AAC kicking me as OP - Move (Timer)

### ISSUE THREAD

**Issue by marint94** [konsolas/AAC-Issues#1006]
Server version: 1.8.8

AAC version: 3.3.3

ProtocolLib version: 4.4.0 (b389)

Plugin list: WorldEdit, WorldGuard, AAC

Special environment information

ViaVersion version: (1.3.0)

ProtocolSupport version: N/A

ViaBackwards version: N/A

BungeeCord plugins: N/A

AAC kicks me for Move (Timer) as OP

**Comment by marint94** [comment]
No Permission Plugin installed

**Comment by Slimerblue22** [comment]
AAC's move check never seemed to understand you don't check people with OP and aac.bypass. You can't really turn said check off though unless you wanna disable half of AAC

**Comment by CeIebrimbor** [comment]
Yes. The Move check is like the central nervous system for AAC. It cannot by bypassed with permission or OP.

**Comment by Janmm14** [comment]
just use some hacks that are not called timer if you are op xd

**Comment by marint94** [comment]
Yeah you're right, let's keep breaking mods which use fly like CameraMod because konsolas can't add a simple OP check... 😉

**Comment by CeIebrimbor** [comment]
"Bug" implies "unintended". I would have kept this open if the developer of AAC had not previously stated that the Move check would not be compatible with bypass and OP.

Here's to another feature request that will be on the tracker for a year 🍻

**Comment by konsolas** [comment]
The move check currently cannot be disabled because it acts as a safety net against crashes.

**Comment by Janmm14** [comment]
@konsolas In case of a bypass permission you might want to allow some more move packets per tick, this won't crash the server but allows using timer cheats and possibly also such camera mods.
