### ISSUE TITLE
Jesus Bypass

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#1008]
https://youtu.be/5exywyV9NeU
### Core information
**Server version**: **CraftBukkit version git-Spigot-65e8124-357b573 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)**

**AAC version**: **3.3.3**

**ProtocolLib version**: **ProtocolLib v4.3.0**

**Plugin list**: **Plugins (38): CoreProtect, WorldEdit, PCore, Bosses, Ope
nInv, ClearLag, ArmorStandEditor, HubRider, Votifier, TablistPrefix, WorldGuard, 
Multiverse-Core, Socket4MC, KitsPlus, SkinsRestorer, OldCombatMechanics, PluginCm
dBlock, Heal, DiscordChat, PermissionsEx, MicroJump, ViaVersion, Vault, BankNotes
, BungeeTabListPlus, MassiveCore, SKMCPlugin, Essentials, ProtocolLib, AAC, SKAdm
inTool, EssentialsAntiBuild, SuperVanish, ServerListPlus, EssentialsSpawn, AuthMe
, HolographicDisplays, AuthMeBridge**

### Special environment information
**ViaVersion version**: **ViaVersion 1.3.0**

**ProtocolSupport version**: **None**

**ViaBackwards version**: **None**

**BungeeCord plugins**: **On request**

**Works on default configuration, I can list this if needed**

**Comment by Janmm14** [comment]
Default config does have the older "jesus" check enabled since 3. September. Do you have it enabled too?
Additionally I do see that it gets detected sometimes, however the setback is not far enough at all.

**Comment by Slimerblue22** [comment]
Older Jesus check? I tested with the default by just deleting the custom config and letting AAC make a new one (Made with 3.3.3).

**Comment by Slimerblue22** [comment]
Oh and side note: https://youtu.be/A-jJhg5AuKk

**Comment by LinsaFTW** [comment]
![2017-10-12_04 18 13](https://user-images.githubusercontent.com/25271111/31484195-b25f3836-af05-11e7-8278-fb76e57732ea.png)

I can confirm this with latest jigsaw version. But in my case it doesnt show any message on the verbose on my server.
