### ISSUE TITLE
No slowdown bypass (When colliding with mobs?)

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#1009]
**https://youtu.be/xg8MjN0fHE8**
### Core information
**Server version**: **CraftBukkit version git-Spigot-65e8124-357b573 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)**

**AAC version**: **3.3.3**

**ProtocolLib version**: **ProtocolLib v4.3.0**

**Plugin list**: **Plugins (38): CoreProtect, WorldEdit, PCore, Bosses, Ope
nInv, ClearLag, ArmorStandEditor, HubRider, Votifier, TablistPrefix, WorldGuard, 
Multiverse-Core, Socket4MC, KitsPlus, SkinsRestorer, OldCombatMechanics, PluginCm
dBlock, Heal, DiscordChat, PermissionsEx, MicroJump, ViaVersion, Vault, BankNotes
, BungeeTabListPlus, MassiveCore, SKMCPlugin, Essentials, ProtocolLib, AAC, SKAdm
inTool, EssentialsAntiBuild, SuperVanish, ServerListPlus, EssentialsSpawn, AuthMe
, HolographicDisplays, AuthMeBridge**

### Special environment information
**ViaVersion version**: **ViaVersion 1.3.0**

**ProtocolSupport version**: **None**

**ViaBackwards version**: **None**

**BungeeCord plugins**: **On request**

**Configuration**
https://pastebin.com/xT4SkZJ4

**Comment by Slimerblue22** [comment]
Really not sure if I should make this a different issue since they both have to do with no slowdown, if I need to make a different issue I will. Video: https://youtu.be/fkcGvP3ZF0g

**Comment by konsolas** [comment]
The mechanism here prevents false positives with entity bumping on 1.9+ servers. It seems too minor to be a real issue, and would be quite a complex fix.

**Comment by Slimerblue22** [comment]
What about the other one I put in the comments? Should I make a new issue for it?
