### ISSUE TITLE
v3: Speed/Fly false positives when running into other players.

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#101]
~~If you recieve velocity while being in air it seems to not correctly account the velocity. Due to lag the velocity can also arrive at a later point so there is more leniency needed.~~

Can take a few attempts to reproduce, see title.

**Comment by konsolas** [comment]
@Janmm14 / @Photon-GitHub / @Rqcco code has been added to fix this. Could any of you confirm?

**Comment by Photon-GitHub** [comment]
Fixed.

**Comment by Photon-GitHub** [comment]
If sprinting into a not moving player you will get flagged.

**Comment by konsolas** [comment]
Fixed, confirmed by geNAZt and Rqcco.
