### ISSUE TITLE
No slowdown bypass: walk sideways/backwards

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#1011]
**Side note: This was posted as a comment but that issue was closed so I'll just make a new issue for it** https://youtu.be/fkcGvP3ZF0g
### Core information
**Server version**: CraftBukkit version git-Spigot-65e8124-357b573 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**AAC version**: 3.3.3

**ProtocolLib version**: ProtocolLib v4.3.0

**Plugin list**: Plugins (38): CoreProtect, WorldEdit, PCore, Bosses, OpenInv, ClearLag, ArmorStandEditor, HubRider, Votifier, TablistPrefix, WorldGuard, Multiverse-Core, Socket4MC, KitsPlus, SkinsRestorer, OldCombatMechanics, PluginCmdBlock, Heal, DiscordChat, PermissionsEx, MicroJump, ViaVersion, Vault, BankNotes, BungeeTabListPlus, MassiveCore, SKMCPlugin, Essentials, ProtocolLib, AAC, SKAdminTool, EssentialsAntiBuild, SuperVanish, ServerListPlus, EssentialsSpawn, AuthMe, HolographicDisplays, AuthMeBridge

### Special environment information
**ViaVersion version**: ViaVersion 1.3.0

**ProtocolSupport version**: None

**ViaBackwards version**: None

**BungeeCord plugins**: On request

**Configuration**
https://pastebin.com/xT4SkZJ4

**Comment by Janmm14** [comment]
Eventually related: #818
