### ISSUE TITLE
[API] PlayerViolationEvent is fired twice

### ISSUE THREAD

**Issue by xDefcon** [konsolas/AAC-Issues#1013]
### Issue description
The PlayerViolationEvent present in the AAC's API is fired twice when a player fails a check.

### Steps to reproduce
1) Create an EventHandler for PlayerViolationEvent
2) Print some message to console
3) Register the listener class & try to fail a check. You will get the message twice.

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.3 

**ProtocolLib version**: 4.2.0

**Plugin list**: AAC, TestPlugin (To handle the API event)

### Configuration
Default config.

**Comment by Janmm14** [comment]
Are you sure that your listener is just registered once and the plugin is just loaded one time?

**Comment by xDefcon** [comment]
@Janmm14 Yes, I am sure about it. 
Here is a code snippet to reproduce the issue: https://gist.github.com/31d69438c946ac6144827d8e362ca838

**Comment by konsolas** [comment]
Will be fixed next update
