### ISSUE TITLE
AAC+Citizens Memory Leak 

### ISSUE THREAD

**Issue by komiss77** [konsolas/AAC-Issues#1014]
AAC build thousan instances, when plugin Citizens installed.

### Core information
**Server version**: 1.12.2
**AAC version**: 3.3.2-3.3.3
**ProtocolLib version**: 4.3.1
**Plugin list**: AAC, ProtocolLib, Citizens
**Configuration**: Default config

Steps to reproduce
    run and create some npc and add waypoints to npc move.

`13 950 instances of "net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC$PlayerNPC", loaded by "org.bukkit.plugin.java.PluginClassLoader @ 0x6ec503170" occupy 3 016 335 520 (95,00%) bytes. These instances are referenced from one instance of "me.konsolas.aac.b0", loaded by "org.bukkit.plugin.java.PluginClassLoader @ 0x6ec520840"
Keywords
net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC$PlayerNPC
org.bukkit.plugin.java.PluginClassLoader @ 0x6ec520840
me.konsolas.aac.b0
org.bukkit.plugin.java.PluginClassLoader @ 0x6ec503170`

**Comment by CeIebrimbor** [comment]
This will almost certainly not fix the issue, but please use the [latest stable dev build of ProtocolLib](http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/) for 1.12 servers. We can assume it will still occur, but please report back after updating.

**Comment by komiss77** [comment]
Test with
AAC version: lastes
ProtocolLib version: ProtocolLib 4.4.0-SNAPSHOT-b389
gave the same results

In one of my plugins I came across the fact that it is difficult to distinguish Nps from players. For this there is only one reliable method:
`Citizens citizens=(Citizens) Bukkit.getPluginManager().getPlugin("Citizens");  
  public static boolean isCitizen(Entity e) {
      return citizens == null ? false : (e.hasMetadata("NPC") ? true : citizens.getNPCRegistry().isNPC(e));
   }
`

**Comment by konsolas** [comment]
Since I don't really want to build Citizens as a soft dependency, I've changed the Player references to weak references.
