### ISSUE TITLE
Memory leak with unloaded worlds

### ISSUE THREAD

**Issue by RaynLegends** [konsolas/AAC-Issues#1015]
### Issue description
The AAC-LogWriter Thread seems to be holding references to unloaded worlds and never release them.

In the first screenshot, you can see that there are about 30 "WorldServer" instances, each one of them being already unloaded (hence the relatively small retained heap).

In the second screenshot, which is a list of what classes are holding a reference to those WorldServers (in the screenshot there's only the first WorldServer, but the others are held by the same aac class), you can see that the only thing that's referencing them (thus preventing it from being garbage collected) is the "AAC-LogWriter Thread" (well, it's not exactly what's holding the reference but since the classes are obfuscated I can't tell much more than "it's me.konsolas.aac.U").

You can find the screenshots here:
https://imgur.com/a/AyV8W 

This is happening in AAC 3.3.0, but I'm pretty sure it also "works" with AAC 3.3.3.
I'll test the new version tomorrow but, if the changelogs are accurate, it's unlikely that it has been already fixed.

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 3.3.0

**ProtocolLib version**: 4.3.1-SNAPSHOT-b378

**Plugin list**: AAC, ProtocolLib, ViaVersion, and a lot of proprietary plugins (but that's not relevant, they are not holding the references)

### Special environment information
**ViaVersion version**: 1.3.0

**Comment by RaynLegends** [comment]
I've tested with AAC 3.3.2 (well, in the spigot resource page it says "3.3.3" but with /aac I get "3.3.2") and the problem is still there.

I've added a screenshot in the album (it's the third one, https://imgur.com/a/AyV8W)

**Comment by Slimerblue22** [comment]
Yeah, AAC 3.3.3 says 3.3.2 when you run /aac

**Comment by CeIebrimbor** [comment]
#951?

**Comment by konsolas** [comment]
Will be fixed in the next update.
