### ISSUE TITLE
Hitbox vl decay rework

### ISSUE THREAD

**Issue by LinsaFTW** [konsolas/AAC-Issues#1016]
The hitbox-reach detection is really bad , it almost doesnt detect Akrien and Jigsaw.

Actually i think a fix would be instead of decreasing the hitbox vl with legit hits AAC should clear it after 60 ticks from the last hitbox detection , because with jigsaw , akrien , etc it detects barely ok when youre far but when youre closer the vl automatically clear because of the legit clicks.

Adding a vl multiplier wont fix this as that can generate false positives.

Heres proof that the hitbox-reach detection is bad:
![2017-10-12_04 49 51](https://user-images.githubusercontent.com/25271111/31485025-ce20f638-af08-11e7-8eb6-3cd140856d5a.png)
It just clears vls after getting closer! (Killaura reach: 5.1 CPS: 6cps)

Obviously heuristics takes care of Jigsaw , but applying my fix will make AAC unbypasseable with new cheat-clients based on hitbox modification.

**Comment by Rerd** [comment]
This is actually a really good idea.

**Comment by konsolas** [comment]
The obvious worry is that legitimate players might be able to build up hitbox violations. Maybe 60 seconds is too long.

Any thoughts?

**Comment by LinsaFTW** [comment]
Configurable clear_vl under hitbox:

Well i think this will fix false positives because most of them happen when you lag out and they accumulate like 20vls

And if we apply this the dude with augmented hitbox will accumulate over time the hitbox vls as he will be doing false hits everytime they are at more than 4 blocks and that means they can accumulate vls until they get like 60

**Comment by LinsaFTW** [comment]
It will really help detection as every time the player with hitbox-reach knockbacks the other player (or otherwise) he will accumulate a lot of vls

**Comment by Rerd** [comment]
I think every 60 ticks after the last flag, it should remove 1 VL from the player. Both of these should be able to be changed in the config. They should be called something like `clear_vl` and `clear_ticks`.

`clear_ticks` should be the amount of ticks it takes to remove the amount of VL specified (Defaulted to 60)
`clear_vl` should be the amount of VL which is removed after the amount of ticks have occurred specified with `clear_ticks` (Defaulted to 1)

**Comment by LinsaFTW** [comment]
In my config i would use clear_ticks: 40 and clear_vl: 60 would that work?

**Comment by Rerd** [comment]
How so?

**Comment by LinsaFTW** [comment]
Most of false positives get to 20vls , if we reduce 1 vl after 60 ticks of the last vl it will acumulate lot of false positives.

So it should clear all the vls after 60ticks from the last vl so it doesnt acumulate false positives.

**Comment by Rerd** [comment]
I think the further the player hits from, it should add more VL to the player to make it much faster.

**Comment by LinsaFTW** [comment]
I have a better idea! vl_multiplier: 3 :) so vls reduce with legit clicks slower.

Any opinions?

**Comment by konsolas** [comment]
Adding reduce_delay to hitbox check next update
