### ISSUE TITLE
Fightspeed FP

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#1017]
Video: https://www.youtube.com/watch?v=4hfIliXwEQg&feature=youtu.be
AAC-Log: https://hastebin.com/adiqunoqif.hs

**Comment by CeIebrimbor** [comment]
That's a lot of landed hits on the target over the course of 3 seconds. Do I see a NoHitDelay plugin or mechanic at play here?

**Comment by Hyronymos** [comment]
We don't use a NoHitDelay plugin or other mechanics.

**Comment by CeIebrimbor** [comment]
Reproduce = 100% vanilla 1.8 JitterClick in a corner?

**Comment by konsolas** [comment]
That's some really really fast clicking. If this is common amongst your players, or you allow macros, you can increase the click speed limits in the configuration section of fightspeed. The default limit seems more widely applicable.
