### ISSUE TITLE
Improve KillAura check/Make it faster

### ISSUE THREAD

**Issue by jiangdashao** [konsolas/AAC-Issues#1020]
### Issue description

  aac's ka check is too slow and easy bypass now,I think AAC much Rely on Heuristic check,but ignore normal check,I suggest add more normal check method(check illegal head roll,direction,etc)

**Comment by Rerd** [comment]
#953

**Comment by Janmm14** [comment]
illegal head roll is already a separate check inside acc (derp).

If you see a bypassing killaura in a client, please report the client and its used settings.

**Comment by jiangdashao** [comment]
Well,such as Liquidbounce,skid,nivia,vape

**Comment by Rerd** [comment]
Any killaura that attacks invisible mobs will bypass normal.

**Comment by jiangdashao** [comment]
@rerd
yes
