### ISSUE TITLE
Last update Spam error

### ISSUE THREAD

**Issue by JavituRec** [konsolas/AAC-Issues#1025]
Last update I get a spam error: https://hastebin.com/igejiyeqar.vbs
I don't know cause.

Core information

Server version: 1.8.8

AAC version: 3.3.4

ProtocolLib version: 4.3

Special environment information

ViaVersion version: 1.3.0

BungeeCord plugins: Last

Sincerely.

**Comment by Janmm14** [comment]
Duplicate of #1023
