### ISSUE TITLE
Killaura normal bug

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#1026]
### Issue description
High cps (jitterclicking) and jumping will flag killaura normal.
Video: https://youtu.be/uj8yqoSKPxc

### Core information
**Server version**:  1.8.8

**AAC version**: 3.3.4-b1 (it happens on older versions too)

**ProtocolLib version**: 4.2.0

**Plugin list**: Upon request

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: Upon request

### Configuration
Default. No changes were made.

**Comment by CeIebrimbor** [comment]
#953 (similar)

**Comment by Rerd** [comment]
This issue especially happens when the player has over 100 ping. I've had to limit killaura normal bans to 0-175 ping. This is actually ridiculous.
