### ISSUE TITLE
NPE@x.a:89@ar.a:234@t.a:104@N.lambda$new$2:47

### ISSUE THREAD

**Issue by MisterKraabs** [konsolas/AAC-Issues#1030]
https://prnt.sc/gxe0kd

i got a task exception in the console.

**Comment by Janmm14** [comment]
@MisterKraabs Please do test stuff yourself next time or read the changelog of 3.3.4-b1.

**Comment by MisterKraabs** [comment]
Ah, i saw it , sorry xd Thank's
