### ISSUE TITLE
Hitbox Check Features + Reach placeholder

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1031]
### Verbose
**Reach:**
In the verbose for Hitbox's reach check, we currently have a message somewhat like this:
`* [AAC] Rerd failed Hitbox: attacked entity too far away (4.000 blocks, expected 3.50 + 0.30 + 0.10) [ping:0 tps:20.00] VL:2`
I think that where it says `4.000 blocks` there should be another set of numbers in brackets that subtract the hitbox size (in this example `0.30`) and the move compensation (in this example `0.10`) so it shows the reach after the calculations have been done. This would show the actual reach.
So, with this example when this feature is added, it would look like this:
`* [AAC] Rerd failed Hitbox: attacked entity too far away (4.000 blocks [3.600], expected 3.50 + 0.30 + 0.10) [ping:0 tps:20.00] VL:2`

**Lenience:**
Lenience currently shows this in verbose:
`* [AAC] Rerd failed Hitbox: attacked entity out of their line of sight (reach: 4.000 blocks) [ping:0 tps:20.00] VL:1`
I think that with the part where it shows the reach (`reach:4.000`), it should also show the calculations done with the Reach part of Hitbox in brackets.
So, with the feature added, it would be like this with a 0.10 move compensation and 0.30 size hitbox:
`* [AAC] Rerd failed Hitbox: attacked entity out of their line of sight (reach: 4.000 blocks [3.600]) [ping:0 tps:20.00] VL:1`

### Reach Placeholder for /aacstaffnotify
With the /aacstaffnotify command, it should be possible to display the average Reach of the player that is flagging with the calculations done as stated above in the Verbose, Reach section. The placeholder would be something like `{reach}`. If the player has not hit anyone within maybe 30 seconds, then the reach in the output would be `0.00`. So, for example, the output would look somewhat like this in the configuration file:
`8: "aacstaffnotify {player} in {world} is suspected for Killaura (Hitbox) (reach = {reach}, ping = {ping}, tps = {tps})"`
 ... and like this in-game (0.30 hitbox size and 0.10 move compensation):
`[AAC] [CONSOLE] Rerd in world is suspected for Killaura (Hitbox) (reach = 3.60, ping = 0, tps = 20.00)`

**Comment by Janmm14** [comment]
"attacked entity out of their line of sight" is thrown when the raytracing algorithm found out that the ray does not hit the hitbox, I guess the reach shown in brackets in that case is just some squaredDisntacne or sth. similar.

As for the reach placeholder, this will not get implemented with the same reason why there will not be a heuristic pattern placeholder.

**Comment by Minemaniak** [comment]
Why there won't be a Heuristic pattern placeholder?

**Comment by Janmm14** [comment]
Because the command replacement system is different from the verbose system.
A player can trigger multiple heuristics at different percentages, which can change over time.
A player will trigger multiple hitbox violations, all with different reach.

See #784

**Comment by konsolas** [comment]
See explanation in #784
