### ISSUE TITLE
Cannot measure distance between world and world_nether

### ISSUE THREAD

**Issue by kuohsuanlo** [konsolas/AAC-Issues#1032]
[AAC] Task #1009 for AAC v3.3.4 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and world_nether

------
if( location1.getWorld().equals(location2.getWorld())){
location1.distance(location2);
}

You're welcome. ;)

**Comment by Janmm14** [comment]
@kuohsuanlo
Konsolas knows how to fix those issues. And I guess he already has written similar ifs multiple times in AAC.

By the way it would be a good idea to include the stack trace so konsolas knows where to search.

**Comment by Hamata6** [comment]
Duplicate of #1027
@Janmm14

**Comment by Janmm14** [comment]
@Hamata6 until the stack trace is provided its not sure. It could also happen in a different method theoretically.

@kuohsuanlo add the full error (stack trace) please
