### ISSUE TITLE
Ice fp

### ISSUE THREAD

**Issue by Justinis77** [konsolas/AAC-Issues#1033]
### Issue description
I have fp on Ice

### Core information
**Server version**: 1.8.8 Spigot
**AAC version**: 3.3.4
**ProtocolLib version**: 4.2.0
**Plugin list**: AAC, AACadditionpro, ProtocoLib, ConditionalCommands
### Special environment information
**ViaVersion version**:N/A

(Localhost Testserver)
Video: https://youtu.be/LiuRQZo3Okg

AAC Logs: https://pastebin.com/y8YEz3Re

**Comment by Rerd** [comment]
You’re meant to replace “insert” with the info.

**Comment by Slimerblue22** [comment]
Dupe of https://github.com/konsolas/AAC-Issues/issues/933 #933
