### ISSUE TITLE
1.12 Hitbox false positive due to new combat system

### ISSUE THREAD

**Issue by xDefcon** [konsolas/AAC-Issues#1034]
### Issue description
The hitbox check is flagging false positives due to the new combat system introduced in 1.12 (i do not remember if that is still present since 1.11). When hitting players or mobs with the full damage bar, you'll be able to hit more than 1 player/mob in the radius.

Demonstration: https://i.imgur.com/gH8qmzE.gif

Another Video(added by Cel): https://www.youtube.com/watch?v=TBnPg0NqYt0

### Core information
**Server version**: 1.12

**AAC version**: 3.3.3, present also in 3.3.4

**ProtocolLib version**: latest

**Plugin list**: not needed to replicate

### Configuration
Default config

**Comment by CeIebrimbor** [comment]
Where are the hitbox flags? If they are in the video, they are cut off. Please provide them. 

I have tested this at great length in the past while being completely surrounded by 10+ mobs and was unable to get more than a single incidental hitbox and interact detection.

**Comment by xDefcon** [comment]
@CeIebrimbor https://gist.github.com/de05037a1a62d33f060ffb2e996b1860

**Comment by CeIebrimbor** [comment]
😮 ...

**Comment by Slimerblue22** [comment]
That was added back in 1.9 I think

**Comment by xDefcon** [comment]
@Slimerblue22 yes but the ranged hits should be from 1.12
