### ISSUE TITLE
Interact FP & Bypass(?)

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1036]
**FP:** Moving your head vertically really fast and interact (place blocks) it will FP for Interact. This is especially an issue on a pvp server than uses Flint and Steels, which is the one I mainly have it on. The problem with pvp servers that use Flint and Steels is when players turn their head fast (like a 180 or something) it will block the placement of the Flint and Steel. Currently, we are having to disable them until this is fixed. Another issue with this is playing BuildUHC. In BuildUHC, decent players place blocks underneath them while running towards and away from someone. With this as an issue, a lot of the blocks will be blocked from placing and will really annoy players.

**Bypass(?):** Any client, literally any. AAC doesn’t cancel interactions through blocks (levers, buttons, etc.).

[Video which includes both the Bypass and FP.](https://www.youtube.com/watch?v=-3gJt2T60r0)

### Configuration
Default AAC Config.

**Comment by Slimerblue22** [comment]
Yea, I have my interact check set to stop at VL 27 and sometimes legit players manage to make it to that VL.

**Comment by w-o-a-h** [comment]
this is a issue because the server is 1 tick behind the client
