### ISSUE TITLE
Killaura heuristics false positives

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#1038]
### Issue description
(#941 previous issue was marked as fixed, although it's not)
Title is pretty self explanatory. Tested on a default configuration. 

Video: https://youtu.be/xBxfmw6zMHI

In the video: SpookyFueZ failed Heuristics: detected by pattern P/95 (confidence 78.0) [ping:11 tps:19.99] VL:1

I tried it again (without recording), then I had this: SpookyFueZ failed Heuristics: detected by pattern P/99 (confidence 78.0) [ping:14 tps:19.92] VL:1

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.4-b1

**ProtocolLib version**: 4.2.0

**Plugin list**: AAC and ProtocolLib

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

**Comment by Slimerblue22** [comment]
Does the target have to be lifeless or can it be done in PvP on a player fighting back?

**Comment by iConfueZ** [comment]
It can be done with a player fighting back, though it takes longer and it's a different pattern which I fail then.

**Comment by konsolas** [comment]
Does the confidence ever go above 78.0?

**Comment by iConfueZ** [comment]
Nope, doesn't go above 78.0

**Comment by Janmm14** [comment]
p/99 and p/95 got changed in the last updates, open a new issue if you are expirencing false positives on latest aac (3.3.8 by now)
