### ISSUE TITLE
Server still starting up.

### ISSUE THREAD

**Issue by enly1337** [konsolas/AAC-Issues#1042]
### Issue description
Players can`t connect to arena with reason: "Server still starting up." https://gist.github.com/enly1337/361dccb15803b6d0ab0db9cde6a54385

### Core information
**Server version**: git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)

**AAC version**: 3.3.4

**ProtocolLib version**: 4.3.0

**Plugin list**: BedWars, ViaVersion, BlazePermissions, ProtocolLib, AAC, AACAdditionPro, ConditionalCommands

### Special environment information
**ViaVersion version**: 1.3.0

**Comment by Slimerblue22** [comment]
Try updating AAC and see if the problem still happens

**Comment by konsolas** [comment]
Going to need the full log file of the server

**Comment by CeIebrimbor** [comment]
Will reopen if the requested info is given.
