### ISSUE TITLE
cheaters can pass through walls and doors

### ISSUE THREAD

**Issue by NORTBE** [konsolas/AAC-Issues#1043]
Server version: 1.8.9 PaperSpigot
All checks in AAC enabled (last version)
ProtocolLib 4.2.1
ViaVersion 1.3.0
BungeeCord plugins (SkinsRestorer)
Plugins (73): PickupCooldown, SetWarpLimiter, PlaceholderAPI, TwenturePickupFix, PlugMan, FunnyCr, SFMCGUI, ViaVersion, HideStream, WorldEdit, HealthBar, KitLimiter, Skript, GappleCooldown, TwentureCore, RenameManager, ClearLag, AutoMessage, WorldBorder, BlockSyntax, ActionBarAPI, CustomizableHealth, Multiverse-Core, ProtocolLib, TWCChatFilter, AdvancedPortals, Joiner, LimitCrafting, PermissionsEx, TwentureCreative, EffectLib, CustomJoinItems, Vault, PayForCommands, Repuska, KillerMoney, HolographicDisplays, WorldGuard, AAC, SkinsRestorer, PacketBookFix, ChestCommands, MythicMobs, PlayerVaults, TwentureRules, ChatManager, InfiniteArmor, RedstoneClockPreventer, Essentials, TwentureBlocker, TWCCases, LiftSign, LimitedWorldEdit, WGFlyStop, ItemFixer, Citizens, ColoredTags, Shopkeepers, CrazyAuctions, JLib, EffectsShop, CombatTagPlus, DontTouch, TwentureKoth, TwentureBans, LeaderHeads, PVPLimiter, CommandNPC, EssentialsSpawn, TwentureFight, TitleManager, AuthMe, AuthMeSQ

**Comment by Rerd** [comment]
You’re supposed to replace “insert” with the information asked.

**Comment by Slimerblue22** [comment]
Lots of information in this post. (This is an example of what we call Sarcasm)

**Comment by konsolas** [comment]
Closing due to insufficient information.
