### ISSUE TITLE
Errors on starting

### ISSUE THREAD

**Issue by xMalware** [konsolas/AAC-Issues#1045]
### Issue description
I've a problem when I start minigame instances on my server with my own plugins and AAC. Sometimes, the server isn't joinable, players are kicked with a message : "Server still starting up".
I've an AAC error in my logs.

Logs:
https://hastebin.com/vovabofujo.sql

### Core information
**Server version**: 1.8.8-R0.1 (PaperSpigot)

**AAC version**: v3.3.4

**ProtocolLib version**: v4.3.0

**Plugin list**: BadblockGameAPI, BadBlockGuardian, ViaVersion, ProtocolLib, NoCheatPlus, AAC, BadblockTower

### Special environment information
**ViaVersion version**: 1.3

**ProtocolSupport version**: No

**ViaBackwards version**: No

**BungeeCord plugins**: BadHAProxy, BungeeOthers, BungeeUtils, LadderBungee

### Configuration
I've just disabled some cheats and removed lines where AAC kicks, nothing else.

Differences:
https://www.diffchecker.com/QnmT39H1

**Comment by Janmm14** [comment]
Related: #1042

**Comment by konsolas** [comment]
No response.
