### ISSUE TITLE
Error on join velocity causing too many packets

### ISSUE THREAD

**Issue by kekshost** [konsolas/AAC-Issues#1047]
I have a large console error: https://pastebin.com/MGWtNucz and most of the players are kicked for too many packets. The server is a creative server.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: PaperSpigot 1.12.2

**AAC version**: 3.3.1

**ProtocolLib version**: 4.3.0

**Plugin list**: insert

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: 2.3.1

**BungeeCord plugins**: N/A

### Configuration

Celembrimbor config for that version....

**Comment by Janmm14** [comment]
Usually there is nothing applying velocities on join to players. Hmm... will be fixed likely anyway.
