### ISSUE TITLE
Users with aac.bypass cause the KillAura (normal) mobs to not spawn

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#1049]
Video: https://youtu.be/pdWdEPGDYoc
### Core information
**Server version**: CraftBukkit version git-Spigot-65e8124-357b573 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**AAC version**: 3.3.4

**ProtocolLib version**: ProtocolLib v4.3.0

**Plugin list**:  Plugins (43): CoreProtect, PCore, Bosses, OpenI                                                                                        nv, ClearLag, ArmorStandEditor, HubRider, Votifier, TablistPrefix, Mult                                                                                        iverse-Core, Socket4MC, SkinsRestorer, KitsPlus, OldCombatMechanics, FastAsyncWo                                                                                        rldEdit, PluginCmdBlock, Heal, DiscordChat, PermissionsEx, MicroJump, ViaVersion                                                                                        , Vault, BankNotes, BungeeTabListPlus, MassiveCore, WorldEdit, SKMCPlugin, Essen                                                                                        tials, PassiveAddons, WorldGuard, ProtocolLib, AAC, SKAdminTool, Plan, Essential                                                                                        sChat, EssentialsAntiBuild, SuperVanish, ServerListPlus, EssentialsSpawn, AuthMe                                                                                        , HolographicDisplays, AuthMeBridge

### Special environment information
**ViaVersion version**: ViaVersion 1.3.0
**ProtocolSupport version**: insert (or N/A)

**ViaBackwards version**: insert (or N/A)

**BungeeCord plugins**: **On request**

**Comment by CeIebrimbor** [comment]
This is known. I will wait on dev to decide to close or label a "request", but will not assume he is not willing to rethink his stance on this.

It's just an unfortunate side effect of making someone immune to checking. 🤷‍♂️

**Comment by Slimerblue22** [comment]
Ah, alright. Didn't know that it was known already. Found out about it a few days ago so I thought I'd make a report on it

**Comment by Rerd** [comment]
Also it stops Hitbox from working if you’re attacking a player with aac.bypass.

**Comment by konsolas** [comment]
This is intentional behaviour as the combat checks rely on data collected from both entities to work correctly.
