### ISSUE TITLE
Fly, speed, and Phase Bug, under a block.

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#105]
If you go under a block and start jumping up and down while crouching, you get detected for phase. If you jump next to it, you get detected for fly and sometimes speed. https://www.youtube.com/watch?v=L-9fxoQntfQ

**Comment by Rqcco** [comment]
*Fly only flags when there is a ladder on the block on top*

**Comment by Janmm14** [comment]
Player hitbox gets smaller when sneaking(.15 smaller), also make sure that you have an idea when players uncround in that one bad moment.

**Comment by konsolas** [comment]
Fixed and tested. (Rqcco and Janmm14)

**Comment by Photon-GitHub** [comment]
Phase detection is fixed but fly detection still is a thing...

**Comment by Photon-GitHub** [comment]
(Tested under a ladder)

**Comment by Janmm14** [comment]
The 3-blocks-jump fly false positve is only there if you don't move while jumping. If you move you won't get flagged / setbacked

**Comment by konsolas** [comment]
Fixed, tested.
