### ISSUE TITLE
Killaura bypass (only when Invisibles are enabled)

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#1050]
### Issue description
Title is self explanatory

Video: https://youtu.be/F2UoRIsk7dI

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.4-b1

**ProtocolLib version**: 4.2.0

### Configuration
Only changed cancel: true to cancel: false in the Hitbox check.

**Comment by Janmm14** [comment]
Killaura is usually best detected in real fights where the killaura module is doing head rotations etc.
What you showed is impossible to detect as killaura.

**Comment by CeIebrimbor** [comment]
9/10 of those hits would have been blocked if Hitbox was canceling hits. The Killaura check is not the exclusive killaura blocking technique. It is 1 of _many_, including hitbox. Killaura these days is primarily there to quickly stop/kick multiaura and blatant clients where Hitbox and Heuristics pick up the softer (less effective) clients.
