### ISSUE TITLE
Ice Jump and Sprint False Positve

### ISSUE THREAD

**Issue by DasCanard** [konsolas/AAC-Issues#1051]
### Issue description

Report Video: https://streamable.com/uze25

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.4-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: PermissionsEx, WorldEdit, Essentials, EssentialsSpawn, Multiverse-Core, WorldGuard, ProtocolLib, AAC, AACAdditionPro, MineResetLite

### Special environment information
**ViaVersion version**: N/A (or N/A)

**ProtocolSupport version**: N/A (or N/A)

**ViaBackwards version**: N/A (or N/A)

**BungeeCord plugins**: N/A (or N/A)

### Configuration
Standard

**Comment by Janmm14** [comment]
Looks like a dupe of #933
