### ISSUE TITLE
Criticals false positive with boats

### ISSUE THREAD

**Issue by xDefcon** [konsolas/AAC-Issues#1052]
### Issue description
When a player is destroying a boat that is 1 block underneath him (see the video for better explanation) it is detected for criticals.

Video: https://dl.dropboxusercontent.com/s/u8226d7fdqcrj9x/2017-10-29_19-29-47.mp4
Logs: 
```
Tester failed Criticals: tried to do a mini-jump VL: +2 | 2
Tester failed Criticals: tried to do a mini-jump VL: +2 | 4
Tester failed Criticals: tried to do a mini-jump VL: +2 | 6
Tester failed Criticals: tried to do a mini-jump VL: +2 | 8
Tester failed Criticals: tried to do a mini-jump VL: +2 | 10
```
### Core information
**Server version**: 1.12

**AAC version**: 3.3.3, present also in 3.3.4

**ProtocolLib version**: latest

### Configuration
Replicable with default config.

**Comment by Slimerblue22** [comment]
No wonder this was flagged as critical as it involves a critical FP!...I'll go now
