### ISSUE TITLE
WallSpeed bypass

### ISSUE THREAD

**Issue by StronglyHoldTV** [konsolas/AAC-Issues#1054]
**Server version**: 1.8.8

**AAC version**: 3.3.4

**ProtocolLib version**: latest

**Plugin list**: AAC, ProtocolLib, AACAdditionPro
**Configuration**: default 

**Debug**: https://gist.github.com/StronglyHoldTV/59cff097da17bbcec57283f860d817a6#file-gistfile1-txt-L174-L531

**Comment by konsolas** [comment]
Debug log seems to be incomplete - data from speed check is absent.
