### ISSUE TITLE
Step bypass

### ISSUE THREAD

**Issue by StronglyHoldTV** [konsolas/AAC-Issues#1055]
Server version: 1.8.8

AAC version: 3.3.4

ProtocolLib version: latest

Plugin list: AAC, ProtocolLib, AACAdditionPro
Configuration: default

Debug: https://gist.github.com/StronglyHoldTV/0bd072a6285511bff46afd9694fc2dd2#file-step-bypass-aac-3-3-4-L204-L426

**Comment by Slimerblue22** [comment]
Can you link the client or a video?

**Comment by Janmm14** [comment]
Why should he? All required information is there.

**Comment by Slimerblue22** [comment]
I just thought the client with said bypass would be needed, if its not nvm then. Maybe I'm just putting too much info in mine idk

**Comment by Janmm14** [comment]
Well if there is a debug log provided, konsolas does not need the client, as he would just create a debug log with that to fix stuff based on that.

This is however just true for movement-related issues.

**Comment by konsolas** [comment]
Same issue as #1054 - debug log seems incomplete
