### ISSUE TITLE
[Feature-question] Limiting interact check

### ISSUE THREAD

**Issue by TheIronMinerLv** [konsolas/AAC-Issues#1056]
So I want to allow Schematica mod to work on my server. To do so I had to disable some checks. Now the problem is "interact check" - players now can use Schematica BUT they can with freecam open chests and place spawn eggs.. (cancel_ghost_block: false). Could I somehow only use ghost block check on chest opening and egg placement?

**Comment by Rerd** [comment]
Change `cancel_vl_place` to something very very high. Though this may allow placing spawn eggs through walls. Haven’t tested myself.

**Comment by konsolas** [comment]
cancel_vl_place refers only to block placements, so raising this would do what you want. 

Schematica behaves in a similar way to other fast building/griefing mods, so the interact check blocks it by default.
