### ISSUE TITLE
Killaura heuristic false positive

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#1057]
### Issue description
Video: https://youtu.be/3gO0TN2mySA
SpookyFueZ failed Heuristics: detected by pattern P/96 (confidence 79.1)

@konsolas 

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.4-b1

**ProtocolLib version**: 4.2.0

**Comment by Rerd** [comment]
Similar to #1038.

**Comment by iConfueZ** [comment]
I was trying Flux's AimAssist against a friend of mine (he was playing legit). I was fighting him for like 2 minutes, and I wasn't even detected at all and somehow he got detected by Heuristics by P/69 with a confidence of 93.2. Sadly don't have a video of that as he wasn't recording the fight and neither was I.

I guess there are some problems with P/96 and P/69?
