### ISSUE TITLE
Blockhitting FP

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1058]
[Video Here](https://youtu.be/3Q2oUtec2oE)

Gets extremely annoying in PvP. Happens to me all the time.

### Core information
**Server version**: PaperSpigot 1.8.8

**AAC version**: 3.3.4-b1

**ProtocolLib version**: 4.2.0

**Plugin list**: if requested

### Configuration
Custom config I made, though speed settings not changed other than thresholds.

**Comment by CeIebrimbor** [comment]
That is normal pvp behavior? 🤔 

I guess I personally find it hard to believe that a player would sprint/block/hit spam violently for 10+ seconds as a pvp tactic... I guess I will let you make your case... Is this common pvp?

**Comment by LinsaFTW** [comment]
Yeah its annoying... I fixed it by increasing the item scalar.

**Comment by Slimerblue22** [comment]
> That is normal pvp behavior? thinking

I guess I personally find it hard to believe that a player would sprint/block/hit spam violently for 10+ seconds as a pvp tactic... I guess I will let you make your case... Is this common pvp?
For me it is :P

**Comment by Janmm14** [comment]
@Slimerblue22 but it looks like it didn't flagged you for speed in your newest issue 1290, o i guess this can be closed?!

**Comment by Minemaniak** [comment]
I don't think this one is fixed, so why close @Janmm14 ? Maybe @Rerd could check if it is.

**Comment by Janmm14** [comment]
@minemaniak
Why you do not think it might be fixed if there is a video in issue 1290 that shows no problems with blockhitting?

**Comment by Minemaniak** [comment]
No verbose on test server - we don't know if he was getting any violations.
First time he was blockhitting, he was standing still - so not possible to be flagged by this issue.
Second time - blockhitting fight was short, there wasn't enough time to be setbacked maybe, and he was thrown in the air a few times, that could decrease his speed violations. This + no verbose means we don't know if issue happens.

**Comment by Rerd** [comment]
I will test this once I get home from my trip.
