### ISSUE TITLE
v3: Speed without jumping

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#106]
/speed 2.191 - 6.42s (20% faster than sprintjumping)
/speed 1 - 9.94s
/speed 1 & sprintjumping - 7.74s

Test length: 55 blocks

As you do not use the bukkit api to get the player's walkspeed, /speed can be used to test groundspeeds. I was able to higher the walkspeed up to 2.191 without setbacks and notifications (2.192 does both).

This means that increasing the player speed with /speed should be equal to only higher the player's walkspeed clientside.
This means that the simplest of all speeds is working: increasing player's walk speed.

**Comment by konsolas** [comment]
Need clarification what this is, and lots of it.

**Comment by Janmm14** [comment]
@konsolas Made description more clear, also see #80, I think thats the connection.

**Comment by konsolas** [comment]
Speed check now supports /speed. #80 is fixed, and this should be fixed too.
