### ISSUE TITLE
Squake WaterSpeed

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#1060]
Mod: https://minecraft.curseforge.com/projects/squake
Video: https://youtu.be/tw6bzX_jwpQ

### Core information
**Server version**: CraftBukkit version git-Spigot-65e8124-357b573 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**AAC version**: 3.3.4

**ProtocolLib version**: ProtocolLib v4.3.0

**Plugin list**:  Plugins (43): CoreProtect, PCore, Bosses, OpenI                                                                                        nv, ClearLag, ArmorStandEditor, HubRider, Votifier, TablistPrefix, Mult                                                                                        iverse-Core, Socket4MC, SkinsRestorer, KitsPlus, OldCombatMechanics, FastAsyncWo                                                                                        rldEdit, PluginCmdBlock, Heal, DiscordChat, PermissionsEx, MicroJump, ViaVersion                                                                                        , Vault, BankNotes, BungeeTabListPlus, MassiveCore, WorldEdit, SKMCPlugin, Essen                                                                                        tials, PassiveAddons, WorldGuard, ProtocolLib, AAC, SKAdminTool, Plan, Essential                                                                                        sChat, EssentialsAntiBuild, SuperVanish, ServerListPlus, EssentialsSpawn, AuthMe                                                                                        , HolographicDisplays, AuthMeBridge

### Special environment information
**ViaVersion version**: ViaVersion 1.3.0
**ProtocolSupport version**: insert (or N/A)

**ViaBackwards version**: insert (or N/A)

**BungeeCord plugins**: **On request**

**Comment by Janmm14** [comment]
Like with other plugin/mod compability requests, this will very likely not be directly supported inside AAC.

**Comment by Slimerblue22** [comment]
I'm not asking to add support for it, I'm saying part of the mod has a water speed type of thing which is like a water speed hack. Maybe I phrased it wrong

**Comment by Janmm14** [comment]
I did not heard the audio of the vid. Also the chat clearly shows that it is detected?!

**Comment by Slimerblue22** [comment]
It was detected some of the time, then sometimes it wasn't I thought I'd report it. If it isn't of importance feel free to close it

**Comment by Slimerblue22** [comment]
*Closing it due to importance  and inactivity*
*It isn't really anything to worry about and might as well remove it from the open issues to focus on whats important*
