### ISSUE TITLE
Climbing trap doors causes fly flag

### ISSUE THREAD

**Issue by eightbitx** [konsolas/AAC-Issues#1061]
### Issue description
Climbing a stack of trap doors by jumping and holding right click causes players to be flagged for Flying. Their violation level will continue to climb until they are kicked.

Player was playing 1.12.2

https://www.youtube.com/watch?v=aDWUmEmF4TM&feature=youtu.be

### Core information
**Server version**: git-Paper-1248

**AAC version**: 3.3.4-b1

**ProtocolLib version**: 4.4.0-SNAPSHOT-b390

**Plugin list**: https://imgur.com/KHVHK67

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: 2.3.1

**BungeeCord plugins**: N/A

### Configuration
Using Celebrimor's optimized config

**Comment by Janmm14** [comment]
Apparantly an issue in relation to the encapsulation shit in iava 9.
