### ISSUE TITLE
Falling after shulker wears off causes fly flag

### ISSUE THREAD

**Issue by SioWolf** [konsolas/AAC-Issues#1062]
### Issue description
Once the shulker effect wears off and you fall to the ground you accumulate fly violation points, it is possible to be kicked if you fall far enough. You also accumulate violation points for fly if you try to use a shulker while falling after the effect wears off.

Player was playing 1.12.2

https://www.youtube.com/watch?v=WkITmfr3eAA&feature=youtu.be

### Core information
**Server version**: git-Paper-1248

**AAC version**: 3.3.4-b1

**ProtocolLib version**: 4.4.0-SNAPSHOT-b390

**Plugin list**: https://imgur.com/KHVHK67

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: 2.3.1

**BungeeCord plugins**: N/A

### Configuration
Using Celebrimor's optimized config

**Comment by CeIebrimbor** [comment]
I think it's safe to say the **Levitation** potion effect is the culprit in general.
