### ISSUE TITLE
Velocity Bypass

### ISSUE THREAD

**Issue by MisterKraabs** [konsolas/AAC-Issues#1064]
### Issue description

Velocity Bypass für AAC (Reverse Velocity)

### Core information
**Server version**: Spigot-1.8.8

**AAC version**: 3.3.4-b1 (latest)

**ProtocolLib version**: 4.3.0

**Plugin list**: AAC,AACAdditionPro,AAD,Protocollib,SayNoToMcLeaks,NoCheatPlus

### Special environment information
**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

### Configuration
None Modifications

https://www.youtube.com/watch?v=U1IxPawS4b8

**Comment by Janmm14** [comment]
I do ask me again and again why people think they deserve support if they did not bought AAC.
