### ISSUE TITLE
Boating off a Cliff caused Fly flag

### ISSUE THREAD

**Issue by SioWolf** [konsolas/AAC-Issues#1068]
### Issue description
Driving a boat off a cliff causes player to get kicked for flying.

Player was playing 1.12.2

https://www.youtube.com/watch?v=HyJ-CaTsWU0

### Core information
**Server version**: git-Paper-1248

**AAC version**: 3.3.4-b1

**ProtocolLib version**: 4.4.0-SNAPSHOT-b390

**Plugin list**: https://imgur.com/KHVHK67

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: 2.3.1

**BungeeCord plugins**: N/A

### Configuration
Using Celebrimor's optimized config

**Comment by Slimerblue22** [comment]
This also happens with pigs and maybe horses

**Comment by FrankHeijden** [comment]
yes same issue here.
