### ISSUE TITLE
Fishing rod speed false pos

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#107]
If you "hit" someone with a fishing rod in mc 1.10 you can move him to you by hooking.
This will throw a lot of false positives for speed.

**Comment by Photon-GitHub** [comment]
This can also trigger fly (hook from above) or criticals (hook from a certain angle)

**Comment by konsolas** [comment]
Fixed, confirmed by Rqcco and Janmm14.
