### ISSUE TITLE
[bug] AAC kicks for hitbox when farming blazes (Check out the enchantments on the player)

### ISSUE THREAD

**Issue by FrozenBeard** [konsolas/AAC-Issues#1070]
players are being kicked for hitbox when they farm blazes, please look at the enchantments on the player and the effects on the player too. 

https://www.youtube.com/watch?v=TBnPg0NqYt0

Possible dupe of #1034

**Comment by CeIebrimbor** [comment]
Yes, duplicate. The video is helpful, but this is more so a blatant bug(not really needing video) because a new version of Hitbox did not account for vanilla hit mechanics (hitting groups of mobs).
