### ISSUE TITLE
Killaura Heuristics FP

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1071]
Video: [Click](https://youtu.be/EYIQYYkBxew)

I've had to exempt patters:
70
71
72
74
75
76
79

### Configuration
Custom Config. Confidence set to 75%

**Comment by Janmm14** [comment]
AAC version?

**Comment by CeIebrimbor** [comment]
Looks like 7 needs a review...

**Comment by Rerd** [comment]
AAC Version 3.3.4-b1

**Comment by CeIebrimbor** [comment]
Hmm, video suggests (1)you have NoHitDelay of some form(because it's clear it's not 1.9+) because you can hit 2 targets in the same 1/4 second timeframe and (2) we once again have a report of AFK dummies backed into a corner causing violations(something that never happens in real PvP).

If you have NoHitDelay, can you get these violations without it running?

**Comment by Rerd** [comment]
1. There is no NoHitDelay plugin installed.
2. This is possible to do without AFK lifeless players as I have experienced false positives during actually fights with two or more people and constantly changing targets.

**Comment by Rerd** [comment]
New issues I’ve found while testing on my server.
Patterns 62, 63 and 65 have falsely flagged my players.
Screenshot of logs (https://gyazo.com/25eae6e888d0204c43f4fcfc92455bb9)

**Comment by Janmm14** [comment]
I suggest to set the confidence in the config above  78. This will add more measurements and should reduce false positives.

**Comment by Rerd** [comment]
Well then it completely misses out on Flux’s Killaura which I don’t want.

**Comment by konsolas** [comment]
Obviously I can't properly test this, but modifications were made to the patterns you specified to improve detection accuracy.

**Comment by Rerd** [comment]
Please re-open as this is still not fixed, 8 seconds of testing by flinging my head causes pattern 77 to be set off.

**Comment by Janmm14** [comment]
maybe just do normal fighting?

**Comment by Rerd** [comment]
I experienced it in normal combat. I think konsolas should’ve tweaked all of the 7x patterns instead of the ones only I listed as it seems like all of them used to be having issues. The ones he have fixed seem to not be falsely occurring anymore.

**Comment by Rerd** [comment]
One time was 76.5% confidence and the other was 78%.
