### ISSUE TITLE
Phase kick error

### ISSUE THREAD

**Issue by lucas2107** [konsolas/AAC-Issues#1073]
### Issue description
This issue happened when a player was kicked for Phase.
https://hastebin.com/pocaximuxo.md

I think my TAB plugin can cause this but I'm not sure, I'm reporting this error to the author of tab plugin too.

### Core information
**Server version**: Paperspigot 1.8.8

**AAC version**: 3.3.4-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: http://prntscr.com/h9f7rs

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
https://hastebin.com/eceyasanuh.bash

**Comment by Photon-GitHub** [comment]
The first error is definitely a problem of the tab plugin, the second one might be caused by it as well.

**Comment by konsolas** [comment]
3.3.7-b1 (not the tab list one)
