### ISSUE TITLE
FastBow false positives

### ISSUE THREAD

**Issue by crimilo** [konsolas/AAC-Issues#1074]
### Issue description
~~False Positive 1: Run on the ice and jump, get kicked for Speed.~~

False Positive 2: Shoot fast arrows, get kicked for FastBow.

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.4-b1

**ProtocolLib version**: 4.3.0

**ViaVersion version**: 1.3.0

Please, FIX this 2 FP's and you will got 5 stars review!

**Comment by Slimerblue22** [comment]
The fastbow FP idk a real fix for it, I just turn it off and normally the other checks handle fast bow hacks. As for the ice thing its already reported

**Comment by Rerd** [comment]
Here, I have a temporary fastbow fix if anyone needs it:
https://gyazo.com/d06132c1bc0152726c613d6bd3c49620

**Comment by konsolas** [comment]
Default config update fixed this in 3.3.8
