### ISSUE TITLE
Regen FP (+1.11.2)

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#1076]
Server log: https://hastebin.com/ujexaqipih.sql
AAC log: https://hastebin.com/saqikiyipu.sql
Video: https://youtu.be/ZYDO5og6tQY

Latest ViaVersion

**Comment by Rerd** [comment]
Can you provide steps on how to make this false positive occur? Maybe even a video? Also please state the actual version of ViaVersion and AAC instead of putting “Latest”

**Comment by Hyronymos** [comment]
The Server log shows which Version of AAC we use. Why should I write the exact version instead of simply latest? I only added "Latest ViaVersion" because we use ViaVersion as Bungeecord Plugin.

**Comment by Slimerblue22** [comment]
Well @Hyronymos At the time it might be latest, if this is checked say 2 months later and maybe 2 newer versions are out we might think this happened on the newer version and not the one it did happen on (I'm not completely sure what I said makes any seance but Im going with it)

**Comment by Slimerblue22** [comment]
Wait in the log it says the server is starting in 1.8.8? But this is about 1.11.2 regen?

**Comment by Hyronymos** [comment]
1.11.2 clients

**Comment by Slimerblue22** [comment]
Is via-version set up correctly?

**Comment by Hyronymos** [comment]
Video: https://youtu.be/ZYDO5og6tQY

**Comment by Rerd** [comment]
He's most likely cheating. The way his head moves at 00:34 and the way he moves at 00:59 makes me believe he is cheating.

**Comment by Hyronymos** [comment]
Pls leave this to the dev

**Comment by Rerd** [comment]
Well we shouldn't waste the dev's time with issues that are invalid.

**Comment by Janmm14** [comment]
other popular servers do not have any reported problems with regen on specific clients, maybe you use some incompatible version bridge plugin, since viaversion seems absent

**Comment by Hyronymos** [comment]
Please don't forget that no one plays 1.11

**Comment by Rerd** [comment]
@Hyronymos as stated on the [ViaVersion Spigot page](https://www.spigotmc.org/resources/viaversion.19254/), `The spigot version is recommended over Bungee, why? There are currently some anti-cheat issues with the Bungee version (though if this isn't a problem, use it!)`

Please use the spigot version of ViaVersion.
