### ISSUE TITLE
AAC API Question

### ISSUE THREAD

**Issue by TheCactus7** [konsolas/AAC-Issues#1077]
hello,

i am trying to execute certain actions on a violation level like the configuration does. so vl50 will for example execute staff notify.

now i try it with api 
if (e.getHackType() == HackType.KILLAURA && vl >= 30 &) {
here is the p.sendmessage if the player has aac.notify
}

but it spams my chat when i call playervioevent.
how do i make it so it executes a action above vl 30 like the config only once?

**Comment by Janmm14** [comment]
Check that the current violation level of the player is below x and that it is above x with the vl of the event added.

**Comment by TheCactus7** [comment]
so like
if (e.getHackType() == HackType.KILLAURA && vl >= 30 && vl <=40) { 
?
Because it will still send you multiple notifications or may even skip the vl due to multiplier.

no way to make it so when it reaches 30 or above it executes it once? and same for 50, 70 like config?

**Comment by Janmm14** [comment]
No.
Use the API to get the VL of a player:
```java
int previousVl = AACAPIProvider.getAPI().getViolationLevel(player, hackType);
```
Then the if would be like:
```java
if (previousVl < 30 && vl >= 30) {
    //...
}
```

**Comment by Photon-GitHub** [comment]
Assuming this is clear I will close this. Reopen if necessary.
