### ISSUE TITLE
Carpet Bug

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#108]
Carpets in general seem really buggy. When you  jump from a block to another block that has carpet, while sneaking causes speed/fly flags.

**Comment by Janmm14** [comment]
The issue is about block edges. You fixed it for normal blocks, but you need to adapt your fix also to other blocks like carpets, half-sleps, beds, repeaters, trapdoors (I think you got the category of blocks I mean), partly I think also stairs.

**Comment by konsolas** [comment]
Fixed, confirmed by Rqcco.

**Comment by Janmm14** [comment]
The carpet-block edge bug also exists for various other blocks!

Tested with:
* enchanting table
* end rod
* chest
* bed
* trapdoor
* half slep
* repeater / comparators
* end portal
* All snow layers (even slow layer 1 that doesn't modify height)
* daylight detector

**I thikn it exists for all blocks if you magane to jump at that one point where the outline just ended. I think its not bound to blocks that have full 1-block-length**
