### ISSUE TITLE
[glitch] Cant open trap door under you

### ISSUE THREAD

**Issue by FrozenBeard** [konsolas/AAC-Issues#1080]
https://www.youtube.com/watch?v=A7BJJqq4GDo
Simply stand on top of a closed trap door and try to open it so you will fall down. This bug will most likely happen.

**Comment by CeIebrimbor** [comment]
Please use the report template. Some issues are straightforward enough to just post a video, but this is not one...

**Comment by Janmm14** [comment]
For moving issues, an aac debug log additionally to the usual report template answers can help to find potential issues faster.

**Comment by CeIebrimbor** [comment]
Closed until someone provides AAC detection verbose or a debug log. We waited long enough for more info or other users to back this claim (we don't even know what check is at fault).
