### ISSUE TITLE
[ghost block] Gitch trapping players

### ISSUE THREAD

**Issue by FrozenBeard** [konsolas/AAC-Issues#1081]
Effects currently active: Haste 2
Tools And Effects:
Diamond Pickaxe with:
Efficiency 5
Silk Touch
Unbreaking 3
Mending

https://www.youtube.com/watch?v=D7XzgZKKGyQ

How often it occurs: Often. More present with faster mining tools. Is repeatable with any tool. 

The block, instead of breaking, breaks client side but server side remains. While other players can see the block, the player who created the ghost block cannot. This causes them to be whip-lashed around, and get stuck. If they are sieging someone and trying to dig in, this happens a lot. It will eventually kick the player, making them loose the siege and loose their items.

**Comment by Slimerblue22** [comment]
The ghost block isn't caused by AAC but if the player is stuck in it then AAC will start adding up VL for phase.

**Comment by CeIebrimbor** [comment]
This is a server/client bug, not AAC (or anything AAC can fix). When breaking blocks at insane speeds, the client and server do not keep up with each other and the client thinks it broke a block, but the server still has a solid block there. AAC listens to the server...so the player is seen as phasing.

This is the primary reason that AAC does not kick for Phase. Try out the /aacchunkrestore command after 5-10 VL. That may help.
