### ISSUE TITLE
Bypass the Wurst 6.15 timer, fastladder hack

### ISSUE THREAD

**Issue by mckite** [konsolas/AAC-Issues#1088]
Bypass the Wurst 6.15 timer, fastladder hack

### Core information
**Server version**: insert 1.8.8

**AAC version**: insert
3.3.4
**ProtocolLib version**: insert
4.3
**Plugin list**: insert
AAC , ProtocolSupport , Massivelag, Authme , Essentials, ect, Not affectred
### Special environment information
**ViaVersion version**: 
N/A
**ProtocolSupport version**:
4.23
**ViaBackwards version**: 
N/A
**BungeeCord plugins**: 
N/A

**Comment by Janmm14** [comment]
As a little note: you are supposed to replace the "insert" of the template and also supposed to remove the informative text blocks of the template.

**Comment by mckite** [comment]
others N/A
