### ISSUE TITLE
Add more AAC commands

### ISSUE THREAD

**Issue by jiangdashao** [konsolas/AAC-Issues#1089]
### Issue description
I suggest add these commands
I think they are useful

**/aacvl command:**
 /aacvl (player) (check) (VL) - Change Player's VL
 for example,i use /aacvl xxx KillAura -10,then xxx 's KillAura VL will reduce 10
This command can be used in condition commands
check players' condition,and then change his vl

**/aacverbose command:**
add this command so that we can easily toggle verbose

**/aactoggle (Check)** -  Enable / disable a check

**/aacbypass (Player) (Check) (on/off)** - Controls whether the player bypasses a check]
And this bypassing is not permanent, and will automatically expire after the player quit the server

You might think we can use AAC API,But most of AAC users are not developers
And adding these commands will make us configure AAC more powerful

**Comment by jiangdashao** [comment]
Post again,edited some words:

Issue description

I suggest add these commands
I think they are useful

/aacvl command:
/aacvl <Player> <Check> <VL>- Change Player's VL
for example,i use /aacvl xxx KillAura -10,then xxx 's KillAura VL will reduce 10
This command can be used in condition commands
check players' condition,and then change his vl

/aacverbose command:
add this command so that we can easily toggle verbose

/aactoggle <Check>- Enable / disable a check

/aacbypass <Player> <Check> (on/off) - Controls whether the player bypasses a check]
And this bypassing is not permanent, and will automatically expire after the player quit the server

You might think we can use AAC API,But most of AAC users are not developers
And adding these commands will make us configure AAC more powerful

**Comment by Janmm14** [comment]
I will maybe create an external plugin with /aacvl, /aactoggle and /aacbypass.

/aacverbose already exists, you need enable it in the config (remove the # at start) and then you can use permissions and that command to toggle it.

**Comment by Janmm14** [comment]
Also verbose and checks can already be toggled in /aacadmin

**Comment by konsolas** [comment]
/aacverbose already exists
/aactoggle is doable via the GUI
/aacbypass can be done with any permission plugin
/aacvl isn't hugely useful because of how fast violation levels change in AAC.

**Comment by Minemaniak** [comment]
/aacvl would be useful to put in config if we want notify and setbacks but not kicks, without it after maximum defined VL there are no more notifications. With this command, we could reset it at the highest threshold.

**Comment by Janmm14** [comment]
VLs go down automatically, by time and/or by legit actions, depending on the specific check.

**Comment by Minemaniak** [comment]
I know that, but if someone is gathering them constantly he will eventualy stop sending warnings. I had such situation yesterday, a guy with few thousand fly VL's.

**Comment by CeIebrimbor** [comment]
> I know that, but if someone is gathering them constantly he will eventualy stop sending warnings. I had such situation yesterday, a guy with few thousand fly VL's.

Put in a perm ban threshold at a higher threshold. So if your kick is 500, ban on 2000.

**Comment by Janmm14** [comment]
(In that cade a quick check in /aacadmin's vl oberview will likely show you him on the first position with a really big fly vl)
