### ISSUE TITLE
NoWeb

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#109]
NoWeb Still works with Wurst, You can't be sprinting though.

**Comment by Janmm14** [comment]
only works when soulsand is below, else you're going too fast with noweb form wurst

**Comment by MinecraftiUndCo** [comment]
I created a video of that to illustrate the bypass. [https://www.youtube.com/watch?v=30lmXTYtoV4&feature=youtu.be](url)

**Comment by konsolas** [comment]
Closing in favour of the more detailed #117
