### ISSUE TITLE
Problem with the CAA, multiple catastrophic failures

### ISSUE THREAD

**Issue by xXLoloGameplayXx** [konsolas/AAC-Issues#1092]

**Comment by xXLoloGameplayXx** [comment]
Hi. I bought the AAC a while ago because it's worth buying, but ... when I install the latest version of the AAC it does not start error, anyway. I installed an old version, and the problem is that it generates many errors, every two times three, it kills players, of course using hacks, anyway. If you need server information, it's Mc.UltraCraft. It's compatible from 1.8 to 1.12.

**Comment by CeIebrimbor** [comment]
What version of Spigot and what version of ProtocolLib?

**Comment by xXLoloGameplayXx** [comment]
Sorry, already works, update the protocollib.
