### ISSUE TITLE
Killaura Heuristics FPs (pt 2)

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1095]
Having issues with patterns 72, 73, 77 and 79. This time with much higher confidence such as 80%+. Related to #1071. I didn’t list these ones on the list I gave in the previous issue so they weren’t fixed, although they do need tweaking.

**Comment by CeIebrimbor** [comment]
Videos of reproduced detection?

**Comment by Rerd** [comment]
Exactly the same as the previous video. Happens in normal combat mostly when fighting 2 or more people. Sometimes happens when players do legitimate head snaps which good players do.

**Comment by konsolas** [comment]
3.3.6 will have adjustments to the listed patterns.
