### ISSUE TITLE
Interact (bedfucker), Step & Spider Nofall 

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#1096]
Video (Interact (bedfucker) bypass): https://www.youtube.com/watch?v=lputD74DzQc
Another Video: https://www.youtube.com/watch?v=n4Tz5tHKZZQ&feature=youtu.be

Log: https://hastebin.com/wovigahabi.sql
AAC-Log: https://hastebin.com/zepijemana.sql

**Comment by konsolas** [comment]
....

**Comment by Hyronymos** [comment]
What do you need more? AAC Debug? Some tests on the official AAC Server? (Client ist not public)

**Comment by konsolas** [comment]
The title contains 5 different bypasses, the log only seems to contain the bedfucker.

**Comment by Hyronymos** [comment]
"Item Teleport" is fixed since 3.3.6

Another Log of Bedfucker, Step & Spider Nofall: https://hastebin.com/ojukovohik.sql

Step works without any flags (only some after like +10 blocks)

**Comment by Hyronymos** [comment]
@konsolas all 3 bypasses?

**Comment by Janmm14** [comment]
@Hyronymos *4

**Comment by Janmm14** [comment]
(superhit not fixed, will come soon)
