### ISSUE TITLE
Killaura Heuristic FPs

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#1097]
1. Video (pattern P/72 (confidence 81,2 (67,7 - max 82,0))): https://youtu.be/NmaeojWS6cU
2. Video (pattern P/66 (confidence 78,0 (64,7 - max 78,0))): https://youtu.be/PbED_elAobA

Log of Player 1: https://hastebin.com/jafiveteke.hs
Log of Player 2: https://hastebin.com/tapukujehe.hs

Another Player with the same Problem (No Video but 100% legit): https://hastebin.com/rizaroyosu.hs
Another Player #2 with the Problem (No Video but 100% legit): https://hastebin.com/izazeciguy.pas

AAC version: 3.3.5-b1
ProtocolLib version: 4.3.0

We currently ban at confidence of 75 (default)

**Comment by Rerd** [comment]
Pattern 72 has been fixed.

**Comment by Hyronymos** [comment]
nope
