### ISSUE TITLE
Add a Heuristic Event in API | Add Heuristic Accuracy/Pattern Placeholder

### ISSUE THREAD

**Issue by jiangdashao** [konsolas/AAC-Issues#1098]
### Issue description
I suggest add a heuristic event in api and add heuristic Accuracy/Pattern placeholder for Heuristic Check

~~Event:~~
~~double getAccuracy~~
~~int getPattern~~
~~Player getPlayer~~

Placeholder for Heuristic check:
%accuracy% - show Accuracy
%pattern% - show pattern

**Comment by konsolas** [comment]
The pattern and confidence can be parsed from PlayerViolationEvent#getMessage

**Comment by Janmm14** [comment]
(Specific placeholders for the variables of certain checks will not be added to AAC)

**Comment by konsolas** [comment]
@Janmm14 is right in saying that placeholders cannot realistically be made specific to a certain check, because they're usable in the command lists of all checks: a command may be executed when there is no accuracy or pattern placeholder available.
