### ISSUE TITLE
Players Stuck in farmland

### ISSUE THREAD

**Issue by lucas2107** [konsolas/AAC-Issues#1099]
### Core information
**Server version**: Paperspigot 1.8.8

**AAC version**: 3.3.6

**ProtocolLib version**: 4.3.0 (I think)

**Plugin list**: AAC, Essentials

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Default Config

###Bug
When a player move in a farmland, he's kicked for fly. (Client version: 1.10+)

**Comment by lucas2107** [comment]
#922

**Comment by konsolas** [comment]
Closing as a duplicate of #922
