### ISSUE TITLE
onPacketReceiving(PacketEvent)

### ISSUE THREAD

**Issue by zBoringDrop** [konsolas/AAC-Issues#1100]
Hi, randomly in console i saw this today:
https://pastebin.com/R2jisNBT

I use last protocollib and 3.3.5 aac version.

**Comment by CeIebrimbor** [comment]
Confirmed on 1.12.2 Paper w/ ProtocolLib 4.4.0 b389

**Comment by zBoringDrop** [comment]
No, i due spigot 1.12

**Comment by zBoringDrop** [comment]
Use*

**Comment by CeIebrimbor** [comment]
> No, i use spigot 1.12

Understood. Just confirming...

**Comment by Hyronymos** [comment]
Problem on 1.8.9 SPIGOT too

**Comment by Toshka17** [comment]
Add critical label...

**Comment by Toshka17** [comment]
Does not fixed
https://pastebin.com/DS70Pnnr

**Comment by Janmm14** [comment]
@Toshka17
Different issues please in a new issue.
