### ISSUE TITLE
Elytra fp with rockets

### ISSUE THREAD

**Issue by wulfwuud** [konsolas/AAC-Issues#1102]
**Info**
https://streamable.com/99obj

**Server version**: 
git-Paper-1104 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**AAC version**: 
3.3.6

**ProtocolLib version**: 
4.3.0

**Plugin list**: 
Permsplugin AAC Protocollib WE Viaversion

### Special environment information
**ViaVersion version**:
1.3.0

### Configuration
default

**Comment by LogGits** [comment]
I am also getting this issue. Players are reporting getting glitch into blocks when they have elytra on and tp. When they tp or warp they get trapped and even go through blocks. It tells me that they could be phase hacking and it sends them a message saying "Are you stuck in a glitched block? Consider re-logging". Im on paper 1.12.2. Using AAC version 3.3.6 and Celebrimbor's config.

**Comment by Janmm14** [comment]
@LogGits Please create a new issue and maybe ask celebrimbor for how to create a debug log, those are usually really helpful with movement-related issues.

**Comment by CeIebrimbor** [comment]
> I am also getting this issue. Players are reporting getting glitch into blocks when they have elytra on and tp. When they tp or warp they get trapped and even go through blocks. It tells me that they could be phase hacking and it sends them a message saying "Are you stuck in a glitched block? Consider re-logging". Im on paper 1.12.2. Using AAC version 3.3.6 and Celebrimbor's config.

Separate issue as it related to Phase and being sucked into blocks. It is tied to your #1104.
