### ISSUE TITLE
Phase bug after 3.3.5

### ISSUE THREAD

**Issue by JuliCarles** [konsolas/AAC-Issues#1103]
### Issue description
After updating to the latest version a bug was discovered.
Players are able to go through blocks that are meant to be indestructible.
This can be seriously noticed within any mini game that works with cages. (E.g Skywars, Eggwars).

Here's a video to prove it:
https://youtu.be/VJgllFDJrfI

Two debug logs in case it's needed:
https://mega.nz/#!lB1nFRYT!ZjTvUhoPoe5XH_fai1g8Hpt-VuMW5cb-OxUuu2Z5ABY
MEGA Download.

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.5/6

**ProtocolLib version**: 4.2.0

**Plugin list**: Ask if needed.

### Special environment information
**ViaVersion version**: Latest.

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: Ask if needed.

### Configuration
Celebrimbor modifications.

**Comment by CeIebrimbor** [comment]
Likely aftermath or patching #919, but be cautious not to reintroduce #830...
