### ISSUE TITLE
Error occurred while enabling AAC v3.3.6

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1107]
### Issue description

Had this occur during one of our server startups. Happens once out of 10 times, very weird.
https://pastebin.com/raw/d5et7YV7

### Core information
**Server version**: 1.12.2 - Spigot Build 1468

**AAC version**: 3.3.6
**AAC config**: 3.3.6|1-Default-Celebrimbor

**ProtocolLib version**: 4.3.0 Build 390

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Janmm14** [comment]
maybe try updating java

**Comment by andrewkm** [comment]
@janmm14 that does not help me.
I am running Java 8 u151/152 which is the latest.
Java 9 shouldn’t yet be used with MC servers.
