### ISSUE TITLE
SnowYPort - SnowSpeed - AAC 3.3.6

### ISSUE THREAD

**Issue by Monstercide** [konsolas/AAC-Issues#1108]
### Core information
**Server version**: AAC 3.3.6

**AAC version**: AAC 3.3.6

**ProtocolLib version**: Latest

**Plugin list**: EVERYTHING

Comment: you can use yport and speed and fast speed on snow!

**Comment by Rerd** [comment]
Server version is referencing the actual version of Minecraft your server is running (1.8, 1.9, 1.10, etc.)

“EVERYTHING” isn’t a valid answer for your list of plugins.

Also, is there any specific client that you used? Maybe a video or some aac logs via /aacdebug?

**Comment by Slimerblue22** [comment]
I've seen a few videos about this but haven't tested anything myself, here is one of the videos I found https://www.youtube.com/watch?v=Vz4EFDK_Bes

**Comment by konsolas** [comment]
Closing due to insufficient information.
