### ISSUE TITLE
Unhandled exception number 32 occured in onPacketReceiving(PacketEvent) for AAC

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1111]
### Issue description

New bug happening as of latest AAC. Haven't seen this one before.
https://pastebin.com/raw/K4CYnTTu

### Core information
**Server version**: 1.12.2 - Spigot Build 1468

**AAC version**: 3.3.7
**AAC config**: 3.3.7|1-Default-Celebrimbor

**ProtocolLib version**: 4.3.0 Build 390

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by andrewkm** [comment]
Awww shit just noticed, issue number 11:11
I win an internet.

**Comment by konsolas** [comment]
3.3.7-b1
