### ISSUE TITLE
Depth Strider III + SkillAPI

### ISSUE THREAD

**Issue by Jnxd1** [konsolas/AAC-Issues#1115]
## **Update:**
 - ### **Core Test Results**
_This test was done on a clean test server. Core info on the server bellow._

**AAC Log // Depth Strider 3 & Speed 2 Pot:** https://hastebin.com/menitahefa.hs
**AAC Full Log // Full Duration of the Test:** https://hastebin.com/kasitupiya.sql
Hard to give any specific info on the reproduce process. ACC barely got activated when using Depth Strider 1 & Depth Strider 2, that is with and without speed pots. It is also hard to reproduce.
But the real deal is Depth Strider 3 and speed 2 pot.

_**Conclusion**_
It is harder to reproduce it on the "clean" server.
On my public server i have some mechanics in work that also increase the speed of the player by default without any pots. I guess that this helps partially to increase the detection issue. ___And___ if i was able to reproduce it on the "clean" server that means that these mechanics just helps AAC to be activated faster.

 - ### **Secondary Test Results**
**AAC Full Log // Using PaperSpigot Same Server:** https://hastebin.com/uhetovequh.sql
Also did this one just because i had a chance changing the server.jar and possibly getting more info etc.

## **Core information**

**Server version:** Spigot 1.8.8 Build # 46 (Final 1.8.8 Version)

**AAC version:** 3.3.7-b2

**ProtocolLib version:** 4.4.0-SNAPSHOT-b390

**Plugin list:** Vault, ProtocolLib, AAC, ConditionalCommands, Essentials, EssentialsProtect, EssentialsSpawn, EssentialsGeoIP, EssentialsChat

### **Special environment information**

**ViaVersion version:** N/A

**ProtocolSupport version:** N/A

**ViaBackwards version:** N/A

**BungeeCord plugins:** N/A

### **Configuration**

Default configoration used from Celebrimbor - Optimized Config AAC v3.3.7 | 1

**Comment by CeIebrimbor** [comment]
I continue to believe that this is a ViaVersion bug, since there would be a massive outcry if Depth Strider was 100% unusable. Do you have an environment to test on vanilla 1.8.8 (Spigot 1.8.8)? Provide logs?

Last time the Dev (and myself) tested Depth Strider in many ways with different enchant levels and speed potions, there were not detections. Also, I run a 1.12.2 server and haven't heard a peep. 😢

**Comment by Jnxd1** [comment]
1. I don't run Bungee.

2. It doesn't matter if he eats or not. So no.

3. Yes i do.

**Comment by CeIebrimbor** [comment]
Pending data from standard Spigot server.

**Comment by Jnxd1** [comment]
## **Update:**
 - ### **Core Test Results**
_This test was done on a clean test server. Core info on the server bellow._

**AAC Log // Depth Strider 3 & Speed 2 Pot:** https://hastebin.com/menitahefa.hs
**AAC Full Log // Full Duration of the Test:** https://hastebin.com/kasitupiya.sql
Hard to give any specific info on the reproduce process. ACC barely got activated when using Depth Strider 1 & Depth Strider 2, that is with and without speed pots. It is also hard to reproduce.
But the real deal is Depth Strider 3 and speed 2 pot.

_**Conclusion**_
It is harder to reproduce it on the "clean" server.
On my public server i have some mechanics in work that also increase the speed of the player by default without any pots. I guess that this helps partially to increase the detection issue. ___And___ if i was able to reproduce it on the "clean" server that means that these mechanics just helps AAC to be activated faster.

 - ### **Secondary Test Results**
**AAC Full Log // Using PaperSpigot Same Server:** https://hastebin.com/uhetovequh.sql
Also did this one just because i had a chance changing the server.jar and possibly getting more info etc.


## **Core information**

**Server version:** Spigot 1.8.8 Build # 46 (Final 1.8.8 Version)

**AAC version:** 3.3.7-b2

**ProtocolLib version:** 4.4.0-SNAPSHOT-b390

**Plugin list:** Vault, ProtocolLib, AAC, ConditionalCommands, Essentials, EssentialsProtect, EssentialsSpawn, EssentialsGeoIP, EssentialsChat

### **Special environment information**

**ViaVersion version:** N/A

**ProtocolSupport version:** N/A

**ViaBackwards version:** N/A

**BungeeCord plugins:** N/A

### **Configuration**

Default configoration used from Celebrimbor - Optimized Config AAC v3.3.7 | 1

**Comment by Janmm14** [comment]
How do you increase the player speed on your server?

**Comment by Jnxd1** [comment]
Using [SkillApi](https://www.spigotmc.org/resources/skillapi.4824/) , made my own few skills and one of them is passive skill giving speed potion effect with around +1.3 modifier on default _(a bit higher than Speed 1 Pot)_.

**Comment by Jnxd1** [comment]
It would be so cool if AAC had a hook for SkillAPI.
How would that work? Not, not sure if SkillAPI has to hook in AAC or AAC to SkillAPI.

**Comment by CeIebrimbor** [comment]
> Using SkillApi

Seems like a very relevant bit of information to leave out... 😅

**Comment by Janmm14** [comment]
SkillAPI apparantly has no hook to AAC.

**Comment by Jnxd1** [comment]
It is not only issue of SkillAPI.
The test results shown above, are done on server without it, and the issue is still current.
Using speed pots and depth strider 3, on a spigot server will provoke AAC to miscount as a "hack".

**Comment by Jnxd1** [comment]
@CeIebrimbor Like i said, i'm using SkillAPI to change the movement speed of the player by default.
Idk how much clear i can be on that, but if you want/need any more info on it, tell me what and i can provide it.
In simple words, it is applying movement speed potion effect to the player on infinite loop with about +1.3~4 multiplier than the base player speed _(it is a bit higher than Speed 1 Potion)_.

**Comment by CeIebrimbor** [comment]
It was simply a comment on how you didn't include that in the initial report. I deleted comments and cleaned up this report after finding that out.

I would still list it as "compatibility" since Depth Strider III is not a vanilla enchant. So I guess you can call it compatibility x2 🤷‍♂️

**Comment by Janmm14** [comment]
@Jnxd1 
There is no possibility of applying 1.3 strength of a potion. What is likely happening is that the plugin is modifying the base movement speed for certain players (similar to /walkspeed from essentials).
The question is now how it is done.

**Comment by Jnxd1** [comment]
@Janmm14 Agree on that.
Still i think we got a bit off point. Just forget the SkillAPI plugin, let's get back to the test that i ran and the results that i had on the Spigot 1.8.8 Build # 46 server. As you can see there i have listed the plugins. Nothing else was for the test except Speed 2 Potion and Depth Strider 3 and AAC got that as an fly-movement "hack".

**Comment by w-o-a-h** [comment]
Depth Strider III is a vanilla enchant... @CeIebrimbor

**Comment by CeIebrimbor** [comment]
Oops, my bad. Thought it was I-II

**Comment by CeIebrimbor** [comment]
I want to say it's the same issue as 1281. If 1281 being patched in 3.3.13 does not solve it, then this can be re-opened, given there is new supporting data.
