### ISSUE TITLE
Memory leak with unloaded worlds [AAC 3.3.7-b2]

### ISSUE THREAD

**Issue by RaynLegends** [konsolas/AAC-Issues#1116]
### Issue description
It's back! Literally the same as #1114 but in another class (And this time under AAC-LogWriter thread).

https://imgur.com/a/mEqyh

UPDATE: Turns out I was using AAC 3.3.7-b1, I've updated to AAC 3.3.7-b2 and now I got exactly the same issue as #1114, under the same thread but in another class (Possibly the same but with a different name because of obfuscation)
I added an updated screenshot to the album (last image)

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 3.3.7-b2

**ProtocolLib version**: 4.3.1-SNAPSHOT-b378

**Plugin list**: AAC, ProtocolLib, ViaVersion, and a lot of proprietary plugins (but that's not relevant, they are not holding the references)

### Special environment information
**ViaVersion version**: 1.3.0

**Comment by Janmm14** [comment]
this array of issues should end some time :/

**Comment by RaynLegends** [comment]
Yeah. BTW I'm not actually 100% sure of this one, I should be able to confirm/close it tomorrow.

**Comment by Jnxd1** [comment]
I'm having some strange crashes on the server for the last 4-5 days. I'm trying to remember if is it then when i updated to AAC 3.3.7+, but right now i can't. And i'm trying to locate the issue of these crashes.
The server simply runs out of memory and it has quite enough (8G), with minimum amount of players.
Can this be the issue that i'm looking for?

**Comment by Janmm14** [comment]
@jnxd1This issue is happening if a server is unloading many worlds.

**Comment by RaynLegends** [comment]
It could be, if you've a large enough draw distance or you frequently unload worlds, but issues similar to this one are present since I don't know how many versions (possibly since forever but they've never been reported), it's really unlikely to be causing problems if you haven't had any problem before using this particular version.

**Comment by Jnxd1** [comment]
@RaynLegends I see.., thanks for the clarification. I will try and check on that with the older version that i had and if i see any results i will check back with more info.
Cheers!

**Comment by RaynLegends** [comment]
Updated the post, I had AAC 3.3.7-b1 but the issue is present also in -b2.

**Comment by lucas2107** [comment]
I've a memory leak till 3.3.7-b1 too.
Idk how this is happening, but after 10 hours, server reach 100% of 16GB.
Server version: PaperSpigot 1.8.8

**Comment by Janmm14** [comment]
@lucas2107 That does not help us.
Are your plugins fiddling with loading and unloading of worlds?
What you can to at debugging a memory leak is providing a heap dump of the process. (Google is your friend xd)

**Comment by Pluginsel** [comment]
@konsolas When is will fixed?
