### ISSUE TITLE
Explosions trigger hitbox check

### ISSUE THREAD

**Issue by Sprax2013** [konsolas/AAC-Issues#1117]
### Issue description
I'm creating an explosion using following code:
`((CraftWorld) coal.getWorld()).getHandle().createExplosion(((CraftPlayer) e.getPlayer()).getHandle(), x, y, z, 4, false, false);`

Spawning the explosion like this instead of simply using
`Bukkit.getWorld("world").createExplosion(x, y, z, 4, false, false);`
will set the damager to `e.getPlayer()` instead of `null` because the server thinks the player has caused the explosion. Should be the same method when a player is setting a block of TNT on fire.

It does work but AAC is messaging me (the `e.getPlayer()`)

> [AntiCheat] [CONSOLE] Sprax2013 in Ruine is suspected for Killaura (Hitbox) (ping = 29, tps = 19.61)
> [AntiCheat] [CONSOLE] Sprax2013 in Ruine is suspected for Killaura (Hitbox) #2 (ping = 26, tps = 20.0)

### Core information
**Server version**: CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**AAC version**: 3.3.7

**ProtocolLib version**: 4.3.0

**Plugin list**: LuckPerms, Citizens, EmptyWorldGenerator, ViaVersion, Spectate, OnlyProxyJoin, ProtocolLib, AAC, CherryNetworkUtils, KnockOut

### Special environment information
**ViaVersion version**: insert (or N/A)

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**ViaVersion version**: 1.3.0

**BungeeCord plugins**: AdvancedBan, AlwaysOnline, BungeeInfo, BuycraftX, CherryEssentials, CoinCommand, GlobalStats, HubMagic, JoinMe, LuckPerms-Bungee, McGameInfoBungee, MoveMeNow,
 NuVotifier, OnChatHACKER, ServerListPing, StoreLogs, TeamChat, VoteListener, VPNGuardBungee

### Configuration
https://www.diffchecker.com/tEEPaoZm

**Comment by Janmm14** [comment]
As an unrelated side note: your config is outdated
