### ISSUE TITLE
Allow viewing of violation log without AAC.admin

### ISSUE THREAD

**Issue by bob7l** [konsolas/AAC-Issues#1122]
I'm suggesting an alternative method/permission for viewing the violation log. Since the violation log is pretty much read-only, i don't see why it's combined with other powerful functions such as the ability to toggle modules. Could you possibly add a command, if not a simple permission to allow viewing of ONLY the violation log, and not the rest of the admin functions.

**Comment by Janmm14** [comment]
AAC.manage is required to toggle modules

**Comment by konsolas** [comment]
This is already present, as Janmm14 has detailed above. For clarification

If you want a user to view the violation log but not toggle modules, give them AAC.admin
If you want a user to toggle modules or reload as well, give them AAC.manage on top of that.
