### ISSUE TITLE
AAC critical cpu usage issues 

### ISSUE THREAD

**Issue by craftrise** [konsolas/AAC-Issues#1123]
### Issue description

The AAC plugin, too, is using some CPU over-time.

### Core information

**Server version**:  1.8.8 - Spigot

**AAC version**: Latests 3.3.7-b2

**ProtocolLib version**: 4.2.0

**Plugin list**: CUSTOM

### Special environment information

**ViaVersion version**: LATEST

**BungeeCord plugins**: CUSTOM

Here are the parts that are lag:
https://hastebin.com/menerapice.md

PHOTOS:
[https://i.hizliresim.com/qJ72QW.png](https://i.hizliresim.com/qJ72QW.png)
[https://i.hizliresim.com/POXENQ.png](https://i.hizliresim.com/POXENQ.png)

Online players: 150 , Cpu usage %160, If im remove AAC: %70 - 80

**Comment by jiangdashao** [comment]
It is normal
not a bug

**Comment by craftrise** [comment]
@jiangdashao, Yes, it's not a bug. It's a issue.

**Comment by Toshka17** [comment]
![20180105014157](https://user-images.githubusercontent.com/10418172/34585741-cb67fd3e-f1ec-11e7-866b-bf080098abfc.png)

**Comment by craftrise** [comment]
@Toshka17 How many players are online?

**Comment by Toshka17** [comment]
On this server? This is minigame's arena, about 24 players

**Comment by konsolas** [comment]
Unfortunately CPU usage cannot be "fixed" because AAC needs to monitor the activity of every player on the server.
