### ISSUE TITLE
Interact false positive falling sand + litlte lag (in water)

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1124]
Video: https://www.youtube.com/watch?v=KOy3V6pyToQ

### Core information
**Server version**: Paper 1.12.2

**AAC version**: Latest (3.3.7-b2)

**ProtocolLib version**: v4.3.0

**Plugin list**: Almost not

### Special environment information

**ProtocolSupport version**: buildnumber: 178

### Configuration
Config: https://pastebin.com/ZWyzZKNp
Tresholds like Celebrimor config

Log: https://pastebin.com/eauNFH1u

**Comment by Janmm14** [comment]
Hmm its likely because the sand is instantly falling down
