### ISSUE TITLE
ERROR Could not pass event PlayerTeleportEvent to AAC 

### ISSUE THREAD

**Issue by CalontroMC** [konsolas/AAC-Issues#1126]
Core information
**Server version**: 1.8.8

**AAC version**:v3.3.7

**ProtocolLib version**: 4.3.0

**Plugin list**:
AAC
AACAdditionPro
Authme
bStats
HackedServer
HideandCustomPlugins
HideStream
LiteBans
PlaceholderAPI
PlugMan
PremiumHub
ProtocolLib
React
Tablist
Updater
ViaVersion
Worldedit

Error log: https://hastebin.com/mamonusupu.vbs
Could not pass event PlayerTeleportEvent to AAC v3.3.7 org.bukkit.event.EventException

Please Help thank

**Comment by Janmm14** [comment]
net.martinekstrom.PremiumHub is teleporting asynchroniously. This is not supportedby AAC and bukkit itself accordingto the original documentation does not cliam its always possible too.
