### ISSUE TITLE
Falling through the blocks

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1129]
This bug has existed since June. Since that time, many changes have been made, it began to happen less often, but it still happens.

For example, this often happens when the player is teleported from a large distance (there must be enough buildings around so that the chances around the player last longer). Also, if you turn on Phase check, then the bug appears less often (with the phase check disabled, the bug appears often).

Also, this bug is manifested in the fact that players can pass through easily destructible blocks.

Video 1st person: https://radikal.ru/video/5r74CScDt2b
Video 3st person with console: https://radikal.ru/video/DfvoH0xebow

Without AAC everything is fine

________________________________________________________________________________________________________
Core information

Server version: Paper 1.8.8
AAC version: Latest (3.3.7-b2)
ProtocolLib version: v4.3.0
Plugin list: AAC, ProtocolLib, BedWarsRel, Multiverse-Core
________________________________________________________________________________________________________

Log: https://pastebin.com/GmdR8Bzs
Config: https://pastebin.com/WmNkRCJH

________________________________________________________________________________________________________

P.S. Also this bug was checked with WorldGuard on paper 1.12.2: https://youtu.be/7smLFJBUId4?t=30s

**Comment by LogGits** [comment]
I am also having the same issue. Player reported using /back to get back to the end and fell through a 1 block floor to their death. I did notice completely disabling Phase reduces the likelihood of the issue occurring however, it still appears very often.

**Comment by craftrise** [comment]
I am also having the same issue.

**Comment by Toshka17** [comment]
@CeIebrimbor This happens not only after teleportation, read the issue more carefully

**Comment by CeIebrimbor** [comment]
Ah... understood. That is just where I get a majority of complaints (after teleporting).

**Comment by Toshka17** [comment]
By the way, I realized how to repeat the fall under the blocks after teleportation. It is necessary to lower the TPS of the server. But I have not had time to record the video.

**Comment by konsolas** [comment]
RaspberryDrank says that this no longer occurs in 3.3.8 when Phase detection is enabled. Can you check this again please?

**Comment by Hyronymos** [comment]
Still happen to me

**Comment by craftrise** [comment]
Yes and still happen to me. (3.3.8)

**Comment by DreenDex** [comment]
This works even when you break block under you. 
Not every time, but it works. Also you need to be lagging.
