### ISSUE TITLE
[setback] v3: Fly as Step check (your new one) - False positives

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#113]
just sprint the way:

setup: trapdoor -> space -> trapdoor:
false positive: fly moved unexpectedly 0.00 (-0.00)

setup: trapdoor -> space -> redstone repeater:
false positive: fly moved unexpectedly 0.00 (-0.06)

going to beds without autojump:
false positive: fly moved unexpectedly 0.56 (-0.08)

setup: trapdoor -> space -> half slep:
false positive: fly moved unexpectedly 0.00 (0.30)

setup: endrod -> space -> half slep:
false positive: fly moved unexpectedly 0.00 (0.25)
false positive reverse: fly moved unexpectedly 0.59 (-0.30)

setup: halfslep -> space -> brew stand 1 block above (jump from stop up and leave step pressed):
false positive: fly moved unexpectedly 0.58 (-0.30)

setup full block with carpet downjumping on block edges -> up to 3 fly and 1 speed flags (vl up to 20) and fly dragback

setup: trapdoor -> space -> carpet:
false positive: fly moved unexpectedly 0.00 (-0.16)

With different snow layers various fly moved unexpectedly dragbacks

**Seems to work only with a space inbetween. The first value seems to be the height difference of the two blocks.**

**The essence of this issue is that if you manage to go down to a block border and as you reach it u go up again, fly does flag that incorrectly.**

Exception: Normal blocks and soulsand blocks: If you get to jump to the connection of both, you get up to 3 detections and ~20 vl

[note: occasinal phase into iron trapdoors sometimes when moving at iron trapdoors, but it seems its random and depends on the packets sent by the client]

**Comment by konsolas** [comment]
Fixed, tested by Janmm14

**Comment by Janmm14** [comment]
Still issues with snow

**Comment by CeIebrimbor** [comment]
Does this need to be reopened @Janmm14 ?

**Comment by konsolas** [comment]
Snow is a separate issue, and isn't clear-cut yet.

**Comment by Janmm14** [comment]
@konsolas But it gives "fly moved unexpectedly" message. Still I'll open a new issue for that.
