### ISSUE TITLE
/aackick and ban-threresold

### ISSUE THREAD

**Issue by tatin1998** [konsolas/AAC-Issues#1130]
Hi konsolas,
the first, I'm spanish and sorry for my bad english.

I want to use ban-theresold, but I have problems.
I use before /kick command, but I have know for ban-theresold work I have to use /aackick. There start the problem. :(
/aackick command kick random player, and ban-theresold ban random player when the action repeat a lot of times.

In this video (https://www.youtube.com/watch?v=M4v-oFPXfGk) you can see that AAC kick user "zDove" when AntiHack message say that player who want kick is "McPark" (you can see this in chat).

I think that the problem in ban-theresold start with /aackick because this fail a lot of times.

Please fix this bug, because I can't use autoban for my server.

Regards, tatin1998.

**Comment by konsolas** [comment]
I'm not quite sure what the bug means... I'm pretty sure there aren't bugs related to aackick running for the wrong player
