### ISSUE TITLE
AAC Killaura/Bhop Bypass

### ISSUE THREAD

**Issue by jiangdashao** [konsolas/AAC-Issues#1134]
### Issue description
https://youtu.be/FsAiAkRj_SA

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.7-b2

**ProtocolLib version**: 4.2.1

**Plugin list**: AAC,AACAdditionPro,ProtocolLib,KitBattleX...etc

### Special environment information
**ViaVersion version**: 1.0.3

**ProtocolSupport version**: none

### Configuration
Celebrimbor's optimized configuration

**Comment by jiangdashao** [comment]
The video also shows a velocity bypass

**Comment by jiangdashao** [comment]
The client is LiquidBounce b30

**Comment by Janmm14** [comment]
closing in favor of #1135
