### ISSUE TITLE
AAC Killaura/BHOP Bypass

### ISSUE THREAD

**Issue by jiangdashao** [konsolas/AAC-Issues#1135]
### Issue description

Client: LiquidBounce b30
Bypass: KillAura,BHOP
Videos: https://streamable.com/0oqdk
Client Config: https://www.file-upload.net/en/download-12896777/LB_CONFIG.zip.html

And when you using BHOP
Just press "W",do not press “A”and "D"

### Core information
**Server version**: 1.8

**AAC version**: 3.3.7-b2

**ProtocolLib version**: 4.2.1

**Plugin list**: AAC,AACAdditionPro,etc

### Configuration
Celebrimbor's Optimized Config
And after I changed Fly min_vl to 30,still easy to bypass

**Comment by jiangdashao** [comment]
The video is lag
ignore it

**Comment by jiangdashao** [comment]
@Janmm14 Why it is invalid?
You can try the client with the config
hmmmmmmmm

**Comment by Janmm14** [comment]
https://youtu.be/FsAiAkRj_SA (from 1134)

**Comment by jiangdashao** [comment]
@konsolad @Janmm14
still can bypass
not fixedㄟ(▔ ,▔)ㄏ

**Comment by konsolas** [comment]
No it can't
