### ISSUE TITLE
AAC Error: Could not pass event EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by Jerimu** [konsolas/AAC-Issues#1136]
**Issue description**
https://hastebin.com/oteletiqun.go

**Core information**
Server version: 1.11.0

**AAC version:** 3.3.7-b2

**ProtocolLib version:** 4.4.0-SNAPSHOT-b390

**Plugin list:** AAC,AACAdditionPro,ProtocolLib,ConditionalCommands,Own Plugins

**Special environment information**
**ViaVersion version:** 1.3.0

**ProtocolSupport version:** none

**Configuration**
Celebrimbor's optimized configuration

**Comment by Janmm14** [comment]
Try spigot 1.11.2 if possible
