### ISSUE TITLE
False positive of Heuristics P/26

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1137]
### Issue description

Video: https://www.youtube.com/watch?time_continue=6&v=YgX3FbCDvfs

### Core information
**Server version**: Paper 1.12.2

**AAC version**: Latest (3.3.7-b2)

**ProtocolLib version**: v4.3.0

**Plugin list**: Almost not + OldCombatMechanics (Disable 1.9 hit cooldown)

### Special environment information

**ProtocolSupport version**: buildnumber: 178

### Configuration

Log: https://pastebin.com/Nv7B2EtN
Config: https://pastebin.com/YVRDJWDH
Tresholds like Celebrimor config

**Comment by Toshka17** [comment]
I noticed that players very often complain about Heuristics when killing mobs. Can make the function so that you can turn off the check when attacking the mobs?

**Comment by Slimerblue22** [comment]
I see you are running 1.12.2 but what I'm confused about is that there are no attack cool downs? Do you have a mod removing 1.9 cool downs?

**Comment by Toshka17** [comment]
https://www.spigotmc.org/resources/oldcombatmechanics-disable-1-9-hit-cooldown.19510/

**Comment by Slimerblue22** [comment]
Ah, forgot about that lol, we use that in our kitpvp. Might want to make sure to add that in reports about combat, it does effect it a bit since it kindof removes the entire 1.9 combat system :P.
