### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1138]
### Issue description
Just error. Log: https://yadi.sk/d/GNt8SkCJ3RCdt4

### Core information
**Server version**: Paper 1.12.2

**AAC version**: Latest (3.3.7-b2)

**ProtocolLib version**: v4.4.0-SNAPSHOT

### Special environment information

**ProtocolSupport version**: buildnumber: 178

**Comment by CeIebrimbor** [comment]
Update
http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

**Comment by Toshka17** [comment]
I'm using the latest version

**Comment by CeIebrimbor** [comment]
Thank you for editing the issue to reflect that instead of posting the older version.

**Comment by Janmm14** [comment]
From 1139: https://pastebin.com/WVV737Pn
