### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1139]
### Issue description
Log: https://pastebin.com/WVV737Pn

### Core information
**Server version**: Paper 1.12.2

**AAC version**: Latest (3.3.7-b2)

**ProtocolLib version**: v4.4.0-SNAPSHOT

### Special environment information

**ProtocolSupport version**: buildnumber: 178

**Comment by Janmm14** [comment]
Duplicate of #1138

**Comment by Toshka17** [comment]
These are different errors, no?
