### ISSUE TITLE
Purpur Bug

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#114]
Purpur stairs in particular seem to flag for phase in regular use. https://www.youtube.com/watch?v=-hhMR28BVXs

**Comment by v0idst4r** [comment]
Please share a video of you trying it on vanilla minecraft

**Comment by Janmm14** [comment]
It works on every other stairs just not the purpur ones. I did used wurst too, but without anything relevant on. Go test it yourself - if you join test server front right - and then up

**Comment by v0idst4r** [comment]
Does test.kons.co support 1.10.2 yet?

**Comment by CeIebrimbor** [comment]
That's all it supports to my knowledge. That's all I've ever logged in with.

**Comment by v0idst4r** [comment]
Hmm last time I tried it said outdated server

**Comment by Janmm14** [comment]
The aac3 test server is aac3.kons.co

**Comment by konsolas** [comment]
Fixed on the test server. Confirmed by Rqcco.
