### ISSUE TITLE
Fly false positive

### ISSUE THREAD

**Issue by SyqlexxPI** [konsolas/AAC-Issues#1141]
### Issue description
https://www.youtube.com/watch?v=3hxrWrcmx7U

### Core information
**Server version**:  PaperSpigot 1.8.8 R0.1

**AAC version**:  3.3.7

**ProtocolLib version**: 4.2.1

### Special environment information
**ViaVersion version**: 1.3.0

**Comment by Slimerblue22** [comment]
Does it ever go higher than that (as in lagging the player down or setting off an alert)
