### ISSUE TITLE
2-block-high areas allow speeding

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#1142]
Client: Slowly
Config: Celebrimbor's awesome InstaBan config 

Video 1: https://youtu.be/k4clhLINDdA
Video 2: https://www.youtube.com/watch?v=vXjDh_45XMI&feature=youtu.be

[debug.0a62c61e-d68d-4cdb-b28f-c5c6828ba503.debug.log](https://github.com/konsolas/AAC-Issues/files/1623029/debug.0a62c61e-d68d-4cdb-b28f-c5c6828ba503.debug.log)

He got no flags

**Comment by Janmm14** [comment]
Shouldnt be that hard to fix for konsolas ita likely an idontgiveafuck in 2block high areas left over from previous speed check versions

**Comment by Hyronymos** [comment]
looks like something went wrong with the debug, I created a new one
[debug.c9fdd12f-8067-4ab8-9aba-eb883f0ebb39.debug.log](https://github.com/konsolas/AAC-Issues/files/1617169/debug.c9fdd12f-8067-4ab8-9aba-eb883f0ebb39.debug.log)
