### ISSUE TITLE
Phase: impossible to climb the ladder (ProtocolSupport)

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1145]
### Issue description
Players (version 1.8) can not climb the ladder on the 1.12.2 server with ProtocolSupport
Video: https://radikal.ru/video/nfeLHCN6rDt

### Core information
**Server version**: paper 1.12.2

**AAC version**: 3.3.7-b2

**ProtocolLib version**: 4.4.0

**Plugin list**: ProtocolSupport, AAC

### Special environment information

**ProtocolSupport version**: latest
### Configuration
https://pastebin.com/gC2435jc

**Comment by konsolas** [comment]
In general, the solution here is to exempt LADDER in the configuration section for phase.
