### ISSUE TITLE
Icespeed/vanilla fly, snowspeed, stairspeed, waterspeed & much more bypasses

### ISSUE THREAD

**Issue by MrHeiLo** [konsolas/AAC-Issues#1146]
### Issue description
https://www.youtube.com/watch?v=DibQBhYzvFA&t=90s / Icespeed/Vanillafly ~by haze.
https://www.youtube.com/watch?v=DibQBhYzvFA&t=150s Snowspeed ~by haze.
https://www.youtube.com/watch?v=DibQBhYzvFA&t=590s Stairspeed ~by haze.
https://www.youtube.com/watch?v=DibQBhYzvFA&t=630s Waterspeed ~by haze.
https://www.youtube.com/watch?v=DibQBhYzvFA&t=740s Velocity ~by haze.
https://www.youtube.com/watch?v=DibQBhYzvFA&t=770s Spider ~by haze.
https://www.youtube.com/watch?v=DibQBhYzvFA&t=830s Step ~by haze.
https://www.youtube.com/watch?v=DibQBhYzvFA&t=837s NoFall (1) ~by haze.
https://www.youtube.com/watch?v=DibQBhYzvFA&t=910 Anticactus ~by haze.
https://www.youtube.com/watch?v=DibQBhYzvFA&t=910 NoFall (2) ~by haze.

i think that should be enough for now xD

### Core information
**Server version**: 1.8.? (GommeHD.net)

**AAC version**: 3.3.7

**ProtocolLib version**: unavailable

**Plugin list**: unavailable

### Special environment information
**ViaVersion version**: unavailable

**ProtocolSupport version**: unavailable

**ViaBackwards version**: unavailable

**BungeeCord plugins**: unavailable

**Comment by Janmm14** [comment]
icespeed is not related to aac
