### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by Z609** [konsolas/AAC-Issues#115]
I know that this probably isn't the best way to talk about it, but I think we could get a discord server where we can get information about updates and things of that nature. That would help with communication amongst testers and plugin buyers alike. What do you think?

**Comment by konsolas** [comment]
I was thinking a slack team, perhaps.

Here's a poll: http://www.strawpoll.me/11547661

**Comment by Sikatsu** [comment]
Would vote discord.

**Comment by Janmm14** [comment]
Discord!

**Comment by Z609** [comment]
I think that although Slack is a good way of communicating, it requires an invite for each specific person. I think it'd be nicer for the community for Discord because of the fact that it has a URL joining system.

**Comment by konsolas** [comment]
My concern with discord is just that: for random people to end up joining, regardless of their intent. 

Nevertheless, I'm going to change the poll to see what people think.

New poll: http://www.strawpoll.me/11559564

**Comment by Sikatsu** [comment]
You can setup security levels in discord and get some moderators to keep it
clean.

Op wo 2 nov. 2016 19:32 schreef Vincent <notifications@github.com>:

**Comment by v0idst4r** [comment]
Discord

**Comment by konsolas** [comment]
https://discord.gg/uc9w2nx
