### ISSUE TITLE
Heuristics P/96 

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#1150]
Could P/96 be looked into? It wasn't changed this update and it's the currently the most common false positive for my server at high confidences.

**Comment by Janmm14** [comment]
As far as I know it got changed too.

**Comment by Hyronymos** [comment]
If he fixed some other heuristics patterns, could sew get please a full list?

**Comment by konsolas** [comment]
96 is one that I forgot to include in the list on that issue, will add it now
