### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by Argentoz** [konsolas/AAC-Issues#1151]
AAC 3.3.8.
False positives:
     - Fly
     - Speed
     - Velocity
url https://www.youtube.com/watch?v=IgXaS56nduk&feature=youtu.be

**Comment by Janmm14** [comment]
Fixed your link.
Just type the link without markdown formatting or if you want to label your link, write the label of the link in the `[]` brackts and the url into the `()` brackets.

**Comment by Janmm14** [comment]
Additionally it would be great if you would instead create some video that does __respect the development__ of AAC and maybe ask yourself how often certain shown special scenarios do occurr on many servers.

**Comment by konsolas** [comment]
Not following issue format + unclear situation on test server.
