### ISSUE TITLE
BedFucker and Nofall work

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#1152]
BedFucker and Nofall still works on AAC 3.3.8

**Comment by Hyronymos** [comment]
still "insufficient info"?

**Comment by konsolas** [comment]
Although 3.3.9 _may_ fix this, I currently cannot test because I don't have access to the clients.

**Comment by Hyronymos** [comment]
I will test it now

**Comment by Hyronymos** [comment]
Bedfucker and NoFall still works, you can test it with LiquidBounce
