### ISSUE TITLE
Killaura Heuristics needs to be improved

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#1153]
The current heuristics are too slow. There are some clients who are currently completely or just for a really long time completely by-passing Heuristics

**Comment by konsolas** [comment]
...

**Comment by Hyronymos** [comment]
Some clients do not even get a confidence of 75 after 5 minutes. If you need a video, aacdedbug or other from various clients, I can gladly provide them to you.

**Comment by konsolas** [comment]
Names/links of various clients would be useful.

**Comment by Hyronymos** [comment]
Suicid and Ambien

**Comment by konsolas** [comment]
They're getting some changes next update.
