### ISSUE TITLE
aac.bypass checked too frequently?

### ISSUE THREAD

**Issue by SlimeDog** [konsolas/AAC-Issues#1157]
AAC 3.3.8

aac.bypass is checked every 25-30 seconds. I'm sure it isn't a huge resource drain, but why does it need to be checked so frequently. It seem like the sort of permission that might be assigned to OP, then left alone. I assume that it is checked when a player establishes a connection, which should be sufficient.

Just a thought.

**Comment by CeIebrimbor** [comment]
Maybe check only on aacreload (or login)? It's probably an insignificant consumption and Konsolas will probably suggest it's not worth a change. We'll see 🤷‍♂️

**Comment by SlimeDog** [comment]
Yeah, I'm just kind of on a campaign on this issue. Now that I'm monitoring, I've encountered plugins that are checking similar permissions **every 5 ticks**. So 25-30 seconds is small potatoes. Nevertheless...

**Comment by Janmm14** [comment]
Other plugins do check permission on every execution and I think and hope any permissions plugin is built in a way that it doesn't create any lag for such a task.
Increasing the delay or removing it completely could lead to people asking why aac doesn't update perms.

**Comment by SlimeDog** [comment]
It is a dilemma. :)

No worries at this end. Just raising the issue to eyeball level.

**Comment by konsolas** [comment]
Definitely not a significant impact in any way.
