### ISSUE TITLE
Hitbox FP

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#1159]
Log: https://hastebin.com/ileritifev.cs
Video: https://www.youtube.com/watch?v=YU_O8Gy4urI&feature=youtu.be

**Comment by CeIebrimbor** [comment]
5:45 in video. Confirmed that players have double jump which allows them to change velocity midair. Maybe the cause of frequent hitbox violations?

**Comment by Janmm14** [comment]
did the enemy had lag spikes?
5.8 blocks is fairly huge

**Comment by Hyronymos** [comment]
Our doublejump is only a toggle of fly (aac does support this) and I have much other reports from bedwars (no doublejump).

It gives some velocity bypasses that quick boost towards a player without hitbox flags so It can't be a double jump thing
e.g. all of haze hacking videos

**Comment by Hyronymos** [comment]
https://www.youtube.com/watch?time_continue=21&v=ATgyaLUKatQ

Another Ban (NO DOUBLEJUMP)

**Comment by CeIebrimbor** [comment]
@hyronymous
Can you downgrade to 3.3.7 and see if it’s still happening? I’m starting to think that a change in Hitbox to help with a KA bypass may have crossed some wires.

**Comment by CeIebrimbor** [comment]
Another chase scene with Hitbox problems:
https://streamable.com/c6g6j

`move_comp` broken in 3.3.8? :thinking:
