### ISSUE TITLE
aacadmin lags server

### ISSUE THREAD

**Issue by timothydavidhart** [konsolas/AAC-Issues#1160]
### Issue description
When I do /aacadmin it locks up my whole server for a solid ~10 seconds here is my timings report after running the command

### Core information
**Server version**: 1.12.2 9b8bba4-bdcc8c8

**AAC version**: 3.3.8

**ProtocolLib version**: 4.3.0

Ban config by celebrimbor

**Comment by Janmm14** [comment]
It is loading the skins and you forgot to provide the timings link if you wanna show it

**Comment by timothydavidhart** [comment]
opps sorry about that https://timings.spigotmc.org/?url=wixapodado

**Comment by konsolas** [comment]
This is something that can't really be worked around - spigot does skin lookups on the main thread, and /aacadmin looks up the skins of online players to get their skulls for the violation list.
