### ISSUE TITLE
PlayerMoveEvent and unhandled exception occured in onPacketReceiving(PacketEvent)

### ISSUE THREAD

**Issue by craftrise** [konsolas/AAC-Issues#1164]
**Server version**: 1.8.8
**AAC version**: 3.3.9
**ProtocolLib version**: 4.2.0
**Plugin list**: Custom

**ViaVersion version**: Yes
**BungeeCord plugins**: Custom

Errors: https://hastebin.com/abebeqalaj.vbs

**Comment by konsolas** [comment]
hastebin link dead :(

**Comment by Janmm14** [comment]
hastebin has trouble

**Comment by craftrise** [comment]
@konsolas, pastebin: https://pastebin.com/JLUr4JrV
