### ISSUE TITLE
Startup error | AAC not working

### ISSUE THREAD

**Issue by Lyfetime** [konsolas/AAC-Issues#1166]
Hi,
AAC is not working for some reason. I'm running Spigot 1.8.8, have tried downloading several times, have ProtocoLlib installed, and even deleted every single plugin except for AAC and ProtocolLib (temporarily) to see if it would work, and it didn't, so a plugin isn't causing it. I get this error message when I start it up: https://hastebin.com/axucowepew.vbs I'm running the latest version of AAC. I tried the older version and it worked, but I'd like to use the newest one. Any ideas?
Plugins: https://ibb.co/fp45Gw
Thanks,
9000

**Comment by Rerd** [comment]
I’ve noticed a few people with this same issue. I have a feeling it has something to do with the update that’s messed up. I recommend using the last version that worked for you.

**Comment by Janmm14** [comment]
If you use java 9 please try out java 8.
