### ISSUE TITLE
Performance of the plugin ...

### ISSUE THREAD

**Issue by Pikuuu** [konsolas/AAC-Issues#1167]
Hello, I'm Polish, so I apologize in advance for the incorrectness of sentences: D I am the owner of one of the largest servers in Poland and when the server was sitting a large number of players has happened: 
https://timings.aikar.co/?id=275f874c9e7a4f9c897f10bd40cac986

Is there any way to improve the performance of the plugin?

Regards

**Comment by CeIebrimbor** [comment]
That's actually not unexpected for an Anti-Cheat with 250 players. AAC looks like it's about 30% of your CPU load on average.

The only way (on your end) to reduce the load is to disable checks like Speed and Fly. Maybe you also include your server specs to additional commentators can see if you have enough power to back this load.

**Comment by Pikuuu** [comment]
I use this plugin to make your plugin work better

https://www.spigotmc.org/resources/conditionalcommands.14295/

**Comment by CeIebrimbor** [comment]
Conditional Commands has nothing to do with CPU consumption. AAC eats CPU based on the number of players and what said players are doing. Kicking and notifying based on ping or TPS is not going to make AAC take less CPU to accomplish its detection tasks.

I wish there was a not so insulting way to say this, but I thought that would be common sense to someone who runs the largest server in Poland 😨

**Comment by Pikuuu** [comment]
I'm not a programmer;) Can I do something to make AAC take less resources?

**Comment by Minemaniak** [comment]
Apart from disabling checks? No

**Comment by konsolas** [comment]
Unfortunately there is not really any way to improve the performance as AAC still needs to monitor the actions of every player on the server.
