### ISSUE TITLE
Bow boosting = Speed

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#1168]
### Issue description
Typical bow boosting with punch enchant will hit min_vl pretty quick.

Video: https://www.youtube.com/watch?v=IqDnkpEUGys
Debug: https://pastebin.com/GD5Rrau2

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.9

**ProtocolLib version**: 4.2.0

**Plugin list**: None, just punch enchant

### Special environment information
N/A (just stock Spigot 1.8.8 and 1.8.8 client)

### Configuration
Relevent speed values all default

**Comment by Hyronymos** [comment]
maybe related to #1165 

https://youtu.be/IzP1Pd_ZU3k

**Comment by CeIebrimbor** [comment]
Looks like a possibility. This issue singles out the direct cause though. If you feel like the other issue has something more to offer or has another issue linked into it, keep it open and maybe clean it up? If you think it's 100% identical, then I can close this.

At first glance, I feel like this issue is best since it's all vanilla velocity. No chance of other combat plugin stuff going on. 🤷‍♂️

**Comment by alexmarkey** [comment]
Experiencing the same.

**Comment by Minemaniak** [comment]
Not fixed.

**Comment by CeIebrimbor** [comment]
Couple reports this is still a problem.

**Comment by Minemaniak** [comment]
https://pastebin.com/aj70h8gM Debug log from new version, it looks even worse than in 3.3.9
