### ISSUE TITLE
Slime Block Tower = Fly

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#1169]
### Issue description
Simple nerd pole with slime blocks quickly accumulates Fly.

Video: https://www.youtube.com/watch?v=8D9Az3aoJOQ
Debug: https://pastebin.com/igdfdmSG

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.9

**ProtocolLib version**: 4.2.0

**Plugin list**: N/A

### Special environment information
N/A (just stock Spigot 1.8.8 and 1.8.8 client)

### Configuration
Relevent Fly values all default

**Comment by Minemaniak** [comment]
Not fixed....

**Comment by konsolas** [comment]
Tested properly this time.
