### ISSUE TITLE
v3: NoSlowdown cobweb partly bypass

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#117]
NoSlowdown works on soulsand without any issues, seems like the modifier isn't respected. Even if there is two-layered soulsand.

NoWeb is working if you sneak with it (its still faster than not sneaking without noweb) (not with souldsand below)

Also sneaking in cobwebs normally causes you to move even slower. (See #109)

(Little side note: you can for example use fly in a hack client to walk without sinking into soulsand.

**Comment by Janmm14** [comment]
@konsolas You had a fix for normal jumping in cobwebs and I think also for the little-faster-noweb on the test server, but it seems gone :/ Works as before u patched.

**Comment by Rqcco** [comment]
@konsolas The NoClip report I did that you closed seems to actually be faster than sprinting and jumping so it's still considered "Speed".

**Comment by Rqcco** [comment]
Janmm14 and I tested it out.

**Comment by Janmm14** [comment]
That NoClip speed is probably the same as #106

**Comment by konsolas** [comment]
NoSlowdown fix completed.

**Comment by v0idst4r** [comment]
@konsolas I can't sprint jump in webs, it causes the "please sneak/block" message

**Comment by v0idst4r** [comment]
Just sprint then hold space.

**Comment by Janmm14** [comment]
Update!

NoSlowndown is bypassing byjumping on cobwebs, however it only flags when sprinting and its also faster than normal if you don't sprint.

**Comment by v0idst4r** [comment]
shh

**Comment by Janmm14** [comment]
So jumping through cobwebs (#241) is basically the same as jumping above cobwebs?
