### ISSUE TITLE
Error enable AAC 3.3.6

### ISSUE THREAD

**Issue by juliandaw** [konsolas/AAC-Issues#1174]
### Issue description
console:
[18:09:21 INFO]: [AAC] Enabling AAC v3.3.6
[18:09:22 INFO]: [AAC] Disabled due to piracy (69)
[18:09:22 INFO]: [AAC] Disabling AAC v3.3.6
[18:09:22 INFO]: [AAC] Disabling checks...
[18:09:22 INFO]: [AAC] Error enabling AAC: 0x04
[18:09:22 INFO]: [AAC] Please report this to konsolas

### Core information
**Server version**: Spigot 1.8.9

**AAC version**: 3.3.6

**ProtocolLib version**: 4.3.0

**Plugin list**: https://i.imgur.com/hT2o9zU.png

### Special environment information
**ViaVersion version**: insert (or N/A) NO

**ProtocolSupport version**: insert (or N/A) ??

**ViaBackwards version**: insert (or N/A)??

**BungeeCord plugins**: insert (or N/A)NO

### Configuration
no config

**Comment by Janmm14** [comment]
Are you sure you bought AAC on spigotmc and nobody published your AAC copy?

**Comment by juliandaw** [comment]
no not from spigotmc

**Comment by juliandaw** [comment]
:D

**Comment by Minemaniak** [comment]
So first buy the plugin, don't steal someone's work.

**Comment by juliandaw** [comment]
:/
i cant buy it :(
dont ask me why

**Comment by juliandaw** [comment]
So first buy the plugin, don't steal someone's work.

this is the problem ?

**Comment by juliandaw** [comment]
but i want it

**Comment by Minemaniak** [comment]
You can't use the plugin without buying it.

**Comment by Janmm14** [comment]
@juliandaw 
THIS IS NO ISSUE!
