### ISSUE TITLE
Feature request: Bypass heuristics per player

### ISSUE THREAD

**Issue by Minemaniak** [konsolas/AAC-Issues#1175]
Current AAC API let's you easily make it compatibile with non-standard mechanics, by cancelling PlayerViolationEvent in problematic situations. This applies to all checks but Heuristics. It's not enough to bypass (cancel events) while problematic situation happens, because they can flag a long time after. How long?? @konsolas says, that in theory infinitely long. So my request is: add funcionality to the API that would let you set the player to not be checked by heuristics at all (or only by certain patterns) and later revoke that bypass. This way we would be able to make all checks compatibile with custom plugins.

**Comment by Minemaniak** [comment]
Even something like option to cancel all pending heuristics analyzes on player would be useful. One could use it after incompatibile situation, to make sure no more violations will happen caused by this situation

**Comment by konsolas** [comment]
This can now be achieved by cancelling PlayerViolationEvent for Killaura.
