### ISSUE TITLE
1.12 clients on 1.8 server SOIL speed false positive

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#1176]
> Latest release didn't fix the issue completely. Players don't fall through soil anymore, but they are still kicked for Speed.
>
> https://github.com/konsolas/AAC-Issues/issues/922#issuecomment-361011354 by @MineTheCube

**Comment by Janmm14** [comment]
See #1237 
![](https://camo.githubusercontent.com/1e3f2dbc171a30a2c4bad9300b424ee59714b084/68747470733a2f2f692e696d6775722e636f6d2f47434372704d612e676966)

**Comment by MineTheCube** [comment]
I know, but I thought you were close or in touch with konsolas or something.

@konsolas so? it's been almost a [year](https://github.com/konsolas/AAC-Issues/issues/922) :/
