### ISSUE TITLE
Speed FP Walk Speed change

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#1177]
### Issue description
https://youtu.be/fd_qXgaWA_k
In the beginning of the video, you can see the player will be flagged for speed when they change their weapon, every weapon have different walk speed, and when they change their weapon, I change their walk speed by Player#setWalkSpeed.
This occured after updating to 3.3.9, did not happen in 3.3.7

### Core information
**Server version**: paper 1.12.2

**AAC version**: 3.3.9

**ProtocolLib version**: 4.4.0-SNAPSHOT-b390

**Plugin list**: upon request

### Special environment information

**ProtocolSupport version**: 4.29)

**BungeeCord plugins**: upon request

### Configuration
3.3.9's default configuration

**Comment by MClausz** [comment]
@konsolas Please fix this ASAP, this is crittical to my server.

**Comment by Janmm14** [comment]
First, konsolas is away this week.
Second, you see the issue tracker has more than 50 open issues, that likely means fixes are coming with some delay.

**Comment by MClausz** [comment]
It's been over a month now what the heck

**Comment by MClausz** [comment]
@konsolas please, fix this in the next version, it's been over 3 months now, and it's a critical issue in my server.

**Comment by Janmm14** [comment]
konsolas will probabl  start updates again in july. for now u need to wait until his gcse's are over.
