### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Nekiplay** [konsolas/AAC-Issues#1178]
### Issue description
Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 
![image](https://user-images.githubusercontent.com/35975332/35590674-64f7d226-0629-11e8-8059-ead5f992fe84.png)

### Core information
**Server version**: 1.12.2

**AAC version**: 3.3.6

**ProtocolLib version**: 4.3.0

**Plugin list**: AAC,AACAdditionPro-3.5.0,AuthMe-5.3.1-legacy,AutoSaveWorld,Essentials-2.x-SNAPSHOT,EssentialsSpawn-2.x-SNAPSHOT,MaxBans,ProtocolLib,ProtocolSupport,ViaVersion-1.3.0

### Special environment information
**ViaVersion version**: 1.3.0 (or N/A)

**ProtocolSupport version**: 4.28 (or N/A)

**ViaBackwards version**: insert (or N/A)

**BungeeCord plugins**: insert (or N/A)

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

**Comment by CeIebrimbor** [comment]
Purchase AAC from SpigotMC, problem solved.
