### ISSUE TITLE
LiquidBounce fully bypasing AAC's killaura heuristic detection

### ISSUE THREAD

**Issue by LoicFlows** [konsolas/AAC-Issues#1179]
### Issue description
Latest LiquidBounce is fully bypassing AAC's killaura heuristic detection. I've been fighting for more than 3 minutes, and I haven't got flagged by heuristics at a confidence of 75 and neither on 50. 

I was using default settings (the only thing that I changed was enabling "AAC" in the killaura settings.).

### Core information
**Server version**: 1.8.8 (Paper)

**AAC version**: 3.3.9

**ProtocolLib version**: 4.2.0

**Comment by CeIebrimbor** [comment]
@LoicFlows 
By chance was the player being hit by the hack client OP (or have AAC.bypass perm)? If a player that is targeted has AAC bypass, the hacker cannot be detected when using any KA hacks on them. 

I just wanted to make sure that wasn't at play here. It is pretty common for claims of "full KA bypass" to be linked to that.

**Comment by LoicFlows** [comment]
Oh, yeah, totally forgot about that. Re-tried, now got flagged within 20 seconds. Can be marked as invalid.

**Comment by ShadowLBx** [comment]
bruh just do .config aac or .config gomme and it is completely flagless lol tested on poke.sexy

**Comment by konsolas** [comment]
poke.sexy not helpful as a source for testing.

**Comment by w-o-a-h** [comment]
tbh the only reason why it would not be helpful is because you don't give you logs because its used to create cheats for aac
