### ISSUE TITLE
Make it so heuristics doesn't false flag when fighting lifeless players and or entities

### ISSUE THREAD

**Issue by LoicFlows** [konsolas/AAC-Issues#1180]
### Issue description
Make it so heuristics doesn't false flag when fighting lifeless players and or entities. In my opinion, an anti-cheat _shouldn't_ false flag when fighting a lifeless player or entity. This has been a problem since version 3.1.4 (before that, this wasn't a _big_ issue)

Imagine a player fighting a player who is AFK, he will most likely get flagged by heuristics. This is the same for entities, whenever you for example need to fight entities you can get flagged by heuristics.

My suggestion is to add more leniency to heuristics when you're fighting a player or entity who isn't fighting back as it is less likely to occur when you're in a real combat situation (when a player is fighting back).

**Comment by konsolas** [comment]
Heuristics have been removed.
