### ISSUE TITLE
Creative Mode + Bone Meal = Interact FP

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1182]
Video: https://youtu.be/8viZ2tk4KGI

### Core information
**Server version**: Paper 1.12.2

**AAC version**: Latest (3.3.9)

**ProtocolLib version**: v4.4.0-SNAPSHOT

**Plugin list**: (2): AAC, ProtocolLib

### Configuration
Config: https://pastebin.com/j7XGqA4m

Log: https://pastebin.com/uYBNC2aL

**Comment by Toshka17** [comment]
Perhaps this is due to the fact that the player is in the creative mode.
Maybe then turn off the checking of players who are in gamemode 1?

**Comment by CeIebrimbor** [comment]
#688 and #641. Not sure why 688 was closed other than "Old Version".
