### ISSUE TITLE
False Suspicious combat detection

### ISSUE THREAD

**Issue by dobrac** [konsolas/AAC-Issues#1184]
### Issue description
Hello, I have got today this report from one player on my server. 

When the player was kicked the server had 20 TPS and the player had ping 49 ms.

The situation was captured on this video: https://www.youtube.com/watch?v=zBF8IKyzs50&feature=youtu.be (he gets banned at about 0:30)

I am sorry, but I don't have any other information from AAC, because I have disabled verbose.

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.9

**ProtocolLib version**: insert

**Plugin list**: AAC, ConditionalCommands, ProtocolLib, some private plugins

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: Some private plugins (nothing to do with AAC)

### Configuration
Default configuration with default thresholds. (but some checks are disabled) ( https://www.diffchecker.com/885SCHpn )

**Comment by Photon-GitHub** [comment]
First of all I have never heard of an „insert“ ProtocolLib version. 😉 
In the video I can only see clearly non-vanilla behavior, such as his short „fly“ period as well as his obviously modded client. If you cannot even provide logs it is hard for us to help you.

**Comment by dobrac** [comment]
Sorry, my bad. ProtocolLib version should be: 4.3.0

Yes. The player used before the fight one spell, that gave him instant velocity via Bukkit API. 

And yes, he is using some mods in his client, but the weird thing is, that he was banned after the fight when he was running away :/

I would like to send you the logs, but because I have these verbose things disabled, so in my logs is visible just the final command :/ I don't really know, how to replicate it, so I could send you verbose logs from AAC.

I understand that it is really hard to fix this issue with such little informations, but I tryied it. Because the source code is not open source (for obvious reasons), and can't know, if this little helps. :)

**Comment by Rerd** [comment]
He most definitely isn’t cheating in that clip. That was 100% legit and it’s definitely a false positive. If you could find the section he got banned at in the logs that would be helpful.

**Comment by dobrac** [comment]
1. I have a problem with it, because all of my servers are deleted on stop, so files, that I don't save are lost. (And this is the lost case)
2. Okay, I understand
3. Yeah, the lag is weird, but it doesn't look like something AC related.

Can I somehow help to solve this problem without the log?

**Comment by Janmm14** [comment]
Without a log there is no possibility to find the pattern which got triggered, which is required by konsolas to fix false positives for heuristics.

I see the behaviour does look legit, but second 18 with slowmo does not look legit for me, I wouldn't be able to do that.

**Comment by dobrac** [comment]
Ok.

Is it possible to add feature for logging these things to MySQL? It would be much easier for me to save these logs.

**Comment by Janmm14** [comment]
Previous request(s?) about MySQL logging was denied as out-of-scope.
gzipping logs and sending them to some file server would probably also lead to less disk space used.

**Comment by dobrac** [comment]
It would not be so out-of-scope. Actually, it could be much easier to search through it and find maybe some similar cases and so on.

I would use it (maybe create some dedicated database for on) on my network rather then saving log files somewhere. (Daily players online: 800+, so nice sample.)

**Comment by konsolas** [comment]
The problem is that the chronological logging format used by AAC isn't really suited to databases, because old data is never modified and new data is simply added onto the end.
