### ISSUE TITLE
BugUP Bypass/Bug

### ISSUE THREAD

**Issue by jiangdashao** [konsolas/AAC-Issues#1185]
LiquidBounce Client has a **BugUP**  cheat,
it can setback you from void when you fall into void
It will cause AAC flag,then AAC will teleport the hacker
I suggest add a force drag down when AAC detected fly or speed flag,and also give player a fall damage

**Comment by Slimerblue22** [comment]
From what I've seen AAC drags the user down and will cause them to take fall damage, I haven't seen it teleport a hacker back.

**Comment by jiangdashao** [comment]
When does AAC fixed the BugUP bypass?
I tested it in AAC 3.3.8,and i used the liquidbounce b33

**Comment by jiangdashao** [comment]
3.3.9 Fixed this bug

**Comment by jiangdashao** [comment]
Close it
