### ISSUE TITLE
LAGBACK: Phase check

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1188]
### Issue description
In the latest version, there are VERY many lagbacks that are called false positives of Phase check. This happens really often now. Players complain. You can simply run, knock on some block and the phase check will respond to it.

Video1: https://radikal.ru/video/TOqCm9LKFWl

Log: 
![image](https://user-images.githubusercontent.com/10418172/35874471-4fa008be-0bb8-11e8-866b-079902024495.png)

UPD: 
Video2: https://radikal.ru/video/DJfV6xzSuSw
Video3: https://radikal.ru/video/sI0vVtBDef1

### Core information
**Server version**: paper 1.12.2

**AAC version**: latest (3.3.9)

**ProtocolLib version**: v4.4.0-SNAPSHOT

**Comment by Toshka17** [comment]
It also happens when building up and is very disturbing
(tested on clean server (only PLib and AAC))

Video2: https://radikal.ru/video/Pi2JF3lSdzF
Log: 
[19:18:04 INFO]: [AAC] [VERBOSE] obormotik failed Phase: moved into a block (SANDSTONE at 34,122,196) [ping:167 tps:19.99] VL:1

**Comment by Minemaniak** [comment]
I can confirm, sometimes just running into wall trigers phase, or running alongside wall touching it

**Comment by Janmm14** [comment]
This is probably a result of float/double conversion issues.

Could you please provide the client version used?

**Comment by Toshka17** [comment]
@Janmm14 
Version 1.12.2

**Comment by Toshka17** [comment]
Video2: https://radikal.ru/video/DJfV6xzSuSw
Video3: https://radikal.ru/video/sI0vVtBDef1

**Comment by Minemaniak** [comment]
Version 1.8.9

**Comment by Minemaniak** [comment]
Easy to trigger on non-full blocks (stairs, slabs, etc), but happens also with full blocks.

**Comment by Rerd** [comment]
Bumping this because it's extremely irritating to players.
