### ISSUE TITLE
fastbreak check problem!

### ISSUE THREAD

**Issue by LegendsIta** [konsolas/AAC-Issues#1189]
### Issue description
Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.9

**ProtocolLib version**: 4.3.0

**Plugin list**: permissionex, aac, vault, worldedit

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".
Default Config

Hi, AAC does not detect the fastbreak on the following picks:

-PICKAXE Wood : efficiency 5 (not detect)
----------------------------------------------------
-PICKAXE Stone : efficiency 5 (not detect)
----------------------------------------------------
-PICKAXE Iron : efficiency 4 (not detect)
----------------------------------------------------
-PICKAXE Iron : efficiency 5 (not detect)
----------------------------------------------------
-PICKAXE Gold : efficiency 4 (not detect)
----------------------------------------------------
-PICKAXE Gold : efficiency 5 (not detect)
----------------------------------------------------
-PICKAXE Diamond : efficiency 4 (not detect)
----------------------------------------------------
-PICKAXE Diamond : efficiency 5 (not detect)
----------------------------------------------------
help me please!

**Comment by Janmm14** [comment]
i think doesn't detect because of the enchantment being so high to prevent false positives

**Comment by bob7l** [comment]
Same on my server

**Comment by konsolas** [comment]
Extremely high efficiency tools are not checked because they break blocks almost instantly. You can make this more strict in the fastbreak configuration if you wish.
