### ISSUE TITLE
Server motd

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#119]
Instead of writing § in the server motd you should use the term \u00A7
so e.g. \u00A7e would be yellow color. This will prevent the special characters before the actual texts.

**Comment by Janmm14** [comment]
The server-properties is changed by minecraft in a wrong way: it replaces `§` to two \u escapes, you need to delete the first one.

**Comment by konsolas** [comment]
Sorted. Thanks guys 👍
