### ISSUE TITLE
Sprint+Jump & bhop not being detected.

### ISSUE THREAD

**Issue by FrozenBeard** [konsolas/AAC-Issues#1194]
### Issue description
We have a few custom weapons that trigger AAC (See #1193) so its a quick way to trigger AAC for testing as we know this is a known bug for AAC to test things, I had a player report bhop isn't detected, this can quickly be shown by showing the custom weapon rubber banding you by simply holding it and running, and then when you Spring+Jump it completely bypasses AAC, so bunny hopping would work.

https://www.youtube.com/watch?v=tmOANVf9Rls&feature=youtu.be

### Core information
**Server version**: 1.12.2 Paper Spigot 1320

**AAC version**: 3.3.9

**ProtocolLib version**: 4.4.0 b390

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: LuckPerms

### Configuration
I use the paid config.

**Comment by Janmm14** [comment]
lol

**Comment by konsolas** [comment]
what?

**Comment by FrozenBeard** [comment]
Why was this classed as an old version, I posted this when it was 3.3.9, was it fixed in the latest releases? is that why its closed now?

**Comment by Minemaniak** [comment]
This report is invalid. You show that certain bug isn't happening in certain conditions and conclude that it means bhop isn't detected. This conclusion doesn't make any sense. If you report a bypass, show the actual bypass, the client which is bypassing etc.
