### ISSUE TITLE
Default group geting kicked

### ISSUE THREAD

**Issue by UltraMIX95** [konsolas/AAC-Issues#1196]
my group are getting kicked from acc http://prntscr.com/icnuls

**Comment by Minemaniak** [comment]
AAC doesn't have any Anti-AFK system, so it won't kick for being AFK. It's other's plugin fault.

**Comment by CeIebrimbor** [comment]
Not AAC

**Comment by UltraMIX95** [comment]
i only stay for like 10sec away and he kicks

Em 10/02/2018 05:37, "Minemaniak" <notifications@github.com> escreveu:

**Comment by Minemaniak** [comment]
Kicks you re experiencing ar not caused by AAC, you have to look into your other plugins.

**Comment by Rerd** [comment]
Check your Essentials config.yml for this kick.

**Comment by UltraMIX95** [comment]
i solve it thanks, sorry for bothering

2018-02-10 12:56 GMT-05:00 Rerd <notifications@github.com>:
