### ISSUE TITLE
Lag Spikes can cause FightSpeed false positives

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1197]
When a player has a lag spike (not fps), there's a possibility for them to start flagging and even get banned for it.

I actually accidentally recreated this a while ago and got banned. I did have Conditional Commands set up for the FightSpeed check too. In the video, I was purposely limiting my bandwidth to create lag, although this has been happening to many other players with low internet speeds or just lag spikes in general. [Video here](https://www.youtube.com/watch?v=lgSqR0_BEbI).

### Core information
**Server version**: Spigot 1.8.8 R0.1-Snapshot

**AAC version**: 3.3.2 (first time) and 3.3.9 (latest time)

**ProtocolLib version**: 4.2.0

**Plugin list**: (if requested)

### Special environment information
**ViaVersion version**: Not used

**ProtocolSupport version**: Not used

**ViaBackwards version**: Not used

**BungeeCord plugins**: (if requested)

### Configuration
Custom Configuration (will send if requested)

**Comment by Slimerblue22** [comment]
I can confirm this can happen with lag spikes, my internet being my internet shows me that alot

**Comment by Rerd** [comment]
I’ve also noticed that lag spikes can also cause Killaura Heuristics and Criticals false positives too. I think there should be compensation for huge lag spikes for the three checks and maybe others too.
