### ISSUE TITLE
AAC 1.13 - Possible False Positives 

### ISSUE THREAD

**Issue by Pluginsel** [konsolas/AAC-Issues#1198]
1.13 is a next major update to be released in Minecraft since 1.8 and 1.9 version. 
Official name is confirmed for The Update Aquatic and is will add new features to ocean and will include long-awaited changes.

I think the new BUBBLE COLUMNS is will have the false positives for AAC plugin. Is will need to test after the full release: http://prntscr.com/idsbm6

New swimming animation.

This issue will be updated once snapshots begin.

**Comment by Pluginsel** [comment]
1.13 snapshot 18w07a is out and the swimming animation is added.

**Comment by Janmm14** [comment]
for now I'd say its unimportant since it will take some time until 1.13 is released

**Comment by CeIebrimbor** [comment]
Sucked into #1202
