### ISSUE TITLE
[Feature Request] AutoSoup detection

### ISSUE THREAD

**Issue by Krymonota** [konsolas/AAC-Issues#12]
There are a lot soup pvp servers out there, especially for Minecraft 1.8. The basic concept is that you get 3.5 hearts by clicking a mushroom soup. You need some skill to heal yourself with mushroom soups whilst fighting against players.
A lot cheaters on those servers are using a cheat called "AutoSoup". Most hack clients are using the same pattern for AutoSoup, so it's quite easy to detect lots of hack clients with a single check.
I guess you know this kind of cheat, but here's a video - just in case you don't know it: 
https://www.youtube.com/watch?v=wkUblsjaITM
As you can see in the video, AutoSoup first eats all the mushroom soups in the hotbar when the players health is below 6.5 hearts. Once there are no more mushroom soups in the players hotbar, it just puts the first bowl back into the inventory, takes a mushroom soup from the inventory and puts it into the hotbar so that it can be eaten to regain hearts.

Here's a list of some hack clients that provide this cheat:
- Huzuni
- Wurst ([source code of AutoSoup](https://github.com/Wurst-Imperium/Wurst-Client-for-MC-1.8.X/blob/ce5b3b9ce3ed7dbb5726c0ec2dfbe3e21ae33439/Wurst%20Client%20for%20MC%201.8.X/src/tk/wurst_client/mods/AutoSoupMod.java))
- Kryptonite
- Kronos
- Metro
- Argon
- Wolfram

There are some plugins that are able to detect autosoup, but they don't provide many features and it's generally easier to maintain this small detection in one plugin:
- [AntiAutoSoup by therealspoljo](https://www.spigotmc.org/resources/antiautosoup.555/)
- [Anti Auto Soup by maciekmmn](https://www.spigotmc.org/resources/anti-auto-soup.688/)

So, it would be really nice if you would add an AutoSoup detection in the future!
In addition, I don't want to use a separate plugin for only one detection.

**Comment by Photon-GitHub** [comment]
Instead of blocking and monitoring the Inventory actions I recommend to monitor if the player is sprinting/sneaking (high vl addition) or walking normally (normal vl addtion) when clicking in an inventory. This would also block AutoArmor, AutoPot, AutoRefill and InventoryMove.

**Comment by CeIebrimbor** [comment]
@Photon-GitHub Vanilla allows you to equip armor while sprinting, so that sounds like false positive city. I guess blocking the removal of armor of the player is in full sprint would be half a solution?

In my experience, there will be no effective way to block auto-soup since simply having a hotbar toggle would trip the detection and a small nugget of lag would label anyone who simply scrolls and eats a soup as a hacker. If it were added, I see it being a notify only check. Konsolas has never really mentioned if he was interested in even looking at inventory related checks.

**Comment by Photon-GitHub** [comment]
No this works perfectly as when equipping armor out of the hotbar no InventoryClickEvent is fired.
Just try my plugin, I already tested this.

**Comment by Photon-GitHub** [comment]
This is fixed by using my plugin.
