### ISSUE TITLE
Speed false positive start sneaking in the air

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#120]
When you sprint-jump and sneak right before landing you will get flagged for speed (vl 7).

**Comment by konsolas** [comment]
This never causes problems, and is unnatural.

**Comment by Photon-GitHub** [comment]
You don't need to do it in the end, normal sneaking in air while jumping is enough. Please reconsider as this can really spam a lot of detections when aac is running on a Parkour-based server.

**Comment by CeIebrimbor** [comment]
Well the idea is that (1)It will never get to lag-back or kick levels and (2), it is so uncommon that you're not going have a giant AAC log as a result of it being left ignored. 

This is similar to the old sprinting down stairs detections. It will never cause an issue, but it's so common that it _would_ make for insanely massive logs and verbose spam out the *ss.

Consider reclosing this @Photon-GitHub so he doesn't need to take time regurgitating the reasoning. He has enough issues to resolve and read.

**Comment by Photon-GitHub** [comment]
The problem is that I triggered a detection with almost every jump...
You pretty much always sneak when landing in a jnr if you are using advanced techniques.

**Comment by Photon-GitHub** [comment]
This would in fact generate massive logs on servers like playminity (jumpleague)

**Comment by CeIebrimbor** [comment]
Fair enough.

**Comment by Janmm14** [comment]
Maybe alternative solutions might be the better idea heŕe:
* turning of the first speed notification
* automatically compress logs

**Comment by konsolas** [comment]
The speed check rewrite of the rewrite has fixed this.
