### ISSUE TITLE
Heuristics pattern P/92 false positives

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1200]
### Issue description

The player used a speed II potion and ran into the attack.

Video: https://www.youtube.com/watch?v=XggcJ9BA4rw
Log: https://pastebin.com/RXKGC2r7

### Core information
**Server version**: 1.12.2 paper

**AAC version**: 3.3.9

**ProtocolLib version**: v4.4.0-SNAPSHOT

### Special environment information
**ProtocolSupport version**: buildnumber: 178

### Configuration
https://pastebin.com/WFQnG8DG

**Comment by Rerd** [comment]
Confirmed.

Two completely legit players, one actually fighting me when they got banned
`SmackM failed Heuristics: detected by pattern P/92 (confidence 81.4) [ping:37 tps:20.0] VL:2`
`Jeikuuu failed Heuristics: detected by pattern P/92 (confidence 78.2) [ping:109 tps:20.0] VL:2`
