### ISSUE TITLE
AAC Features / Fixes

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1201]
### Overview
Alright so basically I've had many complains and false positives with checks that I never thought would happen. Here to list a few checks that could be worked on, let me know what you think in the comments. I'll be updating in the comments if I think of anything else that could be improved.

**Criticals:**
I don't think I've ever had Criticals false positives until recently. Players are getting flagged for `_Blue_Potato_ failed Criticals: tried to perform a critical hit whilst on the ground [ping:1171 tps:20.0] VL:2` when they are having huge amounts of lag spikes and packet loss. I think AAC should automatically check if the player is having large amounts of lag spikes / packet loss and maybe automatically stop the player from flagging Criticals.

**FightSpeed:** (#1197)
Basically the same issue here is occurring as is with Criticals. Players that have huge lag spikes / packet loss are flagging FightSpeed for 30+ CPS. I recommend the same thing that I've said for Criticals.

### **Heuristics:** (serious issue)
When a player is laggy (200+ ping), they can get hits that are delayed which allows hits while the player is not looking at the enemy. This causes false flags for Heuristics pretty commonly. Not sure how you would be able to fix this, but some opinions from other people in the comments would help.

**Heuristics Patterns:** (3.3.12 HAS FIXED THIS)
<del>I’ve been having trouble with a few patterns. Here’s the list of them:</del>
    <del>- "P/29"</del>
    <del>- "P/59"</del>
    <del>- "P/72"</del>
    <del>- "P/92" (#1200) _fixed_</del>
    <del>- "P/96"</del>
    <del>- "P/97"</del>
    <del>- "P/99"</del>

**Killaura Normal:** (#953) (3.3.11 HAS FIXED THIS)
<del>I've made a post about this before but whatever, I'll add it to this one so we can close the other one. Alright, to be completely honest, either this check needs to be completely recoded or it just needs to go. This is the most useless and experience ruining check in the plugin. Combat is completely different when Killaura Normal is enabled, such as, hitting mobs instead of players causing for much different hit registration and increased reach because of how far off the invisible mobs are from the player. Another issue is how fighting someone with Normal on causes the effect of KeepSprint because you are attacking mobs, which is considered a cheat in competitive communities. The last issue is the endless false positives for players that either have high cps (12+ CPS) or high ping (150+ ping). My recommendation is to change invisible mobs to invisible players, fix the false positives as soon as possible and reduce the space in between the entity and the enemy by default.</del>

<del>_Old Post (#953): Killaura Normal is basically worst for pvping while you're legit. Because Normal spawns invisible mobs inside of the player, when you get someone in a combo, your sprint isn't stopped like it does normally because you are not actually hitting the player, but you are hitting the mobs. This can ruin combos and affect pvp on the server. Another issue with it is that since the Normal check spawns mobs that are a little bit outside of the player on each side, this can actually increase hitbox size and maybe even reach distance because they are spawned a bit too far out of the player. I know that can be fixed by changing the config, but it would be great to have it fixed with the default config. My recommendation that will fix the first issue with the sprint stopping is instead of spawning mobs inside of players, we should spawn players inside of players._</del>

- [ ] Criticals

- [ ] FightSpeed

- [ ] Heuristics

- [x] Heuristics Patterns

- [x] Killaura Normal

**Comment by Janmm14** [comment]
You can check for lag spikes with [ConditionalCommands](https://github.com/konsolas/AAC-Issues#conditional-commands), at least for thresholds.
As far as I know the killaura normal entities are 0.05 blocks away from the entity.

**Comment by Rerd** [comment]
I think the Killaura Normal entities are a bit behind the player's movements which allows hits over the limit.

**Comment by Toshka17** [comment]
The problem of using conditional-commands is that it checks the player's TPS and ping at the time the penalties are issued, but the detection of the cheat is performed some time before. since aac causes short-term drops in the server's TPS, this causes the AAC to detect the innocent players because of this, and by the time the VL reaches the threshold, the TPS and ping come to normal.

**Comment by konsolas** [comment]
Killaura Normal getting the requested changes (and some more) in 3.3.10

**Comment by Rerd** [comment]
Heuristics with around 200+ ping is becoming a huge issue.

**Comment by Rerd** [comment]
_Bump_ for issue with players ghosting and bans.
