### ISSUE TITLE
1.13 Aquatic Update - Planned

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#1202]
Since many will ask **"will AAC update for 1.13?"**, this issue will be created to both answer that question and track progress for development. The answer is **"yes, at some point"**... 😉 

- [x] ProtocolLib updated to 1.13

### Changes Needing Attention (most likely)
- [ ] New Mob & Mob mechanics (i.e. ride skeleton horse underwater)
- [ ] Trident Weapon
- [ ] Riptide Enchant (player launch in water & rain)
- [ ] New Blocks and Block IDs (Coral + Turtle Eggs)
- [ ] Water Mechanics (jump in flowing water)
- [ ] Dolphin's Grace potion (swim faster)
- [ ] Conduit Power (mining speed underwater)
- [ ] Blue Ice (more slip)
- [ ] Potion of Slow Falling
- [ ] Water Columns (magma & soul sand)
- [ ] Swimming Ability (sprint in water)
- [ ] Potion of Turtle Master (Slowness IV)
- [ ] Vine Placements (2 vines in same space)
- [ ] Anvil, Cauldron (+many other) Collision Block Changes

**Comment by FrankHeijden** [comment]
[ x ] new fish mobs
[ x ] magma blocks/soul sand under water

**Comment by CeIebrimbor** [comment]
Mob support covers fishes.

Water columns covers magma? What does souls sand do?

**Comment by FrankHeijden** [comment]
Same as magma but then the upwards, thought they weren’t specified yet

**Comment by ArrowReport** [comment]
Update this

**Comment by MerlinK11** [comment]
yes Please ! update this

**Comment by CeIebrimbor** [comment]
v4.0 (when released). Closing the checklist.
