### ISSUE TITLE
Async Teleportation

### ISSUE THREAD

**Issue by Jpx3** [konsolas/AAC-Issues#1203]
AAC throws an IllegalStateException while checking an asyncronous teleport event.

Error-Log: https://hastebin.com/isicimulub.lua

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.9

**ProtocolLib version**: /

**Plugin list**: /

### Special environment information
**ViaVersion version**: /

**ProtocolSupport version**: /

**ViaBackwards version**: /

**BungeeCord plugins**: /

**Comment by Janmm14** [comment]
Intended behaviour.
Bukkit API states at async task creation all bukkit api has to be considered non-thread-safe.
