### ISSUE TITLE
snow step?!

### ISSUE THREAD

**Issue by ImperatorBuzov** [konsolas/AAC-Issues#1206]
please fixed this is snow-step 2.1:

if(mc.thePlayer.isColliedHorizontally){
mc.thePlayer.onGround = true;

**Comment by Janmm14** [comment]
wanna stress the unimportance of snowstep

**Comment by ImperatorBuzov** [comment]
lol, this is bug

**Comment by Janmm14** [comment]
you are not detailed enough

**Comment by ImperatorBuzov** [comment]
aac 3.3.10, test on poke.sexu

**Comment by konsolas** [comment]
I might start a policy of rejecting all issues citing "poke.sexy" because of how people completely ignore the issue template.
