### ISSUE TITLE
Hitting a player while they are moving (sprinting) causes fly false positive (HOTFIX!)

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1207]
### Issue description
When a player is moving above a certain speed and they get hit, it will cause Fly false positives. This gets up to the maximum teleport VL in just 10 seconds of fighting (100VL)

### Core information
**Server version**: 1.8.8 Spigot

**AAC version**: 3.3.10

**ProtocolLib version**: If Requested

**Plugin list**: If Requested

### Configuration
Default config with Fly `min_vl` at 100

**Comment by Janmm14** [comment]
debug log?

**Comment by Rerd** [comment]
[Debug](https://ghostbin.com/paste/om5up/raw)
[Verbose](https://gyazo.com/1893bc3fdce3ef7a9a7003898b1f1352)

**Comment by Rerd** [comment]
Fixed in 3.3.10-b1!
