### ISSUE TITLE
Update AAC on the testserver

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#1210]
Its outdated af.

**Comment by Slimerblue22** [comment]
YES PLEASE UPDATE THE DARN THING

**Comment by ItsTigerss** [comment]
Pls. K thnx

**Comment by LinsaFTW** [comment]
I can build and configure it if konsolas give me the permission. https://imgur.com/a/DugF5

A good test server even if the anticheat was bad will increase the amount of costumers considerably.

And maybe some people will join just for fun... ;)

**Comment by Janmm14** [comment]
Konsolas already has a test server @LinsaFTW, it just needs an update to a recent AAC version.

**Comment by LinsaFTW** [comment]
@Janmm14 Its really bad. It needs a general udpate. AAC wont draw attention of new costumers that test like this. Its really unprofessional.

**Comment by Teals53** [comment]
test.kons.co is closed ?

**Comment by konsolas** [comment]
It's updated.
