### ISSUE TITLE
NoFall still works

### ISSUE THREAD

**Issue by martinm236** [konsolas/AAC-Issues#1212]
### Issue description
 I made AAC 3.3.10 NoFall from 30 blocks 0 damage.

Here is my video: https://youtu.be/WzxCbnEkr7E

### Core information
**Server version**: 1.8.X
   server: test.kons.co

**AAC version**: 3.3.10

**ProtocolLib version**: u know

**Plugin list**: u know

**Comment by konsolas** [comment]
In favour of #1267.
