### ISSUE TITLE
Elytra FPs

### ISSUE THREAD

**Issue by wulfwuud** [konsolas/AAC-Issues#1213]
### Issue description
Elytra FP's
https://streamable.com/rit7e
AAC LOG - https://hastebin.com/teconadewe.sql
SERVER LOG - https://hastebin.com/fifesuxuhu.md
 
### Core information
**Server version**:
git-Paper-ee2ec9fe (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
**AAC version**:
3.3.10
**ProtocolLib version**:
4.3.0
**Plugin list**: 
Nothing special here

### Special environment information
**ViaVersion version**: 
1.3.0
### Configuration
Default generated 3.3.10

**Comment by konsolas** [comment]
AAC has undergone major restructuring since this version.
