### ISSUE TITLE
Derp False Positive

### ISSUE THREAD

**Issue by Minemaniak** [konsolas/AAC-Issues#1215]
### Issue description
Person 1, with op/aac.bypass uses derp (tested with headless on wurst), and person 2, without bypass, teleports to the person 1. Person 2 gets detected for derp.

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.10-b1

**ProtocolLib version**: 4.2.0

**Plugin list**: (8): LuckPerms, WorldEdit, ProtocolLib, DummyHQAPI, WorldGuard, AAC, AACAdditionPro, ConditionalCommands

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Celebrimbor's config

**Comment by CeIebrimbor** [comment]
Interesting find. I don't even know if this is really needing a fix. Hopefully, your staff and OP players aren't using hacks. And if they are... at least they can be aware of that one "bug".

**Comment by Minemaniak** [comment]
This bug is totally irrelevant for me, as none of my staff, not even me, have bypass. I just thought it's may be worth a report or fix.
