### ISSUE TITLE
getUUID not available for temp player @cX.onPacketSending:7

### ISSUE THREAD

**Issue by Zeruska** [konsolas/AAC-Issues#1216]
### Issue description
I guess, the log tells everything. :)

https://pastebin.com/4Gyh4Sxy

Maybe its usefull for the fix.
https://github.com/filoghost/HolographicDisplays/commit/98e5827a8a0e33940454a7e6e1014a3d1c2baea4

### Core information
**Server version**: git-Paper-1155 (MC: 1.12)

**AAC version**: 3.3.9 (also 3.3.7 and 3.3.6)

**ProtocolLib version**: v4.4.0-SNAPSHOT-b390

**Plugin list**: -

### Special environment information
**ViaVersion version**: Not used

**ProtocolSupport version**: Not used

**ViaBackwards version**: Not used

**BungeeCord plugins**: Not used

### Configuration
Default settings!

**Comment by Zeruska** [comment]
Dear @konsolas !

When can I expect the bug fix?

**Comment by Janmm14** [comment]
It might spam the log, but it should at most happen shortly after login and shouldn't cause any harm.

**Comment by Zeruska** [comment]
@Janmm14 No, its happens more times, like an infinit loop.
And server going unreachable, players can't connecting!

https://pastebin.com/8uq7QCqg
