### ISSUE TITLE
Fly flag mining downwards

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#1219]
### Issue description
I mined Sandstone with a normal diamond pickaxe on localhost.

Flags apparantly not always.

VL does not stop climbing when getting setback.

_Debug log 3.3.9:_
[debug.cc168709-3969-472b-b3e4-caf36af9d421.debug.log](https://github.com/konsolas/AAC-Issues/files/1752801/debug.cc168709-3969-472b-b3e4-caf36af9d421.debug.log)

_Debug log 3.3.10-b1:_ (Just second try flagged)
[debug.b28243bd-7414-428f-aa0c-e7169afd0824.debug.log](https://github.com/konsolas/AAC-Issues/files/1752890/debug.b28243bd-7414-428f-aa0c-e7169afd0824.debug.log)

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 3.3.9 / 3.3.10-b1

**ProtocolLib version**: 4.1

**Plugin list**: AAC, ProtocolLib, PermissionsEx, WorldEdit

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
In debug log. (default generated)

**Comment by konsolas** [comment]
This doesn't seem to be an issue anymore.
