### ISSUE TITLE
[AAC 3.3.11 RC] Speed setbacks let you phase trough chests without cheats.

### ISSUE THREAD

**Issue by Minemaniak** [konsolas/AAC-Issues#1224]
### Issue description
You can glitch yourself into chests without cheats and phase trough them quite easily. Speed setbacks allow it, sometimes it even flags on chat / kicks for speed while doing this.

Video: https://www.youtube.com/watch?v=0wTnCvAOMU8&feature=youtu.be

SERVER INFO: test.kons.co, AAC 3.3.11 RC

**Comment by Janmm14** [comment]
Please report beta and release candidate bugs in the discord channel feedback
