### ISSUE TITLE
[AAC 3.3.11 RC] Speed glitch with stone slabs

### ISSUE THREAD

**Issue by Minemaniak** [konsolas/AAC-Issues#1225]
### Issue description
It's hard to reproduce, but sometimes when running near stone slabs, barerly touchng them, you can get stopped totally, speed check holding you in place, and kicking you after few seconds.

https://imgur.com/T9ZZj7a <- Screenshot of example place where you can get glitched 

Server info: test.kons.co, AAC 3.3.311 RC

**Comment by Janmm14** [comment]
Please report beta and release candidate bugs in the discord channel feedback

**Comment by Minemaniak** [comment]
Ok, people told me there to also report it here, so I did. On that channel it's hard to tell if anyone has read it or not.

**Comment by Janmm14** [comment]
leave them open
