### ISSUE TITLE
Water Speed Bug

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#123]
At the edge of a block, if there's water and if you sprint half in and half out, you get flagged for Speed. This video should explain: https://www.youtube.com/watch?v=d8gSHOB3irc

**Comment by Janmm14** [comment]
\**click**
[![AAC v3.0 Criticals false positive](http://img.youtube.com/vi/VETorGx6RtY/0.jpg)](http://www.youtube.com/watch?v=VETorGx6RtY"AAC v3.0 Criticals false positive")

**Comment by konsolas** [comment]
Fixed and tested by myself.
