### ISSUE TITLE
Jumping underneath blocks while sprinting = speed

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1231]
### Issue description
Jumping and sprinting at the start of a block causes speed to false flag, gets annoying when running away from players in fights then getting glitched back and killed.
[Video](https://youtu.be/bxjIxn0BbLE)
[Debug](https://github.com/konsolas/AAC-Issues/files/1756799/debug.9d74673d-d4d4-4a43-8441-73d7477b1332.debug.log)

### Core information
**Server version**:  git-Spigot-db6de12-18fbb24 (MC: 1.8.8)

**AAC version**: 3.3.10-b1

**ProtocolLib version**: if requested

**Plugin list**: if requested

### Configuration
Custom Config and Default

**Comment by Janmm14** [comment]
From issue 1296:
https://streamable.com/yo642

**Comment by Rerd** [comment]
Bumping this because it's somewhat critical.
