### ISSUE TITLE
Cancel_vl_place BUG + false positives of interact check

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1232]
### Issue description
Players often complain that the building blocks suddenly disappear. Example: https://yadi.sk/i/IYrhv2PD3SkbwJ   (mid of video)

Video with verbose-mode: https://youtu.be/3wTfWs38PQU
As you can see from the video, they disappear due to false positives of Interact-check.

But I set "cancel_vl_place" to 14, but VL in verbose-mode never goes beyond 9. Then why does the block installation fail?

You could add more comments to interact check? Because it's not entirely clear. for which this test and each of its parameters are responsible. Write down which cheats are affected by the parameters more specifically.

### Core information
**Server version**: paper 1.12.2

**AAC version**: 3.3.9

**ProtocolLib version**: v4.4.0-SNAPSHOT

### Configuration

https://pastebin.com/zm3YFi4R

**Comment by Rerd** [comment]
#1036
