### ISSUE TITLE
False kick Move

### ISSUE THREAD

**Issue by Henriks9** [konsolas/AAC-Issues#1233]
### Core information
**Server version**:Test Server

https://www.youtube.com/watch?v=Zbqgd1gVMpQ&feature=youtu.be

**Comment by Rerd** [comment]
Unable to recreate?

**Comment by konsolas** [comment]
Not getting this :/

**Comment by Minemaniak** [comment]
I can get it pretty easily, vanilla 1.8.8, just holding lmb on flower while having sword im hand. It kicks for speed (too many uses)

**Comment by CeIebrimbor** [comment]
I’ve seen this. You have to raise max_use_toggles in speed to avoid it. It is technically an incompatibility with land claims (maybe not all types), so I will label Compatibility.

**Comment by Rerd** [comment]
I can now recreate this. Easier to reproduce with lower ping and with a sword/bow in your hand.
