### ISSUE TITLE
1.12 clients on 1.8 server are stuck in/fall through SOIL

### ISSUE THREAD

**Issue by MineTheCube** [konsolas/AAC-Issues#1237]
Duplicate of:
- #1176 
- #922 

Version of AAC involved: `3.3.10`
![gif](https://i.imgur.com/GCCrpMa.gif)

Sometimes the player falls through soil, sometimes he is kicked for `speed` or `knockback`.

**Comment by Janmm14** [comment]
Duplicateof #922
