### ISSUE TITLE
Killaura check went incompatible with "see invisibles" option of teams

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#1239]
AAC 3.3.11

Either add option so aac overrides invisibility option for  teams or state it'll be incompatible.

Edit: See #1261

**Comment by d4d3boss** [comment]
Thanks

**Comment by konsolas** [comment]
Going to add a new option to use mobs. 1.8.8 has a client side limitation with nametags and invisibility.

**Comment by Janmm14** [comment]
oh :(

**Comment by Minemaniak** [comment]
Maybe add config option to not spawn players that in the same team?

**Comment by Janmm14** [comment]
@Minemaniak just look at #1261

**Comment by Minemaniak** [comment]
Sorry, I forgot about that one
