### ISSUE TITLE
Name duplication problem

### ISSUE THREAD

**Issue by BlackDemonZetaxd** [konsolas/AAC-Issues#1242]
There is a name duplicating problem in AAC new version:
https://imgur.com/a/gmZTP
Also, the NPCs that flies arround you to find a killaura hacker, gets duplicated.

**Comment by Rerd** [comment]
Neither of these are issues, they’re both features.
These are a part of the remade Killaura check.
Turn off your esps so you cannot see them or don’t cheat.

**Comment by BlackDemonZetaxd** [comment]
Is  happening the same without ESP .-.

**Comment by Janmm14** [comment]
Duplicate of #1239
