### ISSUE TITLE
Can Walk over one block with 'AirWalk'

### ISSUE THREAD

**Issue by BlackDemonZetaxd** [konsolas/AAC-Issues#1243]
You can walk over one block with Wolfram Client 1.8 (AirWalk hack)
Here is the video:
https://www.youtube.com/watch?v=k54XdmfPkYQ&feature=youtu.be
I'm using the latest version of AAC with all the config identical.

**Comment by Rerd** [comment]
You can actually walk over 1 block gaps legitimately just by sprinting. Not only would this be unimportant, but it’s also invalid since it’s not really a bypass.

**Comment by BlackDemonZetaxd** [comment]
Its a bypass, as you can see i can do it without sprinting -..-

**Comment by Rerd** [comment]
This is really unimportant. You can do that with every client. Also what even is the point in flying over a 1 block gap when you can just jump over even not while sprinting.
