### ISSUE TITLE
New KillAura Check Broken - 3K Entities, Visible Entities, Error in Log

### ISSUE THREAD

**Issue by SioWolf** [konsolas/AAC-Issues#1245]
### Issue description
After updating to the new version of AAC several players are reporting very low FPS on the server and "mobs that just follow them around but can't hurt them".

It appears that the new KillAura check is spawning up to 3K entities around the player and this is the cause of the low FPS. After disabling KillAura the entity count in F3 drops to around 500. The mobs that it spawns are also visible to regular players, in fact three players reported seeing the mobs within 4 hours of updating (and we update over night when there are usually only 3 players online).

I believe all of this is also related to the console error reported in #1240.

Screenshots of visible mobs (submitted by players): https://imgur.com/a/IpiUP

### Core information
**Server version**: git-Paper-1337 (MC: 1.12.2)

**AAC version**: 3.3.11

**ProtocolLib version**: 4.4.0-SNAPSHOT-b390

**Plugin list**: https://gist.github.com/d852c7d57c265336c2da31fb12cf185d

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: 2.3.1

**BungeeCord plugins**: N/A

### Configuration
Using Celebrimor's Ghost Config v 3.3.11

**Comment by Rerd** [comment]
Possible solution:
Limit the amount of amount of entities that can be behind you and disable it for certain mobs (blazes, endermen, spiders, etc.).
