### ISSUE TITLE
Invisible mobs critical Bug

### ISSUE THREAD

**Issue by zBoringDrop** [konsolas/AAC-Issues#1248]
### Issue description
So, all players see randomly invisible mobs behind they (immortal mobs).
And also randomly, AAC spawns random smoke particles.
In this time, AAC show this: https://pastebin.com/QNZ9jyKv
This are 2 screen of effects in game: https://imgur.com/a/zsRRN

### Core information
**Server version**: 1.12

**AAC version**: 3.3.11

**ProtocolLib version**: 4.3.0

### Special environment information
**ViaVersion version**: 1.3.0

**ViaBackwards version**: 2.3.1
+ Viarewind

### Configuration
This error happens only when i replaced 3.3.10 to last 3.3.11

**Comment by Rerd** [comment]
#1245
