### ISSUE TITLE
LiquidBounce Killaura Bypasses Heuristics Perfectly

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1251]
### Issue description
Latest versions of LiquidBounce bypass heuristics like it's not even there.

For any more info, ask.

### Core information
**Server version**: Paper 1.8.8

**AAC version**: 3.3.11-b1

**ProtocolLib version**: if requested

**Plugin list**: if requested

### Configuration
Custom Config with Heuristics confidence at 78%. Though it bypasses on the official test server aswell.

**Comment by BlackDemonZetaxd** [comment]
Can i see a video?

**Comment by konsolas** [comment]
Heuristics getting big updates.

**Comment by EthanTG** [comment]
hi this is my first comment

**Comment by tigrecode** [comment]
AAC combat and heuristic checks are very good. Also the dragdown with fly flags is good. But why did you disable setbacks in the Move check? A timer speed works...

**Comment by tigrecode** [comment]
Add pattern 1337 for ultra rotation checks LOL

**Comment by SenkJu** [comment]
https://www.youtube.com/watch?v=fxJ_o2Yu8QY @BlackDemonZetaxd Youre welcome

**Comment by superblaubeere27** [comment]
This is the deadly joke from Monty Python ^^ LMAO. This joke have to be stopped!
