### ISSUE TITLE
Auto Respawn  = Move

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#1255]
Latest AAC

**Comment by Rerd** [comment]
Auto respawn also causes speed flags. Last tried on 3.3.9.

**Comment by Janmm14** [comment]
Debug logs are neat.

**Comment by Janmm14** [comment]
Normla respawn not?

**Comment by Rerd** [comment]
No, not normal respawn.

**Comment by konsolas** [comment]
Should be a fix for Move cancelling teleports.

**Comment by Janmm14** [comment]
@konsolas This doesn't cancel teleports.

**Comment by konsolas** [comment]
I know, it's the same issue as the teleport one
