### ISSUE TITLE
Limit Invisible Entities Behind Players

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1256]
For the “Killaura” check, there should be a configuration option to set a limit to the amount of invisible entities are shown behind a player. This should limit both mobs and players behind the player. Bigger servers with more players in a smaller area could have performance issues when there are a ton of players with each of them having invisible entities of each player around them behind them.

Ex. server with 50 players: If a server has 50 players, and it’s an FFA server or something, each of the 50 players will have around 49 invisible entities behind them. This could possibly impact performance on some servers.

**Comment by BlackHawk2306** [comment]
Also you got 49 Nametags behind you(why is that a thing again?) ._.
I still don't get why it aren't just 2 or 3 bots anyways, if you don't hit 2, you probably won't hit the 10 others at the same spot ( ± 1 block) either I guess

**Comment by konsolas** [comment]
Removing the entities behind players.
