### ISSUE TITLE
Piston movement

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#126]
Could you please enable the piston allowed to move blocks flag on the test server (otherwise the speedrace redstone-mechanics are not working).

**Comment by Janmm14** [comment]
(location: below the block edge testing; if you go down the waterfall test (after you went the big waterfall up)

**Comment by konsolas** [comment]
Since I'm not sure what crazy redstone contraptions will be built in the future, I've given the TESTER rank full worldguard permissions to change the regions as they see fit.

Please maintain some degree of control over building as the server is public.
