### ISSUE TITLE
Fly Bypass Near or In water

### ISSUE THREAD

**Issue by Reeferx7** [konsolas/AAC-Issues#1260]
### Core information
**Server version**:  1.8.8

**AAC version**: 3.3.11

**ProtocolLib version**:  4.4.0-SNAPSHOT-b390

**Plugin list**: No Plugins (Test Server)

I can fly near on in water with hackclient.

Here a video im not OP, at the end of the video i move away from water and i fall.

https://i.gyazo.com/aca188090575f8acd42b3f30831bea57.mp4

**Comment by Rerd** [comment]
This does work.

**Comment by konsolas** [comment]
Gyazo link is down

**Comment by Reeferx7** [comment]
sorry, check this
https://i.gyazo.com/aca188090575f8acd42b3f30831bea57.mp4
