### ISSUE TITLE
The dragon is now a killaura bot

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#1262]
Funny story, AAC will use the ender dragon as a kill aura bot :p its not even invis so you just have a dragon ontop of you

**Comment by Slimerblue22** [comment]
![image](https://user-images.githubusercontent.com/29098956/36941722-16d305be-1f30-11e8-9ff2-7d4dea53e0a6.png)
**AAC now comes with your very own pet dragon**

**Comment by Rerd** [comment]
Slight note, a ghast and giant works too.
