### ISSUE TITLE
null

### ISSUE THREAD

**Issue by FrankHeijden** [konsolas/AAC-Issues#1266]
### Issue description
https://paste.md-5.net/xuxosaxigu.java
https://paste.md-5.net/fafedowupo.avrasm

### Core information
**Server version**: CraftBukkit version git-Spigot-4bd94dc-fb414fe (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**AAC version**: 3.3.11-b1

**ProtocolLib version**: ProtocolLib v4.4.0-SNAPSHOT-b390

**Plugin list**: n/a

### Configuration
cel's

**Comment by Janmm14** [comment]
First one likely duplicate of #1254 

Second one not enough information.
A bug report about movement checks requires more information about the situation.

Use /aacdebug to toggle debug logging to a file in `plugins/AAC`.

Additionally it would be great to have a short description of the actions done - were blocks build, broken near you?

Verbose information alone is not enough to  fix false positives.

**Comment by FrankHeijden** [comment]
Nono, this is all one issue, i used the aaclog for displaying what happened while the error occured as i couldn’t replicate

**Comment by Janmm14** [comment]
Can you search your log form the start where the error is bigger please?

**Comment by FrankHeijden** [comment]
Its not bigger, i copied this directly from my log file, it is just like this lol.

**Comment by Janmm14** [comment]
The error is defintiely shortend by the java runtime which just happens after some time if the error happens often.

**Comment by FrankHeijden** [comment]
https://paste.md-5.net/wesaledoma.java

**Comment by Janmm14** [comment]
Ok, its the same error as in #1254, thanks for checking again.
