### ISSUE TITLE
task Y

### ISSUE THREAD

**Issue by FrankHeijden** [konsolas/AAC-Issues#1268]
### Issue description
[![Screenshot from Gyazo](https://gyazo.com/8d2329c9bb9055d2cc2f0279390a5318/raw)](https://gyazo.com/8d2329c9bb9055d2cc2f0279390a5318)

also, world - tracker seems to be VERY high

[![Screenshot from Gyazo](https://gyazo.com/2d0a6ce1e101d7f5b5da868bb22ee84b/raw)](https://gyazo.com/2d0a6ce1e101d7f5b5da868bb22ee84b)
what is this task and why is it so heavy?

**Comment by Janmm14** [comment]
I think its part of the enable process. Reset timings after AAC is loaded and it will disappear.

**Comment by konsolas** [comment]
@Janmm14 is correct.

Task Y is the enable task. It is executed when the server starts and enables all checks in AAC. It is a one-time cost and does not affect the server while it is running.
