### ISSUE TITLE
False Positive | Move false positive

### ISSUE THREAD

**Issue by craftrise** [konsolas/AAC-Issues#1269]
Tested in test.kons.co. 
Client version: 1.8.9

AAC version:
http://prntscr.com/impts1

False positive: https://gyazo.com/097c1d633a019d00697b8237631bd812

**Comment by Minemaniak** [comment]
Duplicate of https://github.com/konsolas/AAC-Issues/issues/1231

**Comment by Janmm14** [comment]
Duplicate of #1231
