### ISSUE TITLE
Akrien WaterSpeed Bypass

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1273]
WaterSpeed bypass on Akrien version 4.2.
[Here is the debug log.](https://github.com/konsolas/AAC-Issues/files/1783023/debug.eb4ad81f-e5f4-4f3d-95d9-9a8558fe93f0.debug.log) (Player933).

### Core information
**Server version**: PaperSpigot 1.8.8

**AAC version**: 3.3.11-b1

**ProtocolLib version**: if requested

**Plugin list**: if requested

### Configuration
Custom Config. Jesus, Speed and Fly left at default settings.

**Comment by konsolas** [comment]
Merging with #1226
