### ISSUE TITLE
LiquidBounce Bhop Bypass ~7%

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1275]
LiquidBounce b39's speed mode AAC7 bypasses. It looks to be around 7% faster.
You can either test it yourself or look at the debug [here](https://github.com/konsolas/AAC-Issues/files/1783015/debug.f0cf6b2e-b586-41cb-80fe-50ed26156c53.debug.log) (Slimerblue22).

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 3.3.11-b1

**ProtocolLib version**: if requested

**Plugin list**: if requested

### Configuration
Custom Config. Speed values are default.

**Comment by konsolas** [comment]
It's a timer speed.

**Comment by Rerd** [comment]
that makes a lot of sense

**Comment by Rerd** [comment]
Still works, tested on LiquidBounce b44.
