### ISSUE TITLE
NAMETAGSEDIT

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1277]
### Issue description
Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**:  spigot 1.8.8

**AAC version**: 3.3.11-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: insert

### Special environment information
**ViaVersion version**: NO use it

**ProtocolSupport version**:  NO use it

**ViaBackwards version**:  NO use it

**BungeeCord plugins**: insert (or N/A)

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

**Comment by leoncp9** [comment]
nametags edit with aac don't work

**Comment by Janmm14** [comment]
1. i do not like your attitude towards the issue template
2. does it work with "killaura" check off?

**Comment by leoncp9** [comment]
Hi! Killaura work (i need to set her because i have a lot false positive), but plugin NametagEdit don't show correctly name of players, (3.3.11-b1)
