### ISSUE TITLE
AAC randomly cancels teleport event, this bug is back!

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#1278]
Teleporting players will occasionally trigger the speed check and they'll not be teleported.
Related to #850  and #1046, this issue came back after updating to 3.3.11-b1
Please fix asap as this is critical to my minigame.

**Comment by Janmm14** [comment]
Debug log please.

**Comment by MClausz** [comment]
https://pastebin.com/vn3MWFJ1
This is the debug log at the time MasterClaus's teleportation get canceled

**Comment by Janmm14** [comment]
That is not a debug log, but verbose log.
To toggle debug logging use /aacdebug command.

**Comment by MClausz** [comment]
I can hardly do a debug log for this bug

**Comment by konsolas** [comment]
Should be a fix for the Move check cancelling teleports.
