### ISSUE TITLE
Shield/Bow Bug, spamming right click.

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#128]
If you sprint and right click with a shield every second, it flags you and kicks you for speed.

**Comment by konsolas** [comment]
Having tried to reproduce this on the test server, it seems to be extremely hard to do, and neither me/Janmm14 were able to get a large number of violations.

Although this seems to be a bug, it is unnatural and rare to reproduce.

**Comment by Janmm14** [comment]
@konsolas 
Its not that hard to reproduce it and I think normal people would also get this as some people tend to spamclick always.
I created a video about this: https://www.youtube.com/watch?v=3xqd3Aeh3jc
Also the vl can get up to 30 or maybe even higher.
Maybe you could block the blocking also as aworkaround if people spamclick too often.

**Comment by Photon-GitHub** [comment]
Can also lead to a kick if spamming the bow and can kick players or let them reach high vls very quickly.
