### ISSUE TITLE
Nametag duplication during newest updates

### ISSUE THREAD

**Issue by Tyloonie** [konsolas/AAC-Issues#1280]
### Issue description
After updating the plugin recently, nametags (using AnimatedNames) are somehow duplicated for the last group setup.

Showcase: https://prnt.sc/io1zm8

### Core information
**Server version**: 1.12.2

**AAC version**: Newest 3.3.11

**ProtocolLib version**: 4.4.0

**Plugin list**: AnimatedNames, AAC

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: 4.29

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Simple disabling the KillAura check in AAC config.yml fixes the issue.

**Comment by konsolas** [comment]
#1239 and similar
