### ISSUE TITLE
Head in water and body in lava causes fly flags

### ISSUE THREAD

**Issue by tigrecode** [konsolas/AAC-Issues#1283]
### Core information
**Server version**: 1.8.x

**AAC version**: 3.3.11

**ProtocolLib version**: 3.4.0

**Plugin list**: aac, protocollib, essentials

**Comment by Janmm14** [comment]
I dont see any valid reason why someone would build such a map and disable physics

**Comment by tigrecode** [comment]
In the soup scene, and lava challenges there are many of these maps. It's not like that unimportant.

**Comment by konsolas** [comment]
Too nuanced to be worth fixing.
