### ISSUE TITLE
Request: Add version 1.8.0 

### ISSUE THREAD

**Issue by tigrecode** [konsolas/AAC-Issues#1285]
AAC doesn't work for me in the 1.8.0 correctly. A bunch of errors and vanilla fly works. Please add this version, you can **do** it! 😉

**Server version**: 1.8.0

**AAC version**: 3.3.11 LATEST

**ProtocolLib version**: 4.3.0 LATEST

**Plugin list**: ACC, ProtocolLib, Essentials

**Comment by Photon-GitHub** [comment]
Trolling issue.
