### ISSUE TITLE
TPS drop on latest version of AAC

### ISSUE THREAD

**Issue by CertainLach** [konsolas/AAC-Issues#1287]
### Issue description
Latest version of AAC causes massive TPS drop, as you can see here: https://timings.spigotmc.org/?url=hodewuwobu

### Core information
**Server version**: 3d850ec-809c399 (1.12.2)

**AAC version**: 3.3.11-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: 
- Citizens 
- WE/WG
- FAWE
- + Custom written

### Configuration
https://www.diffchecker.com/EXKZBxUd

**Comment by Janmm14** [comment]
Disable "killaura" check of AAC. killaura will still get detected by hitbox and heuristics check.
