### ISSUE TITLE
/Home on air bug

### ISSUE THREAD

**Issue by zBoringDrop** [konsolas/AAC-Issues#1289]
### Issue description
So, if a player set his home on air, AAC report him when he do /home (and has the home on air)
AAC Log Info: mediafire.com/file/uton9tso3rlfxgl/aac.log
SERVER log info (Can you understand where the player write /Home?): https://imgur.com/a/upslA

### Core information
**Server version**: 1.12

**AAC version**: 3.3.11 - b1

**ProtocolLib version**: 4.3.0

### Special environment information
**ViaVersion version**: 1.3.0

**ViaBackwards version**: 2.3.1
+ ViaRewards

### Configuration
None, same config of AAC previous versions

**Comment by konsolas** [comment]
Can't find punisher action for "XLobbs" in the logs

**Comment by zBoringDrop** [comment]
Can you execute this?
I cant now
