### ISSUE TITLE
PlayerTags duplicated

### ISSUE THREAD

**Issue by craftrise** [konsolas/AAC-Issues#1294]
### Issue description
Player tags duplicated.

Link: http://prntscr.com/iqiig2

Core information
**Server version**: 1.8.8 (CUSTOM)

**AAC version**: 3.3.12

**ProtocolLib version**: 4.2.0

**Plugin list**: CUSTOM (No NameTagEdit and others...)

**ViaVersion version**: Latest

**Comment by EthanTG** [comment]
first

i'm very informitive

**Comment by Rerd** [comment]
Fix this by disabling 'use_players' in the Killaura check.

**Comment by craftrise** [comment]
@Janmm14 
I tested with 1.12.2 server, again not fixed this bug. (This is not a client bug. %100)

Link: http://prntscr.com/ismhri

(LATEST AAC, 4.3.0 PROTOCOLLIB)

**Comment by Janmm14** [comment]
To fix your issue disable use players option.
