### ISSUE TITLE
Speed FP

### ISSUE THREAD

**Issue by DasCanard** [konsolas/AAC-Issues#1296]
### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.12

**ProtocolLib version**: 4.3.0

**Plugin list**: AAC, ProtocolLib

Video: https://streamable.com/yo642
Jump to the Edge of the Block

**Comment by Rerd** [comment]
Duplicate of #1231.

**Comment by DasCanard** [comment]
@Rerd sorry i dont saw it
