### ISSUE TITLE
Killaura FP

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#1297]
Video: https://www.youtube.com/watch?v=t7LI5WVe3Y8
Log: https://hastebin.com/otatesuzex.vbs

**Comment by Rerd** [comment]
Maybe an issue with stacked mobs?

**Comment by konsolas** [comment]
Again, killaura changes should theoretically fix this.

**Comment by Hyronymos** [comment]
another video: https://www.youtube.com/watch?v=8id_1GcHjJ8

Maybe it helps to understand the bug more
