### ISSUE TITLE
Feature request: API for toggling check for only one player

### ISSUE THREAD

**Issue by CertainLach** [konsolas/AAC-Issues#1298]
### Issue description
This isn't an issue.
Something like
```java
void disableCheck(Player player, HackType hackType);
void enableCheck(Player player, HackType hackType);
```
would be awesome

**Comment by Minemaniak** [comment]
+ maybe
void disableCheck(Player player, HackType hackType, int ticks);
void enableCheck(Player player, HackType hackType, int ticks);

To bypass it for certain time?

**Comment by konsolas** [comment]
The current method via the API is to cancel PlayerViolationEvent for bypassed players.

I wrote a small class some time ago which can be used for the time being: https://gist.github.com/konsolas/2cfac653a69668d1318c
