### ISSUE TITLE
1.12 levitation effect is causing many false positives with AAC

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#1299]
Video: https://www.youtube.com/watch?v=oNAjgC09NkE&feature=youtu.be
False positives include: Fly, Jesus, Criticals, and sometimes velocity (hard to reproduce velocity however) 

### Core information
**Server version**: 
![image](https://user-images.githubusercontent.com/29098956/37476923-c3afd684-284c-11e8-8f3d-44e09d459588.png)

**AAC version**: 3.3.11 (Probably would happen on 3.3.12 still) *Can confirm it happens on 3.3.12*

**ProtocolLib version**: 4.3.0

**Plugin list**: On request (Nothing that effects potion effects)

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: None

**ViaBackwards version**: None

**BungeeCord plugins**: On request (Nothing that effects potion effects)

### Configuration
Nothing that should effect it, happens on default config as well if the checks are on.

**Comment by ArtNRG** [comment]
Criticals+levitation FP confirmed on AAC v3.3.15
Paper version git-Paper-1436 (MC: 1.12.2)
ProtocolLib v4.4.0-SNAPSHOT-b397
