### ISSUE TITLE
[Bypass] NoFall bypass (Jump mode)

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#13]
You can easily avoid fall damage by sending one onGround - packet right before the landing and after that always jumping as long as you are not in water. (If you time this right you can always avoid fall damage even with normal clients, just keep jumping) - works on all versions

**Comment by konsolas** [comment]
Does the on-ground packet just before landing not lead to fall damage?

**Comment by Photon-GitHub** [comment]
Nope thats the point of the jumping because if you do not jump you will get fall damage afterwards.
Code snippet out of AlphaCentauri:
`} else if(this.mode.value == ModuleNoFall.Mode.GroundSpoofJump) {
            if(event instanceof EventPacketSend) {
               if(((EventPacketSend)event).getPacket() instanceof C03PacketPlayer) {
                  ((C03PacketPlayer)((EventPacketSend)event).getPacket()).onGround = false;
               }
            } else if(event instanceof EventTick && AC.getMC().getPlayer().onGround) {
               AC.getMC().getPlayer().jump();
            }
         }`

**Comment by konsolas** [comment]
Do you mean that onground stays false from the jump to water?

**Comment by Janmm14** [comment]
Looks like onground stays false always and the player can't stop jumping.

I think he means that you can only disable NoFall in water to not recieve the fall damage afterwards.

**Comment by Photon-GitHub** [comment]
Yes, you can only prevent NoFall damage as long as you are jumping (not onGround) or just by going to the next water and disabling the mod there.

**Comment by konsolas** [comment]
A fix has been put on the test server. @Photon-GitHub need confirmation.

**Comment by konsolas** [comment]
Patched and tested by @Photon-GitHub
