### ISSUE TITLE
Sprint jumping on ice false positives [1.10.2 only]

### ISSUE THREAD

**Issue by v0idst4r** [konsolas/AAC-Issues#130]
Sprint jumping on ice in 1.10.2 will 90% of the time false positive. Tested on aac3.kons.co. It could possibly be because of minecrafts slipperiness mechanics.

**Comment by Janmm14** [comment]
The test server is 1.10.2-only I thought?!

**Comment by v0idst4r** [comment]
It isn't. Wurst and most other clients are only 1.10.

**Comment by CeIebrimbor** [comment]
@konsolas Server 1.10 or 1.10.2?

**Comment by v0idst4r** [comment]
It supports both

**Comment by Janmm14** [comment]
Oops sorry I thought protocol version changed.

**Comment by konsolas** [comment]
Despite my best efforts, I was unable to reproduce this. 

Test case: http://i.imgur.com/6eIfcLu.png

**Comment by v0idst4r** [comment]
@konsolas I found the cause to be because I was using an elytra.
