### ISSUE TITLE
Command /aacadmin makes lag

### ISSUE THREAD

**Issue by arturek1666** [konsolas/AAC-Issues#1301]
**Server version**: 1.12.2 PaperSpigot

**AAC version**: 3.3.10

**ProtocolLib version**: 4.3.0

**Plugin list**: insert

### Special environment information
**ViaVersion version**: Newest 

**ProtocolSupport version**:  Newest 

Everytime I use /aacadmin it laggs the server until the command will work

	
AAC::Command: AAC:aacadmincount(1)  total(37.36% 13.954s, 167.12% of tick)avg(13,954.13ms per - 83.56ms/0.01 per tick

**Comment by Minemaniak** [comment]
Duplicate https://github.com/konsolas/AAC-Issues/issues/1160
