### ISSUE TITLE
Aimbot ByPass

### ISSUE THREAD

**Issue by BlackDemonZetaxd** [konsolas/AAC-Issues#1303]
I recenly uploaded a Killaura ByPass too that was doing more or less the same, but here its just aimboting, not auto attacking :)

Video of the ByPass: https://www.youtube.com/watch?v=ijuqP1zkk9Y&feature=youtu.be

Version of AAC: The latest 👍

Protocol Lib version: The latest

Details of the video: This client also has PacketAimbot that is also not detected well. I am sure this public client will have bypasses for more AAC checks, as it is very recent and its focused on bypassing AAC.
Also, in the end of the video, i got kicked, but im NOT kicked for the AntiHacks, is a bug with my server and 1.9+ versions :)

Name of the client: BinaryMiasma 1.11.2

**Comment by konsolas** [comment]
Can't do anything without more information on the client.

**Comment by konsolas** [comment]
Merging with #1300
