### ISSUE TITLE
[Suggestion] HeuristicViolationEvent

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#1305]
### Issue description
It would be useful to have a HeuristicViolationEvent in AAC which would have the following methods;
String pattern = e.getPattern();
double confidence = e.getConfidence();

This would give you the ability to ban for certain patterns on a higher confidence. Pretty useful if a pattern has lots of false positives.

**Comment by Minemaniak** [comment]
It is already added in AACAdditionPro https://www.spigotmc.org/resources/aacadditionpro.33590/
If you don't want to use it, or can't afford it, you can parse e.getMessage() from AAC's PlayerViolationEvent to get confidence and pattern.

**Comment by iConfueZ** [comment]
What´s the alternative solution? @Janmm14

**Comment by Janmm14** [comment]
Use PlayerViolationEvent and parse the message, just like Minemaniak said.

**Comment by iConfueZ** [comment]
The goal of the event is not the have alerts showing the confidence/pattern, but to ban for certain patterns only on a certain confidence, which is not possible to do with e.getMessage(). Not really an alternative solution imo.

**Comment by Minemaniak** [comment]
Why isn't it possible? There's no difference between event you want and parsing e.getMessage()

**Comment by Janmm14** [comment]
@iconfueZ
The PlayerViolationEvent is called for every verbose message. Verbose messages of heuristics include the pattern and the confidence.
