### ISSUE TITLE
Add compatibility to LauncherX

### ISSUE THREAD

**Issue by Tyloonie** [konsolas/AAC-Issues#1306]
Hello! Sorry for refraining from the usual application, this will only take a second.

I was wondering if it was possible to add compatibility or a hook into LauncherX and similar plugins in terms of movement, fly, speed etc.

Link to LauncherX Spigot: https://www.spigotmc.org/resources/launcherx.38930/
Link to LauncherX GitHub: https://github.com/Derkades/LauncherX

Thanks!

**Comment by konsolas** [comment]
It is up to other plugins to use AAC's API if they want to provide compatibility - it's not reasonable to include hooks in AAC for 100+ other plugins.
