### ISSUE TITLE
AAC Fast speed like 84584584854858458 blocks in 1 sec

### ISSUE THREAD

**Issue by Monstercide** [konsolas/AAC-Issues#1307]
**Server version**: 1.8.8

**AAC version**: 3.3.12

**ProtocolLib version**: latest

**Plugin list**: AAC PROTOCOLLIB

**ViaVersion version**: no

**ProtocolSupport version**: no

**ViaBackwards version**: no

**BungeeCord plugins**: no

video - https://www.youtube.com/watch?v=SMXa97Dz5F0

**Comment by Minemaniak** [comment]
It was just a bug in 3.3.11 that Move check wasn't setbacking. It was still detected, just not setbacked. Bypass not present on 3.3.12

**Comment by Janmm14** [comment]
Invalid. Video says its 3.3.11, you claim its 3.3.12
