### ISSUE TITLE
Critical bug with LibsDisguises

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1308]
### Issue description
When players in minigame "HideAndSeek" click to item in hotbar, they are kicks.

Log: 
[10:58:35 INFO]: obormotik lost connection: Cannot interact with self!
[10:58:35 WARN]: handleDisconnection() called twice

Video: https://youtu.be/sAE-P5zSbc4

Without AAC all fine. (with AAC 3.3.9 all was fine)

### Core information
**Server version**: 1.12.2 paper

**AAC version**: 3.3.12

**ProtocolLib version**: v4.4.0-SNAPSHOT

**Plugin list**: AAC, ProtocolLib, ProtocolSupport, LibsDisguises, HideAndSeek

**Comment by Janmm14** [comment]
The kick is from minecraft. AAC in previous versions appaeantly cancelled self-interact somehow before.

**Comment by konsolas** [comment]
Should be fixed by changes to killaura. Obviously can't test this.
