### ISSUE TITLE
Players die after rejoin or respawn

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1309]
### Issue description
After updating AAC 3.3.9 -> 3.3.12 players began to complain very often that when they enter the server they die.

The cause of death is "death from falling"

Video: https://radikal.ru/video/1mrX92AB1fs
Log: https://pastebin.com/ZAaGg8Aj

### Core information
**Server version**: 1.12.2 paper

**AAC version**: 3.3.12

**ProtocolLib version**: v4.4.0-SNAPSHOT

**Plugin list**: AAC, ProtocolLib, ProtocolSupport

### Configuration
Celebrimbor config

**Comment by Slimerblue22** [comment]
Can confirm this will happen, been having it in kitpvp but no fall damage since we disabled it still flags like crazy randomly though

**Comment by Janmm14** [comment]
Debug log would help.

**Comment by EthanTG** [comment]
Removing the players' IP would probably be nice too...

**Comment by Toshka17** [comment]
Players also sent me a video that this happens also after the change of the world.

https://streamable.com/cwzpn
https://streamable.com/bgn38

**Comment by Slimerblue22** [comment]
@Toshka17 Could you please remove the player IP

**Comment by konsolas** [comment]
Need a debug log of this.

**Comment by Toshka17** [comment]
@konsolas , debug to death: https://pastebin.com/nJCiW62b

**Comment by konsolas** [comment]
player seems to log in at 272100.003,12.000,-591799.657, but then teleports to 806.500,44.000,154.500

Can you tell me more about what 806.500,44.000,154.500 is on your server? Do you teleport players on the PlayerJoinEvent perhaps?

**Comment by konsolas** [comment]
This should be fixed in 3.3.13

**Comment by Toshka17** [comment]
After change the world

Debug: https://pastebin.com/xPpwvKvP
Video: https://youtu.be/5KvzFo9_fRY
Username: obormotik

**Comment by Archengius** [comment]
Can you test your shit properly before publishing new build please?

**Comment by EthanTG** [comment]
oof

**Comment by Rerd** [comment]
If this is related to #1317, it isn’t fixed. Still receiving insane amounts of Move flags when an instant respawn occurs.

**Comment by konsolas** [comment]
Can't accept speculation to re-open an issue, especially since people have indicated that 3.3.13 has solved fall damage issues related to respawning.

**Comment by Janmm14** [comment]
Aka @Rerd you should create a new issue for your problem.
