### ISSUE TITLE
NoSlowdown on Stairs

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#131]
When NoSlowdown is enabled, you can go up stairs while eating food without being pulled back or getting high violations. This can also work with various other objects like shields. https://www.youtube.com/watch?v=xTQrfVLgBaQ

**Comment by v0idst4r** [comment]
NoSlowdown (with items and such) is a little tricky to patch. Even no cheat plus can only attempt to patch shield NoSlowdown but it's easy bypassed by sending a release use item packet pre tick.

**Comment by Janmm14** [comment]
@v0idst4r in that case the effect of shield blockage should be stopped too, so that's no real bypass?

**Comment by konsolas** [comment]
@v0idst4r NoSlowdown is patched everywhere else, but there's currently a special case for stairs.

**Comment by konsolas** [comment]
Going to close this as a wontfix due to the general difficulty of stairs hitboxes.
