### ISSUE TITLE
Heuristics Pattern 92 Issue

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1310]
Yet again, another issue with pattern 92. I got 86% confidence on it. 
`* [AAC] Rerd failed Heuristics: detected by pattern P/92 (confidence 86.0) [ping:0 tps:19.91] VL:2`
This is actually the second time I set it off.

### Core information
**Server version**: 1.8.8 PaperSpigot

**AAC version**: 3.3.12

### Configuration
Heuristics with 85% confidence.

**Comment by konsolas** [comment]
No attempt to describe the conditions of the issue at all.

**Comment by Rerd** [comment]
Normal fight, Speed 2. Was fighting for 1 minute. My aim was slightly choppy because I just came back from a trip and I was jitter clicking.

**Comment by konsolas** [comment]
Will be some minor changes to heuristics.

**Comment by Rerd** [comment]
From #1318: https://vk.com/videos308819433?section=uploaded&z=video308819433_456239023/pl_308819433_-1

**Comment by Janmm14** [comment]
@Toshka17 Can't watch the video because I don't have login for vk

**Comment by Toshka17** [comment]
@Janmm14 ,
Just some of my players upload the video there.
I'll try to download the video and upload it somewhere else.
https://youtu.be/6hBTiB0bjJU

**Comment by Rerd** [comment]
That isn’t nearly enough footage to see what actually caused the player to get banned. We’d need around 30-60 seconds of footage before the ban.

**Comment by Rerd** [comment]
Not fixed. Normal fight, still got flagged. Screenshots taken on LiquidBounce, but I had no cheats on. Both me and Slimerblue22 had speed 2. We ran at each other and started fighting. This time my aim was smoother than usual and I was following his exact movements. Fights lasted about 1 and a half minutes.
https://gyazo.com/1e3f09ecd44d193ec5e7185685e30f43
https://gyazo.com/c14c7a45fdfe8e19a0224e73033bfc0d

**Comment by Toshka17** [comment]
On AAC 3.3.13

[29-03-2018 19:56:43.460] OutLife failed Heuristics: detected by pattern P/92 (confidence 83.4) [ping:58 tps:19.93] VL:2

Video: https://www.youtube.com/watch?v=hd8uzn7v-IE
