### ISSUE TITLE
setVelocity (jumppads etc) still not working.

### ISSUE THREAD

**Issue by Minemaniak** [konsolas/AAC-Issues#1311]
### Issue description
Compatibility with setVelocity was marked as fixed, but it isn't, still flags for speed and fly. 
Very simple use (like player.setVelocity(player.getLocation().getDirection().setY(0.3).multiply(4));) triggered with pressure plate makes AAC flag you.

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.12

**ProtocolLib version**: 4.3.0

**Plugin list**: Irrelevant

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Cel'sconfig

**Comment by konsolas** [comment]
Cannot reproduce. Tested with https://www.spigotmc.org/resources/launch-pad-plus.8315/
