### ISSUE TITLE
AAC FLY

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#1313]
https://www.youtube.com/watch?v=C3hYLuCJaSI 
works on test server (Not always but sometimes)
Edit: You need to take void damage for it to work

**Comment by Janmm14** [comment]
doesn't give advantage with certain spigot.yml values being at default because boosting up can't be made high enough

**Comment by Janmm14** [comment]
Oops, I put wrong information out. My test setup was flawed.
