### ISSUE TITLE
AAC  is incompatible with the rust plugin - ghost

### ISSUE THREAD

**Issue by Pikuuu** [konsolas/AAC-Issues#1314]
### Core information
**Server version**: 1.8.8

**AAC version**: latest

**ProtocolLib version**: 4.3.0

**Plugin list**: rust plugin, protocollib, permissionsex, essentials, aac, automessage,

### Special environment information
**ViaVersion version**: null

**ProtocolSupport version**: null

**ViaBackwards version**: null

**BungeeCord plugins**: 1.8-1.12

I run a RUST server. The ghosts that I use in the game are required for AAC. When I kill such a ghost, the server throws a large part of the players. However, if you disable checking "killaur", nothing bad happens when killing the sprite. What can I do ? Spirits are created when the player is leaving the server and then another player can find him if he can find him. But then, as I said, the server throws players out while the "killaura" check is turned on

**Comment by Janmm14** [comment]
What do you mean with "throws players out"?
- Are they kicked by AAC?
- Do they get an "Internal error" kick message?

**Comment by Pikuuu** [comment]
he simply throws the player into the lobby

**Comment by Janmm14** [comment]
what does the server log show if those users are kicked

**Comment by Pikuuu** [comment]
This error pops up. This is only the case when I use "bungeecord"

https://i.imgur.com/xkjLdqa.png

**Comment by Pikuuu** [comment]
exact error: https://pastebin.com/9PWEV114

**Comment by konsolas** [comment]
Killaura changes will _probably_ fix this
