### ISSUE TITLE
CRITICAL false positives of killaura (Incompatibility with blocked getting damage)

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1315]
### Issue description
In many mini-games, in order to create a click-through effect to the player, uses event receiving damage. AAC killaura actively issues false positives for this after a recent update. (sorry for my english, it google translate).

Video: https://youtu.be/RgxsxbpXDtg

### Core information
**Server version**: 1.12.2 paper

**AAC version**: 3.3.12

**ProtocolLib version**: v4.4.0-SNAPSHOT

**Plugin list**: Custom

### Configuration
Cel-r
https://pastebin.com/hx0jHSkx

**Comment by Rerd** [comment]
Temporarily turn off the Killaura check until fixed.

**Comment by Janmm14** [comment]
Video not viewable without login

**Comment by Toshka17** [comment]
Test
<iframe src="//vk.com/video_ext.php?oid=308819433&id=456239023&hash=3787ef75a90ddf82&hd=2" width="853" height="480" frameborder="0" allowfullscreen></iframe>

**Comment by CeIebrimbor** [comment]
All issues stemming from the 3.3.10+ version of Killaura should be going away in the next release.
