### ISSUE TITLE
AAC | Critical CPU ussages.

### ISSUE THREAD

**Issue by craftrise** [konsolas/AAC-Issues#1316]
Server version: 1.8.8 | Viaversion: YES | ProtocolLib: 4.2.0 | AAC version: 3.3.12 (The worst version)

**First of all, I want to say:**
 - I get support from Google Translate. (I do not have a very good English, I work on it.)
 - We are a server with over 2000 to 3500 players.
 - We write all the plugins ourselves, we write them professionally.

**How did things start?**
 - With each new release of AAC, CPU usage is slightly higher. We no longer consider using AAC because it uses a lot of resources. If you solve this problem, AAC will be a perfect plugin. I'm telling you how to solve this. I really do not think I need to say that. Because, in the statistical reports I will give, the event is determined.

_This is the last chance we gave to AAC. If performance problems improve, we will continue to use it._

**Note:** When I remove the AAC, all of the performance problems are corrected and the CPU usage is reduced by about 50% to 60%.

I do not have a statistical report that works very well for me. I think you will understand the problem from here. I think these are enough.

Statistics Reports: (I like natural numbers)
0- http://prntscr.com/iu94cn
1- http://prntscr.com/iu92fu
2- http://prntscr.com/iu92j0
3- http://prntscr.com/iu92ln
4- http://prntscr.com/iu9cxt (NEW)
5- http://prntscr.com/iu9g6r (NEW)

And since AAC does not work with the main task, it does not appear in these reports.

**2x Note:** If you want, I can add more statistical reports.

**Comment by Toshka17** [comment]
I fully support your words. 
Yes, AAC uses about 60% of the CPUs of my servers, too. But it will not surprise anyone. Everyone knows that AAC is very voracious. 
It should be understood that anticheat creates a huge amount of work, checking a lot of types of moving etc. Especially since I have tried all the anticheats that are now in the access and ... AAC does not have any competitors at the moment. If you know what you can use instead of it, write me it in private messages, please, if it's not a secret. 

_____
Regarding performance improvement, our developer would be happy to help in the optimization of AAC. I knew that most likely Konsolas would never agree to this, but I promised to ask.

**Comment by Janmm14** [comment]
- Did you tried disabling the killaura check of AAC? It's cpu usage is too high atm.
- Your images can't be viewed: 403 Forbidden

**Comment by craftrise** [comment]
@Toshka17 
Yes, I agree.
If AAC continues to perform poorly, we would like to use it by editing on NoCheatPlus. I'm sure it will be better.

@Janmm14 
If I do not use "KillAura" or "Heuristics" features, why would I use AAC? NoCheatPlus solves speed/fly control and other controls with fewer false positive. I will update the images soon.

**Comment by Janmm14** [comment]
@craftrise The killaura performane problems will be hopefully solved in the next update, as you can see a bunch of killaura related issues on here are already marked with 3.3.13. This was meant as a temporary solution until the next update will be released.

**Comment by craftrise** [comment]
@Janmm14 , The same performance issues exists in older versions. If AAC really wants to improve performance, it should take good care of the reports I throw.

**Comment by Toshka17** [comment]
Monitor the performance of the plugin through the plugins (like massivelag or just timings) on the server is a bad idea

**Comment by Janmm14** [comment]
Would still like to see timings report.
Is your tps low?
Do you experience ingame lag?
The background compiler from protocollib can be ignored, it will not run contineously and will just improve performance if done.

**Comment by craftrise** [comment]
@Toshka17 
I just did not use the plugin. I added the VM outputs.

-----------------------------------------------------------------------------

@Janmm14 
I do not want to give Timings reports, it contains private information. I took HTOP pictures.

(Different servers, but same plugins, same hardware, same software)

- With AAC: http://prntscr.com/iue55p
- With NoCheatPlus: http://prntscr.com/iue4zk

**Comment by Janmm14** [comment]
@craftrise you could screenshot the aac part of your timings and the overall information

**Comment by craftrise** [comment]
@Janmm14, I can send Timings reports to you with a private message. (Discord)

**Comment by Teals53** [comment]
Vay aq craftrisede buralarda :D

**Comment by craftrise** [comment]
@Janmm14 , @konsolas 

**Very good news!

The new version (3.3.13) seems to have solved performance problems.
I will give more detailed information soon.

**Comment by CeIebrimbor** [comment]
Closing unless/until new evidence suggests otherwise.
