### ISSUE TITLE
False positives of move check after respawn

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1317]
### Issue description

After the update 3.3.9 -> 3.3.12 I have a fairly large number of complaints about the false kicks of the players for checking the move.

Video: https://youtu.be/PcYx3HVkhnE?t=42s
Log: https://pastebin.com/RTMD841u

Also, players sent a video about such incidents after teleportation to other worlds

### Core information
**Server version**: 1.12.2 paper

**AAC version**: 3.3.12

**ProtocolLib version**: v4.4.0-SNAPSHOT

**Plugin list**: AAC, ProtocolLib, ProtocolSupport, Custom

### Configuration
Cel-r
https://pastebin.com/nuVk56Sf

**Comment by Toshka17** [comment]
More incidents:
Log: https://pastebin.com/mScVCCHd
Video: https://streamable.com/rsb9i

**Comment by konsolas** [comment]
Merging wiht #1309 because they seem to be the same issue.
