### ISSUE TITLE
Step Bypass

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#1320]
https://youtu.be/3s9RPjAFFT8

**Comment by SenkJu** [comment]
Lol, meiner war dir nicht gut genug oder was?

**Comment by Janmm14** [comment]
spaßmachtfun

**Comment by SenkJu** [comment]
Jaja, red dich ruhig raus, du Lügenkobold.

**Comment by 0-x-2-2** [comment]
this is a vanilla feature what
