### ISSUE TITLE
AAC work but tps is 7.00

### ISSUE THREAD

**Issue by ItsCrazyFrog** [konsolas/AAC-Issues#1321]
Hello! 
When i put AAC plugin in my server it don't star and cpu is 100%.
The kick message is: "server still starting up".
Error: https://hastebin.com/qutolanayo.makefile
https://hastebin.com/ifigicoxed.css

**Comment by 0-x-2-2** [comment]
the log looks like is cut off a little

**Comment by ItsCrazyFrog** [comment]
@0-x-2-2 https://hastebin.com/emotigesep.md

**Comment by Janmm14** [comment]
PerWorldPlugins stuff. Try disable usetps, if it doesnt help, idk

**Comment by ItsCrazyFrog** [comment]
@Janmm14 these are no this erros but players can't join again
Kick message: "server still starting up" with 0 errors in console

**Comment by ItsCrazyFrog** [comment]
Plugin work now but tcp is over 5-10
