### ISSUE TITLE
PlayerViolationEvent sometimes broken

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#1323]
I'm using AACAdditionPro Heuristic-addion and sometimes the wrong player getting banned

Maybe related to #1130

**Comment by Photon-GitHub** [comment]
I just parse the player from the event with the event.getPlayer method and use that information to punish.

**Comment by konsolas** [comment]
How do you know it's the wrong player?

**Comment by Hyronymos** [comment]
Because he got banned from heuristics without any flags

**Comment by konsolas** [comment]
Where are you getting these flags and logs from?

**Comment by konsolas** [comment]
@Photon-GitHub do you cancel the PlayerViolationEvent?

**Comment by Hyronymos** [comment]
from server log, aac log and aacadditionpro log. Normally AACAdditionPro should spam in the logs with Heuristic Violations, that did not happen

**Comment by Janmm14** [comment]
Not seeing any setCancelled of PlayerviolationEvent in the heuristic addon code.

**Comment by konsolas** [comment]
Heuristics don't spam the logs anymore.

**Comment by konsolas** [comment]
@Hyronymos does this change your assessment?

**Comment by Hyronymos** [comment]
Not sure, close it until other people have the same problems too
