### ISSUE TITLE
Hitbox FP

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#1324]
https://youtu.be/um-e2iWHSTQ

**Comment by Rerd** [comment]
Logs? Maybe you can fix it by increasing the lenience.

**Comment by Hyronymos** [comment]
lenience: 0.65

**Comment by Rerd** [comment]
Can you maybe try recreating that while recording and with verbose on?

**Comment by Toshka17** [comment]
Video: https://youtu.be/_GFe-p-rBAI?t=1m5s
Log: https://pastebin.com/Ltw4bcdv

AAC 3.3.12
C-g: https://pastebin.com/r5uxSj0G

**Comment by Rerd** [comment]
Because the player has high ping, konsolas probably can’t do anything about it unless he changes how hitbox works. You can turn up the lenience to about 1.0 (what i have it at) and also turn off cancel hits.

**Comment by Toshka17** [comment]
@konsolas , why until now "insufficient info"?
