### ISSUE TITLE
Client crashes if creeper wants to explode and is attacked

### ISSUE THREAD

**Issue by Blueeyestar** [konsolas/AAC-Issues#1325]
### Core information
**Server version**: insert
Paperspigot 1.12.2

**AAC version**: insert
3.3.13

Problem:

If you have a Creeper skillst and Killaura activated, the game crashes immediately and it turns off completely. Even the launcher is outside

**Comment by Rerd** [comment]
What do you mean by, "If you skin a Creeper"?

**Comment by Blueeyestar** [comment]
As soon as you try to hit a creeper

**Comment by Rerd** [comment]
Can't recreate, can you record it?

**Comment by Janmm14** [comment]
also happening with vanilla client?

**Comment by Blueeyestar** [comment]
**When the launcher comes out the following comes in the console**

 [K[05:25:14 INFO]: Starnos lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: The connection was reset by the communication partner

**Comment by lancce-Wolf** [comment]
alright i had time to look for this problem again, i have a crash log from minecraft
[crash-2018-03-26_12.25.11-client.txt](https://github.com/konsolas/AAC-Issues/files/1847409/crash-2018-03-26_12.25.11-client.txt)

**Comment by Blueeyestar** [comment]
Here is my crash report

[crash-2018-03-26_05.42.57-client.txt](https://github.com/konsolas/AAC-Issues/files/1847519/crash-2018-03-26_05.42.57-client.txt)

**Comment by Toshka17** [comment]
So AAC-3.3.13 can not be placed on servers where there are creepers?

**Comment by Janmm14** [comment]
disable the mods option or disable the killaura check

**Comment by MerlinK11** [comment]
i have found a bug that ist soo break the AAC system Probably the Enchantment Sweeping edge III whem a normal player have this enchant on a sword and kill mobs wars kick the player for killaura but why it is tested on 1.12.2 and on ZombiePigmans ! please Fix that

!!!!!!

**Comment by Janmm14** [comment]
@MerlinK11 Please create a new issue for your killaura bug, so stuff stays organized. AAC can't be properly tested for all versions each release.

**Comment by SioWolf** [comment]
I also have this issue, I can provide any info necessary to solve this.

**Comment by FeroxDrood** [comment]
Also having this issue too ^

**Comment by Janmm14** [comment]
Everyone will have this issue likely.
