### ISSUE TITLE
AAC randomly cancels teleport... again

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#1326]
Related to #1278 
The bug still happen in 3.3.13 and doesn't happen in 3.3.10.
I can't make a debug log of this.

**Comment by Toshka17** [comment]
I confirm. From my players began to complain about the fact that they sometimes do not teleport. For some mini-games this is a critical bug.

Our plugin just teleports the player back to the lobby (like all other players), but AAC somehow overrides it.

[13:46:20 INFO]: [AAC] [VERBOSE] Fetox failed Move: (movement validation) sent unsafe movement -1877.300,26.368,-1988.458 -> 299.9024728655913,17.79673560066869,-674.3793470245708 [ping:114 tps:19.98] VL:100

**Comment by Janmm14** [comment]
Debug logs required.

**Comment by Toshka17** [comment]
Critical issue for minigames :(
