### ISSUE TITLE
[FEATURE] Phase check | Add teleport options.

### ISSUE THREAD

**Issue by craftrise** [konsolas/AAC-Issues#1327]
(Spigot: 1.8.8 | ProtocolLib: 4.2.0 | Viaversion: YES | AAC: 3.3.13)

As players walk, they are stuck in the phase control and thrown back. (Sometimes happens)
Add "teleport: true" option to phase control. Like this: http://prntscr.com/ixmo4r (This JUST example)

This will largely correct the problem.

And I want to say:
I would like to thank @konsolas , who has greatly improved performance issues in the last update.

**Comment by Toshka17** [comment]
Without this, players will fall through the ground after teleportation

**Comment by craftrise** [comment]
@Toshka17 , AAC can fix this.

**Comment by Janmm14** [comment]
This looks more like there is some underlying problem with phase which should be addressed actually.

**Comment by Rerd** [comment]
It actually has been addressed in issue #1188, but seems to have been ignored.
