### ISSUE TITLE
IceSpeed Bypass

### ISSUE THREAD

**Issue by lukeaction** [konsolas/AAC-Issues#133]
Hello,
I have found an IceSpeed Bypass on the AAC 3.0.0 Testserver !
Here is the video:
https://www.youtube.com/watch?v=MwWoyh7YcyI

**Comment by Janmm14** [comment]
@lukeaction Is it actually faster than sprintjumping on ice?

**Comment by CeIebrimbor** [comment]
Video looks to be rather brisk (pun intended yet still meant as substantive observation).

**Comment by Rqcco** [comment]
https://www.youtube.com/watch?v=tG5usQSo2F0

**Comment by konsolas** [comment]
New move checks fix ice limits.
