### ISSUE TITLE
Client crashing when hitting a creeper

### ISSUE THREAD

**Issue by sannielollie** [konsolas/AAC-Issues#1332]
### Issue description

Client crashing when hitting a creeper. Any other mobs give no problems. When AAC is disabled there are no crashes. About 80% of all my players are experiencing this issue, different minecraft versions tried (1.9.2-1.12.2)

Downgraded AAC to version 3.3.12 and the problem disappears instantly, no more clients getting crashed.

Crashreport of one player's client: https://gist.github.com/sannielollie/49d15d3c3becdc5a0c6776c20cc882fc 

### Core information
**Server version**: 1.12.2 Spigot

**AAC version**: 3.3.13

**ProtocolLib version**: 4.4.0-SNAPSHOT-b390

**Plugin list**:  Plugins (89): 3DManeuverGear, AddLight, AdvancedBan, AdvancedMobArena, AnimatedNames, AutoCrafters, Autorank, Banknotes, BossShopPro, BungeeTabListPlus, ChatColor, ChatControl, ChopTree3, Citizens, ClearLag, ConditionalCommands, ConsoleSpamFix, CoreProtect, CorpseReborn, CratesPlus, CustomPolls, DeathMessages, DiceFurniture, dynmap, Dynmap-Essentials, Elevator, ElytraPlus, Emoti, EnjinMinecraftPlugin, EntityDetection, Essentials, EssentialsChat, EssentialsSpawn, Factions, FactionsDynmap, FurnitureLib, GadgetsMenu, GAListener, GriefPrevention, GroupManager, HeadsInventory, HeadsPlugin, HolographicDisplays, HolographicScoreboard, InfinityDispensers, LWC, MassiveCore, mcMMO, Minator, MiniaturePets, Multiverse-Core, MVdWPlaceholderAPI, MythicMobs, NightVision, NoteBlockAPI, NoteBlockMusicPlayer, PlayerPoints, PlayTimeRewardsRecoded, PluginLibrary, PlugMan, PremiumVanish, ProtectionLib, ProtocolLib, React, RecipeBookDupePatch, RedstoneCommand, SantaClaus, SilkSpawners, SimpleBossBar, SimpleSit, Statz, Sudo, Superpickaxe, Trading, TrailGUI, TransportPipes, UltraBar, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, Wild, Winter, WorldEdit, WorldGuard, WorldGuardExtraFlags, XRayHunter, HeadDatabase

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: 2.3.1

**BungeeCord plugins**: Ultimatereporter, BungeeCountryManager, BungeeList, BungeeMail, Bungeetablistplus, bungeeyaml, commandfo, empbungee, fastconnect, jmrestart, liteannouncer, nuvotifier, premiumvanish, quietcord, serverlistplus, slashserver, staffchatbungee, superantiad, yamler-bungee

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

	anti-xray-patch: false
	use-new-deathmessages: false
 	auto-team: false	86.	# If the above is true, should we automatically team players until you do?
 	suppress-metadata-errors: true
        tracking-max-warnings: -1
        tracking-warning-pps: -1
        tracking-period: -1
        max-pps: 5000	
	

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

**Comment by CeIebrimbor** [comment]
#1325
