### ISSUE TITLE
Elytra flying is Buggy

### ISSUE THREAD

**Issue by MerlinK11** [konsolas/AAC-Issues#1333]
AAC is causing problems with extreme problems with the plugin:
SuperElytra here is the link:
https://www.spigotmc.org/resources/superelytra-improved-elytra-flight.19382/

So the problem is that I have the AAC blocks this plugin completely since the flying with the Elytra is speeded up you can fly there with an Elytra vertically high the thing is you can add a hook for that?

then this plugin is loved by a lot of players on my server right now i hope you can do that to add this hook please i need that very much

Thank you in advance in advance for your help

Best regards

MerlinK11

**Comment by MerlinK11** [comment]
:1 bug

**Comment by MerlinK11** [comment]
AAC is causing problems with extreme problems with the plugin:
SuperElytra here is the link:
https://www.spigotmc.org/resources/superelytra-improved-elytra-flight.19382/

So the problem is that I have the AAC blocks this plugin completely since the flying with the Elytra is speeded up you can fly there with an Elytra vertically high the thing is you can add a hook for that?

then this plugin is loved by a lot of players on my server right now i hope you can do that to add this hook please i need that very much

Thank you in advance in advance for your help

Best regards

MerlinK11

**Comment by Janmm14** [comment]
#1334
