### ISSUE TITLE
SuperElytra plugin support request

### ISSUE THREAD

**Issue by MerlinK11** [konsolas/AAC-Issues#1334]
AAC is causing problems with extreme problems with the plugin:
SuperElytra here is the link:
https://www.spigotmc.org/resources/superelytra-improved-elytra-flight.19382/

So the problem is that I have the AAC blocks this plugin completely since the flying with the Elytra is speeded up you can fly there with an Elytra vertically high the thing is you can add a hook for that?

then this plugin is loved by a lot of players on my server right now i hope you can do that to add this hook please i need that very much

Thank you in advance in advance for your help

Best regards

MerlinK11

**Comment by sannielollie** [comment]
Same issue on the ElytraPlus plugin - does about the same as SuperElytra - also gives false positives on fly
