### ISSUE TITLE
Some weird timer detection false positive

### ISSUE THREAD

**Issue by zBoringDrop** [konsolas/AAC-Issues#1337]
### Issue description
In 1.8.8 you can move very few, aac block all your movements. 3 or 4 updates ago there wasn't this bug.
I also tried to remove viabackwards and viarewind (also delete aac config to generate default config), but the bug stills. 

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.13

**ProtocolLib version**: 4.4.0

### Special environment information
**ViaVersion version**: 1.3.0

**ViaBackwards version**: 2.3.1

**ViaRewind**: 1.3.5

### Configuration
Default config.
(But this bug stills also with other edits)

**Comment by Rerd** [comment]
Verbose? Logs? Video? Update to 3.3.13 and try?
You need to provide much more info for something like this.

**Comment by zBoringDrop** [comment]
So, sorry but i failed on version, i already use 3.3.13 but this stills.
So, for:
I downgraded protocollib to 4.3.0, but the bug stills.
Logs: https://pastebin.com/cU8UBCX8
Verbose: https://pastebin.com/aFaqnW7N (Infinite spam, also if i still)

**Comment by Janmm14** [comment]
Are you sure you do not have timer enabled?

**Comment by zBoringDrop** [comment]
Im not using hacks

**Comment by Minemaniak** [comment]
No CheatEngine? What client version? 1.8.8? Is it completely vanilla, or is it some custom client? Any mods?

**Comment by zBoringDrop** [comment]
No no no.
NORMAL minecraft client (1.12.2 in a 1.8.8 server).
O mods 
Not a custom client

**Comment by Janmm14** [comment]
This is likely no problem on AAC's side.
The version was tested on 1.8.8 server with 1.8.9 client already and currently a couple of minigame networks use that setup.

Are you sure this happens with default config too?
A misconfiguration of move can cause such problems too.

Recently changes were made to the move check to prevent antifire and antipoision cheats.

**Comment by zBoringDrop** [comment]
Yes im sure.
I solve by disabling move, speed and velocity check.
This make aac useless

**Comment by Janmm14** [comment]
By disabling move, all movements checks are disabled.
So also fly, criticals, etc.

Can you please show the "move" part of your config? (thresholds, if any, not needed)

**Comment by zBoringDrop** [comment]
It is the default, i also tried with the celebrimbor ghost config (less fast than the default) and the bug stills

**Comment by Janmm14** [comment]
Can you please enable debug with `/aacdebug`, then join the server and disable debug again with the same command and send the log file? (you can remove the config at the top of the log)

**Comment by zBoringDrop** [comment]
Pastebin.com/ZWfDKz8Y

**Comment by Janmm14** [comment]
Sorry I can't help you. Either it is a really rare bug in AAC coming up with some lag or one of your plugins.

**Comment by zBoringDrop** [comment]
No, i tested with 0 lag..
And I tested also without viabackwards and viarewind.. what plugin can cause this? I did lots of tests.. 
In 3 different servers, so different plugins, the bug stills and they are all 1.8.8.
Anyway, 0 bugs in 1.12.
So it's only with 1.8.8.

**Comment by Janmm14** [comment]
You joined 1:28:12 first movement was recieved 1:28:15 (3secs)
Actual movement processing was somehow delayed for years and packet checking started 1:28:19 (another 4 secs later)

**Comment by zBoringDrop** [comment]
So?
(Can you remove insufficient info?)

**Comment by Minemaniak** [comment]
He probably won't, it doesn't look like AAC mistake, rather some extremaly strange lag or other plugin interfering. Try reproducing it on clean server with ONLY AAC and protocol Lib (with default, unmodified spigot if you use some modified one), with default configs.

**Comment by zBoringDrop** [comment]
Ok, i will do this later

**Comment by zBoringDrop** [comment]
So, i tried and:
With only aac and protocollib the bug stills on my public server but i tried also on localhost server with SAME plugins and the bug disappears...

**Comment by Rerd** [comment]
Twerion.net seems to be having the same issue or maybe a similar issue to this. It seems to be an issue with ViaVersion and BungeeCord. It happens on all versions other than the original server-based version.

If anyone is experiencing this issue on their server, please send verbose and debug logs of this happening.

**Comment by zBoringDrop** [comment]
Another time?

**Comment by Janmm14** [comment]
BungeeCord-based ViaVersion is not recommended for usage with AAC.

**Comment by zBoringDrop** [comment]
So? There arent fixs?

**Comment by Rerd** [comment]
Most likely not. Switch to Spigot ViaVersion.

**Comment by konsolas** [comment]
Probably nothing I can do about this. Something is causing too many move packets to be sent to the server, which isn't distinguishable from cheats which do this.

See #1348

**Comment by zBoringDrop** [comment]
Sorry, but can i do somthing to fix?
How other servers know how fix this bug?

**Comment by Minemaniak** [comment]
It looks like othersaren't experiencing this issue. You need to try to locate the probem yourself. Start with totally clean server without ANY other plugins apart from AAC and ProtocolLib. Add plugins one by one to locate the error. If you have modified engine - try with unmodified. If you use bungee cord - try without it. Try withour viaversion/other protocol hacks. Etc.

**Comment by zBoringDrop** [comment]
Alredy did, the problem is viaversion on bungeecord

**Comment by Minemaniak** [comment]
Try to play with simulate-pt and nms-player-ticking in viaversion config. If it osn't that - I have no idea. That's quite popular setup, it must be misconfiguration on your side.

**Comment by zBoringDrop** [comment]
Can you send me the config?
I dont understand what do you mean

**Comment by zBoringDrop** [comment]
The problem is that sometimes of i use viaversion in this way, it kicks random player for bad packet or similar, with bungee is more stable.
I also think that the most minecraft servers use it only in the proxy plug-in folder

**Comment by Janmm14** [comment]
It is impossible for an anticheaz to distinguish between timer (antifire/antipotion/regen) and viaversion used that way as far as I know
