### ISSUE TITLE
interact through blocks bypasses

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1338]
### Issue description

Is possible add anti breakanura or bedfucker? anti break through the blocks /for bedwars)

### Core information
**Server version** 1.8.x / 1.12.2

**AAC version**: 3.3.13

**ProtocolLib version**: 4.3.0

**Plugin list**: insert

### Special environment information
**ViaVersion version** 1.3.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: 2.3.1

**BungeeCord plugins**:N/A

**Comment by Janmm14** [comment]
Note: You are supposed to replace the existing text below issue description with your issue description instead of pasting that below.

Already exists, but has problems currently.

**Comment by leoncp9** [comment]
okay no problem, i m wait , good job :)

**Comment by Rerd** [comment]
Duplicate of #1036?

**Comment by Janmm14** [comment]
I'd just say similar
