### ISSUE TITLE
Citizens NPE@u.a:46@N.a:108 v3.3.13

### ISSUE THREAD

**Issue by xion87** [konsolas/AAC-Issues#1339]
### Core information
**Server version**: 1.8.8 + viaversion 1.3.0

**AAC version**:3.3.13

**ProtocolLib version**: 4.2.0

**Plugin list**: Strikepractice,citizens

When fighting with the bot (from citizen) the console trow me these errors https://pastebin.com/2rqvyp8R

**Comment by Minemaniak** [comment]
Hastebin dead, paste it on pastebin, or here as code snippet.

**Comment by xion87** [comment]
Link updated ty :)
