### ISSUE TITLE
False positive with the new slime check, landing in the middle of 4 slime blocks.

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#134]
When you jump on a slime block from a decent hight, and land on the FULL block of slime, (Meaning you can't land in the middle of two slime blocks or the corner of two.) you will be setback, with medium violation. When you try to reproduce, it might take multiple attempts due to the erratic behavior of slime blocks. https://www.youtube.com/watch?v=CfYLANwjEY8

**Comment by Rqcco** [comment]
Actually, I just tested it again and it's when you land on the outer blocks of the first slime platform that causes the issues, I'll label signs so when you get on you will understand

**Comment by Rqcco** [comment]
in addition, if you land at the very corner of a slime block, it will not bounce you up, but however  damage you.

**Comment by v0idst4r** [comment]
@konsolas U tryna fix slime jump m6?

**Comment by Janmm14** [comment]
@v0idst4r its not an aac issue and aac can probably not do anything here

**Comment by v0idst4r** [comment]
@Janmm14 ?

**Comment by konsolas** [comment]
Fixed. Confirmed by @Photon-GitHub.

**Comment by Photon-GitHub** [comment]
It is indeed there if you jump on the exact middle of 2 or 4 blocks.

**Comment by konsolas** [comment]
Fixed, confirmed by @Photon-GitHub

**Comment by Janmm14** [comment]
Oh, I got it wrong.
