### ISSUE TITLE
Custom Enchant false positives

### ISSUE THREAD

**Issue by zBoringDrop** [konsolas/AAC-Issues#1343]
### Issue description
I'm using this plugin ( https://www.spigotmc.org/resources/crazy-enchantments-new-gkitz.16470/ ) and with some enchant it sometimes kick someone for cheats.
For example, a pickaxe enchant that destroy with one click a block of 3x2 blocks.

### Core information
**Server version**: 1.12

**AAC version**: 3.3.13

**ProtocolLib version**: 4.3.0

**CrazyEnchantments Plugin version**: 1.7.9.3.7

**Comment by CeIebrimbor** [comment]
That plugin dev used to support AAC. It would be best to ask that dev to double check his application to make sure he's not accidentally conflicting with such a widely used AC.

**Comment by konsolas** [comment]
Not an AAC issue.
