### ISSUE TITLE
Heuristics Detection is Now Extremely Slow

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1344]
In 3.3.13, the heuristics detectly is now extremely slow to the point where a player could get like 50 kills before he gets banned, as it was previously around 5-10. The check seems to kick in after fights, which isn’t good especially for FFA/KitPvP. My suggestion is attempting to make it as fast as it was pre-3.3.13, since that was when it was at its prime detection speed.

The delays between flags also seem to be dramatically long, which can be annoying for people that have higher thresholds for different things set up, as I do.

**Comment by Janmm14** [comment]
konsolas said, he won't do this
