### ISSUE TITLE
AAC memory usage...

### ISSUE THREAD

**Issue by TheColdEmeraldCODE** [konsolas/AAC-Issues#1345]
I want AAC on my server because I paid for it and stuff! But it gets out of memory with it!

**Comment by Janmm14** [comment]
PerWorldPlugins can cause such issues.
Try disabling use-tps in the AAC config. In general, PerWorldPlugins is listed as possibly incompatible in the overview.

**Comment by TheColdEmeraldCODE** [comment]
Ok thanks i disabled that already so i will see about PWP
