### ISSUE TITLE
Heuristics P/93 and P/96 FP

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1346]
### Issue description
No info on how the fights happened, although blakebighead explained that they were chasing someone, hit them like 5 times then went afk for 10 seconds. Seems like most of the P/9x’s need to be made way less strict since my issue #1310 still exists too.

Pattern 96
Ex. 1: `blakebighead failed Heuristics: detected by pattern P/96 (confidence 88.4) [ping:51 tps:20.0] VL:3`
Ex. 2: `Woht failed Heuristics: detected by pattern P/96 (confidence 89.0) [ping:38 tps:20.0] VL:3`

Pattern 93
Ex. 1: ` Exports failed Heuristics: detected by pattern P/93 (confidence 88.2) [ping:144 tps:20.0] VL:3`

### Core information
**Server version**: 1.8.8 Spigot

**AAC version**: 3.3.13

### Configuration
Heuristics Confidence set to 87.

**Comment by xion87** [comment]
I noticed false kick on heuristic P/96 too, using 1.8.8 paperspigot, that player was legit
BenvePvP_ failed Heuristics: detected by pattern P/96 (confidence 89.6) [ping:86 tps:19.97] VL:3"

**Comment by bob7l** [comment]
P/92, P/96, and P/93 all generate false positives over 80 confidence
