### ISSUE TITLE
Bypass of speed check (Flight at the minimum distance above the block)

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1347]
### Issue description
Video: https://www.youtube.com/watch?v=ynZvZ09JBJk
As you can see from the video, the player flies a short distance above the block and flies faster than the players run. Situations when the player flies and choose the height, you can see several times on this video.

### Core information
**Server version**: paper 1.12.2

**AAC version**: 3.3.13

**ProtocolLib version**: v4.4.0-SNAPSHOT

### Configuration
Cel-r config.
Turned on only badpackets, speed, fly, move and interact.

**Comment by Rerd** [comment]
First issue, we don’t have the client name or version. 
Second issue, we don’t have any debug files. 
Third issue, the framerate of the video is absolutely terrible where I can barely tell what’s going on.
Please provide at least the client name and a debug file of someone using the speed.
