### ISSUE TITLE
AAC Move check for 1.9 - 1.12.2 client broken (ViaVersion)

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#1348]
Log: https://pastebin.com/tSG7StP0
Debug: https://pastebin.com/qQCaaBxJ
ViaVersion Config: https://pastebin.com/jCwBJftq
Video: https://www.youtube.com/watch?v=qO18Arnz7-w&feature=youtu.be

**Comment by Janmm14** [comment]
Don't use ViaVersion bungee? I thought you had similar issues already.

**Comment by Hyronymos** [comment]
I just disabled the regen check. I can't read in the aac overview page that aac does not support viaversion on bungeecord.

The owner of minesucht.net said, that he have the same problems without using viaversion on bungeecord.

**Comment by konsolas** [comment]
Probably nothing I can do about this. Something is causing too many move packets to be sent to the server, which isn't distinguishable from cheats which do this.
