### ISSUE TITLE
Liquid bounce Bypass

### ISSUE THREAD

**Issue by Hellinduction** [konsolas/AAC-Issues#1349]
Just informing you that the latest version of liquid bounce 1.8.9 bypasses some off aac checks such as scaffold and killaura to a certain extent and it gives that player an unfair advantage and quit a big "unfair advantage" so please could you possibly fix this or give me instructions on how to fix it myself within config files? Thankyou for reading, from joe.

**Comment by Janmm14** [comment]
AAC has no Scaffold check.

**Comment by Minemaniak** [comment]
There is Scaffold check in AACAdditionPro, which is different plugin than AAC. Did you check if it bypasses AACAP's Scaffold?

**Comment by Hellinduction** [comment]
what about the killaura?

**Comment by Hyronymos** [comment]
LiquidBounce Killaura doesn't bypass aac yet

**Comment by konsolas** [comment]
@Hellinduction LiquidBounce is detected by heuristics for me.

**Comment by Slimerblue22** [comment]
AACs aura detection with LB is weird sometimes, it detects within seconds (45 seconds) sometimes then sometimes it takes a few mins (3-5 mins)

**Comment by craftrise** [comment]
@Slimerblue22 , I agree with yours. The same problem exists within our server.

**Comment by Teals53** [comment]
@craftrise artık aac dan vazgeçin hilenin anasını ağlatıyorum çok rahat bir şekilde lb b46 indir al buda config hazır ayarlamışım herşeyi rehberide oku tüm avantaj sağlayacak şeyleri tavsiyelere yazdım xD
 http://www.mediafire.com/file/13vo846xtq1latc/Config.rar
