### ISSUE TITLE
Eating while sneaking bug.

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#135]
Very self explanatory. Eating while sneaking forward will cause speed flags.

**Comment by Rqcco** [comment]
*Same things with shields*

**Comment by konsolas** [comment]
Fixed.

**Comment by v0idst4r** [comment]
:P

**Comment by v0idst4r** [comment]
@konsolas Sneaking, while blocking, while jumping false positives fly. Confirmed by @Rqcco

**Comment by konsolas** [comment]
@v0idst4r cannot reproduce that. We should ideally check if an issue can be reproduced again before reopening.
