### ISSUE TITLE
Flag NoFall

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#1353]
Ok I really don't have too many details at the time but you can get the client yourself and try what I did in the video
https://youtu.be/piYzCZ6VXv8

**Comment by Slimerblue22** [comment]
As a side note it works with some of the other flight modes but the one I used in the video doesn't flag criticals every 2 seconds

**Comment by Slimerblue22** [comment]
On the test server it seems fixed like #1410

**Comment by konsolas** [comment]
👍
