### ISSUE TITLE
PotLag

### ISSUE THREAD

**Issue by ItsCrazyFrog** [konsolas/AAC-Issues#1354]
Can i fix anticheat potlag.

**Comment by ItsCrazyFrog** [comment]
when i use anticheat in server players have potlag legendary apple lag and regen lag

**Comment by ItsCrazyFrog** [comment]
please fix fly bug on jumping on cactus, potlag and speed bug when speed is given from beacon

**Comment by ItsCrazyFrog** [comment]
And one more bug: speed bug on cobweb trying to remove in region kick for speed

**Comment by Janmm14** [comment]
looks like a troll

**Comment by Janmm14** [comment]
in case its not a troll, make sure you have latest aac version and

- movement bug reporting please with a debug log (debug logging can be toggled with /aacdebug)
- transitions with speed effects are likely not going to be fixed
- your "pot lag, apple lag and regen lag" is not valid until you explain what you actually mean with it and maybe provide a video of that bug
