### ISSUE TITLE
Fly [Speed] Bug

### ISSUE THREAD

**Issue by ItsCrazyFrog** [konsolas/AAC-Issues#1355]
Players with Creative and Fly permissions have been kicked for flying or speed ....

**Comment by Minemaniak** [comment]
One more time: issue template isn't here to delete, but to fill it. Provide required information, or I'm sure this will be closed.

**Comment by ItsCrazyFrog** [comment]
Log: https://hastebin.com/uyosocaqab.bash

**Comment by Janmm14** [comment]
disable invalid ability packets in config
