### ISSUE TITLE
False positives of HitBox check

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1358]
### Issue description
Log: https://pastebin.com/irLwaCma   (look latest lines)
Video: https://www.youtube.com/watch?v=NBTnmopJZrM   (Only first 23 seconds)

### Core information
**Server version**: paper 1.12.2

**AAC version**: 3.3.14

**ProtocolLib version**: v4.4.0-SNAPSHOT

### Configuration
Like Cel-r

**Comment by Rerd** [comment]
Increase your move compensation and lenience for hitbox.
