### ISSUE TITLE
False positives of Killaura check

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1359]
### Issue description
Log: https://pastebin.com/rG0sRxWB (Look latest lines)
Video: https://www.youtube.com/watch?v=5-7itSJ6IwE

### Core information
**Server version**: paper 1.8.8

**AAC version**: 3.3.14

**ProtocolLib version**: v4.4.0-SNAPSHOT

### Configuration
Like Cel-r

**Comment by konsolas** [comment]
Killaura has been rewritten.
