### ISSUE TITLE
False positives of Killaura check (Incompability with LibsDisguises (HideAndSeek))

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1360]
### Issue description
Recently, I have a lot of complaints from players who receive false penalties in this mini-game. This is HideAndSeek, it works through LibsDisguises (players are disguised in falling blocks)

Video: https://www.youtube.com/watch?v=qkNQjiEh77k
Log: https://pastebin.com/9U34Q5Aa

### Core information
**Server version**: paper 1.12.2

**AAC version**: 3.3.14

**ProtocolLib version**: v4.4.0-SNAPSHOT

**Plugin list**: AAC, ProtocolLib, ProtocolSupport, LibsDisguises, HideAndSeek

### Configuration
Like Cel-r

**Comment by Rerd** [comment]
Disable the killaura check. I don’t think this will get fixed.

**Comment by Toshka17** [comment]
Before this version, there were no problems.

**Comment by konsolas** [comment]
Set killaura.normal to -1 (AAC 3.5.0 and above)
