### ISSUE TITLE
Velocity's "Changed Direction Midair" Not Setting Players Back Anymore

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1362]
### Issue description
When someone flags velocity via the "changed direction midair" check, it doesn't set them back anymore. I have tried setting my `min_vl` to 1, still nothing. A few versions ago (3.3.9) when I last have tested this, it would always set back no matter what `use_velocity_setbacks` and `min_vl` is set to, although now it doesn't.

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 3.3.14

### Configuration
`check_length: 18`
`max_tp_dist: 0.0`
`use_velocity_setbacks: true`
`min_vl: 5`
`vl_normal: 1`
`vl_no_packet: 0``

**Comment by Minemaniak** [comment]
You have max_tp_dist set to 0, maybe that's the reason? Set it to default value and try again.

**Comment by Janmm14** [comment]
Closing because you set max_tp_dist to 0.
