### ISSUE TITLE
Freecam bug kick and join

### ISSUE THREAD

**Issue by Wenferth** [konsolas/AAC-Issues#1367]
### Issue description
The player activates freecam and is kicked directly for fly (no problem so far) then he reconnects the freecam is still active for him but aac does not detect freecam and the player can use the freecam (embarrassing)
### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.14

**ProtocolLib version**: 4.4.0-SNAPSHOT-b391

**Plugin list**: insert

### Special environment information
**ViaVersion version**: N

**ProtocolSupport version**: N

**ViaBackwards version**: N

**BungeeCord plugins**: N

### Configuration
My config it's optimized aac

**Comment by konsolas** [comment]
AAC does not detect freecam - it is a client side cheat and is generally undetectable.
