### ISSUE TITLE
Incompatibility with the plugin "AutoKiller"

### ISSUE THREAD

**Issue by xTaisaku** [konsolas/AAC-Issues#1368]
Hi, i have the version 3.3.12 of AAC and i have been testing it and works pretty well with the default config, the issue is when i put the AutoKiller (Anti Autoclickers plugin) in the plugins folder. I run the console and everything looks fine, i write /pl and it shows that AAC,AutoKiller and ProtocolLib are running https://gyazo.com/216c4834fa1d1630862b1247fb04afd5 ,But in the game when AAC works, AutoKiller doesnt work, and sometimes AutoKiller works but AAC doesnt work. Please! give a solution thank you so much.

**Comment by Janmm14** [comment]
Are you sure there ar no cosole errors?

**Comment by xTaisaku** [comment]
Well, this is what it looks like: I will show you images in order
https://gyazo.com/757e4b8a0b6edd9a8a12e31dd5b6237b , https://gyazo.com/a711ba900076f7f0b3db48ff18c302cd , https://gyazo.com/92f7b33bf6f9abb65268dc5a4b9a79ac

**Comment by xTaisaku** [comment]
Can you help me please?
