### ISSUE TITLE
CRITICAL False positives of Killaura check (climbing the ladder and pvp in water)

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1372]
### Issue description
Occurs when climbing the ladder, also the players write that you can get FP in water or poisoning.

Log: https://pastebin.com/TYqkgLc4
Video: https://www.youtube.com/watch?v=EfJCRgLLQfY

### Core information
**Server version**: paper 1.8.8

**AAC version**: 3.3.14

**ProtocolLib version**: v4.4.0-SNAPSHOT

### Configuration
Like Cel-r

**Comment by Minemaniak** [comment]
I can confirm massive FPs with fights on ladders. Also, fights in/neat the cowebs can cause similiar FP's.

**Comment by Hyronymos** [comment]
Pls hoffix if possible

**Comment by Slimerblue22** [comment]
I believe its when you are hitting an entity/player from below. My guess is that it won't hit the killaura entities since they are spawned too high up. *Keep in mind this is a guess*

**Comment by Janmm14** [comment]
Basically every action can cause killaura false positives. Possibility increases with lag.

**Comment by Minemaniak** [comment]
That's not the problem. Normally, killaura in 3.3.14 works well, nearly no FP's. But there are situations (ladders and conwebs), when violations skyrocket, ping doesn't matter here.

**Comment by Toshka17** [comment]
A lot of complaints about FP in these situations, to repeat simply enough

**Comment by Rerd** [comment]
If you’re having a ton of false positives because of this, I recommend either disabling Killaura or making it only flag temporarily until it gets fixed. There won’t be a fix until konsolas is finished his exams, which is the end of June.

**Comment by konsolas** [comment]
Killaura has been rewritten.
