### ISSUE TITLE
Lagbacks in fight

### ISSUE THREAD

**Issue by Minemaniak** [konsolas/AAC-Issues#1380]
Lately players started to complain about lagbacks while fighting. Hard to reproduce, so no debug log. I only managed to get 1 video
https://youtu.be/sqOZJ3jqIo0?t=25s (watch from 0:25)
Don't know if it is the only issue, or if there are more ways to get this bug :/
It's most likely speed check, what else could it possibly be?
### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.14

**ProtocolLib version**: 4.3.0

**Plugin list**: -

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: -

### Configuration
Celebrimbors optimized, with changes:
speed.threshold: 0.005 -> 0.02
speed.max_use_toggles: 40 -> 1000

**Comment by Rerd** [comment]
Not a bug with AAC, but a bug with Minecraft itself. Player was blocking their sword server-side, but client-side it wasn’t.

**Comment by Minemaniak** [comment]
I don't think that's the case. For this bug to appear, he would have to block with sword, as you can see in the video, he didn't. Also, if that was the issue, it would setback him forever, but as you can see it stopped after a few seconds without him doing anything to unglitch. I'm aware of the bug you are talking about, it happens sometimes, but not here.

**Comment by Janmm14** [comment]
Hard rlto tell what happend there without logs as it seems to be some client-server sync issue, because normal running works

**Comment by Minemaniak** [comment]
One more video, what do you think @Janmm14? https://www.youtube.com/watch?v=Son5564LEX4

**Comment by Rerd** [comment]
I stand with the point I said above. It’s simply the server thinking the player is blocking their sword, but client-side it’s not.

**Comment by Minemaniak** [comment]
Bugged blocking sometimes happens, I am aware of this bug. But it doesn't mean you can accuse it of every speed issue. Many of those lagbacks are not related to this - if you spectate player, he isn't blocking, and he is still lagged back.

**Comment by Rerd** [comment]
It is definitely the speed issue and it is definitely an issue with the sword blocking. There is simply no other explanation for this.

**Comment by Minemaniak** [comment]
I will test more, but there seem to be 2 different issues. First is in fact glitched blocking, which is our thing to fix, not AAC's. But lagbacks in fight from speed check happen even without this bug, and are fixed by setting strict_velocity_checking to false (which is unacceptable because it opens up shit load of bypasses). I will test more and try to get some logs.

**Comment by Minemaniak** [comment]
Not yet, didn't have time to test
