### ISSUE TITLE
Riding horse over carpet

### ISSUE THREAD

**Issue by LogGits** [konsolas/AAC-Issues#1381]
### Issue description
Using Cele's config.

Riding a horse over a carpet triggers false positives. If anyone else can test this and let me know if it is happening to them, it would be really helpful 👍 

-- error was duplicate of #1357 --

### Core information
**Server version**: Paper version git-Paper-1416 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) 

**AAC version**: 3.3.14

**ProtocolLib version**: v4.4.0-SNAPSHOT-b390

**Comment by Rerd** [comment]
For the issue with the horse, you should probably record and start a debug file while you’re recreating the bug.

For the issue with the error, you create a separate issue for it.

**Comment by Janmm14** [comment]
The error is already reported in #1357
