### ISSUE TITLE
KillAura bypass | Velocity bypass and others...

### ISSUE THREAD

**Issue by craftrise** [konsolas/AAC-Issues#1384]
### Issue description
Killaura and velocity bypass (With LiquidBounce client)

**Video:** https://www.youtube.com/watch?v=PcwkahNP5AY&feature=youtu.be
**Config link:** https://we.tl/z3zbm9WDWB

### Core information
**Server version**: 1.8.8

**AAC version**: Latest - 3.3.14

**ProtocolLib version**: 4.2.0

### Configuration
Config from Celebrimbor.

**Comment by Rerd** [comment]
I just tried the fly mode used in the video on a default config of AAC and it did not work.

**Comment by Slimerblue22** [comment]
^^^ same

**Comment by Nort721** [comment]
Very very bad configuration file (The conifg is not from celeb) I have tested these hacks already with the same client and Celebs config and its not bypassing

**Comment by craftrise** [comment]
Okay, let's look at the others.

**Comment by Nort721** [comment]
just try to use this hacks that you have used in the video at the AAC test server and record it and send it to here

**Comment by craftrise** [comment]
I just increased the "min_vl" option slightly for fly protection. Other than that, I did not make a change. The config are completely owned by Celebrimbor.
The min_vl value has been changed back. Fly protection problem solved.

Killaura and Velocity problems are continuing.

**Comment by Teals53** [comment]
is that my config ? @craftrise

**Comment by Teals53** [comment]
@Janmm14 why deleted my messages ? :(

**Comment by Janmm14** [comment]
This issue does not show any aac configuration file, so stop talking about that

**Comment by konsolas** [comment]
Killaura is mostly detected by heuristics, and the velocity bypass is not significant.

**Comment by Teals53** [comment]
xD

**Comment by konsolas** [comment]
Killaura has been rewritten.
