### ISSUE TITLE
Pig riding speed cheat largely undetected.

### ISSUE THREAD

**Issue by Aerodog** [konsolas/AAC-Issues#1385]
### Issue description
Players can
- speed hack on pigs (extremely fast, enough to crash server if given enough open space)
- climb hills while in boats

### Core information
**Server version**: Spigot 1.12.2

**AAC version**: 3.3.14

**ProtocolLib version**: 4.4.0-SNAPSHOT-b18

**Plugin list**: Essentials, AACAdditionPro, WE, WG, GriefPrevention, LogBlock, NoElytra

### Configuration
Default (with customized kick commands, but that's irrelevant).

**Comment by Janmm14** [comment]
Horse stuff is checked if I remember correctly.

**Comment by Aerodog** [comment]
You're right--I made a mistake. It is, in fact, pigs that are the problem. I edited it.
