### ISSUE TITLE
Normal Bhoping In Ice Have Bug

### ISSUE THREAD

**Issue by Helloxddd** [konsolas/AAC-Issues#1386]
**no information sorry i dont have server i found that bug when i playing in aac 3.3.14 server**
ok
when i bhoping top of ice and top of me trapdoor 
its give me speed check
fix plz
![image](https://user-images.githubusercontent.com/37207067/40581324-c05247f0-6155-11e8-9e64-e303ed92f055.png)

**Comment by Helloxddd** [comment]
if u want the ip of server
its
poke.sexy its anticheats test server xd

**Comment by Janmm14** [comment]
Duplicate of #1214
