### ISSUE TITLE
JigSaw fastplace bypass

### ISSUE THREAD

**Issue by jolo613** [konsolas/AAC-Issues#1389]
**Server version**: 12.2.2 (latest) Paper version git-Paper-1427 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**AAC version**: Latest (3.3.15)

**ProtocolLib version**: Latest(4.3.0)

**Plugin list**: AAC, ConditionalCommands, EpicWorldGenerator, FastAsyncWorldEdit, MaxBansPlus, ProtocolLib, SilkSpawners, SuperVanish, Teleport, UltraPermissions, WorldEdit, WorldGuard

### Configuration
Celembridor's "optimized config" latest version.

AAC Logs: [aac_2018-05-27_17-34-04.log](https://github.com/konsolas/AAC-Issues/files/2043044/aac_2018-05-27_17-34-04.log)
[aac_2018-05-27_17-26-24.log](https://github.com/konsolas/AAC-Issues/files/2043049/aac_2018-05-27_17-26-24.log)
Server log: [latest.log](https://github.com/konsolas/AAC-Issues/files/2043045/latest.log)

 How to reproduce: Enable fastplace.
 Video : https://gyazo.com/c1f77cdb7373366bde091675ded42f93

**Comment by konsolas** [comment]
Same effect should be achievable by spamming right click.
