### ISSUE TITLE
AAC FLY BYPASS

### ISSUE THREAD

**Issue by Monstercide** [konsolas/AAC-Issues#1391]
mc.thePlayer.motionY = -8;
mc.timer.timerspeed = 0.9f;

**Comment by Janmm14** [comment]
Fly bypass with motionY = -2? Seems pretty useless

**Comment by Slimerblue22** [comment]
Video...or something (I got no clue how code works ok)

**Comment by Nort721** [comment]
well if this is how you are creating fly hacks I think you should quit, or learn about what the motion thing means

**Comment by Janmm14** [comment]
Please add more information and reply why this should be deemed a bypass for FLY @Monstercide

This just looks like sime useless and constantly flagging dastdown-miniglide (not tested).
