### ISSUE TITLE
Class init error aac.aI

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1394]
aac latest
yes viaversion
i use Paper-1414 (MC: 1.12.2)
protocolib latest
look this error by aac (photo)
https://drive.google.com/open?id=1oTx4VZPtYcRJq6KjC98mL5gaHyaRi0Mq
https://drive.google.com/open?id=1PZ0nz_XxUZWskSkQOyJPkEeOs2IM5VO2
https://drive.google.com/open?id=16AeLkWJWac869OmXbjchdn_gvVOXNHcY

**Comment by Janmm14** [comment]
Please ask your provider / look at info about the used java version and if it is java 8, ask them to upgrade to 8u152 or a later java 8 update

**Comment by leoncp9** [comment]
No dude, when i do /aacreload i need to restart all server because crash cause aac reload , This is my info about my server Minecraft Version: 1.12.2 Operating System: Linux (amd64) version 4.4.0-104-generic Java Version: 1.8.0_151, Oracle Corporation. i remove aac 3.3.15

**Comment by leoncp9** [comment]
when i do /aac i get this messagge "an internal error occured while attempting to perform this command"

**Comment by Janmm14** [comment]
Please try updating java to newest java 8 version 1.8.0_172 and check whether that issue is fixed by that please.

**Comment by leoncp9** [comment]
my host don't update :( so all user who used host who don't update java can't use aac? ...

**Comment by leoncp9** [comment]
dude write on description aac need java latest version because with my host i can't use aac plugin cause bad version of java (i use host)

**Comment by leoncp9** [comment]
Dude, the problem is not big problem.... sometimes work... sometimes i need to remove plugin... just i lost 6 hours to chat with my host cause aac, my host idiot don't upgrade :(

**Comment by leoncp9** [comment]
ok for now i can't use the plugin, my host will update java
