### ISSUE TITLE
Killaura FP when FastClicking

### ISSUE THREAD

**Issue by LoXR** [konsolas/AAC-Issues#1397]
### Issue description
So basically people who spam click on mobs seems to be falsely kicked for Killaura

### Core information
**Server version**: insert
git-Spigot-2086bb0-8cc5a7e (MC: 1.12.2)

**AAC version**: insert
AAC version 3.3.15

**ProtocolLib version**: insert
ProtocolLib version 4.3.0

**Plugin list**: insert
N/A

### Special environment information
**ViaVersion version**: insert (or N/A)
N/A

**ProtocolSupport version**: insert (or N/A)
ProtocolSupport version 4.29-dev

**ViaBackwards version**: insert (or N/A)
N/A

**BungeeCord plugins**: insert (or N/A)
N/A

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 
Just set hitboxes to false to see if it still consists thats all.

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

**Comment by konsolas** [comment]
Can't reproduce this at all. Going to need a lot more information.
