### ISSUE TITLE
AAC causing lag

### ISSUE THREAD

**Issue by GameModeOnX** [konsolas/AAC-Issues#1398]
### Issue description
https://cdn.discordapp.com/attachments/262588738939387904/445188098691956739/unknown.png
aac check is not active
https://cdn.discordapp.com/attachments/262588738939387904/445188206175191050/unknown.png
aac check is active
https://timings.aikar.co/?id=aa2361574406406f9bf25860cb68c3ab

### Core information
**Server version**: insert
1.8.8 paperspigot
**AAC version**: insert
3.3.15
**ProtocolLib version**: insert
4.3.0
**Plugin list**: insert
https://i.hizliresim.com/2a26bO.png
### Special environment information
**ViaVersion version**: insert (or N/A)
-
**ProtocolSupport version**: insert (or N/A)
-
**ViaBackwards version**: insert (or N/A)
-
**BungeeCord plugins**: insert (or N/A)

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 
https://hastebin.com/fakamatode.bash

**Comment by leoncp9** [comment]
confirm, on paper spgito 1.13.2 and aac latest version i get lag
