### ISSUE TITLE
Jesus FP | Swimming up next to water

### ISSUE THREAD

**Issue by Nvaros** [konsolas/AAC-Issues#1399]
If you swim up next to solid water slowly, you will be flagged for Jesus.
This also occurs for AAC 3.3.15.
Recording: https://youtu.be/NGVJhm7Fh6s
It is laggy, but actually I am trying to swim up constantly, but it causes AAC to drag me down. At the end of the video, you can see that this is a real FP and not a fake video.

**Comment by Minemaniak** [comment]
Duplicate of https://github.com/konsolas/AAC-Issues/issues/1171
