### ISSUE TITLE
[Bypass] Fastladder

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#14]
Fastladder is being bypassed by climbing nearly one block away from the ladder, possibly letting AAC think the whole ladder climbing time that the user just started climbing.

**Comment by konsolas** [comment]
Do you have offsets/similar that were used?

**Comment by Janmm14** [comment]
The source says the ladder gets 0.9 blocks thick while the player seems to climb up with x or z as ?.8.
Then the player is given an upwards velocity of .5 each time the client ticks (in this case).

Normally the player position to the ladder is ?.425

Please do not simply block these specific x/z coordinates :)

**Comment by Photon-GitHub** [comment]
The module expands the BlockCollisionBox to be on the ladder even before really being on the ladder, this apparently bypasses the climb check.

**Comment by konsolas** [comment]
Fix is live on the test server.
