### ISSUE TITLE
Move check is killing players.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1400]
### Issue description

We are getting more and more reports of the move check (@CeIebrimbor code 101) killing players upon their login back to the server. Here's some information from the latest case.

Example report from a player:
https://i.imgur.com/zJGjISK.png

Our server log instances of the reporting player:
https://pastebin.com/raw/RyN02JSN

AAC logs leading up to the kick, and just shortly following the player logging back in:
https://gist.githubusercontent.com/andrewkm/67bbe12d0a79ec46196ed33a73165a53/raw/209b46a7502c599d6711dfaf5b9dd4e7a4cf9707/gistfile1.txt

Any help would be highly appreciated. This has only been happening to us as of 3.3.15

Do let me know if you require any further information.

PS: We are not currently running AACAdditionPro.

### Core information
**Server version**: 1.12.2

**AAC version**: 3.3.15
**AAC config**: 3.3.15|1-Default-Celebrimbor

**ProtocolLib version**: 4.4.0 Build 398

**Plugin list**: (on request via Discord - andrewkm-0001)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Janmm14** [comment]
It looks like the player got some velocity (someone hitting him, shooting with a bow, maybe lava?)
What is your velocity min_vl? 3?

It looks like he then fell down and inside the void he did fall much too fast than AAC thought.

**Comment by andrewkm** [comment]
@janmm14 config setup is posted in issue above.

**Comment by konsolas** [comment]
I haven't had time to properly debug this issue so the temporary fix of deal_fall -> false was added in 3.3.15

**Comment by xion87** [comment]
Got the same issue #1488  maybe is the same thing?

**Comment by andrewkm** [comment]
For now I'm using deal_fall set to false which is helping us get by. :)
