### ISSUE TITLE
FastUse FP

### ISSUE THREAD

**Issue by Lorak-mmk** [konsolas/AAC-Issues#1401]
### Issue description
If you have some food in hand, start eating it and pressing q, after few dropped items you get flagged for FastUse and yours hand slot is changed.

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.14 (AFAIK FastUse wasn't changed in 3.3.15, so it should also work there)

**ProtocolLib version**: 4.2.0

**Plugin list**: AACA, AACAP, ProtocolLib, other are irrelevant, tested on few setups.

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Celebrimbors config.

**Comment by Janmm14** [comment]
(Hand slot is always changed when flagging fastuse)

**Comment by Minemaniak** [comment]
Vanilla 1.8.9

**Comment by Slimerblue22** [comment]
I think it does that because sometimes when you throw or pick up food while eating, it speeds up the eating time. (Makes you eat quicker)

**Comment by Rerd** [comment]
It doesn’t speed up consume times.

**Comment by Slimerblue22** [comment]
I timed it awhile ago, it sometimes does. But whatever, not really of importance tbh

**Comment by Janmm14** [comment]
Probably aac thinks u stop eating when amount of food changed, but it goes on. AAC resets eating time and then boom.
