### ISSUE TITLE
Fightspeed/Speed kicks while feeding rabbits.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1402]
### Issue description

We are getting kick complaints for constant kicking (@CeIebrimbor code 006 & 008) while feeding rabbits. Here's how one of the complaints looks from a trusted user that we can verify is not hacking.

Example report from a player:
https://i.imgur.com/kmIXeXS.png

> I keep getting kicked with code 008 and 006 while feeding rabbits. That's all I'm doing, feeding rabbits.

Our server log instances of the reporting player:
https://pastebin.com/raw/1CJLmRHE

AAC logs throughout the same time frame:
https://pastebin.com/raw/k2gL4gh7

Any help would be highly appreciated.
This has only been happening to us now as of 3.3.15 from my knowledge, although it may have been an issue in the past and I simply didn't know. We are running an event currently involving rabbits thus perhaps we are noticing it that much more now.

Do let me know if you require any further information.

PS: We are not currently running AACAdditionPro.

### Core information
**Server version**: 1.12.2

**AAC version**: 3.3.15
**AAC config**: 3.3.15|1-Default-Celebrimbor

**ProtocolLib version**: 4.4.0 Build 398

**Plugin list**: (on request via Discord - andrewkm-0001)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
Looks like this was caused by the player's extremely high ping, which might not be directly fixable by AAC, other than by using higher thresholds for players with high ping.
