### ISSUE TITLE
AAC only blocking a few hacks

### ISSUE THREAD

**Issue by UnlimitedNinjas** [konsolas/AAC-Issues#1403]
### Issue description

Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

ISSUE:
AAC doesnt block much hacks, only flight and spider and noslow etc.. killaura is not blocked

### Core information
**Server version**: 1.12.2

**AAC version**: 3.3.15

**ProtocolLib version**: 4.3.0

**Plugin list**: cant tell you sorry

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: NA

**ViaBackwards version**: NA

**BungeeCord plugins**: NA

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 
nothing

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

**Comment by Janmm14** [comment]
No effort.
