### ISSUE TITLE
Constant KillAura kicks with zombie pigmen spawners.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1404]
### Issue description

We are getting kick complaints for constant kicking (@CeIebrimbor code 013) while killing zombie pigmen at their spawners. Here's how one of the complaints looks:

Example report from a player:
https://i.imgur.com/GofX3kN.png

In depth thread on the issue:
https://www.ecocitycraft.com/forum/threads/skyblock-keep-getting-kicked-for-anticheat-013.176861/

From a bit of testing it seems to me that I can verify this only seems to happen when killing Zombie Pigmen, not other mobs, as the thread above states from another user here: https://i.imgur.com/rqUC7Ei.png

AAC logs throughout the report's time frame showing the KillAura kicks:
https://gist.githubusercontent.com/andrewkm/aab0908081aa8a6e6abe88f0df045960/raw/e1e5db9e996d60ea0e9e60071b76c0e71db8cc28/gistfile1.txt

Any help would be highly appreciated.

Do let me know if you require any further information.

PS: We are not currently running AACAdditionPro.

### Core information
**Server version**: 1.12.2

**AAC version**: 3.3.15
**AAC config**: 3.3.15|1-Default-Celebrimbor

**ProtocolLib version**: 4.4.0 Build 399

**Plugin list**: (on request via Discord - andrewkm-0001)
It is worth mentioning we are using a mob stacking plugin:
https://github.com/Nathat23/StackMob-2
Although there have been no notable changes to it I believe that would cause this issue.
(_I may very well of course be wrong_).

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by andrewkm** [comment]
We've disabled this for now and it has fixed the issue via:
```
killaura:
   check_mobs: false
```

**Comment by konsolas** [comment]
Killaura has been rewritten.
