### ISSUE TITLE
API method that allows FULL disabling AAC checks for specified player(s)

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#1405]
### Issue description
This topic is a suggestion to add a new feature to improve server performance.

*Please, if there is any possibility to realize this right now, write about it.*

At the moment, the AAC API only allows you to ignore the receipt of the players VL (with bypass permission), But the server still checks this player and performs the same load. 

Since the load from the anticheat is about 50-80% of the server load, then when the number of players that need to be checked is reduced, the load will fall dramatically .. It would be very logical for AAC not to check the player on bypass at all. I'm surprised that there is still no way to limit the checks of players. Anticipating the question of how the servers want to give bypass to players - I will say that this is a server problem, not the developers of AAC, I just ask you to give this opportunity. I very much hope for understanding on your part and I very much look forward to the implementation of such a function (if it is not yet envisaged).
(Sorry for my English)

**Comment by konsolas** [comment]
Currently the internal design of AAC means it is not easy to fully not process a player, because many checks require data from nearby players, which need to be processed for this data to be collected.
