### ISSUE TITLE
Interact block placing false positive

### ISSUE THREAD

**Issue by xion87** [konsolas/AAC-Issues#1406]
### Issue description
Player that are using 1.12.2 client in 1.8.9 server (viaversion) and they try to place blocks aac will detect it as hack (no kick but block disapears) 
log: https://gist.github.com/xion87/43fc1508ed621462ec1770f1fe8ac197
### Core information
**Server version**: insert
1.8.8+viaversion
**AAC version**: insert
3.3.15
**ProtocolLib version**: insert
4.3.0
**Plugin list**: insert
Not rilevant a basic skyblock server, same situation on all server
### Special environment information
**ViaVersion version**: insert (or N/A)
1.3.0
**ProtocolSupport version**: insert (or N/A)
N/A
**ViaBackwards version**: insert (or N/A)
N/A
**BungeeCord plugins**: insert (or N/A)
N/A
### Configuration
I am using the optimized Celebron configuration

**Comment by Janmm14** [comment]
There is no "fastblock" check. It is the interact check thats triggered there.

The logs you are seeing there show that aac thinks the client placed a block witohut looking at the correct position.

**Comment by Minemaniak** [comment]
Isn't it caused by this? https://github.com/konsolas/AAC-Issues/issues/977 I think it may be a dupe

**Comment by Janmm14** [comment]
@Minemaniak thats a feature request and no bug, so its no dupe
