### ISSUE TITLE
Error in the plugin api

### ISSUE THREAD

**Issue by Pikuuu** [konsolas/AAC-Issues#1407]
### Core information
**Server version**: 1.8.8

**AAC version**: latest

**ProtocolLib version**: 4.3.0

**Plugin list**: core, aac, protocollib, permissionsex

On this code:
https://pastebin.com/TVDxABf6

i have error in console:

https://i.imgur.com/Nm8h261.png

Can I fix this ?

Regards.

**Comment by konsolas** [comment]
PlayerViolationEvent may be called async.

You need to schedule a task to dispatch the command on the main thread.
