### ISSUE TITLE
New option in API

### ISSUE THREAD

**Issue by Pikuuu** [konsolas/AAC-Issues#1408]
Core information
Server version: 1.8.8

AAC version: latest

ProtocolLib version: 4.3.0

Plugin list: core, aac, protocollib, permissionsex

Konsolas, can You add for example AACAPIProvider.getAPI().enableCheck(player, HackType);
and 	AACAPIProvider.getAPI().disableCheck(player, HackType); ?

**Comment by konsolas** [comment]
You can cancel PlayerViolationEvent for the players that you want to have bypassed.
