### ISSUE TITLE
PlayerViolationEvent problem

### ISSUE THREAD

**Issue by Pikuuu** [konsolas/AAC-Issues#1409]
Core information
Server version: 1.8.8

AAC version: latest

ProtocolLib version: 4.3.0

Plugin list: core, aac, protocollib, permissionsex

Why PlayerViolationEvent see speed, fly, move but don't see killaura, velocity etc when i have aac.bypass command?

**Comment by Janmm14** [comment]
permissions are recached every 30 seconds
