### ISSUE TITLE
Nofall bypass by abusing speed flag (on official test server)

### ISSUE THREAD

**Issue by NaNaShiSan1** [konsolas/AAC-Issues#1410]
### Issue description

Nofall bypass by abusing speed flag on official test server.(cuz i dont have aac)
this also works on another test server like poke.sexy.
[https://www.youtube.com/watch?v=5xsAbjQ0AsM](https://www.youtube.com/watch?v=5xsAbjQ0AsM)

 

### Core information
test server
### Special environment information
test server
### Configuration
test server

**Comment by Nvaros** [comment]
The same applies for the fly check.

**Comment by Nvaros** [comment]
The latest AAC beta version (3.4.0 / official test sever) seems to have patched this "bypass".

**Comment by Janmm14** [comment]
Nice to hear that the fix attempt works. Thanks for your cooperation.
