### ISSUE TITLE
Killaura false positives/detections

### ISSUE THREAD

**Issue by Golicraft** [konsolas/AAC-Issues#1412]
### Issue description
Okay hi. I have an issue with the default killaura. Legit players are being flagged on vl: 150++. I have a video that you can see showing a fight with one of my servers best pvpers. It hasn't just happened with him but 5++ others too. I can, of course, send more videos from other of my players fighting but I hope this video lasts.

I am 99% he does not use illegal client mods. We have screenshared him many times and with different tools, Safeshare etc (if you have heard of that) Otherwise here is the video: https://www.youtube.com/watch?v=Td61Kz7CVBc&t=499s

As I talked to Celebrimbor he told me Gomme has this check almost disabled, I thought that is because of some false positives/detections. Luckily for you, I have taken my time to report it :+1: 

##Good to know
This happens on all my servers, not just KitPVP. 
- The video above is recording playing on the account, Wee_Callum22
Logs: https://pastebin.com/arqR6zgt

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 3.3.15

**ProtocolLib version**: 4.3.0

**Plugin list**: I will not show my plugins as others can see them. I can send a screen to Celebrimbor who can send it further to you, yes yes. 

### Special environment information
**ViaVersion version**: 1.30

**ViaRewind (make my server 1.7 to 1.12)**: 1.3.8

### Configuration
https://pastebin.com/BeJV14LV

Thanks. My dream is to have /ban with killaura checks, but I will dream further about 2 years yes yes xD

**Comment by konsolas** [comment]
Killaura has been rewritten.
