### ISSUE TITLE
Flight bypass

### ISSUE THREAD

**Issue by Monstercide** [konsolas/AAC-Issues#1413]
hi please listen for 1 sec i know your going to delete this or something but before you do can you help me know how to check if a player is on a slime block im working on a anticheat and my fly check flags if i bounce on a slime block so please tell me!
EDIT: heres all the aac bypasses on my channel - https://www.youtube.com/channel/UCYwxEaPmpZsvXTR4V64-p6A

**Comment by Janmm14** [comment]
If you don't know how to determine if a player is above a certain block you're definitely not the right one to create an anticheat.

PS: Your "flight bypass" is no "flight bypass", but more a minimalistic and from my point of view useless glide bypass.

Additionally its nothing new that the velocity check is in no way perfect.

**Comment by TeamOceanox** [comment]
you did not tell me how to do it
