### ISSUE TITLE
aristos and matix client can bypass speed control

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1416]
latest version of aac and protocolib
server paper sgpito 1.12.2 latest build
client aristos 1.12.2 have full bypass on speed control
client matix 1.12.2 sometims bypass speed control

**Comment by Janmm14** [comment]
Not enough information.

**Comment by leoncp9** [comment]
1 install paper spigot 1.12.2
2 install latest version of aac on your server
3 install latest verson of protocolib
4 use aristos or matix client
5 enjoiy free speed and bypass aac plugin

**Comment by Slimerblue22** [comment]
As far as I remember those clients are complete trash but I'll go check it out
*I'll edit this comment when I see if they bypass or not*

**Comment by Janmm14** [comment]
If you believe your issue was closed as a mistake, please provide REAL EVIDENCE in your bug report next time. Additionally please do NOT delete the template, but fill it out.
