### ISSUE TITLE
AACBan revamp and /aac command

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#142]
Right now I don't any server using the aacban feature of aac and it creates a useless text file.
Thus I would like to see some  improvements:
- Use a banwave system instead of aacban (you should be able to set the delay and the command
- A new placeholder: %check% to get the name of the check triggering the banwave-addition
- A banwave auto-adding config in certain checks (e.g. Nuker, Derp)
- A customizable kick command for the other checks (I would like to use litebans:kick on my server but after a fast relogin the player's vl is too high for another kick (e.g. Nuker vl 1000)) or a vl-setback to 0 after some sort of kick.
- Customizable command for the banwave-ban

//Some other stuff
- reenable the feature to block /aac and print out a command not found - message to players without a certain permission (cheaters use this to determine the anticheat).

**Comment by konsolas** [comment]
So you're suggesting a complete replacement of the current punishment system?

**Comment by Photon-GitHub** [comment]
Yes. The one right now is pretty standard and not used by the servers.

**Comment by Janmm14** [comment]
Will close as wonfix, other ban wave plugins can be used
