### ISSUE TITLE
AAC Speed

### ISSUE THREAD

**Issue by TeamOceanox** [konsolas/AAC-Issues#1420]
you did not talk to me in my last issue i want to know how to check if a player is on a slime block
	                  	      if(p.getLocation().getBlock().getRelative(BlockFace.DOWN).getType().equals(Material.SLIME_BLOCK)) {
	                	    	  return;
	                	      }

this does not work so please help me

**Comment by Janmm14** [comment]
Stop posting irrelevant stuff on this issue tracker.

**Comment by 0-x-2-2** [comment]
This is the wrong place to ask this is for issues for aac not bukkit coding class 8
