### ISSUE TITLE
Weird Kick Bug when using Timer or Vanilla Fly

### ISSUE THREAD

**Issue by TreesPlay** [konsolas/AAC-Issues#1424]
### Core information
**Server version**: 1.8.8

**AAC version**: 3.4.0

**ProtocolLib version**: Build: 341

**Plugin list**: On Request, AACAP is installed but the Bug works perfectly without it

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: idk what this is

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration

Spam protection turned off
Removed all AACStaffNotify

Config: http://aac-test.pw/aacconfig.yml
Config generated by AAC 3.3.14 or AAC 3.3.10

### Other Information

aac.bypass and OP doesn't help still kicks :/
Not only Kicks for Timer also for Vanilla Fly when not Creative, but for Flying only Players without aac.bypass and OP get kicked
If i disable Bungee the Kick Message is on my Screen
Screen Error: http://aac-test.pw/errorscreen.png

Links:

Video: http://aac-test.pw/thisbugisreallyannoying.mp4
Bungee Error: http://aac-test.pw/bungeeerror.txt
Serverprotocol: http://aac-test.pw/serverprotocol.txt

I know you can see my IP, but what's the Deal of it xd

I hope this is enough Information, if not PM me Discord: TreesPlay#7754 and i will send you the Plugin List!

**Comment by TreesPlay** [comment]
How can i add Labels, im too dumb for this?

Can someone add Bug, Move?

**Comment by Janmm14** [comment]
1. Labels can only be added by people with special access.
2. A cheat client getting kicked is no bug for me under any circumstance.

**Comment by TreesPlay** [comment]
But i should get kicked for something like "[AAC] < Bad Packets" or for an Error

This is a Testserver kicked get displayed as Title, here an Error happens which kicks me so that's the Problem

**Comment by Janmm14** [comment]
Test servers are not allowed by aac eula

**Comment by TreesPlay** [comment]
i know, but this doesn't fix the bug

**Comment by Janmm14** [comment]
I don't care
