### ISSUE TITLE
IllegalArgumentException | Adding Locations of different worlds.

### ISSUE THREAD

**Issue by Francy1978** [konsolas/AAC-Issues#1425]
**Server version**: PaperSpigot-1.12.2

**AAC version**: 3.4.0

**ProtocolLib version**: Build 403

**Plugin list**: BedWars1058, ProtocolLib, AACAdditionPro, ProtocolSupport & AAC.

### Special environment information
**ViaVersion version**: (N/A)

**ProtocolSupport version**: latest

**ViaBackwards version**: (N/A)

**BungeeCord plugins**: BungeeReport

error: https://pastebin.com/raw/70MYUdAG

**Comment by Photon-GitHub** [comment]
Please notice that "latest" is not a valid version as the affected plugins might be updated regulary and we cannot reproduce your problem in this case.

**Comment by Janmm14** [comment]
Duplicate of #1422
