### ISSUE TITLE
Interact FP: Players unable to break certain nonfull blocks

### ISSUE THREAD

**Issue by KennyTV** [konsolas/AAC-Issues#1426]
### Issue description
Players are not able to break cobweb, distance to the block doesn't matter (with and without swords, versions 1.8-1.13)
24.07 21:34:01 [Server] INFO [AAC] [VERBOSE] i___i___i failed Interact: broke a block out of line of sight [ping:23 tps:20.0] VL:3
24.07 21:34:01 [Server] INFO [AAC] [VERBOSE] i___i___i failed Interact: interacted with a block out of his line of sight [ping:23 tps:20.0] VL:2

### Core information
**Server version**: 1.8.8 Paper

**AAC version**: 3.4.0

**ProtocolLib version**: 4.3.0

**Plugin list**: -

### Special environment information
**ViaVersion version**: 1.4.2-SNAPSHOT

### Configuration
Optimized Config without changes

**Comment by Janmm14** [comment]
Same for vines, signs, rails and maybe levers and buttons
