### ISSUE TITLE
AAC having issues with TreeFeller

### ISSUE THREAD

**Issue by HyperGaming18** [konsolas/AAC-Issues#1430]
Alright, so the plugin version I'm using is latest. I double checked and triple checked. I also used default configs and It still kicked players.

Link to the survival kicks ( over 1000 ) https://hypergaming.co.uk/punishments/kicks.php

The plugin AAC is having issues with: https://www.spigotmc.org/resources/tree-feller-async.20385/

The issue happens when a user attempts to chop down a tree with any axe and the plugin kicks for nuker or fast break.

**Comment by Photon-GitHub** [comment]
TreeFeller and similar plugins are explicitly listed in the "AAC may be incompatible with" list on the overview as "Any plugins that affect block interaction out of a player's line of sight." AAC does not provide support for these plugins, instead please contact the author of the TreeFeller plugin.

**Comment by Janmm14** [comment]
(The API of AAC to code against is available for free on this github or on my maven repo, more info is in the readme of this github)
