### ISSUE TITLE
Unexpected exception while parsing console command "aac"

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1434]
### Issue description

Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: paper spigot 1.12.2

**AAC version**: insert 3.4.2-b1

**ProtocolLib version**: insert  4.3.0

**Plugin list**: insert aac

### Special environment information
**ViaVersion version**: insert (or N/A) 1.4.2 snapshot

**ProtocolSupport version**: insert (or N/A) no

**ViaBackwards version**: insert (or N/A) latest dev

**BungeeCord plugins**: insert (or N/A) no

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".
DOWNLOAD LOG
https://drive.google.com/open?id=1nryow7CfXcHd0pSdjbM3OqRu6MQkLQz8
i get this error on console 
 Unexpected exception while parsing console command "aac"
org.bukkit.command.CommandException: Cannot execute command 'aac' in plugin AAC v3.4.2 - plugin is disabled.

**Comment by leoncp9** [comment]
[AAC] Error enabling AAC: 0x04

**Comment by konsolas** [comment]
This is fixed by 3.4.2-b2.
Thanks for reporting.
