### ISSUE TITLE
Speed check causing problems with epearls

### ISSUE THREAD

**Issue by iPintoBean** [konsolas/AAC-Issues#1435]
### Issue description

Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: fork of paper spigot 1.8.8 (Beerspigot)

**AAC version**: lastest version

**ProtocolLib version**: Lastest version

**Plugin list**: https://gyazo.com/ddc1dcb6d7d8dd973d170c90042424a0

### Special environment information
**ViaVersion version**:  1.3.0

**ProtocolSupport version**: n/a

**ViaBackwards version**: n/a

**BungeeCord plugins**: n/a

### Configuration
You can just say for Config- "Celebrimbor's Optimized Config"

I don't know if this is a config issue or a plugin issue but if a faction has a claim outside enemy territory and they fly from their territory into the enemy land it gives the player damage until they die.

There is also this weird thing happening when a player jumps from a stack of blocks, throws and epearl in the air. When the epearl hits the ground the player gets stuck in a loop where they just keep dying and taking damage. It looks like he is walking sideways. It looks like some sort of voodoo happening XD.

It looks as though they are setting off the speed check in some instances.

**Comment by Photon-GitHub** [comment]
Please note that „latest“ is not a valid version as it is very hard to track it back after a few updates. (Especially as ProtocolLib is frequently updated). Also a video of your bug would be helpful.
