### ISSUE TITLE
False Flags on Teleport

### ISSUE THREAD

**Issue by ArrowReport** [konsolas/AAC-Issues#1436]
### Issue description

Getting False Flags for Teleporting

Using Commandblock with
/tp @p %x% %y%.2 %z%

(.2 Teleports the .2 Blocks higher so they'll don't fall through Block when they have a bad Ping)

### Core information
**Server version**: 1.8.8

**AAC version**: 3.4.2

**ProtocolLib version**: b341 (v4.2.0)

### Special environment information
**ViaVersion version**:  1.3.0

### Flags:

http://pasted.co/a61d3fa4

**Comment by ArrowReport** [comment]
I found out the Problem, so the Commands port you like ~1000 Block away, then you Glide into the Ground because the Chunks are not loaded for you and the Anticheat thinks your using Phase

**Comment by konsolas** [comment]
This should be harmless, as Phase should not be configured to kick players. In this case, AAC is substituting the default NMS behaviour which would keep the player above the ground anyway.
