### ISSUE TITLE
Clicking on the title of Minecraft hangs it. AAC flags for fly 

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#145]
When so jump off a cliff and click onto the MC Application Title in 1.8 the Client hangs. When you release the cursor you got flagged for flying.

**Comment by konsolas** [comment]
Clients can simulate this to hover. Undesirable in games such as bedwars where a player can essentially hover under the map, invincible.

The detection of hovering is intended behaviour.
