### ISSUE TITLE
Applying high velocity (knockback 100+) will flag speed and no knockback

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#146]
Hitting a player with a knockback 100 stick will cause him to not move and generate speed violations. Due to the setback of the speed violation the player also gets a no knockback violation.

**Comment by CeIebrimbor** [comment]
At what extent is it unreasonable to accommodate a knockback level that would never be used? I see servers with KB X in kits, but who would ever use 20+ on a real server?

**Comment by geNAZt** [comment]
Still getting this with KB lvl 10 / 15 / 20

https://www.youtube.com/watch?v=thixL2dBn80&feature=youtu.be

**Comment by konsolas** [comment]
Fixed, confirmed by @Photon-GitHub
