### ISSUE TITLE
ImpossibleInteraction whilst breaking a block

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#147]
When you stand on a block and break the block infront of that block (you look down) and you slowly look upwards and the target of the client changes you get flagged for impossible interact

**Comment by Janmm14** [comment]
There is a cancel_vl present (see #55), also take a look at https://github.com/konsolas/AAC-Issues/issues/81#issuecomment-256620407 by konsolas.

So basically getting flagged does not mean the interact would've been cancelled, if you stay below that vl (I think that'll likely happen). also its not intended to kick.

I just hope that cancel_vl will not stop cancelling if interacts are clearly impoosible (throuh blocks).

**Comment by Photon-GitHub** [comment]
This is intended and will probably not be fixed.

**Comment by geNAZt** [comment]
No mine is quite different. I just break blocks while going and get violations:

https://www.youtube.com/watch?v=JYVzlVHETDc&feature=youtu.be

**Comment by Photon-GitHub** [comment]
One vl 2 violation can safely be ignored. This is no big issue and it is not kicking.

**Comment by CeIebrimbor** [comment]
It blocks interaction when detected? That is something to be concerned over if AAC randomly cancels interactions. If it requires VL 4 to cancel, then so be it.

**Comment by konsolas** [comment]
Switching blocks when moving cannot be helped; it is an unfixable bug.

Similar to NCP's blockinteract_visible check where you'll just get spammed if you hold left click and look around.
