### ISSUE TITLE
[Bypass] Phase/Spider

### ISSUE THREAD

**Issue by v0idst4r** [konsolas/AAC-Issues#148]
If you clip into a block successfully, you can jump all the way to the top. It's kind of like CheckerClimb. https://youtube.com/watch?feature=youtu.be&v=MDQxtVR44r8

**Comment by boomboompower** [comment]
@v0idst4r this is called 'block glitching'. Also this is not a direct issue with AAC, this can happen without hacks anyway

**Comment by v0idst4r** [comment]
It is an issue with AAC, it's supposed to block things like this.

**Comment by Photon-GitHub** [comment]
1) This flags a lot.
2) This is hard to patch, especially with legit possibilities to achieve this
3) Checkerclimb bypass with a lot of flags is certainly not top priority.

**Comment by v0idst4r** [comment]
@Photon-GitHub If you do it correctly, you can do it with little to no flags.

**Comment by v0idst4r** [comment]
@Photon-GitHub I've tried hclipping 0.006 into the block, getting one flag (i think, cant tell since im not a tester), turning on phase which sets bounding boxes above your feet null, and jumping

**Comment by konsolas** [comment]
Fixed.
