### ISSUE TITLE
Cannot add locations of different worlds@C.a:44 (subtract) v3.5.0

### ISSUE THREAD

**Issue by Alperenn** [konsolas/AAC-Issues#1481]
### Issue description
Exception photo: http://prntscr.com/ki3o2q

### Core information
**Server version**: 1.12

**AAC version**: 3.5.0

**ProtocolLib version**: Build #403 (09.Tem.2018 22:35:10)

**Plugin list**: http://prntscr.com/ki3mw9

### Special environment information
**ViaVersion version**: 1.4.1

**ProtocolSupport version**: N/A

**ViaBackwards version**: 2.3.1

**BungeeCord plugins**: http://prntscr.com/ki3nj0

**Comment by Alperenn** [comment]
http://prntscr.com/ki5uv4 @Photon-GitHub

**Comment by Janmm14** [comment]
@Alperenn Please for a visibly different issue open also a new issue on here.

**Comment by LoYungSum** [comment]
I got this error too. But this time it is caused by my own plugin. So what should I change in my coding to teleport a player to different worlds without causing this error by AAC?

**Comment by Janmm14** [comment]
@LoYungSum I don't think its solvable from your code.
AAC needs to solve that.

**Comment by Janmm14** [comment]
Maybe causes extreme lag on workd switch through BlockBreakEvent.
See issue 1507
