### ISSUE TITLE
Cannot add locations of different worlds@C.a:44 (subtract)

### ISSUE THREAD

**Issue by MatinDark** [konsolas/AAC-Issues#1483]
### Issue description
There is error on console https://hastebin.com/eyelipopoc.cs

### Core information
**Server version**: PaperSpigot 1.12.2

**AAC version**: 3.5.0-b1

**ProtocolLib version**: 4.4.0-SNAPSHOT-b406

**Plugin list**: Request via Discord Matin_Dark#0001

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: NO

**ViaBackwards version**: 2.3.1

**BungeeCord plugins**: Matin_Dark#0001

Configuration : Cele's Config

**Comment by Janmm14** [comment]
Duplicate of #1481
