### ISSUE TITLE
AntiKnockBack/Velocity Fully Bypass

### ISSUE THREAD

**Issue by jiangdashao** [konsolas/AAC-Issues#1486]
### Issue description
Client: LiquidBounce b54
Bypass Mode: AAC and AACPush
Horizontal: 0~1
Vertical: more than 0.08 (if the vertical value less than 0.08,it will trigger Fly flag)

Not just the LiquiddBounce client, many paid clients also bypass

https://imgur.com/a/kbAtPtY

### Core information
**Server version**: 1.8.9

**AAC version**: 3.5.0-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: AAC,ProtocolLib

### Configuration
Cele's optimized Configuration

**Comment by CrackFileso** [comment]
LiquidBounce's Kiilaura is scrapped now.
