### ISSUE TITLE
AAC 1.13 error

### ISSUE THREAD

**Issue by Purplegigabyte** [konsolas/AAC-Issues#1487]
### Issue description
So i updated my server to 1.13 and AAC gives me this error whenever i try to start it up

https://gist.github.com/Purplegigabyte/a70dc2344445142a0355610ec222ac83

### Core information
**Server version**: 1.13

**AAC version**:  3.5.0-b1

**ProtocolLib version**: v4.4.0-SNAPSHOT-b414

**Plugin list**: AAC ProtocolLib

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

**Comment by Photon-GitHub** [comment]
AAC is not yet compatible with 1.13.
