### ISSUE TITLE
Damage on /tp /warp /spawn

### ISSUE THREAD

**Issue by xion87** [konsolas/AAC-Issues#1488]
### Issue description
Peple ocasionally get falling damage when doin /tp or /warp or /spawn
https://gist.github.com/xion87/215939800706345485cfc3553727c1a6 (a guy died for using /spawn at  time 10:28:33)

### Core information
**Server version**: 1.8.8 Paperspigot

**AAC version**: 3.5.0-b1

**ProtocolLib version**: v4.4.0-SNAPSHOT-b403

### Configuration
Using Latest Celebrion config

**Comment by Janmm14** [comment]
It would be great if you can somehow provide an aac debug log of that situation, for example if theres a player where it happens multiple times.

If enabled, AAC will log check specific data and many player actions from all online players into a debug log file inside plugins/AAC/.
WARNING: AAC debug logging can generate really huge files.
You can toggle the debugging state with /aacdebug, everytime debug is disabled a new debug file will be generated.
A debug log is especially useful for movement related issues.
