### ISSUE TITLE
Wolfram killaura

### ISSUE THREAD

**Issue by BioMasterHZ** [konsolas/AAC-Issues#1489]
### Issue description
Wolfram bypasses killaura check easily

### Core information
**Server version**: 1.12

**AAC version**: 3.5.0

**ProtocolLib version**: 4.4.7.0

**Plugin list**: insert

### Special environment information
**ViaVersion version**: insert (or N/A)

**ProtocolSupport version**: insert (or N/A)

**ViaBackwards version**: insert (or N/A)

**BungeeCord plugins**: insert (or N/A)

**Comment by Janmm14** [comment]
Your issue would be more readable if you delete the exlanatory text.
And if your issue description would not be below, but in the section for the issue description.
