### ISSUE TITLE
flux b13 killaura bypass

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1490]
### Issue description

Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: insert paper 1.12.2

**AAC version**: insert latest

**ProtocolLib version**: insert latest

**Plugin list**: insert no plugin, 

### Special environment information
**ViaVersion version**: insert (or N/A) no viaverions

**ProtocolSupport version**: insert (or N/A) no potocolsupport

**ViaBackwards version**: insert (or N/A) no

**BungeeCord plugins**: insert (or N/A) no bungee 

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

Flux b13 have killaura aac mode, if i set , range 1.5 , aps 10, switch delay 800/1000 fow 360, i can kill all with killaura without i get kick 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

**Comment by leoncp9** [comment]
how can i set a short delay for kick istant for killuara? because for now, kick arrive after 3/ 5 minutes

**Comment by leoncp9** [comment]
scaffold mode aac of flux b13 bypass control of aac

**Comment by leoncp9** [comment]
safewalk of flux b13 = scaffold = is possible block?

**Comment by Janmm14** [comment]
delayed kick in aac 3.5.0 means that aac wasn't sure enough before accoridng to default config.

**Comment by leoncp9** [comment]
ok thank
