### ISSUE TITLE
False Postive: Killaura (switch) aimbot-like yaw patterns

### ISSUE THREAD

**Issue by ArrowReport** [konsolas/AAC-Issues#1496]
### Issue description

**False Positive:**

Killaura (switch) aimbot-like yaw pattern
(https://youtu.be/wlqZcxzfsow)

**Comment by konsolas** [comment]
Video shows a maximum of VL 2 being reached. This is not even close to the cancel threshold of 30.

**Comment by Janmm14** [comment]
@ArrowReport no
