### ISSUE TITLE
Tp issue

### ISSUE THREAD

**Issue by IHazCow** [konsolas/AAC-Issues#1498]
### Issue description
The issue is when teleporting is that either NoFall or the Fly checks force people to take damage on teleporting. Not sure how to fix that. 

### Core information
**Server version**: PaperSpigot 1.8.8

**AAC version**: 3.5.0-b1

**ProtocolLib version**: 4.4.0-SNAPSHOT-b403

**Plugin list**: https://i.gyazo.com/61d5818a131db4137eda7fef113a4017.png

### Special environment information
**ViaVersion version**: 1.5.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 
Default, with modifications for testing the issue. Other than that it is default. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

**Comment by konsolas** [comment]
seems to be similar to all the other teleportation issues.
