### ISSUE TITLE
AAC errors a "No internet connection." on startup.

### ISSUE THREAD

**Issue by Spark3757** [konsolas/AAC-Issues#1499]
### Issue description
AAC starting too long (about 2-3 minutes), it prints that server dont have internet connection. But server has.

Log: https://gist.github.com/Spark3757/3873a2dd84880ea109f764fb00ff75c0
### Core information
**Server version**: insert

**AAC version**: 3.5.0

**ProtocolLib version**: 4.2.0

**Plugin list**: -

### Special environment information
**ViaVersion version**: 1.5.0

**ProtocolSupport version**: -

**ViaBackwards version**: -

**BungeeCord plugins**: -

**Comment by Spark3757** [comment]
Server can connect to cloudflare. What i need to do else?

**Comment by Janmm14** [comment]
What happens when you try `ping konsolas.net` on your server?

**Comment by Baterka** [comment]
Still exists in 4.3.12

**Comment by Janmm14** [comment]
@Baterka Please do not bump old issues.

Additionally, this is no issue. This is intended behaviour.
