### ISSUE TITLE
[Bypass] Criticals

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#15]
Mini-Jump criticals can bypass your check.
Src of a bypassing criticals mod:
`double posX = mc.thePlayer.posX;
			double posY = mc.thePlayer.posY;
			double posZ = mc.thePlayer.posZ;
			
			mc.thePlayer.connection.sendPacket(new CPacketPlayer.Position(posX, posY + 0.0625D, posZ, true));
			mc.thePlayer.connection.sendPacket(new CPacketPlayer.Position(posX, posY, posZ, false));
			mc.thePlayer.connection.sendPacket(new CPacketPlayer.Position(posX, posY + 0.001D, posZ, false));
			mc.thePlayer.connection.sendPacket(new CPacketPlayer.Position(posX, posY, posZ, true));`

Possible check method (probably not removed all false positives):
If (player velocity == 0 && player hurttime == 0)
{
//No small jump heights can be achieved legit
-> flag
}

**Comment by Photon-GitHub** [comment]
Also think of the other methods:
Small motionY - values or y-port criticals.

**Comment by konsolas** [comment]
A version of this check is now on the test server. Please re-open if it doesn't catch what it should.
