### ISSUE TITLE
Knockback check FP

### ISSUE THREAD

**Issue by MedicOP** [konsolas/AAC-Issues#1505]
Using Celebrimbor config and latest AAC version

How to reproduce: Simply keep hitting someone while they try to stay in the same spot, VL will go up to the point of kick

**Comment by Janmm14** [comment]
Knockback check is old and therefore disabled by default. It was not deleted in case people have problems with its replacement, the velocity check.
A configuration comment also states this: https://gist.github.com/konsolas/400c9678e0264fab8d04d84780ec4c63#file-config-yml-L296
