### ISSUE TITLE
Extreme lag on world change

### ISSUE THREAD

**Issue by SyqlexxPI** [konsolas/AAC-Issues#1507]
### Issue description

Error: https://paste.md-5.net/kecolorufi.avrasm 

This mistake comes in between when you change the world. After this error, all players time out

### Core information
**Server version**: 1.12.2

**AAC version**: 3.5.0

**ProtocolLib version**: 4.3.0

### Special environment information
**ProtocolSupport version**: build 176

**Comment by Janmm14** [comment]
Duplicate of #1481
