### ISSUE TITLE
/aacreload needs to be used twice to reload config

### ISSUE THREAD

**Issue by MedicOP** [konsolas/AAC-Issues#1511]
/aacreload needs to be used twice to reload config.

Example: I disable velocity check in the config then type /aacreload, it doesn't actually disable it. I need to type the command again and then it disables it.

Using latest of everything, but this bug has been around since 3.0.0

**Comment by Photon-GitHub** [comment]
Is this actually a bug @konsolas or some required / desired behaviour?

**Comment by Rerd** [comment]
Why would that be required or wanted?

**Comment by Photon-GitHub** [comment]
When it has been around since 3.0.0 it could be the result of some data restructuring in that version (might be beneficial to performance or makes the code easier).
