### ISSUE TITLE
TPS decrease

### ISSUE THREAD

**Issue by Pikuuu** [konsolas/AAC-Issues#1514]
### Core information
**Server version**:  1.8

**AAC version**: latest

**ProtocolLib version**:  4.4.0-SNAPSHOT-b403

**ViaVersion version**: ---

**ProtocolSupport version**: ---

**ViaBackwards version**: ---

**BungeeCord plugins**: auth plugin, custompayloadfixer, bungeetablistplus, skinrestorer

Is it possible to correct the code? TPS decrease ...

0.90% (     0.56s) me.konsolas.aac.av.lambda$handleMoveInPVP$0()
0.07% (     0.04s) me.konsolas.aac.bZ.m()
0.03% (     0.02s) me.konsolas.aac.c0.a()

**Comment by Pikuuu** [comment]
Such a load was only for 30 people, so I'm afraid to think what will happen to more players.

**Comment by yyunusyigit** [comment]
@Pikuuu , we have the same problem: http://prntscr.com/l4th32

**Comment by Photon-GitHub** [comment]
1.8 is an unsupported version. Please update to 1.8.8

**Comment by Janmm14** [comment]
The error log shows they're using v1_8_R3 and aac wouldnt load at all if it was just 1.8 and not 1.8.8
