### ISSUE TITLE
walking on 1.13.2 causes spam

### ISSUE THREAD

**Issue by FrankHeijden** [konsolas/AAC-Issues#1517]
https://paste.md-5.net/bacopapabu.avrasm

walking causes this ^ 
### Core information
**Server version**: 
1.13.2
**AAC version**: 
3.6.0
**ProtocolLib version**: 422

**Comment by konsolas** [comment]
@FrankHeijden could you try redownloading the newest version? You might have missed a silent update posted only a short while after release.

**Comment by FrankHeijden** [comment]
no doesn't work for me, still errors, but idk if these are the same or new:

https://paste.md-5.net/gibumamofi.avrasm
https://paste.md-5.net/galokudade.avrasm

**Comment by konsolas** [comment]
Could I get a full latest.log right from the beginning?

**Comment by FrankHeijden** [comment]
I sent it in a PM to you

**Comment by konsolas** [comment]
Possibly a plugin compatibility issue at the moment

**Comment by FrankHeijden** [comment]
Can confirm, citizens was the issue

**Comment by konsolas** [comment]
3.6.2 resolves the citizens issue.
