### ISSUE TITLE
Arrow doesn't fly further in a jump

### ISSUE THREAD

**Issue by wasder** [konsolas/AAC-Issues#1518]
### Issue description
On a server with AAC:
https://dl.dropboxusercontent.com/s/xkg4gxcllg5pt4l/2018-10-27_17-02-19.mp4
On the same version of PaperSpigot but without AAC:
https://dl.dropboxusercontent.com/s/4vs19l3tff0dq06/2018-10-27_17-16-55.mp4

### Core information
**Server version**: 
PaperSpigot 1.12.2
**AAC version**: 
3.3.15

**ProtocolLib version**: 
ProtocolLib v4.4.0-SNAPSHOT-b390

### Special environment information
**ViaVersion version**: 
1.5.2 on BungeeCoord

**ViaBackwards version**: 
2.3.1 on BungeeCoord

### Configuration
Celebrimbor's configs.

**Comment by konsolas** [comment]
The test cases are very different. In the original "CastleWars 2" server, it looks like there are a lot of plugins which could all be interfering with arrow velocity. AAC shouldn't interfere with projectile velocity in any way.

I have tested this on a local server and have found that AAC does not affect arrow trajectory.

Can you prove that this is AAC's fault?

**Comment by wasder** [comment]
It is affected by Nofall check. Please see my new video:
https://dl.dropboxusercontent.com/s/rl65bmee5kjr8v4/2018-10-28_22-12-36.mp4

**Comment by wasder** [comment]
Same on 3.5.0
