### ISSUE TITLE
Stairs

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1521]
### Core information
**Server version**: paper spigot 1.13.2

**AAC version**: 3.6.2 (STILL BETA)

**ProtocolLib version**: latest

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ?? ProtocolSupport#300

**ViaBackwards version**: ?? no

**BungeeCord plugins**: ?? no

### Configuration

when i walk on Stairs i have a problem, i use 1.8.8 version for play, server is paper 1.13.2

**Comment by leoncp9** [comment]
https://gist.github.com/leoncp9/000244c73306d7ebe5e3a9976c7b04cb

**Comment by leoncp9** [comment]
photo
https://drive.google.com/open?id=1QJLyvhVHtrSJZRv4xfSMCHgRC72PxQMm

**Comment by leoncp9** [comment]
the problem is only when I go up

**Comment by konsolas** [comment]
Looks like this is a 1.13 only issue
