### ISSUE TITLE
Overview page and mention of heuristics check

### ISSUE THREAD

**Issue by ArrowReport** [konsolas/AAC-Issues#1523]
### Issue description
Found this on AAC Overview:

But wait, I heard that AAC's Killaura detection is easily bypassed!
That strongly depends on how you define "bypassed". What you won't find if you're running AAC is any killaura that gives the user a significant advantage. Some good "smooth aim" or "triggerbot" cheats are undetectable (heuristics are trying its best), no matter what anyone tells you. It's also basically useless, no matter what anyone tells you.

Which heuristics lol, check got rm -rf'd

**Comment by Janmm14** [comment]
Heuristics were combined with killaura check into some general classes of heuristics, they're not actually removed.
