### ISSUE TITLE
Fly kick when in bubble column

### ISSUE THREAD

**Issue by FrankHeijden** [konsolas/AAC-Issues#1525]
### Issue description
Try a "bubble-column" lift and see AAC flagging people for fly and eventually kicking them.

### Core information
**Server version**: CraftBukkit version git-Spigot-e4d0c66-aed3aec (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**AAC version**: 3.6.3

**ProtocolLib version**: 422

### Configuration
Celebrimbor

**Comment by LogGits** [comment]
We are also experiencing this issue on `3.6.4`
