### ISSUE TITLE
[3.6.3] Random numbers in the console

### ISSUE THREAD

**Issue by Sikatsu** [konsolas/AAC-Issues#1526]
### Issue description
Random numbers show up in the console. They are really spammy too.

04.11 12:21:35 [Server] INFO -0.07384623611779162
04.11 12:21:35 [Server] INFO -0.03236931369801255
04.11 12:21:35 [Server] INFO 0.10178080259764322
04.11 12:21:35 [Server] INFO 0.0814246432914345

http://prntscr.com/le7iui

### Core information
**Server version**: 
This server is running CraftBukkit version git-Spigot-117d4f7-96c461b (MC: 1.13.2)
**AAC version**: 
3.6.3
**ProtocolLib version**: 
4.4.0

### Configuration
Celebrimbor

**Comment by Photon-GitHub** [comment]
Close in favor of #1540
