### ISSUE TITLE
Giant velocity

### ISSUE THREAD

**Issue by Drizz1** [konsolas/AAC-Issues#1528]
AAC: 3.6.3
Protocol: 4.3
PaperSpigot

Mob Giant - "BOSS" is pushing other players in my plugin. And Boss is pushing itself.

**Comment by FrankHeijden** [comment]
Please paste in paste.md-5.net or use code brackets

**Comment by powerax** [comment]
https://paste.md-5.net/luxibagita.avrasm

**Comment by FrankHeijden** [comment]
That error is not related to AAC? It’s related to something like “Skript”

**Comment by Janmm14** [comment]
Closed as it doesn't look like an AAC issue to me. 
If you want to report a false positive, include debug or verbose output from aac.
