### ISSUE TITLE
[Feature] Chat click notifications

### ISSUE THREAD

**Issue by ThePigKnight** [konsolas/AAC-Issues#153]
Hey it would be cool if AAC had like a notification of 3 choices and you would have to click in the chat for them to trigger.
[BAN] would ban the player
[KICK] would kick the player
[INVESTIGATE] would Teleport you to the player with vanish enabled(if your server is runing a vanish based plugin) if not you will be teleported to the player only.

ACC > KingOfKings will be automaticlly banned in X seconds for Kill Aura [BAN] [KICK] [INVESTIGATE]
a.k.a

AAC > KingOfKings will be automatically banned in %amount% seconds for %check5 [%ban%] [%kick%} [%investigate%]

**Comment by v0idst4r** [comment]
Fancy.

**Comment by Janmm14** [comment]
I actually never had a usage for this library, but I grant permission to konsolas to use it fully or parts of it, maybe also changed in his plugin without any attribution required: https://github.com/Janmm14/JsonMessageMaker

**Comment by ThePigKnight** [comment]
welp i misspelled the %check% down

**Comment by v0idst4r** [comment]
I think you misspelt "wrong" too

**Comment by Rqcco** [comment]
https://gyazo.com/4f934b90195adf82039d320dff729574

**Comment by Photon-GitHub** [comment]
Will not be implemented.
