### ISSUE TITLE
Fly bypass

### ISSUE THREAD

**Issue by variationtime** [konsolas/AAC-Issues#1530]
1.8.9 spigot, with latest possible AAC version (custom config *celebmrimbor*)
ProtocolLib 4.4.0
### Special environment information
ViaVersion version 1.6.0
ViaBackwards version 2.3.1

https://www.youtube.com/watch?v=msNc4qkMovA
https://yadi.sk/d/pe5eY0sewWFtrA - cheat client which he used
I have no idea how he did this, but as u can see, this is fresh video. Any fix?

**Comment by Janmm14** [comment]
your fly min_vl is too high in config

**Comment by Janmm14** [comment]
See #1502

**Comment by Janmm14** [comment]
Very likely duplicate of #1502
