### ISSUE TITLE
Jumping and Spinning around while holding Right-Click causes MUCH Interact FP's

### ISSUE THREAD

**Issue by ArrowReport** [konsolas/AAC-Issues#1531]
### Issue description
Jumping and Spinning around while holding Right-Click causes MUCH Interact FP's

Poof! eh no, ehm Proof:
https://vgy.me/tRP8O6.mp4

Btw, the new Interact Check doesn't seem to support the Bypass Permission anymore

### Core information
**Server version**:  1.8.8

**AAC version**: 3.6.3

**ProtocolLib version**:  4.4.0

**Plugin list**: Not Required

### Configuration
Spam Check = oof
Removed AACStaffNotify Stuff

**Comment by Janmm14** [comment]
AAC caches permissions, wait a half minut eor a minute after changing permissions or rejoin.

**Comment by ArrowReport** [comment]
Btw, The Bypass Permissionen, rejoining or having OP still doesn't disable the new Interact Check 

You also get these False Flags when you use the WorldEdit Compass
https://vgy.me/RUkGKv.mp4

**Comment by ArrowReport** [comment]
Found even more False Positives

https://vgy.me/Dw89YT.mp4
