### ISSUE TITLE
Constant kicking while breaking ICE.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1533]
### Issue description

We are getting issues with constant kicking (@CeIebrimbor code 022) while breaking ICE.
Complaints have been verified and reproduced.

AAC logs throughout the same time frame:
https://pastebin.com/raw/BMZ8VZsD

### Core information
**Server version**: 1.13.2

**AAC version**: 3..6.3
**AAC config**: 3.6.3|1-Default-Celebrimbor

**ProtocolLib version**: 4.4.0 Build 422

**Plugin list**: (on request via Discord - andrewkm-0001)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Photon-GitHub** [comment]
I cannot reproduce this even with a efficiency 5 diamond pickaxe. After 3 mined stacks of ice I had at most 2 vl.
