### ISSUE TITLE
.PacketPlayInFlying@5312881f[

### ISSUE THREAD

**Issue by Plooper12** [konsolas/AAC-Issues#1535]
Server Version 1.8.8-R0.1-SNAPSHOT
AAC v3.6.3
ProtocolLib v4.4.0-SNAPSHOT-b390
I've been doing some tests in the Lobby I've got about 250 bots and for some reason I jump this error

[AAC] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC
java.lang.NullPointerException
Parameters:
net.minecraft.server.v1_8_R3.PacketPlayInFlying@5312881f[
x=0.0
y=0.0
z=0.0
yaw=0.0
pitch=0.0
f=true
hasPos=false
hasLook=false

**Comment by Janmm14** [comment]
After that there should be a bunch of lines stzarting with "at" in the log / console.

Without those, the bug cannot be resolved.

**Comment by Plooper12** [comment]
> After that there should be a bunch of lines stzarting with "at" in the log / console.
> 
> Without those, the bug cannot be resolved.

https://pastebin.com/7vUNZTTS
