### ISSUE TITLE
Playerradar

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#154]
I noticed the PlayerRadar check is still in AAC3.
I either recommend to remove it (just some useless code) or doing the recode I recommended you some time ago (Fake invis players, hiding sneaking players and entities without nametag behind walls, etc.)

**Comment by v0idst4r** [comment]
Players with special attributes like that wouldn't be hard at all to filter out, why not normal entitys inside blocks that you cant see without esp/tags/tracers/radar?

**Comment by v0idst4r** [comment]
Then again it wouldn't be hard to check if they're inside a block

**Comment by Janmm14** [comment]
The best option would be to just hide players who are sneaking or not in line of sight.

**Comment by konsolas** [comment]
Going to be deleting this check for now.

**Comment by v0idst4r** [comment]
vouch
