### ISSUE TITLE
AAC allows glitching through gaps while swimming.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1541]
### Issue description

With the below setup, AAC allows glitching through gaps while swimming.
With AAC: https://www.youtube.com/watch?v=qTCS4DFOM3I
On Vanilla: https://www.youtube.com/watch?v=iQjfllPd5XU

### Core information
**Server version**: 1.13.2

**AAC version**: 3..6.3
**AAC config**: 3.6.3|1-Default-Celebrimbor

**ProtocolLib version**: 4.4.0 Build 422

**Plugin list**: (on request via Discord - andrewkm-0001)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by xtomyserrax** [comment]
Yeah this happens in another servers too. It is like it doesnt detect yet the half block swimming, wish it gets fixed soon! Thanks for the amazing work!
