### ISSUE TITLE
AAC 3.6.4 causing major server hang for several seconds.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1544]
### Issue description

AAC 3.6.4 causing major server hang for several seconds.
Logs just before hang, during hang, and just after hang:
https://gist.githubusercontent.com/andrewkm/b93c1973ec205e83552cb2a75e1dc023/raw/f7436aeb6bc987d1aec4c102dd865c0fc4ef2fed/gistfile1.txt
AAC logs just before hang, during hang, and just after hang:
https://gist.githubusercontent.com/andrewkm/367f1c59c53e267cf52d4fc787803019/raw/79574681942a04baa314474733bb26274ed01799/gistfile1.txt

### Core information
**Server version**: 1.13.2

**AAC version**: 3..6.4
**AAC config**: 3.6.3|1-Default-Celebrimbor

**ProtocolLib version**: 4.4.0 Build 422

**Plugin list**: (on request via Discord - andrewkm-0001)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by andrewkm** [comment]
For the record, this issue happened yesterday on 3.6.3 as well using exact same setup as above, however on AAC 3.6.3.

Logs for that occurence can be found here:
https://gist.githubusercontent.com/andrewkm/a1505199a364183d92b8518cdcb4a9e1/raw/bc110b57593ad09d4ff4655ba5dcf700e1a66ffe/gistfile1.txt

**Comment by Janmm14** [comment]
Seems to be related to block breakage  / playerblock interaction.

**Comment by CeIebrimbor** [comment]
Didn't you just implement an API related to block breaking?

**Comment by andrewkm** [comment]
@celebrimbor yes @photon-GitHub did, however it wasn’t live until after these errors.

These errors occurred prior to using photon’s changes.

**Comment by konsolas** [comment]
Should be fixed in 3.6.4-b1
