### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KennyTV** [konsolas/AAC-Issues#1546]
### Core information
**Server version**: 1.8.8

**AAC version**: 3.6.4

**ProtocolLib version**: 4.4.0

### Special environment information
**ViaVersion version**: 1.6.0

The following error appeared a few times in the console: https://hastebin.com/yeqicuvuto.pl

**Comment by Janmm14** [comment]
Unfortunaly the hastebin is not loading or already deleted again.

Please uplaod to https://pastebin.com or https://gist.github.com
