### ISSUE TITLE
Phase False Positive

### ISSUE THREAD

**Issue by v0idst4r** [konsolas/AAC-Issues#155]
https://youtu.be/x64ni3Mlv9Kk

**Comment by v0idst4r** [comment]
Oops. https://youtu.be/x64ni3miv9k

**Comment by v0idst4r** [comment]
:/ Making typing this on a phone is hard, sorry.

https://youtu.be/x64ni3MIv9k

**Comment by NEZNAMY** [comment]
Also causes a fly kick.

**Comment by konsolas** [comment]
Fixed.
