### ISSUE TITLE
False positive interact kick for using McMMO shake on shulkers.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1552]
### Issue description

Users report:
Brief Description: Kicked for using mcmmo shake on shulkers
Instructions: Hold down right click on a shulker with a fishing rod
How many times did you recreate this?: 5 times
Result: Kicked for 022
Expected Result: To not get kicked and successfully kill the shulker
Original report: https://ecocitycraft.com/forum/threads/kicked-for-022-for-shaking-shulkers.179044/

Video included:
https://www.youtube.com/watch?v=YKz4RDHq0Cw

### Core information
**Server version**: 1.13.2

**AAC version**: 3.6.4-b1
**AAC config**: 3.6.3|1-Default-Celebrimbor
One config adjustment running at KillAura.Click: 0

**ProtocolLib version**: 4.4.0 Build 422

**Plugin list**: (on request via Discord - andrewkm-0001)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Janmm14** [comment]
whats 022?

**Comment by andrewkm** [comment]
Interact, as stated in the title.

**Comment by Janmm14** [comment]
oops
