### ISSUE TITLE
Placing a block against a ladder = Interact violation 

### ISSUE THREAD

**Issue by Lysandr0** [konsolas/AAC-Issues#1558]
### Issue description
https://www.dropbox.com/s/jf5xrlwx679txjh/Interact%2BLadder.mov?dl=0

### Core information
**Server version**: Spigot 1.12.2

**AAC version**: v3.6.4

**ProtocolLib version**: v 4.4.0

### Special environment information
Nothing on the special environment.

### Configuration
Default config

**Comment by Pesticidus** [comment]
The bug still exists on the latest version (4.1.8)

Log: https://pastebin.com/fxpRNyq0
Video: https://youtu.be/MnpxOFzpm8o

**Comment by konsolas** [comment]
duplicate of #1720 (which was created on the newest version).
