### ISSUE TITLE
Clients can still sprint if hunger is at 6 halfs or below

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#156]
Tested in 1.8
If hunger goes down to 3 = 6/2 legit you're not able to sprint anymore, while clients can still send that they're sprinting.
Additionally clients are not setbacked when they sprint while they don't send that they're sprinting (they stay at vl 7 and it does not get higher really)

**Comment by Janmm14** [comment]
@konsolas Using killaura while jumping near players also causes speed vl7 - is this your start of verifying sprint directions?

**Comment by v0idst4r** [comment]
You can even sprint without sending the START_SPRINTING packet.

**Comment by Janmm14** [comment]
@v0idst4r
Thats basically the same issue.

**Comment by v0idst4r** [comment]
@Janmm14 The speed between not sprinting and sprinting is very small and would cause alot of false positives

**Comment by Photon-GitHub** [comment]
A packet level detection is possible but a normal is some work...

**Comment by Janmm14** [comment]
Packet-Level detection is not needed, because in that case clients simply fake the sprinting and recieve vl7 permanently. Also it should be possible to use the bukkit api to get whether a player is sprinting.
As it already flags vl7 permanently I think it should be possible to just increase that specific threshold.

**Comment by Photon-GitHub** [comment]
Will be fixed by using my plugin.
