### ISSUE TITLE
Printer

### ISSUE THREAD

**Issue by HairHen** [konsolas/AAC-Issues#1561]
I am using Printer and the AAC is Kicking me for Killaura

https://pastebin.com/U5jgaez0

### Core information
**1.8 BeerSpigot**: 

**3.6.3**: 

**ProtocolLib version**: 

**None**: 

### Configuration
https://www.diffchecker.com/Vp603CWm

**Comment by CeIebrimbor** [comment]
This is not a bug and AAC is not able to provide support for Mods. As such, you will probably need to make some alterations to your config.

Printer impacts the Interact, Fastplace, and Speed Check. You don’t have to disable any of them to make it work.
 
**Interact: **Set `cancel_ghost_block` false
**Fastplace: **Raise `max_place_per_second` until printer users no longer get flagged (the number will depend on your printer speed settings)
**Speed: **Set `max_sneak_toggles` higher, again, depends on your printer settings.
**Killaura: **If Killaura is sending violations (less common), set `click` to 0
