### ISSUE TITLE
Killaura getting detected while mining

### ISSUE THREAD

**Issue by TrollC** [konsolas/AAC-Issues#1563]
Issue: Killaura False Positive

Description: When a player mines on skyblock in a particular way, they get kicked for killaura.
Extra: I am using celebrimor's setup
Screenshots of mining type: https://imgur.com/a/VI1OtEn
Steps to reproduce: 
1. Mine in the way shown on the pictures
2. Get kicked for killaura

**Server version**: 
Spigot 1.12.2 latest

**AAC version**: 
3.5.0

**ProtocolLib version**: 
4.4.0

**Plugin list**: 
StaffTools, AACAdditionPro, NCP 

**ViaVersion version**:  1.6.0

**ProtocolSupport version**: not used

**ViaBackwards version**: 2.3.1

**BungeeCord plugins**: dont think they matter

**Comment by Janmm14** [comment]
what do aac logs show for the kicked players? aka what type of killaura?

**Comment by TrollC** [comment]
here is a pastebin https://pastebin.com/rbeJXknu
