### ISSUE TITLE
Horse Bug 1.8.8 - velocity check - ERROR in CONSOLE

### ISSUE THREAD

**Issue by TonnyBear** [konsolas/AAC-Issues#1565]
When player riding horse and jump its triggering velocity check and give big error in console.

Error in console: https://pastebin.com/nhVijKaW
AAC log: https://pastebin.com/4zaxRHzg

Server version:  Spigot 1.8.8

AAC version: 3.6.4

ProtocolLib version:  ProtocolLibDEV#341

Plugin list
AAC, KitBattle, VanishNoPacket, EssentialsChat, EssentialsSpawn, PvPManager, GroupManager, PlaceholderAPI, Essentials, ProtocolLib

ViaVersion version: 1.6.0

**Comment by TonnyBear** [comment]
Ok. I change it to pastebin

**Comment by Janmm14** [comment]
Can you try using a newer ProtocolLib version?
