### ISSUE TITLE
Hack Client Crash AAC v3.6.3

### ISSUE THREAD

**Issue by Plooper12** [konsolas/AAC-Issues#1566]
Server Version 1.8.8-R0.1-SNAPSHOT
AAC v3.6.3
ProtocolLib v4.4.0-SNAPSHOT-b390
https://pastebin.com/KUFqRwxx

**Comment by irworks** [comment]
We are experiencing the same issue, it might be related to disabling `movement.Speed` and `movement.Fly`.

**Comment by irworks** [comment]
They do not really „crash“ the server, it freezes all movements for all players.

**Comment by Janmm14** [comment]
Anyone had this with AAC 3.6.4? Internal stuff was changed
