### ISSUE TITLE
Speed false positive while fighting often vl 7

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#157]
Yeah you don't get bugged back, but you reach vl 7 very often

**Comment by konsolas** [comment]
This seems to be a duplicate of #101 as hits themselves don't cause any alerts.

**Comment by Janmm14** [comment]
@konsolas I tested this on the 1.8 test server, so #101 can't be the issue.

**Comment by Janmm14** [comment]
Created a video: https://www.youtube.com/watch?v=IHrISJsCsGI

**Comment by Janmm14** [comment]
@konsolas @genazt
I think this is the issue of many false-setbacks on the qsg-test, because if a player gets this violation and another vl7 violation of the vl7 false positives which are ignored, it gives some vl > 12 and people will be setbacked falsely.

**Comment by Janmm14** [comment]
Fixed by @konsolas, fix tested by me.
