### ISSUE TITLE
Sigma 3.1.11 HighJump(3blocks) Bypass

### ISSUE THREAD

**Issue by XnimaPRO** [konsolas/AAC-Issues#1570]
Server Version: Spigot 1.8.8
AAC Version:3.6.4
PL Version:4.4.0
Sigma 3.1.11

**Comment by XnimaPRO** [comment]
Sorry，Is SKID Can HighJump :( SKid 12.3 can bypass highjump and scaffold

**Comment by Janmm14** [comment]
You can actually edit title and issue description.
