### ISSUE TITLE
Liquidbounce B60 Killaura Bypass

### ISSUE THREAD

**Issue by XnimaPRO** [konsolas/AAC-Issues#1571]
Server Version: Spigot 1.8.8
AAC Version:3.6.4
PL Version:4.4.0
LiquidBounce Killaura Could Bypass with a low VL, with liquidbounce built-in AAC Config

When Players Attacking Normaly or just shake their head slightly when attacking,you Will get KA FPs

**Comment by Janmm14** [comment]
For the false positive mentioned in last line, please open a new issue with some video showing *how extensively you try to behave like a killaura*
