### ISSUE TITLE
Feature Request:improve AntiSpam

### ISSUE THREAD

**Issue by XnimaPRO** [konsolas/AAC-Issues#1575]
AAC 's Spam Detection is toooo wooden, it just Check Players message's Delay Between each message.
AAC has an 'whitelist' to make words like GG,LOL cant be detected. 
Also,AAC Cant Block some insulting words,like FXXK.
So,why dont add an'blacklist' that can make some words like fXck,AXXhole,NXXXXXY can be detected directly and Kick Players Sent Messages that including these rude words? When Player Sent some words in blacklist in aacconfig ,aac can block and notify to player that sent these message is kick and bannable?

The wooden antispam makes aac spam detection too weak and useless,PLZ Improve it.Like Add An BlackList System .
THX

**Comment by XnimaPRO** [comment]
I am too Active to report issues in AAC with a BAD eng    
:0

**Comment by Janmm14** [comment]
The spam detection is just there to prevent excessive spam.
If you want a chat filter plugin, there are likely many free and some good ones around.

**Comment by CeIebrimbor** [comment]
v4.0 will not have the Spam check
