### ISSUE TITLE
AAC Killaura action VL ignoring AAC.bypass perm

### ISSUE THREAD

**Issue by yorik100** [konsolas/AAC-Issues#1576]
### Core information
**Server version**: 1.8.8 latest Spigot

**AAC version**: 3.6.4-b1

**ProtocolLib version**: Latest

**Plugin list**: /

### Special environment information
**ViaVersion version**: Latest

**ProtocolSupport version**: /

**ViaBackwards version**: /

**BungeeCord plugins**: /

### Configuration : Default

PLEASE DO NOT WRITE YOUR ISSUE DESCRIPTION HERE -->
![image](https://user-images.githubusercontent.com/16320315/50424942-a7bab780-086d-11e9-972e-b9b795ee71c6.png)
This lil "action" thing totally ignores AAC.bypass perm, just that, the rest is fine
Same for "move" check

**Comment by yorik100** [comment]
Exactly, I mean, that's what AAC.bypass is made for, like Hypixel youtubers who got Watchdog disabled for example, but AAC.bypass should cover EVERY checks, not a matter of what a want but a matter of what it should normally do, it's a glitch and I report it.

**Comment by Janmm14** [comment]
Sure, thanks for the report.

I just remembered it being already reported and marked as intentional that its kicking: https://github.com/konsolas/AAC-Issues/issues/1414

So that portion won't get fixed in AAC.
