### ISSUE TITLE
teleport paper spigot 1.13.2

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1583]
### Core information
**Server version**:  paper spigot 1.13.2

**AAC version**: 3.6.4-b1 (BETA)

**ProtocolLib version**: ProtocolLib#422

**Plugin list**: latest

### Special environment information
**ViaVersion version**: ?? no

**ProtocolSupport version**:ProtocolSupport#329

**ViaBackwards version**: ??no

**BungeeCord plugins**: ?? no

**Comment by Janmm14** [comment]
Please describe your issue.

**Comment by leoncp9** [comment]
when i teleport me to other destination of map, i get glitch and i can't move after tp or teleport, if i remvoe aac this problem is fixed, with aac is not fixed, i can't move if i tp to other player cause i stay stuck on block

**Comment by Janmm14** [comment]
Ok.
Please do this:
1. Enable debug logging with /aacdebug
2. Teleport so you get stuck
3. Disable debug logging with /aacdebug again
4. Upload your debug log (in `plugins/AAC/` folder)

**Comment by leoncp9** [comment]
If i use 1.13.2 no problem, bu if i use 1.8.8 i get a problem, this is a log, can you say me what can i do now? i need to disable fly or other control of hack?
https://drive.google.com/open?id=1tLjbLOwQ891_5O0-yzvXW-inNRnBudor

**Comment by leoncp9** [comment]
ok thank

**Comment by Janmm14** [comment]
You need to leave this open.

**Comment by leoncp9** [comment]
oook :)
