### ISSUE TITLE
AAC 3.5.0 Glide Bypass

### ISSUE THREAD

**Issue by FAKE1007** [konsolas/AAC-Issues#1587]
### Issue description
In this video: https://www.youtube.com/watch?v=UxEQsfQxXMQ Dark Light Neron(hack creator) uses Glide AAC Bypass with his hack. The server is TeslaCraft, and it uses AAC 3.5.0
I also downloaded this hack and found out that it really works on AAC 3.5.0(Tested servers: TeslaCraft, ForsCraft)

### Core information
**Server version**: Unknown/Unnecessary

**AAC version**: 3.5.0

**ProtocolLib version**: Unknown/Unnecessary
**Plugin list**: Unknown/Unnecessary

### Special environment information
**ViaVersion version**: Unknown/Unnecessary

**ProtocolSupport version**: Unknown/Unnecessary

**ViaBackwards version**: Unknown/Unnecessary

**BungeeCord plugins**: Unknown/Unnecessary

### Configuration
Unknown configuration

### More info
If you need more info, I can record a video with this hack. I can also send link to this hack if you need.

**Comment by Janmm14** [comment]
Too lenient configuration VERY likely. Ask the owners of those servers t oreport again with neccessary configuration information (fly and speed mostly).
