### ISSUE TITLE
AAC FPs when a player jumping that the player has jumpboost effect

### ISSUE THREAD

**Issue by XnimaPRO** [konsolas/AAC-Issues#1589]
pl latest
aac 3.6.4

if player has jumpboost effect , aac FPs this player is flying

**Comment by Janmm14** [comment]
1. What level of jump boost?
2. Always false positive or just in certain conditions? (Like only when jumping on place, jumping onto blocks, etc.)
3. Verbose logs please (screenshot with /aacverbose on (needs verbose in config on beforehand) or an aac log (plugins/AAC/logs) excerpt where a player is just trying to jump with jumpboost) 
4. Optional: A video with /aacverbose on and a player trying to jump with jumpboost.

**Comment by XnimaPRO** [comment]
jumpboost 1 will FP, jump with jumpboost 255 will make that player stuck
Alwalys FP. just jump normaly with jumpboost nomatter capriole or jump into blocks
i will send verbose later
