### ISSUE TITLE
v3 Soulsand with Ice causing fly

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#159]
Soulsand flags for fly when you sprint through it with ice, https://www.youtube.com/watch?v=YbQVpgkk87A

**Comment by Photon-GitHub** [comment]
It is the hitbox problem. I will move this to #122 .

**Comment by Photon-GitHub** [comment]
No duplicate and still there.

**Comment by Rqcco** [comment]
Still a thing

**Comment by konsolas** [comment]
Finally :P
