### ISSUE TITLE
Memory leak with unloaded worlds.

### ISSUE THREAD

**Issue by Esmorall** [konsolas/AAC-Issues#1592]
### Issue description

I am creating my own mini-game plugin, in which I have to load and unnload worlds constantly for the games, I have seen that there is a memory-leak so I have made a profile using VisualVM and I have analyzed the memory with Eclipse Memory Analyzer, where I have found that the "WorldServer" Object is the one that occupies most of the ram, and has references all directed to different classes of AAC.

I have the same problem using the lastest version of AAC, but i still prefer using 3.5.0

https://imgur.com/yLOZQII

### Core information
**Server version**: spigot-1.8.8

**AAC version**: 3.5.0-1 (the lastest that is not in BETA)

**ProtocolLib version**: 4.4.0

**Plugin list**: 

### Special environment information
**ViaVersion version**: 1.6.1-SNAPSHOT

**ProtocolSupport version**: not installed

**ViaBackwards version**: not installed

**BungeeCord plugins**: SkinsRestorer, LiteBans, PowerFulPerms, BuycraftX, MultiLobby, RedisBungee

### Configuration
I use the custom configuration of Celebrimbor, but disabled log file, and some options that cancels/delays hiting/block placing

**Comment by Esmorall** [comment]
I have the same problem using AAC 3.6.4, and yes, there are references to Locations on some classes of AAC into WeakHashMaps. but not matter how many times i perfomr a GC there are still references of the worlds

**Comment by BestMark** [comment]
I had this problem on Spigot 1.8.8 before, too, but after upgrading to 3.6.4, it is now gone, if you look memory leak in the Memory Analyzer Tool. Please, recheck with latest version.

**Comment by Esmorall** [comment]
i hope this get fixed son, i am currently restarting the server every X games to prevent the memory leak

**Comment by Janmm14** [comment]
@Esmorall
Maybe a /aacreload can clear the memory leak too, I would give it a try.

**Comment by Esmorall** [comment]
> @Esmorall
> Maybe a /aacreload can clear the memory leak too, I would give it a try.

i tried, and it remove like the 80% of the worlds from the memory, but it still keeps a lot, in my server can be played more than 1000 games daily, so at the night it has 200+ loaded worlds on memory

**Comment by Janmm14** [comment]
Please note too that the future of AAC is unknown because konsolas is not answering.
