### ISSUE TITLE
LiquidBounce b60 teleport bypass

### ISSUE THREAD

**Issue by XnimaPRO** [konsolas/AAC-Issues#1593]
aac 3.6.4
PL (latest)
U can use Blink+AAC350 Teleport to teleport (32metres)

aac movement check detected but aac didnt do some action like cancel,Pull Back just have vl

**Comment by XnimaPRO** [comment]
infact blink can bypass many thing .like aac nofall

**Comment by ArrowReport** [comment]
dafuq

**Comment by CrackFileso** [comment]
A Video with useful informations Please.
Useless to describe by plain txt.

**Comment by Janmm14** [comment]
> infact blink can bypass many thing .like aac nofall

One bug per issue please.

**Comment by Janmm14** [comment]
Please do:
1. /aacdebug
2. Do the teleport
3. Disable /aacdebug
4. Upload the created debug log file to gist.github.com or pastebin.com (set to never expire)

Please prepare everything so the time /aacdebug is active is as short as possible.

Also please state the used server version.

**Comment by Toshka17** [comment]
Client: Liquid Bounce b62, version: 1.8.9

Server version: paper 1.12.2
Config AAC: *i don't want to make it public*

Video: https://yadi.sk/i/uB91z0-35u34HA
AACDubug: 
[debug.f55c03e1-eefc-4f24-ac90-0d894ef72e4c.debug.log](https://github.com/konsolas/AAC-Issues/files/3116783/debug.f55c03e1-eefc-4f24-ac90-0d894ef72e4c.debug.log)
