### ISSUE TITLE
Error, idk where it came from

### ISSUE THREAD

**Issue by dabou0** [konsolas/AAC-Issues#1595]
### Issue description

 https://pastebin.com/wZu36SQb

never used the plugin in a production server, just bought a few days ago and used a custom config i bought from Celebrimbor, it was working fine the plugin, never changed nothing, another day started the server and bump, got this error from nowhere, i didnt even needed to join the server, just on the stratup it appeared, no new plugins.

### Core information
**Server version**: 
Spigot 1.12.2

**AAC version**: 
last

**ProtocolLib version**: 
[last]

**ViaVersion version**: ??
[1.4.1]

**ProtocolSupport version**: ??
[last ]

### Configuration
[Using custom config bought from Celebrimbor]

**Comment by CeIebrimbor** [comment]
Please contact me on the contact method used to purchase my content.

**Comment by CeIebrimbor** [comment]
Make sure your server has internet connection on startup.
