### ISSUE TITLE
Nuker cheats not blocked properly.

### ISSUE THREAD

**Issue by Lysandr0** [konsolas/AAC-Issues#1597]
### Issue description
https://www.dropbox.com/s/5x5d7tw0ky3gval/Nuker.mov?dl=0

As you can see from the video, the cheat does get picked up by the various check, but they don’t seem to cancel the player’s event/action. (or not enough at least).
### Core information
**Server version**: Spigot 1.12.2

**AAC version**: AAC v3.6.4

**ProtocolLib version**: ProtocolLib v4.4.0

### Special environment information
n/a
### Configuration
I only tweaked the kick thresholds in order to better demonstrate the issue in the video :p

**Comment by Janmm14** [comment]
AAC is no creative mode anticheat.
