### ISSUE TITLE
[Bypass] Sprintjumping-like speeds

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#16]
The speeds working with the default configuration are about 15% faster, so its not the world, but still.

Speed mode names working with default configuration: BHopAAC1 and BHopSpartan1

Maybe @Photon-GitHub can provide the sources, I'm on my phone now.
Basically its increasing speed on the ground significantly and slightly while jumping. (Force-jumping)

**Comment by konsolas** [comment]
The names aren't worth much without a client or code to go with it.

**Comment by Photon-GitHub** [comment]
Yes, just wait a min.

**Comment by Photon-GitHub** [comment]
Disclaimer: This is my own src and not the AlphaCentauri src, but it works:
`if(mc.thePlayer.onGround)
			{
				mc.thePlayer.motionX = 0;
				mc.thePlayer.motionZ = 0;
				mc.thePlayer.jump();
			}else{
				if(	mc.thePlayer.motionX <= Cer.instance.optionManager.speedOptionManager.getSpeedFloatOption(SpeedDivider.class).getValue() / 10 &&
					mc.thePlayer.motionZ <= Cer.instance.optionManager.speedOptionManager.getSpeedFloatOption(SpeedDivider.class).getValue() / 10 &&
					mc.thePlayer.motionX >= -Cer.instance.optionManager.speedOptionManager.getSpeedFloatOption(SpeedDivider.class).getValue() / 10 &&
					mc.thePlayer.motionZ >= -Cer.instance.optionManager.speedOptionManager.getSpeedFloatOption(SpeedDivider.class).getValue() / 10)
				{
					mc.thePlayer.motionX *= Cer.instance.optionManager.speedOptionManager.getSpeedFloatOption(SpeedMultiplier.class).getValue() / 5;
					mc.thePlayer.motionZ *= Cer.instance.optionManager.speedOptionManager.getSpeedFloatOption(SpeedMultiplier.class).getValue() / 5;
				}
			}`

Perfect values for:
multiplier:  8.83
divider: 5.58

it flags a bit, but works.

**Comment by Janmm14** [comment]
Its nearly everything from https://twitter.com/SirJava_Buddy/status/779781492855767044

There is also an older leak which is actually the full source and its compiled version. Don't know whether its still downloadable janmm14.de/qunamc/dl/282 or /dl/283
DL instructions: www.blackspigotmc.xyz/threads/how-to-download-my-stuff.32/ (No I'm not him)

**Comment by konsolas** [comment]
Speed check is being rewritten. I will put up a whitelisted test server soon, these may be invalidated.

**Comment by Photon-GitHub** [comment]
Fixed on the test-server, recommended to close this issue.
