### ISSUE TITLE
AAC MySQL Error

### ISSUE THREAD

**Issue by santafejay** [konsolas/AAC-Issues#1600]
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
00:48:57 [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
00:48:57 [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
00:48:57 [SEVERE] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
00:48:57 [SEVERE] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
00:48:57 [SEVERE] at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
00:48:57 [SEVERE] at com.mysql.jdbc.Util.getInstance(Util.java:408)
00:48:57 [SEVERE] at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
00:48:57 [SEVERE] at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
00:48:57 [SEVERE] at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
00:48:57 [SEVERE] at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
00:48:57 [SEVERE] at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
00:48:57 [SEVERE] at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2030)
00:48:57 [SEVERE] at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
00:48:57 [SEVERE] at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
00:48:57 [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
00:48:57 [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
00:48:57 [SEVERE] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
00:48:57 [SEVERE] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
00:48:57 [SEVERE] at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
00:48:57 [SEVERE] at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
00:48:57 [SEVERE] at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
00:48:57 [SEVERE] at java.sql.DriverManager.getConnection(DriverManager.java:664)
00:48:57 [SEVERE] at java.sql.DriverManager.getConnection(DriverManager.java:247)
00:48:57 [SEVERE] at iiiiIIIIIiIiiiIiii.IIIIIIIiIiIIiiiiIi(MySQL.java:34)
00:48:57 [SEVERE] at iiiiIIIIIiIiiiIiii.<init>(MySQL.java:24)
00:48:57 [SEVERE] at IIIIIIIiIiIIiiiiIi.onEnable(AACBungeeConnect.java:123)
00:48:57 [SEVERE] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
00:48:57 [SEVERE] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)
00:48:57 [SEVERE] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
00:48:57 [SEVERE] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
00:48:57 [SEVERE] Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
00:48:57 [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
00:48:57 [SEVERE] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
00:48:57 [SEVERE] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
00:48:57 [SEVERE] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
00:48:57 [SEVERE] at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
00:48:57 [SEVERE] at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
00:48:57 [SEVERE] at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:342)
00:48:57 [SEVERE] at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2197)
00:48:57 [SEVERE] at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2046)
00:48:57 [SEVERE] ... 19 more
00:48:57 [SEVERE] Caused by: java.net.ConnectException: Connection refused (Connection refused)
00:48:57 [SEVERE] at java.net.PlainSocketImpl.socketConnect(Native Method)
00:48:57 [SEVERE] at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
00:48:57 [SEVERE] at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
00:48:57 [SEVERE] at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
00:48:57 [SEVERE] at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
00:48:57 [SEVERE] at java.net.Socket.connect(Socket.java:589)
00:48:57 [SEVERE] at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
00:48:57 [SEVERE] at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:301)
00:48:57 [SEVERE] ... 21 more
00:48:57 [INFO] [AACBungeeConnect] ================================[COPY STACK TRACE UP TO HERE]================================
00:48:57 [INFO] [AACBungeeConnect] Could not create the MySQL Table! Plugin doesn't work! Please PM Noali2000 with the following StackTrace on the SpigotForums, if you belive this is a plugin error!
00:48:57 [INFO] [AACBungeeConnect] ================================[COPY STACK TRACE FROM HERE]================================
00:48:57 [SEVERE] java.lang.NullPointerException
00:48:57 [SEVERE] at iiiiIIIIIiIiiiIiii.IiIiiiIiiiIiIIIIiI(MySQL.java:64)
00:48:57 [SEVERE] at iiiiIIIIIiIiiiIiii.<init>(MySQL.java:25)
00:48:57 [SEVERE] at IIIIIIIiIiIIiiiiIi.onEnable(AACBungeeConnect.java:123)
00:48:57 [SEVERE] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
00:48:57 [SEVERE] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)
00:48:57 [SEVERE] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
00:48:57 [SEVERE] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Photon-GitHub** [comment]
This is not an issue of AAC, but of AACBungeeConnect. That author is not affiliated with konsolas in any way.
