### ISSUE TITLE
aackick drop item help

### ISSUE THREAD

**Issue by AtakanULUKAN** [konsolas/AAC-Issues#1620]
### Issue description
With the aackick command, players do not fall when they are thrown out of the server. In order to make things fall, I'm enforcing the kill command at first, but even the non-killaura throws from the server. Can we have the stuff to fall?

### Core information
**Server version**: 
Spigot 1.8.8
**AAC version**: 
3.6.4
**ProtocolLib version**: 
 4.4.0

**Comment by Photon-GitHub** [comment]
Sou can configure the commands in the config. In your case you likely want to execute the kill command before the kick command.
