### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dabou0** [konsolas/AAC-Issues#1624]
### Issue description

Error: https://pastebin.com/scD6SbNB

Happened once and never more, and after leaving the server.

### Core information
**Server version**: 

Custom 1.8.8 Spigot, fork of Paper (Taco)

**AAC version**: 

3.5.0

**ProtocolLib version**: 

4.4.0

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

2.0.1

**ProtocolSupport version**: ??

Not using

**ViaBackwards version**: ??

Not using

**BungeeCord plugins**: ??

**Comment by dabou0** [comment]
update to this bish, it happens on server stop

**Comment by Janmm14** [comment]
You are using 3.5.0
Do you have a reason why you did not update to 3.6.x?

**Comment by dabou0** [comment]
all .6 are still on beta, look at the reviews
http://prntscr.com/nm7lud

**Comment by Janmm14** [comment]
the beta only applies to 1.13 support
