### ISSUE TITLE
issue Op player

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1626]
Hi can you add options for control Opped player?
can you fix problem if a player is opped , if he get deop and join again he can bypass control of aac? i need to restart every time server for add again contro with player who was opped

**Comment by Janmm14** [comment]
AAC checks permissions every 30 seconds or every minute to prevent bad permission plugins from slowing the server down too much.

**Comment by CeIebrimbor** [comment]
AAC is not designed to quick-switch between bypass mode instantaneously. The player is either trusted, or they aren't. If you are concerned about a person given OP to be cheating, why do they have OP???
