### ISSUE TITLE
Phase false positive

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#163]
When jumping on fertilized land and it turns into dirt, do not jump again and just try to move: all movement will be blocked and you will be detected for phase.

**Comment by Janmm14** [comment]
Note: On 1.8, fertilized land does not cause the player to be lower than on a normal block.

**Comment by Photon-GitHub** [comment]
The bug is not present on 1.8

**Comment by konsolas** [comment]
Fixed in code.
