### ISSUE TITLE
HighJump caused by false flags

### ISSUE THREAD

**Issue by orasunis** [konsolas/AAC-Issues#1633]
### Issue description
A _highjump_ can be caused by false flags as shown in [this video](https://www.youtube.com/watch?v=pH1YS9-bcoI) (not my video).

### Core information
**Server version**: CraftBukkit (git-Spigot-db6de12-1gfbb24) API version 1.8.8-R0.1-SNAPSHOT

**AAC version**: 4.0.0

**ProtocolLib version**: not visible in the video
**Plugin list**: AAC and ProtocolLib

### Special environment information
**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

### Configuration
seems like the default configuration

**Comment by konsolas** [comment]
This is likely to be fixed by -b1.
