### ISSUE TITLE
Web Issues

### ISSUE THREAD

**Issue by DasCanard** [konsolas/AAC-Issues#1634]
### Issue description

https://streamable.com/4rpyf

### Core information
**Server version**: 1.8 spigot

**AAC version**: 4.0.0-b1

**ProtocolLib version**: 4.4.0

**Plugin list**: https://drive.google.com/uc?id=1bc8QHG39DFmGP8NmdIZ33hKm0Q5xvA5v

### Special environment information
**ViaVersion version**: yes

**ProtocolSupport version**:  /

**ViaBackwards version**:  /

**BungeeCord plugins**: LuckPerms

### Configuration
only removed kicks

**Comment by konsolas** [comment]
Luckily the VLs stay quite low so it doesn't seem too bad for now

**Comment by DasCanard** [comment]
> Luckily the VLs stay quite low so it doesn't seem too bad for now

well we can fix this with the config but maybe try to fix it though

**Comment by konsolas** [comment]
>

**Comment by konsolas** [comment]
4.0.4
