### ISSUE TITLE
[FP] Interact

### ISSUE THREAD

**Issue by wulfwuud** [konsolas/AAC-Issues#1635]
### Issue description

https://youtu.be/WJLtGx-tvmo

### Core information
**Server version**: 
This server is running Paper version git-Paper-c66f02b1 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**AAC version**: 
4.0.0b2
**ProtocolLib version**: 
ProtocolLib version 4.4.0-SNAPSHOT-b403

**Plugin list**: 

### Special environment information
**ViaVersion version**: 
ViaVersion version 2.1.0

**ProtocolSupport version**: 
none

**ViaBackwards version**: 
none

**BungeeCord plugins**: 
none

### Configuration
default

**Comment by konsolas** [comment]
This has happened in previous versions of AAC and can't be helped, and is one of the reasons why interact does not kick by default.
