### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Kyrobi** [konsolas/AAC-Issues#1636]
### Core information
**Server version**: Paper #136

**AAC version**: 4.0.0-b2

**ProtocolLib version**: 

**Plugin list**: (20): AAC, BeSocial*, ChatControl, Essentials, EssentialsChat*, GriefPrevention, InventoryRollback, JoinTime*, LiteBans, LuckPerms*, MineHooks, notify*, PlaceholderAPI*, ProtocolLib, Regionerator, TAB, V4P*, Vault*, WorldEdit, WorldGuard

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

Issue: https://pastebin.com/FNXieUDg

### Configuration

https://pastebin.com/XqueXkuH

**Comment by konsolas** [comment]
4.0.0-b3
