### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1638]
log
https://pastebin.com/aWHUYnEk

server version paperspigto 1.12.2

**Comment by Photon-GitHub** [comment]
What version of AAC and ProtocolLib are you using?

**Comment by leoncp9** [comment]
aac 4.0.0-b3 https://www.spigotmc.org/resources/aac-advanced-anti-cheat-hack-kill-aura-blocker.6442/
protocolib build #425 http://ci.dmulloy2.net/job/ProtocolLib/425/

**Comment by leoncp9** [comment]
the error was with 4.0.0-b2, but today konsolas update his plugin
