### ISSUE TITLE
flux b13

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1639]
flux b13 can bypass killaura check and scaffold check
scaffold mode aac
killaura mode aac, value 
range 1
aps 1
switch delay 1
fov 10
flux b13 can't bypass matrix anticheat killaura, so matrix is better than aac for block killaura mode aac of flux b13

**Comment by Janmm14** [comment]
fov 10 doesn't seem useful tbh

**Comment by leoncp9** [comment]
range 1
aps 1
switch delay 1
fov 10
is OP when aac is good conofigured, if you think is low attack, you need to see this amazing killaura with aps 1 and switch delay 1, it click super fast! look https://www.youtube.com/watch?v=WE9dazWLqEM

**Comment by leoncp9** [comment]
DUDEEEEEEEEE why i need to add matrix anticheat for block killaura of fluxb13 with low value? matrix anticheat is free but block low killaura of fluxb13 :/ can you try make a better kill aura options?? You know Kaur anticheat (PREMIUM)? can you add to aac options better than kauri and matrix anticheat? look kauri config https://pastebin.com/35wSgzpa, you need to add more Type of killaura on your config!

**Comment by Janmm14** [comment]
in the video you linked it looks like your client is attackingthe fake player
in that case, the detection is not based of behaviour

aac is meant to block meaningful cheats

**Comment by leoncp9** [comment]
in the video i show you only aps 1 and
switch delay 1, he is like aps 10 and super fast click

**Comment by leoncp9** [comment]
don't focus where go the attack, but this killaura is super fast with low value :/

**Comment by Janmm14** [comment]
if you want that kind of detection ,why you dont want to use kauri or how your anticheat is called?

the amount of config options have no direct relation on check accuracy etc.

**Comment by leoncp9** [comment]
because i don't have kauri, i can't spent $200 for one plugin at the moment :/

**Comment by leoncp9** [comment]
this is link of kauri
main page
https://www.mc-market.org/threads/454154/
shop page
https://funkemunky.cc/shop

**Comment by leoncp9** [comment]
he cost $300 dollars

**Comment by Janmm14** [comment]
oh i thought you have it because of the vid and the config

**Comment by leoncp9** [comment]
on the video i use aac + aacadditionalpro

**Comment by Janmm14** [comment]
the video shows some guardians in detection, the chat is blurred, and the flying fake entity is not from aac

**Comment by leoncp9** [comment]
entity is by AACAdditionPro

**Comment by coolpvpv** [comment]
> flux b13 can bypass killaura check and scaffold check
> scaffold mode aac
> killaura mode aac, value
> range 1
> aps 1
> switch delay 1
> fov 10
> flux b13 can't bypass matrix anticheat killaura, so matrix is better than aac for block killaura mode aac of flux b13

this is useless cause LEGIT 1 REACH 1 APS 10 FOV LIKE WTF? HOW IS THIS EVEN A ADVANTAGE ITS LEGIT A DISADVANTAGE CAUSE LEGIT NORMAL PVPING IS BETTER THEN THAT

**Comment by leoncp9** [comment]
I CAN  hack with killaura mode aac by flux b13 with low value, on the hive, jartex network and all server who use aac, i always win because flux b13 have a perfect killaura for bypass aac plugin

**Comment by Janmm14** [comment]
The you probably win because of
a) Older AAC versions used
b) Not all checks enabled / set to mitigate
c) Low
