### ISSUE TITLE
Slimeblock and elytra

### ISSUE THREAD

**Issue by splintermik** [konsolas/AAC-Issues#1640]
version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2)
[ProtocolLib] Loading ProtocolLib v4.4.0
[AAC] Loading AAC v4.0.0 ( AAC-4.0.0-b4 )
[ProtocolSupport] Loading ProtocolSupport v4.29-dev
basic config.yml file

Hello, I have a bug with the anti cheat plugin
I made a video, which will show more simply the problem 
the first one is with the slime block ( the damage is not part of the bug)
the second is with elytra and fireworks

the first account has bypass permission, the other one does not

https://youtu.be/95SUOpyMRCw

thanks

**Comment by konsolas** [comment]
4.0.3
