### ISSUE TITLE
ClassCastException 1.14.4 CraftBubbleColumn not Levelled

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#1641]
### Issue description

Issue of nekoli#6699 

https://pastebin.com/7RHktDQc

### Core information
**Server version**: 1.14.4

**AAC version**: 4.0.1

**ProtocolLib version**: not asked

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by Nekoli** [comment]
Plugins: BlockLocker, CoreProtect, Essentials, EssentialsChat, InvRestore2, LibsDisguises, LuckPerms, PremiumVanish, ProtocolLib (4.5.0-SNAPSHOT), React, Vault, and WorldEdit.

**Comment by konsolas** [comment]
Fixed in 4.0.2. Thanks.
