### ISSUE TITLE
Error on /aac

### ISSUE THREAD

**Issue by TheSkiddy** [konsolas/AAC-Issues#1642]
### Issue description

/AAC BungeeCord error: https://p.reflex.rip/luno.bash
Player kicked for skywars server.

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 4.0.2

**ProtocolLib version**: 4.4.0

**Plugin list**: ProtocolLib, AAC, SkyWars.

### Special environment information
**ViaVersion version**: 2.1.3

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: SkinRestorer

**Comment by konsolas** [comment]
How do you know this was caused by AAC?
Do you know which check(s) affect it?

**Comment by TheSkiddy** [comment]
Without AAC everything is fine
And with other anti-cheat all OK.

**Comment by TheSkiddy** [comment]
I don't know what caused it, I just enter /aac and that's it.

**Comment by konsolas** [comment]
So this only happens when you use the /aac command?

**Comment by TheSkiddy** [comment]
Yes.
When you enter /aac verbose, etc., everything is fine

**Comment by konsolas** [comment]
This doesn't seem too major as the average player probably won't be using /aac, but I'll look into it for the next update.

**Comment by konsolas** [comment]
4.0.4
