### ISSUE TITLE
onPacketReceiving exception

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1644]
https://pastebin.com/ftqhTa9s
# Core information
**Server version**: Paper 1.12.2

**AAC version**: 4.0.3

**ProtocolLib version**: 4.4.0

**Comment by konsolas** [comment]
4.0.4

**Comment by BestMark** [comment]
The same crash with AAC 4.0.6: https://pastebin.com/t0axHh3b
Please, reopen the issue.

**Comment by konsolas** [comment]
It isn't the same error. Discussed in discord DM.
