### ISSUE TITLE
Move false positive when player jumps and puts blocks under him

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1646]
When a player jumps and puts blocks under him, anti-cheat detects him.
Video: https://youtu.be/eL9sGMYanQE
Log: https://pastebin.com/8j47nxb9
Client: Minecraft 1.12.2 vanilla without any mods
# Core information
**Server version**: Paper 1.12.2

**AAC version**: 4.0.3

**ProtocolLib version**: 4.4.0

**Comment by konsolas** [comment]
Should be fixed in 4.0.8-b1
