### ISSUE TITLE
Move false positive when player jumps

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1647]
When a player player jumps, anti-cheat detects him.
Video: https://youtu.be/M15v0qvCDzE
Log: https://pastebin.com/dTPj7d16
Client: Minecraft 1.8.9
# Core information
**Server version**: Paper 1.12.2

**AAC version**: 4.0.3

**ProtocolLib version**: 4.4.0

**Comment by konsolas** [comment]
Going to say this is fixed in 4.0.8-b1
