### ISSUE TITLE
Move-velocity false positive

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1648]
When a player player jumps, Move-velocity check randomly detects him.
Video: https://youtu.be/V1DAUjveCro
Log: https://pastebin.com/kjtCvXu4
Client: Minecraft 1.8.9
# Core information
**Server version**: Paper 1.12.2
ViaVersion, ViaRewind latest versions from SpigotMC, ViaBackwards latest build (not dev).

**AAC version**: 4.0.3

**ProtocolLib version**: 4.4.0

**Comment by konsolas** [comment]
This should have been fixed a while ago, along with the whole detection while jumping thing.
