### ISSUE TITLE
NoFall and Phase false positives

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1649]
When a player just walks and jumps, anti-cheat randomly detects him.
Video: https://youtu.be/Cyem1u4qqkg
Log: https://pastebin.com/wY3rLSNX
Client: Minecraft 1.12.2 and/or 1.8.9
# Core information
**Server version**: Paper 1.12.2
ViaVersion, ViaRewind latest versions from SpigotMC, ViaBackwards latest build (not dev).

**AAC version**: 4.0.3

**ProtocolLib version**: 4.4.0

**Comment by Janmm14** [comment]
The nofall false positive should not be harmful.
