### ISSUE TITLE
v3: NoFall false positive [Reopened]

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#165]
When you sprint and then sprint (without letting go) onto stairs and jump on the stairs you get flagged for speed and fly, sometimes even nofall

**Comment by konsolas** [comment]
This has been fixed.

**Comment by Photon-GitHub** [comment]
Beware that this is not actually a big when you have damage disabled!

**Comment by Janmm14** [comment]
https://youtu.be/gZTRKIUEVT4 (still uploading / processing, be patient)

**Comment by konsolas** [comment]
Fixed, confirmed by Rqcco and Janmm14.

**Comment by Janmm14** [comment]
Issue got reproduced by genazt again and konsolas fixed it again.
