### ISSUE TITLE
Several false positives (move and phase) when jumping under roof

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1650]
When a player player jumps, anti-cheat detects him.
Video: https://youtu.be/jCldml7T9Bo
Log: https://pastebin.com/TNG9r87h
Client: Minecraft 1.12.2
# Core information
**Server version**: Paper 1.12.2

**AAC version**: 4.0.3

**ProtocolLib version**: 4.4.0

without any other plugins

**Comment by konsolas** [comment]
duplicate of #1690
