### ISSUE TITLE
1.14 players get stuck into the IRON_FENCE on 1.8.8 server (cross-version compatibility problem)

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1651]
### Issue description
1.14 players get stuck into the IRON_FENCE on 1.8.8 server. When the player jump on the fence, he stucks in it.
AAC log: https://gist.github.com/BestMark/27d77fb04000d78bf4a228a770a1703d
Video from the player: https://youtu.be/cXO6YwHCWw0
I think, you should add the IRON_FENCE block in exclude list (Phase check).
### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 4.0.3

**ProtocolLib version**: 4.4.0

### Special environment information
**ViaVersion version**: latest from SpigotMC

### Configuration
I have default AAC config.

**Comment by CeIebrimbor** [comment]
Add IRON_FENCE to the ignited blocks in the Phase check.

**Comment by BestMark** [comment]
Thanks

**Comment by konsolas** [comment]
IRON_FENCE will be added to the default phase exclusions next update. Thank you.
