### ISSUE TITLE
AAC disabled after failing to remove default SecurityManager

### ISSUE THREAD

**Issue by SlimeDog** [konsolas/AAC-Issues#1655]
### Issue description
On server start-up:
```
[10:42:52] [Server thread/INFO]: [AAC] Enabling AAC v4.0.5
[10:42:52] [Server thread/ERROR]: [AAC] Failed to remove default SecurityManager
[10:42:52] [Server thread/INFO]: [AAC] Disabling AAC v4.0.5
```

### Core information
**Java version**:
```
java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)
```

**Server version**: Spigot 1.14.4 (Jenkins 2423) or Spigot 1.13.2 final

**AAC version**: 4.0.5

**ProtocolLib version**: 4.5.0-b9

**Plugin list**: 

### Special environment information
**ViaVersion version**: [2.1.3, but 1.14.4 client attached to 1.14.4 server]

**ProtocolSupport version**: n/a

**ViaBackwards version**: n/a

**BungeeCord plugins**: n/a

### Configuration
Default except
```
fightspeed:
  enabled: false
...
hitbox:
  max_reach: 14.1
```

**Comment by Janmm14** [comment]
Plugin list might be helpful

**Comment by SlimeDog** [comment]
This is a plugin test server, so lots of them. But it's the same plugins as with previous AAC versions:
http://whitedog.straight8.com/drops/list-plugins

Please advise when you copy it, so I can remove it.

**Comment by Janmm14** [comment]
The problematic plugin here is NetworkInterceptor

**Comment by SlimeDog** [comment]
Thanks. The issue is all the network callouts that AAC makes. But there were no issues through AAC 4.0.4. :(

I will reconfigure NetworkInterceptor.

**Comment by konsolas** [comment]
Sadly people have been inserting sections of NetworkInterceptor's code into AAC in order to crack it. Hence the new measures.

**Comment by SlimeDog** [comment]
Thanks for the (more useful) information. Is there a configuration option to disable the new measures?

**Comment by Janmm14** [comment]
@SlimeDog Having a config option for that would render it useless.

**Comment by SlimeDog** [comment]
Most every AAC check can be enabled/disabled. But I guess this is different.
