### ISSUE TITLE
Remove Thread sleep from onEnable

### ISSUE THREAD

**Issue by Xayanix** [konsolas/AAC-Issues#1658]
![image](https://user-images.githubusercontent.com/12672902/62043498-cd8fac80-b200-11e9-9072-827f524e6874.png)
It takes much longer to server startup.

**Comment by Janmm14** [comment]
Have an internet connection

**Comment by Xayanix** [comment]
Lol nice tip, but im running public server on dedicated server and there are about 1200 players daily on it.

**Comment by Janmm14** [comment]
And you are behaind the great firewall? Or why you can't allow it to connect to api.konsolas.net / cloudflare?
