### ISSUE TITLE
Speed false postive when leaving cobwebs

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#166]
Speed false postive when sprintjumping when leaving cobwebs and being at the edge.

To reproduce you need some time and get out at certain heights I think. Also causes some fly violations (up to vl 5 or 7)

Edit:
Created a video for beter demonstration:
https://youtu.be/BYLFLLrcy2o

**Comment by konsolas** [comment]
Fixed, confirmed by Janmm14
