### ISSUE TITLE
AAC v4 Killaura Falses 

### ISSUE THREAD

**Issue by Reed3411** [konsolas/AAC-Issues#1660]
### Issue description
When fighting players I get false kicked/ false banned/ false flagged. During the video I had verbose enabled. I held the sprint key during the video.

https://youtu.be/QfiSpuTWjHM 

### Core information 

**Server version**: 1.8.8 Spigot

**AAC version**: AAC v4.0.5

**ProtocolLib version**: 4.4.0

**Plugin list**: ProtocolLib and AAC

### Special environment information
**ViaVersion version**: ?? (viaversion was not used)

**ProtocolSupport version**: ?? (protocol support was not used)

**ViaBackwards version**: ?? (viabackwards was not used)

**BungeeCord plugins**: ?? (none)

### Configuration
<!--Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 
The default config was used (all kicks or bans were removed)

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

**Comment by konsolas** [comment]
Seems like AAC is cancelling hits before reaching min_vl, which shouldn't be happening.

**Comment by konsolas** [comment]
Does this still happen if you set killaura.modules.normal to -1?

**Comment by CeIebrimbor** [comment]
@konsolas 
talking on my network, he confirmed this is the fix. Setting normal: -1

**Comment by konsolas** [comment]
This issue definitely doesn't affect every server, so I'm going to need a full plugin list.

**Comment by Reed3411** [comment]
It did fix my issue entirely. I only have 2 plugins on the server so theres nothing that could cause a conflict other than spigot or protocol lib.

**Comment by konsolas** [comment]
Are you any particular client version? Is it vanilla or do you have mods such as the Badlion client, optifine, labymod, etc?

**Comment by Reed3411** [comment]
![awdawdawd](https://user-images.githubusercontent.com/48283890/62247484-ed1b0680-b3b3-11e9-9a21-ba808f845a63.PNG)

**Comment by Reed3411** [comment]
hold on I think I do have a few mods.

**Comment by Reed3411** [comment]
I have optifine, worldedit, and old animations mod. I am on 1.8.9 forge.

**Comment by BestMark** [comment]
I have same problems with PvP on 1.8.x clients.
I use ProtocolSupport on 1.12.2. 1.12.2 is OK, but a lot of 1.8.9 legit players write me, that they have problems with PVP.
Tomorrow I will test it myself.

**Comment by Reed3411** [comment]
Cool

**Comment by konsolas** [comment]
The issue with killaura.normal has been fixed in 4.0.6

You can re-enable it now if you want.
