### ISSUE TITLE
1.14 Move false positives consolidated.

### ISSUE THREAD

**Issue by Lysandr0** [konsolas/AAC-Issues#1661]
### Issue description

1. Jumping in a 1x1 area
 https://gyazo.com/b41238d43decdada42d516f77e27774a

2. Trying to jump out of water against a 2-blocks high wall 
 https://gyazo.com/68c6c4f66f3cd27a6ef1fca1bc7b781c

3. “jump-sneaking”
 https://gyazo.com/89ce1177fa643e16351195626c105e74
 
4.  Getting hit/pushed by mobs
 https://gyazo.com/1fe1f5ae8ca7449afcbdcc185c7c7765
 
5. Jumping through berry bushes (Walking is fine)
 https://gyazo.com/c0b6dcd1d85b1199b0726c85468e0e29
 
6. Jumping and then landing at bedrock level (?)
 https://www.dropbox.com/s/v5ussxo1yggblzg/movefp.mov?dl=0
-------
7. Quickly switching through usable/consumable items with the right mouse button pressed
https://www.dropbox.com/s/c35lraam2aiypry/quickswitchmovefp.mov?dl=0

8. Trying to riptide in air with a trident (Not in water, which has been fixed)
https://www.dropbox.com/s/ndld78s952i4cq7/riptidefp.mov?dl=0

9. Jumping against a block
https://www.dropbox.com/s/x9w9rnidzkhko54/jumpwallmovefp.mov?dl=0

### Core information
**Server version**: Spigot 1.14.3

**AAC version**: AAC 4.0.5

**ProtocolLib version**: v4.5.0-SNAPSHOT

### Special environment information
**ViaVersion version**: /

**ProtocolSupport version**: /

**ViaBackwards version**: /

**BungeeCord plugins**: /

### Configuration
Default config values

**Comment by Lysandr0** [comment]
Swiftly threw in a few more FPs I've found. (7/8/9 Tested on AAC 4.0.10)

**Comment by Janmm14** [comment]
Issue 7 is something where the minecraft client is behaving very weird and one would have to wait for the next move to be able to correctly determine what the client did previously, because the client is sending some packets in a shitty order for good checking.

**Comment by konsolas** [comment]
It's turning out to be quite difficult to manage issues which contain large numbers of "sub-issues".

The 4.0.11 update should fix a number of the problems listed. For any that remain, please open *separate issues for each of them*. I understand that this may be annoying, but it should only take a few moments because you already have all of the information - only copy+paste is necessary.

Thanks.

**Comment by Lysandr0** [comment]
I've split everything into different tickets.
Just a quick note regarding issue n.7 and n.2:  Move still throws out some FPs occasionally, (especially for n.7) but they seem to have gotten way better than before.
