### ISSUE TITLE
Crossbow incompatibility with FastBow

### ISSUE THREAD

**Issue by Lysandr0** [konsolas/AAC-Issues#1662]
### Issue description
Nothing much else to say, just use a crossbow with AAC 4 and check it yourself. :p

### Core information
**Server version**: Spigot 1.14.3

**AAC version**: AAC v4.0.5

**ProtocolLib version**: 4.5.0-SNAPSHOT

### Special environment information
**ViaVersion version**: /

**ProtocolSupport version**: /

**ViaBackwards version**: /

**BungeeCord plugins**: /

### Configuration
Default config

**Comment by konsolas** [comment]
4.0.6
