### ISSUE TITLE
AAC server crash. (LP Verbose)

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1665]
Using LuckPerms (https://github.com/lucko/LuckPerms) verbose spams the entire chat. (Permission checks are constant). Further more it lags the server to the point of a crash. (This has been an issue in the past).

_/lp verbose on valese_
Regular Player Verbose: https://i.imgur.com/XAeHtNF.png
_/lp verbose on andrewkm_
Admin Verbose: https://i.imgur.com/QXIM745.png

Would be lovely if you can fix this, along side LuckPerms, as verbose is very important for debugging permission issues on production servers, and AAC confliction makes this system useless.

PS: Perhaps @lucko can shed some light as well.

### Core information
**Server version**: 1.12.2 & 1.13.2

**AAC version**: 4.0.5
**AAC config**: 4.0.5|1-Default-Celebrimbor

**ProtocolLib version**: 4.4.0 Build 425

**Plugin list**:
LuckPerms 4.4.2.7
(Remaining on request via Discord - andrewkm-0001)

### Special environment information

**ViaVersion version**: 2.1.4 Build 361

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
AAC used to cache permissions to prevent this sort of thing from happening, but lots of people requested that it be removed.

Perhaps LuckPerms could add an option to exclude certain permissions from verbose?

**Comment by andrewkm** [comment]
Looking at their Github wiki, it seems a filtering option exists.
_/lp verbose on andrewkm & !aac_

I guess we can close the ticket then, would be nice if something could possibly be done though to prevent unsuspecting AAC admins crashing services with verbose.

**Comment by konsolas** [comment]
I don't think luckperms allows plugins to exclude themselves from verbose, so it looks like this workaround will be best for the foreseeable future.
