### ISSUE TITLE
Could not pass event PlayerMoveEvent to AAC v4.0.6

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1666]
Getting this since update to 4.0.6
1.12.2 server: https://pastebin.com/raw/TD8CbK0j
1.13.2 server: https://pastebin.com/raw/HTZGem3E

### Core information
**Server version**: 1.12.2 & 1.13.2

**AAC version**: 4.0.6
**AAC config**: 4.0.5|1-Default-Celebrimbor
**AAC enabled checks**:

- Move
- Timer
- BadPackets
- FastBreak
- FastPlace
- Interact

**ProtocolLib version**: 4.4.0 Build 403

**Plugin list**:
LuckPerms 4.4.2.7
(Remaining on request via Discord - andrewkm-0001)

### Special environment information

**ViaVersion version**: 2.1.4 Build 361

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by andrewkm** [comment]
From different server (related I believe):
https://pastebin.com/raw/HTZGem3E

**Comment by CeIebrimbor** [comment]
@andrewkm 
In your move check, did you make the change to recognize 1.12 movement?

Default
  simulate_versions:
    - "1.8"

You need remove 1.8 and put in 1.12, assuming it's just a 1.12 server.

**Comment by andrewkm** [comment]
@CeIebrimbor the issue above is actually happening on both 1.12.2 and 1.13.2 servers.
Let me update original ticket to reflect that.

**Comment by CeIebrimbor** [comment]
Please confirm the error still pops up after you remove 1.8 and add 1.13 to your `simulate_versions`.

**Comment by andrewkm** [comment]
It does indeed.

1.12.2 servers changed to:
```
  simulate_versions:
    - "1.12"
    - "1.13"
```

1.13.2 servers changed to:
```
  simulate_versions:
    - "1.12"
    - "1.13"
```

_/aac reload_
Errors persist.

**Comment by konsolas** [comment]
4.0.7
