### ISSUE TITLE
AAC can't use in Spigot 1.8

### ISSUE THREAD

**Issue by PolarTraveler** [konsolas/AAC-Issues#1667]
### Issue description

I installed this plugin and it did't load successfully in my server.
Here are some information:
When I use AAC 3.6.4:
`[17:24:19] [Server thread/INFO]: [AAC] Enabling AAC v3.6.4`
`[17:24:20] [Server thread/ERROR]: [AAC] FATAL: FAILED TO AUTOCONFIGURE SERVER VERSION`
`[17:24:20] [Server thread/INFO]: [AAC] Disabling AAC v3.6.4`
When I use AAC 3.0.0:
`[17:18:28] [Server thread/INFO]: [AAC] Enabling AAC v3.0.0`
`[17:18:30] [Thread-11/ERROR]: [AAC] FATAL: FAILED TO AUTOCONFIGURE SERVER VERSION`
`[17:18:30] [Thread-11/ERROR]: [AAC] Translation: You modded your server so hard we can't even find its version number.`
`[17:18:30] [Thread-11/INFO]: [AAC] Disabling AAC v3.0.0`
When I use AAC 1.9.9:
It loaded successfully,but when a player moves,the console kept reporting:
`[17:20:01] [Thread-21/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R1.EntityHuman.bS()`
`[17:20:01] [Thread-21/WARN]: 	at java.lang.Class.getDeclaredMethod(Unknown Source)`
`[17:20:01] [Thread-21/WARN]: 	at java.lang.invoke.MethodHandleImpl$BindCaller$T/12397571.invoke_V(Unknown Source)`
`[17:20:01] [Thread-21/WARN]: 	at me.konsolas.aac.i.b.j.a(Unknown Source)`
`[17:20:01] [Thread-21/WARN]: 	at me.konsolas.aac.b.c.P.run(P.java)`

### Core information
**Server version**: Spigot 1.8

**AAC version**: 1.9.9 3.0.0 3.6.4(I tried many versions)

**ProtocolLib version**: 4.2.1

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

### Configuration
Default

**Comment by konsolas** [comment]
You need to have 1.8.8
1.8 and 1.8.3 aren't supported.
