### ISSUE TITLE
"Added violations to a player without data" exception (4.0.6)

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1672]
1. https://pastebin.com/QiQgtHjz
2. https://pastebin.com/BCmi9e2i (the same, but in AAC-MoveCheck) 
# Core information
**Server version**: Paper 1.12.2

**AAC version**: 4.0.6

**ProtocolLib version**: 4.4.0

**Comment by konsolas** [comment]
4.0.9
