### ISSUE TITLE
Velocity check for non-moving players

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1674]
We checked 3 cheat-clients and concluded that Velocity (AntiKnockback) check doesn't work.
Video: https://youtu.be/WgrcnPNnB2M (Flux b6 cheat-client)
AntiKnockback gives a big advantage on the BedWars mini-game.
# Core information
**Server version**: Paper 1.12.2

**AAC version**: 4.0.6

**ProtocolLib version**: 4.4.0

**Comment by konsolas** [comment]
The velocity check will only work if the target player moves in some way, e.g. if they turn around.
