### ISSUE TITLE
Unable to move out of water.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1675]
This was happening on 4.0.6 (Unsure if fixed in 4.0.7)
Original report: https://ecocitycraft.com/forum/threads/unable-to-move-out-of-water.187173/
Report includes video.

> Brief Description: Am unable to move out of the water after getting stuck 1 block or more deep
> Instructions: Go into a small pool of water (one block) and try to escape. Most of the time, it wont let you.

Everything in logs pertaining to "move" for the player in question on the day of.
https://gist.githubusercontent.com/andrewkm/2f128170acd8a5a7fd1f3b55f98f63c7/raw/8ce77cd25aacf4628a1a145fdb9c53598506b3f2/gistfile1.txt

### Core information
**Server version**: 1.13.2

**AAC version**: 4.0.6
**AAC config**: 4.0.5|1-Default-Celebrimbor
**AAC enabled checks**:

- Move (Kick thresholds disabled)
- Timer
- BadPackets
- FastBreak
- FastPlace
- Interact

**ProtocolLib version**: 4.4.0 Build 425

**Plugin list**:
(On request via Discord - andrewkm-0001)

### Special environment information

**ViaVersion version**: 2.1.4 Build 361

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
Looks like the new feature of waterlogged slabs is causing some issues.

**Comment by konsolas** [comment]
4.0.8
