### ISSUE TITLE
Move/Nofall/Velocity False Positive

### ISSUE THREAD

**Issue by ZugPilot** [konsolas/AAC-Issues#1679]
### Issue description

https://youtu.be/cMbago6MF9Y

### Core information
**Server version**: 

1.8.8 Paper Spigot

**AAC version**: 

4.0.6

**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

I don't have that

**ProtocolSupport version**: ??

I don't have that

**ViaBackwards version**: ??

I don't have that

**BungeeCord plugins**: ??

I don't have that

**Comment by konsolas** [comment]
4.1.4
