### ISSUE TITLE
v3 Speed // Fly Setback Jumping on Wateredge with Jumpboost.

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#168]
Title says it all, video ---> https://www.youtube.com/watch?v=MTV7wYGCkdo

**Comment by Janmm14** [comment]
I believe its more caused by the water, but I have to sleep now, ao maybe test it.

**Comment by Rqcco** [comment]
^ What he said.

**Comment by Janmm14** [comment]
Maybe edit the title to:
Speed setback jumping at wateredge
or sth. similar

**Comment by konsolas** [comment]
Fixed, tested by Rqcco.
