### ISSUE TITLE
Boat/Minecart False Positive

### ISSUE THREAD

**Issue by ZugPilot** [konsolas/AAC-Issues#1680]
### Issue description

https://youtu.be/gF98nBc_jjM

### Core information
**Server version**: 

1.8.8 Paper Spigot

**AAC version**: 

4.0.6

**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

I don't have that

**ProtocolSupport version**: ??

I don't have that

**ViaBackwards version**: ??

I don't have that

**BungeeCord plugins**: ??

I don't have that

**Comment by konsolas** [comment]
4.0.11

**Comment by konsolas** [comment]
4.1.4
