### ISSUE TITLE
Unsupported protocol version: -1

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1684]
https://pastebin.com/S0SNrdcV
# Core information
**Server version**: Paper 1.12.2

**AAC version**: 4.0.7-b1

**ProtocolLib version**: 4.4.0

**Comment by konsolas** [comment]
Is ViaVersion and/or ProtocolSupport present?

**Comment by BestMark** [comment]
ProtocolSupport

**Comment by konsolas** [comment]
4.0.8
