### ISSUE TITLE
NPE on BlurredBlockBreakEvent

### ISSUE THREAD

**Issue by niqoar** [konsolas/AAC-Issues#1685]
**Issue description**: 
NPE on BlurredBlockBreakEvent when somebody use wild teleport.
 
Log: https://pastebin.com/8MgYJRcU
Plugin: https://www.spigotmc.org/resources/wilderness-tp.22853/

**Server version**: 
Paper version git-Paper-"1832d799" (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**AAC version**: 
4.0.7-b1

**ProtocolLib version**: 
4.5.0-SNAPSHOT

**Comment by konsolas** [comment]
Unsurprisingly a blurredblockbreakevent isn't a blockbreakevent

**Comment by konsolas** [comment]
Should be fixed in 4.0.8.
