### ISSUE TITLE
Block Break/Place false positive

### ISSUE THREAD

**Issue by Xayanix** [konsolas/AAC-Issues#1686]
https://www.youtube.com/watch?v=l9hP-ur-Bf4&feature=youtu.be

[02-08-2019 23:44:15.977] Jonatan failed fastplace: placed 27 blocks in 1 second [ping:54 tps:20.0] VL:3
[02-08-2019 23:44:16.093] Jonatan failed fastplace: placed 28 blocks in 1 second [ping:54 tps:20.0] VL:6

**Comment by Janmm14** [comment]
Fastplace check does not detect the cheat specifically.
It is there to limit block places per second to some possibly legitimate level of a good player.
Therefore a false positive of this cheat cannot exist. If you want to allow your players to place blocks faster, use a higher limit in the configuration.

**Comment by Xayanix** [comment]
It looks like counter for placed and broken blocks doesnt reset, and thats an issue.
