### ISSUE TITLE
A lot of KillAura and HitBox false positives (most parts)

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1688]
Video: https://youtu.be/-qC8203YEQY
Log: https://pastebin.com/NUqA8QLh
# Core information
**Server version**: Paper 1.12.2

**AAC version**: 4.0.8-b1

**ProtocolLib version**: 4.4.0

**Comment by konsolas** [comment]
Not a false positive. Verbose is just debugging information, not a detection.
