### ISSUE TITLE
Move kicks players when they join the server (1000+ VL in one second!)

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1689]
Client: OptiFine 1.12.2 without any mods.
Video: https://youtu.be/mlqumQEZ0vI
Verbose: https://pastebin.com/DBVmMRb9

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 4.0.8-b1

**ProtocolLib version**: 4.4.0

### Special environment information
**ViaVersion version**: 2.1.3

P.S. Another Move kicks on the same server:
https://pastebin.com/PRYJgSRS (1.12.2 client without mods)
https://pastebin.com/caxEdpCX (1.12.2 client without mods)

1.12.2 server + ProtocolSupport:
https://pastebin.com/g0Ub1wTV (1.12.2 client without mods)

**Comment by konsolas** [comment]
Due to the new max_vl_increment option this should no longer be possible. I'm not sure what can be done beyond that.
