### ISSUE TITLE
Speed setback: Falling into water while holding spacebar from great heights

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#169]
https://www.youtube.com/watch?v=Ba3rjpqiKeM

**Comment by konsolas** [comment]
Fixed, confirmed by Rqcco.

**Comment by Photon-GitHub** [comment]
Falling into deep water out of great heights will result in the same problem.

**Comment by Photon-GitHub** [comment]
Fixed, confirmed by me.
