### ISSUE TITLE
Move kicks players when they're climbing the ladder

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1691]
Client: OptiFine 1.12.2 without any mods.
Video: https://youtu.be/7gcyU8N478M
Verbose: https://pastebin.com/Qjb3WdQX

### Core information
**Server version**: Paper 1.12.2

**AAC version**: 4.0.8-b1

**ProtocolLib version**: 4.4.0

### Special environment information
**ProtocolSupport version**: latest build for 1.12.2

P.S. Please, add option to disable ladder checking. There are a lot of false positive kicks for it on my server.

**Comment by BestMark** [comment]
When players go down the stairs, AAC kicks them too.
Video: https://youtu.be/9jdvUlV_pPs

**Comment by konsolas** [comment]
4.0.9
