### ISSUE TITLE
PlayerMoveEvent Console Error

### ISSUE THREAD

**Issue by Xm4g1kZzXj0k3** [konsolas/AAC-Issues#1692]
Hi,
i want report a possible console error.

https://pastebin.com/TMnmPgFy

Server version:
This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

AAC version:
4.0.8-b1

ProtocolLib version:
4.4.0

ViaVersion version:
2.1.3

**Comment by konsolas** [comment]
4.0.9
