### ISSUE TITLE
KillAura false positive in no-combat-zone

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1693]
Client: OptiFine 1.12.2 without any mods.
Video: https://youtu.be/kMA3lBG5CqQ
Verbose: https://pastebin.com/rYtWaKs7

### Core information
**Server version**: Paper 1.12.2

**AAC version**: 4.0.8-b1

**ProtocolLib version**: 4.4.0

### Special environment information
**ProtocolSupport version**: latest build for 1.12.2

**Comment by konsolas** [comment]
4.1.0 (new killaura check)
