### ISSUE TITLE
Move false positive when climbing the Lily Pad

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1694]
Video: https://youtu.be/W3akz--CHwM
Minecraft 1.8.9 client
### Core information
**Server version**: Paper 1.12.2

**AAC version**: 4.0.9

**ProtocolLib version**: 4.4.0

### Special environment information
**ProtocolSupport version**: latest build for 1.12.2

**Comment by BestMark** [comment]
The same issue with ViaVersion + ViaRewind + ViaRewind Legacy Support

**Comment by konsolas** [comment]
Can you confirm that this only happens if the client is 1.8.x?

**Comment by BestMark** [comment]
Yes, it happens if player uses 1.8.x client. Player with 1.12.2 doesn't get stuck in a ladder.
ProtocolSupport has a bounding box fix for ladders, same as in [ViaRewind Legacy Support](https://github.com/Gerrygames/ViaRewind-Legacy-Support/commit/ba4d64cb56c0e5619d5457106b12cd62d461adf7).

**Comment by DDuart** [comment]
Hi, I have this problem too.

**Comment by BestMark** [comment]
Fixed in AAC 4.0.10

**Comment by konsolas** [comment]
Thanks for confirming.
