### ISSUE TITLE
/aac verbose: player argument

### ISSUE THREAD

**Issue by LogGits** [konsolas/AAC-Issues#1695]
/aac verbose is hard to manage because there are alot of random user violations. When I am trying to test something with a player and check their output im getting additional verbose output from other players making it abit difficult to test stuff.Can you add a player argument to /aac verbose so i can check a specific players verbose output.
Proposed usage: `/aac verbose [playername]` 
*this would toggle my verbose but only output verbose info from [playername]*

**Comment by BestMark** [comment]
That would be very useful.

**Comment by konsolas** [comment]
Verbose streams in 4.2.0
