### ISSUE TITLE
Riding pig move fp

### ISSUE THREAD

**Issue by LogGits** [konsolas/AAC-Issues#1696]
### Issue description
Seem to have issues with players riding pigs with carrots on stick. It is triggering move fp's.

To reproduce this:
1) Get a pig.
2) Put a saddle on the pig.
3) Ride pig
4) Put carrot on stick in your main hand
5) After a few tests, you will be kicked for move fp's

**I will post some pics of verbose output soon**

### Core information
**Server version**: 1.13.2
**AAC version**: 4.0.10
**ProtocolLib version**: 4.4.0

### Special environment information
**ViaVersion version**: ??
2.1.3

### Configuration
Cele's config

**Comment by konsolas** [comment]
4.0.11
