### ISSUE TITLE
AAC not loading during startup

### ISSUE THREAD

**Issue by Darkhooper** [konsolas/AAC-Issues#1698]
### Issue description
AAC won't load when I am running my Minecraft server. Here's what I get : https://pastebin.com/KjDEJVug

### Core information
**Server version**: 1.14.4

**AAC version**: 4.0.10

**ProtocolLib version**: 4.5.0-b16

**Plugin list**: Vault 1.7.2, PlugMan 2.1.6, EssentialsX 2.17.1.11, AuctionHouse 1.7.17

**Comment by Janmm14** [comment]
Please try updating your java installation to 64bit java

**Comment by yyunusyigit** [comment]
I think this is an obfuscator error.

**Comment by Janmm14** [comment]
No, its not.
