### ISSUE TITLE
False Positives on Move and cancelled hits 

### ISSUE THREAD

**Issue by CentralVortex** [konsolas/AAC-Issues#1700]
##
False Positives with movement (players get stuck in blocks) and random cancelled hits with killaura.
**video**: https://www.youtube.com/watch?v=toUEfggKCms&feature=youtu.be
**logs**: https://gist.github.com/CentralVortex/58a402f5ba47b04036849f8e8d9e4e08

### Core information
**Server version**: 1.8.8
**AAC version**: 4.0.10
**ProtocolLib version**: 4.4.0 
**config**: Using Celebrimbor's config.

**Comment by konsolas** [comment]
Are you sure those are the correct logs? They don't show any cancelled hits like the video does.

**Comment by konsolas** [comment]
Merging with #1719
