### ISSUE TITLE
Archiving old logs

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1701]
Due to the huge number of log entries this would be very relevant. If possible, archive old logs in the same way as in the Spigot (log.gz). I also recommend the autoremove for old logs.
I don't want to use AACAdditionPro for this since it functions horribly (a lot of false positives and crashes).

**Comment by konsolas** [comment]
This was discussed on discord and will be added at some point

**Comment by CeIebrimbor** [comment]
You could always use AACadditionPro and disable everything but the LogBot. Just food for thought.

**Comment by konsolas** [comment]
Compression added in 4.1.5. Automatic log removal will not be added to AAC.
