### ISSUE TITLE
FightSpeed doesn't take ping or tps into account

### ISSUE THREAD

**Issue by thehollowedone** [konsolas/AAC-Issues#1704]
### Issue description
FightSpeed will flag players heavily & punish them if the server lags or if they have high ping and send more packets than normal.

### Core information
**Server version**: 1.14. (PaperSpigot 162)

**AAC version**: 4.0.11-b1

**ProtocolLib version**:  4.5.0

### Special environment information
**ViaVersion version**: X

**ProtocolSupport version**: X

**ViaBackwards version**: X

**BungeeCord plugins**: X

### Configuration
I use Celebrimbor's Optimized Config.

**Comment by BestMark** [comment]
Same problem. A lot of players were kicked when server hang for 3-5 seconds.
Logs: https://pastebin.com/0hXiNfFv

**Comment by konsolas** [comment]
4.1.0
