### ISSUE TITLE
 Could not load 'plugins\AAC-4.0.11-b1.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1705]
log
https://pastebin.com/JTxSF1f3
server version
paper 1.12.2
and
paper 1.13.2
i can't load aac 4.0.11-b1

**Comment by leoncp9** [comment]
I realized that I can no longer upload any version of your plugin, why? Waht is the problem? :/

**Comment by Janmm14** [comment]
please download 64bit java

**Comment by leoncp9** [comment]
ok thank
