### ISSUE TITLE
1.14  jumping in a 1x1 block area

### ISSUE THREAD

**Issue by Lysandr0** [konsolas/AAC-Issues#1706]
### Issue description
Crawling in a 1x1 area can be quite buggy with AAC, especially if you try to jump
https://gyazo.com/b41238d43decdada42d516f77e27774a (From #1661)
### Core information
**Server version**: Spigot 1.14.4
**AAC version**: AAC v4.0.11-b1
**ProtocolLib version**: v4.5.0-SNAPSHOT
### Special environment information
**ViaVersion version**: n/a
**ProtocolSupport version**: n/a
**ViaBackwards version**: n/a
**BungeeCord plugins**: n/a
### Config
Default config

**Comment by konsolas** [comment]
Going to merge this with #1703
