### ISSUE TITLE
1.14 Berry bush incompatibility with Move

### ISSUE THREAD

**Issue by Lysandr0** [konsolas/AAC-Issues#1708]
### Issue description
Trying to get through berry bushes while jumping can cause the Move check to rack up violations fairly quickly.
(Walking is fine tho) (From #1661)
### Core information
**Server version**: Spigot 1.14.4
**AAC version**: AAC v4.0.11-b1
**ProtocolLib version**: v4.5.0-SNAPSHOT
### Special environment information
**ViaVersion version**: n/a
**ProtocolSupport version**: n/a
**ViaBackwards version**: n/a
**BungeeCord plugins**: n/a
### Config
Default config

**Comment by konsolas** [comment]
4.1.4
