### ISSUE TITLE
test-server better chat message layout

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#171]
Current chat message layout has no difference between name and message for sr. testers and konsolas.
I suggest using this suffix:`§8» &f`

**Comment by Rqcco** [comment]
I totally agree

**Comment by Photon-GitHub** [comment]
Or §7 : §f like I use on my server

**Comment by konsolas** [comment]
going to close this because I can't be asked

**Comment by Janmm14** [comment]
well i asked you around creation time, but nvm this just very unimportant
