### ISSUE TITLE
Move FP when moving around at bedrock level.

### ISSUE THREAD

**Issue by Lysandr0** [konsolas/AAC-Issues#1712]
### Issue description
As the title says, you should watch the video to get a better idea.  It’s a bit hard to reproduce.
https://www.dropbox.com/s/v5ussxo1yggblzg/movefp.mov?dl=0

https://www.dropbox.com/s/ljt2j5mqw6veayj/img_9555.mp4?dl=0 (re-tested on AAC 4.0.11-b1)
### Core information
Server version: Spigot 1.14.4
AAC version: AAC v4.0.11-b1
ProtocolLib version: v4.5.0-SNAPSHOT
### Special environment information
ViaVersion version: n/a
ProtocolSupport version: n/a
ViaBackwards version: n/a
BungeeCord plugins: n/a
### Config
Default config

**Comment by voodootje0** [comment]
Any updates on this?
