### ISSUE TITLE
conflict with another plugin (proxySelector == null)

### ISSUE THREAD

**Issue by NeNex-GitHub** [konsolas/AAC-Issues#1713]
### Issue description

AAC 4.0.10 and above make an error with another plugin (Vixio) and makes it unusable 
https://pastebin.com/p8xKczYv
There is no error with versions less than 4.0.10
There is no error when there is no aac

Should I contact the developer of the other plugin?

### Core information
**Server version**: 1.8.9

**AAC version**: 4.0.10 and above

**ProtocolLib version**: 4.4.0

### Special environment information
**ViaVersion version**: 2.1.2

**ProtocolSupport version**: X

**ViaBackwards version**: X

**BungeeCord plugins**: X

### Configuration

Default config

**Comment by Janmm14** [comment]
okhttp3 seems to not handle correctly that proxyselector can in fact be null and is allowed according to the javadocs: https://docs.oracle.com/javase/8/docs/api/java/net/ProxySelector.html#setDefault-java.net.ProxySelector-

Forward this information to the skript developers, they either have to update their okhttp3 library, change their usage or forward the problem to okhttp3.

**Comment by xkuyax** [comment]
@Janmm14 why is AAC editing the ProxySelector system wide? I don't see any reason for an anti cheat to edit an java.net class regarding ProxySelectors?

**Comment by Janmm14** [comment]
It does not "edit" a java.net class. It is just using it.

**Comment by xkuyax** [comment]
@Janmm14 i mean "edit" in the sense of setting the object to null... 
Why is aac even setting the ProxySelector to null?

**Comment by Janmm14** [comment]
Won't answer that.
