### ISSUE TITLE
BufferBlob::jni_fast_GetIntField fatal error

### ISSUE THREAD

**Issue by AmazedMender16** [konsolas/AAC-Issues#1714]
### Issue description
Fatal error Java Runtime Environment

```
# Problematic frame:
# v  ~BufferBlob::jni_fast_GetIntField
```

https://pastebin.com/sHCpSefZ

### Core information
**Server version**: 
Paper/Spigot 1.14.4

**AAC version**: 
4.0.11-b1

**ProtocolLib version**: 
4.5.0-SNAPSHOT

### Configuration
Celebrimbor Ghost Config with only KA enabled.

**Comment by Janmm14** [comment]
Will likely be fixed in the upcoming aac version

**Comment by BestMark** [comment]
Use -XX:-UseFastJNIAccessors flag in your startup script. It helped me.

**Comment by konsolas** [comment]
This will be fixed (completely) in the next update.

**Comment by konsolas** [comment]
4.1.0
