### ISSUE TITLE
this is not issue: Can you add entity killaura?

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1716]
i can't find section for question , so i write this
can you add entity like hypixel.
Entity appear when player hack on combact, is possible? actually aacap have entity killaura but he have big bug, player disappear and don't support 1.13.2, is possible add to aac?

**Comment by Janmm14** [comment]
konsolas will not add this because it is too easy to bypass.

**Comment by leoncp9** [comment]
Why hypixel or cubecraft use it?  i mean entity not for control, just for fun, is not possible found a good plugin with entity, but i mean not real control by entity, only aesthetic and choreographic

**Comment by leoncp9** [comment]
i don't need entity 100% working, but just a fake entity? the problem is, is hard to make this is not good idea? i think if is possible, you can add a fake entity only for fun, not for real control, the control is by aac like, killaura, fightspeed, hitbox and criticals

**Comment by Janmm14** [comment]
why give cheaters additional hints that they are being detected?
apart for many, many possible detection vectors where some of them are quite hard to avoid, one thing why aac will not add this is because of the hassle by changed packets over all the versions

**Comment by leoncp9** [comment]
ok
R.I.P
