### ISSUE TITLE
Cancelled hits and false kicks for killaura and flagging movement.

### ISSUE THREAD

**Issue by CentralVortex** [konsolas/AAC-Issues#1719]
Cancelled hits and false kicks for killaura and flagging movement
video: https://www.youtube.com/watch?v=C9E0pa9K2eQ
logs: https://gist.github.com/CentralVortex/df390fd500c0e3e9b0c2731b75649a94
Core information
Server version: 1.8.8
AAC version: 4.1.1
ProtocolLib version: 4.4.0
config: Using Celebrimbor's config

**Comment by CentralVortex** [comment]
Killaura seems to be fixed for now. Move check is still causing some trouble based on this video.

**Comment by Janmm14** [comment]
Any idea why AAC thinks DirtyKoala69 is using timer cheats?

**Comment by CentralVortex** [comment]
Probably a hacker. These logs are based on me and Weeso.

**Comment by Janmm14** [comment]
Oh thats just your whle log file

**Comment by CentralVortex** [comment]
Yeah sorry for that lol.

**Comment by Janmm14** [comment]
For the stuff with the flag when jumping next to a block, it'd be nice if you can try this again and then only submit that portion of the log.

**Comment by CentralVortex** [comment]
Iv'e always used cel's config. I'll try maybe recording another video.

**Comment by Hyronymos1337** [comment]
https://www.youtube.com/watch?v=SEJ0WpnqMs8&feature=youtu.be

**Comment by CentralVortex** [comment]
Cancelled hits still exist as well..
