### ISSUE TITLE
Killaura C3 False Positive - 4.1.3

### ISSUE THREAD

**Issue by funkemunky** [konsolas/AAC-Issues#1723]
### Issue description

**Check**
 Killaura C3

**AAC Logs**
 https://pastebin.com/izzn6kBs

**Hardware/Software Used**
Mouse: Razer DeathAdder Elite, bought in December, 2018. Not used often.
Keyboard: Razer Blackwidow Ten-keyless 2016, bought in June, 2019.
Minecraft Version: 1.8.8, Depression client 1.47 (https://depressionclient.ml). This can be recreated any 1.8.8 version though.

**How to recreate**
Video: https://www.youtube.com/watch?v=ygIgGzOHwko

Step by step:
- Summon a Zombie in a 30x40 flat arena.
- Click at around 8-10 CPS with two fingers, known as "butterfly clicking". The result can be achieved, however, using any clicking style. I just found it easier to keep my hand steady to click this way. Most people click like this when fighting, especially in 1.8, since nothing above 10 CPS produces an noticeable advantage.
- Fight the mob in a swooping strafe motion. I use this tactic all the time when fighting in actual pvp fights, and it is not abnormal.
- While it takes longer to false flag, it can still happen. Just be patient. I have made a video so you can see visually how to false flag it a lot easier if you are having trouble. 

### Core information
**Server version**: CraftBukkit version git-Spigot-e4d471e-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R€.I-SNAPSHOT) 

**AAC version**: 4.1.3

**ProtocolLib version**: 4.4.0

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
This is the fully default configuration. When updating from 4.1.1, I made sure to delete the whole AAC folder before starting my server to make sure there was no chance of error when generating or interference.

**Comment by konsolas** [comment]
4.1.4-b1
