### ISSUE TITLE
The usage of reflection

### ISSUE THREAD

**Issue by voodootje0** [konsolas/AAC-Issues#1724]
### Issue description
As you can see in this profiling (https://sparkprofiler.github.io/#D5jeWBvCcu), several methods in AAC are using reflection, however on the several places it seems like the reflection isn't cached. 

![image](https://user-images.githubusercontent.com/6852308/63216762-d823ce80-c13a-11e9-8914-8a8c4e5b4989.png)
![image](https://user-images.githubusercontent.com/6852308/63216786-10c3a800-c13b-11e9-8e87-cd57acf2e670.png)

optimizing this would be really appreciated, as AAC is already pretty CPU consuming. 

If you need anything, just let me know.

### Core information
**Server version**: 1.8.8 PaperSpigot (custom build, should not really matter)

**AAC version**:  4.1.2

**ProtocolLib version**: 4.4.0

### Special environment information
**ViaVersion version**: 2.1.3

**BungeeCord plugins**: https://i.imgur.com/87FX9Id.png

### Configuration
Using Celebrimbor's optimized config, but should not matter for this issue.

**Comment by voodootje0** [comment]
I have run a new profiling for 12 minutes (https://sparkprofiler.github.io/#Cvnw72Gvgz)

![image](https://user-images.githubusercontent.com/6852308/63218182-e03d3780-c155-11e9-9277-c898523d552d.png)

For the interval check, only the reflection usage CPU usage is 83% 

> 3.70% = interval check
> 3.07% = (2.37+0.70) reflection usage
> (100 / 3.70  * 3.07)

**Comment by Janmm14** [comment]
Class.getSimpleName cannot be cached

**Comment by konsolas** [comment]
This is the start of the method in question:

![image](https://user-images.githubusercontent.com/9408210/63224230-1a8bf080-c1b9-11e9-9074-3e6e1dad4541.png)

I'm essentially attempting to ignore anything that might not be an actual player. Do you have any suggestions for how to optimise this?

**Comment by konsolas** [comment]
4.1.4
