### ISSUE TITLE
Couple Suggestions

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#1725]
**Separate checks**
It would be great to have the checks inside of Killaura to be separated. Example of why this would be useful is because a staff member may get an alert of somebody using Killaura the player could be using an aim assist or an autoclicker though they will be looking for killaura. The alerts won't be detailed enough and staff members won't know exactly what to look for. This also helps with seeing specifically what a player was banned for without an owner needing to look into the logs of AAC.

Here is what I'm thinking:
_Killaura Ax_ should be moved to a check called _Aim_, _Killaura Bx_ should be kept in the _Killaura_ check, and _Killaura Cx_ should be moved into a check called _Autoclicker_.

**Hitbox check**
Hitbox max_reach should check for the reach every click on a player instead of every time they deal damage. The reasoning would be for far faster detection of reach and especially for ghost clients or players who use little amounts of reach. Maybe a config option to toggle between this would be nice to have.

**Comment by konsolas** [comment]
I'm hesitant to create new checks as this might break plugin compatibility. The hitbox suggestion is definitely something to be considered though.

**Comment by Rerd** [comment]
If you’re able to get separated checks for the Killaura check to work properly that would be extremely useful.

**Comment by ArtNRG** [comment]
It is possible to add an additional messages based on killaura checks. It will not break anything and give the staff all information.

**Comment by konsolas** [comment]
Killaura has been split into aimbot and autoclicker in AAC5.
