### ISSUE TITLE
AAC setVelocity server freeze for 5 minutes

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1729]
AAC 4.1.4, Paper 1.12.2
When player used trampoline (setVelocity), Move check triggered him and server hung for 5 mins.
https://pastebin.com/2mZjBZ4b

**Comment by BestMark** [comment]
https://www.spigotmc.org/threads/excessive-velocity-detected-before-crash.190397/
So, the reason of the crash is Paper
Could you add compatibility with Paper warnForExcessiveVelocity function?

**Comment by konsolas** [comment]
On discord, it was determined that SkywarsX caused this particular crash.
