### ISSUE TITLE
NPE on PlayerMoveEvent

### ISSUE THREAD

**Issue by niqoar** [konsolas/AAC-Issues#1731]
Issue description:
NPE on PlayerMoveEvent

Log: https://pastebin.com/0PVvXXS9

Server version:
Paper version git-Paper-173 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

AAC version:
4.1.4

ProtocolLib version:
4.5.0-SNAPSHOT

**Comment by konsolas** [comment]
4.1.4-b1
