### ISSUE TITLE
Move check false positive with carpets

### ISSUE THREAD

**Issue by Zaino60** [konsolas/AAC-Issues#1733]
### Issue description
Basically when you try to sprint through carpets the move check triggers and it lag backs. Video Reproducing the bug: https://gyazo.com/86d7ed6e0bc4a02ce19a6054b19fd690

**AAC Log**: https://pastebin.com/aTfsUZSG (Users reproducing the bug: "SiSuficiente" and "GreenBearr". Bug Happens with any Minecraft version from 1.8 to 1.14.4)
### Core information
**Server version**: PaperSpigot 1.14.4

**AAC version**: 4.1.4-b1

**ProtocolLib version**: 4.5.0-SNAPSHOT

**ProtocolSupport version**: 4.29-dev

**BungeeCord plugins**: This server is running BungeeCord version git:BungeeCord-Bootstrap:1.14-SNAPSHOT:34febec:1419 by md_5

### Configuration
Using Celebrimbor's optimized config but the issue happens even with default config.

**Comment by Janmm14** [comment]
The logs show that AAC thinks there is no carpet apparantly.

**Comment by konsolas** [comment]
This is caused by ProtocolSupport, which is apparently removing the carpet hitbox for some reason.

**Comment by konsolas** [comment]
4.1.5 adds internal corrections for carpet hitboxes.
