### ISSUE TITLE
Make Movement modules toggleable

### ISSUE THREAD

**Issue by ezzerland** [konsolas/AAC-Issues#1735]
Currently, all move checks are combined and you have no control over which modules you do or do not punish for. It's currently an all or nothing kind of mitigation. It's obviously ideal for all move data to be interpreted at once and then for the modules to act based on that data (or so I assume this is how the movement check works), but each module should still be mutable, imo.

It's similar for Kill-Aura modules. Right now you can scale the VL's that kill-aura offer, but you cannot disable any of the modules (tested removing from config, setting to 0 and setting to -1, still adds VL's for the removed checks).

For longevity, I think the bit more robust control of these features would be beneficial.

**Comment by konsolas** [comment]
Do you mean you want to disable move mitigation/kicks specifically in water, or specifically when using the elytra? If this is the case, then you can set the "weight" of the module to 0, so it doesn't add any VL and as a result will not teleport the player or cause any kicks.

Removing a killaura module from the config will result in it being enabled with the default weight. Given that scaling the VLs of different modules works for you, it's unclear why you weren't able to disable them by setting them to 0 or -1. What happened when they were set to these values?

**Comment by ezzerland** [comment]
> Do you mean you want to disable move mitigation/kicks specifically in water, or specifically when using the elytra? If this is the case, then you can set the "weight" of the module to 0, so it doesn't add any VL and as a result will not teleport the player or cause any kicks.
Yes, but if I do this, I can now no longer ban the user for that action because it's not increasing the violations (have not tested to see if the VL's add up).

> Removing a killaura module from the config will result in it being enabled with the default weight. Given that scaling the VLs of different modules works for you, it's unclear why you weren't able to disable them by setting them to 0 or -1. What happened when they were set to these values?
Previously, they just continued to count VL's. I didn't test it on the latest version until this morning and found that it currently works as intended, so whatever issue may have been here seems to be corrected.

**Comment by konsolas** [comment]
Because of how integrated the different parts of the move check are, I don't think maintaining a separate violation level for each one is going to be realistic, so I'm going to close this feature request for now.
