### ISSUE TITLE
1.14.4 Crouch walking in water with depth strider boots + dolphin's grace

### ISSUE THREAD

**Issue by AndyK77** [konsolas/AAC-Issues#1738]
### Issue description

Player equipped with depth strider 3 boots + dolphin's grace potion effect will get violations if the player is crouching on the edge of a block submerged under the water and attempting to move (video: https://cdn.discordapp.com/attachments/248520431986802688/614603203602022410/water.mp4)

### Core information
**Server version**: 1.14.4

**AAC version**: 4.1.5

**ProtocolLib version**: 4.5.0-SNAPSHOT (latest dev build) 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
Should be fixed in 4.1.6 (I tested with /speed 10 instead of specific effects)
