### ISSUE TITLE
High Jump not detected

### ISSUE THREAD

**Issue by ezzerland** [konsolas/AAC-Issues#1739]
1.8.8 server
4.1.5 with default config

Just tested wolfram and was able to use high jump with no detections. Not sure if high jump support has been added.

**Comment by coolpvpv1** [comment]
> 1.8.8 server
> 4.1.5 with default config
> 
> Just tested wolfram and was able to use high jump with no detections. Not sure if high jump support has been added.

ive tried highjump before and aac detected it so idk if its something wrong with your server and why did you completely remove the format the issue gave you

**Comment by ezzerland** [comment]
Really no need to be rude. Issue doesn't need a lot of detail. Nothing wrong with my server. If more detail is required, welcome to ask for it, but it should be very easy to replicate.

**Comment by konsolas** [comment]
Do you have any more details? For example, what height did you set highjump to?

**Comment by ezzerland** [comment]
https://youtu.be/dgJWOt5C4XA

Small clip to demonstrate.

I did notice after I recorded that if I am sprinting while high jumping that it seems to detect it basically immediately. But if I am walking or standing in place it does not seem to.

Just to be clear, only permission that account has on the server is aac.verbose

**Comment by konsolas** [comment]
I can't reproduce this one; I'm being detected pretty much instantly:

![image](https://user-images.githubusercontent.com/9408210/63638547-a7cfb900-c681-11e9-924e-00b62622b7ec.png)

Have you checked if you're bypassing AAC in any way (e.g. if you have flight on)? Does AAC detect blatant stuff like Fly?

**Comment by konsolas** [comment]
I can't reproduce this. I'm being detected pretty much instantly:

![image](https://user-images.githubusercontent.com/9408210/63638581-16147b80-c682-11e9-9892-fbc5a52046e9.png)

Have you made any modifications to the default configuration? Is it possible that you're bypassing AAC somehow? A good way to check might be to try out something that will definitely be detected, like fly.

**Comment by BestMark** [comment]
AAC doesn't detect HighJump with Celebrimbor's config. He answered me that it is OK, and he will not do something to fix it.
So, I recommend you lower the Move mitigation min_vl value to ~250.
![image](https://user-images.githubusercontent.com/18399104/63640799-7836a600-c6ad-11e9-8d86-bea34541f71e.png)

**Comment by coolpvpv1** [comment]
> Really no need to be rude. Issue doesn't need a lot of detail. Nothing wrong with my server. If more detail is required, welcome to ask for it, but it should be very easy to replicate.

i wasn't rude

**Comment by ezzerland** [comment]
@coolpvpv1 - Then I apologize for misinterpreting.
@BestMark - I don't have Celebs config, but in my previous tests I did modify that value.

After checking, I've realized I did not restart the server after deleting the config and after restart, it detects this as intended.

Thanks all :)
