### ISSUE TITLE
Eating while moving

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#174]
Eating while sneaking was patched, however when you eat regularly and move forward now you will be flagged. https://www.youtube.com/watch?v=ktkvJpAKL2s

**Comment by Janmm14** [comment]
I reproduced this with vanilla 1.10.2 minecraft. gettig vl7 or vl7 and vl14

**Comment by Photon-GitHub** [comment]
Fixed, tested by me.
