### ISSUE TITLE
Still strong web issues

### ISSUE THREAD

**Issue by DasCanard** [konsolas/AAC-Issues#1740]
### Core information
**Server version**: 1.8.8 Spigot

**AAC version**: 4.1.5

**ProtocolLib version**: 4.4.0

**Plugin list**: 
![image](https://user-images.githubusercontent.com/17070204/63638132-94721d00-c684-11e9-8947-f6513816cd19.png)

### Special environment information
**ViaVersion version**: 2.1.2

### Configuration

Default config

https://youtu.be/oWCCtA1Vs9E
https://youtu.be/91xdmoEr2FY

**Comment by DasCanard** [comment]
sorry forgot to add: related to #1634

**Comment by konsolas** [comment]
4.1.6
