### ISSUE TITLE
onPacketReceiving NPE@ck.a:2

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1741]
server version 1.13.2 paperspigot
i use protocolsupport
log
https://pastebin.com/8kGrZiLy

**Comment by konsolas** [comment]
AAC version?

**Comment by leoncp9** [comment]
4.1.5

**Comment by leoncp9** [comment]
same problem with paperspgito 1.14.4., i use aac version 4.1.6

**Comment by konsolas** [comment]
4.1.7
