### ISSUE TITLE
Spam console error

### ISSUE THREAD

**Issue by CentralVortex** [konsolas/AAC-Issues#1742]
Console Error: https://gist.github.com/CentralVortex/687286a57f2f236dd6d976839fcda134
logs: https://gist.github.com/CentralVortex/7381a65ba8b35916ecfd9423168c528c + these logs provide phase false positives
Core information
Server version: 1.8.8
AAC version: 4.1.6
ProtocolLib version: 4.4.0
config: Using Celebrimbor's config

**Comment by CentralVortex** [comment]
These logs provide me (CentralVortex) getting phase false positives and getting stuck in blocks

**Comment by konsolas** [comment]
4.1.7
