### ISSUE TITLE
False positive move check on slabs

### ISSUE THREAD

**Issue by blek-id** [konsolas/AAC-Issues#1743]
### Issue description
https://pastebin.com/xx9u9dwa
When player moves on slabs, they got tons of false positive move checks. They tried running on top a full slab, or slabs that are 1 block apart

### Core information
**Server version**: 1.13.2

**AAC version**: 4.1.6

**ProtocolLib version**: 4.4.0

**Plugin list**: -

### Special environment information
**ViaVersion version**: 2.1.3

**ProtocolSupport version**: -

**ViaBackwards version**: -

**BungeeCord plugins**: -

### Configuration
PLEASE DO NOT WRITE YOUR ISSUE DESCRIPTION HERE -->
I'm using Optimized Config Support (Ghost Config) by Celebrimbor
AAC v4.1.5 | Ghost | 1

**Comment by konsolas** [comment]
Can I have a screenshot of the slabs that were being run on?

**Comment by blek-id** [comment]
![image](https://user-images.githubusercontent.com/26654664/63647673-06169d80-c74f-11e9-91d4-e533507634e4.png)

the quartz slab doesn't cause any false positive

**Comment by konsolas** [comment]
So only a specific type of slab causes false positives?

**Comment by blek-id** [comment]
All types are affected. I only make the one as quartz to let you know that placing the slab in that manner is fine

**Comment by konsolas** [comment]
Will need to verify this - haven’t had anyone else reporting slab issues yet.
