### ISSUE TITLE
Server freezes when AAC tries to analyze bounding box

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1744]
Thread dump: https://pastebin.com/x88xbgdn
Server log before freeze: https://pastebin.com/YNyxpQd5 (lots of flood in console)

### Core information
**Server version**: Paper 1.12.2

**AAC version**: 4.1.6

**ProtocolLib version**: 4.3.0

### Special environment information
**ProtocolSupport version**: latest for 1.12.2

**Comment by Janmm14** [comment]
You likely have move async enabled. I suggest that you turn it off as it should very likely fix this server freeze.

**Comment by konsolas** [comment]
Should be resolved in 4.1.7
