### ISSUE TITLE
1.14.4 [Move] Elytra fly against ladders 

### ISSUE THREAD

**Issue by AndyK77** [konsolas/AAC-Issues#1745]
### Issue description

When flying with elytra against a ladder, there's an insane amount of false-positive violations, video: https://cdn.discordapp.com/attachments/262588738939387904/615278195339690004/elytra_ladder.mp4

### Core information
**Server version**: 1.14.4

**AAC version**: 4.1.6

**ProtocolLib version**: 4.5.0-SNAPSHOT (latest dev build)

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
4.1.7
