### ISSUE TITLE
[AAC] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1749]
log
https://pastebin.com/bpm0iaDK
server version paperspigot 1.14.4
client fluxb13
aac version 4.1.7

**Comment by konsolas** [comment]
What exactly are you doing that causes this error to occur, and what makes the client relevant?

**Comment by leoncp9** [comment]
i don't know why is important the client, i don't know why i get this error :/

**Comment by konsolas** [comment]
Can you send me the full latest.log privately? e.g. in a discord DM. You could also post it here if you're comfortable with that.

**Comment by leoncp9** [comment]
done

**Comment by konsolas** [comment]
4.1.8
