### ISSUE TITLE
AAC v3 speed/fly false positive with fences/fencegates in the ground

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#175]
https://youtu.be/eBeSZ9iW-gg

**Comment by konsolas** [comment]
Fixed, confirmed by geNAZt

**Comment by Janmm14** [comment]
Still flags for
* moved too quickly
* jumping too quickly
* rarely fly (got it once: moved unexpectedly 0.00 (0.00 -> -0.08), vl2)
