### ISSUE TITLE
PAPI Suggestion 

### ISSUE THREAD

**Issue by FlaxenYapper287** [konsolas/AAC-Issues#1751]
Hey,

I would really like to see AAC have some[ PAPI](https://www.spigotmc.org/resources/placeholderapi.6245/) placeholders that I (and I'm sure many others) could use to link in with other plugins. For now all I am looking for is a way of getting someones total violation level as a placeholder (Maybe %aac_violation_lvl%) however I am sure there would be lots of uses for other placeholders.

Thanks, 
Flax

**Comment by konsolas** [comment]
Replacing AAC's internal placeholder system with PlaceholderAPI entirely might be a possibility. This would break existing configs, though.

**Comment by FlaxenYapper287** [comment]
It's good to know that it is a possibility, obviously if it is too big a change just to add this then it's no big deal :)

**Comment by konsolas** [comment]
PlaceholderAPI integration added in 4.2.1
