### ISSUE TITLE
Shulker boxes false positive

### ISSUE THREAD

**Issue by AndyK77** [konsolas/AAC-Issues#1752]
### Issue description

While standing on a shulker box, open it and immediately close while trying to jump, video:
https://cdn.discordapp.com/attachments/262588738939387904/615959158805626950/shulker.mp4

I had parkour built on this mechanic, after installing aac it is unplayable :C

### Core information
**Server version**: 1.14.4

**AAC version**: 4.1.7

**ProtocolLib version**: 4.5.0-SNAPSHOT (latest dev build)

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
What an odd mechanic to build a game mode around. I wonder if any other anticheats handle this correctly.

**Comment by konsolas** [comment]
Do you have text logs of this from plugins/AAC/logs? It can be hard to tell exact timestamps from the video.

**Comment by konsolas** [comment]
4.1.8
