### ISSUE TITLE
tHeN rEpOrT iT ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by ZugPilot** [konsolas/AAC-Issues#1754]
### Issue description

**Video**: https://www.youtube.com/watch?v=So57w9wM5CE 

### Core information
**Server version**: 
1.8.8 - Spigot
**AAC version**: 
3.1.7
**ProtocolLib version**: 

**Plugin list**: 
Nothing interesting 
### Special environment information
**ViaVersion version**: ??
NONE
**ProtocolSupport version**: ??
NONE
**ViaBackwards version**: ??
NONE
**BungeeCord plugins**: ??
NOOOONE

**Comment by konsolas** [comment]
duplicate of #1722
