### ISSUE TITLE
Killaura cancelled hits and false kicks (Start video from minute 2)

### ISSUE THREAD

**Issue by CentralVortex** [konsolas/AAC-Issues#1755]
Cancelled hits and false kicks for killaura.
video: https://www.youtube.com/watch?v=L2ZC6HAxxG0&feature=youtu.be
logs: https://gist.github.com/CentralVortex/dd40333f415a0e62bd3690a1f128b271
Core information
Server version: 1.8.8
AAC version: 4.1.7
ProtocolLib version: 4.4.0
config: Using Celebrimbor's config

**Comment by konsolas** [comment]
Please disable killaura.C3
