### ISSUE TITLE
Enderpearl Glitching 

### ISSUE THREAD

**Issue by ZugPilot** [konsolas/AAC-Issues#1756]
### Issue description

https://youtu.be/t8Sv-MOtpbY

### Core information
**Server version**: 

**AAC version**: 

**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
Fixed in AAC5
