### ISSUE TITLE
AAC allows phasing while has allowed flight enabled.

### ISSUE THREAD

**Issue by SeverePvP** [konsolas/AAC-Issues#1757]
Issue description
AAC allows the player to phase through blocks if the player hasAllowFlight() equaling to true.
1) https://pastebin.com/DGtzbX6N (The log of when player.hasAllowFlight() = false)
     - When player.hasAllowFlight() = true, this error doesnt even show up and lets the player 
        phase through walls.
2) Hacked clients can VCLIP (phase) through walls only IF the player hasAllowFlight() = true 
   (doesn't matter whether isFlying() is true or not)
        How to reproduce:
              a) Get hacked client, type /fly (using essentials command)
              b) Tell your hacked client to VCLIP (phase) through blocks (in any direction up or down)
              c) Enjoy phasing through a block and getting into bases. 
3) -  Video of Player trying to phase through blocks but failed because hasAllowFlight() = false;
            https://gyazo.com/295676af57959af1e99a25cb24cd4e3e
    -  Video of Player trying to phase through blocks and succeed because hasAllowFlight() = true;
          https://gyazo.com/7d823078b30267389ee57e70fca8af72

Server Information
Server version: PaperSpigot (MC: 1.8.8-R0.1-SNAPSHOT)
AAC version: 4.1.7
ProtocolLib version: 4.4.0
ViaVersion 2.1.3

Configuration
No changes, using default config.

**Comment by konsolas** [comment]
AAC doesn’t check players with allowFlight, so this is intended behaviour.
