### ISSUE TITLE
Incompability with lenis0012's Marriage plugin

### ISSUE THREAD

**Issue by PinkLolicorn** [konsolas/AAC-Issues#1758]
### Issue description
Marriage plugin from lenis0012 gives a heart attack to AAC and then plugin collapses. I have seen three issues with similar stacktrace, two old. One from last week, but this is something different. I was unable to figure out what in this plugin is the cause of ExceptionInInitializerError.

Problematic plugin: [Marriage.zip](https://github.com/konsolas/AAC-Issues/files/3558086/Marriage.zip)
GitHub: https://github.com/lenis0012/Marriage
Stacktrace: https://pastebin.com/QsGudeqZ

### Core information
**Server version**: Paper-1618 (MC: 1.12.2)
**AAC version**:  4.1.7,  4.1.8-b1 and probably more, old AAC 3.3.15 was working fine
**ProtocolLib version**: useless
**Plugin list**: only Marriage plugin matters

### Special environment information
**ViaVersion version**:  nah
**ProtocolSupport version**: nah
**ViaBackwards version**: nah
**BungeeCord plugins**: nah

### Configuration
Not applicable really.

**Comment by konsolas** [comment]
Possibly related #1753

**Comment by Janmm14** [comment]
Not related, the marriage plugin is just faster in initialising.

**Comment by Janmm14** [comment]
I attemtped to change lenisutils to fix this problem, please try with this version again: https://github.com/Janmm14/Marriage/releases/tag/v2.0.20-SNAPSHOT

**Comment by Janmm14** [comment]
@PinkLolicorn This custom update should fix your problem https://github.com/Janmm14/Marriage/releases/tag/v2.0.20-SNAPSHOT
