### ISSUE TITLE
Player's version detection can be tricked by ProtocolSupport

### ISSUE THREAD

**Issue by PinkLolicorn** [konsolas/AAC-Issues#1759]
### Issue description
AAC should get player's version from ViaVersion as first source, because ViaVersion with ProtocolSupport causes ProtocolSupport to think everyone is using 1.12.

### Core information
**Server version**: Paper-1618 (MC: 1.12.2)
**AAC version**: 4.1.8-b1
**ProtocolLib version**: 4.4.0
**Plugin list**: AAC, FastAsyncWorldEdit, Multiverse-Core, Multiverse-Portals, ProtocolLib, ProtocolSupport, ViaBackwards, ViaVersion, WorldEdit

### Special environment information
**ViaVersion version**: 2.1.4-SNAPSHOT
**ProtocolSupport version**: 4.28
**ViaBackwards version**: 2.4.0-SNAPSHOT

### Configuration
No changes, default config everywhere.

**Comment by konsolas** [comment]
4.1.8-b2
