### ISSUE TITLE
AAC crashes server

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1760]
https://pastebin.com/9nYVnRYy
### Core information
**Server version**: Spigot 1.8.8

**AAC version**: v4.1.8-b1

**ProtocolLib version**: 4.4.0.

### Special environment information
**ViaVersion version**: latest

**Comment by konsolas** [comment]
4.1.8-b2

**Comment by BestMark** [comment]
Crash wasn't fixed.
https://pastebin.com/wMWrxTjk
