### ISSUE TITLE
AAC Logger API

### ISSUE THREAD

**Issue by ForceUpdate1** [konsolas/AAC-Issues#1761]
Please add a way to access the logger via the API to add custom messages. So that you can better identify problems later.

**Comment by Janmm14** [comment]
do you have examples?

**Comment by konsolas** [comment]
Probably something like `AACAPI#log(Plugin, String)`

**Comment by Janmm14** [comment]
I mean more like why? And examples like example strings to log

**Comment by ForceUpdate1** [comment]
For example, for the mini game state like lobby or ingame

**Comment by konsolas** [comment]
4.2.0
