### ISSUE TITLE
Console error on plugin enable

### ISSUE THREAD

**Issue by MrDsa1** [konsolas/AAC-Issues#1763]
### Issue description

Console error on enabling. Error text - [click](https://justpaste.it/62epa)
(on my other spigot servers the same version all works)

### Core information
**Server version**: spigot 1.12.2

**AAC version**: 4.1.8

**ProtocolLib version**: 4.4.0

**Plugin list**: 
![image](https://user-images.githubusercontent.com/49731463/64074131-23e48500-ccb0-11e9-87a4-88f3ba1984e9.png)

### Special environment information
**ViaVersion version**: 2.1.3

### Configuration
default

**Comment by konsolas** [comment]
Related to #1758
