### ISSUE TITLE
The plugin wont start

### ISSUE THREAD

**Issue by PreddieFTW** [konsolas/AAC-Issues#1766]
### Issue description
The cheat wont start up, it says in the console the same.

### Core information
**Server version**: Spigot 1.14.4

**AAC version**: The latest one 4.1.8-b3

**ProtocolLib version**: 

**Plugin list**: [https://i.gyazo.com/78064d4587a879c46336a888b0377a08.png](url)

### Special environment information
**ViaVersion version**: x

**ProtocolSupport version**: x

**ViaBackwards version**: X

**BungeeCord plugins**: x

### Configuration
02.09 04:51:59 [Server] INFO Loading libraries, please wait...
02.09 04:52:03 [Server] Server thread/INFO Starting minecraft server version 1.14.4
02.09 04:52:03 [Server] Server thread/INFO Loading properties
02.09 04:52:04 [Server] Server thread/INFO This server is running CraftBukkit version git-Spigot-9de398a-9c887d4 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
02.09 04:52:04 [Server] Server thread/INFO Server Ping Player Sample Count: 12
02.09 04:52:04 [Server] Server thread/INFO Using 4 threads for Netty based IO
02.09 04:52:04 [Server] Server thread/INFO Debug logging is disabled
02.09 04:52:04 [Server] Server thread/INFO Default game type: SURVIVAL
02.09 04:52:04 [Server] Server thread/INFO Generating keypair
02.09 04:52:04 [Server] Server thread/INFO Starting Minecraft server on 51.75.186.33:25565
02.09 04:52:04 [Server] Server thread/INFO Using epoll channel type
02.09 04:52:09 [Server] Server thread/WARN Plugin DeluxeTags v1.7.1 does not specify an api-version.
02.09 04:52:09 [Server] Server thread/WARN Plugin Vivecraft-Spigot-Extensions v1.14.4-r6 does not specify an api-version.
02.09 04:52:09 [Server] Server thread/WARN Plugin Marriage v2.0.19 does not specify an api-version.
02.09 04:52:10 [Server] Server thread/INFO [AAC] Attempting to inject into PlayerConnection
02.09 04:52:10 [Server] Server thread/ERROR Could not load 'plugins/AAC-4.1.8-b3.jar' in folder 'plugins'
02.09 04:52:10 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
02.09 04:52:10 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
02.09 04:52:10 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
02.09 04:52:10 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:253) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
02.09 04:52:10 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
02.09 04:52:10 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
02.09 04:52:10 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
02.09 04:52:10 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
02.09 04:52:10 [Server] INFO Caused by: java.lang.ExceptionInInitializerError
02.09 04:52:10 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
02.09 04:52:10 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
02.09 04:52:10 [Server] INFO ... 6 more
02.09 04:52:10 [Server] INFO Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02.09 04:52:10 [Server] INFO at me.konsolas.aac.a0.a(Native Method) ~[?:?]
02.09 04:52:10 [Server] INFO at me.konsolas.aac.a0.run(Native Method) ~[?:?]
02.09 04:52:10 [Server] INFO at me.konsolas.aac.AAC.<clinit>(AAC.java:21) ~[?:?]
02.09 04:52:10 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
02.09 04:52:10 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
02.09 04:52:10 [Server] INFO ... 6 more
02.09 04:52:10 [Server] INFO Caused by: java.lang.reflect.InvocationTargetException
02.09 04:52:10 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at me.konsolas.aac.a0.a(Native Method) ~[?:?]
02.09 04:52:10 [Server] INFO at me.konsolas.aac.a0.run(Native Method) ~[?:?]
02.09 04:52:10 [Server] INFO at me.konsolas.aac.AAC.<clinit>(AAC.java:21) ~[?:?]
02.09 04:52:10 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
02.09 04:52:10 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
02.09 04:52:10 [Server] INFO ... 6 more
02.09 04:52:10 [Server] INFO Caused by: java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "net/minecraft/server/v1_14_R1/PlayerConnection"
02.09 04:52:10 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at me.konsolas.aac.a0.a(Native Method) ~[?:?]
02.09 04:52:10 [Server] INFO at me.konsolas.aac.a0.run(Native Method) ~[?:?]
02.09 04:52:10 [Server] INFO at me.konsolas.aac.AAC.<clinit>(AAC.java:21) ~[?:?]
02.09 04:52:10 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_222]
02.09 04:52:10 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
02.09 04:52:10 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
02.09 04:52:10 [Server] INFO ... 6 more
02.09 04:52:10 [Server] Server thread/WARN Plugin BetterRTP v2.8.4 does not specify an api-version.
02.09 04:52:10 [Server] Server thread/WARN Plugin ChatInjector v1.0.0 does not specify an api-version.
02.09 04:52:11 [Server] Server thread/WARN Plugin TitleManager v2.1.5 does not specify an api-version.
02.09 04:52:11 [Server] Server thread/INFO [PlaceholderAPI] Loading PlaceholderAPI v2.10.3-DEV-77

**Comment by PreddieFTW** [comment]
already found out what it was.. it was the marriage plugin. i have no clue why it does this tho

**Comment by Janmm14** [comment]
Check out https://github.com/konsolas/AAC-Issues/issues/1758#issuecomment-526550173

I have edited the Marriage plugin to be compatible with AAC.
