### ISSUE TITLE
OkHttp dispatcher error

### ISSUE THREAD

**Issue by Ultracrepadarian** [konsolas/AAC-Issues#1767]
### Issue description

Since ive downloaded the plugin, I've been getting an error stack trace in my console all the time. It seems to be happening pretty randomly. The error is as follows: 

https://pastebin.com/kPPVC7rM

### Core information
**Server version**: 1.12

**AAC version**: 4.1.8

**ProtocolLib version**: 4.4.0

**Plugin list**: 

### Special environment information
**ViaVersion version**: 2.1.1

**ProtocolSupport version**: 2.4.0

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by Janmm14** [comment]
What craftingstore plugin are you using?
The current version does not look like it is using okhttp3

**Comment by Ultracrepadarian** [comment]
Im using craftingstore 2.1.5. Is this an issue i should report to them?

**Comment by Janmm14** [comment]
Update thst plugin to the alatesz version 2.2.1, they changed it there.
