### ISSUE TITLE
Move event IllegalState: Queue full

### ISSUE THREAD

**Issue by LorgeN** [konsolas/AAC-Issues#1770]
### Issue description
I am not sure if there were any in-game consequences of the issue other than the move check not doing its thing correctly, but I spotted this stack trace in the logs when I was reviewing them for something else:
https://gist.github.com/LorgeN/aa644e511fc2e68081fbcc3ba85ffa10

### Core information
**Server version**: Paper 1.8.8

**AAC version**: 4.1.8-b3

**ProtocolLib version**: 4.4.0

**Plugin list**: 

### Special environment information
**ViaVersion version**: 2.1.3

### Configuration
Using Celebrimbor's ghost config

**Comment by konsolas** [comment]
Is async on by any chance?

**Comment by CeIebrimbor** [comment]
@LorgeN 
In the Move check, did you change `async: false` to true?

**Comment by LorgeN** [comment]
I did not. The only changes I have made are replacing commands to use my own notification system. I would attach the full configuration, but I don't want to publish @CeIebrimbor's stuff so everyone can grab it. If you'd like I can DM you the configuration over Discord? LorgeN#0001

**Comment by konsolas** [comment]
4.2.0
