### ISSUE TITLE
shadowsnap capabilities

### ISSUE THREAD

**Issue by untuned** [konsolas/AAC-Issues#1771]
**This is an enhancement.**

Allow detection of whether ShadowSnap is installed, and if so, allow automatic creation of snaps.
Not entirely sure how this would work, maybe start recording on a configurable violation level for each check?  This would be greatly helpful in showing evidence back to people who appeal bans, instead of hoping it was recorded properly.

**Comment by konsolas** [comment]
You can already do this by setting a threshold action to /shadow snap

e.g:
```
50:
  - "shadow snap %aac_player%"
```
