### ISSUE TITLE
Assume highest version if protocol greater than current highest

### ISSUE THREAD

**Issue by SlimeDog** [konsolas/AAC-Issues#1772]
### Issue description
Protocol version encountered (553) is greater than server protocol (498), so 1.8 should not be assumed. Why not assume the server version based on the server protocol version?

```
[08:31:45] [Server thread/WARN]: [AAC] Unsupported protocol version: 553 (assuming 1.8)
[08:31:45] [Server thread/WARN]: [AAC] Unsupported protocol version: 553 (assuming 1.8)
[08:31:45] [Server thread/INFO]: [ViaVersionStatus] rambeau is using version 1.15(553).
```

### Core information
**Server version**: Spigot 1.14.4 (Jenkins 2470) git-Spigot-94af569-6ddeb98 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**AAC version**: 4.1.8-b3

**ProtocolLib version**: 4.5.0-b16

**Plugin list**: 

### Special environment information
**MC client version**: 1.15 19w37a

**ViaVersion version**: 2.1.4-b274

**ProtocolSupport version**: n/a

**ViaBackwards version**: n/a

**BungeeCord plugins**: n/a

### Configuration
Default

**Comment by konsolas** [comment]
4.2.0
