### ISSUE TITLE
Blink detection not work

### ISSUE THREAD

**Issue by MeowMiaoMiao** [konsolas/AAC-Issues#1773]
AAC: 4.1.8-b3
ProtocolLib: 4.4
server: spigot 1.8.8
![blink](https://user-images.githubusercontent.com/29674595/64906734-96c41600-d71c-11e9-9c3d-fef7aa86d3b9.gif)

**Comment by Janmm14** [comment]
Cant you jsut upload a real video?

**Comment by MeowMiaoMiao** [comment]
> Cant you just upload a real video? (for example on youtube)

AAC default configuration 
LiquidBounce b64 cheat client
Blink 30 block easy to reproduce

**Comment by konsolas** [comment]
Going to update defaults for timer in 4.2.4
