### ISSUE TITLE
False positives of Killaura B1: (T3)

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1774]
### Issue description

This happens when you hit an opponent who has a Velocity-cheat.
Log: https://pastebin.com/U5R39s2u
Video: https://youtu.be/d5LpOf3dVb8 (Particles in the video appear when the player teleports (teleportation causes AAC)

Opponent has LiquidBounce b2 cheatclient (1.12.2) with this config: https://i.imgur.com/Ujx1Oze.png

### Core information
**Server version**:  paper 1.12.2

**AAC version**: latest (4.1.8-b3)

**ProtocolLib version**: v4.4.0-SNAPSHOT

### Configuration
Cel-r config

**Comment by konsolas** [comment]
Either you have a plugin that is severely messing with the protocol or _Etzer_ is using killaura.
