### ISSUE TITLE
NoFall bypass

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1776]
### Issue description

NoFall bypass on Wurst

Wurst cheatclient (1.12.2)
Video: https://radikal.ru/video/rB34IvcuxHn
(Console verbose is enabled)

### Core information
**Server version**:  CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

**Plugin list**: ProtocolLib, AAC

### Special environment information
**ViaVersion version**: No

**ProtocolSupport version**: No

**ViaBackwards version**: No

**BungeeCord plugins**: No

### Configuration

Default

**Comment by konsolas** [comment]
duplicate of #1737
