### ISSUE TITLE
Feature for interact-check (BedFucker bypass)

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1777]
### Issue description

Right now, mitigation min_vl has the same meaning for all checks.
I suggest making this option separate for each checks, as well as adding a separate check to destroy the bed.

We all know that the most popular Minecraft game is BedWars, ideally we need to make the anti-cheat cancel the destruction of the bed from 0 VL.

LiquidBounce b2 cheatclient (1.12.2), config: https://i.imgur.com/h1Q9ex4.png
Video: https://radikal.ru/video/Dy3NjkPzzfE

### Core information
**Server version**:  CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

**Plugin list**: ProtocolLib, AAC

### Special environment information
**ViaVersion version**: No

**ProtocolSupport version**: No

**ViaBackwards version**: No

**BungeeCord plugins**: No

### Configuration

Default

**Comment by BestMark** [comment]
Same problem. Also it will be better to add more VLs for check that detects HighJump/LongJump.
