### ISSUE TITLE
Tried to analyse bounding box with huge volume

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1779]
### Issue description

Today I started testing the new version of AAC (after 3.6.4) and on one of the mini-games, I saw that such messages appeared several times in the console: https://pastebin.com/DdMC2J8t

### Core information
**Server version**: paper 1.12.2

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

### Configuration
Cel-r config

**Comment by CeIebrimbor** [comment]
Looks like some detection calculations were left uncovered.
