### ISSUE TITLE
No Fall bypass.

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#178]
No fall bypasses with the AAC mode active. It's work more reliable at lower hights, but can still work at 50 blocks.  https://www.youtube.com/watch?v=NuYNtDBaUEg

**Comment by Janmm14** [comment]
Suicide NoFall works seamingless with 5 blocks

**Comment by Rqcco** [comment]
*I was using the Synergy Client.*

**Comment by konsolas** [comment]
Fixed, tested by myself with the synergy client.
