### ISSUE TITLE
FightSpeed issues with Cobblestone Generators (SkyBlock)

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1781]
Our SkyBlocks ([ASkyBlock](https://github.com/tastybento/askyblock)) cobble stone generators are causing kicks with AAC's FightSpeed check. AAC logs of relevant user: https://gist.githubusercontent.com/andrewkm/7e4f1a3b8ba203b6f769ecd1bd8f9789/raw/7713b4812cf7af693e18799a26aedc58e456017e/gistfile1.txt

Any help would be highly appreciated!

### Core information
**Server version**: 1.12.2 (Paper Build 1618)

**AAC version**: 4.2.1

**AAC config**: 4.2.1|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.4.0 Build 403

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: 2.1.4 Build 368

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
4.2.2
