### ISSUE TITLE
Move check false positives on slabs/certain block edges (water/stairs).

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1782]
Original report states the following:

> Moving(maybe sprinting and jumping)on slabs or certain block edges in water and some stairs. Get you stuck on them until you manage to somehow untangle yourself from the block by moving backwards.

Video follows here:
https://www.youtube.com/watch?v=P9qiPZUVyX8
The first 15 seconds are what's important here (where the AAC related bug was shown), the rest of the video is showing off other bugs that are unrelated to AAC.

During those first 15 seconds, logs for the user are as such:
https://pastebin.com/raw/WCTbEgpg

### Core information
**Server version**: 1.13.2 (Paper Build 645)

**AAC version**: 4.2.1

**AAC config**: 4.2.1|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.4.0 Build 425

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: 2.1.4 Build 368

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
Merging with #1743
