### ISSUE TITLE
Incompability with Marriage Plugin

### ISSUE THREAD

**Issue by FreddieFaulig** [konsolas/AAC-Issues#1783]
Issue Description:
Hey, AAC is not working with the following plugin; https://www.spigotmc.org/resources/marriage-reloaded-1-13-1-8.18998/
Using this on my Server without the Marriage plugin everything works perfectly fine but when i start my server with aac + the marriage plugin i get the following error:
https://pastebin.com/kTrn99aP
the Marriage Plugin still works then but aac is not able to start

**Server version**:  Paper 1.14.4
**AAC version**:  4.2.1
**ProtocolLib version**:  Dev Build #16 1.14.4
**Plugin list**:  ---- See issue description ----

### Configuration
default config

**Comment by Janmm14** [comment]
https://github.com/Janmm14/Marriage/releases/tag/v2.0.20-SNAPSHOT
