### ISSUE TITLE
lost on how to config AAC

### ISSUE THREAD

**Issue by Apexcode1990** [konsolas/AAC-Issues#1787]
Guys im completely lost on how to configure this beast of a plugin,

can someone be extra kind and point me to like a video tutorial or something helpful?

**Comment by CeIebrimbor** [comment]
The config is heavily commented to explain all values. For the most part, you should leave everything at default and only mess with the thresholds to do what you want (like custom commands or messages).

There are no tutorials.

If you have questions about a certain value or how to configure something, you should ask in the plugin's Discord.
