### ISSUE TITLE
Server is not starting with debugger

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1788]
### Issue description

Server is not starting with debugger (JVM option '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005')

Log: https://pastebin.com/k7ZTfvLi

There was no such problem with the old version of AAC (3.6.4)

**Comment by Janmm14** [comment]
mind showing root/Survival5/hs_err_pid25453.log ?

Not sure whether konsolas can do anything about the crash though, I don't think he added new antidebug, it could be a side effect of other new technique.

**Comment by Pesticidus** [comment]
Okey, but I've deleted it, but here's another
[hs_err_pid2310.log](https://github.com/konsolas/AAC-Issues/files/3653512/hs_err_pid2310.log)
