### ISSUE TITLE
NoFall false positives

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1789]
### Issue description
When player teleports to distant coordinates the player’s client has not yet managed to load chunks and the AAC begins to suspect the player in Nofall. The player begins to receive damage and dies at the beginning of the game.

Log: https://pastebin.com/mp6nQsn0

### Core information
**Server version**: paper 1.12.2

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

### Configuration
Cel-r config

**Comment by Pesticidus** [comment]
Another moment and false triggering NoFall:
the player jumps from a distance of two blocks and receives damage

Video with verbose on: https://yadi.sk/i/-sshJbECd1_5Gw
![image](https://user-images.githubusercontent.com/55303668/65628769-cd324880-dfda-11e9-805e-189516e26501.png)

**Comment by konsolas** [comment]
4.2.2
