### ISSUE TITLE
NoSlowdown bypass

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#179]
Noslowdown works while blocking a sword with the AAC Mode active. https://www.youtube.com/watch?v=eL2bRZC8a0o. Video shows me doing in with the AAC mode and with not.

**Comment by Janmm14** [comment]
Also related:
NoSlowdown eating bypass: https://www.youtube.com/watch?v=mSD8NjnHhmg

**Comment by konsolas** [comment]
Fixed, tested with Synergy b5
