### ISSUE TITLE
KillAura C3 False positives

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1790]
### Issue description
This happens if you hit the player and immediately after that begin to destroy the block.
An interesting fact: the player you hit can be your ally (he does not take damage) or be in gamemode 1. But this false positive will still be exist.

Video: https://yadi.sk/i/yopoxEwXYzXijQ
![image](https://user-images.githubusercontent.com/55303668/65759420-8d2aad00-e123-11e9-98c6-ce3ba418727a.png)

### Core information
**Server version**: paper 1.12.2

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

### Configuration
Cel-r config

**Comment by Pesticidus** [comment]
The same: https://youtu.be/tgyWlSd1wlg

**Comment by konsolas** [comment]
4.2.2
