### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1792]
### Issue description
Hi! When using Java 13 and the following code is executed in my plugin before AAC is loaded, AAC throws this error: https://paste.ubuntu.com/p/MWCpCFnsrG/

![image](https://user-images.githubusercontent.com/55303668/65869405-10960980-e383-11e9-9b06-31c0aa755b36.png)

### Core information
**Server version**: paper 1.12.2

**AAC version**: 4.2.1

**Comment by Janmm14** [comment]
Initialize your PlayerConnection field in onEnable
