### ISSUE TITLE
Move Critical False positives (AAC removes velocity for players)

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1795]
### Issue description

As far as I understand this, one player should jumps, and the second player should have a stick with knockback enchantment.
At the moment when the first player falls, the second must hit him.

First person video: https://youtu.be/-p2mlit4icc
Third person video (Verbose enabled): https://youtu.be/2uvJIvu2wX0

### Core information
**Server version**:  CraftBukkit version git-Spigot-dcd1643-e60fc34 (Final Spigot 1.12.2)

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

**Plugin list**: ProtocolLib, AAC

### Special environment information
**ViaVersion version**: No

**ProtocolSupport version**: No

**ViaBackwards version**: No

**BungeeCord plugins**: No

### Configuration

Default

**Comment by yyunusyigit** [comment]
We have same problem with player.setVelocity();

**Comment by Janmm14** [comment]
A potential problem with the current velocity handling code has been identified.

**Comment by konsolas** [comment]
Despite youtube's best efforts, the verbose text is still quite hard to read in some cases. Do you have the relevant logs as text? @Pesticidus

**Comment by Pesticidus** [comment]
@konsolas 
New video + text verbose form the log:
Log verbose: https://pastebin.com/YzBcczNk
Third person video (Verbose enabled): https://youtu.be/JJmV0R8X3aE
First person video: https://youtu.be/2j4CpXXWWZk + https://youtu.be/8xXqT_FWX4w

**Comment by konsolas** [comment]
It's probable that the modifications to velocity handling in 4.2.3 have fixed this, so I'm going to close this unless evidence to the contrary is produced.
