### ISSUE TITLE
Killaura bypass

### ISSUE THREAD

**Issue by RazerXX** [konsolas/AAC-Issues#1796]
### Issue description

Video: https://radikal.ru/video/HUbsVWCPnLx
Cheat client: https://yadi.sk/d/CYqPZfaTuX9DSg

### Core information
**Server version**: 1.12.2

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

**Plugin list**: AAC, Protocollib

### Configuration
Default

**Comment by konsolas** [comment]
4.2.2
