### ISSUE TITLE
Longjump bypass

### ISSUE THREAD

**Issue by RazerXX** [konsolas/AAC-Issues#1797]
### Issue description

Video: https://radikal.ru/video/DIYs11OVsyZ
Cheat client: https://yadi.sk/d/CYqPZfaTuX9DSg

### Core information
**Server version**: 1.12.2

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

### Configuration
Default

**Comment by konsolas** [comment]
Looks like a 4-block gap which can be jumped legitimately. Also it flags a bunch and repeated use leads to a setback.
