### ISSUE TITLE
[Bug] Soulsand noslowdown

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#18]
As the title says something is broken with the NoSlowdown - check (Speed check) on SoulSand - You can just use normal NoSlowdown on it and it works perfectly.

**Comment by konsolas** [comment]
This is fixed and tested in my own code.

**Comment by Photon-GitHub** [comment]
When I use it on my 1.10 test server I can easily sprint jump on it as if there would be no soulsand...
Are you talking about the 1.8 version? I didn't test it on 1.8.

**Comment by konsolas** [comment]
I mean, I've written the fix just now.

When I put up a beta version on the test server, someone else will verify it and then I'll close the issue.

That's what I intend "fix-verification" to mean.

**Comment by Photon-GitHub** [comment]
You should better use a label like "resolved" or "fixed" those have a clear meaning.

**Comment by konsolas** [comment]
I think I'll just close the issue when I've fixed it, and it can be re-opened if the fix doesn't work.

**Comment by Photon-GitHub** [comment]
Fix on the test-server is verified (just tested it).
