### ISSUE TITLE
Reverse Step Check Perhaps?

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#180]
Reverse Step works fluently and maybe there could be a new check for it? https://www.youtube.com/watch?v=s-lENOiQWt8

**Comment by Janmm14** [comment]
Maybe the video doesn't show it correctly, but it causes you to fall faster over a short distance.

**Comment by konsolas** [comment]
This is going to be a wontfix due to the increased complexity not being worth the risk of false positives.

Barely gives an advantage as well.
