### ISSUE TITLE
StackMobs and KillAura detection

### ISSUE THREAD

**Issue by LowTix** [konsolas/AAC-Issues#1800]
### Core information
**Server version**: Paper 1.8.8

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

**Plugin list**: 

### Special environment information
**ViaVersion version**: Y

**ProtocolSupport version**: N

**ViaBackwards version**: N

**BungeeCord plugins**: N

### Configuration

Hello,

I am currently using your AAC plugin on a PvPFactions server. I also have the plugin named StackMob and when a player kills a stack of mob, I receive alerts from KillAura. I then tested with a dual account version 1.8.8 (no mods) and I did indeed alerts. 
I wanted to know if we could disable the MobAura module in the meantime.

Thanks ♥

**Comment by Janmm14** [comment]
There is no possibility to disable killaura for specific target types currently.

**Comment by konsolas** [comment]
Could be difficult to determine what's happening here without logs of the specific killaura modules being triggered.
