### ISSUE TITLE
Move false positives (Soul sand)

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1801]
### Issue description

Video with verbose: https://youtu.be/6LO0OC4KWV8
Verbose from the log: https://pastebin.com/0SHGMWZA

### Core information
**Server version**:  CraftBukkit version git-Spigot-dcd1643-e60fc34 (Final Spigot 1.12.2)

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

**Plugin list**: ProtocolLib, AAC

### Special environment information
**ViaVersion version**: No

**ProtocolSupport version**: No

**ViaBackwards version**: No

**BungeeCord plugins**: No

### Configuration

Default

**Comment by konsolas** [comment]
duplicate of #1750
