### ISSUE TITLE
Killaura B3 false positives

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1802]
### Issue description
Just stand in the corner and press the “W” button several times

Video with verbose: https://youtu.be/pi24k47oISY
Verbose from the log: https://pastebin.com/PhsFYJs8

### Core information
**Server version**: paper 1.12.2

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

### Configuration
Cel-r config

**Comment by konsolas** [comment]
4.2.2
