### ISSUE TITLE
Very high memory allocation (causes frequent garbage collections)

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1803]
### Issue description
Sometimes AAC starts allocating many objects (~10gb per minute) and causes garbage collections
![image](https://user-images.githubusercontent.com/55303668/67590512-ed812e80-f763-11e9-8b32-7df7b9ba3412.png)

### Core information
**Server version**:  Paper 1.12.2

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

### Configuration

Cel-r

**Comment by Janmm14** [comment]
Depending on player surroundings, AAC sometimes has to calculate much more possible movements which could be the cause of this increase (example: many players in water)

**Comment by konsolas** [comment]
4.2.2
