### ISSUE TITLE
Server crashes, after BadPackets exception

### ISSUE THREAD

**Issue by g-orwell84** [konsolas/AAC-Issues#1804]
### Issue description
Server crashes, after AAC spammed BadPackets detections.
https://pastebin.com/z8jqJWqc

### Core information
**Server version**: 1.8.8-R0.1

**AAC version**: 4.2.1

**ProtocolLib version**: 4.4.0

### Special environment information
**ViaVersion version**: 2.1.3

### Configuration
https://pastebin.com/mwBQjCbu

**Comment by Janmm14** [comment]
AAC is no anti crash tool. Apparantly your existing packet limiter has problems detecting all the packets the lag/crash client mod is sending.
I suggest adding ViaVersion to your server and use the packet limiter from viaversion (it is applying a general limit over all packets)
