### ISSUE TITLE
Got error while starting

### ISSUE THREAD

**Issue by GalaxySMediaXz** [konsolas/AAC-Issues#1805]
When the server is starting aac is working normally...
But it when it Attempting to inject into PlayerConnection

I got this error:
https://pastebin.com/yjtejAuT

The server is running on Minecraft 1.10.2
This server is running CraftBukkit version git-Spigot-72c2605-251a5b6 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
AAC = 4.2.1
Protocolib = 4.4.0

Thank you

**Comment by Janmm14** [comment]
Need plugin list to help you with that.

**Comment by GalaxySMediaXz** [comment]
[21:33:24 INFO]: Plugins (78): RPGHealthIndicator, SupplySign, NoHunger, PluginC
onstructorAPI, KeepItems, ClearChat, ItemToCommand, ArrowRemover, GroupManager,
PlaceholderAPI, PlugMan, randomTP, BlockedCommands, WorldResourcepacks, NametagE
dit, ConsoleSpamFix, MyItems, Airdrops, ChatReaction, MultiWorld, Unbreakable, S
kinsRestorer, NoDrop, ViaVersion, Itemizer, WorldEdit, Advanced_Item_Effects, No
Rain, WorldPlayerSign, Essentials, HackedServer, AgarthaLib, ClearLag, ArmorStan
dEditor, AutoMessage, CrackShot, IllegalStack, Interactables, ProtocolLib, Chars
API, iDisguise, WorldEditCrashFix, EssentialsChat, ItemCases, Vaults, NoCraftPlu
s, PVPLogoutEqualsDeath, Vault, MassiveCore, AZRank, SuperPotions, KillRewards,
HolographicDisplays, Marriage, PlayerPoints, WorldGuard, CustomMobs, ChestComman
ds, EssentialsProtect, PhatLoots, EssentialsAntiBuild, PlayerVaults, ServerSigns
, EssentialsSpawn, ParticleHats, TitleManager, MysteryBags, PortalCommands, Worl
dChangeScreenRemover, SafeTrade, SimpleClans, Citizens, Shopkeepers, CrazyAuctio
ns, AuthMe, LockettePro, CommandNPC, PlayMoreSounds

**Comment by Janmm14** [comment]
Ok, its the same for you as a couple others experiencing this error.

Use this marriage jar instead:
https://github.com/Janmm14/Marriage/releases/tag/v2.0.20-SNAPSHOT
