### ISSUE TITLE
AAC Console Error w/ Paper Spigot 1.14.4

### ISSUE THREAD

**Issue by nick-wd** [konsolas/AAC-Issues#1806]
### Issue description
Getting a constant error in console with the latest AAC (4.2.1) and Paper Spigot v 1.14.4 (223). Error here: https://pastebin.com/CnCCEecC

### Core information
**Server version**: Paper Spigot 1.14.4 (223)

**AAC version**: 4.2.1

**ProtocolLib version**: 4.5.0 (Latest development build (#429)

**Plugin list**: 

### Special environment information
**ViaVersion version**: 2.1.3

**ViaBackwards version**: 2.4.0

### Configuration
Fully default.

**Comment by konsolas** [comment]
This might be an incompatibility with the Marriage plugin, or an incompatibility with the JVM you're using.

**Comment by Janmm14** [comment]
Please use a 64bit JVM to run AAC. (And do not use OpenJ9, but you're not atm, it'd throw a different error)
