### ISSUE TITLE
Killaura A6 False positives (?)

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1808]
### Issue description

Video from servers replay with verbose: https://youtu.be/TNyDeSPG-kQ

### Core information
**Server version**: 1.12.2

**AAC version**: 4.2.1

**ProtocolLib version**:  4.4.0

### Configuration
Cel-r

**Comment by konsolas** [comment]
It does seem strange but this is unlikely to be a false positive.
