### ISSUE TITLE
Cannot install AAC  (Server Crash, 1.8.8)

### ISSUE THREAD

**Issue by LucasCodes01** [konsolas/AAC-Issues#1809]
### Issue description

I cannot start my server with AAC because it gives me this error: https://pastebin.com/9mMTwg1P

I have ProtocolLib installed, however, I can't start the server as it gives me the error above and then the server crashes, please help.

### Core information
**Server version**: 1.8.8 (Spigot)

**AAC version**: 4.2.1

**ProtocolLib version**:  4.4.0

**Plugin list**: WorldEdit, PermissionsEX, ViaVersion, Vault, ProtocolLib, DinoManager (Custom made plugin it is private), Citizens, Essentials, EssentialsChat, CommandNPC, SuperVanish, HolographicDisplays, EssentialsSpawn, BungeeTabListPlus

### Special environment information
**ViaVersion version**: 2.13

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: DinoBungeeManager (Custom made plugin it is private), BungeeTabList, NetworkManager

**Comment by Janmm14** [comment]
Please use another JVM vendor.
Hotspot, Oracle, OpenJDK is supported.
OpenJ9 is not supported.

This should be changeable in settings or advanced settings of your minecraft hosting. In case you have a vserver, look up on how to install another jvm in google if you don't know how.

**Comment by LucasCodes01** [comment]
Thanks it worked!
