### ISSUE TITLE
Water Velocity works (Water doesn't push you)

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#181]
Water Velocity, (basically noslowdown in water) works perfectly with no flags. Water Velocity prevents the currents of the water pushing you, NOT making  it easier to walk through.
Video for demonstration: https://www.youtube.com/watch?v=7QQgZVtC7yQ

**Comment by Photon-GitHub** [comment]
It is hard to detect without false positives as it is velocity and also low priority.

**Comment by Rqcco** [comment]
Yeah, This is definitely low priority.
