### ISSUE TITLE
velocity / killaura bypass

### ISSUE THREAD

**Issue by leoncp9** [konsolas/AAC-Issues#1812]
Hi, I found two clients who bypass knockback and killaura

Jessica Cheat client: https://yadi.sk/d/CYqPZfaTuX9DSg
(Jessica already reported by other user :/)
Aristois Cheat client:  https://aristois.net/download
(Aristois work from 1.12+ version)
Video proof: https://www.youtube.com/watch?v=2x_H9G2Domk

**Comment by leoncp9** [comment]
Acc version ; 4.2.1

**Comment by Janmm14** [comment]
The no knockback / no velocity cheat only works because the hitted player is not moving at all. If he would rotate his head or move, the cheat would get detected amd flagged.
So this is no huge bypass.

**Comment by leoncp9** [comment]
SUPER OMG! ok ok ok ok ok ok if i find a friend i rec with a player who make a movement
