### ISSUE TITLE
Console Error in PlayerMoveEvent while player is riding UNKNOWN

### ISSUE THREAD

**Issue by JustBru00** [konsolas/AAC-Issues#1813]
### Issue description

Console Error:
https://pastebin.com/qBe9qU1p

The console error posted above will appear when a player rides an ender dragon pet created by the MyPets plugin. I believe the ender dragon is "fake" and created via ProtocolLib. My guess is that the error message simply needs to be caught and ignored.

### Core information
**Server version**:  This server is running Paper version git-Paper-225 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**AAC version**: 4.2.1

**ProtocolLib version**: 4.5.0-SNAPSHOT

**Plugin list**: AAC, AdvancedDungeons, Chairs2*, CustomCrafting, DangerousNether*, DeathMessagesPrime, Dimensions, DMPWorldGuard, EliteMobs, EpicRename, EpicShrug, FastAsyncWorldEdit, GroupManager*, LimitPillagers, mcMMO, Multiverse-Core, MyPet, NoBlackSky*, PhantomSMP, PromisedLand, ProtocolLib, Seasons, Vault, VoxelSniper, WBFillPause, WolfyUtilities, WorldBorder, WorldEdit, WorldGuard

### Special environment information
**ViaVersion version**: Not used.

**ProtocolSupport version**: Not Used

**ViaBackwards version**: Not Used

**BungeeCord plugins**: Not Used

### Configuration

Default config except for disabling any kicking or canceling of player actions. Config: https://pastebin.com/09CfCtZz

Let me know if you have any further questions,
Justin B.

**Comment by Janmm14** [comment]
The error is actually created by AAC itself btw.

**Comment by JustBru00** [comment]
I understood that the error was caused by AAC. I was attempting to provide context for when the error message occurred.

**Comment by konsolas** [comment]
4.2.2
