### ISSUE TITLE
Hitbox false positives

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1817]
### Issue description
This happens when the player is next to blocks such as tall grass (when the player is in gamemode 2 or just the destruction of the blocks is turned off). This also happens if the player is next to mobs whose damage is turned off.

Video with verbose: https://youtu.be/S022fkPksmk
Verbose from the log: https://pastebin.com/vSf9Jsym

### Core information
**Server version**:  CraftBukkit version git-Spigot-dcd1643-e60fc34 (Final Spigot 1.12.2)

**AAC version**: 4.2.2

**ProtocolLib version**: 4.4.0

**Plugin list**: ProtocolLib, AAC

### Special environment information
**ViaVersion version**: No

**ProtocolSupport version**: No

**ViaBackwards version**: No

**BungeeCord plugins**: No

### Configuration

Default

**Comment by konsolas** [comment]
Is it in gamemode 2 only?

**Comment by Pesticidus** [comment]
> Is it in gamemode 2 only?

No. This also happens in gamemode 0 in situations where destruction of the blocks is turned off or if the player is next to mobs whose damage is turned off.

**Comment by konsolas** [comment]
How is it possible to turn off the destruction of blocks in gamemode 0?

**Comment by Pesticidus** [comment]
> How is it possible to turn off the destruction of blocks in gamemode 0?

For example, in mini-games

**Comment by konsolas** [comment]
I'm not familiar with this mechanic. Are you aware of a way for a plugin to check if a block has destruction disabled?

**Comment by konsolas** [comment]
Reported to be fixed (v5)
