### ISSUE TITLE
Move false positives (setback when players pvp in the water)

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1818]
### Issue description

Video with verbose: https://youtu.be/SMaQrCI5nqE
Verbose from the log: https://pastebin.com/RL9Q7ZL7

### Core information
**Server version**:  CraftBukkit version git-Spigot-dcd1643-e60fc34 (Final Spigot 1.12.2)

**AAC version**: 4.2.2

**ProtocolLib version**: 4.4.0

**Plugin list**: ProtocolLib, AAC

### Special environment information
**ViaVersion version**: No

**ProtocolSupport version**: No

**ViaBackwards version**: No

**BungeeCord plugins**: No

### Configuration

Default

**Comment by HexedHero** [comment]
Just wanted to comment and say I've been seeing a good few false positives when players are swimming (the animation) in water when hitting mobs.
