### ISSUE TITLE
Flight bypass

### ISSUE THREAD

**Issue by TheIronMinerLv** [konsolas/AAC-Issues#1820]
### Issue description
A player in my server was able to use Flight hacks. I am not sure in what manner, but many players including my staff were reporting that, so here I am with this report...

Logs: https://pastebin.com/gdUHqJXW

### Core information
**Server version**: 1.8.8
**AAC version**: 4.2.3
**ProtocolLib version**: 4.4.0-SNAPSHOT-b403
**Plugin list**: not needed

### Special environment information
**ViaVersion version**: not using
**ProtocolSupport version**: not using
**ViaBackwards version**: not using
**BungeeCord plugins**: not needed

### Configuration
I am using Celebrimbor's ghost config.

**Comment by Janmm14** [comment]
Doesn't look like it was bypassing.

```
[07-12-2019 23:02:28.955] [Lofiks] movement.Move: executing command "aac notify §8§l[§c§lAC§8§l] §eLofiks §fis HIGHLY suspected for hacks > Move >
```

Your config seems to be set up quite lenient.

**Comment by konsolas** [comment]
@CeIebrimbor's ghost config is not designed to block or punish.

I would recommend that you either use the optimised config, or speak to Celebrimbor directly for more options.

**Comment by konsolas** [comment]
What is confusing is why the move violation levels don't appear in the logs :/
