### ISSUE TITLE
KillAura detecting false positives

### ISSUE THREAD

**Issue by Auntex** [konsolas/AAC-Issues#1821]
### Issue Description

Yesterday, I updated AAC to latest version, with Celebrimbor Optimized Config _(Without AACAdditionPro)_. The problem here is, players sometimes hit others on a WorldGuard protected zone from PvP, or PreciousStones protected areas (Non-PvP). If they keep hitting to other player, it gets kicked, they easily are detected as using Kill Aura just hitting, nothing strange. I maded a video demonstrating how it is: https://youtu.be/aQ4nGIMAs0A

**AAC Log**: https://pastebin.com/nJRqZMKj

### Core information
**Server version**: Paper 1.12.2 (git-Paper-1617)

**AAC version**:  4.2.3

**ProtocolLib version**: 4.4.0 

**ViaVersion version**: 2.1.3

### Config information
Actually I am using the Optimized Config of Celebrimbor, didn't modified nothing. Using exactly as 4.2.3 | 1 version.

**Comment by konsolas** [comment]
Could you post your most recent AAC log file (in plugins/AAC/logs) which contains this event?

**Comment by Auntex** [comment]
Edited. I did the logs but didn't uploaded, my bad.

**Comment by konsolas** [comment]
Are you using ViaBackwards/ViaRewind or similar? This might be related to multi version support.

**Comment by konsolas** [comment]
killaura.B2 will be disabled by default in 4.2.4 due to known incompatibilities with viabackwards and similar. You can do this yourself in the meantime by setting killaura.modules.B2 to 0.

**Comment by Auntex** [comment]
Actually using ViaVersion, ViaRewind, ViaRewind-Legacy-Support and ViaBackwards. Also, an extra detail is that I'm using OldCombatMechanics and KnockbackMaster.

Also, thank you! Will disable B2 module from KillAura. An strange thing is that only happens most of the times, but not always.
