### ISSUE TITLE
FastBow check detecting false positives

### ISSUE THREAD

**Issue by Auntex** [konsolas/AAC-Issues#1822]
### Issue Description

While i was testing the issue #1821 if it is fixed when disabling module "B2" by Author recommendation. I got an unexpected false positive, Fast Bow. You get kicked if you stay with your bow holding near to a player for a long time, it cancels to you the shoot and then you got kicked. Here's a video demonstrating: https://youtu.be/YinRObfH4kk _(Ignore the verbose, there was spamming about Move check from other players)_

**AAC Log**: https://pastebin.com/MeY9LHYP

### Core information

**Server version**: Paper 1.12.2 (git-Paper-1617)

**AAC version**:  4.2.3

**ProtocolLib version**: 4.4.0 

**ViaVersion version**: 2.1.3

As extra detail, list of plugins that may be useful in the report: ViaRewind, ViaRewind-Legacy-Support, ViaBackwards, OldCombatMechanics, KnockbackMaster

### Config information
Actually I am using the Optimized Config of Celebrimbor, didn't modified nothing. Using exactly as 4.2.3 | 1 version.

**Comment by konsolas** [comment]
I think this is related to a previous issue where some types of interactions would reset the FastBow timer.
