### ISSUE TITLE
Hit Through wall bypass

### ISSUE THREAD

**Issue by visionfutur** [konsolas/AAC-Issues#1828]
video:https://streamable.com/gb2ay
killaura can hit through wall

**Comment by konsolas** [comment]
This only works on non-player entities, since AAC is more lenient when checking hitboxes for those entities.

I'm going to mark it as unimportant for now, since the focus is on PVP.

**Comment by visionfutur** [comment]
I don't think so. it worked when killaura hit player 1 hit/second.

**Comment by konsolas** [comment]
Because of AAC's violation system.

min_vl can be reduced if you want to block those hits.
