### ISSUE TITLE
ProtocolLib 1.15 Player Action packet compatibility.

### ISSUE THREAD

**Issue by timr2000** [konsolas/AAC-Issues#1831]
### Issue description
Random console errors https://pastebin.com/2TnDfAm0

### Core information
**Paper-8 (MC: 1.15)**: 

**Aac 4.3.0**: 

**Protocillib 4.5.0**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

### Configuration
Using celebrimbor his instaban config.

**Comment by konsolas** [comment]
https://www.spigotmc.org/threads/protocollib.36230/page-60#post-3628468

**Comment by Janmm14** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/731

**Comment by konsolas** [comment]
Fixed, not by me, but by https://github.com/dmulloy2/ProtocolLib/commit/e915fd0f9a1dfa446831aff6fd4e2e7a1cb10baa
