### ISSUE TITLE
AAC Strange Crashes

### ISSUE THREAD

**Issue by Auntex** [konsolas/AAC-Issues#1834]
### Issue Description ###
My Survival server is getting some strange crashes and kicks to my users due to a KeepAlive timeout (Not using AACAdditionPro btw). Logs: https://pastebin.com/zWbPPp07

### Core information ###

*Server version:* Paper 1.12.2 (git-Paper-1617)

*AAC version:* 4.3.1

*ProtocolLib version:* 4.4.0

*ViaVersion version:* 3.0.0-Abstraction

### Config information ###
Actually I am using the Optimized Config of Celebrimbor, didn't modified nothing. Using exactly as 4.3.1 | 1 version.

**Comment by konsolas** [comment]
While AAC does appear in the crash log, it seems that a lot of other things were also going on at the same time which may also have contributed to the crash.

Could you get a general timings report of your server running normally?

**Comment by Auntex** [comment]
Okay, I did a timings report of 3 minutes. Here it is https://timings.aikar.co/?id=1709dcfced344e95860ebf9a0743aeca#timings

**Comment by konsolas** [comment]
Seems like CMI's lag monitor is also doing some stuff.

In the meantime, please set move.async to true and let me know if this resolves the issue.
