### ISSUE TITLE
AAC Visual bypass

### ISSUE THREAD

**Issue by TheRealElonMusk** [konsolas/AAC-Issues#1835]
### Issue description

I am on Wurst client 1.14.4 v7.0pre18 on the test.kons.co test server and I am using Fullbright, MobSpawnESP, and PlayerESP w/out it detecting me

### Core information
**Server version**: 
1.14.4 I think
**AAC version**: 
Newest
**ProtocolLib version**: 

idk
**Plugin list**: 
AAC, Essentials, EssentialsSpawn, LiteBans, Luckperms, MineResetLite, Multiverse-core, OldConbatMechanics, ProtocolLib, ProtocolSupport, Shrug*, WorldEdit, WorldEditSelectionVisualizer, WorldGuard
### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: Idk

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

**Comment by TheRealElonMusk** [comment]
Why was this closed

**Comment by TheRealElonMusk** [comment]
oh... 

I'm dumb

**Comment by Janmm14** [comment]
AAC does not claim it can detect these cheats.
Additionally these cheats are undetectable.
