### ISSUE TITLE
1.15.x Swimming false positive.

### ISSUE THREAD

**Issue by sowhatifimlazy** [konsolas/AAC-Issues#1838]
### Issue description
Minecraft 1.15.x introduced a new mechanic when swimming. When you press your jump key, you will slowly ascend up to the surface, and when you press your crouch key you slowly descend into the water. When swimming and and pressing your crouch key, you flag timer and get pulled down to the bottom of the lake/pond/ocean instantly.

Video showing off the issue can be seen [here](https://streamable.com/ahvjo).
First part of the video shows an exempted player swimming to show how its supposed to function, the second part shows a normal player doing the same thing and getting flagged.

### Core information
**Server version**: 
Minecraft 1.15.1, git-Paper-26

**AAC version**: 
AAC version 4.3.3

**ProtocolLib version**: 
ProtocolLib version 4.5.0-SNAPSHOT-b439

**Plugin list**: 
AAC, and ProtocolLib.

### Special environment information
**ViaVersion version**:
n/a

**ProtocolSupport version**:
n/a

**ViaBackwards version**:
n/a

**BungeeCord plugins**:
n/a

### Configuration
Completely unedited.

**Comment by konsolas** [comment]
Verified to be an issue on 1.15 but not on 1.13 and 1.14

Looks like swimming mechanics changed slightly in 1.15
