### ISSUE TITLE
The plugin does not initialize

### ISSUE THREAD

**Issue by dasilvaj4** [konsolas/AAC-Issues#1839]
### Issue description
https://pastebin.com/3jWBqhVh
https://pastebin.com/hBFFyM4b
All errors that appears when startup server.

### Core information
**Server version**: Paper (MC: 1.14.4) 

**AAC version**: 4.3.3

**ProtocolLib version**: 

**Plugin list**:  ActionBarAPI, ActionHealth*, AdvancedBan*, AdvancedPortals, AntiCooldown, AsyncWorldEdit, AuthMe, BankCheque*, BlockParticles, BottledExp, BountyHunters, ChestShop, ChestSort, Citizens, ClearLag, CombatLogX, CommandNPC*, CoreProtect, CrazyAuctions, CrazyCrates, CropChecker, DeluxeMenus, Elevator, EntityTrackerFixer, EpicFarming, EpicHoppers, EpicRename, EpicSpawners, Essentials, EssentialsSpawn, EZBlocks*, FastAsyncWorldEdit, GSit, HackedCore*, HackedServer*, Harbor, HeadDatabase*, HolographicDisplays, IllegalStack, JDALibLoaderBukkit*, LagAssist, LimitPillagers, Marriage*, mcMMO, MeteoritesPro, Minepacks, MobFarmManager, Multiverse-Core, Multiverse-Portals, MyCommand, MyPet, NerfPhantoms, PermissionsEx*, PixelVip*, PlaceholderAPI*, Plan, PlayerWarps, ProtocolLib*, Quests, RedProtect, ShopGUIPlus, SimpleClans*, SkinsRestorer, TAB, TradeSystem, UltimateChat, UltimateFishing, UltimateStacker, UltimateStatistics, UltimateTimber, Vault, Votifier, VotingPlugin, WebSender*, Wild, WorldBorder, WorldEdit, WorldGuard

### Special environment information
**ViaVersion version**: None

**ProtocolSupport version**: None

**ViaBackwards version**: None

**BungeeCord plugins**: None

**Comment by Janmm14** [comment]
Use this as replacement for your marriage (reloaded) jar: https://github.com/Janmm14/Marriage/releases/tag/v2.0.20-SNAPSHOT
