### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by PlesCZ** [konsolas/AAC-Issues#1841]
Issue description
startup error = https://pastebin.com/dRtQDGqm

Core information
Server version: 1.8.8

AAC version: 4.3.4

ProtocolLib version: Latest

Plugin list: Doesn't matter

Special environment information
ViaVersion version: Latest

ProtocolSupport version: ??

ViaBackwards version: ??

BungeeCord plugins: ??

Configuration

**Comment by konsolas** [comment]
Please see the solution to #1809
