### ISSUE TITLE
[1.15] Weird flowing water false

### ISSUE THREAD

**Issue by sowhatifimlazy** [konsolas/AAC-Issues#1843]
### Issue description
Swimming up and down with flowing water above you in some cases will cause you to flag movement.Timer after a bit.

Video: [https://streamable.com/zomf7](https://streamable.com/zomf7)

I've also made a schematic out of the testing area in the video so you can test this.
Schematic download: [https://gofile.io/?c=5V3l2Z](https://gofile.io/?c=5V3l2Z)

**Note:** The schematic must be pasted in with 1.15.1 WorldEdit or it will break.

### Core information
**Server version**: Minecraft 1.15.1, git-Paper-29

**AAC version**: 4.3.4

**ProtocolLib version**: 4.5.0-SNAPSHOT-b439

### Special environment information
**ViaVersion version**: n/a

**ProtocolSupport version**: n/a

**ViaBackwards version**: n/a

**BungeeCord plugins**: n/a

### Configuration
Unmodified.

**Comment by konsolas** [comment]
AAC5
