### ISSUE TITLE
[Feature request] Config option to use cached permissions.

### ISSUE THREAD

**Issue by voodootje0** [konsolas/AAC-Issues#1846]
Currently, AAC checks permissions each tick for each online player. It would be great to simply cache the permission like AAC used to have. 

You could potentially hook into LuckPerms [UserDataRecalculateEvent](https://github.com/lucko/LuckPerms/blob/master/api/src/main/java/net/luckperms/api/event/user/UserDataRecalculateEvent.java) and refresh the cache for the specified user in the event.

**Comment by konsolas** [comment]
AAC5 only checks permissions on join now.
