### ISSUE TITLE
Closing doors while standing in them move false-positives

### ISSUE THREAD

**Issue by PinkLolicorn** [konsolas/AAC-Issues#1849]
### Issue description
Just close a doors couple of times while walking through them or standing in them and you will be blocked by massive setbacks.

![image](https://user-images.githubusercontent.com/44551064/71749999-5cbb8300-2e77-11ea-9676-e2225d519cfe.png)

[Raw logs](https://gist.github.com/PinkLolicorn/d313cda9ba65887ccbb481e2784ad075)

### Core information
**Server version**: Paper 1.15.1
**AAC version**: 4.3.4
**ProtocolLib version**:  4.5.0-SNAPSHOT-b439
**ProtocolSupport version**: 4.29-dev

### Configuration
I'm using default generated config.

**Comment by konsolas** [comment]
Merging with #1868
