### ISSUE TITLE
Falling blocks will bug you completly move false-positive

### ISSUE THREAD

**Issue by PinkLolicorn** [konsolas/AAC-Issues#1850]
### Issue description
When falling block falls at your head, good luck escaping it.

![image](https://user-images.githubusercontent.com/44551064/71751098-c0937b00-2e7a-11ea-8593-1dfe782863e7.png)

[Raw logs](https://gist.github.com/PinkLolicorn/50615fd147d0b8289687da769f95b8d6)

### Core information
**Server version**: Paper 1.15.1
**AAC version**: 4.3.4
**ProtocolLib version**:  4.5.0-SNAPSHOT-b439
**ProtocolSupport version**: 4.29-dev

### Configuration
I'm using default generated config.

**Comment by konsolas** [comment]
Merging with #1868
