### ISSUE TITLE
Trap doors are real trap now move false-positive

### ISSUE THREAD

**Issue by PinkLolicorn** [konsolas/AAC-Issues#1851]
### Issue description
Just click a couple of times to close/open trapdoor above you to shuffle between new 1 block height and normal mode.

![image](https://user-images.githubusercontent.com/44551064/71751409-ba51ce80-2e7b-11ea-86ac-69f09b398c2c.png)

[Raw logs](https://gist.github.com/PinkLolicorn/a1960c5488bddf69a726769ef690c426)

### Core information
**Server version**: Paper 1.15.1
**AAC version**: 4.3.4
**ProtocolLib version**:  4.5.0-SNAPSHOT-b439
**ProtocolSupport version**: 4.29-dev

### Configuration
I'm using default generated config.

**Comment by konsolas** [comment]
Merging with #1868
