### ISSUE TITLE
False positive with piston lift/contraption

### ISSUE THREAD

**Issue by Leonardo-Fiori** [konsolas/AAC-Issues#1854]
### Issue description
A video is the best way to describe the issue:
https://www.youtube.com/watch?v=dIWXlb3JY9Q

In a few words: use a redstone slime piston lifter

### Core information
**Server version**:  git-Paper-238 (MC: 1.14.4)

**AAC version**: AAC version 4.3.4

**ProtocolLib version**:  ProtocolLib version 4.5.0-SNAPSHOT

### Special environment information
**ViaVersion version**:  ViaVersion version 2.2.2

### Configuration
Using Celebrimbor's Ghost config. Latest version.

**Comment by konsolas** [comment]
Can you post logs of this issue from plugins/AAC/logs?

**Comment by konsolas** [comment]
Alternatively, a schematic of the piston contraption would also be useful.

**Comment by Leonardo-Fiori** [comment]
Here you go:
[redstone_quickfrost.log](https://github.com/konsolas/AAC-Issues/files/4038207/redstone_quickfrost.log)

Schematic:
https://drive.google.com/file/d/1QXKszDu9u5_Rc55nh3_sHtGNHJBkrFFk/view?usp=sharing

**Comment by Leonardo-Fiori** [comment]
Any news?

**Comment by Leonardo-Fiori** [comment]
It's more than a month.. I think that the issue is still here. I provided a schematic too. Any news?

**Comment by konsolas** [comment]
AAC5
