### ISSUE TITLE
False positive with a fast vanilla horse

### ISSUE THREAD

**Issue by Leonardo-Fiori** [konsolas/AAC-Issues#1855]
### Issue description
A video is the best way to describe the issue:
https://youtu.be/5hmiHECVn7w

In a few words: an user managed to breed a very fast horse. It gets detected as movement hack. In this clip the user does not manage to get kicked but it happens quite often. The horse is 100% vanilla.

### Core information
**Server version**:  git-Paper-238 (MC: 1.14.4)

**AAC version**: AAC version 4.3.4

**ProtocolLib version**:  ProtocolLib version 4.5.0-SNAPSHOT

### Special environment information
**ViaVersion version**:  ViaVersion version 2.2.2

### Configuration
Using Celebrimbor's Ghost config. Latest version.

**Comment by konsolas** [comment]
Please include relevant logs from plugins/AAC/logs

**Comment by Leonardo-Fiori** [comment]
Here is the log.. player is jobjob:
[horse.log](https://github.com/konsolas/AAC-Issues/files/4040444/horse.log)

**Comment by Leonardo-Fiori** [comment]
@konsolas
