### ISSUE TITLE
crash when reload

### ISSUE THREAD

**Issue by laelbe** [konsolas/AAC-Issues#1857]
PaperMC#34 (latest)
AAC-4.3.4 (latest)

[03:19:48 INFO]: [AAC] Attempting to inject into PlayerConnection
 A fatal error has been detected by the Java Runtime Environment:
 
  SIGSEGV (0xb) at pc=0x00007ff22da48fd8, pid=38110, tid=0x00007ff1d1145700
 
 JRE version: OpenJDK Runtime Environment (8.0_232-b09) (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
 Java VM: OpenJDK 64-Bit Server VM (25.232-b09 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 J 8081 C2 java.lang.StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder; (8 bytes) @ 0x00007ff22da48fd8 [0x00007ff22da48f80+0x58]
 
 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
 
 An error report file with more information is saved as:
 /home/minecraft/penguin/hs_err_pid38110.log
Compiled method (c2)   91278 8081       4       java.lang.StringBuilder::append (8 bytes)
 total in heap  [0x00007ff22da48e10,0x00007ff22da49780] = 2416
 relocation     [0x00007ff22da48f38,0x00007ff22da48f78] = 64
 main code      [0x00007ff22da48f80,0x00007ff22da493c0] = 1088
 stub code      [0x00007ff22da493c0,0x00007ff22da493e8] = 40
 metadata       [0x00007ff22da493e8,0x00007ff22da49420] = 56
 scopes data    [0x00007ff22da49420,0x00007ff22da49638] = 536
 scopes pcs     [0x00007ff22da49638,0x00007ff22da496f8] = 192
 dependencies   [0x00007ff22da496f8,0x00007ff22da49700] = 8
 handler table  [0x00007ff22da49700,0x00007ff22da49760] = 96
 nul chk table  [0x00007ff22da49760,0x00007ff22da49780] = 32
 
 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp

**Comment by Janmm14** [comment]
Please send /home/minecraft/penguin/hs_err_pid38110.log too

**Comment by hhmun** [comment]
https://www.dropbox.com/s/abngnxnyhiyutfa/bug-report.zip?dl=1
Here is crash log & some file.

How to reproduce error.
1. run paper-34.jar(latest version)  with  ProtocolLib(latest version) & AAC(latest version)
2. reload
3. reload confirm
4. error if lucky, crash if unlucky.

**Comment by laelbe** [comment]
https://www.dropbox.com/s/abngnxnyhiyutfa/bug-report.zip?dl=1
Here is crash log & some file.

How to reproduce error.
1. run paper-34.jar(latest version)  with  ProtocolLib(latest version) & AAC(latest version)
2. reload
3. reload confirm
4. error if lucky, crash if unlucky.

**Comment by Janmm14** [comment]
AAC does not support reloads.

**Comment by laelbe** [comment]
Not supported is good. But i think this should not make crash.

**Comment by konsolas** [comment]
Please do not attempt to reload AAC. The injection business is quite volatile.
