### ISSUE TITLE
LiquidBounce killaura bypass: new option RotationStrafe

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#1858]
### Issue description
LiquidBounce's killaura has a new option called 'RotationStrafe' (https://prnt.sc/qk4rgx) which is bypassing the killaura check. When disabled, it's being flagged by killaura.d1.

### Core information
**Server version**:  1.8.8 (Paper)
**AAC version**:  4.3.4

**Comment by BestMark** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/d070317105b2a45dae9e50306a9eab4ff4d13611
Sources of the option called _RotationStrafe_.

**Comment by konsolas** [comment]
New detection methods in v5
