### ISSUE TITLE
false positive when switch bow or food 

### ISSUE THREAD

**Issue by visionfutur** [konsolas/AAC-Issues#1859]
AAC; 4.3.4
video: https://streamable.com/zbk1w
the previous issue you said i enable sprint. but in this video i didn't enable sprint.

**Comment by Janmm14** [comment]
Why you don't just make a video without a cheat client?

**Comment by visionfutur** [comment]
I recorded it 1 week ago. So... 
if you want i can record again

**Comment by konsolas** [comment]
Duplicate of https://github.com/konsolas/AAC-Issues/issues/1722

This issue can't be fixed for 1.8 clients.
