### ISSUE TITLE
Speed works on slabs

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#186]
As said in the title if your position is y.5 blocks on a slab you can easily use most speed modes, especially low/bhops.

**Comment by Rqcco** [comment]
https://www.youtube.com/watch?v=pfcyCKVvp68

**Comment by Rqcco** [comment]
Works with AAC Speed on Synergy

**Comment by Janmm14** [comment]
This might also be an issue with other blocks from the block-edge list.

**Comment by konsolas** [comment]
Patched with the new NMS ground checking.
