### ISSUE TITLE
[4.3.4] Move false positive while legit bridge-building

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1860]
https://pastebin.com/08nJ0ifk
### Issue description
Video: https://youtu.be/cge_X3AdBtI
lizaveta_ put was scaffolding on BedWars mini-game. AAC removed the block under the player, and lizaveta_ got stuck. After that AAC teleported her to the void. It seems that the problem is relevant only for players with 150+ ping.

### Core information
**Server version**: 1.12.2

**AAC version**: 4.3.4

**ProtocolLib version**: 4.4.0

### Special environment information
**ProtocolSupport version**: latest build for 1.12.2

### Configuration
Default config from Celebrimor

**Comment by Janmm14** [comment]
Scaffolding as in cheating? Or legit bridge-building?

**Comment by BestMark** [comment]
@Janmm14, legit bridge-building, of course

**Comment by BestMark** [comment]
It happens only if the player have high ping (150+) and unstable internet connection. 
I think anti-cheat should be more careful with players with high ping.
Video: https://youtu.be/cge_X3AdBtI

**Comment by konsolas** [comment]
4.3.5 modifies how the move check handles block changes.

**Comment by Janmm14** [comment]
on behalf of BestMark
