### ISSUE TITLE
[4.3.4] KillAura C3 (T2) false positive

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1861]
https://pastebin.com/CcUyMfZn
### Issue description

Oni-chan was hitting another player immediately after another player respawned. AAC kicked him after killing a player ~5-10 times immediately after respawning.

### Core information
**Server version**: 1.12.2

**AAC version**: 4.3.4

**ProtocolLib version**: 4.4.0

### Special environment information
**ProtocolSupport version**: latest build for 1.12.2

### Configuration
Default config from Celebrimor

**Comment by konsolas** [comment]
This is almost certainly an autoclicker.
