### ISSUE TITLE
[4.3.4] Interact, BadPackets, FastPlace false positives while legit bridge-building

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1862]
Log: https://pastebin.com/9YUUVnva
### Issue description
YouTube video: https://youtu.be/Ym-bZ9EcHd4
### Core information
**Server version**: 1.12.2

**AAC version**: 4.3.4

**ProtocolLib version**: 4.4.0

**ProtocolSupport version**: latest

### Configuration
Celebrimor's config

**Comment by BestMark** [comment]
Please note that wool can be placed faster than other blocks. It is worth making an exception in the anti-cheat for the WOOL block.

**Comment by konsolas** [comment]
Do you have a source for that claim?

**Comment by konsolas** [comment]
No longer present on latest version.
