### ISSUE TITLE
[4.3.4] AAC Move false positive

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1863]
https://pastebin.com/cPVAjrx3
### Issue description
It happens when player jumps on whole blocks, for example, climbing stairs.
### Core information
**Server version**: 1.8.9
**Client version**: 1.12.2

**AAC version**: 4.3.4

**ProtocolLib version**: 4.4.0

**Plugin list**: 

### Special environment information
**ViaVersion version**: latest

### Configuration
Celebrimor's config

**Comment by konsolas** [comment]
Merging with #1867
