### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Royul2k** [konsolas/AAC-Issues#1864]
When starting up my server after I installed AAC my server crashes immediately. I can't post any logs from AAC because the AAC folder has not been generated because it crashed before it can.

Error: https://pastebin.com/X7ykrLrB

### Core information
**Server version**: 1.12.2 Paper Spigot

**AAC version**:  4.3.4

**ProtocolLib version**: 4.4.0

### Special environment information
**ViaVersion version**: ?? None

**ProtocolSupport version**: ?? None

**ViaBackwards version**: ?? None

**BungeeCord plugins**: ?? None

Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. None

**Comment by Janmm14** [comment]
AAC does only support OpenJDK / Oracle Java (or 100% compatible equivalents). Some hosters use the term "hotspot" to describe that JVM.
To change the java version on many hosters, go to their (advanced) settings and choose a compatible JVM asnd Java version. AAC does not support Java 7 or below.
