### ISSUE TITLE
Move false positives with high ping (> 300 ms)

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#1866]
### Issue description
If your ping is > 300 ms and you are fighting another player, you will keep on flagging move and eventually get setbacks / stuck in air. (https://streamable.com/p1wca)

### Core information
**Server version**:  1.8.8 (Paper)
**AAC version**: 4.3.4

**Comment by konsolas** [comment]
AAC5 waits up to 1000ms for velocity
