### ISSUE TITLE
[4.3.4] Move false positive while climbing stairs (video)

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1867]
### Issue description
It happens when player climbs stairs.
Verbose and detailed information on the video: https://youtu.be/zZQoexjkT9s
### Core information
**Server version**: 1.8.9
**Client version**: 1.12.2

**AAC version**: 4.3.4

**ProtocolLib version**: 4.4.0

**Plugin list**: 

### Special environment information
**ViaVersion version**: latest

### Configuration
Celebrimor's config

**Comment by sowhatifimlazy** [comment]
I can second this, happening on 1.15.x as well. Players complain about stairs and slabs all the time.

**Comment by konsolas** [comment]
AAC 5.0.0-pre15
