### ISSUE TITLE
AAC 4.3.5 inventory/crafting bugs and glitches

### ISSUE THREAD

**Issue by Leonardo-Fiori** [konsolas/AAC-Issues#1870]
### Issue description
Various inventory and crafting glitches started happening since i installed AAC 4.3.5. As soon as i reverted back to 4.3.3 they all almost disappeared.

Examples:
When shift+clicking items to make them go inside a chest, if they need to stack onto items of the same type already existing in the chest, sometimes, the action get's cancelled.

Some crafting recipes are broken. For example bone meal comes out of bones only if you put less than 64 bones in the crafting table.

Villagers trades are kinda bugged, you click them and they don't take all the required or available items (example take all of your carrots, they take only a small number).

Crafting recipes book is broken, it does not put items into the crafting table sometimes.

I wasn't personally able to reproduce the bugs with my OP account but i asked players to make some videos:

https://gyazo.com/990318dc2b31e28cd06bcf5fe1829fc8

https://media.giphy.com/media/LMR89tZ1EhMwV7jmoN/giphy.gif

https://media.giphy.com/media/WpCqJL3x2kXU9T8BM3/giphy.gif

Going back to AAC 4.3.3 fixed all the issues (made exception for the recipes book, it is still kinda broken they say)

### Core information
**Server version**: git-Paper-238 (MC: 1.14.4)

**AAC version**: AAC version 4.3.5

**ProtocolLib version**: ProtocolLib version 4.5.0-SNAPSHOT

### Special environment information
**ViaVersion version**: ViaVersion version 2.2.2

### Configuration
Celebrimbor's Ghost Config 4.3.5
I don't actually use AACAdditionPro (from what i know it checks inventory move patterns)

Log (actually nothing interesting here):
[aac_2020-01-10_11-51-26.log](https://github.com/konsolas/AAC-Issues/files/4045559/aac_2020-01-10_11-51-26.log)

**Comment by konsolas** [comment]
This is almost certainly not related to AAC.
It doesn't check or modify player inventories in any way.
