### ISSUE TITLE
Move false positive when walking next to blocks 

### ISSUE THREAD

**Issue by Floyaal** [konsolas/AAC-Issues#1871]
**Issue description**
Move (and sometimes timer) violations highly increase when you touch a block and walk next to it at the same time. https://youtu.be/ADtVBsg_nAU and https://youtu.be/5zUgoOVYYLQ

**Core information**
Server version: 1.8.8
Client version: 1.8.9
AAC version: 4.3.5
ProtocolLib version: 4.4.0

**AAC Configuration**
Celebrimor's config

**Comment by voodootje0** [comment]
I'm having similar issues with the exact same information as provided above.

This next video doesn't contain the AAC verbose output, but it show some important things such as moving near connected glass panes will have a higher chance of glitching. (See 1:29)
and getting glitched when you got knockbacked by someone else and got on a 2 block higher platform (see from 2:00). 

https://youtu.be/nnsVtMmpnmc
