### ISSUE TITLE
Critical phase issue

### ISSUE THREAD

**Issue by voodootje0** [konsolas/AAC-Issues#1872]
### Issue description
Some hacked clients are able to phase through the walls.
https://streamable.com/wm77f

### Core information
**Server version**:  PaperSpigot 1.8.8

**AAC version**: 4.3.4

**ProtocolLib version**:  4.4.0

### Special environment information
**ViaVersion version**: 2.2.2

### Configuration
https://haste.jartexnetwork.com/zakocehaxu.bash

**Comment by konsolas** [comment]
v5
