### ISSUE TITLE
Attacking blocks while moving false positives?

### ISSUE THREAD

**Issue by thehollowedone** [konsolas/AAC-Issues#1874]
### Issue description
https://pastebin.com/XHMgC2wi

Attacking blocks + Moving = Spamming move false positives

I have OldCombatMechanics installed, could that be why?
Spam left click on blocks while moving to re-produce.

### Core information
**Server version**: 
1.15.1 (Paper)
**AAC version**: 

**ProtocolLib version**:  4.5.0

### Special environment information
**ViaVersion version**: 2.2.2

**ProtocolSupport version**: N/A

**ViaBackwards version**: Latest

**BungeeCord plugins**:  ViaVersion, ViaBackwords, BungeeResourcepacks, Bot-Sentry, CleanMotD.

### Configuration
Using Celebrimbor's Config.

**Comment by konsolas** [comment]
Can't reproduce this one
