### ISSUE TITLE
[1.15.1] /reload crash

### ISSUE THREAD

**Issue by Insprill** [konsolas/AAC-Issues#1877]
### Issue description
 
Crash Log: https://pastebin.com/M3qNbQH0
Console: https://pastebin.com/dc0D1w2V

### Core information
**Server version**: 

**AAC version**: 

**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by Janmm14** [comment]
AAC does not support reloads.
