### ISSUE TITLE
Speed False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [konsolas/AAC-Issues#1878]
Issue description
If your on honey blocks and your moving and you jump you will false speed every single time
Also if you try to stack up with honey blocks you also false movement

Core information
Server version: Spigot 1.15.1

AAC version: 4.3.5

ProtocolLib version: 4.5.0

Plugin list: PermissionsEx, LunarClientAPI, Vault, BadlionClientCPSAPI, FastPot, BadlionClientModAPI, BadlionClientTimerAPI, ProtocolLib, Ram, AAC, Essentials

Special environment information

ViaVersion version: none

ProtocolSupport version: none

ViaBackwards version: none

BungeeCord plugins: none

Configuration
Default Nothing Changed At All

**Comment by konsolas** [comment]
Can't reproduce this. Furthermore, it's impossible to stack up with honey blocks due to the reduced jump height.
