### ISSUE TITLE
v3 Anti-Drown 

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#188]
Anti-Drown works fluently on the Synergy Client without any flags. I'm not sure if this is supported in AAC, so let me know.
 
Video of demonstration: https://www.youtube.com/watch?v=AhmsgdFEOBU

**Comment by v0idst4r** [comment]
I propose that this issue should be closed, such a mod is unpatchable since the client is stopping cpacketplayer packets when the player is underwater and not moving.

**Comment by Janmm14** [comment]
One could fake-recieve c3playerpackets if some are missing though.

**Comment by v0idst4r** [comment]
It's basically emulating lag

**Comment by Janmm14** [comment]
Filling the gaps with fake-packets would prevent this.
