### ISSUE TITLE
Elytra move false positives

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1882]
### Issue description
When walking and running with elytra there will be a huge amount of false positives

Video: https://youtu.be/DnLxgzaTz2w
Log: https://pastebin.com/nYxnDeXw

### Core information
**Server version**: 1.12.2

**AAC version**: 4.3.5

**ProtocolLib version**:  4.4.0

### Configuration
Cel-r

**Comment by Pesticidus** [comment]
This is recorded on the test server. Endless lagbacks when walking when wearing elytra.
https://youtu.be/JhWoJyQ_vxg

**Comment by konsolas** [comment]
Fixed in AAC5
