### ISSUE TITLE
[4.3.5] Hitbox false positive while sneaking

### ISSUE THREAD

**Issue by kjzl** [konsolas/AAC-Issues#1883]
### Issue description

**This Issue persists on any Server with Version 1.14+ and any Player using 1.8.x-1.13.x**
This obviosly happens because of the changed 1.5 Block tall Player Hitbox while sneaking and the changed line of sight, AAC expects you to have with 1.14 while sneaking.

1st way to reproduce (you are sneaking): https://youtu.be/ZcOpniiiz7Y

2nd way to reproduce (the other player is sneaking): https://youtu.be/Z6I6SG60Bmc

- Tested and recorded on Konsolas Test Server

### Core information
**Server version**: 1.14.4

**AAC version**: 4.3.5

**ProtocolLib version**: 4.5.0

### Special environment information

**ProtocolSupport version**: 4.29

**Comment by konsolas** [comment]
AAC5 5.0.0-pre16
