### ISSUE TITLE
[4.3.5] Interact false positive while sneaking

### ISSUE THREAD

**Issue by kjzl** [konsolas/AAC-Issues#1884]
### Issue description

**This Issue persists on any Server with Version 1.14+ and any Player using 1.8.x-1.13.x**
This obviosly happens because of the changed sneak behaviour and line of sight AAC expects you to have with 1.14.x

https://youtu.be/TQMx2SPXk3o

- Tested and recorded on Konsolas Test Server

### Core information
**Server version**: 1.14.4

**AAC version**: 4.3.5

**ProtocolLib version**: 4.5.0

### Special environment information

**ProtocolSupport version**: 4.29

**Comment by konsolas** [comment]
-pre21
