### ISSUE TITLE
[4.3.5] Interact false positive

### ISSUE THREAD

**Issue by kjzl** [konsolas/AAC-Issues#1885]
### Issue description

With 1.14.x the block hitbox of the bed has changed. Similar to other Block Hitbox changes from 1.13.x like for example the hopper (might be more blocks that have changed its hitbox in 1.14 or 1.13). This introduces a Interact false positive for players (1.8.x - 1.13.x) that dont see the different bed hitbox from 1.14 on 1.14 Servers.

https://youtu.be/TQMx2SPXk3o

- Tested and recorded on Konsolas Test Server

### Core information
**Server version**: 1.14.4

**AAC version**: 4.3.5

**ProtocolLib version**: 4.5.0

### Special environment information
**ProtocolSupport version**: 4.29

**Comment by konsolas** [comment]
5.0.0-pre21
