### ISSUE TITLE
Mcmmo -> AAC swords killaura fp

### ISSUE THREAD

**Issue by LogGits** [konsolas/AAC-Issues#1887]
### Issue description
MCMMO has a swords skill whereby it applies damage to entities in a bleeding out fashion. This causes higher levels of the swords skill to create almost instakick falsepositives saying:

"Player combat.hitbox: missed entity hitbox in attack [ping:247 tps 20.0]"
players with relatively low ping (e.g. 20-50) also experience this issue. 

A high level for our server is 400+ which would equate to level 40+ on a fresh install of mcmmo.
The attack is done with sweeps.
Example seen here:
https://gyazo.com/58dc3cf7994564d93c871aadfb9ca706

This eventually leads to a killaura kick.
**EDIT: pressing right click before sweep attacks (to toggle ability) causes instakick at swords level 423**
you can use `/mmoedit [player] swords 423` to easily change ur level

### Core information
**Server version**: 
1.15.2 paper build 87
**AAC version**: 
4.3.6
**ProtocolLib version**: 
4.5.1 build 445
**Plugin list**: 
mcmmo+aac+ paper+luckperms etc.

### Configuration
Cele's config

**Comment by konsolas** [comment]
AAC5 moves hitbox check to packet level.
