### ISSUE TITLE
Move false positives (nether bedrock)

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1889]
### Issue description

Video 3rd person (with chat verbose): https://youtu.be/QQUXyFmT-AQ
Video 1rd person: https://youtu.be/dm38KBTXGHI
Log: https://pastebin.com/3HGJjFi9

### Core information
**Server version**: 1.12.2

**AAC version**: 4.3.6

**ProtocolLib version**:  4.4.0

### Configuration
Default

**Comment by Pesticidus** [comment]
Video with verbose: https://youtu.be/OqcWwDUv7hY
Log: https://pastebin.com/nVVhf64C

### Core information
**AAC version**: 4.3.7
### Configuration
Default

**Comment by konsolas** [comment]
Fixed in AAC5 (bedrock was treated as a bed?)
