### ISSUE TITLE
Move false positives (bow shooting)

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1892]
### Issue description

Video 3rd person (with chat verbose): https://youtu.be/vYytmfZPE0w
Video 1rd person:  https://youtu.be/XQ6o32ko51Q
Log: https://pastebin.com/5h8YT0HW

### Core information
**Server version**: 1.12.2

**AAC version**: 4.3.6

**ProtocolLib version**:  4.4.0

### Configuration
Default

**Comment by Pesticidus** [comment]
Repeated + Timer false positives

Video with verbose: https://youtu.be/OQdyI5JEKFw
Log: https://pastebin.com/x8UX6WG7

### Core information
**AAC version**: 4.3.7
### Configuration
Default

**Comment by konsolas** [comment]
AAC5
