### ISSUE TITLE
Interact false positives (snow digging)

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1893]
### Issue description

Video 3rd person (with chat verbose): https://youtu.be/l2z356A7cn0
Video 1rd person:  https://youtu.be/SrnOUCmlKnM
Log: https://pastebin.com/5UEHQzBW

### Core information
**Server version**: 1.12.2

**AAC version**: 4.3.6

**ProtocolLib version**:  4.4.0

### Configuration
Default

**Comment by visionfutur** [comment]
This happened with slimeblock too

**Comment by konsolas** [comment]
aac5
