### ISSUE TITLE
Just Move false positives ( ¯\_(ツ)_/¯ )

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1895]
### Issue description
Players send a huge number of complaints about lagbacks ...

Video from player: https://youtu.be/hX4NPZLN4-Q
Video from server's replay (with chat verbose): https://youtu.be/VPm9yMxypQI
Log: https://pastebin.com/SKrRadgr

### Core information
**Server version**: 1.12.2

**AAC version**: 4.3.6

**ProtocolLib version**:  4.4.0

### Configuration
Cel-r

**Comment by Pesticidus** [comment]
One more

Video from player: https://youtu.be/dvXJvLx_17w?t=123
Video from server's replay (with chat verbose): https://youtu.be/IejomC7vbpI?t=356
Log: https://pastebin.com/JAnNCT6b

**Comment by mokdennie26** [comment]
I can confirm such issue. This is one of the severe defects found in the latest version of AAC. Lagbacks (setbacks) happened when a player is jumping for a long time just with speed potions. More lagbacks happened when they are engaged in long combats, receiving knockbacks. While receiving knockbacks, they appear to be lagging in a block or stuck in the mid air. If a player stays longer and plays in the pvp arena for a long time without dying, the move VLs built up to more than 10000 levels which cannot be mitigated.

**Comment by Pesticidus** [comment]
I think that problems appeared in update 4.3.1 most likely

**Comment by jakkuh** [comment]
On 1.12.2 Paper 1618 we are having the same issue where decay doesn't decay.

**Comment by mokdennie26** [comment]
> On 1.12.2 Paper 1618 we are having the same issue where decay doesn't decay.

Very true. The decay does not work. That is why the VL can build up to so high unless:
1. That player is kicked.
2. That player re-logged.

**Comment by mokdennie26** [comment]
> I think that problems appeared in update 4.2.4 (Yes, it is in this version 100%)

Confirmed. Downgrade to 4.2.1 seems to be a temporary solution.

**Comment by jakkuh** [comment]
We are using 4.2.3 without issue as it occurs in 4.2.4

**Comment by Shuowo** [comment]
Hello, i got the same problem with lagbacks and i tried using 1.8.9 where i got lagbacks and 1.10, no lagbacks

**Comment by konsolas** [comment]
#1905

**Comment by konsolas** [comment]
@Pesticidus unclear if this is directly related to every other move issue you've posted recently - i'll them locally and mark as appropriate.
