### ISSUE TITLE
to many problems with Advanced enchanments and so many false positives

### ISSUE THREAD

**Issue by anthony114669** [konsolas/AAC-Issues#1896]
### Core information
**Server version**: 

**AAC version**: 

**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by Janmm14** [comment]
missing details
