### ISSUE TITLE
[Urgent] AAC doesn't load/crashes server on Java Versions newer than Java 8 Build 241

### ISSUE THREAD

**Issue by train21** [konsolas/AAC-Issues#1897]
### Issue description
AAC doesn't load on Java Versions newer than Java 8 Build 241

**Do not use hastebin or other time-limited services to post your logs**
Suggested alternatives: https://gist.github.com or https://pastebin.com
AAC not loading on Java 8 Build 241 running on my laptop (console logs): https://pastebin.com/pqmE0Ubp
AAC crashing my server on my server host running Java 8 Build 242 (hs_err_pid42761 file): https://pastebin.com/3Y9wVVJy

**Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.**
So I woke up to my console writing over 1,500 error logs saying that it can't load AAC and I did some investigation. So I traced the error to be AAC crashing the server on boot, everytime I would try to start the server, it would crash and write an hs_err file which I have uploaded. My server host recently did an upgrade to their software which they had some maintenance done so Java on their end updated and then once the server restarted, it would be updated to the latest version of Java, which then made the server crash. I then went to see if AAC loaded on my localhost server which it did but I noticed my Java was outdated on Java 8 Build 221 so I updated it directly from the website and tried again to produce the error. Long and behold the same situation happened which AAC didn't load in. It didn't crash the server but it just would not load.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. -->

### Core information
**Server version**: 1.8.8 / 1.15.1

**AAC version**: 4.3.6

**ProtocolLib version**: 4.5.0

**Plugin list**: N/A

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

**Comment by Janmm14** [comment]
For now I suggest downgrading java 8 to a working version like 221. Konsolas is already informed about this problem and will investigate and fix the problem as soon as possible.

**Comment by Insprill** [comment]
for me it only happens on 1/8 servers. tried going to java 221 but it didn't work. also tried putting in a fresh .jar of aac and that didn't help either

**Comment by Janmm14** [comment]
Should be fixed in 4.3.8
