### ISSUE TITLE
Timer false positives in web (setbacks)

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1898]
### Issue description

Video 3rd person (with chat verbose): https://youtu.be/m6ufDNdq-xM
Video 1rd person:  https://youtu.be/TZ61NSA_MRU
Log: https://pastebin.com/NdbJXQZB

### Core information
**Server version**: 1.12.2

**AAC version**: 4.3.6

**ProtocolLib version**:  4.4.0

### Configuration
Default

**Comment by Janmm14** [comment]
likely fixed with aac 5
