### ISSUE TITLE
[Bug] Cobweb handling

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#19]
Cobweb handling (Speed check) is pretty much broken as "a bit slower than normal walking" -NoWeb modules easily bypass the check (it is not strict enough / bad default values)

**Comment by konsolas** [comment]
Cobweb handling has been written and is working on the test server.

**Comment by Janmm14** [comment]
Did you also blocked jumping on cobwebs?

**Comment by konsolas** [comment]
yes.

**Comment by Photon-GitHub** [comment]
Reopened due to a not functioning fix.
Horitontal movement is still not detected and I can use my noweb ("a bit slower than walking") and horizontal movement is patched a bit, but even with persistent jumping I cannot reach vls higher than 7.
Therefore I don't consider this patched -> reopen.

**Comment by konsolas** [comment]
Reduced limits and tested again. @Photon-GitHub reopen if you still experience problems on your client.
