### ISSUE TITLE
AAC works but 99% commands don't. Console says it does though.

### ISSUE THREAD

**Issue by Sedatte** [konsolas/AAC-Issues#1900]
Hello, today I bought AAC for the first time and when I imported the plugins into my plugins folder for both my KitPvP and Lobby the plugin worked in game but none of the commands worked but the following: /aac reload, staus, manage, notify, moderator, verbose, and banvl. Everytime I try to put in any other command it doesn't say "I don't have permission" it says "unknown command." But, when I check the console it says that the unknown commands are commands. Please fix this. Here are some pictures: https://imgur.com/a/ofr811e

Thank you and please fix this because that was all my money.

**Comment by Janmm14** [comment]
Plugin works as intended.
Not a problem of the plugin.
Support is given in discord after buyer verification. (Alternatively message Janmm14 on spigotmc for support if you don't have discord)
