### ISSUE TITLE
[Urgent] AAC doesn't load/crashes server on Java Versions newer than Java 8 Build 241

### ISSUE THREAD

**Issue by DebuffPvP** [konsolas/AAC-Issues#1902]
### 

Logs Link: https://pastebin.com/DTBDthNL

### Core information
**Server version**: 
This server is running CraftBukkit version git-TacoSpigot-bf023c7d (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**AAC version**: 
The latest one also aacplus by celebrimbor doesn't load either

**ProtocolLib version**: 
Protocollib version 4.5.0

### Special environment information
Latest viaversion

**Comment by yyunusyigit** [comment]
A different error type: https://hasteb.in/unokiwob.sql

**Comment by Janmm14** [comment]
@yyunusyigit That error is completely unrelated.

**Comment by Janmm14** [comment]
Some people do report AAC working on latest java 8 version btw

**Comment by DebuffPvP** [comment]
@Janmm14 so what can i do to fix this?

**Comment by Janmm14** [comment]
For now (ask to) downgrade to 8b232 hotspot

**Comment by konsolas** [comment]
Merging with #1897
