### ISSUE TITLE
AAC breaks java.net.ProxySelector.getDefault()

### ISSUE THREAD

**Issue by FaberoM** [konsolas/AAC-Issues#1904]
### Issue description
AAC causes default java.net.ProxySelector to be null and breaks any plugin using it. I am currently developing a plugin that uses java.net.ProxySelector.getDefault(), without AAC it returns default proxy and with AAC on the server it returns null and breaks the whole system.

### Core information
**Server version**: 1.15.2 (Paper-103)

**AAC version**: 4.3.6

**ProtocolLib version**: 4.5.0 (Also tried 4.5.1-SNAPSHOT-b445 problem still exists there)

**Plugin list**: N/A

### Special environment information
N/A

### Configuration
Using default config

**Comment by Janmm14** [comment]
As per javadoc it is allowed to use ProxySelector.setDefault(null)
https://docs.oracle.com/javase/7/docs/api/java/net/ProxySelector.html#setDefault(java.net.ProxySelector)
