### ISSUE TITLE
Decay not Working

### ISSUE THREAD

**Issue by jakkuh** [konsolas/AAC-Issues#1905]
### Issue description
We've been having issues with Players getting detected for Movement Elytra. I made the decay a lot more aggressive, but in testing it seems that the decay is not working at all for the Move check... There is another issue for this same bug.

Here's a capture of it not decaying. Decay is set as follows so should have started working immediately.

interval: 1
delay: 1
amount: 20

https://drive.google.com/a/linusmediagroup.com/uc?id=11I5NpUzIOSnFGGks_KwQWu4jGwIDgFFS

### Core information
**Server version**: Paper 1.12.2 Build 1618

**AAC version**: 4.3.6

**ProtocolLib version**: 4.5.0

### Configuration
<!--Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

**Comment by mokdennie26** [comment]
Very true. The decay does not work. That is why the VL can build up to so high unless:

That player is kicked.
That player re-logged.

Follow up: https://github.com/konsolas/AAC-Issues/issues/1895

**Comment by konsolas** [comment]
Relevant patch note in 4.2.4:
```The velocity component of Move can now check players who remain entirely stationary```

This was done by overriding the `tick` method in the move check. Unfortunately, decay is also managed in that tick method by a superclass of the move check. 

Fix: 
![image](https://user-images.githubusercontent.com/9408210/74836942-547cb180-5318-11ea-8b83-54912aeab3df.png)

(will be in 4.3.7)
