### ISSUE TITLE
Server could not load AAC

### ISSUE THREAD

**Issue by quickgk** [konsolas/AAC-Issues#1906]
### Issue description

Log:https://pastebin.com/8qJejgzL

### Core information
**Server version**: 1.12.2

**AAC version**: 4.3.7

**ProtocolLib version**:  4.3.0

### Special environment information
**ViaVersion version**: 2.1.0

**BungeeCord plugins**: BungeeTabListPlus-2.8.11

### Configuration

async: true

PLEASE DO NOT WRITE YOUR ISSUE DESCRIPTION HERE -->

**Comment by Janmm14** [comment]
1. AAC 4 is not compatible to server-wide reloads.

2. If you use Marriage plugin, please use the custom version with fixed AAC compatibility: https://github.com/Janmm14/Marriage/releases/tag/v2.0.20-SNAPSHOT

3. If you do not use Marriage plugin, please provide a list of plugins on your spigot server so we can look which plugin is loading PlayerConnection class before AAC attempts to load its on-the-fly-modified one.
