### ISSUE TITLE
Water falses timer in a certain setup.

### ISSUE THREAD

**Issue by True-cc** [konsolas/AAC-Issues#1908]
### Issue description

If the player is collided horizontally and in flowing water pushing him towards a wall, the player will start doing these mini hops. If you're completely submerged in water, it doesn't false, but if you're on like a slab and the water's pushing you into a wall, then aac will start falsing.
Video: https://cdn.discordapp.com/attachments/248520431986802688/680893414941917235/2020-02-22_13-44-51.mov

### Core information
**Server version**: 1.12.2

**AAC version**: AAC-4.3.6

**ProtocolLib version**: 4.5.0

**Plugin list**: Plugins (26): (working) AAC, AACAdditionPro, DiscordSRV, Essentials, EssentialsChat, FastAsyncWorldEdit, HolographicDisplays, HoloPlots, LuckPerms, MatrixPvPAPI, MatrixPvPChat, Multiverse-Core, PigsPlus, PingPlayer, PlaceholderAPI, PlotSquared, PlugMan, ProtocolLib, RideAnything, SkinsRestorer, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard, (not working) Multiverse-Inventories

### Special environment information
**ViaVersion version**: 2.2.3

**ProtocolSupport version**: n/a

**ViaBackwards version**: n/a

**BungeeCord plugins**: n/a

### Configuration

No changes.

**Comment by konsolas** [comment]
#1972
