### ISSUE TITLE
Kicking on death for flying

### ISSUE THREAD

**Issue by martinambrus** [konsolas/AAC-Issues#1909]
### Core information
**Server version**: PaperMC 1.15.2

**AAC version**: 4.3.6

**ProtocolLib version**: 4.5.0

**Plugin list**: AAC, AdminAnything*, AdvancedBan*, AutomaticInventory, AutoTool, BKCommonLib, ClearLag, CraftBook, CreatureCapture, DeadChest, dynmap*, FakaHedaMinequery*, FarmAssist, GriefPrevention, Gringotts, Herochat*, ItemStudio, KeepDeathDrop, Landlord, Landlord-DynMap, LoginSecurity*, LuckPerms, Maplands, OpenInv, PlaceholderAPI, PluginManager*, PremiumVanish, ProtocolLib, QuickBar*, Shop, SignEditor, SpawnerSilk, TeleportBack*, TreeFeller, UltimateStatistics, Vault, VeinMiner, ViaBackwards, ViaRewind, ViaVersion, WorldBorder, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

### Special environment information
**ViaVersion version**: latest DEV (3.0.0-SNAPSHOT)

**ProtocolSupport version**: -

**ViaBackwards version**: latest DEV (3.0.0-SNAPSHOT)

**BungeeCord plugins**: -

Default config.

When player dies on the server and MC freezes them at that point (possibly above the ground because it doesn't always happen), they will be kicked out by AAC for floating too long.

**Comment by konsolas** [comment]
AAC does not kick players with the message "Floating too long". 
This is the vanilla flight kick built into the server. 
You can disable this by setting allow-flight to true in server.properties.
