### ISSUE TITLE
AAC does not like flowing water and slabs.

### ISSUE THREAD

**Issue by True-cc** [konsolas/AAC-Issues#1910]
### Issue description

Just have flowing water and slabs and aac will false as demonstrated in this video.
Video: https://cdn.discordapp.com/attachments/248520431986802688/681201423056240710/2020-02-23_10-09-56.mov

### Core information
**Server version**: 1.12.2

**AAC version**: AAC-4.3.7

**ProtocolLib version**: 4.5.0

**Plugin list**: Plugins (26): (working) AAC, AACAdditionPro, DiscordSRV, Essentials, EssentialsChat, FastAsyncWorldEdit, HolographicDisplays, HoloPlots, LuckPerms, MatrixPvPAPI, MatrixPvPChat, Multiverse-Core, PigsPlus, PingPlayer, PlaceholderAPI, PlotSquared, PlugMan, ProtocolLib, RideAnything, SkinsRestorer, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard, (not working) Multiverse-Inventories

### Special environment information
**ViaVersion version**: 2.2.3

**ProtocolSupport version**: n/a

**ViaBackwards version**: n/a

**BungeeCord plugins**: n/a

### Configuration

No changes.

**Comment by konsolas** [comment]
AAC5
