### ISSUE TITLE
Slimeblock false positives

### ISSUE THREAD

**Issue by kjzl** [konsolas/AAC-Issues#1911]
### Issue description
When jumping on Slime blocks from certain hights with the client version 1.8-1.12 aac produces a false positive.
https://youtu.be/BgIY0idxons

### Core information
**Server version**: 1.14.4

**AAC version**: 4.3.7

**Comment by Xayanix** [comment]
Still not fixed at 5.0.14-b1.
https://youtu.be/oKv4bcwoE3I

False positive at 0:10.
