### ISSUE TITLE
false positives while stacking

### ISSUE THREAD

**Issue by kjzl** [konsolas/AAC-Issues#1912]
### Issue description
As shown in the video, when not standing completely still while stacking up will produce false positives. Even though this was recorded on the AAC-Test Server which is outdated, i can confirm this also happens on other servers with the newest 4.3.7 AAC Version.

https://youtu.be/kwp4J_UHdHE

### Core information
**Server version**: 1.14.4

**AAC version**: 4.3.7

**Comment by konsolas** [comment]
v5
