### ISSUE TITLE
moving + holding left click false positive

### ISSUE THREAD

**Issue by Insprill** [konsolas/AAC-Issues#1915]
### Issue description

When a player is moving + holding in left click, it triggers MAJOR false positives.

https://youtu.be/pPZLCUoXVVY

https://youtu.be/3Irsp7V7Bhw

https://youtu.be/qburx6IL-KA

### Core information
**Server version**: 
Paper 120 1.15.2
**AAC version**: 
4.3.7
**ProtocolLib version**: 
whatever the latest is as of 2/26/2020

### Configuration

Celebrimbor's Platinum InstaBan (with super high move min_vl because of this)

**Comment by BestMark** [comment]
I have problem

**Comment by konsolas** [comment]
Can't reproduce this. Does it happen without optifine?

@BestMark do you know if it's dependent on client version?

**Comment by Insprill** [comment]
it's super bad if you go up to a piece of grass. you can't move at all

**Comment by konsolas** [comment]
Still can’t reproduce this. Any plugins that might be interfering?

**Comment by Insprill** [comment]
Try going in the default spawn area. The 16 blocks. Looking closer at my vids it looks like it only happens in there

**Comment by konsolas** [comment]
Do you have spawn protection enabled in server.properties at 16?

**Comment by Insprill** [comment]
Yes

**Comment by konsolas** [comment]
I’ll be able to test this in a few hours - could you check if setting spawn-protection to 0 fixes this?

**Comment by konsolas** [comment]
Excellent - just tested and it seems like this **only** occurs when spawn protection is enabled, an operator is set on the server, and a checked player is inside the spawn protected region holding left click.

I'm currently not sure what the server is doing that causes this - for now a simple solution is to disable spawn protection which seems to completely fix the issue.

**Comment by konsolas** [comment]
Even without AAC installed, players holding left click while in a spawn protected area have their movement blocked by the server, as if they were being teleported around. The server also doesn't seem to fire a teleport event.

This seems to be a spigot issue rather than an AAC issue - disable spawn protection to resolve this.

**Comment by konsolas** [comment]
Turning off spawn protection is going to be the solution here.
