### ISSUE TITLE
API Feature Request

### ISSUE THREAD

**Issue by rxdn** [konsolas/AAC-Issues#1917]
Would it be possible to get an extra field in PlayerViolationEvent to tell whether a violation was mitigated or not. Would be helpful to me since I have my own cross-proxy notification system.

**Comment by konsolas** [comment]
AAC5 removes PlayerViolationEvent

**Comment by konsolas** [comment]
To exempt players, you can use AACAPI#addExemption (equivalent of cancelling events)

For notifications, you can set a command in the config which triggers your cross proxy notification when executed.
