### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by Xayanix** [konsolas/AAC-Issues#1919]
[01:09:43] [Server thread/INFO]: [AAC] Enabling AAC v4.3.7
[01:09:44] [Server thread/WARN]: [AAC] No internet connection
[01:09:44] [Server thread/WARN]: [AAC] Server will start in 20 seconds.

Please remove that thread sleep. It causes server startup a lot longer.

**Comment by Janmm14** [comment]
give your servers internet connection

**Comment by Xayanix** [comment]
Are u kidding me? I got internet connection

**Comment by Janmm14** [comment]
When why AAC says no?

**Comment by Xayanix** [comment]
Probably because of shit code or smth?
Like few days ago when i couldnt even use aac because of invaild server response. Whats the problem of removing that pointless thread.sleep?

**Comment by SenkJu** [comment]
As far as I know, a plugin that is sold on SpigotMC must be able to start without an internet connection anyway.

**Comment by Janmm14** [comment]
@SenkJu He did not complain that the plugin did not start
