### ISSUE TITLE
Attempting to inject into PlayerConnection...

### ISSUE THREAD

**Issue by amtgaming** [konsolas/AAC-Issues#1923]
### Issue description
https://pastebin.com/DdS6Zt6y

### Core information
**Server version**: Spigot 1.12.2

**AAC version**: 4.3.7

**ProtocolLib version**:  Newest

**Plugin list**:

### Special environment information
**ViaVersion version**: ViaVersion-2.2.2

**ProtocolSupport version**: 4.28

**ViaBackwards version**: viabackwards-all-2.4.0-SNAPSHOT

**ViaRewind version**: ViaRewind-1.4.5

### Configuration
Default

**Comment by Janmm14** [comment]
OpenJ9 is not supported. If you use some minecraft hosting, go to their (advanced) settings and select hotspot/oracle java 8 or above.
