### ISSUE TITLE
v3 Impossible Interact Block Bugs

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#193]
Attempting to place any type of block on the following blocks or subjects listed will cause ImpossibleInteract to flag.

- Brewing Stands
- Slabs
- Buttons
- Railroads
- Flowers Saplings etc.
- Flower Pots
- End Portal Blocks
- Carpet
- Stairs (Lower Part)
- Some layers of snow
- Trap Doors.
- Beds
- Redstone and Repeaters
- Enchantment Tables
- String
- Chests (Sometimes flag, not too much though)

Coding: ~~Fixed~~, **Needs testing**, Not completed.

(There may be more blocks, but these are the blocks I tested with)

Video: https://www.youtube.com/watch?v=JY9YAREi8UY

**Comment by Janmm14** [comment]
Probably an issue caused by the new impossibleinteract check.

**Comment by konsolas** [comment]
Can anyone check if more blocks need to be added to the above list? All solid blocks should be handled correctly; please test other blocks with nonstandard hitboxes.

**Comment by Janmm14** [comment]
* daylight detector

**Comment by konsolas** [comment]
General fix created for all of the above. Tested by myself.
