### ISSUE TITLE
move false positives

### ISSUE THREAD

**Issue by kjzl** [konsolas/AAC-Issues#1930]
### Issue description

With Client version 1.8.9 you get falsely flagged for jumping from high heights onto slime and walking over Grass Path blocks, which only exist since 1.9

### Core information
**Server version**: 1.14

**AAC version**: 4.3.8

**ProtocolLib version**: latest

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
Fixed in 5.0.3
