### ISSUE TITLE
AAC cannot be used with Marriage-Reloaded

### ISSUE THREAD

**Issue by XXY218** [konsolas/AAC-Issues#1931]
### Issue description
https://pastebin.com/v86LkEDk

### Core information
**Server version**: 1.15.2

**AAC version**: 4.3.8

**ProtocolLib version**: 4.5

**Plugin list**: [Marriage (Reloaded)](https://www.spigotmc.org/resources/marriage-reloaded-1-13-1-8.18998/) v2.0.19

**Comment by Janmm14** [comment]
Duplicate of #1378 (and a couple others).
Use https://github.com/Janmm14/Marriage/releases/tag/v2.0.20-SNAPSHOT
