### ISSUE TITLE
Phasing and Nuking

### ISSUE THREAD

**Issue by XXAOS** [konsolas/AAC-Issues#1933]
### Core information
**Server version**: 
1.8.8
**AAC version**: 
4.3.8
**ProtocolLib version**: 

**Plugin list**: 
![image](https://user-images.githubusercontent.com/42284153/77699730-25d5a480-6f70-11ea-8e5b-8898fe0be188.png)

### Special environment information
**ViaVersion version**: ??
2.2.3
**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

### Configuration

Nuking and .vclip phase with Liquidbounce and Huzuni are easily bypassed when the player is given fly. Its a big issue for me since almost everyone on my server has fly and nuking and phasing is a pretty big issue.

**Comment by Janmm14** [comment]
Intended. Many checks are finetuned for non-fly behaviour and disable in case a player is flying.

**Comment by XXAOS** [comment]
I know it is but it would be nice to be able to disable that.

**Comment by konsolas** [comment]
Unfortunately checking players with allowFlight is out of scope for AAC at the moment.
