### ISSUE TITLE
FastBreak bypass with Wurst.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1934]
1. Download Wurst for 1.15.2 (and fabric/fabric API that goes with it)
2. Run Fabric Launcher
3. Press right tab, search for "fastbreak"
4. Enable it
5. Farm Melons with this tool: https://i.imgur.com/WwBh4FD.png

We use swords for farming melons on our server.
(Axes are disabled from working on melons due to our setup/game type).

With the above pictured tool, melons should break after a few hits, however with the Wurst client & FastBreak, it is basically instant break. This was never an issue before, however due to a recent Wurst update it now seems to bypass AAC.

### Core information
**Server version**: 1.15.2 (Paper Build 161)

**AAC version**: 4.3.8

**AAC config**: 4.3.7/8|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.5.1 Build 447

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
Set tolerance back to its default value was suggested on Discord.

**Comment by andrewkm** [comment]
Thanks!

**Comment by andrewkm** [comment]
After testing this it seems the issue persists with the default value of 2.

**Comment by andrewkm** [comment]
@Janmm14 please put a label on this one.
The alt-solution is incorrect.

**Comment by ChiboYen** [comment]
@Janmm14 In relation to AAC5, this has not been resolved, check #2051

**Comment by konsolas** [comment]
FastBreak is detected after about 10 blocks broken on Wurst in AAC5.
