### ISSUE TITLE
Hitbox false positives

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1935]
### Issue description
This happens if you hit a player who runs and jumps under blocks

Video 3rd person (with chat verbose): https://youtu.be/aH07DGDTD5c
Video 1rd person:  https://youtu.be/jRixidDDvjQ
Log: https://pastebin.com/Aajs7jAC

### Core information
**Server version**: 1.12.2

**AAC version**: 4.3.9

**ProtocolLib version**:  4.4.0

### Configuration
Cel-r

**Comment by konsolas** [comment]
Any change if you increase hitbox.buffer_size to, for example, 20?

Additionally, does either player have AAC.bypass? AAC might not be able to check effectively if the player being attacked has AAC.bypass.

**Comment by Pesticidus** [comment]
I checked it through an account that does not have bypass and I couldn’t manage to repeat it. Therefore, the topic can be closed
