### ISSUE TITLE
Possible killaura false positive

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#1936]
### Issue description
Video: https://youtu.be/0IF6_ozJMsU
![image](https://user-images.githubusercontent.com/18399104/78774913-0d1cb400-799e-11ea-84bf-aeb8f8486496.png)

### Core information
**Server version**: Paper 1.12.2

**AAC version**: 4.3.9

**ProtocolLib version**: 4.5.0

### Special environment information
**ViaVersion version**: latest

**ProtocolSupport version**: latest

### Configuration
Celebrimor's config

**Comment by konsolas** [comment]
Can this be reproduced on 1.8 **.8** or above?
