### ISSUE TITLE
Move check having issues with cobwebs

### ISSUE THREAD

**Issue by Jpx3** [konsolas/AAC-Issues#1940]
### Issue description
https://youtu.be/vZtmlnQEI3k
https://youtu.be/mrjeNK0z1bo

### Core information
**Server version**: Spigot 1.8 

**AAC version**: 4.3.10

**ProtocolLib version**: N/A
**Plugin list**: N/A

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration

N/A

**Comment by kjzl** [comment]
When checking /AAC on GommeHD.net it reports a pretty old version of AAC. But anyway I still somewhat have problems with cobwebs in the newest version of AAC.

**Comment by Janmm14** [comment]
likely fixed with aac 5
