### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by PatoTheBest** [konsolas/AAC-Issues#1941]
### Issue description
There is a memory leak in AAC with worlds. I currently have a skywars plugin that loads and unloads many worlds, (each one being a random arena). It appears as a saved location is stored somewhere in AAC referencing the unloaded world. I've analyzed multiple heap dumps, in different server versions and they all report the same,

#### Loaded World
![Loaded World](https://media.discordapp.net/attachments/249828847229337601/699410617341182002/unknown.png)

Lots of references, as to be expected

#### Unloaded World
![Unloaded World](https://media.discordapp.net/attachments/249828847229337601/699410737239556136/unknown.png)

Here we can see how the only reference to the world is by AAC

#### Leak Suspects
![Leak Suspects](https://media.discordapp.net/attachments/249828847229337601/699435711757156412/unknown.png)

![Leak Suspect2](https://media.discordapp.net/attachments/249828847229337601/699435717159419924/unknown.png)

My guess is there is a WeakHashMap in the main listener class with players and locations, which doesn't properly get cleaned up

### Core information
**Server version**: 
Tested with git-Paper-161 (MC: 1.15.2), git-Paper-184 (MC: 1.15.2), latest TacoSpigot 1.8.8

**AAC version**:  4.3.10

**ProtocolLib version**:  4.5.1-SNAPSHOT-b445

**Plugin list**: SkyWars Plugin

### Special environment information
ViaVersion version: 3.0.0-SNAPSHOT

ProtocolSupport version: n/a

ViaBackwards version: n/a

BungeeCord plugins: (chat or actionbar plugins?) n/a

### Configuration
Optimized AAC config, tried with async move on and off.

**Comment by BestMark** [comment]
If you are using a SW plugin with multiworld support, try to move all the arenas into one world.
This problem has long existed in AAC.

**Comment by Xayanix** [comment]
I notice it too.

![image](https://user-images.githubusercontent.com/12672902/79623181-0ff47300-811b-11ea-8f4a-3d5b3b2f62f5.png)

![image](https://user-images.githubusercontent.com/12672902/79623192-1edb2580-811b-11ea-82b3-521e6e80988a.png)

**Comment by ninja-** [comment]
I explained to author several times why this WeakHashMap is leaking and he doesn't give a shit.
It's still the same bug for months and months.
You are creating a GC loop down the chain of references from AAC class holding player stats down to the player object again.
That's why it's not cleaned up even after there are no real references to CraftPlayer anymore.

**Comment by konsolas** [comment]
4.3.11-b1

**Comment by PatoTheBest** [comment]
@konsolas 
Memory leak is still present
4.3.11-b1

![memory leak](https://i.imgur.com/QgaI0nh.png)

**Comment by PatoTheBest** [comment]
@konsolas Hey! Do you have any news regarding the issue? And do you need any more information?

**Comment by konsolas** [comment]
Let me know how things go with 4.3.12

**Comment by PatoTheBest** [comment]
Initial findings show it is fixed. I'll wait one day before closing the issue in the unlikely event it appears.

**Comment by PatoTheBest** [comment]
@konsolas Everything is running great! It even runs more smoothly since GC is running less often. Thank you for the fix!
