### ISSUE TITLE
Move check not accounting for world borders

### ISSUE THREAD

**Issue by MrDsa1** [konsolas/AAC-Issues#1942]
### Issue description

Players can pass through barriers (see video). I am sure that this is AAC, because when you remove AAC, players can no longer pass through the barriers. The quick answer is very important to me, since it completely broke my SkyBlock (passing through the barriers some players managed to build outside of them). I tested different plugins for barriers, so the point is in AAC itself.
Video (Google Drive) - https://drive.google.com/drive/folders/1LNDAs-S0LmjsrLr9tt-A2KN2hTv_rSvi?usp=sharing

### Core information
**Server version**: CraftBukkit version git-Spigot-e8ded36-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**AAC version**:  AAC 4.3.5

**ProtocolLib version**: ProtocolLib v4.5.0

**Plugin list**: ASkyBlock, SkyBlock Border

### Special environment information
**ViaVersion version**: ViaVersion 2.2.2

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

### Configuration
Config - https://pastebin.com/VecJEKHm

**Comment by efekt** [comment]
The same issue occurs on Paper 1.15.2, build #194, AAC 4.3.10
https://youtu.be/HqFDA3B5xQ4
