### ISSUE TITLE
Inventory+ not supported

### ISSUE THREAD

**Issue by EvanSchleret** [konsolas/AAC-Issues#1943]
### Issue description
We can use inventory+ to store items on inventory crafting table : https://gyazo.com/c889e710e2dbd507ab9350e8099f4ea7

### Core information
**Server version**: latest spigot 1.14.4

**AAC version**: 4.3.10

**ProtocolLib version**: 

**Plugin list**: 4.5.0

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: no anti cheat plugin on bungeecord

### Configuration
We don't have modify default configuration.

**Comment by Janmm14** [comment]
AAC does not focus on inventory-related cheats.
