### ISSUE TITLE
Logging Thread Memory Leak

### ISSUE THREAD

**Issue by pkt77** [konsolas/AAC-Issues#1944]
### Issue description
Server running on 4GB with maybe 10 players max on at the same time.
A screenshot of the analyzed heap dump:
![image](https://user-images.githubusercontent.com/1795264/80181366-b7b5e900-85d2-11ea-8b76-72e49e5bf582.png)

### Core information
**Server version**: 1.15.2 Paper

**AAC version**: 4.3.10

**ProtocolLib version**: 4.5.0

**ProtocolSupport version**: Dev build #482

**Comment by PatoTheBest** [comment]
Seems to be related with my issue #1941

**Comment by pkt77** [comment]
> Seems to be related with my issue #1941

Not by the looks of the traces, and we don't unload worlds either - we only have 1.

**Comment by pkt77** [comment]
Maybe it's not directly related to logging, because something still leaks when logging is disabled:
![image](https://user-images.githubusercontent.com/1795264/80446326-8a27b300-88e4-11ea-9a18-710326c5e4a2.png)

**Comment by PatoTheBest** [comment]
> 
> 
> Maybe it's not directly related to logging, because something still leaks when logging is disabled:
> ![image](https://user-images.githubusercontent.com/1795264/80446326-8a27b300-88e4-11ea-9a18-710326c5e4a2.png)

My theory is the map contains locations of players and the player object itself, which isn't cleaned up properly. So when a player leaves the server, the whole player object is stored with location objects referencing the world. So in my case, it leaks memory from players and worlds.

**Comment by konsolas** [comment]
4.3.11-b1
