### ISSUE TITLE
Reach Check Suggestion

### ISSUE THREAD

**Issue by LoopTurn** [konsolas/AAC-Issues#1945]
This is just a suggestion, I think you should add a reach check. It could really help with preventing cheaters and prevent people from just using killaura. I think most anticheats have a reach check and nowadays it is essential for pvp based servers.

**Comment by Janmm14** [comment]
A reach check exists.

**Comment by LoopTurn** [comment]
> A reach check exists.



> A reach check exists.

weird, when I a friend tested it on me he was able to 6 block me

**Comment by WentilatorWentox** [comment]
The check is broken
