### ISSUE TITLE
Aristois Timer Bypasses AAC

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1946]
1. Download Aristois for 1.15.2
2. Enable Timer Hack
3. Farm Melons with this tool: https://i.imgur.com/WwBh4FD.png

We use swords for farming melons on our server.
(Axes are disabled from working on melons due to our setup/game type).

With the above pictured tool, melons should break after a few hits, however with the Aristois client & Timer hack, it is basically instant break and game play is extremely fast. This was never an issue before, however due to a recent Aristois update it now seems to bypass AAC.

### Core information
**Server version**: 1.15.2 (Paper Build 214)

**AAC version**: 4.3.10

**AAC config**: 4.3.10|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.5.1 Build 447

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by andrewkm** [comment]
@Janmm14 please put a label on this one.

**Comment by konsolas** [comment]
v5
