### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by ez-art** [konsolas/AAC-Issues#1951]
AAC will not boot/load if the number of plugins more than 47 plugins (48 with AAC)
i figure out the reason by removing random plugins and downgrade to older versions

**Server version**:  1.8
 
**AAC version**: 4.3.11-b1

**ViaVersion version**: 2.2.3

**Configuration**: Default

**Comment by Janmm14** [comment]
i am 100% sure that it is something different

**Comment by konsolas** [comment]
AAC5
