### ISSUE TITLE
Killaura Not Detecting

### ISSUE THREAD

**Issue by fangshenghan** [konsolas/AAC-Issues#1952]
### Issue description
New liquidbounce b71 hack client, when I turn on killaura(cps 20,range 8,all maxed) aac doesn't detect.

### Core information
**Server version**: 
PaperSpigot-1.8.8
**AAC version**: 
4.3.12
**ProtocolLib version**: 
4.4.0

**Plugin list**: 
Essentials PlaceholderAPI SuperVanish LiteBans Vault
### Special environment information
**ViaVersion version**: ??
2.1.3(bungeecord)
**ProtocolSupport version**: ??
no
**ViaBackwards version**: ??
no
**BungeeCord plugins**: ??
Viaversion Litebans
### Configuration
killaura:
  enabled: true

  modules:
    A1: 10
    A2: 10
    A3: 10
    A4: 10
    A5: 10
    A6: 45
    B1: 10
    B2: 0
    B3: 10
    B4: 10
    B5: 10
    B6: 6
    B7: 10
    C1: 5
    C2: 5
    C3: 5
    C4: 5
    C5: 5
    D1: 10

  decay:
    interval: 5
    delay: 10
    amount: 1

  mitigation:
    enabled: true
    min_vl: 100

  thresholds:
    50: "aac notify %aac_player% is exhibiting suspicious combat patterns (%aac_ping%ms, %aac_tps%TPS)"
    80: "aac notify %aac_player% is exhibiting very suspicious combat patterns (%aac_ping%ms, %aac_tps%TPS)"
    100:
      - "aac notify %aac_player% was suspicious combat patterns (%aac_ping%ms, %aac_tps%TPS)"
      - "banvl 1 %aac_player% Killaura"

**Comment by CeIebrimbor** [comment]
When you tested, was the hacked client attacking a staff member or account with the AAC.bypass (or OP) permission? Killaura detection will not function if the hacked client is attacking a player that has bypass.

**Comment by iConfueZ** [comment]
https://github.com/konsolas/AAC-Issues/issues/1858

**Comment by konsolas** [comment]
unlikely to still not be detected on aac5
