### ISSUE TITLE
ClubSpigot(fork) Incompatibility

### ISSUE THREAD

**Issue by Foulest** [konsolas/AAC-Issues#1953]
### Issue description
AAC is not compatible with either ClubSpigot or SpigotX.
Startup error: https://pastebin.com/raw/HVSfNqHW
Other anticheats, such as Spartan, NCP, and Verus, work perfectly fine.
I'd like to use AAC on these spigots, but I'm forced to use alternatives.

### Core information
**Server version**: ClubSpigot (fork of Spigot 1.8.8)
**Server download**: https://www.mediafire.com/file/7euc7joni5i6bhd/server.jar/file
**AAC version**: 4.3.12
**ProtocolLib version**: 4.5.0

### Special environment information
**ViaVersion version**: 2.2.3
**ViaRewind version**: 1.4.5

### Configuration
No modifications to default config.

**Comment by Janmm14** [comment]
Ask creators of clubspigot and spigotx to not load PlayerConnection class before plugins and ask them to not rename the packet movement method in that class as well as not modify the disrtance threshold for move event firing

**Comment by Foulest** [comment]
These spigots aren't being updated anymore. Hoping konsolas can look at this.

**Comment by BompIsTheBest** [comment]
> Ask creators of clubspigot and spigotx to not load PlayerConnection class before plugins and ask them to not rename the packet movement method in that class as well as not modify the disrtance threshold for move event firing.
> 
> I did not look at the server jar, these are general tips. Maybe konsolas can look at it later on and show what exactly failed.

yea guys my tips is to not make the spigot better. what a dummy you are

**Comment by dewgs** [comment]
Hello, Thank You For You're Inquiry About This PaperSpigot Fork (ClubSpigot). Due To The Nature Of How This Spigot Works, We Are Unable To Do This, We Would Be Sacrificing SO MANY TPS If We Died This.

**Comment by Janmm14** [comment]
Not a good idea to use an unmaintained fork.

For extended support please join our discord (and verify your ownership there).



> > Ask creators of clubspigot and spigotx to not load PlayerConnection class before plugins and ask them to not rename the packet movement method in that class as well as not modify the disrtance threshold for move event firing.
> > I did not look at the server jar, these are general tips. Maybe konsolas can look at it later on and show what exactly failed.
> 
> yea guys my tips is to not make the spigot better. what a dummy you are

You are dumb if you think that these advices would slow down your server.

**Comment by dewgs** [comment]
> Not a good idea to use an unmaintained fork.
> 
> For extended support please join our discord (and verify your ownership there).
> 
> > > Ask creators of clubspigot and spigotx to not load PlayerConnection class before plugins and ask them to not rename the packet movement method in that class as well as not modify the disrtance threshold for move event firing.
> > > I did not look at the server jar, these are general tips. Maybe konsolas can look at it later on and show what exactly failed.
> > 
> > 
> > yea guys my tips is to not make the spigot better. what a dummy you are
> 
> You are dumb if you think that these change requests to make heavily customized spigot compatible with AAC again would slow down your server.

The Server Uses A Custom DWORD And QWORD DataType Which Is More Optimizedlyed Garbage Collected And This Change Would Break it Severley.

**Comment by AgentManny** [comment]
Hello. As one of the creators of ClubSpigot, I don't believe we are able to change the PlayerConnection to suit your needs. With that being said, you have to make your anticheat plugin support it because we don't want to sacrifice significant TPS to suit your anticheat when we could instead use NoCheatPlus or other most advanced alternatives that don't require us to manipulate our PlayerConnection for a plugins need. 

Thank you
 - Agent of Manny
