### ISSUE TITLE
Fishing rod false positive. (BadPackets)

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1954]
1. Grab a fishing rod.
2. Make your minecraft use key "f"
3. Hold f while attacking a ghast. You will use your fishing rod so fast that it will kick you from the server for BadPackets.

AAC Logs: https://pastebin.com/raw/zZv8kJM1
This can be reproduced on the default minecraft client.
No special enchantments on the fishing rod.

### Core information
**Server version**: 1.15.2 (Paper Build 282)

**AAC version**: 4.3.12

**AAC config**: 4.3.12|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.5.1 Build 451

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by CeIebrimbor** [comment]
Seen similar detection for concrete machines (things that force you to interact fast when holding down your interact key).

**Comment by konsolas** [comment]
Tested, doesn't seem to happen in AAC5.
