### ISSUE TITLE
McMMO triggering AAC

### ISSUE THREAD

**Issue by Pugabyte** [konsolas/AAC-Issues#1955]
### Core information
![image](https://user-images.githubusercontent.com/12417961/81873574-06a7cc00-954a-11ea-85ca-6a75fc7c7796.png)

### Config
[config.yml](https://paste.bnn.gg/aac.yml)
[diffchecker.com](https://www.diffchecker.com/4VKED4fy)
Brief summary of changes: Most mitigation turned off, detection only, some thresholds raised.

[logs](https://paste.bnn.gg/raw/aac-logs)

(And no, my pastes dont expire)

### Issue
McMMO is triggering a couple different things in AAC
![image](https://user-images.githubusercontent.com/12417961/81873978-e0cef700-954a-11ea-9eba-a9939f131e97.png)

This may not be entirely McMMO as we aren't watching every player all the time, but we have tested ourselves and can pretty easily trigger it with giga drill. We also think McMMO's new sword ability "Rupture" (i think?) is triggering the "attcking out of their line of sight" (killaura) detection. But that seems to already be covered in https://github.com/konsolas/AAC-Issues/issues/1887

I found https://github.com/konsolas/AAC-Issues/issues/1676 and am not sure why I don't have the same fixes as @andrewkm. Maybe these compatibility issues were fixed in McMMO Classic? 

Some guidance would be appreciated, thank you!

**Comment by konsolas** [comment]
AAC5's hitbox check now works at packet level so shouldn't be affected by mcMMO
