### ISSUE TITLE
An illegal reflective access operations has occurred.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1958]
Startup warning:
https://i.imgur.com/SDLnLjk.png

### Core information
**Server version**: 1.15.2 (Paper Build 301)

**AAC version**: 4.3.12

**AAC config**: 4.3.12|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.5.1 Build 451

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Janmm14** [comment]
It is just a warning and there is no alternative available
