### ISSUE TITLE
NPE@h.a@PlayerInteractEvent 

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#1959]
Caught this error in console:
https://pastebin.com/raw/B6RDvD34

### Core information
**Server version**: 1.15.2 (Paper Build 301)

**AAC version**: 4.3.12

**AAC config**: 4.3.12|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.5.1 Build 451

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
AAC5
