### ISSUE TITLE
AAC Memory leak

### ISSUE THREAD

**Issue by PatoTheBest** [konsolas/AAC-Issues#1960]
### Issue description
This is a follow up with the Memory Leak Issue #1941,
Previously there was a memory leak related to player objects not being cleared up, which got patched and I'm having no issues with that.

Now there's another memory leak, but this one is related to world objects. 

#### Leak Suspects
![Leak Suspects](https://media.discordapp.net/attachments/262588738939387904/712509801107554354/unknown.png)

![Leak Suspect2](https://media.discordapp.net/attachments/262588738939387904/712509828156751923/unknown.png)

![Leak 3](https://media.discordapp.net/attachments/262588738939387904/712510065038590042/unknown.png)

![Leak 4](https://media.discordapp.net/attachments/262588738939387904/712510135985111090/unknown.png)

### Core information
**Server version**: 
git-TacoSpigot-"95870a93"

**AAC version**:  4.3.12

**ProtocolLib version**:  4.5.1-SNAPSHOT-b445

**Plugin list**: SkyWars Plugin, AAC, AACPlus, ConditionalCommands

### Special environment information
I'm currently using Slime-World Manager for loading and saving worlds from a SLIME format, the reason being it's much smaller in size and much faster to load and save. This also uses less RAM which allows our server to run for a longer period of time without running out memory. This does not modify anything else.

ViaVersion version: 3.0.0-SNAPSHOT

ProtocolSupport version: n/a

ViaBackwards version: n/a

BungeeCord plugins: (chat or actionbar plugins?) n/a

### Configuration
Optimized AAC config

**Comment by konsolas** [comment]
AAC5
