### ISSUE TITLE
PlayerViolationCommandEvent Not firing.

### ISSUE THREAD

**Issue by DocCodeSharp** [konsolas/AAC-Issues#1961]
### Issue description

When using a custom plugin to hook into the API the event `PlayerViolationCommandEvent ` is not firing. The other event PlayerViolationEvent works fine with no issues.

### Core information
**Server version**: 1.12.2 w/Via Version

**AAC version**: 4.3.12

**ProtocolLib version**: 

**Plugin list**: 4.5.0

### Special environment information
**ViaVersion version**: 2.2.3

**ProtocolSupport version**: 4.5.0

**Comment by konsolas** [comment]
Removed in AAC5
