### ISSUE TITLE
Add support for Geyser proxy

### ISSUE THREAD

**Issue by Leonardo-Fiori** [konsolas/AAC-Issues#1962]
Geyser proxy is an incredible piece of software that allows Bedrock clients to connect to Java edition servers. I can see a lot of servers using it in the near future, since it is approaching an almost complete release. It would be nice if AAC detected clients connected trough Geyser and added a compatibility to them. I think that other anticheats like Spartan already do that. If it is a possible addition you should totally do that :)

Here is the link to their GitHub
https://github.com/GeyserMC/Geyser

**Comment by konsolas** [comment]
5.0.0-pre16

**Comment by Mfweb** [comment]
> 5.0.0-pre16

When using the BungeeCord version of Geyser, AAC will still check the player.

**Comment by Janmm14** [comment]
@Mfweb You need to use Floodgate

**Comment by Mfweb** [comment]
> @Mfweb You need to use Floodgate

No, I'm using Floodgate

![aac](https://mimage.mfweb.top/blog/2020/12/aac5.jpg)
