### ISSUE TITLE
Move and Timer false positives with Iron Trapdoors and Slime Blocks

### ISSUE THREAD

**Issue by Wentoxic** [konsolas/AAC-Issues#1963]
### Issue description

If you jump under iron trap doors, under which there is a slime block, you are flagged for move and timer.

Video: https://www.youtube.com/watch?v=GtEul8oEzV8

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 4.3.12

**ProtocolLib version**: 4.5.0

**Comment by konsolas** [comment]
Merging with #2027
