### ISSUE TITLE
OP Mining Triggering A3 & B7 Killaura Checks

### ISSUE THREAD

**Issue by MrSwalbert** [konsolas/AAC-Issues#1965]
### Issue description
We're testing our configurations and noticed that a player mining with an **efficiency 10 pickaxe** (pretty much instant-break) constantly moving their head triggers the A3 & B7 killaura checks quite frequently. Also as you can see from the below, the `move` and the `timer` check has also been known to trigger, though this is not included in the below. The player was just moving around in a prison mine.
**Verbose:** https://pastebin.com/6pQxCTy9

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 4.3.12

**ProtocolLib version**: 4.5.1

### Special environment information
**ViaVersion version**: 2.2.3

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
I'm using Celebriminor's configuration.

**Comment by konsolas** [comment]
AAC5's killaura checks now properly determine if a player is breaking blocks.
