### ISSUE TITLE
NoFall false positives (Elytra Landing)

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#1967]
### Issue description

Video:  https://vk.com/video421407243_456239072
Log: https://pastebin.com/VNEXfkQU

### Core information
**Server version**: 1.12.2

**AAC version**: 4.3.11

**ProtocolLib version**:  4.4.0

### Configuration
Cel-r

**Comment by Janmm14** [comment]
paste was removed

**Comment by visionfutur** [comment]
@Janmm14 legit player can false flag nofall even fall < 3 block if you rotate head legit +stop quickly. konsolas doesn't fix it

**Comment by konsolas** [comment]
aac5
