### ISSUE TITLE
ProtocolLib errors

### ISSUE THREAD

**Issue by Axerr0** [konsolas/AAC-Issues#1968]
### Issue description

AAC throws protocollib errors in console
Console stacktrace: https://pastebin.com/t08XEh7M

### Core information
**Server version**: 1.15.2

**AAC version**: 4.3.11

**ProtocolLib version**: 4.5.0

**Plugin list**: 

### Special environment information
**ViaVersion version**: No ViaVersion plugin

**ProtocolSupport version**: No ProtocolSupport plugin

**ViaBackwards version**: No ViaBackwards plugin

**BungeeCord plugins**: No BungeeCord

### Configuration

Default configuration

**Comment by konsolas** [comment]
AAC5
