### ISSUE TITLE
Extreme Aimbot still working when KillAura checks are enabled.

### ISSUE THREAD

**Issue by UnrealPixel** [konsolas/AAC-Issues#1970]
### Core information
**Server version**: 1.12.2 Paper Spigot
**AAC version**: 4.3.12
**ProtocolLib version**: Latest (downloaded yesterday)

### Configuration
killaura:
  # Enable check? || true/false
  enabled: true
 
How much should AAC increase the violation level for each detection method?
These modules will appear in detection verbose.
A = aimbot/aimassist, B = killauras, C = autoclickers
  modules:
    A1: 10 #Default 10
    A2: 10 #Default 10
    A3: 10 #Default 10
    A4: 10 #Default 10
    A5: 10 #Default 10
    A6: 45 #Default 45
    B1: 10 #Default 10
    B2: 0 #Default 0
    B3: 10 #Default 10
    B4: 10 #Default 10
    B5: 10 #Default 10
    B6: 6 #Default 6
    B7: 10 #Default 10
    C1: 5 #Default 5
    C2: 5 #Default 5
    C3: 5 #Default 5
    C4: 5 #Default 5
    C5: 5 #Default 5
    D1: 10 #Defaul 10
 
Aimbot is still usable:
Video: https://streamable.com/56g95q

A bit extreme

Using Wolfram for Minecraft version 1.12.x

**Comment by respiter** [comment]
thats too far to track is my guess

**Comment by UnrealPixel** [comment]
Hmm
It is still a good reach for gamemodes like Quake etc.
And the lock is really extreme

**Comment by UnrealPixel** [comment]
Oh btw, range is 30 blocks of this aimbot from Wolfram

**Comment by konsolas** [comment]
new checks in aac5
