### ISSUE TITLE
Feature Request - Adding Ban Waves

### ISSUE THREAD

**Issue by ShreyasAyyengar** [konsolas/AAC-Issues#1973]
Hi there,

I was wondering if in the future AAC would be able to add a ban wave feature.

For example, as of the moment, there are vl levels and if they exceed that number in the config, a command will be executed. What could be really cool if instead, after the vl levels exceed you could add a command to move a player to the ban wave? for example /acc ban wave add/remove (player) (any other things you might want to add). And then in the config, you could add how often a ban wave happens, and what commands apply to whom. There could also be multiple ban waves, for example, one for hacking, one for chat abuse etc. So if there are 10 people on the ban wave and it is executed in like 30 seconds, in 30 seconds a certain command can be executed during the ban wave and the commands are different depending on what they are getting banned for. 

Just a thought,

Shreyas Ayyengar

**Comment by konsolas** [comment]
probably out of scope
