### ISSUE TITLE
1.16. + support?

### ISSUE THREAD

**Issue by ShreyasAyyengar** [konsolas/AAC-Issues#1974]
### Issue description
AAC not working for 1.16 +

Just wondering if 1.16 and above is supported with AAC. After I updated my server console and jars and everything AAC doesn't seem to be working. Is this because of 1.16 support not available? Commands also do not work such as /aac reload. /aac moderator, /aac verbose. As I try to do so, the chat gives me this message. 

/aac <reload|status|manage|notify|moderator|verbose|banvl>

I've tried reloading the plugin by deleting the jar and reinstalling it using the latest version from your spigot page, no success. 

### Core information
**Server version**: 
1.16.1

**AAC version**: 
4.3.12

**ProtocolLib version**: 
Not quite sure of the number but i know it is the latest. 

### Special environment information

**ViaVersion version**: 
3.0.1 Although playing on 1.16.1

**ProtocolSupport version**: ??
latest

**ViaBackwards version**: ??
3.0.1

Any solid answers will be greatly appreciated.

Shreyas Ayyengar

**Comment by Janmm14** [comment]
AAC needs to be updated for each minecraft server version. Running a 1.15.2 server with ViaVersion shjould make AAC handle 1.16 clients like 1.15 clients and probably provide relatively good compatibility.

**Comment by ShreyasAyyengar** [comment]
Ahhh okay. Will AAC be supporting 1.16 + anytime soon or should I stick to a via version 1.15.2 server?

**Comment by Janmm14** [comment]
I don't know

**Comment by konsolas** [comment]
There's still some work to be done on AAC 5 and we're also waiting for ProtocolLib at the moment.

**Comment by konsolas** [comment]
Late v4 + v5
