### ISSUE TITLE
AdvancedEnchantments Support

### ISSUE THREAD

**Issue by ShabbirSheeps** [konsolas/AAC-Issues#1976]
Hey there!

I would love if you guys could add support for AdvancedEnchantments. This is because some of the enchantments that AdvancedEnchantments provides don't work. For example, enchantments like Detonate which blows up blocks and the higher the level the more blocks it breaks. Pickaxes with that enchantment just don't work.

Thanks a lot.

**Comment by MrFlacko** [comment]
Has anything been done about this?

**Comment by Janmm14** [comment]
Compatibility might haveincreased with AAC 5, nothing special to this issue has been done however. retest needed

**Comment by konsolas** [comment]
wontfix - compatibility of other plugins is their responsibility
