### ISSUE TITLE
Detect FLy 

### ISSUE THREAD

**Issue by SharkblackFr** [konsolas/AAC-Issues#1978]
Hello,
I would like to know for a detection of the fly without necessarily that pause problem on the jumps with windows

**Comment by SharkblackFr** [comment]
?

**Comment by Janmm14** [comment]
What do you want exactly?

**Comment by SharkblackFr** [comment]
on jumps of this type this bug and tells me that it moves incorrectly
Screen on jump is impossible if "detect move is activated":
https://i.badlion.net/xufVoysodQVgZDSkdZWhzm.png

here is my configuration:
https://pastebin.com/Lrzn71v0

**Comment by SharkblackFr** [comment]
??

**Comment by konsolas** [comment]
This is probably multiversion since lone glass panes are either tiny poles or have 4 bits sticking out, depending on the client version.

**Comment by SharkblackFr** [comment]
our server is available 1.14.4 and higher but is there no way to prevent the fly

**Comment by SharkblackFr** [comment]
because it’s quite problematic

**Comment by konsolas** [comment]
Merged with #1697
