### ISSUE TITLE
Move and Timer Flags in Water

### ISSUE THREAD

**Issue by Wentoxic** [konsolas/AAC-Issues#1981]
### Issue description

Just rotate in water and spam space.

Verbose messages visible in the video

https://www.youtube.com/watch?v=--nzg5wRubE

### Core information
**Server version**: 1.7 - 1.16

**AAC version**: 4.4.0

**Comment by visionfutur** [comment]
Hmm just press space while in water?You will flag move many times

**Comment by konsolas** [comment]
v5
