### ISSUE TITLE
AAC crashes on startup.

### ISSUE THREAD

**Issue by mecray** [konsolas/AAC-Issues#1982]
### Issue description
When restarting (not reloading) the server, AAC does not start up and gives the following error: 
https://pastebin.com/ajqufxnv
### Core information
**Server version**: Paper 1.16.1

**AAC version**: 4.4.0

**ProtocolLib version**: 4.5.1

**Plugin List**:  

> AdvancedBan*, AdvancedHelp, ChatControl, Citizens, CommandNPC*, CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, HolographicDisplays, LuckPerms, MCLink*, Multiverse-Core*, NametagEdit*, NetherPortal*, OnePlayerSleep, PacketListenerApi*, PlaceholderAPI, ProtocolLib, RandomTeleport, ShopGUIPlus, SimplePortals, StaffPlus, SuperVanish, TabList, UltimateAutoRestart, Vault, VoidSpawn, WorldEdit, WorldGuard

**Comment by Janmm14** [comment]
I suggest that you open PacketListenerAPI jar with a zip tool and add this line to its plugin.yml file:
```yaml
softdepend: [AAC]
```

If that works, konsolas mght add something equal to AAC's plugin.yml file in future updates so you don't have to add this on PacketListenerAPI updates again.

**Comment by mecray** [comment]
I tried what you suggested with the PacketListenerAPI jar, however the same error still occurs. In fact, I ran the plugin in a test server with only AAC and ProtocolLib and I still get the same error. I tried Paper 1.16.1 and 1.15.2.

**Comment by Janmm14** [comment]
I'm sorry, I misread the log you sent.
It looks like AAC jar file was corrupted.
The most recent common cause for this is a virus in another plugin, which spreads into every plugin jar file of that specific minecraft server if the server does not run on windows.

1. Stop the server.
2. Redownload all plugin jar files. Do not download plugins from suspicious sources, as these are more likely to contain viruses. Let your server developers (if applicable) recreate all custom jar files or use the original jar file you got from them on your windows computer.
3. I highly suggest and recommend that you scan your plugins and especially any new plugins regulary with this Antimalware Tool (not a plugin!): https://www.spigotmc.org/resources/spigot-anti-malware-detects-over-200-malicious-plugins.64982/

**Comment by konsolas** [comment]
Malware.
