### ISSUE TITLE
Wearing Full Netherite Armour Triggers Move Checks (Assuming it's an antiKB check)

### ISSUE THREAD

**Issue by ShreyasAyyengar** [konsolas/AAC-Issues#1983]
### Issue description
On a 1.16.1 server, wearing full netherite armor and fighing people or creatures (like iron golems) trigger a move check and bans me too.

**Do not use hastebin or other time-limited services to post your logs**

Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

Use latest version of AAC, use any client (I am using badlion), wear full netherite armor and attack a golem, let the golem attack you for a while, it should trigger aac checks.

### Core information
**Server version**: 
1.16.1
**AAC version**: 
Latest
**ProtocolLib version**: v4.5.0 

**Plugin list**: 

### Special environment information
**ViaVersion version**: Latest

**ProtocolSupport version**: None

**ViaBackwards version**: Latest

**BungeeCord plugins**: N/A

### Configuration
Thresholds of a ban for the move check are at 1000.

**Comment by ShreyasAyyengar** [comment]
I might add that wearing netherite decreases KB

**Comment by konsolas** [comment]
Fixed in v5
