### ISSUE TITLE
aac shows license at /aac and a random letter

### ISSUE THREAD

**Issue by keksgauner** [konsolas/AAC-Issues#1985]
### Issue description
If you enter /aach for AdvancedAchievements for the help page. The license comes from aac (/aac). I suspect it is why /aac(h).
No matter if you just enter /aac and then a random letter, there are licenses e.g. /aaca - /aacb - /aacc
is it a bug or thought so?

### Core information
**Server version**: 
git-Paper-378 (MC: 1.15.2)
**AAC version**: 
4.4.0
**ProtocolLib version**: 
4.5.1

### Special environment information
**ViaVersion version**: Latest
**ProtocolSupport version**: None
**ViaBackwards version**: Latest
**BungeeCord plugins**: ??
Waterfall lastest
### Configuration
Not needed

**Comment by konsolas** [comment]
v5
