### ISSUE TITLE
[Bypass] Fly aac 4.X.X (critical thread)

### ISSUE THREAD

**Issue by visionfutur** [konsolas/AAC-Issues#1987]
### Issue description
This server is using latest aac 4.4.0 proof: https://m.youtube.com/watch?v=6fg3BOL7R5I&feature=youtu.be
Note: it work every server using aac 4.X.X

**Comment by Janmm14** [comment]
I think that unfortunaly this is not enough information for konsolas to fix it easily. If you can provide more details, this could really help tospeed things up.

**Comment by visionfutur** [comment]
Another proof server mineverse using aac 4.3.7: https://www.youtube.com/watch?v=Gld9FPL-Ehs&t=25s
unfortunately the code bypass is ofuscated. so i cannot access it to give you. 
More information:
i tested in official sv. it flag a bit first and then, force send packet position.(percent it doesn't work is 15% if sv lag)

**Comment by Janmm14** [comment]
you could send it me on discord. join aac discord and send it to janmm14. i am likely capable of deobfuscating

**Comment by TheFleksisCekcu** [comment]
xdlol its mine video

**Comment by konsolas** [comment]
AAC4 is no longer supported

**Comment by circleaac** [comment]
Can you bypass aac4push+！Emm...I need it！
