### ISSUE TITLE
glass fly false positive

### ISSUE THREAD

**Issue by SharkblackFr** [konsolas/AAC-Issues#1988]
hello,
I would like to know the fly is included in the category move?
The problem I use this anti cheat for the jump but I have effect blocks of the style that make jump higher and it counts as cheat
is there a way to solve this problem
same at the glass jump level it says the cheat players

**Comment by Janmm14** [comment]
"move" includes speed, fly, velocity, elytrafly and other cheats which alter movement

**Comment by SharkblackFr** [comment]
is it possible to fix the problem of Jump on glass. that it detects as a fly???

**Comment by Janmm14** [comment]
That is not easily fixable especially if you are using viaversion

**Comment by SharkblackFr** [comment]
> That is not easily fixable especially if you are using viaversion

that is to say how I could go about trying to settle?

**Comment by SharkblackFr** [comment]
I would like to know that represents  amount in decay
