### ISSUE TITLE
Soul Speed on Soul Blocks

### ISSUE THREAD

**Issue by ShreyasAyyengar** [konsolas/AAC-Issues#1989]
### Issue description

1.16 Nether: Using Soul Speed on boots when walking on soul sand or soul soil triggers false move checks. 

1. Install AAC on a 1.16+ server.
2. Enchant any boots with soul speed (1-3)
3. Find a soul sand valley and start sprinting.
4. You should be triggering false move checks.

### Core information
My server is running CraftBukkit version git-Spigot-379750e-82542d0 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**AAC version**: 
4.4.0

**ProtocolLib version**: 

4.6.0-SNAPSHOT-b476

n/a 

### Special environment information
**ViaVersion version**: 3.1.0

**ProtocolSupport version**: ??

**ViaBackwards version**: ??
3.1.0

**BungeeCord plugins**: ??
n/a

### Configuration

Using modified config (reduced violations)

**Comment by HexedHero** [comment]
You can use this as a temp fix for now
https://www.spigotmc.org/resources/aacnetherfixer-fix-aac-nether-false-positives.84136/
