### ISSUE TITLE
v3 Dropping down to Water bug

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#199]
Fly flags and accumulates when you drop down to water. (Sign Under Water) https://www.youtube.com/watch?v=b7x24xcnr3s

**Comment by Photon-GitHub** [comment]
Fixed, tested by myself.

**Comment by Photon-GitHub** [comment]
Again there.

**Comment by Rqcco** [comment]
This flags as nofall now and kills you. No fly violations.
