### ISSUE TITLE
Pressing right-click with a sword will flag move after opening/closing inventory

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#1990]
### Issue description
When pressing right-click on an entity which opens a menu, it will flag move after the menu is closed.
https://streamable.com/9hebdg

### Core information
**Server version**: 1.8.8

**AAC version**: 4.3.12

**ProtocolLib version**: 4.2.0

**Plugin list**: 
![image](https://user-images.githubusercontent.com/29337109/90562675-dacc6000-e1a2-11ea-8aa4-cc7f3aa0ab80.png)

### Special environment information
**ViaVersion version**: 

### Configuration
https://paste.ubuntu.com/p/pzGznCYr3g/

**Comment by ChiboYen** [comment]
Potentially due to never registering the close event for the GUI?

**Comment by Janmm14** [comment]
Video not available
And this is a client bug as it does not send unblock in some cases.
Workaround is to use villagers with non-NaN health.

Might be possible to account for this bug in AAC though.

**Comment by konsolas** [comment]
probably v5
