### ISSUE TITLE
aac.bypass permission does not bypass notifications

### ISSUE THREAD

**Issue by Leonardo-Fiori** [konsolas/AAC-Issues#1996]
### Issue description
Since this June Bedrock Edition Players can join my Java server thanks to an incredible piece of software called Geyser Proxy. Like me, other 2000 server owners are using Geyser as of now.

AAC has a lot of problems with bedrock players, it gets triggered LOTS of times, almost constantly. We could say that with 10+ bedrock players online it almost floods the chat from time to time, and bedrock players would get constantly kicked, if they did not have the permission aac.bypass.

For this reason i automatically give a LuckPerms group with the permission aac.bypass to everyone who plays from Bedrock Edition. This saves them from being kicked, but does not help at all my staff members that get constantly notified/flooded with messages from AAC.

**Solution A:**
aac.bypass permission bypasses also notifications and not only punishments for players

**Solution B:**
support for geyser proxy bedrock players

Of course solution B would be the real solution, since solution A is only about hiding the real problem. But i understand that it would take time to implement. Instead, a simple bypass for notifications won't take so much effort.

**Comment by konsolas** [comment]
This was resolved on discord.
