### ISSUE TITLE
Massive TPS Drops

### ISSUE THREAD

**Issue by unholymac** [konsolas/AAC-Issues#1997]
### Issue description

AAC Logs - https://gist.github.com/unholymac/d393481d35e689a73b975c65e240c2ec

Getting massive tps drops to 10 my host says its the anti cheat and as soon as i disable it im back to 20tps all the time im not sure what you guys can do to fix it? even when i turn off all the checks it still drops it so i had to remove the plugin until it gets fixed quite upsetting since it costed me £20 and no reply in the discord server :(

Timings report - https://timings.aikar.co/?id=8a4ea7428a5145178a3b1b221fd5c9a0

### Core information
**Server version**:  1.15.2

**AAC version**: 4.4.1

**ProtocolLib version**: 4.5.1

**Plugin list**:  
eglow
nuvotifier
Quickshop
TAB
Head Database
Voting Plugin
Advanced Achievements
ConditionalCommands
AAC Plus
GadgetsMenu
AuctionHouse
BeastWithdraw
Core protect
entity tracker fixer
featherboard
grief prevention flags
harbor
mvdwplaceholder
protocollib
ShopGUI+
SuperVanish
Trade
Ultimate Stacker
Ultra Cosmetics
Ultra Permissions
World Edit
grief prevention
essentials X
DiscordSRV
AdvancedBan
EZColors
SUMO
King of the Hill
jobs reborn
Vault
SuperTrails
plotsquared
BuyCraft
ClearLagg
Crazy Crates
Deluxe Menu
Deluxe Tags
Holographic displays
item in chat free
Multiverse core, inventories, netherportals
placeholderAPI
reserve
Via Version
wild
WorldGuard

### Special environment information
**ViaVersion version**: 3.1.0

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

### Configuration
https://gist.github.com/unholymac/1da110d763835895ac7120d9c2d2c450

**Comment by unholymac** [comment]
https://timings.aikar.co/?id=957e69f7c3a84a65a2bca7662ade7ef6

**Comment by unholymac** [comment]
Still getting massive drops! what can i do to fix this?

**Comment by unholymac** [comment]
Heya its almost been a month since ive had a reply is this ever going to be fixed or have i wasted £20? 

https://timings.aikar.co/?id=e2a5c8fa63b64146bfda8c9e93098c14

**Comment by unholymac** [comment]
Im still getting massive tps drops!!! when i turn off checks its fine, have i wasted my money on this plugin because i haven't had a reply in nearly 2 months!!!!!!!!!!!!!!!!!

**Comment by konsolas** [comment]
AAC5 improves performance
