### ISSUE TITLE
Climbing nether vines, when adjacent to blocks, causes false flags; players constantly teleport back to ground

### ISSUE THREAD

**Issue by Sabinno** [konsolas/AAC-Issues#1998]
### Core information
**Server version**: 1.16.2

**AAC version**: 4.4.1

**ProtocolLib version**: 4.5.1

**Plugin list**: AAC, AltDetector, BanItem, CombatLogX, CooldownsX, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, LogBlock, LuckPerms, Mineman, NameHide, ProtocolLib, RandomSpawnPlus, Reinforcement, StopShulkers, SuperTracerBlocker, TCPShield*, ViaVersion, WorldEdit

### Special environment information
**ViaVersion version**: 3.1.1 (supports 1.16.3)

### Configuration

https://www.diffchecker.com/3hHhWlcD

### Issue description
When players climb nether vines that are adjacent to blocks, AAC throws false flags and teleports them back to the ground constantly. This happens very consistently and is easily reproducible. I will gather more evidence soon, but I wanted to go ahead and report this. I think AAC causes this issue because the teleportation happens immediately as soon as AAC throws a warning about a player doing something fishy, though they're just climbing long nether vines adjacent to blocks.

It seems nether vines work as intended when there are no adjacent blocks.

**Comment by ChiboYen** [comment]
Use protocolLib version 4.6.0 dev builds, its made for 1.16

**Comment by HexedHero** [comment]
Just update to 1.16.3 as well. Nothing will break.

**Comment by HexedHero** [comment]
You can use this as a temp fix for now
https://www.spigotmc.org/resources/aacnetherfixer-fix-aac-nether-false-positives.84136/
