### ISSUE TITLE
Illegal reflective access

### ISSUE THREAD

**Issue by TheGreyRaven** [konsolas/AAC-Issues#1999]
### Issue description
When I start my server everything works without issue but I noticed one warning that the console threw:
```
[16:46:36 INFO]: [AAC] Attempting to inject into PlayerConnection
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.konsolas.aac.J (file:/E:/mcserver/plugins/AAC-4.4.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of me.konsolas.aac.J
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[16:46:37 INFO]: [AAC] Successfully injected.
```
I don't know if this is a known "issue" but I thought it might be a good idea to bring it up!

### Core information
**Server version**: 1.16.3

**AAC version**: 4.4.1

**ProtocolLib version**: [Latest Dev Build #480](https://ci.dmulloy2.net/job/ProtocolLib/480/)

**Plugin list**: 
* AAC
* GlowAPI
* LoneLibs
* LuckPerms
* PacketListenerAPI
* ProtocolLib
* RealisticWorldGenerator
* ServerBooster
* SmoothTimber

### Special environment information
**ViaVersion version**: None

**ProtocolSupport version**: None

**ViaBackwards version**: None

**BungeeCord plugins**: None

### Configuration
No modifications has been made.

**Comment by Janmm14** [comment]
That is only a warning you can ignore.

**Comment by TheGreyRaven** [comment]
Ah okay thank you!
