### ISSUE TITLE
v3 Jesus works while taking damage

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#200]
When damaging your self (via poison or anything else) while having the Jesus hack on, you can travel on water fluently without any Jesus flags. You do get a few speed violations but the violations aren't servere enough to flag (aacnotify) or to kick you. (Standing still and not sprinting gives close to no violations) Without damaging yourself, you get normal Jesus flags. https://www.youtube.com/watch?v=Nvq5tj5wr5s

**Comment by Rqcco** [comment]
If you feel this is very minor compared to other issues at the moment, feel free to label it unimportant.

**Comment by geNAZt** [comment]
Does this also work with self damage via PacketUseEntity?

**Comment by Janmm14** [comment]
@genazt Selfdamaging with hitting yourself has been patched in vanilla in 1.8 or before as far as I know.
