### ISSUE TITLE
AAC move false positive (noslow)

### ISSUE THREAD

**Issue by crimilo** [konsolas/AAC-Issues#2000]
### Issue description

when using a bow and spamming with it u get kicked for fastbow, but the main problem is that if u spam with bow while moving u get detected for move. type /aac verbose to see the false positives. there are a lot.
EDIT: to replicate the bug as best as possible, run in diagonal while spamming with the bow.

### Core information
**Server version**: PaperSpigot 1.8.8

**AAC version**: AAC 4.4.2

**ProtocolLib version**: ProtocolLib 4.5.1

**Plugin list**: not required to replicate the issue

### Special environment information
**ViaVersion version**: not required to replicate the issue

**ProtocolSupport version**: not required to replicate the issue

**ViaBackwards version**: not required to replicate the issue

**BungeeCord plugins**: not required to replicate the issue

**Comment by Janmm14** [comment]
Next time, please make sure that your capslock key is off. Thanks.

**Comment by konsolas** [comment]
v5
