### ISSUE TITLE
aac doesn't launch due to error

### ISSUE THREAD

**Issue by DebuffPvP** [konsolas/AAC-Issues#2002]
### Core information
**Server version**: 
This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**Server Log**: 
https://pastebin.com/HMUKMRi2

**AAC version**: 
the newest

**ProtocolLib version**: 
4.5.1
**Plugin list**: 

### Special environment information
**ViaVersion version**: ??
newest version

**ProtocolSupport version**: ??
i dont use this

**ViaBackwards version**: ??
newest version

**BungeeCord plugins**: ??
i dont use bungee

### Configuration
none

PLEASE DO NOT WRITE YOUR ISSUE DESCRIPTION HERE -->

**Comment by konsolas** [comment]
aac5 no longer injects stuff and can be loaded by plugman
