### ISSUE TITLE
AAC version bug

### ISSUE THREAD

**Issue by crimilo** [konsolas/AAC-Issues#2004]
### Issue description

On server startup i get a message saying "A new version of AAC is avaibable" when im using the latest version

### Core information
**Server version**: 1.8.8 Paper

**AAC version**: 4.42

**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
Fixed
