### ISSUE TITLE
Anvil movement false positive

### ISSUE THREAD

**Issue by crimilo** [konsolas/AAC-Issues#2005]
### Issue description

If you try to jump/glitch on/into anvils, aac will flag you for move. This is VERY annoying for kitpvp/factions server with a repair zone with anvils.

### Core information
**Server version**: 1.8.8 Paper

**AAC version**: 4.4.2

**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
This is a vanilla 1.8.8 bug
