### ISSUE TITLE
AAC false positive timer/move

### ISSUE THREAD

**Issue by crimilo** [konsolas/AAC-Issues#2006]
### Issue description

If u get into a cactus and walk around it while getting damage aac will flag u for move/timer.

### Core information
**Server version**: 1.8.8 Paper

**AAC version**:  4.4.2

**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
Timer check gone in AAC5
