### ISSUE TITLE
Killaura C3 False positive

### ISSUE THREAD

**Issue by crimilo** [konsolas/AAC-Issues#2007]
### Issue description

Just jitterclicking you get flagged for killaura C3. You basically can't do more than 9-10 CPS. Usually good pvpers jitterclick at 13-14 cps. 

### Core information
**Server version**: 1.8.8 Paper

**AAC version**: 4.4.2

**ProtocolLib version**: 4.5.1

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
No longer an issue in aac5
