### ISSUE TITLE
Interact False Positive

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#2008]
Logs: https://pastebin.com/Kvm88ZUA

Video link: https://www.youtube.com/watch?v=-5JQvAfG6B0&feature=youtu.be
Description: When breaking crops and moving your mouse from side to side it sets off interact false positives. 

### Core information
**Spigot 1.16.3** 

**AAC 4.4.2**

**ProtocolLib version 4.6.0-SNAPSHOT-b480**

**Plugin list**: 
Plugins (15): LuckPerms, Citizens, WorldEdit, AsyncWorldEdit, Denizen, Essentials, ViaVersion, ViaBackwards, ProtocolLib, WorldGuard, AAC, BKCommonLib, AACAdditionPro, ConditionalCommands, LightCleaner

### Special environment information
**ViaVersion 3.1.1**

**ProtocolSupport version: Not installed**

**ViaBackwards version 3.1.1**

**BungeeCord plugins: None**

### Configuration
Config is default aside from some changed thresholds.

**Comment by konsolas** [comment]
aac5
