### ISSUE TITLE
Soul Speed FP

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#2009]
Logs: https://pastebin.com/t2SF16ig

Video link: https://youtu.be/NeNt5gt4_X8

Description: When sprint jumping with soul speed (I, II, or III) you will flag move. Also happens when running onto a block that isn't affected by soul speed after being on soul sand or soul soil.

Extra info: Client is modded with fabric but there shouldn't be anything there that would affect something like this.

### Core information
**Spigot 1.16.3** 

**AAC 4.4.2**

**ProtocolLib version 4.6.0-SNAPSHOT-b480**

**Plugin list**: 
Plugins (15): LuckPerms, Citizens, WorldEdit, AsyncWorldEdit, Denizen, Essentials, ViaVersion, ViaBackwards, ProtocolLib, WorldGuard, AAC, BKCommonLib, AACAdditionPro, ConditionalCommands, LightCleaner

### Special environment information
**ViaVersion 3.1.1**

**ProtocolSupport version: Not installed**

**ViaBackwards version 3.1.1**

**BungeeCord plugins: None**

### Configuration
Config is default aside from some changed thresholds.

**Comment by konsolas** [comment]
v5
