### ISSUE TITLE
1.16.3 Lava Swimming Issues.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2010]
Swimming/moving in lava, most notably flowing lava, results in the player having glitchy movement.

Instructions:
- Be in nether(?)
- Drink fire res. potion
- Walk/swim into lava
- Attempt to escape lava either by walking or jumping/spacebar

During this report the following AAC logs can be found:
https://pastebin.com/raw/3URF06g8

Original report: https://ecocitycraft.com/forum/threads/vmr-bug-report-lava-swimming-bugged.204101/
Video from report: https://www.youtube.com/watch?v=5uLDxQWUr94

### Core information
**Server version**: 1.15.2 (Paper Build 301)

**AAC version**: 4.4.2

**AAC config**: 4.4.1|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.6.0 Build 480

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by ClayCoffee** [comment]
Confirmed

**Comment by konsolas** [comment]
5.0.0-pre10
