### ISSUE TITLE
Killaura and Move False Positives (important)

### ISSUE THREAD

**Issue by crimilo** [konsolas/AAC-Issues#2011]
### Issue description

When attacking, blocking and sprinting forward at the same time you get flagged and kicked in few seconds with default config.
This is an important bug and it should be in the priority list.
Here's a video showing it: https://youtu.be/8wX0T_Lvpd8
Here's the log of the video: https://pastebin.com/jHWvU9Zx
EDIT: Looks like that when you use shift + right click on the player (sometimes), AAC thinks you're still blocking and even if you walk normally it flags you (for noslow i guess). To fix it u have to right click again. Here's another video: https://youtu.be/GGAx1jw8QHk.
I had this issue not only right clicking a player but also interacting with NCP's (not villagers NPCs) and other things (such as opening custom inventories with right click having a sword in hand). This is the major AAC issue i've found.

### Core information
**Server version**: 1.8.8 Paper

**AAC version**: 4.4.2

**ProtocolLib version**: 4.5.1

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
v5
