### ISSUE TITLE
Question - Security Manager

### ISSUE THREAD

**Issue by bobhenl** [konsolas/AAC-Issues#2013]
Hi, why is Security Manager in AAC needed? And couldn't I disable it somehow? Cause my hosting provider uses it for security and plugin won't load.... And they can't change it especially for my server, when it's for bunch of servers.

**Comment by Janmm14** [comment]
AAC requires that there is no security manager present as security managers can easily interfer with DRM.

**Comment by Volgeop** [comment]
And could it be solved somehow if hosting doesn't wanna turn their Security Manager off?

**Comment by konsolas** [comment]
5.0.0-rc (maybe?)
