### ISSUE TITLE
Movement setback problem

### ISSUE THREAD

**Issue by SwagPancakes** [konsolas/AAC-Issues#2014]
### Issue description

The setback doesn't work properly on minecraft versions 1.16+. When I use fly hacks and move at the same time at a certain height the setback works but when I don't move while using fly hacks and I'm in mid air the setback doesn't work anymore.
Here is the AAC Log https://pastebin.com/FxSGdy2V
There are no errors or anything on the aac log or on the console.

I tested this in versions below 1.16 and the setback works fine even when I do not move in mid air while fly hacking. I think the problem is only occurs in versions 1.16 and above.

### Core information
**Server version**: 1.16

**AAC version**: 4.4.2

**ProtocolLib version**: Dev build #482

**Plugin list**: AAC, ProtocolLib, ViaVersion, ViaBackwards, ViaRewind, ViaRewindLegacySupport

### Special environment information
**ViaVersion version**: 3.2.0

**ProtocolSupport version**: ??

**ViaBackwards version**: 3.2.0

**BungeeCord plugins**: ??

**Comment by Janmm14** [comment]
Which highest minecraft version (below 1.16) did you test with?

**Comment by SwagPancakes** [comment]
> Which highest minecraft version (below 1.16) did you test with?

I tested 1.15.2 to 1.8.8 spigot and paperspigot and the setback problem didn't occur.

**Comment by SwagPancakes** [comment]
The problem has been solved with the latest version of AAC 5 thx :D:D:DDDDD
