### ISSUE TITLE
allow blocking /aac, don't expose owner's spigotmc page to all players

### ISSUE THREAD

**Issue by ghost** [konsolas/AAC-Issues#2015]
### Issue description
This is just scummy, why would a plugin attempting to be professional behave this way. You cannot block the /aac command and anyone on the server can see your spigotmc page.

### Core information
**Server version**: 1.16.4

**AAC version**: 4.4.2

**Comment by SwagPancakes** [comment]
> ### Issue description
> This is just scummy, why would a plugin attempting to be professional behave this way. You cannot block the /aac command and anyone on the server can see your spigotmc page.
> 
> ### Core information
> **Server version**: 1.16.4
> 
> **AAC version**: 4.4.2

You cannot block the command but you can block the message instead by using this plugin https://www.spigotmc.org/resources/message-blocker-1-8-1-15.74783/
and use chatcontrol or chatcontrolpro or any commandblocker plugin to add another message like "Unknown command. Type "/help" for help."

**Comment by konsolas** [comment]
AAC5 no longer displays spigot userid.
