### ISSUE TITLE
AAC5 Move Bug

### ISSUE THREAD

**Issue by ZugPilot** [konsolas/AAC-Issues#2018]
### Issue description

First of all, there was no log folder. So no logs :/
Basically I disabled mitigation for the move check and delay checks and tried to cheat on my testserver and now move doesn't seem to appear in status at all, even when aggressively bhoping around the map or flying around with vanilla fly.

### Core information
**Server version**: 
1.8.8
**AAC version**: 
5.0.0-pre1
**ProtocolLib version**: 
4.5.1

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

### Configuration

Config paste: https://pastebin.com/JUtb5z1F

**Comment by konsolas** [comment]
pre2
