### ISSUE TITLE
AAC5 Move Bug

### ISSUE THREAD

**Issue by ZugPilot** [konsolas/AAC-Issues#2019]
### Issue description

https://www.youtube.com/watch?v=CNMj6Jr1QyM

### Core information
**Server version**: 
1.8.8
**AAC version**: 
AAC5.0.0-pre1
**ProtocolLib version**: 
4.5.1

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
Can't reproduce this one - are you using normal unmodified spigot?

**Comment by HexedHero** [comment]
Cannot reproduce this one too

**Comment by ZugPilot** [comment]
Actually, yes. I'm using a Paper Fork called SportPaper and I just looked up their patches and saw this: https://github.com/Electroid/SportPaper/blob/master/patches/server/0191-Prevent-1.7-players-glitching-in-carpet.patch
I'msorry. I should have noticed that I'm using a modified spigot.
