### ISSUE TITLE
AAC5 Pre2 - Interact Error

### ISSUE THREAD

**Issue by HexedHero** [konsolas/AAC-Issues#2020]
Got this weird error that only happened once so I doubt its a big issue.
https://pastebin.com/raw/wnJqRapW

Sorry to say I have no idea how this happened and I cannot reproduce.

### Core information
**Server version**: 1.8.8 Paper

**AAC version**: AAC5 Pre2

**ProtocolLib version**: v4.6.0-SNAPSHOT 483

**Plugin list**: AAC ProtocolLib 

### Special environment information
**ViaVersion version**: 3.2.0
**ProtocolSupport version**: N/A
**ViaBackwards version**: N/A
**BungeeCord plugins**: N/A

### Configuration
No changes.

**Comment by konsolas** [comment]
pre3
