### ISSUE TITLE
move packets stop being sent to server

### ISSUE THREAD

**Issue by True-cc** [konsolas/AAC-Issues#2021]
### Issue description

After flagging a bit, aac prevents move packets from being sent to the server I think. Not entirely sure but it sure seems like it.

### Core information
**Server version**: paper 1.12.2

**AAC version**: 5.0.0PRE1

**ProtocolLib version**: 

**Plugin list**: AAC5 BlockGlitchFix, Citizens, CitizensCMD, CoreProtect, Essentials, EssentialsSpawn, FastAsyncWorldEdit, LiteBans, LuckPerms, MatrixPvPBase, Multiverse-Core, packetevents, PlaceholderAPI, PlugMan, ProtocolLib, Sentinel, SuperbVote, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, WorldEdit, WorldGuard

### Special environment information
**ViaVersion version**: 3.2.0

**ProtocolSupport version**: ??

**ViaBackwards version**: 3.2.0

**BungeeCord plugins**: ??

**Comment by Janmm14** [comment]
How does this impact your server negatively? What should be altered?

**Comment by True-cc** [comment]
Well for starters it makes it annoying to test because when I get flagged aac seems to block movement packets. Don't cancel movement packets, just teleport the player back which it does but then it starts to cancel movement packets.

**Comment by konsolas** [comment]
Can't reproduce this. Make sure your hacked client is replying to teleport packets.

Also try using spigot/paper and remove plugins other than AAC and ProtocolLib
