### ISSUE TITLE
AAC5 Piston Bug?

### ISSUE THREAD

**Issue by ZugPilot** [konsolas/AAC-Issues#2022]
### Issue description

Being on top of redstone clocked pistons flags you false, with and without slime blocks (move check)
The same thing for sideways sticky pistons with a block attached to it. 
https://i.imgur.com/fhlXSQR.png

### Core information
**Server version**: 
1.8.8
**AAC version**: 
AAC5.0.0-pre2
**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
pre3
