### ISSUE TITLE
AAC Speed Bypass

### ISSUE THREAD

**Issue by ZugPilot** [konsolas/AAC-Issues#2023]
### Issue description

https://www.youtube.com/watch?v=7cFVkf_TlTQ&feature=youtu.be

### Core information
**Server version**: 
1.8.8
**AAC version**: 
5.0.0-pre3
**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
pre4
