### ISSUE TITLE
move bug with hoppers

### ISSUE THREAD

**Issue by ZugPilot** [konsolas/AAC-Issues#2024]
### Issue description

https://www.youtube.com/watch?v=W8dRM31IXXM

### Core information
**Server version**: 
1.8.8
**AAC version**: 
5.0.0-pre4
**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
pre8
