### ISSUE TITLE
move bug with any ridable entity

### ISSUE THREAD

**Issue by ZugPilot** [konsolas/AAC-Issues#2026]
### Issue description

https://youtu.be/aKwV1Wza_UE

### Core information
**Server version**: 
1.8.8
**AAC version**: 
5.0.0-pre4
**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
might be resolved in -pre5?
