### ISSUE TITLE
move check broken?

### ISSUE THREAD

**Issue by ZugPilot** [konsolas/AAC-Issues#2028]
### Issue description

Move check does not seem to mitigate at all/or detect me
https://i.imgur.com/4GnTd1L.png
Thats what happens when I fly
Version of the client is 1.8

### Core information
**Server version**: 
1.8.8
**AAC version**: 
5.0.0-pre6
**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
Posted a silent update.
