### ISSUE TITLE
Pandora Phase

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#203]
Phase on the Pandora Client works and bypasses. It's kind of tricky to do it the first time but once you get the hang of it you can go through fences and other things. https://www.youtube.com/watch?v=PpBjmhjzoSs

**Comment by Janmm14** [comment]
rly critical?

**Comment by Rqcco** [comment]
oops

**Comment by konsolas** [comment]
Fixed, awaiting confirmation by @Rqcco

**Comment by Rqcco** [comment]
Fixed.
