### ISSUE TITLE
combat false positives

### ISSUE THREAD

**Issue by ZugPilot** [konsolas/AAC-Issues#2030]
### Issue description

https://www.youtube.com/watch?v=YK09GwKiW8Q&feature=youtu.be

### Core information
**Server version**: 
1.8
**AAC version**: 
5.0.0-pre8
**ProtocolLib version**: 

**Plugin list**: 
see vid description
### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
-pre11
