### ISSUE TITLE
Issue with veinminer

### ISSUE THREAD

**Issue by husscraft** [konsolas/AAC-Issues#2032]
Hi, since the last few updates, I've been having an issue with players getting flagged for breaking blocks too quickly when using veinminer. Myself and admin get the 'spectate' notification, and eventually players will get kicked by Ultra Punishments. I realise UPUN is not your responsibility. There are some regulars who I would feel comfortable exempting from punishments, but obviously I can't do that for everyone. 

Is there anything I can change in config, or something you could do to address the issue in a future update?

**Comment by konsolas** [comment]
VeinMiner needs a new anticheat hook for AAC5.
Will look into this further when the API is finalised.

**Comment by konsolas** [comment]
Pending https://github.com/2008Choco/VeinMiner/pull/48

**Comment by 2008Choco** [comment]
Aforementioned PR was merged, VeinMiner was released and now supports AAC 5. Consequently, support for AAC 4 was dropped.
https://www.spigotmc.org/resources/veinminer.12038/update?update=376212
