### ISSUE TITLE
False positive with twisting vines

### ISSUE THREAD

**Issue by AppleMacOS** [konsolas/AAC-Issues#2033]
### Issue description

https://streamable.com/l8gu1n

### Core information
**Server version**: git-Paper-288 (MC: 1.16.4)

**AAC version**: 5.0.0-pre15

**ProtocolLib version**: 4.5.1

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration

I'm using the default AAC5 config and haven't made any changes to it.

**Comment by konsolas** [comment]
-pre16
