### ISSUE TITLE
AACv5 Carpet Issue

### ISSUE THREAD

**Issue by Reed3411** [konsolas/AAC-Issues#2034]
### Issue description
https://youtu.be/zx5-c310jzk. When using AACv5 and stepping onto and around carpets the move check falsely corrects the player. At the end of the video there is an issue where AACv5 does not accept velocity that is created by the server, although this is only a minor issue.

### Core information
**Server version**:  1.8.8 TacoSpigot

**AAC version**:  AACv5-pre16

**ProtocolLib version**: 4.5.1

**Plugin list**:  n/a

### Special environment information
**ViaVersion version**: not used

**ProtocolSupport version**: not used

**ViaBackwards version**: not used

**BungeeCord plugins**: n/a

**Comment by konsolas** [comment]
Can't reproduce this at all (testing 1.8.8 client on Paper 1.16.4). 

Need a video with /aac debug enabled, or alternatively a paste of /aac debug from the console.
