### ISSUE TITLE
Bring back PlayerViolationEvent and PlayerViolationCommandEvent events to API

### ISSUE THREAD

**Issue by Xayanix** [konsolas/AAC-Issues#2035]
As above, bring them back to AAC 5.

**Comment by konsolas** [comment]
Violations no longer exist so it is unclear what a PlayerViolationEvent would do.

Commands can be detected by just handling the command when it's executed.

**Comment by Xayanix** [comment]
Ok, can you add exempt option to API?
 I got players with anticheat client versions which should be not checked by AAC (performance save).

**Comment by Xayanix** [comment]
Ok, have you got any documentation of check exemption in API?

**Comment by konsolas** [comment]
- get an instance of AACAPI with the bukkit services manager
- create a new AACExemption with some detail string
- call AACAPI#addExemption and AACAPI#removeExemption as appropriate
