### ISSUE TITLE
Exemptions for GeyserMC/Floodgate not working correctly.

### ISSUE THREAD

**Issue by Illusionika** [konsolas/AAC-Issues#2036]
### Core information
**Server version**: PaperSpigot 1.16.4
(online-mode=false , bungeecord: true)

**AAC version**: 5.0.0 pre18

**BungeeCord version**: Waterfall
(online_mode: false , ip_forward: true)

**GeyserMC version**: Geyser-BungeeCord.jar
(auth-type: offline)

-------------------------------------- The following translation is Google --------------------------------------

Use Bedrock Edition clients (WIN10) to enter the game
Jumping blocks will flashback when going forward
AAC does not exempt players from GeyserMC, exempt=0 in SQL
Modified to 1(/aac exempt) will not flashback (need to re-enter the game)

And the UUID in MariaDB (MySQL) is �����（unrecognizable characters）

Videos and aac debug Logs are in the attachment file

[BUG.zip](https://github.com/konsolas/AAC-Issues/files/5623457/BUG.zip)

**Comment by Janmm14** [comment]
I guess the geyser support is currently limited to the spigot version

**Comment by Illusionika** [comment]
emmmm...

I just tried using
spigot-1.16.4.jar + Geyser-Spigot.jar + AAC-5.0.0-pre18.jar
paperclip-298.jar + Geyser-Spigot.jar + AAC-5.0.0-pre18.jar
The result is the same as when using BC

[spigot_aac_debug.log](https://github.com/konsolas/AAC-Issues/files/5624386/spigot_aac_debug.log)

**Comment by konsolas** [comment]
Do you have Floodgate installed on the spigot server? AAC uses the Floodgate API.

**Comment by konsolas** [comment]
@Janmm14 is correct about the UUID representation.
Exemptions due to Floodgate will not be reflected in the database, so there's no need to look there.

**Comment by Illusionika** [comment]
There is no problem installing Floodgate
Thank
