### ISSUE TITLE
Water animation transition lagbacks the player, when jumping into water and pressing spacebar

### ISSUE THREAD

**Issue by ChiboYen** [konsolas/AAC-Issues#2038]
### Issue description

When jumping into water the transition into the swim animation will result in a detection and lagback. Video can be provided if necessisary, however this is not an edge case. If one jumps into the water while spamming space, essentially transitioning into the swim movement mode, AAC will flag.

https://pastebin.com/gLe4gwnW

### Core information
**Server version**: aac.kons.co

**AAC version**: aac.kons.co (pre20)

**ProtocolLib version**: aac.kons.co

### Special environment information
**ViaVersion version**: aac.kons.co

**ProtocolSupport version**: aac.kons.co

**ViaBackwards version**: aac.kons.co

**BungeeCord plugins**: aac.kons.co

### Configuration
aac.kons.co was used to test

**Comment by loveGhb** [comment]
I am using version 1.12 and ViaVersion (latest version), AAC 5.0.0. And when a player enters from version 1.14 and falls into the water, he starts to hang terribly, this is very critical.

**Comment by ChiboYen** [comment]
Not relevant anymore, issue isn't present anymore from the v5 betas
