### ISSUE TITLE
When a player first logs in, they get lagged back by aac and get 100 scoring

### ISSUE THREAD

**Issue by kentos01** [konsolas/AAC-Issues#2039]
### Core information
**Server version**: 1.16.4

**AAC version**: 5.0pre21

**ProtocolLib version**: 

**Details**: 
AAC Player Analysis of Player at 03-Dec-2020 18:52
Scoring (113)
The player has moved 42.5 blocks/min incorrectly
The player recently joined for the first time
The player recently joined from a new ip address
Insufficient data to analyse the player's movement
Insufficient data to analyse the player's interactions
Insufficient data to analyse the player's combat

**Comment by konsolas** [comment]
Server log / debug log?
