### ISSUE TITLE
Setback/false positive when sprint jumping on waterlogged slabs

### ISSUE THREAD

**Issue by ChiboYen** [konsolas/AAC-Issues#2043]
### Issue description
When running on waterlogged slabs, when ascending there will be a setback by AAC5
https://pastebin.com/nf0U6Sy4

### Core information
**Server version**: 1.16.4

**AAC version**: Pre22 Test Server

**ProtocolLib version**: Test Server

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

### Configuration
Test.kons.co

**Comment by konsolas** [comment]
-pre23
