### ISSUE TITLE
Player Movement Bug

### ISSUE THREAD

**Issue by GoT-HiM** [konsolas/AAC-Issues#2044]
When activating AAC5, there is an error. When a player enters the server, he can move around and do everything. But for the server the player remains stationary. This only happens with AAC5, as, by removing it, the players move quietly.

**Comment by konsolas** [comment]
Server version/AAC version/protocolsupport/viaversion?

**Comment by GoT-HiM** [comment]
1.12.2 PaperSpigot AAC5 latest version (5.0.0-pre22) ViaVersion

**Comment by konsolas** [comment]
Can you run /aac debug <player> in the console and send the log here?

**Comment by GoT-HiM** [comment]
Sure wait

**Comment by GoT-HiM** [comment]
Ehm it do not send any text

**Comment by konsolas** [comment]
Are you using ViaRewind?

**Comment by konsolas** [comment]
Going to merge this with #2045 since there appears to be a viaversion bug here
