### ISSUE TITLE
Teleport Accept packet not being passed to ProtocolLib by ViaVersion

### ISSUE THREAD

**Issue by Rollczi** [konsolas/AAC-Issues#2045]
**Players cannot move**. (Players move **locally** but **actually stand still**)
 (After disabling the AAC5 plugin, everything is fine)

Admin sees:
![image](https://user-images.githubusercontent.com/49173834/101427124-9a822080-38fe-11eb-888b-fc02d7c26e7a.png)

Player sees:
![image](https://user-images.githubusercontent.com/49173834/101427232-cac9bf00-38fe-11eb-9ec8-1ba490d4a35b.png)

Chunk doesn't render for Player:
![image](https://user-images.githubusercontent.com/49173834/101427278-e2a14300-38fe-11eb-85ec-73b1238d7873.png)

The server does not accept any moves, interact ... from the Player.

The commands work.

![image](https://user-images.githubusercontent.com/49173834/101427549-622f1200-38ff-11eb-9000-8b71720128df.png)
No answer...

### Core information
**Server version**: 1.12.2 (PaperSpigot)

**AAC version**: AAC5 pre22

**ProtocolLib version**: 4.5.1

**Plugin list**: - (Other plugs don't interfere)

### Special environment information
**ViaVersion version**: 3.2.0

**ProtocolSupport version**: -

**ViaBackwards version**: 3.2.0

**BungeeCord plugins**: -

### Configuration
- no changes

**Comment by ChiboYen** [comment]
You are using a hacked client... regardless or not whether the hacks are on, sometimes hacked clients send bad packets that are detected. Test again with vanilla client

**Comment by Rollczi** [comment]
I tested a little.
All 1.8.8 clients are down. (Regardless of whether it has op or not)
1.12.2 works properly.

**Comment by konsolas** [comment]
The teleport accept packet that ViaRewind sends doesn't seem to be received by ProtocolLib. Currently investigating.

**Comment by konsolas** [comment]
Pending https://github.com/ViaVersion/ViaVersion/pull/2229

**Comment by konsolas** [comment]
https://ci.viaversion.com/job/ViaVersion/
https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/
