### ISSUE TITLE
1.8 Client move false positive + infinitely being teleported back since pre22

### ISSUE THREAD

**Issue by kjzl** [konsolas/AAC-Issues#2046]
### Issue description
Theres a move false positive with 1.8 Clients while sneaking and walking forwards next to a wall. Easiest to reproduce with an Angle of 30° to the wall. Im pretty sure this has to do with the slightly smaller playerhitbox of 1.8 Clients.
https://youtu.be/zLv-Qvn_kiE

Infinitely being teleported back only occurs with the new pre22 update as far as I know.

### Core information
test.kons.co server with pre22

**Comment by Janmm14** [comment]
there is no smaller player hitbox on 1.8 clients

**Comment by konsolas** [comment]
Still happening to me with AAC removed.

**Comment by konsolas** [comment]
Seems very likely to be a protocolsupport bug

**Comment by konsolas** [comment]
Confirmed to be a protocolsupport bug. Can reliably reproduce by swimming against a wall underwater and then relogging. Happens without AAC installed.
