### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by ChiboYen** [konsolas/AAC-Issues#2048]
### Issue description
AAC server crash, thread dump provided: https://pastebin.com/UHwwMaaj

### Core information
**Server version**: 1.16.4

**AAC version**: Pre22 AAC5

**ProtocolLib version**: latest 6.4.0 dev snapshot

**Plugin list**: 

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Default Config

**Comment by konsolas** [comment]
5.0.0-rc
