### ISSUE TITLE
Fast(use/break/place) hacks are not detected, thus bypassed

### ISSUE THREAD

**Issue by ChiboYen** [konsolas/AAC-Issues#2051]
### Issue description
I am able to use fastuse hacks, which remove the interact/use item delay in vanilla Minecraft.
For example, firework rockets/exp bottles are able to be used at a super fast rate

Player stood still (no movement), looked at the ground and was able to fire off rockets at a super fast rate for this period of debug log:
https://pastebin.com/wJ9cSMVm

No detections nor flags were presented by AAC

### Core information
**Server version**: 1.16.4

**AAC version**: AAC5 Pre23

**ProtocolLib version**: 

**Plugin list**: N/A

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Default config

**Comment by ChiboYen** [comment]
Update: this issue has been observed to be the case with numerous clients, also extending to fastbreak and fastplace as well. Interaction checks in AAC5 do not appear to stop or mitigate the fast placement/use/interaction modules many clients have.

**Comment by Janmm14** [comment]
Fastbreak can be detected quite well while fastplace is a balance between users clicking fast on their mouse and cheats.

**Comment by konsolas** [comment]
Can't reproduce fastbreak bypasses.

Players are able to use items every tick by right clicking very quickly - this is not a bypass.
