### ISSUE TITLE
Poison effect will slow/speed up player due to server imposed velocity, AAC5 does not account for this change in speed/velocity

### ISSUE THREAD

**Issue by ChiboYen** [konsolas/AAC-Issues#2052]
### Issue description
This issue is related probably to #2037

Poison damage ticks will slow/speed up the player, and the move check does not currently account for the velocity change imposed by the server's poison/damage-tick

debug log:
https://pastebin.com/gS4seFHJ

### Core information
**Server version**: 1.16.4

**AAC version**: 5.0-pre23

**ProtocolLib version**: Latest dev, 4.6.0 SNAPSHOT

### Configuration
Default config

**Comment by Janmm14** [comment]
AAC 5 should actually get every velocity as its using a packet listener for velocity.

**Comment by konsolas** [comment]
Cannot reproduce on test server. Need more information about server/client versions.

**Comment by konsolas** [comment]
Debug log shows AAC reading a velocity packet and the client not respecting it - seems like some protocol hack or client mod is interfering.

**Comment by ChiboYen** [comment]
Client interaction seems to be the cause of this, and it is not present in the vanilla or optifine clients. Therefore, I assume that this is not due to AAC's fault, you're good to close this.
