### ISSUE TITLE
Add a tolerance value for boat on ice, or even more generalized: boat setback configuration value

### ISSUE THREAD

**Issue by ChiboYen** [konsolas/AAC-Issues#2055]
When I check the config for AAC5-rl, specifically the move check portion:
```
  flowing_speed: 0.2
    bubble_column_speed: 1.8
    bumping_speed: 0.1
    elytra_rocket_speed: 2.0
    riptide_speed: 4.2
    boat_hitbox_tolerance: 0.7
    shulker_hitbox_tolerance: 0.6
    elytra_landing_tolerance: 0.5
```
I see numerous tolerances, but boats are not on here (boat hitbox is simply when the player is up against the hitbox of a boat from my understanding). 

Is there any way to add a method to define how fast a player should be able to travel in a boat on ice? This issue is related to #2054 of course since it would be nice if AAC didn't break ice highways in vanilla Minecraft.

Furthermore, would it be possible to add in a config value to disable the teleportation of a player outside their boat/entity? 

Appreciate it Konsolas! Keep up the good work

**Comment by konsolas** [comment]
Merging with #2054
