### ISSUE TITLE
Random exceptions

### ISSUE THREAD

**Issue by wulfwuud** [konsolas/AAC-Issues#2056]
### Issue description
https://hastebin.com/rihikeruse

### Core information
**Server version**: 1.12.2

**AAC version**: 5.0.0

**ProtocolLib version**: 4.5.1

**Plugin list**: 

### Special environment information
**ViaVersion version**: not installed

**ProtocolSupport version**: not installed

**ViaBackwards version**: not installed

**BungeeCord plugins**: ??

### Configuration
default

**Comment by konsolas** [comment]
Could you please use a different service? Hastebin doesn't seem to want to load for me.

e.g.
- https://gist.github.com/
- https://pastebin.com/

**Comment by wulfwuud** [comment]
https://pastebin.com/zjievMYD

**Comment by konsolas** [comment]
5.0.1
