### ISSUE TITLE
AAC null - crashes client.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2059]
We have AAC running on 9 servers across one bungee network.
At times, when a player gets kicked on another server, admins with aac.* get client crashed with error:
https://i.imgur.com/gmdpfIy.png

Console only shows:
```
[23:10:22] [AAC Report Generator Thread/INFO]:  AAC null
[23:10:22] [Server thread/INFO]: andrewkm lost connection: Disconnected
[23:10:36] [AAC Report Generator Thread/INFO]:  AAC null
```

I cannot reliably reproduce, but it continues to happen constantly.

### Core information
**Server version**: 1.16.4 (Paper Build 325)

**AAC version**: 5.0.1

**AAC config**: 5.0.1|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.6.0 Build 480

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
5.0.2
