### ISSUE TITLE
Item Attributes (AAC Feature)

### ISSUE THREAD

**Issue by BiGUNMAN** [konsolas/AAC-Issues#206]
I've been asking this for a while, and I'm sure many others have been too. It would awesome to see support for item attributes.

- ~~Max Health~~
- Knockback Resistance (WONT FIX)
- ~~Increased attack damage~~
- ~~Armor (an item gives more armor points)~~
- ~~Armor toughness~~
- ~~Attack speed~~
- Walk speed (NEEDS FIX)

Full list here: http://minecraft.gamepedia.com/Attribute

These changes are all based on whether player holds item or has armor with the attribute. Support for these attributes I believe would be widely appreciated. It would be awesome to see this implemented into AAC V3

**Comment by Janmm14** [comment]
armor values and max health should be supported by aac already (most likely no special code for that needed)

**Comment by konsolas** [comment]
I believe only two of those are valid at the moment.

**Comment by konsolas** [comment]
oops

**Comment by BiGUNMAN** [comment]
Correct, those are 2 of quite a few that aren't supported, such as
movement.

**Comment by MinecraftiUndCo** [comment]
I and our network (LPmitKev.de) would also appreciate an item attribute support. The most important are Knockback Resistance and Walk Speed. I hope it will be implemented before spring holidays. :)

**Comment by konsolas** [comment]
Walk speed has so far been completed.

**Comment by Janmm14** [comment]
As far as I know the knockback resistance attribute is a percentage chance of not taking knockback at all.

**Comment by CeIebrimbor** [comment]
Update as of 3.2.1. Speed attribute is not supported (detects for speed).

**Comment by Janmm14** [comment]
(Little note: Changing player walk speed is supported, just item attributes are not)

**Comment by BiGUNMAN** [comment]
Well, it'll be nice to see the default built-in mc features working with
AAC :/

**Comment by FrozenBeard** [comment]
2 years and we still don't have Item Attributes! come on!

**Comment by Rerd** [comment]
bump, still needing support for this — over a year old
