### ISSUE TITLE
Combat FPs

### ISSUE THREAD

**Issue by Hyronymos1337** [konsolas/AAC-Issues#2060]
Latest AAC Version
AAC log: https://privatebin.net/?8beb3bad91f7bf99#HQxQrxCXK9ochzdkh8ZXJ9cUNEQR8hBDP1Z6R5GTgfXK

Video 01: https://www.youtube.com/watch?v=d54fZhkXKDI
Video 02: https://www.youtube.com/watch?v=SrqD8vMTR_s

Note: The player said he had ping issues

**Comment by konsolas** [comment]
5.0.4 adds hitbox.lag_compensation_ticks
