### ISSUE TITLE
Invalid bungee message: uuid

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2062]
Everytime a player gets kicked as of 5.0.2 we get the following:
(Back on 5.0.1 it would just say AAC null).

```
[AAC5] Invalid bungee message: uuid = f84b60e3-5b53-42cc-817d-b0669eacbfbf
```

### Core information
**Server version**: 1.16.4 (Paper Build 325)

**AAC version**: 5.0.2

**AAC config**: 5.0.1|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.6.0 Build 480

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
Is it possible that `ip_forward` is not enabled in bungeecord or `bungeecord` is not set in `spigot.yml` of any of your servers?

**Comment by andrewkm** [comment]
Lol bro...
Of course that's all set.

**Comment by andrewkm** [comment]
Any ideas on this one?

**Comment by andrewkm** [comment]
Plugin abandoned
