### ISSUE TITLE
Can't Open Chests When Crouched Under Slabs

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2063]
Original report with video:
https://ecocitycraft.com/forum/threads/cant-open-chests-when-crouched-under-slabs.206918/
Kick is 514 - Interact Global (All Interact Checks)

```
Brief Description: Can't open chests when crouched under a slab unless shift + clicking, but cannot at all when an item is in hand even when shift clicking.

Instructions:Place some slabs overhead. Place some chests near. Go under slabs. Try and open chests without holding shift, then holding shift, and then while having an item in hand.

How many times did you recreate this?: 14 with various items.

Result: Kicked by anti-cheat (514) and cannot open chests.

Expected Result: Should be able to freely open the chests regardless of holding shift or an item in hand.
```

https://www.youtube.com/watch?v=hAoLUrj903A&feature=emb_title

### Core information
**Server version**: 1.16.4 (Paper Build 325)

**AAC version**: 5.0.2

**AAC config**: 5.0.1|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.6.0 Build 480

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
5.0.3
