### ISSUE TITLE
Cannot Attack Mobs Under Slabs.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2065]
Original report with video:
https://ecocitycraft.com/forum/threads/kicked-by-anti-cheat-attacking-mobs-under-slabs.206947/
Kick is 506 - Hitbox

```
Brief Description: Crouching under a slab and attacking a mob ends up resulting in a kick by anti-cheat (506 mostly, and did 501 once but wasn't recording.)

Instructions: Have a slab over your head and be crouching. Attack a mob that is near (1 block up if that matters any).

How many times did you recreate this?: 11 to see what various codes would come up.

Result: Kicked by anti-cheat.

Expected Result: Not to be kicked and for my sword swings to be damaging the mobs.
```

https://www.youtube.com/watch?v=uRfr0WS2B3M&feature=emb_title

### Core information
**Server version**: 1.16.4 (Paper Build 325)

**AAC version**: 5.0.2

**AAC config**: 5.0.1|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.6.0 Build 480

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
5.0.3
