### ISSUE TITLE
API Support Request

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2066]
Cannot get our /sneak command to work anymore.
Basically allows players to walk at regular speeds while sneaking (crouching).

Previously we used:
```
	@EventHandler
	public void onPlayerViolation(PlayerViolationEvent event)
	{
		// Sneaking special ability
		if (event.getHackType() == HackType.MOVE && LS.sneakingPlayers.contains(event.getPlayer().getUniqueId()))
		{
			event.setCancelled(true);
		}
```
Now however, we're kind of lost on how to make this possible.
I can send the /sneak command code via Discord if you'd like to check it out.

We also had API code written up for our non vanilla enchanted tools, but those don't seem to be a problem anymore with AAC5 as they fire the correct events I believe like mentioned in your overview.

```
		if (event.getHackType() == HackType.INTERACT &&
				// Interact false positive with Efficiency 7+ tools.
				(event.getPlayer().getInventory().getItemInMainHand().getEnchantmentLevel(Enchantment.DIG_SPEED) >= 7 
						// Interact false positive with Efficiency 5+ swords (melon farming)
						(event.getPlayer().getInventory().getItemInMainHand().getType() == Material.DIAMOND_SWORD && event.getPlayer().getInventory().getItemInMainHand().getEnchantmentLevel(Enchantment.DIG_SPEED) >= 5)) &&
				event.getMessage().contains("interacted with a block out of his line of sight"))
		{
			event.setCancelled(true);
		}
```

Any ideas on how to handle the Move stuff for /sneak though?

**Comment by Janmm14** [comment]
konsolas decides how the api looks like
I'm just copypasting the api portion out of the aac jar.

konsolas decided that AAC 5 has no PlayerViolationEvent anymore - all you can do for compatibility is exempt players beforehand from all checks via the api.

I don't know how you did the sneak stuff, but a ProtocolLib outbound listener to entity metadata to set the sneaking flag when sent to other players should be compatible (clone metadata before modifying).

**Comment by konsolas** [comment]
Possible alternate solution with `checks.move.check_sneak` in 5.0.3 - let me know if this works for you.

**Comment by andrewkm** [comment]
Works! <3
