### ISSUE TITLE
1.11 Support

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#207]
You know...

**Comment by konsolas** [comment]
Marked for the record. Currently spigot is in beta, so I wouldn't want to write all the NMS bindings just to see them change within a month.

**Comment by CeIebrimbor** [comment]
With how quick the community moves, I'd think 1.11 would have all the nuts and bolts in 2 weeks with mass testing already taking place.

**Comment by ssamjh** [comment]
Yeah we have been working hard doing a lot of testing, maybe wait until 1.11 is --rev latest.

**Comment by konsolas** [comment]
1.11 is now --rev latest.
