### ISSUE TITLE
Memory Leak - 5.0.2 Version

### ISSUE THREAD

**Issue by michcie** [konsolas/AAC-Issues#2070]
### Issue description

So i found memory leak in 5.0.2 version.
ss: https://imgur.com/a/TdnD3lA

### Core information
**Server version**:  1.8.10

**AAC version**: 5.0.2

**ProtocolLib version**: 4.5.1

**Plugin list**: 

### Special environment information
**ViaVersion version**: 3.2.1

**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
Update to 5.0.3

**Comment by michcie** [comment]
In Version 5.0.3 i got new memory leak:
https://imgur.com/a/y0I0r4D
