### ISSUE TITLE
[AAC5] Task #11 for AAC5 v5.0.3 generated an exception

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2072]
Noticed console getting bombed with:
https://pastebin.com/exTwYEBi

(I'm aware we are on 5.0.4, I'm just about to update, but incase this wasn't fixed in 5.0.4 thought I'd report it.)

### Core information
**Server version**: 1.16.4 (Paper Build 334)

**AAC version**: 5.0.3

**AAC config**: 5.0.3|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.6.0 Build 480

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Janmm14** [comment]
5.0.4 should contain a fix specifically for such issues

**Comment by andrewkm** [comment]
Alright I'll monitor newest version. :)
