### ISSUE TITLE
Hitbox issues.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2073]
One of my users been complaining about continuously getting kicked while mob farming
He has no reproduction steps, and says it "happens from time to time"
Which I... hate those reports.
Anyways: https://pastebin.com/raw/daETX4Zn
Is all I got.

@CeIebrimbor said best posted here as it's potentially an issue with the new version.

Actual report by the player (which doesn't tell us too much...)

```
Brief Description: When flying, using a ECC PVP AXE, or farming mobs, i do often get kicked. Most kicks happends when i mob farm, on mobs that can fly, examples is ghasts.

Instructions: No clear instructions, i dont honestly know what do affect it, so it happends so occasionally

How many times did you recreate this?: 3-4 times, on different days, and in rising, aswell as in mining.

Result: Kicked by anti-cheat, kode 501
```

### Core information
**Server version**: 1.16.4 (Paper Build 335)

**AAC version**: 5.0.4

**AAC config**: 5.0.4|1-Default-Celebrimbor

**AAC enabled checks**: All checks enabled.

**ProtocolLib version**: 4.6.0 Build 480

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by CeIebrimbor** [comment]
I’ve been getting a number of reports about Hitbox/Combat/Global for mob farming the last 24 hours.

**Comment by konsolas** [comment]
5.0.5 (?)
