### ISSUE TITLE
Reach FP

### ISSUE THREAD

**Issue by Hyronymos1337** [konsolas/AAC-Issues#2074]
Latest AAC

Video: https://www.youtube.com/watch?v=MK-5W5WllvA&feature=youtu.be
Log: https://paste.twerion.net/oveqepubov.vbs

**Comment by konsolas** [comment]
Could you try increasing lag_compensation_ticks to e.g. 20?

**Comment by Hyronymos1337** [comment]
I will try it later today

**Comment by Hyronymos1337** [comment]
still valid.

log: https://paste.twerion.net/alacirixit.vbs
video: https://medal.tv/clips/39406203/d1337tgymrNd

**Comment by Hyronymos1337** [comment]
log from another player (he got some other combat flags too): https://paste.twerion.net/temavafuqo.vbs

video: https://youtu.be/LZcv_3hUEj0
