### ISSUE TITLE
Horse false positive when breaking leaves at the same time.

### ISSUE THREAD

**Issue by Agaloth** [konsolas/AAC-Issues#2077]
Server version:
1.16.4 purpur
AAC version:
5.0.5
ProtocolLib version: ProtocolLib version 4.6.0-SNAPSHOT-b482

Plugin list:
Plugins (116): AAC5, AACPlus, AdvancedEnchantments, AirBar, Aliases, ArmorStandTools, ArtMap, BannerBoard, BattlePass, BlockLocker, BlockParticles, BuycraftX, CS-CoreLib, CarbonChat, ChatReaction, ChestTerminal, Chunky, Citizens, CitizensCMD, ClearLag, ColoredAnvils, CombatLogX, CommandRegions, ConditionalCommands, ConsoleSpamFix, CoreProtect, CustomCrafting, DeathMessagesPrime, DeluxeCommands, DeluxeJoin, DeluxeMenus, DeluxeTags, DiscordSRV, Dynmap-Towny, Elevator, Essentials, EssentialsSpawn, GSit, GappleOptions, Gatekeeper, GoldenCrates, Graves, Harbor, HeadDatabase, HellConomy, HolographicDisplays, HolographicPlaceholders, IllegalStack, InventoryRollback, ItemsAdder, JakesRTP, Jobs, KiteBoard, LeaderHeadsRevamped, LightAPI, LimitPillagers, LiteBans, LoneLibs, Lottery, LuckPerms, MVdWPlaceholderAPI, MarriageMaster, MessageAnnouncer, MineableSpawners, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, NexEngine, NightVision, NotTooExpensive, OldCombatMechanics, OpenInv, PacketListenerApi, PlaceholderAPI, Plan, PlayerKits, PlayerVaults, Playtime, ProCosmetics, ProtocolLib, QuickShop, QuickShopDynmap, ServerListPlus, ServerUtils, ShopGUIPlus, ShopGUIPlusMineableSpawnersBridge, Slimefun, SpeedyPaths, StaffChat, SuperVanish, TAB, TCPShield, TitleManager, TokenManager, Towny, TownyChat, TownyFlight, TownyNameUpdater, TreasureChest, UltimateTimber, Vault, Vehicles, ViaBackwards, ViaVersion, VoteParty, Votifier, VotingPlugin, WildStacker, WolfyUtilities, WorldBorder, WorldEdit, WorldGuard, XLTournaments, dynmap, mcMMO and spark

Special environment information

ViaVersion version: ViaVersion version 3.2.1

ViaBackwards version: ViaBackwards version 3.2.1-SNAPSHOT

Configuration: Using Celebrimbor ghost config.

https://youtu.be/0D-hiV-EBL4 <- false flag video

**Comment by konsolas** [comment]
Need console logs from when the kick took place

**Comment by Agaloth** [comment]
It kicked for fastbreak

**Comment by Agaloth** [comment]
I’ll try getting logs

**Comment by Agaloth** [comment]
https://pastebin.com/KyAJs8Ub

**Comment by konsolas** [comment]
Definitely looks like leaf blower - #2096
