### ISSUE TITLE
Server error: Unhandled exception

### ISSUE THREAD

**Issue by bobbyfc** [konsolas/AAC-Issues#2079]
When one of my users logs in, Console outputs the following error message: https://pastebin.com/xvGLkKrG

**Server version**: Paper 1.13.2 

**AAC version**: AAC 5.0.5

**ProtocolLib version**: ProtocolLib 4.5.1

**ViaVersion version**: ViaVersion 3.2.1

I am using Celebrimor's latest AAC5 config.

**Comment by Dartume** [comment]
Hello we have the same Error https://pastebin.com/fKSU4kST
Server version: Paper 1.16.4

AAC version: AAC 5.0.3 and AAC 5.0.5

ProtocolLib version: ProtocolLib 4.5.1

**Comment by konsolas** [comment]
@Dartume your error is unrelated and you need to update ProtocolLib
