### ISSUE TITLE
Combat FPs

### ISSUE THREAD

**Issue by Hyronymos1337** [konsolas/AAC-Issues#2080]
Latest AAC Version

Log: https://paste.twerion.net/ezowodivox.vbs
Video: https://youtu.be/IcfCSBc3cbk

**Comment by konsolas** [comment]
Thresholds are far lower than default combat kick of 200. Try using default thresholds for combat.

**Comment by Hyronymos1337** [comment]
he got mainly flagged for the aac_aimbot_zero, I thought it would be a good idea  to report it, since aac_aimbot_zero is still experimental
