### ISSUE TITLE
AAC IllegalArgumentException: entityID cannot be negative

### ISSUE THREAD

**Issue by BestMark** [konsolas/AAC-Issues#2084]
### Core information
**Server version**: Paper 1.12.2

**AAC version**: 5.0.5

**ProtocolLib version**: 4.5.1

**Plugin list**: 

### Special environment information
**ViaVersion version**: 3.2.1

**ProtocolSupport version**: latest

Crash: https://pastebin.com/CjefjbLD

**Comment by konsolas** [comment]
Do you have another anticheat plugin spawning entities with negative IDs?

**Comment by konsolas** [comment]
5.0.6 will just ignore negative eids.
