### ISSUE TITLE
Feature: Minimum delay before players can reconnect.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2085]
Please add this back to AAC:
```
# AAC can enforce a minimum delay (in ms) before players can relog after disconnect.
relog_protection: 5000
relog_message: "Please wait 5 seconds before rejoining the server"
```

<3 It was so incredibly useful.

**Comment by ChiboYen** [comment]
Isn't this unnecessary due to bukkit/paper already having a configurable connection throttled (rejoin timer) and message?

**Comment by andrewkm** [comment]
> Isn't this unnecessary due to bukkit/paper already having a configurable connection throttled (rejoin timer) and message?

Doesn't work as well as AAC's reconnection timer worked.

**Comment by Janmm14** [comment]
AAC's reconnection timer worked on players, the connection throttle works on ips and can therefore not be used on spigots behind bungeecord

**Comment by andrewkm** [comment]
Plugin abandoned
