### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by GoT-HiM** [konsolas/AAC-Issues#2086]
### Core information
**1.16.4**: 

**AAC 5.0.5**: 

**4.5.1**: 

**I don't think that can be a plugin problem**: 

### Special environment information
**ViaVersion 3.2.1**: ??

**I don't use ProtocolSupport**: ??

**ViaBackwards 3.2.0 **: ??

**Ehm... Why?**: ??

**Comment by Janmm14** [comment]
So... where is the error?

**Comment by konsolas** [comment]
Missing error.
