### ISSUE TITLE
Console error spam on 5.0.6

### ISSUE THREAD

**Issue by bobbyfc** [konsolas/AAC-Issues#2092]
Since updating to AAC 5.0.6, my console has been spammed with the following error:

https://pastebin.com/SVr0DYFn

**Server version**: Paper 1.13.2

**AAC version**:  AAC 5.0.6

**ProtocolLib version**: 4.5.1

**ViaVersion version**:  3.2.1

I am using Celebrimors AAC configuration.

**Comment by konsolas** [comment]
Reset your config or make the config changes here: https://gist.github.com/konsolas/1ed816ed91996eab7262d95386c1bfa0/revisions
