### ISSUE TITLE
phase mitigation failure

### ISSUE THREAD

**Issue by wulfwuud** [konsolas/AAC-Issues#2099]
### Issue description
https://www.youtube.com/watch?v=ckovY8pHaec

### Core information
**Server version**: 1.12.2

**AAC version**: latest

**ProtocolLib version**: 4.5.1

**Plugin list**: 

### Special environment information
**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: direct connection

### Configuration
default

PLEASE DO NOT WRITE YOUR ISSUE DESCRIPTION HERE -->

**Comment by konsolas** [comment]
Just checked - this is possible to do in vanilla minecraft without phase/noclip. Just throw the pearl as shown in your video and then sprint/jump into the wall, and you'll emerge on the other side.
