### ISSUE TITLE
[Improvement] Disallow hitting through walls

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#21]
Currently its possible to hit entities through walls partly.

**Comment by Photon-GitHub** [comment]
There is the problem that on the edges it is sometimes even in vanilla minecraft possible to hit an entity through a wall...

**Comment by Janmm14** [comment]
Then simply add this as a special case ?! Should be possible to otherwise increase the hitbox used for calculation a little and it should work

**Comment by Photon-GitHub** [comment]
Would probably be a good heuristic after the removal of the ff check
-> planned.

**Comment by Janmm14** [comment]
@konsolas
With #7 being fixed, this issue should be easy to fix, right?

**Comment by konsolas** [comment]
That is correct, and this has been fixed.
