### ISSUE TITLE
Unhandled Exception Resulting in Console Spam

### ISSUE THREAD

**Issue by EnderGamingFilms** [konsolas/AAC-Issues#2105]
### Issue description
Console: https://pastebin.com/x0LUScfH

I'm running a 1.16.3 server with AAC5 and AACPlus but outside of this I am not using nay custom config (only using MySQL). I don't really know how this issue happened, but all I know is that since I updated to AAC5 I get console spamming a lot of the time any idea on as to why this is happening.

### Core information
**Server version**: 1.16.3

**AAC version**: 5.0.6

**ProtocolLib version**: 4.5.1

**Plugin list**: 
- AACPlus

### Special environment information
**ViaVersion version**: 3.2.1

**ViaBackwards version**: 3.2.0

**BungeeCord plugins**: 
- TCPShield
- PremiumVanish
- MiniMOTD
- BungeeControl
- BotSentry
- BungeeTabListPlus
- LuckPerms

**Comment by konsolas** [comment]
Update ProtocolLib
