### ISSUE TITLE
Speed Effects can trigger FP killaura and heuristics

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#211]
Players with Speed Effects get FP on heuristics (pattern 52) and killaura normal checks

**Comment by Janmm14** [comment]
@konsolas Is this fixed or not or? (Killaura normal check fps are not bound to speed, see #212)

**Comment by Janmm14** [comment]
@konsolas Pattern 52 got removed, right? In that case this issue can be closed.
