### ISSUE TITLE
[Feature] Please add AACAPI.getScore

### ISSUE THREAD

**Issue by SelfMadeSystem** [konsolas/AAC-Issues#2110]
Please add AACAPI.getScore(Player player, String id) that returns a double or float (however you store the score). Please this would be so useful.

**Comment by True-cc** [comment]
![image](https://user-images.githubusercontent.com/38010540/103677337-01631b80-4f37-11eb-95f3-4a9ac146e824.png)

**Comment by SelfMadeSystem** [comment]
Update: I don't think konsolas will be changing the API
