### ISSUE TITLE
Timer false positive upon lag spike

### ISSUE THREAD

**Issue by ChiboYen** [konsolas/AAC-Issues#2115]
### Issue description
The timer subcategory of the movement check does not account for TPS very well, as occasionally, a player or two will be flagged up to 300VL by it when there is a lag spike on the server of 100+mspt. I feel like this isn't my server's fault, as my TPS is 20 across the board and it's expected that certain periods will have higher ticks than normal, thus AAC should account for low TPS and give leniency or take it into consideration however the check works.

```
[05:24:08 INFO]: [⚡] TPS from last 5s, 10s, 1m, 5m, 15m:
[05:24:08 INFO]: [⚡]  *20.0, 20.0, 20.0, 20.0, 20.0
[05:24:08 INFO]: [⚡] 
[05:24:08 INFO]: [⚡] Tick durations (min/med/95%ile/max ms) from last 10s, 1m:
[05:24:08 INFO]: [⚡]  20.9/23.8/28.2/319.1;  20.7/23.4/28.2/319.1
```

### Core information
**Server version**:  1.16.4

**AAC version**: 5.0.7

**ProtocolLib version**: B492

### Configuration
Custom configuration of the timer move subcategory:
```
  movetimer:
    features:
      - aac_move_timer
    thresholds:
      ...
      160: "conditional kick command here"
```

**Comment by konsolas** [comment]
What's the output of `/aac status` for the player that got to 300? It's unlikely to all be timer.

**Comment by ChiboYen** [comment]
Here are some various false positive statuses:
```
[Thu, 7. Jan 2021 05:04:51 UTC INFO] Scoring (127)
[Thu, 7. Jan 2021 05:04:51 UTC INFO] - The player is trying to speed up time
[Thu, 7. Jan 2021 05:04:51 UTC INFO] - The player recently joined for the first time
[Thu, 7. Jan 2021 05:04:51 UTC INFO] - The player recently joined from a new ip address
[Thu, 7. Jan 2021 05:04:51 UTC INFO] - Insufficient data to analyse the player's combat
[Thu, 7. Jan 2021 05:04:51 UTC INFO] - Insufficient data to analyse the player's interactions
[Thu, 7. Jan 2021 05:04:51 UTC INFO] Generated by AAC 5.0.7
``` 
```
[Thu, 7. Jan 2021 05:04:51 UTC INFO] Scoring (183)
[Thu, 7. Jan 2021 05:04:51 UTC INFO] - The player is trying to speed up time
[Thu, 7. Jan 2021 05:04:51 UTC INFO] - The player recently joined for the first time
[Thu, 7. Jan 2021 05:04:51 UTC INFO] - The player recently joined from a new ip address
[Thu, 7. Jan 2021 05:04:51 UTC INFO] - Insufficient data to analyse the player's combat
[Thu, 7. Jan 2021 05:04:51 UTC INFO] - Insufficient data to analyse the player's interactions
[Thu, 7. Jan 2021 05:04:51 UTC INFO] Generated by AAC 5.0.7
```
```
[Thu, 7. Jan 2021 04:24:05 UTC INFO] Scoring (160)
[Thu, 7. Jan 2021 04:24:05 UTC INFO] - The player is trying to speed up time
[Thu, 7. Jan 2021 04:24:05 UTC INFO] - The player recently joined from a new ip address
[Thu, 7. Jan 2021 04:24:05 UTC INFO] - Insufficient data to analyse the player's interactions
[Thu, 7. Jan 2021 04:24:05 UTC INFO] - Insufficient data to analyse the player's combat
[Thu, 7. Jan 2021 04:24:05 UTC INFO] - Insufficient data to analyse the player's movement
[Thu, 7. Jan 2021 04:24:05 UTC INFO] Generated by AAC 5.0.7
```

Weirdly they are all new players, however, I have decreased the weights of "insufficient data..." and "joined from a new ip address"

**Comment by ChiboYen** [comment]
Using Janmm14's suggestion, I simulated laggy conditions with Clumsy 0.2 and got reproduced these results that falsed the timer:
https://pastebin.com/Bv5VNC03

```
[16:14:46 INFO]:  Scoring (160)
[16:14:46 INFO]:   - The player is trying to speed up time
[16:14:46 INFO]:   - Insufficient data to analyse the player's interactions
[16:14:46 INFO]:   - Insufficient data to analyse the player's combat
```

**Comment by ChiboYen** [comment]
@konsolas I left debug on with a certain laggy player, and they got banned again but this time I have an actual debug log
https://pastebin.com/2usJsBHm

**Comment by ChiboYen** [comment]
Here is an additional debug log that I managed to capture from a player:
https://pastebin.com/24tkrd61

The issue likely has to do with the lag compensation from #2116

**Comment by ChiboYen** [comment]
Update: Upon further observation of laggy players, you can close #2116, please however look into this debug log (the elytra move check was falsed):
https://pastebin.com/tWiUpWnv
