### ISSUE TITLE
Improvement reach detection

### ISSUE THREAD

**Issue by Fxetzi** [konsolas/AAC-Issues#2117]
In my opinion the reach detection can be improved, because you can hit a player quite often with reach until a message appears in /aac status <player>. Another thing i have experienced is that you can hit players 5 from 10 times with reach and no message appears but when you hit a player 5 from 50 times this message appears after a few time. So my suggestions is that each time when AAC recognizes a range hit that it will get scored like the movement check: "The player has moved {rate} blocks/min incorrectly". With that range cheater could be faster detected and kicked/baned from the server.

**Comment by CeIebrimbor** [comment]
By default, Hitbox takes the average of a grouping of hits to determine if a player is cheating. You can choose to enact this behavior by setting `hit_queue_size: 1` in the Hitbox settings. This is not recommended.

**Comment by Janmm14** [comment]
Checking a player can be forced by running `/aac check playername`.

**Comment by Fxetzi** [comment]
ok but on my test server are currently only 2 players online and when i used the /aac check <player> command nothing happened.
But 50 seconds after the player hit the last person the "The player attacks {value} blocks further than normal" appeared.
Is this also normal?

**Comment by konsolas** [comment]
Right now AAC waits for at least 30 seconds of combat before analysing reach data.

**Comment by Fxetzi** [comment]
i have a made a video showing this i talked about:
https://youtu.be/2JPE8gWz0s4
So this is not a bug?
