### ISSUE TITLE
Timer false positive on 5.0.8

### ISSUE THREAD

**Issue by ChiboYen** [konsolas/AAC-Issues#2125]
### Issue description
A known laggy player logs in and gets false detected by the timer subcategory, however this time there is a debug log and this was recorded:

Partial debug log of one instance:
https://pastebin.com/7F7g0hmF

Here's an instance of a debug log of the player from log-in to ban:
https://pastebin.com/Ehbe31rw

### Core information
**Server version**: 1.16.4

**AAC version**: 5.0.8

**ProtocolLib version**: b492

### Special environment information
Not a special environment

### Configuration
Doesn't really matter, it's a threshold of 140 so it's not like it's too low or anything. The only thing in the action is aac_move_timer. Conditional commands are used for this as well.

**Comment by konsolas** [comment]
Can't reproduce with 1000ms delay and throttling on clumsy. Try with default config.

**Comment by ChiboYen** [comment]
Done, I /aac reloaded with the default config, and it still kicked the player for actions.global (Timer subcategory of the move check)

**Comment by konsolas** [comment]
Set the weight of features.aac_move_timer to 0.

I haven't had any other reports of this and I have no way to reproduce it.

**Comment by ChiboYen** [comment]
Is it possible that this player is sending a burst of packets every few seconds instead of simply a delay in packets? Not an expert in networking, but would it be possible for you to try using various Clumsy settings?

**Comment by konsolas** [comment]
5.0.9 reduces the weight of the timer check again.
