### ISSUE TITLE
Wierd behavior with elytra when falling

### ISSUE THREAD

**Issue by Haczyn** [konsolas/AAC-Issues#2127]
Wierd behavior with elytra and falling

### Core information
**Server version**: 
his server is running Yatopia version git-Yatopia-"aaeb472" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
same on paper
**AAC version**: 
5.0.8
**ProtocolLib version**: 
ProtocolLib v4.6.0-SNAPSHOT-b492
**Plugin list**: 
Plugins (2): AAC5, ProtocolLib
### Configuration
default
https://www.youtube.com/watch?v=LMdnAp59BgA

**Comment by konsolas** [comment]
Need console logs from around the time of the kick.
