### ISSUE TITLE
Don't blocking movements after passenger 

### ISSUE THREAD

**Issue by VanyaNexus** [konsolas/AAC-Issues#2129]
### Issue description
https://www.youtube.com/watch?v=ZjWahJ0J8tc

### Core information
**Server version**: paperspigot 1.12.2

**AAC version**: 5.0.8

**ProtocolLib version**: 4.5.1

**Plugin list**: SimpleSit

### Special environment information
**ViaVersion version**: 3.2.1

**ViaBackwards version**: 3.2.0

### Configuration
default

**Comment by VanyaNexus** [comment]
Why so long? We have been waiting for a very long time...

**Comment by konsolas** [comment]
Merging with #2195
