### ISSUE TITLE
Players lagg in half-blocks

### ISSUE THREAD

**Issue by VanyaNexus** [konsolas/AAC-Issues#2130]
### Issue description
In this situatuions users laggs in blocks (fence, door) and can't move outside. When trying to teleport the player kills
https://www.youtube.com/watch?v=spzZQJqzRvo
https://www.youtube.com/watch?v=52irhR0hcTY
https://www.youtube.com/watch?v=DAXfl0tLhNQ

### Core information
**Server version**: paperspigot 1.12.2

**AAC version**: 5.0.8

**ProtocolLib version**: 4.5.1

### Special environment information
**ViaVersion version**: 3.2.1

**ViaBackwards version**: 3.2.0

### Configuration
default

**Comment by loveGhb** [comment]
Use 5.0.10

https://www.youtube.com/watch?v=W78Djaofuao
https://www.youtube.com/watch?v=rDIpy7EAZko
