### ISSUE TITLE
Player blocking when call setVelocity on him

### ISSUE THREAD

**Issue by VanyaNexus** [konsolas/AAC-Issues#2131]
### Issue description

https://www.youtube.com/watch?v=K65Jn8LDZ0I

 Same problem when calling Player#setVelocity from other plugins
 
### Core information
**Server version**: paperspigot 1.12.2
 
**AAC version**: 5.0.8
 
**ProtocolLib version**: 4.5.1

**Plugins**: GrapplingHook 1.5.9
 
### Special environment information
**ViaVersion version**: 3.2.1
 
**ViaBackwards version**: 3.2.0
 
 
### Configuration
default

**Comment by VanyaNexus** [comment]
With new version calling Player#setVelocity blocking stronger than in the previous version

**Comment by konsolas** [comment]
![image](https://user-images.githubusercontent.com/9408210/107859961-cbb62a00-6e34-11eb-9221-77b6f8d660f4.png)

Don't teleport the player at the same time
