### ISSUE TITLE
[Bug] Wrong threshold execute commands?

### ISSUE THREAD

**Issue by zMick1** [konsolas/AAC-Issues#2133]
Hi, I think there is a problem with executing commands based on the violation levels configured in the thresholds. Let me explain better by making a small preamble.
With the old version of AAC (4) I used to configure the various thresholds in this way (for example, I write it simplified):

50: "sends a message in a dedicated chat alerting a slight suspicion about a player"
100: "sends another message indicating that it is mildly suspicious"
150: "send one last message stating it's very suspicious"
200: "kick the player and send another message in that chat saying he was kicked"

You may be wondering "what is the point of sending messages in a dedicated chat if alerts from suspicious players already exist in AAC5?". I need it as I can't enable either the "bungeecord" or "MySQL" feature in the config, so I need a way to get the notification of suspicious players to the moderators on whatever server they are, before of course the player gets kicked. For this reason I have created a dedicated chat on my server that can be viewed by all staff members.
And here comes the problem, as the type of configuration I wrote earlier doesn't work with AAC5. It always happens to me that as soon as the player reaches the minimum "Scoring" set in the threshold, AAC executes the maximum scoring command. Example: in this config 50 is the minimum and 200 is the maximum => AAC executes the command of 200 even if the Scoring is 50.
I do not know if I have explained myself correctly or if I have configured it incorrectly, in any case now I post evidence that demonstrates what I have reported. (I also asked other users and they told me that they all have the same bug)

Console: https://i.imgur.com/8LX7uM1.png (as you can see it printed "94" of Scoring before executing the commands, while executing the "200" commands wtf?)
Config: https://i.imgur.com/gK8Gaxd.png
 
### Core information
**Server version**: 1.8.8 paper

**AAC version**:  5.0.7

**ProtocolLib version**:  4.5.0

### Special environment information
**ViaVersion version**: 3.2.1

**ProtocolSupport version**: //

**ViaBackwards version**: //

**BungeeCord plugins**: //

**Comment by CeIebrimbor** [comment]
Should be fixed in an update later this week - per Konsolas
