### ISSUE TITLE
Failed to pull entity hitboxes from NMS. Using default hitbox. (Class not found: net.minecraft.server.v1_13_R2.VoxelShapeCollision)

### ISSUE THREAD

**Issue by bobbyfc** [konsolas/AAC-Issues#2140]
I get this error spammed in console: 
https://pastebin.com/Dg9pU7cL

**Server version**: Paper 1.13.2

**AAC version**: 5.0.9

**ProtocolLib version**: 4.5.0

**ViaVersion version**: 3.2.1

Using Celebrimor's latest 5.0.9 AAC config

**Comment by konsolas** [comment]
Multicraft is cutting off the actual error. Please paste latest.log somewhere.

**Comment by bobbyfc** [comment]
> Multicraft is cutting off the actual error. Please paste latest.log somewhere.

Apologies. Here is the full error from latest.log https://paste.ee/p/Mb5Q9

**Comment by LoXR** [comment]
Unsure if this is part of the same issue I was having: https://github.com/konsolas/AAC-Issues/issues/2148

**Comment by bobbyfc** [comment]
> Unsure if this is part of the same issue I was having: #2148

I am still having a similar issue as mentioned by @LoXR and in #2148. Also unsure if that is related to this issue, #2140

**Comment by bobbyfc** [comment]
This issue is still persisting in AAC 5.0.11.
