### ISSUE TITLE
AAC reach false positive when a player is running in circles in a mob farm (endermen)

### ISSUE THREAD

**Issue by ChiboYen** [konsolas/AAC-Issues#2141]
### Issue description
https://pastebin.com/gLbzqNEM

The player was kicked, here is their status:

```
[23:52:22 INFO]:  Scoring (113)
[23:52:22 INFO]:   - The player attacks 0.3683 blocks further than normal
[23:52:22 INFO]:   - The player recently joined from a new ip address
[23:52:22 INFO]:   - The player recently joined for the first time
```

### Core information
**Server version**: 1.16.5

**AAC version**: 5.0.9

**ProtocolLib version**: b492 dev

### Special environment information
No special environment

### Configuration
The threshold was for the aac hitbox category, at a threshold of 100

**Comment by konsolas** [comment]
The hitbox status is at ~73 in the screenshot above.

In the default config, the lowest threshold group that involves the hitbox check kicks at 200.

Please do not open issues if you're kicking players at thresholds of less than half of the defaults.
