### ISSUE TITLE
AAC spams a NullPointer after updating and starting the server

### ISSUE THREAD

**Issue by imparium-de** [konsolas/AAC-Issues#2143]
### Issue description
AAC spams the console with this error after updating from AAC-5.0.0-pre23 to 5.0.9 and AACAdditionPro 6.4.0 to 6.5.1
```
  | [00:55:03 WARN]: [AAC5] Task #10 for AAC5 v5.0.9 generated an exception
-- | --
  | java.lang.NullPointerException: null
  | at me.konsolas.aac.de.a(de.java:9) ~[?:?]
  | at me.konsolas.aac.de.a(de.java:14) ~[?:?]
  | at me.konsolas.aac.bC.<init>(bC.java:85) ~[?:?]
  | at me.konsolas.aac.b9.<init>(b9.java:55) ~[?:?]
  | at me.konsolas.aac.e7.a(e7.java:35) ~[?:?]
  | at me.konsolas.aac.e7.a(e7.java:107) ~[?:?]
  | at me.konsolas.aac.timings.CheckTask.run(CheckTask.java:4) ~[?:?]
  | at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-393]
  | at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-393]
  | at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1289) ~[patched_1.16.4.jar:git-Paper-393]
  | at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-393]
  | at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Paper-393]
  | at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-393]
  | at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-393]
  | at java.lang.Thread.run(Thread.java:834) [?:?]
```
### Core information
**Server version**: git-Paper-366 (MC: 1.16.4)

**AAC version**: 5.0.9

**ProtocolLib version**: Build #493

**Plugin list**: 
Plugins (54): AAC5, AACAdditionPro, AdvancedHelp, AdvancedRegionMarket, AnimatedFrames*, ArmShopBridge, Backpacks, BeautyQuests, BKCommonLib, BungeeTabListPlus, Citizens, CMI, CMILib, CMIPaperLib, CoreProtect, DiceFurniture, FurnitureLib, FurnitureMaker, HackedCore*, HackedServer*, HeadDatabase*, HolographicDisplays, Iaaddon, IMPBungeeBridge*, IMPLib, IMPSafariNet, IPAUtils, ItemsAdder, Jobs, LagMonitor, Lift, LightAPI, LightCleaner, LoneLibs, LuckPerms, MapManager, MCSS_Bukkit*, Multiverse-Core, MysqlPlayerDataBridge, PacketListenerApi*, PlaceholderAPI, PlotSquared, PlugMan, PremiumVanish, ProtectionLib*, ProtocolLib, TokenManager, UltimateTimber, Vault, WorldBorder, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags
(IMP / IA = Self written)

### Special environment information

**BungeeCord plugins**: 
![image](https://user-images.githubusercontent.com/63745647/105925894-326bd300-6041-11eb-872d-f9f31d59d415.png)
(IMP / IA = Self written)
### Configuration
Stock

**Comment by konsolas** [comment]
Reset your config.
