### ISSUE TITLE
AAC Database error

### ISSUE THREAD

**Issue by GoT-HiM** [konsolas/AAC-Issues#2145]
### Issue description

The problem is this error https://pastebin.com/bi1jqadz. This error appears when I try to connect AAC to the Mysql database, with or without SSL.

### Core information
**1.15.2 PaperMC**: 

**AAC_5.0.9**: 

**4.5.1**: 

**Plugin list**: 

### Special environment information
**ViaVersion or forks are not the problem**: ??

**Don't have**: ??

**Same**: ??

**Same**: ??

**Comment by Janmm14** [comment]
Did you really tried adding `?useSSL=false` to the database name?

**Comment by GoT-HiM** [comment]
If you read, it says in the config to do so
