### ISSUE TITLE
Kick message

### ISSUE THREAD

**Issue by mani1232** [konsolas/AAC-Issues#2150]
### Core information
**Server version**: 1.16.5

**AAC version**: latest

**ProtocolLib version**: latest build

**Plugin list**: CMI

### Special environment information
**ViaVersion version**: latest

**ProtocolSupport version**: no

**ViaBackwards version**: latest

**BungeeCord plugins**: no

**Comment by mani1232** [comment]
add support for kicks so that the reason changes in the CMI plugin

**Comment by konsolas** [comment]
I have no idea what this means.
