### ISSUE TITLE
FastPlace false positives.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2154]

**Comment by CeIebrimbor** [comment]
Likely related to #2151

**Comment by andrewkm** [comment]
A very detailed report we just received regarding this.
Looks like a lot boils down to slower PC's/Internet.
https://ecocitycraft.com/forum/threads/anti-cheat-report-anticheat-on-slower-pc-517-kicks-lag-ghost-blocks.209041/

In the meantime, we've disabled fast_place on our end via the delays check.

**Comment by andrewkm** [comment]
Plugin abandoned.
