### ISSUE TITLE
Fastbreak bypass

### ISSUE THREAD

**Issue by wulfwuud** [konsolas/AAC-Issues#2157]
### Issue description
https://youtu.be/tCyKAl6-BI8
not that important tho

### Core information
**Server version**: 1.12.2

**AAC version**: latest

**ProtocolLib version**: 4.5.1

**Plugin list**: 

### Special environment information
**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: direct connection

### Configuration
default

**Comment by konsolas** [comment]
Merging with #2166
