### ISSUE TITLE
Low optimization for MYSQL high usage CPU

### ISSUE THREAD

**Issue by Haczyn** [konsolas/AAC-Issues#2160]
### Issue description

I am using AAC for several servers(4), the problem is with optimizing the queries sent to mysql over 2000 per second. I checked the logs, and it looks like lack of developer knowledge that you can do insert multiple rows in 1 query lol. Please fix the database spam. Don't want to be rude, but please do insert multiple rows in 1 query to optimize this. 

This is 10 MS of general_log from MYSQL 

 
('2021-02-05 20:31:42.645493', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'FBE13C65AAC1383E8AD5D0EAF1D208ED\', 2, 1.0)'),
('2021-02-05 20:31:42.645719', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'FBE13C65AAC1383E8AD5D0EAF1D208ED\', 1, 0.083333336)'),
('2021-02-05 20:31:42.645944', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'FBE13C65AAC1383E8AD5D0EAF1D208ED\', 3, 0.033333335)'),
('2021-02-05 20:31:42.646196', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'AE07AD7EEF4A3772B789B62F4920D7A6\', 2, 0.85)'),
('2021-02-05 20:31:42.646422', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'AE07AD7EEF4A3772B789B62F4920D7A6\', 1, 0.016666668)'),
('2021-02-05 20:31:42.646648', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'AE07AD7EEF4A3772B789B62F4920D7A6\', 3, 0.016666668)'),
('2021-02-05 20:31:42.646874', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'4A744074A65434E0B2C6173F5D6F8C98\', 2, 0.98333335)'),
('2021-02-05 20:31:42.647100', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'4A744074A65434E0B2C6173F5D6F8C98\', 3, 0.033333335)'),
('2021-02-05 20:31:42.647331', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'FBB8BE028B87348F889B3ED99580E55D\', 2, 0.51666665)'),
('2021-02-05 20:31:42.647559', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'FBB8BE028B87348F889B3ED99580E55D\', 1, 0.05)'),
('2021-02-05 20:31:42.647784', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'FBB8BE028B87348F889B3ED99580E55D\', 3, 0.15)'),
('2021-02-05 20:31:42.648008', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'AB4962335AB031308DF7B3CB2CE3A495\', 2, 0.18333334)'),
('2021-02-05 20:31:42.648232', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'3517B98B93CC371CAE252F9BEE18762E\', 2, 0.71666664)'),
('2021-02-05 20:31:42.648457', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'78000614DD753FDEB40F5B1756322AC6\', 2, 0.48333332)'),
('2021-02-05 20:31:42.648693', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'78000614DD753FDEB40F5B1756322AC6\', 3, 0.033333335)'),
('2021-02-05 20:31:42.648919', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'3834711003093DAAA7C96B727FEDE3E3\', 2, 0.65)'),
('2021-02-05 20:31:42.649148', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'3834711003093DAAA7C96B727FEDE3E3\', 3, 0.26666668)'),
('2021-02-05 20:31:42.649376', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'4AAB1934D82F326CBAFA1377F177B565\', 2, 0.56666666)'),
('2021-02-05 20:31:42.649605', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'4AAB1934D82F326CBAFA1377F177B565\', 3, 0.06666667)'),
('2021-02-05 20:31:42.649829', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'CDB3E31AA1C53C3882A91D4B7D9F6845\', 2, 0.73333335)'),
('2021-02-05 20:31:42.650057', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'CDB3E31AA1C53C3882A91D4B7D9F6845\', 3, 0.033333335)'),
('2021-02-05 20:31:42.650282', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'B965AFF91C423C74AA2128EC44AEC660\', 2, 0.6333333)'),
('2021-02-05 20:31:42.650507', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'B965AFF91C423C74AA2128EC44AEC660\', 3, 0.05)'),
('2021-02-05 20:31:42.650734', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'212411916D81392DA761242C11E5869C\', 2, 0.76666665)'),
('2021-02-05 20:31:42.650961', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'FE49C7BF8E5734338709F1DC41DAB296\', 2, 0.6166667)'),
('2021-02-05 20:31:42.651186', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'FE49C7BF8E5734338709F1DC41DAB296\', 3, 0.016666668)'),
('2021-02-05 20:31:42.651416', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'6E62145A69BC374FB9B2CAC8B87E5C3C\', 2, 0.43333334)'),
('2021-02-05 20:31:42.651645', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'6E62145A69BC374FB9B2CAC8B87E5C3C\', 3, 0.1)'),
('2021-02-05 20:31:42.651874', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'D58B9D004A5737F2A3F53ECA0C6E306F\', 2, 0.51666665)'),
('2021-02-05 20:31:42.652127', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'D58B9D004A5737F2A3F53ECA0C6E306F\', 3, 0.016666668)'),
('2021-02-05 20:31:42.652352', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'C11B85E11A393F1F91A76D34F1525046\', 2, 0.5)'),
('2021-02-05 20:31:42.652585', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'C11B85E11A393F1F91A76D34F1525046\', 1, 0.1)'),
('2021-02-05 20:31:42.652811', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'C11B85E11A393F1F91A76D34F1525046\', 3, 0.1)'),
('2021-02-05 20:31:42.653034', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'7F21D2578A4532F99F7916E19274B3E9\', 2, 0.5)'),
('2021-02-05 20:31:42.653259', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'7F21D2578A4532F99F7916E19274B3E9\', 3, 0.11666667)'),
('2021-02-05 20:31:42.653482', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'E7C3D62697303DC7BB52347418E32EEA\', 2, 0.45)'),
('2021-02-05 20:31:42.653707', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'E7C3D62697303DC7BB52347418E32EEA\', 3, 0.1)'),
('2021-02-05 20:31:42.653935', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'C19E192E0FFC3C8E8ABE2055185DA0B0\', 2, 0.56666666)'),
('2021-02-05 20:31:42.654172', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'FC0AC0668CF43BC3841F258CD7CD8FC3\', 2, 0.43333334)'),
('2021-02-05 20:31:42.654404', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'E7693858CE03379A9B027648FB2302BA\', 2, 0.16666667)'),
('2021-02-05 20:31:42.654637', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'E7693858CE03379A9B027648FB2302BA\', 3, 0.016666668)'),
('2021-02-05 20:31:42.654863', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'D2D062982FD23CB996440798C1B1DFEA\', 2, 0.53333336)'),
('2021-02-05 20:31:42.655125', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'D2D062982FD23CB996440798C1B1DFEA\', 1, 0.033333335)'),
('2021-02-05 20:31:42.655314', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'D2D062982FD23CB996440798C1B1DFEA\', 3, 0.016666668)'),
('2021-02-05 20:31:42.655392', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'67C1667EE5083CD6A9E03A4A952F952A\', 2, 0.93333334)'),
('2021-02-05 20:31:42.655455', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'67C1667EE5083CD6A9E03A4A952F952A\', 1, 0.06666667)'),
('2021-02-05 20:31:42.655514', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'67C1667EE5083CD6A9E03A4A952F952A\', 3, 0.11666667)'),
('2021-02-05 20:31:42.655582', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'0E89D11C9BF13B9AB37EC3DD64EBD09A\', 2, 0.11666667)'),
('2021-02-05 20:31:42.655642', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'0E89D11C9BF13B9AB37EC3DD64EBD09A\', 3, 0.016666668)'),
('2021-02-05 20:31:42.655710', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'F6B56DC6CC4E31FDB25784720A5B49DF\', 2, 0.06666667)'),
('2021-02-05 20:31:42.655779', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'7132B29B68E735A5A6DF8367199FC1DE\', 2, 0.11666667)'),
('2021-02-05 20:31:42.655840', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'92D02A0F1A1730E6920F9F15DCF8D7D4\', 2, 0.1)'),
('2021-02-05 20:31:42.655899', 'u48_PD0axFND4E[u48_PD0axFND4E] @  [172.18.0.12]', 31149, 0, 'Query', 'INSERT INTO `aac_events`(`time`, `uuid`, `type`, `data`) VALUES (\'2021-02-05 20:31:42\', x\'92D02A0F1A1730E6920F9F15DCF8D7D4\', 1, 0.016666668)'),

### Core information
**Server version**:  
This server is running CraftBukkit version git-PaperSpigot-4c7641d1 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) 
This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**AAC version**: 
5.0.10
**ProtocolLib version**: 4.5.1

### Special environment information
**ViaVersion version**: 
ViaVersion 3.2.1
**ViaBackwards version**: 3.2.0

**Comment by konsolas** [comment]
AAC already uses batched inserts, so you might want to consider adding `rewriteBatchedStatements=true` to the database name - see https://stackoverflow.com/questions/26307760/

**Comment by new-sashok724** [comment]
Hello! I think it should be solved not by batching, but by minimizing rows count. 2000 inserts per second is not acceptable in any case for just 4 servers, be it batched or not.

I see two possible solutions: either store exactly one row per username with all necessary info needed (for example, dump it on player exit as single value), or use something more suitable for task (Redis? Some NoSQL database? Apache Kafka?)

Also, it would be good to add indexes on aac_events table. Without indexes, it will be painfully slow when accessing this table.
`ALTER TABLE aac_events ADD INDEX (time), ADD INDEX (uuid), ADD INDEX (type)`
