### ISSUE TITLE
/aac spectate "Go Back" button issue.

### ISSUE THREAD

**Issue by VytskaLT** [konsolas/AAC-Issues#2162]
### Issue description
If you execute **/aac spectate \<player\>** two times and then click the go back button, you will be teleported to the first player that you did the command on, and not your actual location before you started spectating.

For example, you can teleport to anyone in the test server by doing:
/aac spectate \<player\>
/aac spectate \<player\>
/aac spectate (same as the go back button)

### Core information
**Server version**: 1.16.4

**AAC version**: 5.0.11

**ProtocolLib version**: 4.6.0-SNAPSHOT-b492

### Special environment information
**ViaVersion version**: 3.2.1

### Configuration
I'm on the test server.

**Comment by TheosisOfficial** [comment]
Server version is actually 1.16.5***
