### ISSUE TITLE
[Feature Request] Anti-Levitation Check

### ISSUE THREAD

**Issue by Kylepoops** [konsolas/AAC-Issues#2170]
### Issue description

there's a type of cheat called Anti-Levitation cannot be detected by AAC5, it's cool if you can add a check of this.

### Core information
**Server version**: 1.16.5

**AAC version**: 5.0.11

**ProtocolLib version**: 4.6.0-SNAPSHOT-b493

**Comment by konsolas** [comment]
Can you clarify what anti-levitation does?

**Comment by Kylepoops** [comment]
> Can you clarify what anti-levitation does?

Player won't levitate when they have levitation effect
