### ISSUE TITLE
Rapidly hitting group of entites (endermen farm) may cause hitbox false positives

### ISSUE THREAD

**Issue by ChiboYen** [konsolas/AAC-Issues#2175]
### Issue description
To reproduce, use a sword with a sweeping edge enchantment around a 3x3 area full of entities (in this case, endermen). As you kill the entities, more must take their place and continuously spawn.

Debug log:
https://pastebin.com/TSsMy0A9

Status:
```
[00:54:42 INFO]:  Scoring (180)
[00:54:42 INFO]:   - The player attacks 0.5177 blocks further than normal
[00:54:42 INFO]:   - The player recently joined from a new ip address
[00:54:42 INFO]:   - Insufficient data to analyse the player's combat
[00:54:42 INFO]:   - Insufficient data to analyse the player's interactions
[00:54:42 INFO]: Generated by AAC 5.0.11
```

### Core information
**Server version**: 1.16.5

**AAC version**: 5.0.11

**ProtocolLib version**: 4.6.0

### Configuration
Hitbox mitigation is false, and this may have prevented this issue from being exposed on other servers

**Comment by ChiboYen** [comment]
Here's another instance of this happening:
https://pastebin.com/6Mjtbgux

**Comment by konsolas** [comment]
Is this limited to endermen or have you seen it with other tightly packed groups of entities?

**Comment by ChiboYen** [comment]
There's no reason why it would be only specific to endermen, other than maybe the missing entity ID in the logs. I've only had this happen with endermen maybe because the player strafes/rotates around the center of the killing platform. Other types of mass grouping entity based farms in survival are when the player stands still.

To answer your question though, no, the only instances of this happening has been with endermen farms, might be because endermen move often and this messes with the calculations?

**Comment by konsolas** [comment]
I'm thinking more about how endermen do that thing where they vibrate in place, which might affect their hitboxes

**Comment by ChiboYen** [comment]
Yep, to restate that the probable causes are:
- Player moves around a central killing platform, which may complicate the calculations because the rotations are changing constantly
- Endermen hitbox behavior isn't accounted for

**Comment by konsolas** [comment]
Going to disable hitbox check for endermen in 5.0.12
