### ISSUE TITLE
performance problem

### ISSUE THREAD

**Issue by DarkyCat** [konsolas/AAC-Issues#2178]
### Issue description

![изображение](https://user-images.githubusercontent.com/50515714/108623940-98daea00-7463-11eb-9579-ca77b038ec74.png)
Timings AAC loads the server when online 35
In the changes in the 5.0.11 update, I did not see this fix.

### Core information
**Server version**: Tuinity 1.16.5

**AAC version**: 5.0.10 

**ProtocolLib version**: 

**Plugin list**: 

### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**:  ps buildinfo
[17:45:22 INFO]: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2021.01.17 at 12:51:35 MSK, buildhost: https://build.true-games.org, buildnumber: 594, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/fc88d0c25513ddd720fec1103626e33e1ca5c1f6)

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by konsolas** [comment]
Missing timings report

**Comment by DarkyCat** [comment]
https://timings.aikar.co/?id=5b5283c8f422483a8a6cc42c99f36f73#plugins

**Comment by konsolas** [comment]
1. Your server is obviously not running Tuinity
2. There is something seriously wrong going on and most of it is not AAC - 

![image](https://user-images.githubusercontent.com/9408210/108631125-6a0f4480-7460-11eb-8d7e-0d6c5d1af47b.png)

**Comment by konsolas** [comment]
Consider asking the maintainers of AirplaneLite for help with your performance issues
