### ISSUE TITLE
Random Warning (VERY LARGE ONE)

### ISSUE THREAD

**Issue by Demeng7215Official** [konsolas/AAC-Issues#218]
I was just wondering why am I keep on receiving this really annoying warning that appears in my console after a few minutes after the server starts?
**AAC Version:** 1.9.10-b8
**ProtocolLib Version:** 4.1.0-b325
**Plugins that my server is using:**
-AAC
-bChatManager
-BuyCraftX
-MaxBans
-PluginMetrics
-ProtocolLib
-SimpleAPI
-SimplePets
-SuperTrials
-SuperVanish
-Vault
-WorldEdit
-zPermissions

**The random warning: (too long, download at Dropbox)**
https://www.dropbox.com/s/dy4d4woa5uw13kb/latest.log?dl=0

**Comment by konsolas** [comment]
Hello;

AAC 1.9.10-b8 is not compatible with minecraft 1.10. Please read the "Dependencies" section of the overview and download the correct version for your server from "Version History".

**Comment by Demeng7215Official** [comment]
Ooops! Thanks for your time, I will be sure to download the right version! Thanks! 
-_Demeng7215_
~Closed
