### ISSUE TITLE
Blatant flight bypass (High speed, floating above ground & void, etc.)

### ISSUE THREAD

**Issue by ObeyBeastJj23** [konsolas/AAC-Issues#2182]
### Issue description

Player using "Moonx" client is able to bypass fly, blatantly, and killaura. Able to fly over the void, over the ground, at high speed, etc.
Will add video when next occurs.

### Core information
**Server version**: 1.8.8 PaperSpigot-"4c7641d" on servers, Bungeecord is on Travertine

**AAC version**: 5.0.11

**ProtocolLib version**: 4.2.0

**Plugin list**: https://i.obey.pro/gvZsO.png (again, pretty sure they won't interfere)

### Special environment information
**ViaVersion version**: 3.2.1

**ProtocolSupport version**: N/A

**ViaBackwards version**: 3.2.0

**BungeeCord plugins**: None that would interfere 99.9% sure

### Configuration

Have turned of mitigation across all modules, as we had better results across the board without any interruption. Haven't changed any other sections.

https://pastebin.com/gPttmxAW

**Comment by konsolas** [comment]
Missing plugin list and config.yml

**Comment by ObeyBeastJj23** [comment]
Will update, give me a sec

**Comment by ObeyBeastJj23** [comment]
Updated ^

**Comment by konsolas** [comment]
This has been the only report of an 'unlimited' flight bypass so I'm going to close this until there's further evidence / debugging information.
