### ISSUE TITLE
Killaura A5 T3 legit flags 

### ISSUE THREAD

**Issue by afe2c3** [konsolas/AAC-Issues#2188]
### Core information
**Server version**: 1.8.9

**AAC version**: 4.4.2

### Reproduction

Hold Ctrl, W, and D at the same time. Then steadily move your mouse at a constant speed to the right, so that you strafe around a central point. You will be flagged, and after about 4 seconds kicked.

**Comment by CeIebrimbor** [comment]
Please report debug data if reproduced on latest AAC v5

**Comment by Janmm14** [comment]
Not sure if i would classify this as bug or as intended as its mimicing the cheat.

Closing because of old version anyway. AAC 5 also updated killaura checks.
