### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by xique233** [konsolas/AAC-Issues#2189]
May I ask if you can add Chinese support or you can customize the language, it was possible in version 3.6 before, but not afterwards :(, not everyone can understand English

**Comment by Janmm14** [comment]
All kick messages can be edited.
Messages shown in `/aac status` can be edited as well:
https://gist.github.com/konsolas/1ed816ed91996eab7262d95386c1bfa0/#file-config-yml-L279-L417

Which messages should be editable additionally?

**Comment by xique233** [comment]
ok thanks
