### ISSUE TITLE
hitbox fp

### ISSUE THREAD

**Issue by iFlamingoz** [konsolas/AAC-Issues#2190]
This also seems to be happening unintentionally and can be reproduced by just fighting normally.
Video: https://streamable.com/dqhi2s

Core information
Server version: 1.8.8 PaperSpigot

AAC version: 5.0.11

ProtocolLib version: v4.6.0

Plugin list: Will give PL if needed in DMs

Special environment information
ViaVersion version: 3.2.1

ViaRewind version: 1.5.3

ProtocolSupport version: none

ViaBackwards version: none

BungeeCord plugins: I'll give Bungee Plugins if needed but probably isn't causing anything.

Configuration:
Using AAC v5.0.11 | 1 from Celebrimbor and have not made any changes to checks.

**Comment by Oreoezi** [comment]
Same happened to me on the official test server.

**Comment by iFlamingoz** [comment]
The issue still persists with aac_hitbox_miss and seem to false more with it. I can send the debug logs with 0.12 if needed.

**Comment by iFlamingoz** [comment]
aac_aimbot_sync still falses but the combat feels much better now. thank you.

**Comment by iFlamingoz** [comment]
Here's a video of me falsing it with debug logs: https://streamable.com/zm1am2
