### ISSUE TITLE
Feature request - Cancel bad hits

### ISSUE THREAD

**Issue by akosvr** [konsolas/AAC-Issues#2193]
Hey!
I saw that, some anticheat do that Its just block bad hits like killaura and things like that.
When it gives a flag, than it cancels the hit event for like 2 seconds but it's mostily an option in the settings (Perhabs it would be good for other interaction based checks).
AAC is the best anticheat I've ever used, so I'd be happy if you can make that happen.

Have a great day, stay safe!

**Comment by True-cc** [comment]
It would make sense for Reach & HitBox to cancel hits, but not really for AimBot/AutoClicker, but I suppose you could. It's an intriguing idea... Meow (a private anticheat) has AimBot setback which is weird but certainly does stuff (it's annoying to hackers).

**Comment by Janmm14** [comment]
Reach and hitbox currently cancel bad hits (not all) depending in how it is configured.

**Comment by konsolas** [comment]
5.0.14's hitbox check cancels hits by default now.
