### ISSUE TITLE
FP: PacketPlayOutPosition causes movement glitch with AAC5

### ISSUE THREAD

**Issue by amadeusmz** [konsolas/AAC-Issues#2198]
### Issue description

I use PacketPlayOutPosition to make recoil effects, and it causes glitch when AAC is installed as shown in the video.
https://www.youtube.com/watch?v=I1sHPaF1jVw
My code: https://pastebin.com/vtvypaNy

### Core information
**Server version**:  Paper 1.16.5

**AAC version**:  5.0.11

**ProtocolLib version**:  4.6.1-SNAPSHOT-b498

### Configuration
default config

**Comment by konsolas** [comment]
See #2094 and let me know if the workaround is acceptable
