### ISSUE TITLE
[Question] Playerradar

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#22]
Is the feature working?
Which entities does it hide?
Sneaking behind blocks / player behind you with a minimum difference?

**Comment by CeIebrimbor** [comment]
I think the intent was to neutralize a clients ability to basically ping a player outside the server's render distance. It was bugged to death the last time I messed with it on 1.10.

I think he plans on removing it in v3

**Comment by Photon-GitHub** [comment]
He should remove the old check and instead hide entities the player cannot see for sure (behind walls)

**Comment by konsolas** [comment]
Playerradar has pretty much been abandoned, and is going to be removed.
