### ISSUE TITLE
Checks continue to run after they are turned off

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#2201]
### Issue description

It's very strange, but interact check is disabled in the config, 
```
  interact:
    enabled: false
```
but it continues to work and players get suspicious for **aac_interact_break** O_o

### Core information
**Server version**: paper1.12.2

**AAC version**: 5.0.11

**Comment by konsolas** [comment]
Did you run `/aac reset` for those players after disabling the interact check?

**Comment by Pesticidus** [comment]
> Did you run `/aac reset` for those players after disabling the interact check?

I cleared the database (mysql) when I turned this off

**Comment by konsolas** [comment]
Does disabling other checks work?

**Comment by konsolas** [comment]
cannot reproduce.
