### ISSUE TITLE
AAC helps cheaters go through blocks

### ISSUE THREAD

**Issue by Pesticidus** [konsolas/AAC-Issues#2202]
### Issue description

It was in AAC4 as well, but I couldn't report it because AAC5 had already been released. This issue was the deciding factor in upgrading my server from AAC4 to AAC5. But unfortunately, as you can see, this problem also exists in AAC5. I don’t know the name of the cheat client and I don’t have any messages from the AAC other than messages about AAC-induced teleports.

Video: https://youtu.be/Yz8UdNcabYw
Teleportation messages: https://pastebin.com/4eaaMku8

### Core information
**Server version**: paper1.12.2

**AAC version**: 5.0.11

### Configuration
Cel-r cfg

**Comment by Pesticidus** [comment]
@konsolas not fixed
AAC still help go through blocks

But it's gotten much worse now: https://youtu.be/ob5I2gMssUk

**Comment by Janmm14** [comment]
@Pesticidus 
You already have anotger open issue about this:
https://github.com/konsolas/AAC-Issues/issues/2228
