### ISSUE TITLE
Suggestion for hitbox check

### ISSUE THREAD

**Issue by Fxetzi** [konsolas/AAC-Issues#2206]
### Issue description
In my opinion the hitbox_reach check has been improved a lot but it still sometimes happens, that you can hit players a lot of times with reach (in this case 306 times) until it get scored. The video shows this thing (the video starts not at the beginning of the combat):
https://youtu.be/CS0ppnHClwE

So my idea was that ervery reach hit gets scored instantely like the other checks do.

### Core information
**Server version**: 
1.8
**AAC version**: 
5.0.13
**ProtocolLib version**: 
4.5.1

**Plugin list**: 

### Special environment information
**ViaVersion version**: 
3.2.1
**ProtocolSupport version**: ??

**ViaBackwards version**: ??

**BungeeCord plugins**: ??

**Comment by Semmel122** [comment]
Yes, I have the same problem. It would be nice if this would be improved.
