### ISSUE TITLE
v5.0.14: ArrayDeque.remove NoSuchElementException@onPacketReceiving

### ISSUE THREAD

**Issue by DJIronic** [konsolas/AAC-Issues#2214]
### Issue description
Server is giving new error into the console after update.

Here it is: https://paste.brcb.eu/ukihobyfyz.http

### Core information
**Server version**:  1.16.5

**ProtocolLib**: 4.6.0 

**AAC version**:  5.0.14

Running the default config, just MySQL enabled.

**Comment by konsolas** [comment]
-b1
