### ISSUE TITLE
V3 soulsand noslowdown bypass

### ISSUE THREAD

**Issue by v0idst4r** [konsolas/AAC-Issues#222]
Editing the BlockSoulSand code to only slow you down just by a bit instead of 0.4 will completely bypass

**Comment by v0idst4r** [comment]
Tested with "*= 0.95" and doesn't flag at all

**Comment by v0idst4r** [comment]
It also works with webs (see discord for pictures)

**Comment by v0idst4r** [comment]
I've uploaded a video [![here](https://img.youtube.com/vi/Rd1HR4ujyHE/0.jpg)](https://www.youtube.com/watch?v=Rd1HR4ujyHE)

**Comment by half-cambodian-hacker-man** [comment]
Why is this marked as 'wontfix'?

**Comment by v0idst4r** [comment]
@half-cambodian-hacker-man I guess they only focus on more important cheats like Aura and Speed
