### ISSUE TITLE
Fly bypass

### ISSUE THREAD

**Issue by VanyaNexus** [konsolas/AAC-Issues#2231]
### Issue description
 
https://www.youtube.com/watch?v=f66qT94pX6c

I do not know how to reproduce this, the cheater does not say how
 
### Core information
**Server version**: paperspigot 1.12.2
 
**AAC version**: 5.0.14-b1
 
**ProtocolLib version**: 4.5.1
 
### Special environment information
**ViaVersion version**: 3.2.1
 
**ViaBackwards version**: 3.2.0
 
 
### Configuration
default

**Comment by konsolas** [comment]
Merging with #2235
