### ISSUE TITLE
FastBreak false positives.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2239]
Have a user complaining about constant FastBreak false positives.
These are all his logs prior to kick: https://pastebin.com/raw/miCbEikV

### Core information
**Server version**: 1.16.5 (Paper Build 576)

**AAC version**: 5.0.14

**AAC config**: 5.0.14|1-Default-Celebrimbor

**AAC enabled checks**: The following checks are disabled & altered:
delays.fast_place: false
aimbot.enabled: false
hitbox.enabled: false
features.aac_interact_place: 0

**ProtocolLib version**: 4.6.0 Build 498

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by CeIebrimbor** [comment]
OP server?

**Comment by andrewkm** [comment]
No, this user was using a regular tool I believe.

**Comment by CeIebrimbor** [comment]
The report is a little too broad. The conditions to replicate should be included if the debug is not obtainable.

**Comment by andrewkm** [comment]
Plugin abandoned.
