### ISSUE TITLE
Simple Feature Request

### ISSUE THREAD

**Issue by strahil211** [konsolas/AAC-Issues#2242]
Requesting that a config option be added for disabling the console spam.

Example:
[AAC5] Cached 274 blocks. (newest: 1.16.x/minecraft:anvil[facing=north])
[AAC5] Cached 275 blocks. (newest: 1.16.x/minecraft:piston[extended=false,facing=east])

Please yoink these messages, I have no idea what they mean!

**Comment by strahil211** [comment]
Will anyone ever look at this?

**Comment by Maroon28** [comment]
I mean, if you really hate them that much, you can just use something like ConsoleSpamFix on spigot, then put that string in and you should be fine!

**Comment by strahil211** [comment]
> I mean, if you really hate them that much, you can just use something like ConsoleSpamFix on spigot, then put that string in and you should be fine!

Shouldn't need to get a whole separate plugin just for that. I've never seen a plugin do this and not have an option to disable it.

**Comment by strahil211** [comment]
I fixed this by switching to Vulcan, thanks!
