### ISSUE TITLE
AAC v3 Falling on slime blocks takes fall damage

### ISSUE THREAD

**Issue by v0idst4r** [konsolas/AAC-Issues#225]
https://www.youtube.com/watch?v=ONeIHJU-rXE

**Comment by Rqcco** [comment]
This is irreproducible. Use vanilla minecraft to test next time, as this does not seem to occur.

**Comment by Photon-GitHub** [comment]
Read above.

**Comment by Janmm14** [comment]
Your video looks like your jump height is not reduced by slime blocks additionally.

**Comment by v0idst4r** [comment]
It's not reduced because I take damage when I fall and that gives me velocity

**Comment by v0idst4r** [comment]
I mightve accidentally left some test code in my client and that made me take fall damage, but I was sure that fall damage was handled server side

**Comment by v0idst4r** [comment]
I think I was taking fall damage because of rubberbanding in the middle of slime blocks, I'm pretty sure there's already an issue for that so I'll leave this closed
