### ISSUE TITLE
Add Anti UUID Spoof

### ISSUE THREAD

**Issue by BackSam6348** [konsolas/AAC-Issues#2252]
My suggestion is added the Anti UUID Spoof
There are still a lot of users running UUID Spoof. And even though Online-mode=true is set, there are many users who connect with UUID Spoof.

**Comment by Janmm14** [comment]
Will not be added to AAC. AAC is an anti-cheat, the feature  you suggested has nothing to do with cheating.

Solution:
Properly set up your system firewall or use an IPWhitelist plugin on your spigot servers.

Those are the most simple anti uuid spoof methods.

Any plugin claiming to fix uuid spoofing without a configuration is useless / lying.
