### ISSUE TITLE
AAC MySQL Driver Update

### ISSUE THREAD

**Issue by KolakZ** [konsolas/AAC-Issues#2257]
**Issue**: I get the following message on startup and was wondering if the driver for AAC could be changed in the next update.
`[20:44:51 WARN]: Loading class com.mysql.jdbc.Driver. This is deprecated. The new driver class is com.mysql.cj.jdbc.Driver. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.`

**Server version**: 1.16.5

**AAC version**: 5.0.14-b1

**ProtocolLib version**: 4.6.1-SNAPSHOT-b501

**ViaVersion version**: 3.2.2-SNAPSHOT

**ViaBackwards version**: 3.2.1-SNAPSHOT

**Configuration**: https://www.mc-market.org/resources/18783/

**Comment by konsolas** [comment]
Unfortunately the driver shaded into spigot does not seem to have `com.mysql.cj.jdbc.Driver`. The warning should be harmless.
