### ISSUE TITLE
v3 Repeater Setback

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#227]
When you jump and sprint on repeaters, with a block above your head, it will setback with quite a bit of violations. https://www.youtube.com/watch?v=4MLHk6TliGI

**Comment by Janmm14** [comment]
Maybe a generic approach using block hitboxes should be used.

**Comment by Rqcco** [comment]
Seems to be fixed, maybe another HitBox issue was possibly fixed making it not flag anymore. I will close for now.
