### ISSUE TITLE
[Feature Request] Geyser Support

### ISSUE THREAD

**Issue by KolakZ** [konsolas/AAC-Issues#2272]
It would be great to see Geyser support with AAC.

**Comment by Janmm14** [comment]
The current movment check style is not compatible with closed-source clients.
AAC can use Floodgate (5.1.0+: Floodgate 2) to exempt bedrock playersfrom being checked.

**Comment by KolakZ** [comment]
Is there an option in config to enable the exempt or it's there for bedrock clients by default?

**Comment by Janmm14** [comment]
This is not configurable and active by default. You can check it with /aac status playerwhojoinedwithbedrock

**Comment by KolakZ** [comment]
Alright, thanks.
