### ISSUE TITLE
12 turn speed bypass AAC

### ISSUE THREAD

**Issue by ENDER1355** [konsolas/AAC-Issues#2277]
12 turn speed killaura bypasses AAC killaura checks

Both of the turn speeds must be 12

**Comment by Janmm14** [comment]
Not enough information.

**Comment by ENDER1355** [comment]
> Not enough information.

What do you mean? Konsolas's test server did not log, and CCBlueX server is down, I tested this in loyisa's test server

**Comment by SleepyKolosLolya** [comment]
> > Not enough information.
> 
> What do you mean? Konsolas's test server did not log, and CCBlueX server is down, I tested this in loyisa's test server

loyisa has aac4, not aac5

**Comment by Janmm14** [comment]
Also which cheat client etc.

**Comment by ENDER1355** [comment]
> Also which cheat client etc.

"Liquidbounce is a trash client"

~Minemen Staff

I'm using Liquidbounce with my own MMC config.
