### ISSUE TITLE
Question: How does GeyserMC check work?

### ISSUE THREAD

**Issue by ENDER1355** [konsolas/AAC-Issues#2283]
How does GeyserMC check work? Wondering what packet does the PE user has to send to check?

**Comment by Janmm14** [comment]
AAC uses Floodgate plugin on the spigot servers to detect PE users which does custom communication with GeyserMC.
Btw. that detection seems to be broken currently.

**Comment by ENDER1355** [comment]
> AAC uses Floodgate plugin on the spigot servers to detect PE users which does custom communication with GeyserMC.
> Btw. that detection seems to be broken currently.

thought it was a config issue

**Comment by BobIsMyManager** [comment]
Lol

**Comment by ENDER1355** [comment]
> Lol

AAC mods when they can't take a joke

**Comment by BobIsMyManager** [comment]
Wtf is with this opening and closing

**Comment by Janmm14** [comment]
Its called accidental button pressing

**Comment by BobIsMyManager** [comment]
Ok
