### ISSUE TITLE
[AAC5] Task #11 for AAC5 v5.2.0 generated an exception java.lang.NoClassDefFoundError: Could not initialize class me.konsolas.aac.lo

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#2294]
5.2.0 does not work at all.
Upon player login, continuous console spam.
https://gist.github.com/andrewkm/6338e097cc567e4b4e37bd6857f78ff5

### Core information
**Server version**: 1.16.5 (Paper Build 783)

**AAC version**: 5.2.0

**AAC config**: 5.1.0|2-Default-Celebrimbor

**AAC enabled checks**: The following checks are disabled & altered:
delays.fast_place: false
aimbot.enabled: false
hitbox.enabled: false
features.aac_interact_break: 0
features.aac_interact_place: 0

**ProtocolLib version**: 4.7.1 Build 531

**Plugin list**: _(Plugins on request via Discord - andrewkm-0001)_

### Special environment information

**ViaVersion version**: 4.0.2 Build 536

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by NoneTirex** [comment]
I have a similar issue with AAC 5.20 on 1.16.5 version, any update?

**Comment by bobbyfc** [comment]
I am having the same issue, exact same plugin versions/paper version

**Comment by Korinocho** [comment]
Same here, paper 1.16.5 786

**Comment by skw359** [comment]
Had the same issue, just use build 5.1.0 if you're running 1.16.5
