### ISSUE TITLE
[Feature] Settings-packet check

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#23]
I would recommend to check for the Play.Client.SETTINGS - packet as a improvement to the derp check as a vanilla client cannot send this while sprinting/sneaking (or other own movement).
This would be an unbypassable check (yes, I am pretty sure about that) for SkinBlinker and FoV-modifying-Zooms.

You can handle sprint/sneak - violations as high amounts of vl as this is certainly not possible in vanilla minecraft.

Another question: How can we apply for getting a place on the whitelist of your test-server 😃 ?

**Comment by konsolas** [comment]
It's currently not up yet. It could take a few days, lots of studying to do atm.

**Comment by CeIebrimbor** [comment]
Booooo. Studying is for dumb people. :)

**Comment by Photon-GitHub** [comment]
Will be present in AACAddition.
