### ISSUE TITLE
Fastattack II

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#230]
It seems that clients can fake the haste effect clientside to attack faster than normally allowed.

**Comment by Janmm14** [comment]
Is this about the noDamageTicks of the enemy or why does this bypass?

**Comment by Janmm14** [comment]
How does it allow faster attacking than normal clients?

**Comment by Photon-GitHub** [comment]
Haste allows cheaters to hit faster and a simulated haste effect makes it easier to hit players right after the hurttime.

**Comment by CeIebrimbor** [comment]
@Photon-GitHub Is this still valid? More proof?

**Comment by Photon-GitHub** [comment]
Yes it is still valid, take a look at cheating-videos in which the client spoofs haste clientsided.

**Comment by Janmm14** [comment]
@Photon-GitHub is this issue applying to 1.9+ only or also 1.8?

**Comment by CeIebrimbor** [comment]
The haste potion does not do anything to the cooldown time between max charged hits, so I only see this as an issue for 1.8 combat. But does Fightspeed not cover this?

This was opened before AAC v3.0.0, so I'm just curious if it's valid, relevant, important, etc.

**Comment by CeIebrimbor** [comment]
> The haste potion does not do anything to the cooldown time between max charged hits in 1.9 combat, so I only see this as an issue for 1.8 combat. But does Fightspeed not cover this?

This is actually inaccurate. The cooldown is not noticeable in the Haste 1-5 range, but potion levels above 5 are significant. Is this bypass a packet (zoot) hack applying fake potions? Assuming it's not caught by Badpackets, is it caught by Move now?

**Comment by Janmm14** [comment]
Closing due to missing information.
