### ISSUE TITLE
ERROR: Failed to inject into PlayerConnection.class

### ISSUE THREAD

**Issue by madsb2004** [konsolas/AAC-Issues#2307]
### Issue description
Console log:
https://pastebin.com/zhXTYc68

Plugin list:
https://gyazo.com/b00deb7f516f46d3648b3b7bbe6e3673

### Core information
**Server version**: 
- Paper 1.8.8

**AAC version**: 
4.3.5

**ProtocolLib version**: 
-4.6.0
**Plugin list**: 
https://gyazo.com/b00deb7f516f46d3648b3b7bbe6e3673

### Special environment information
**ViaVersion version**: ??
3.20
**ProtocolSupport version**: ??

**ViaBackwards version**: ??
- I Use ViaRewind 1.5.3
**BungeeCord plugins**: ??

**Comment by Janmm14** [comment]
AAC jar file modified
