### ISSUE TITLE
[AAC5] Task #11 for AAC5 v5.2.0 generated an exception java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Brand0n1** [konsolas/AAC-Issues#2319]
**Error**
[AAC5] Task #11 for AAC5 v5.2.0 generated an exception java.lang.NullPointerException: null

Can reproduce by loading AAC in 1.18

### Core information
**Server version**: 
1.18

**AAC version**: 
5.2.0 

**ProtocolLib version**: 
4.7.0

**Plugin list**: 
ClearLag, Core Protect, LiteBans, LuckPerms, Marriage master, placeholderapu, TAB v3.8.1, Towny, Towny Chat, Vault, world edit, world guard
### Special environment information
**ViaVersion version**: ??

**ProtocolSupport version**: ??

**ViaBackwards version**: ??
N/A

**BungeeCord plugins**: ??
N/A

### Configuration
I haven't changed the config

**Comment by HexedHero** [comment]
AAC doesn't support 1.18.
