### ISSUE TITLE
v3 Block/Chunk update

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#233]
Have a certain VL (maybe 5) in Jesus and Phase trigger a chunk/block update to alleviate the possibility of a glitched block (super common) trapping and/or triggering detection for a player. 

Solve the Grief Prevention water border blocks flagging for Jesus as well?

**Comment by Janmm14** [comment]
There is a new command named /aacrestorechunk already available for this.

**Comment by CeIebrimbor** [comment]
Oooo, fancy. Missed that one.
