### ISSUE TITLE
Rethink version system of AAC

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#235]
I think AAC needs a good versioning system in the future: 3.a.b

The versioning system for AAC 1.x /2.x seems pretty random.
The changelog didn't included many big improvements when you bumped the second number, but some big changes were done in some builds and you just increased the build number.

I suggest that if the changes you've done include some bigger new features (ex: api improvements, some new killaura heuristics, added illegalsprint check, overhauled violation system, [maybe also: fixing huge false positive]), you can increase the second number (obv. this sets third number to 0).

If the changes only include small false positive fixes, small new features, making some checks more strict or other little generic changes (ex: fixing #227, adding a disable/enable all checks button in the admin gui, completely stop slower original aac-jesus hack, Fixing broken /aacrestorechunk command), the third number of the version should be increased (and if its at 9, it simply turns into 10).

These are my thoughts of good versioning of software.

Also if you somehow stick with build numbers, please include them into /version AAC and /aac.

**Comment by geNAZt** [comment]
So basicly semver xD

**Comment by CeIebrimbor** [comment]
AAC 3².5a-b11-REMASTEREDv2(Alpha)

**Comment by Janmm14** [comment]
@geNAZt Well its basically like that and I know semver, but semver states its only for projects with a public api and the api of AAC is clearly not the main part of the project, so I decided to basically remove that part.

**Comment by konsolas** [comment]
This will be used.
