### ISSUE TITLE
Speed Hack FP (AAC v3)

### ISSUE THREAD

**Issue by enChat** [konsolas/AAC-Issues#237]
Tested on the 1.10.2 test server.

Since you're unable to break blocks, breaking items which you can break in 1 hit with another of the same behind it (like in this picture: http://i.imgur.com/DKwaep2.png ) and holding down left click will cause AAC to think that you're speed hacking.
You can also do it with 1 item (which can be broken in 1 hit) but there needs to be a block behind it and it takes a bit longer.

**Comment by Janmm14** [comment]
Possibly related to #217 and #157

**Comment by konsolas** [comment]
Fixed, tested by Camirlot.
