### ISSUE TITLE
[Minor bug] Double verbose messages

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#24]
On server-start with verbose enabled all "enabled check xyz" - messages are spammed in the console both in normal and in verbose mode:

18:23:17 [INFO] [AAC] (CheckManager) Enabling check world.NoSwing
18:23:17 [INFO]  * [AAC] (CheckManager) Enabled check world.NoSwing
18:23:17 [INFO] [AAC] (CheckManager) Enabling check world.ImpossibleInteract
18:23:17 [INFO]  * [AAC] (CheckManager) Enabled check world.ImpossibleInteract

**Comment by konsolas** [comment]
This is intended for verbose mode.
