### ISSUE TITLE
v3 Regen VL Accumulation

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#240]
The new regen seems to be super safe sided for 1.9+ and the anticipation for the saturated regen(higher possibility for false positives).
      10: "aacstaffnotify {player} is suspected for Regen (ping = {ping}, tps = {tps})"
      30: "aackick {player} Regenerating health too quickly"

This discounts the detection prowess in 1.8 where the buffer isn't needed. Instead of letting the end user compensate in the config, I think the VL accumulation in 1.8 should just double(triple?).

1.8 regen thresholds should(roughly) look like this in comparison:
      3: "aacstaffnotify {player} is suspected for Regen (ping = {ping}, tps = {tps})"
      12: "aackick {player} Regenerating health too quickly"

**Comment by konsolas** [comment]
Regen vl now increases twice as quickly for 1.8 servers.
