### ISSUE TITLE
v3 Jump bug

### ISSUE THREAD

**Issue by Camirlot** [konsolas/AAC-Issues#244]
https://youtu.be/ahNoKD98Ff4

**Comment by CeIebrimbor** [comment]
I missed the bug part. What time in the video did the bug occur?

**Comment by Camirlot** [comment]
0:02 - 0:03 The player falls but glitches in the step?
0:11 - 0:12 You can see that the player successfully jumped on the skull (or the block) but gets bugged down
0:19 - 0:20 again ^
0:25 - 0:26 again

**Comment by Rqcco** [comment]
Are you sure this has to deal with AAC? It seems to 'push' the player down faster than normal, in which I never seen AAC behaved. In addition, I'm having a hard time reproducing this on the test server.

**Comment by konsolas** [comment]
I'm bad at parkour; can any tester+ build/test this situation on the most recent test server?

**Comment by Rqcco** [comment]
@konsolas I have, It does bug the person a bit with fly violations.

**Comment by konsolas** [comment]
Fixed with the new ground checking.
