### ISSUE TITLE
v3 BedFucker bypass

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#245]
On the Alpha Centauri client, fucker seems to work. ImpossibleInteract does flag sometimes, but only for VL:0 https://www.youtube.com/watch?v=tyxJ6zDoQJg

**Comment by MinecraftiUndCo** [comment]
On Wurst client (v2.22) the same issue. I can destroy the bed and everytime it is only flagged at vl:0

**Comment by Janmm14** [comment]
breaking shouldn't flag vl 0 normally

**Comment by Janmm14** [comment]
>I made an attempt to fix it in the last update
>~konsolas 16:49 EST

**Comment by Janmm14** [comment]
According to @MinecraftiUndCo this is not fixed yet.
