### ISSUE TITLE
Sleeping in bed with blocks above -> Fly

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#246]
When you sleep in a bed with blocks above it you will be flagged for fly. https://www.youtube.com/watch?v=fJOdpvZPvnU

**Comment by CeIebrimbor** [comment]
This was resolved in #334 (dupe) by using the appropriate verion of ProtocolLib. It was a 1.11.2 server using 4.2 and fixed after update to 4.2.1.
