### ISSUE TITLE
JnR false pos

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#253]
When playing Jumpleague I am sometimes set down and aac cancels my jumps because of "jumping too often". Maybe increasing the allowed jumps a bit (1)?

**Comment by konsolas** [comment]
Really need more specific locations for this.

**Comment by Janmm14** [comment]
Well maybe it could be a similar scenario like in #175?

**Comment by konsolas** [comment]
"Jumping too quickly" has been removed quite a while ago.
