### ISSUE TITLE
WaterWalk bypass.

### ISSUE THREAD

**Issue by JuliCarles** [konsolas/AAC-Issues#258]
Well, when using HEXEON Hacked Client I can bypass WaterWalk on AAC3 Server (Spigot 1.10.2).
This client seems to make "little jumps" on the water but still going really fast.
Here you have some screenshots:
https://gyazo.com/dbb89473a2b30434166734cb2f9b2649 (here you can see how I'm not on the surface but instead just a little bit down)
https://gyazo.com/dbb89473a2b30434166734cb2f9b2649 (here it takes me back to the surface for aprox. 0.1 sec and again takes me down).

Hope you can fix :)

**Comment by Photon-GitHub** [comment]
Jesus detection takes it time, minijump jesus should be blocked. 
Please make a vid while using this on the TestServer, we cannot see anything on pictures.

**Comment by HorizonCode** [comment]
its easy to fix, just check if the player is in water and the from.gety - to.gety equals 0

**Comment by konsolas** [comment]
@HorizonCode bypassed by changing the offset to 0.0000001 and -0.0000001

**Comment by HorizonCode** [comment]
nah, tried that too in my client, not working.

**Comment by Janmm14** [comment]
@HorizonCode Well it should actually be possible to bypass that by adding a little random like -.0001 to .0001 to the y values, right?

**Comment by Janmm14** [comment]
@JuliCarles You linked the same image twice.

**Comment by JuliCarles** [comment]
Just realized I uploaded the same image twice. As I just wanted you to see the bypass, here's a video I did on AAC Test Server. 
At the beggining you can see I'm being dragged back, this was caused because I was pressing SPACE and W, then realized the bypass works just when pressing W.
https://www.youtube.com/watch?v=iEO3zmMCii0

**Comment by Rqcco** [comment]
Information is valid. However, since it's a minor speed bypass and is hard to reproduce, it is not in the top priorities.
