### ISSUE TITLE
[Bug/Bypass] Vehiclefly

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#26]
The boatfly check only checks boats, therefore it is possible to fly with pigs/horses, especially flying with pigs is easy to block as pigs cannot jump as high as horses can.

You can get the max jump-height of a horse by getting the horse-jump-strength (think of special blocks like slime-blocks(higher jump), liquids (no high jumps) and other interesting blocks.)

Even a positionspoof is possible with this because aac sets you back to your start position without fall damage if you leave your pig/horse midair.

**Comment by konsolas** [comment]
Written and tested.

**Comment by Photon-GitHub** [comment]
The patch is working but has a ton of false positives.
I got kicked out of my horse 5 times just by horse-jumping legit.
Also it is VERY buggy on slimeblocks, especially when riding a pig.

**Comment by Photon-GitHub** [comment]
Some false pos:
When standing exactly on the edge of a block while riding a horse you will get flagged all the time.

**Comment by konsolas** [comment]
I'm going to close this in favour of individual, specific issues, such as #85.
