### ISSUE TITLE
Chest and anvil hitboxes are incorrect on server.

### ISSUE THREAD

**Issue by Supereg** [konsolas/AAC-Issues#262]
Video material: https://www.youtube.com/watch?v=Y7Xm4viCMUw
was captured on 1.8 test server

**Comment by Janmm14** [comment]
Phase issue that continues in speed and fly issues. Chest and Anvil hitboxes are not correct serverside in 1.8, thats the problem

**Comment by konsolas** [comment]
Added whitelist to config.
