### ISSUE TITLE
v3 Jumpboost with Fence gates

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#265]
Really self explanatory, if you use jumpboost 2 and try to jump to the top of a fence gate, you get setback.

**Comment by Janmm14** [comment]
Seems to onyl setback when jumping while being directly near the fences

**Comment by Janmm14** [comment]
Possibly fixed by small movement prediction in 3.0.2

**Comment by Photon-GitHub** [comment]
still valid.

**Comment by Photon-GitHub** [comment]
I cannot reproduce this anymore, therefore I will close this as fixed.
