### ISSUE TITLE
v3 | Falling through stairs and half slabs

### ISSUE THREAD

**Issue by Camirlot** [konsolas/AAC-Issues#268]
Actually there is a problem with half steps and stairs where you can fall through the block.

I think it's really hard to reproduce but the thing you need to do is:
Sometimes you can run against the half slab/stair and then you'll fall through the block

A few screenshots and a video below

![2016-12-19_21 12 26](https://cloud.githubusercontent.com/assets/8605812/21327547/fa8a633e-c62f-11e6-967b-986e90fd2682.png)

![b696c2ab81b1446c8a8c2ddb3c10e8a9](https://cloud.githubusercontent.com/assets/8605812/21327577/257c6506-c630-11e6-87f7-f67cbf373050.png)

**Video:**

[![](https://i.ytimg.com/vi/-Uf1SEhT9gY/maxresdefault.jpg)](https://www.youtube.com/watch?v=-Uf1SEhT9gY)

**Comment by Camirlot** [comment]
Here are two videos where you can see in detail the process:

**Video 1:**

[![](https://i.ytimg.com/vi/7afE5yMGF8k/maxresdefault.jpg)](https://youtu.be/7afE5yMGF8k?t=2m20s)

**Video 2:**

[![](https://i.ytimg.com/vi/RqdHfnAOp-w/maxresdefault.jpg)](https://youtu.be/RqdHfnAOp-w)

**Comment by geNAZt** [comment]
We also had this problem. But its really hard to reproduce. Is it possible you have any verbose logs on hand?

**Comment by konsolas** [comment]
Do we know which check people failed?

**Comment by konsolas** [comment]
Fixed and tested on gomme.
