### ISSUE TITLE
IllegalStateException on PlayerMoveEvent: Start blocked missed in BlockIterator

### ISSUE THREAD

**Issue by Supereg** [konsolas/AAC-Issues#273]
Player joined the server and start walking. The following exception was printed three times.
http://imgur.com/a/te8SX

**Comment by geNAZt** [comment]
What server software do you use?

**Comment by Supereg** [comment]
Normal Spigot 1.8
Latest Aac3 release

**Comment by konsolas** [comment]
BlockIterator (upon further testing) appears to throw IllegalStateException in perfectly normal locations, such as a falling into the void and when above the build height of 256.

I am uncertain about what is meant by "start walking", however. Did the player spawn at 257 blocks?

**Comment by konsolas** [comment]
Closing as duplicate of #288 because it has more information than this.
