### ISSUE TITLE
Cannot be cast to net.minecraft.server.v1_8_R3.EntityVillager

### ISSUE THREAD

**Issue by DerStandard** [konsolas/AAC-Issues#274]
When i open the villager inventory:
http://prnt.sc/dns8h9

**Comment by geNAZt** [comment]
Its a problem with the Goobsygames Duell Plugin. It overwrites the NMS Villager and does not include the extension of EntityVillager. getOwner() in 1.8 checks for IMerchant interfaces and casts the result to an EntityVillager. 

So either ask Spigot to fix it or ask the developer of the plugin to fix that. AAC can either swallow the exception or print it out to show whats going on.

**Comment by konsolas** [comment]
This has already been mentioned on the the discussion.

Swallowing the exception is generally considered a worse option, so this error will stay in but can be ignored if you do not wish to correct the plugin.
