### ISSUE TITLE
FAILED TO PULL ENTITY HITBOXES from CraftSkeletonHorse

### ISSUE THREAD

**Issue by timr2000** [konsolas/AAC-Issues#275]
http://pastebin.com/W8DXLL06

**Comment by Photon-GitHub** [comment]
Your server version is apparently not supported. Please use the latest official spigot build.

**Comment by timr2000** [comment]
im using the latest 1.11 spigot build

**Comment by Janmm14** [comment]
An exception does not normally end with
`25.12 23:23:19 [Server] INFO Caused by: java.lang.IllegalStateException: NMS ERROR PULLING ENTITY HITBOXES`
There should be some more lines starting with ` at ...` below the `Caused by` line.

**Comment by Sikatsu** [comment]
I'll just put my error log here with the lines after the` Caused by` line as advised above.

http://pastebin.com/ta0W1KVR

**Comment by konsolas** [comment]
Spigot please, why does CraftSkeletonHorse have no getHandle method.

**Comment by konsolas** [comment]
Fixed.
