### ISSUE TITLE
FastBreak + Farm FPs

### ISSUE THREAD

**Issue by AmazedMender16** [konsolas/AAC-Issues#276]
People getting kicked when using unsafe enchants from
Essentials and when farming carrots potatos and other farmable stuff

**Comment by CeIebrimbor** [comment]
+1 On OP enchant support. Knockback and Efficiency :)

**Comment by konsolas** [comment]
Specific version for farming? Is it a 1.11 only thing? @CeIebrimbor / @AmazedMender16

**Comment by AmazedMender16** [comment]
Im running latest 1.11

**Comment by AmazedMender16** [comment]
1.11.2*

**Comment by AmazedMender16** [comment]
better add label planned again @konsolas its not fixed at all....
people getting kicked using effiency x pickaxe axes and shovels and even with farming

!!! PLEASE FIX IT !!!

**Comment by Janmm14** [comment]
@AmazedMender16 The planned label was removed completely. An issue is planned if a milestone is attached to it.
