### ISSUE TITLE
Fly & Phase issue.

### ISSUE THREAD

**Issue by JuliCarles** [konsolas/AAC-Issues#277]
**Using latest version of AAC v3. (3.0.0-b2) and ProtocolLib 4.2.0.**
I got some fly and phase issues using **default config.**

Players get kicked when pvping on SkyWars (or doing normal stuff)
https://gyazo.com/d7538147c1518007ae58eb97e7065beb
https://gyazo.com/6306edd369123a30c260262026ddc4ba
https://gyazo.com/89ae4e4a059e337ed87c10694351b898

Also, when falling from the cells (the ones above the SkyWars islands)
people are like falling **really slow**, like being teleported, and then, they get kicked for fly.
I fixed the Phase issue by adding LADDER to the Phase Check.

[25-12-2016 21:42:05.059] xXxGmaeMaxXx failed Fly: moved unexpectedly: 0,00 (0,25->0,16) [ping:92 tps:20.0] VL:20
[25-12-2016 21:41:30.150] jeretgamer failed Fly: moved unexpectedly: -0,30 (-0,30->-0,38) [ping:194636779 tps:20.0] VL:33
He was doing nothing, just jumping, running, pvping.

1.10.2 server, using ProtocolSupport to allow 1.8-1.9 users to join.
Hope there's a fix for this, most of my players are getting kicked for Fly.

**Comment by Janmm14** [comment]
I increased fly tolerance from 0.06 to 0.07on my test server already, and the second detection you mentioned should hopefully be gone by doing so.

**Comment by JuliCarles** [comment]
Impossible to know, people get kicked instantly so I can't see the exact situation.
I think it got fixed by increasing this values to:
   tolerance: 0.08
   e_tolerance: 0.4

BUT still, issues like this:
https://gyazo.com/2f059ad268190eea6d75274eda515aa8
who get my players kicked by Fly.

**Comment by geNAZt** [comment]
The invalid fly ability packets are not normal. Vanilla only sends them on Gamemode change (and i don't think you change gamemodes every tick) and when the client decides it wants to fly.

AAC checks if the player is able to fly via getAllowFlight() and checking the gamemode not being spec or creative. 

There is something fishy in the players client for sure.
