### ISSUE TITLE
NoFall false positives.

### ISSUE THREAD

**Issue by JuliCarles** [konsolas/AAC-Issues#279]
Using latest version of AAC v3. (3.0.0-b2) and ProtocolLib 4.2.0; 1.10.2 server using ProtocolSupport.

As you can see in this picture, there are tons of noFall false positives.
https://gyazo.com/6577c005a3ed6096970204e21b543b9e
In this case, VLs were not that high, but in some cases even damage is taken from the player.

(On normal gameplay, running, jumping, etc. on a SW match).

**Comment by geNAZt** [comment]
Do you have videos or a reproduce instruction?

**Comment by konsolas** [comment]
Closing due to insufficient info.
