### ISSUE TITLE
1.8 players can't climb ladders on 1.11 server using ProtocolSupport

### ISSUE THREAD

**Issue by NEZNAMY** [konsolas/AAC-Issues#280]
As the title says, 1.8 players will be flagged for Phase and Phase 2, but not kicked. They completely can't climb ladders. Works fine with 1.11 client. Using latest AAC, ProtocolLib build and default configuration settings for checks. 

http://prntscr.com/dnyq0u

**Comment by NEZNAMY** [comment]
Adding LADDER to phase exclude list fixed the Issue.

**Comment by konsolas** [comment]
Default phase exclusions list updated.
