### ISSUE TITLE
Fly false kick on slabs

### ISSUE THREAD

**Issue by NEZNAMY** [konsolas/AAC-Issues#284]
Running and jumping on slab structure like that http://prntscr.com/do0600 will increase VL (http://prntscr.com/do066j) and lead to a false fly kick. Tested on 1.11 server with ProtocolSupport, happening with both 1.11 and 1.8 client. I have set teleport:false

**Comment by Rqcco** [comment]
Can you make a video please?

**Comment by NEZNAMY** [comment]
Was very hard to reproduce on slabs, but easy on snow.

http://www.filedropper.com/2016-12-2614-00-57

**Comment by konsolas** [comment]
This needs verification, but the fix was written in the last pushed version.

Reopen if still a problem.

**Comment by Janmm14** [comment]
According to @NEZNAMY this is still a problem.

**Comment by Rqcco** [comment]
I'm going to close this issue and combine it with #316 due to more detail.
