### ISSUE TITLE
Flying hack issue

### ISSUE THREAD

**Issue by AmazedMender16** [konsolas/AAC-Issues#285]
when people try to tame a animal like a horse donkey, im getting a message that they will be kicked for fly hacking

just reporting what i see

**Comment by Rqcco** [comment]
I don't get any violations when reenacting this. Is this a bug on 1.8 or 1.10? Also, make a video, need more information.

**Comment by Janmm14** [comment]
It would be nice if you give additionally these informations:

- server version
- client version
- usage of viaversion or protocolsupport
- if applicable bungeecord version & it's plugins

**Comment by AmazedMender16** [comment]
server version: 1.11.2 Latest build
client version: 1.11.2
viaversion: latest version
No Bungeecord

**Comment by Janmm14** [comment]
@AmazedMender16
Why are you using ViaVersion on a 1.11.2 server? Thats pointless.

**Comment by konsolas** [comment]
Closing - cannot reproduce and no info provided.
