### ISSUE TITLE
bug fastplace/nuker

### ISSUE THREAD

**Issue by ProDash1998** [konsolas/AAC-Issues#286]
Antycheats no detect fastplace and nuker sorry for my bad English. Fastplace detects when huzuni set to 2+ and nukers not detect at all. Huzuni 1.8 / 1.10.2

**Comment by Rqcco** [comment]
This is not enough information. (What version, how do you reproduce it, video?) for a Are you sure you have AAC setup correctly?

**Comment by ProDash1998** [comment]
version 3.0 and 1.9.10-b8

**Comment by ProDash1998** [comment]
The video later because currently I'm doing reinstall the system

**Comment by konsolas** [comment]
Seeing as both are blocked and there are no problems with the detection of fastplace/nuker, closing due to insufficient info.

**Comment by ProDash1998** [comment]
Upload video paste it here soon
