### ISSUE TITLE
Spamming jump with Elytra -> Fly/Phase false positive

### ISSUE THREAD

**Issue by AfkF24** [konsolas/AAC-Issues#287]
AAC Version: v3.0.0-b2
ProtocolLib Version: v4.2.1-SNAPSHOT-b345
Plugins:
• AAC v3
• ProtocolLib v4.2.1 b345
• ConditionalCommands v1.2.1
• ViaVersion v1.0.3
Spigot: 1.9.4

Explanation:
Jumping really fast (literally spamming jump) with elytra on, near water/ice on wheat plants (or even on ice generated by FrostWalker) causes some AAC Fly or even Phase false positives. I only tested this on those blocks, some other blocks may be affected as well. Tested multiple times, have video recorded if needed.

Images:
Console output: http://i.imgur.com/gOSrULV.png
Area on which I'm jumping (near water/ice, on wheat): http://i.imgur.com/6wzTGhu.png, http://i.imgur.com/S4Kd9u8.png

**Comment by AfkF24** [comment]
Yeah, that's right, but it says on the AAC Overview page that we should use the latest build... Haha... Don't think that's causing this though...

**Comment by CeIebrimbor** [comment]
#682 is later version.
