### ISSUE TITLE
Hitbox False Positives/Hit Detection

### ISSUE THREAD

**Issue by Mikgreg** [konsolas/AAC-Issues#289]
### Core information
**Server version**: Paperspigot-c0e7853 (1.8.8)

**AAC version**: 3.0.0

**ProtocolLib version**: 4.2.0

**Plugin list**: https://vgy.me/RAY2Rl.png

**ViaVersion version**: 1.0.3

Hi guys, we recently updated to the brand new version of AAC. We decided to use a fully default configuration, and it seems there's lots and lots of false positives. After ~30 minutes of running the plugin every player on the server had triggered multiple hack checks in AAC, and most of them are complaining about bad hit detection since the update (I assume because of cancelled suspicious hits).

**Comment by CeIebrimbor** [comment]
Need a bit more info (like logs and video).

It is likely the Hitbox check. To temp fix the cancelled hits by Hitbox:
cancel: false

**Comment by Mikgreg** [comment]
Here's a recording of it happening taken by one of our admins:

https://www.youtube.com/watch?v=oJwhzrZ_1Ug&feature=youtu.be

Here's also a recording of them fighting with AAC bypass enabled, they don't really lose any hits:

https://www.youtube.com/watch?v=a-63mASPJLo&feature=youtu.be

Let me know if there's anything else I can provide.

**Comment by Rqcco** [comment]
For now, listen to what @CeIebrimbor said.

**Comment by konsolas** [comment]
Hitbox defaults are being updated to 1.0/3.25
