### ISSUE TITLE
v3 Speed potion + Block edge jump

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#29]
https://vimeo.com/187909029

Bouncing off very edge of block with vanilla speed potions.

**Comment by konsolas** [comment]
I have written a fix, and it appears to be working on the test server. I may need you to confirm, though. If you can still reproduce then please re-open the issue.

**Comment by CeIebrimbor** [comment]
Will test next chance I get. I have about 150-170ms ping to the server, so I feel like I'm a decent candidate to test something that sensitive. Unless you are using your software to slow your ping to 300-400 (realistic level for the average laggy player). I don't have that program.

**Comment by Janmm14** [comment]
The edge-block jump also drags back without any potions, just as a note.

**Comment by CeIebrimbor** [comment]
Still? Or pre-patch?

**Comment by Janmm14** [comment]
Pre-patch apparantly.
