### ISSUE TITLE
Velocity accounting in water missing

### ISSUE THREAD

**Issue by MinecraftiUndCo** [konsolas/AAC-Issues#290]
### Issue description

When a player is swimming in water and someone else is hitting him then the swimming player will be detected for Fly (as shown in the video) and sometimes being teleported back.

* You can see verbose output in video
* https://www.youtube.com/watch?v=PNDZbzGIJIo&feature=youtu.be
* MinecraftiUndCo (hitting) & MinecraftlerTyp (swimming player)

### Core information
**Server version**: 1.8.9
**AAC version**: 3.0.0-b2
**ProtocolLib version**: #341 (V. 4.2.0)
**Plugin list**: AAC, AACAdditionPro, ProtocolLib

### Special environment information

**ViaVersion version**: none
**ProtocolSupport version**: none
**ViaBackwards version**: none
**BungeeCord plugins**: Our own plugins (should not affect aac in any way)

**Comment by konsolas** [comment]
Completed.

**Comment by Photon-GitHub** [comment]
Not fixed, still persisting.
