### ISSUE TITLE
Hoe'd land different version hitbox issue

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#291]
Simply by walking/sprinting into fully grown wheat causes for multiple fly and speed false positives. I later on ended up getting stuck inside the wheat, leading to me getting kicked for phase. I was only able to replicate this bug while on 1.11.2, not sure if the new "auto-jump" feature in 1.11 is the cause of it.

https://youtu.be/0QCiqPX-Z4o

###Core information
Server version: Paperspigot-c0e7853 (1.8.8)

AAC version: 3.0.0

ProtocolLib version: 4.2.0

Plugin list: https://vgy.me/RAY2Rl.png

ViaVersion version: 1.0.3

**Comment by Matthew777k** [comment]
It actually seems that hoe'd land (or whatever it's called) is the cause of it, not the wheat. https://youtu.be/gvkpVdGgygo

**Comment by Janmm14** [comment]
To fix the kick add the proper Bukkit Material name into your phase config exemptions. (will allow phasing through)
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by konsolas** [comment]
SOIL is (I believe) currently in the default list for phase exclusions.
