### ISSUE TITLE
Error message (Official spigot?!)

### ISSUE THREAD

**Issue by AmazedMender16** [konsolas/AAC-Issues#293]
https://hastebin.com/kebukawiku.sql

im getting this error, i dont know what is causing it but its saying im not using official spigot while im for sure running official spigot 1.11.2

**Comment by Janmm14** [comment]
CraftWitherSkeletons do not a getHandle method for whatever reason according to konsolas.

**Comment by Janmm14** [comment]
Actually this is a duplicate of #275.
