### ISSUE TITLE
Ghosthand ignores bypass permission & Should not spam the log anymore

### ISSUE THREAD

**Issue by MinecraftiUndCo** [konsolas/AAC-Issues#294]
### Issue description

If you are jumping around and click or break random a block then you will be detected for "out of his line of sight" (always VL:0) this could be caused by little delays between clicking and checking the block.

What is also very strange: I am detected for a hack but I have the AAC.bypass permissions and I am in gamemode 1. Only applies to this check, others are not displayed even when I really hack. (so the AAC.bypass is only broken with this check)

* You can see verbose output in video
* https://www.youtube.com/watch?v=WRwTib6Imtk
* MinecraftiUndCo (jumping around and clicking)

### Core information
**Server version**: 1.8.9
**AAC version**: 3.0.0-b2
**ProtocolLib version**: #341 (V. 4.2.0)
**Plugin list**: AAC, AACAdditionPro, ProtocolLib

### Special environment information

**ViaVersion version**: none
**ProtocolSupport version**: none
**ViaBackwards version**: none
**BungeeCord plugins**: Our own plugins (should not affect aac in any way)

**Comment by Rqcco** [comment]
konsolas will most likely not fix this, as it only flags  vl:0 in verbose, which isn't causing any harm.

**Comment by MinecraftiUndCo** [comment]
But it is spamming the log and the permission is also not working. When I want to analyse the logs I don't want to have 10000 lines of this kind. :( When it is such a small thing then it can be fixed fast. Just don't let verbose out / detection when the vl dont grow.

**Comment by Janmm14** [comment]
My suggestion:
Ghosthand or aac vls in general should provide an option to set how to log violations with vl 0, which defaults to everywhere and you can provide a string with an `a` or all (default), `f` for file, `i` for ingame and `c` for console (use String#contains to check)

**Comment by konsolas** [comment]
Completed.
