### ISSUE TITLE
Fly bypass with Alpha Centauri

### ISSUE THREAD

**Issue by MinecraftiUndCo** [konsolas/AAC-Issues#295]
###Issue description

With Alpha Centauri 0.1a (FLY Mode NCP2) you can fly unlimited distances and only being detected at the start but not being teleported down or anything else while flying. Should be fixed.

* You can see verbose output in video
* https://www.youtube.com/watch?v=8YPmF2cPiPI&feature=youtu.be
* WeshalbDeshalb (using fly)

###Core information
**Server version**: 1.8.9
**AAC version**: 3.0.0-b2 with default config
**ProtocolLib version**: #341 (V. 4.2.0)
**Plugin list**: AAC, AACAdditionPro, ProtocolLib

**Hack client version**: Alpha Centauri 0.1a
**Hack type used**: FLY Mode NCP2

###Special environment information

**ViaVersion version**: none
**ProtocolSupport version**: none
**ViaBackwards version**: none
**BungeeCord plugins**: Our own plugins (should not affect aac in any way)

**Comment by Photon-GitHub** [comment]
Broken config.
