### ISSUE TITLE
World change Player

### ISSUE THREAD

**Issue by Cryptite** [konsolas/AAC-Issues#296]
PLEASE read the CONTRIBUTING.md file which is linked above.
###Issue description

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.

We can't read your thoughts.

Please include details like:
* AAC logs / Full console error
* Video of the bug / bypass, best with verbose chat output
* The ingame name of the involved players

###Core information
**Server version**: insert

**AAC version**: insert

**ProtocolLib version**: insert

**Plugin list**: insert

###Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: insert

**ProtocolSupport version**: insert

**ViaBackwards version**: insert

**BungeeCord plugins**: insert

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here:

**Comment by Photon-GitHub** [comment]
Rly?

**Comment by Cryptite** [comment]
Er, not sure how that did that... I'll update it?
