### ISSUE TITLE
Phase Plant Issue

### ISSUE THREAD

**Issue by SugarRealms** [konsolas/AAC-Issues#299]
###Issue description

If you go on any plant such as wheat the phase detection triggers and makes it impossible for you to move. I'm assuming this is an issue with ViaVersion.

###Core information
Spigot 1.8.8, latest possible 1.8.8 build.

**AAC - Latest

**ProtocolLib - Latest

###Special environment information
Insert 'none' if you don't use it

**ViaVersion - Latest, Spigot (1.8.8) version, not bungee.

**Comment by Photon-GitHub** [comment]
Rly?
