### ISSUE TITLE
[Bypass] Fly bypassed with fake onGround = true

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#3]
Hack clients send a packet where the client claims to be onGround, getting damage and being able to fake a huge amount of velocity (10 blocks or more I feel), allowing flights with occasional half-heart damage.

Each time the player will recieve one nofall violation, but that will not stop him, because they don't trigger it often.

**Comment by Janmm14** [comment]
Example videos:
https://youtu.be/DMxhAw7JkJE
https://youtu.be/wp3SyNJoegg

I got my hands on a cracked version of such a client and therefore I know what violation is triggered.

You should maybe add some damage causes to a list of causes which do not give huge amounts of velocity.

**Comment by konsolas** [comment]
Seems fixed.
