### ISSUE TITLE
v3 Cocoa Beans + Fly

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#30]
https://vimeo.com/187910058

Same report as #10 still exists in v3

**Comment by Krymonota** [comment]
Can confirm, duplicate to: https://github.com/konsolas/AAC-Issues/issues/10

**Comment by CeIebrimbor** [comment]
Still exists in v3 after it was "planned" in v3. Forgot about #10

**Comment by konsolas** [comment]
Will close as it is a duplicate.
