### ISSUE TITLE
Suggestion - Anti-Knockback Server Velocity

### ISSUE THREAD

**Issue by SugarRealms** [konsolas/AAC-Issues#300]
So, I'm sure you're aware of the hack called Anti-Velocity (anti-kb). 

Currently, it only appears to affect players if they do not take knockback from players/mobs hitting them.
I was wondering if you could make it so server-velocities (like a plugin pushing a player) would also be taken into account. So if a player isn't moving after getting a large server velocity, and isn't lagging, then perhaps run anti-knockback commands?

This would be useful for plugins that attempt to restrict players from entering certain zones, but players can just use Anti-velocity to bypass it.

**Comment by Photon-GitHub** [comment]
Antikockback check is already in aac.

**Comment by Janmm14** [comment]
@Photon-GitHub Did you read it or do you know that server-side velocities are handled by the antiknockback check already?
