### ISSUE TITLE
Elytra(Fly) Issues

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#301]
**Issue 1**
~Jump toggle spamming the Elytra near the ground raises VL. It may seem like a stupid activity, but it is now the go to method of launching with the rockets in 1.11.1.~

**Issue 2**
Using rocket boosting w/ Elytra underwater will get you kicked super quick.

I was making videos but had issues, got ticked and realized these are self explanatory.

Server: PaperSpigot (Latest)
AAC: 3.0.0-b2
ProtLib: Latest

No ViaVersion, ProtSupp, BackwardsVia, Bungee, etc.

fly:
   enabled: true
   reduce_delay: 12
   tolerance: 0.06
   e_tolerance: 0.2
   vl_multiplier: 6.0
   min_vl: 80
   vel_ticks: 12
   teleport: true

**Comment by Janmm14** [comment]
Issue 1 already reported in #287, not sure what to keep so I'll just notify.

**Comment by CeIebrimbor** [comment]
Similar to #382 on new version (after movement rewrite)
