### ISSUE TITLE
Interact Spam

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#303]
Interact Spam seems too be pretty aggressive.

http://www.dailymotion.com/video/x56j90n

Server: PaperSpigot 1.11.2
AAC v3.0.0-b2
ProtocolLib: Latest

interact:
   enabled: true
   cancel_liquids: true
   cancel_ghost_block: true
   cancel_dead: true
   cancel_item_attack: true
   cancel_ghost_attack: true
   cancel_vl_interact: 8
   cancel_vl_place: 6
   cancel_vl_break: 3

**Comment by CeIebrimbor** [comment]
Partial dupe of #294

**Comment by Janmm14** [comment]
I've put the interact spam fully into #294.
