### ISSUE TITLE
AAC not working after rename

### ISSUE THREAD

**Issue by Sitmobedaf** [konsolas/AAC-Issues#305]
AAC does not require advertising. I renamed it because some players have access to the list of plugins. But this is not the main problem. Even when I returned to the AAC standard called it anyway it does not work.
I will ask not to close my tickets without my consent, you have the wrong level of support, plugin is paid. Anti-piracy problem will remain at your side. Plugin any case, must obey the data from plugin.yml. With EWG had no such problems. Now plugin its name does not work.

**Comment by NEZNAMY** [comment]
Default jar works fine. This "Issue" has already been closed.

**Comment by sponges** [comment]
**I will ask not to close my tickets without my consent, you have the wrong level of support, plugin is paid. **

**Comment by Janmm14** [comment]
As people on your server can already simply do `/aac` or try out any other aac command, its senseless to hide it in the plugin list.

Additionally you can disable access to the plugin list and other related commands by negating certain permissions.

If you want to hide certain plugins in your plugins list, I'm sure there are plugins out there that can fake the `/plugins` output, or you could use a plugin like CommandRewriter (you would have to set it up for every alias of `/plugins` however)

See http://wiki.bukkit.org/CraftBukkit_Commands for a list of permisssions for the default commands.
I personally recommend negating both bukkit and minecraft permissions for the commands `version`, `help`, `plugins`, `me` and maybe `tell` if you have an extra plugin for that already.
