### ISSUE TITLE
Fly, BadPackets, and Speed false positives

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#310]
Info :

~AAC Command~
~- Please make it so we can disable it in the config again. Like the old days. (/aac)~
~(Or make it so you need a permission node to use it. As of right now, anyone can type it.)~

Fly is giving false positives for knock back dealt on someone.
- If you shoot someone with a bow
- If you hit someone
- If you bow boost

BadPackets, Fly, and Speed sometimes flag when you login to the server or change worlds.
- Maybe make it so there is a 20-40 tick leniency when you switch worlds or teleport more than 500 blocks away where it doesn't check for speed, badpackets, or fly.

Video: https://www.youtube.com/watch?v=meV2YqIwNwk&feature=youtu.be

Config: https://hastebin.com/xuhoneyiwe.bash

**Server Version**: PaperSpigot 1.8 (Image: https://gyazo.com/35040bc1eabd9120ffd795848001ccd1)

**AAC version**: Newest 3.01 (Image: https://gyazo.com/1d2b0118a03e050a77c9d24f55492007)

**ProtocolLib version**: Newest 4.20

**Plugin list**: 22 Plugins (Image: https://gyazo.com/2878bb99654c8feb8f18f00713aa534d)

### Special environment information

**ViaVersion version**: None

**ProtocolSupport version**: 4.24

**ViaBackwards version**: None

**BungeeCord plugins**: 6 Plugins (Image: https://gyazo.com/c320565a7e3167b4aa518dd9535cc3d2)

**Comment by CeIebrimbor** [comment]
Start by setting `abilities:` in Fly to false. The command will be what it is. Believe me when I say I already made my plea with Konsolas.

Are you getting false kicks with Badpackets, or simply some harmless verbose?

**Comment by Janmm14** [comment]
@SnakeDaoust1232 Btw. the /aac command could not be disabled already in AAC 1.9.10.

**Comment by SnakeDaoust1232** [comment]
Just verbose. No kicks yet on the world change. I will test the abilities when i get home.

**Comment by CeIebrimbor** [comment]
Close issue if you feel as though this is harmless. Things get volatile during knockback and teleport, but that is why there is tolerance built in. If you feel as though it's an issue that needs attention, keep it open and make your case.

**Comment by SnakeDaoust1232** [comment]
I meant the bad packets. These bugs are the main issue here.
**
Fly is giving false positives for knock back dealt on someone.

If you shoot someone with a bow
If you hit someone
If you bow boost
**

**Comment by Janmm14** [comment]
You know that your config allowes players to get hit `4.75` blocks away after lag-accounting done by the hitbox check?

**Comment by SnakeDaoust1232** [comment]
CeIebrimbor, I turned off the abilities and it didn't change anything. The issues with knock back still exist.
