### ISSUE TITLE
Make it so it shows the users current CPS in the autoclicker check.

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#313]
A placeholder in the aacstaffnotify to show what CPS the player is getting when he is flagging the check.

**Comment by JustBru00** [comment]
I would also like this placeholder.

**Comment by konsolas** [comment]
Because the checks are fully modular, it's currently not possible to provide placeholders that are dependent on a certain check, because that check can be disabled.
