### ISSUE TITLE
P/59 FP Killaura Heuristic Check

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#315]
Giving false positives for P/59 Killaura Heuristic check when i'm not cheating.

Video: https://www.youtube.com/watch?v=vuHL5FY3-fM&feature=youtu.be

Config: https://hastebin.com/efusamituf.bash

Server Version: PaperSpigot 1.8 (Image: https://gyazo.com/35040bc1eabd9120ffd795848001ccd1)

AAC version: Newest 3.01 (Image: https://gyazo.com/1d2b0118a03e050a77c9d24f55492007)

ProtocolLib version: Newest 4.20

Plugin list: 22 Plugins (Image: https://gyazo.com/2878bb99654c8feb8f18f00713aa534d)

Special environment information

ViaVersion version: None

ProtocolSupport version: 4.24

ViaBackwards version: None

BungeeCord plugins: 6 Plugins (Image: https://gyazo.com/c320565a7e3167b4aa518dd9535cc3d2)

**Comment by Rqcco** [comment]
Informative video.

**Comment by Janmm14** [comment]
I'm unable to watch the video atm, which client (version) was used?

**Comment by SnakeDaoust1232** [comment]
Forge 1.7.10

**Comment by CeIebrimbor** [comment]
AAC doesn't support 1.7 in any form last I knew. With or without ProtSup

**Comment by SnakeDaoust1232** [comment]
It flags on 1.8 as well. Just confirmed

**Comment by SnakeDaoust1232** [comment]
I have video if you need it as well. For proof its on 1.8 as well.

**Comment by SnakeDaoust1232** [comment]
on 1.8 it flags actually more than just p/59, it flags p/59,/51,52.

**Comment by SnakeDaoust1232** [comment]
I didnt mean to close it

**Comment by Rqcco** [comment]
Are you using Viaversion for 1.7 and 1.8?

**Comment by SnakeDaoust1232** [comment]
no, Protocol support for 1.7 support on 1.8 servers

**Comment by Janmm14** [comment]
Sensitivity 2, hmm. Maybe as a temporary workaround you could put the sensitivity on 3.

Just a quick note to your config:
It looks like you are banning for hitbox too early and you allow timer hacks without any limit on your server.

And why you disabled so many checks?

**Comment by SnakeDaoust1232** [comment]
Yeah on sensitivity 3 there are no heuristic false positives. But that config is a little old. I tweaked and tuned it since. Although, I found hitbox was very bugged. No matter what I set the reach to, it always flagged. And I found that if I have the fast now enabled, it screws with potions and arrows. Interact has some false positives as well.

**Comment by Janmm14** [comment]
@SnakeDaoust1232 In that case please create  aticket per issue or comment at existing issues.

For the hitbox issue you could try to set expand hitboxes maybe to 0.9 and reach to 2.8, this allows an effective reach of 3.7 (vanilla 3.5), +hitbox check's own lag compensation.

**Comment by SnakeDaoust1232** [comment]
okay, ill give it a try

**Comment by SnakeDaoust1232** [comment]
Just another update. I was able to trigger p/52 on sensitivity 3 without cheating. After a while of fighting though.
