### ISSUE TITLE
FastEat and Movement false positives

### ISSUE THREAD

**Issue by smessie** [konsolas/AAC-Issues#317]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

_Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.
We can't read your thoughts._

The issues are false positives. I tried it myself and made videos of it.

_Please include details like:
* AAC logs / Full console error
* Video of the bug / bypass, best with verbose chat output
* The ingame name of the involved players_
1. Fast move bug or I don't know which check :')
The bug with the soil and wheat is already solved
https://youtu.be/F0diKraen1A
Verbose: http://pastebin.com/EdLHzzCd

2. FastEat (Regen) false positives
https://youtu.be/cOAMfAl4zII
Verbose: http://pastebin.com/BvVyTFF1

### Core information
**Server version**: 
Spigot 1.8.8

**AAC version**: 
3.0.1
http://i.smessie.com/x6tw1YLJ2z.png

**ProtocolLib version**: 
3.6.4

**Plugin list**: 
http://i.smessie.com/lHi234iZcU.png
I have it too on other servers with less plugins.
Also using ViaVersion on BungeeCord.

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**:
1.0.3 on BungeeCord.

**ProtocolSupport version**: 
none

**ViaBackwards version**: insert
2.0

**BungeeCord plugins**: 
http://i.smessie.com/4QOfX0Q9Js.png

_### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here:_

**Comment by CeIebrimbor** [comment]
For one, update to ProtocolLib 4.2.
