### ISSUE TITLE
Permission AAC.notify do nothing

### ISSUE THREAD

**Issue by xion87** [konsolas/AAC-Issues#318]
### Issue description
I added AAC.notify  to my staff by using powerfulpermission,  they can't read staff chat and receive notifications. instead opped player can do it.

### Core information
**Server version**: 1.8.8

**AAC version**: 3.0.1-b2

**ProtocolLib version**: latest

**Plugin list**: PowerfulPerms, Protocolib

**Comment by Photon-GitHub** [comment]
You probably messed something up as this Permission works for all the others.

**Comment by xion87** [comment]
all other permission nodes work...

**Comment by CeIebrimbor** [comment]
This will still fall on the perm handler. The fact that it works when OP is a clear indication that the perm system is dropping the ball.

That, or you messed up perms. Try giving perms and restarting server. If you are still get the same, ask the perm handler (which I recall being a pricey premium resource?) to support it.

**Comment by gustav9797** [comment]
Now I don't see why you are questioning PowerfulPerms permission handling. It uses an implementation similar to any other permissions system.
xion87, try the following command: "/pp user playername haspermission aac.notify"
It will say if the player has the permission or not, and that's the final internal outcome too.

**Comment by xion87** [comment]
permission exist, but AAC notify don't work

**Comment by Janmm14** [comment]
@xion87 does it work if you try to run /aacstaffnotify command yourself or use the staffchat-prefix?

**Comment by xion87** [comment]
mm he was able to join write in aacnotify, but he was not able to read the admin chat

**Comment by CeIebrimbor** [comment]
Have we established this is unique to PowerfulPerms?

**Comment by gustav9797** [comment]
I hope you don't check permissions through Vault or some other stupid way, if it checks directly through player.haspermission there is no difference between PowerfulPerms and any other permissions system.

**Comment by Janmm14** [comment]
@gustav9797 permissions seem to work with our own permissions system which does not use vault (its not even installed) and it uses bukkit's permissions system

**Comment by gustav9797** [comment]
Where is the relevant code in AAC that checks this permission, could someone link me please?

**Comment by Janmm14** [comment]
@gustav9797 This will not happen. As far as I know, konsolas uses simply `player.hasPermission(string)`.

**Comment by konsolas** [comment]
This is definitely not an AAC bug. Please review your permission handling plugin.
