### ISSUE TITLE
Fly false positivies cages skywars

### ISSUE THREAD

**Issue by JavituRec** [konsolas/AAC-Issues#320]
### Issue description

When users are in Cages of skywars, they try broke glass and the are kicked for "fly". Good anticheat, good work, keep work. :)

### Core information
**Server version**: 1.8.8

**AAC version**: last

**ProtocolLib version**: last

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: last

**ProtocolSupport version**: last

**ViaBackwards version**: none

**BungeeCord plugins**: dynamicantibot, fastlogin, skinsrestorer, serverlisplus, superantiad and nuvotifier.

**Comment by CeIebrimbor** [comment]
Fly: 
`abilities: true`

Please reopen this issue if the problem still occurs after the modification.

**Comment by JavituRec** [comment]
After changed config:
### Fly:
abilities: false

I still have the same problem.

**Comment by CeIebrimbor** [comment]
Ok then. Need some logs and a video with verbose on would be lovely. Other users with an identical issue resolved it by crippling the glide portion of the Fly check.

Something like this:
vel_ticks: 60

**Comment by CeIebrimbor** [comment]
Closing after weeks waiting for more information. Open a new issue with video, logs and plugin information if you are looking for compatibility support
