### ISSUE TITLE
Depth Strider II + III false speed positive

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#324]
Sprinting in the water with depth strider II or III boots on will cause for multiple false speed flags. I also tested out depth strider I but it didn't seem to falsely flag at all.

https://youtu.be/bhfr1q4ZODw

###Core information
Server version: Paperspigot-c0e7853 (1.8.8)

AAC version: 3.0.0

ProtocolLib version: 4.2.0

Plugin list: https://vgy.me/RAY2Rl.png

ViaVersion version: 1.0.3

**Comment by CeIebrimbor** [comment]
Client version?

**Comment by Matthew777k** [comment]
The video was recorded on 1.11.2, however, I'm able to replicate this on 1.8 and 1.9.

**Comment by CeIebrimbor** [comment]
Now thinking about it, that wouldn't matter in this case. But... Any and all info, especially dealing with Protocol Hacks, is always good info.

**Comment by CeIebrimbor** [comment]
So for now you can set `surface_axis_limit` to 0.20 in your Speed setting. You also need to enable the scalar option by removing the "#" before the line.

**Comment by Justinis77** [comment]
Thanks CeIebrimbor :)
