### ISSUE TITLE
Punch + Knockback water false fly flag

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#325]
Hitting a player with a knockback 1/2 sword or punch 1/2 bow while they're at the surface of the water will cause for false fly flags. These false flags only occur while using a knockback increasing enchant. (punch or knockback)

https://youtu.be/1WFInyVRD-g

###Core information
Server version: Paperspigot-c0e7853 (1.8.8)

AAC version: 3.0.0

ProtocolLib version: 4.2.0

Plugin list: https://vgy.me/RAY2Rl.png

ViaVersion version: 1.0.3

**Comment by CeIebrimbor** [comment]
#290 Duplicate
