### ISSUE TITLE
1.11 lilypad compatibility  

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#326]
Jumping onto lilypads or swimming into the side of them will cause for false fly/speed/phase flags.

https://youtu.be/SJXw_O4ixRM

###Core information
Server version: Paperspigot-c0e7853 (1.8.8)

AAC version: 3.0.0

ProtocolLib version: 4.2.0

Plugin list: https://vgy.me/RAY2Rl.png

ViaVersion version: 1.0.3

**Comment by CeIebrimbor** [comment]
Add "WATER_LILY" to the phase item list. I assume this will soon be default.

**Comment by konsolas** [comment]
Not reproducible on vanilla 1.11, so this is a viaversion compatibility problem.

**Comment by xion87** [comment]
I got the same issue, so what i have to do for fix this?

**Comment by CeIebrimbor** [comment]
https://github.com/konsolas/AAC-Issues/issues/326#issuecomment-269889558
