### ISSUE TITLE
Criticals false positive - Carpet + nonenterable regions

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#328]
**Explanation:**
The yellow carpet is where I have a region set in which players cannot enter. If they try to enter they'll be sent back onto the carpet, which causes for them to falsely flag for crits. 

https://youtu.be/J_U0OB8GjUc

###Core information
Server version: Paperspigot-c0e7853 (1.8.8)

AAC version: 3.0.1

ProtocolLib version: 4.2.0

Plugin list: https://vgy.me/RAY2Rl.png

ViaVersion version: 1.0.3

**Comment by Photon-GitHub** [comment]
This should no longer be valid.
