### ISSUE TITLE
idea for nukers

### ISSUE THREAD

**Issue by ProDash1998** [konsolas/AAC-Issues#329]
I thought that a player who uses nukers was formed wall 2x2 block whose current copies. If you will not be watched on zrespione blocks and dig them is to send the message. I recommend it because it runs on the nuker Huzuni 3.5 (real nuker).Polscy Deweloperzy mają anty-nukera ale chcą za to 300zł (polska waluta) /72$.

I hope you accept my proposal.

P.S sorry that I can dimly English. I used a translator

**Comment by Photon-GitHub** [comment]
I am sorry, but I didn't understand your request at all.
