### ISSUE TITLE
Phase false positive with doors 

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#331]
**Explanation:**
Spam opening a door and walking into it when it's claimed either by world guard or by a faction (/f claim) will create false phase flags.

I'm not sure if this flag is intentional or not, as I was not actually using phase in the video. Players also seem to frequently trigger this flag.

https://youtu.be/fhdvZ1gT1CE

###Core information
Server version: Paperspigot-c0e7853 (1.8.8)

AAC version: 3.0.1

ProtocolLib version: 4.2.0

Plugin list: https://vgy.me/RAY2Rl.png

ViaVersion version: 1.0.3

**Comment by konsolas** [comment]
Since this behaviour can be used to actually phase hack, the blocking/detection is intentional.

**Comment by CeIebrimbor** [comment]
I was going to say... Looks like AAC wins in this case.
