### ISSUE TITLE
Not working with ProtocolSupport?!

### ISSUE THREAD

**Issue by Sitmobedaf** [konsolas/AAC-Issues#332]
Plugin has been tested with ProtocolSupport?

**Comment by Janmm14** [comment]
From the overview (nothing new, existed for a long time):

> AAC may be incompatible with:
> * Any sort of protocol hack (apart from ViaVersion 1.8-1.11)

**Comment by Sitmobedaf** [comment]
I tested from Wurst 1.11 (server with ProtocolSupport), anti-hack checks not triggered. After i test from Aristois (cheat client) 1.11.2, without ProtocolSupport. AAC triggered fastFight.

**Comment by Photon-GitHub** [comment]
As Janmm14 already said, that will not be fixed, use ViaVersion.

**Comment by Sitmobedaf** [comment]
ViaVersion does not make sense on the server 1.11.2. ViaVersion does not make sense to use on servers, this is not the right direction. Correct use of new core with support for old clients. On a page of the AAC is not visible inscriptions that are not supported ProtocolSupport. I can not use not his. On my server, playing 50% of the versions 1.7-1.8 and 50% 1.9-1.11. If you do not plan to support ProtocolSupport, the the AAC for me does not make sense, I should not have bought it. Are refunds possible?

**Comment by Sitmobedaf** [comment]
And why do you close a ticket to a complete solution of the problem? Your excuses are not the answer.

**Comment by konsolas** [comment]
I would like to clarify that since AAC 1.7.10, there has been a compatibility message on the overview stating that AAC does not support any Protocol hacks.

This was updated to exclude ViaVersion upon the release of AAC 1.9/2.0/2.1

ProtocolSupport has never been officially supported in the history of AAC. If you did not read this, that is your fault.

**Comment by Sitmobedaf** [comment]
I have more 25 premium plugins in Spigotmc, and ACC turned out to be the most problematic. konsolas, judging from the way you write your most important money, and not the opinion of your customers. Please return the money now.

**Comment by konsolas** [comment]
What the plugin can/cannot do is clearly stated on the overview.

This conversation is pointless.
