### ISSUE TITLE
combat.Killaura false positive 

### ISSUE THREAD

**Issue by bob7l** [konsolas/AAC-Issues#336]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

If you're inside/mounted on a vehicle entity (or on a head), and hit another user rapidly who is also mounted by aiming BACKWARDS, you'll throw "combat.Killaura" false positives. (tried to attack suspiciously)

The issue is most likely related to a bug with YAW/PITCH while riding another entity. It only appears to happen while you're looking directly behind where your vehicle is pointing.

### Core information
Server version: 1.8 spigot latest

AAC version: 3.0.1b2

ProtocolLib version: latest

### Special environment information

The vehicles the users are mounted on are armor stands in my server with modified AI.

**Comment by Janmm14** [comment]
combat.Killaura requires that every player's position on the server is where they are clientside too. And that no plugins modifies the attack target in the packets. It could also be a yaw/pitch issue, depends on how konsolas implemented combat.Killaura.

If you have an own developer you can fix this by cancelling the PlayerViolationEvent with HackType KILLAURA and the player being mounted.

**Comment by Rqcco** [comment]
Video?
