### ISSUE TITLE
Create even higher vls for high diffs to calculated target location

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#338]
People just got vl 11 for being ~1 block too fast in one move.

**Comment by CeIebrimbor** [comment]
You want weighted VL based on difference from expected? (aka A "feature" request).

The title sounds like a request and the one sentence description sounds like a bug report.

Maybe you already talked to konsolas and this is just a reminder for him?

**Comment by SnakeDaoust1232** [comment]
What i think he is saying is that someone failed once and got flagged for violation level 11. I think in the config you can adjust the "weighted violation level". Here is a screenshot.

Correct me if im wrong: https://gyazo.com/f56d55d718bbc7175a8fada124ceeaad

I have mine set to 1 but the default is either 11 or 12.

**Comment by CeIebrimbor** [comment]
They can hit 11 if VLs had been culled and the player was flagged again before hitting 0. Maybe I'm not even on track with what he's saying.

**Comment by Janmm14** [comment]
That config option exists? Well maybe it would be better to use a nonlinear factor to make being a full block too fast at least vl 20 or even vl 30 as I don't think that such things can be false positives.

This is a bug-report tarned as aac-internal feature request

**Comment by CeIebrimbor** [comment]
You know you can label it a bug, yes? :p

**Comment by CeIebrimbor** [comment]
Should not be relevant with default recommended min_vl tolerances in the Speed/Fly check.
