### ISSUE TITLE
Reach false positive [Creative Mode]

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#34]
I think you forgot to check players for creative mode:
Survival/Adventure reach: 4.5 Blocks
Creative reach: 5 Blocks 
I got this values from the minecraft mod coder pack src, so they should be allowed.
I just got kicked from the aac3 server as I tried to kill a creeper in creative-mode.

**Comment by CeIebrimbor** [comment]
I got some block placing/breaking verbose and cancellation while in creative as well. Couldn't remember if that was intentional(always there) or possibly an oversight on v3.

**Comment by Photon-GitHub** [comment]
I got them a lot of times too, especially when clicking fast.

**Comment by CeIebrimbor** [comment]
Spam click placing has always tripped Fastplace. With or without TPS or Ping lag. 

I have always contended for a "VL to band/cancel" for every check. That way owners aren't forced to choose between forcibly stopping and false punishment. They can dial it back and allow for very minor infractions (or false detection) and if a player reached 3 VL for Fastplace it will start blocking until reduced. Same with Fastbreak, but in the later versions Fastbreak seemed to become more and more likely to get a laggy players up to 20 VL, so refinement needs to take place there.

I'll see about getting a video for fastplace later on. I think @konsolas knows it exists though. I think he also has the intention of adding VL to band to all checks. I know he is for Fly.

**Comment by Photon-GitHub** [comment]
BTW: could you also post a vid when jumping some of the step-tests I built? On some of them the previous normal movement check is trowing lots of false positives...

**Comment by CeIebrimbor** [comment]
Just regular jumping? I know Glide labeled players sometimes when jumping in the right spot next to a block. Now that Glide and Fly are combined, maybe lagging down more aggressively? I will test later today. Like 8 hours from now unfortunately...

**Comment by Photon-GitHub** [comment]
Yes, if you join the server the test right next to the long stair is flagging a lot.

**Comment by konsolas** [comment]
Fixed.
