### ISSUE TITLE
1.11 CobbleStone Fences phase/fly false flag

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#341]
Jumping directly on top of cobblestone fences will cause for false phase/fly flags. I was only able to replicate this issue on 1.11, as it didn't happen on 1,8 or even 1.11.2 which is strange.

https://youtu.be/qxA2_Gb5IsI

###Core information
Server version: Paperspigot-c0e7853 (1.8.8)

AAC version: 3.0.1

ProtocolLib version: 4.2.0

Plugin list: https://vgy.me/RAY2Rl.png

ViaVersion version: 1.0.3

**Comment by CeIebrimbor** [comment]
As you may or may not recall, Mojang messed up cobble wall heights in 1.11 and 1.11.1 (or .2) patched this. This would only occur in 1.11 specifically due to a now patched bug.

**Comment by Janmm14** [comment]
## ProtocolLib 4.2.0 build 341

To the people who came here die to a false link:
Here is the link to ProtocolLib build # 341:
http://ci.dmulloy2.net/job/ProtocolLib/341/

**Comment by CeIebrimbor** [comment]
Oops...
