### ISSUE TITLE
Suggestion: Addition to the Configuration, Toggle checks for PvP or PvE.

### ISSUE THREAD

**Issue by Portanna** [konsolas/AAC-Issues#343]
**Server version**: 1.10.2
**AAC version**: 3.0.1-b2
**ProtocolLib version**: #346

AAC is great in checking hacks within players but with mobs it just spams false positives all over. As I do not want to be obliged to shutdown entire checks or to slow them down (as it would be useless to have an anticheat then) I think a cool addition would be a PvP/PvE toggle for the combat checks.

Example:

hitbox:
   Do you want to enable the angle check
   enabled: true

   **Do you want to enable the angle check for PvP, PvE or both?
   entitycheck: pvp**

   How much should AAC expand hitboxes by?
   lenience: 0.5

   Should AAC cancel illegal hits?
   cancel: true
   
   How far should a player be able to reach?
   max_dist: 3.8
   
   Map of violation levels to commands
   thresholds:
      12: "conditionalcommands:cc {player} if (-ping-<180&-ping->0)&-tps->18.5 do aacstaffnotify {player} Killaura (Hitbox) #1 > PING/TPS={ping}/{tps}"
      24: "conditionalcommands:cc {player} if (-ping-<180&-ping->0)&-tps->18.5 do aacstaffnotify {player} Killaura (Hitbox) #2 > PING/TPS={ping}/{tps}"

Like I wrote above, I just need this kind of option in the combat checks, in which I can choose to consider only PvP, only PvE, or both as it is by default.

>    ** Do you want to enable the angle check for PvP, PvE or both?
>    entitycheck: pvp**

**Comment by Photon-GitHub** [comment]
Unimportant as this is rather a workaround than a real solution.

**Comment by konsolas** [comment]
Since ... recently ... the hitbox check accounts for the size of mob hitboxes, so this issue might no longer be relevant.
