### ISSUE TITLE
AntiKB/Fly false positive with fishing rods

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#347]
Explanation:
Spam rodding a player causes for false fly/antikb flags. The account that this was recorded on was on 1.8, but the alt was on 1.11.2.

https://youtu.be/K4zg_cEdmdY

###Core information
Server version: Paperspigot-c0e7853 (1.8.8)

AAC version: 3.0.1

ProtocolLib version: 4.2.0

Plugin list: https://vgy.me/RAY2Rl.png

ViaVersion version: 1.0.3

**Comment by SnakeDaoust1232** [comment]
https://github.com/konsolas/AAC-Issues/issues/310

**Comment by konsolas** [comment]
This has already been fixed, but a duplicate issue was closed.
