### ISSUE TITLE
AAC v3 Random rubberbanding while taking kb and sprint jumping

### ISSUE THREAD

**Issue by v0idst4r** [konsolas/AAC-Issues#348]
**Server version**: 1.8

**AAC version**: 3.0.1

Simply taking a shot from a punch bow or getting hit more than twice while sprint jumping will rubberband you.

**Comment by v0idst4r** [comment]
https://youtu.be/vHaJj-gWBHs
You can see how much I get rubberbanded just in this short clip.
I am using vanilla 1.8 on a 1.8 server without forge or any other modifications.

**Comment by Janmm14** [comment]
I can safely assume your 1.8 server is in fact a 1.8.8 server and you use ProtocolLib 4.2.0 (build #341)? (+your aac is 3.0.1-b2?)

**Comment by SnakeDaoust1232** [comment]
Its probably related the the KB bug that i posted. *https://github.com/konsolas/AAC-Issues/issues/310

**Comment by CeIebrimbor** [comment]
Closing after a month of lacking information to properly diagnose
