### ISSUE TITLE
[Netty Server IO #0/ERROR]: [AAC] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC

### ISSUE THREAD

**Issue by AmazedMender16** [konsolas/AAC-Issues#350]
PLEASE read the guidelines for contributing which is linked above.

Issue description

im getting this error sometimes a day. https://hastebin.com/zixurojozi.bash

Please include details like:
https://hastebin.com/zixurojozi.bash

Core information

Server version: 1.11.2 latest

AAC version: 3.0.1b2

ProtocolLib version: latest

Plugin list:

Special environment information

Insert 'none' if you don't use it

ViaVersion version: 1.0.3

Reporting issues encountered on the test server has these additional rules:

Make sure the bug is still present at time of submitting your issue
Plugin list, log, AAC and ProtocolLib version not required
Note date and time when the issue occurred here:

**Comment by CeIebrimbor** [comment]
**[ProtocolLib.jar:4.2.0]**
This means you are not using latest. Use _actual_ latest for 1.11 servers.

**Comment by CeIebrimbor** [comment]
http://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
