### ISSUE TITLE
combat.Killaura false positive #2

### ISSUE THREAD

**Issue by bob7l** [konsolas/AAC-Issues#352]
### Issue description

while climbing a ladder If you're hitting a user rapidly who is above you and who is also hitting you, you'll get kicked for combat.Killaura extremely quickly.

### Core information

Server version: 1.8 spigot latest

AAC version: 3.0.1b2

ProtocolLib version: latest

**Comment by SnakeDaoust1232** [comment]
Config?

**Comment by Janmm14** [comment]
done for next release
