### ISSUE TITLE
Support colour codes in verbose chat output

### ISSUE THREAD

**Issue by freak-dk** [konsolas/AAC-Issues#354]
Hi

Just wondering if it would be possible for you to add support for colour codes in the chat warnings.
It makes them a lot easier to read. In case I haven't made myself clear these are the warnings I mean
http://prntscr.com/ds693t

Thanks!

**Comment by Rqcco** [comment]
This is possible if you use this "§" symbol for managing colors. For example, aacstaffnotify (player) **§e**is suspected for KIllaura.
