### ISSUE TITLE
Error when Player Moves

### ISSUE THREAD

**Issue by battlecraft25** [konsolas/AAC-Issues#357]
### Issue description

Hey,

Every time a player moves this same error occured. You can see it in the ServerLog.

LG

battlecraft25

Details:
* AAC logs: https://ufile.io/28b131
* ServerLog: https://ufile.io/93974
* Username: battlecraft25

### Core information
**Server version**: 1.9

**AAC version**: 3.0.1-b2

**ProtocolLib version**: 4.2.0

**Plugin list**: AAC, ViaVersion, ProtocolLib

### Special environment information

**ViaVersion version**: 1.0.3

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by CeIebrimbor** [comment]
1.9.0 or 1.9.2?

AAC only supports 1.9.2
