### ISSUE TITLE
[Important Bypass] Fastattack 1.9+

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#36]
The MorePackets-check is not checking when the player is not moving.
I got on the aac3 test-server with my private client and could easily hit 5 times a second with full attack power just by using Timer and not moving...

**Comment by CeIebrimbor** [comment]
I had someone report this before. Players were able to fastmine with mild packet hacks as long as they were standing still. It guess it applies to anything as long as they stand still.

**Comment by konsolas** [comment]
Badpackets has been made stricter, this needs to be verified.

**Comment by Janmm14** [comment]
Is it possible to fastattack even without sending more movement packets?

**Comment by CeIebrimbor** [comment]
That's what "Fightspeed" checks for?

**Comment by konsolas** [comment]
I'm not sure if this was fixed. Need verification @Photon-GitHub.

**Comment by konsolas** [comment]
Detected by BadPackets, but gets 0 vls.

**Comment by v0idst4r** [comment]
Ooh "private client" sounds spooky

**Comment by Janmm14** [comment]
@v0idst4r Useful comment (!!!111). He has a private client which he uses to try find bypasses in aac and tells it konsolas to fix the bypasses (konsolas has the client too).

**Comment by v0idst4r** [comment]
@Janmm14 Rite!!!1!!1!1!1!1

**Comment by Janmm14** [comment]
@konsolas @Photon-GitHub Haze says fastattack is still working. Could this be possible by hitting both killaura-npc's or is your check maybe not working correctly?

**Comment by konsolas** [comment]
Gomme is 1.8?

**Comment by Janmm14** [comment]
@konsolas yes basically

**Comment by Janmm14** [comment]
Any updates on this?

**Comment by Janmm14** [comment]
@Photon-GitHub Is this fixed?

**Comment by Janmm14** [comment]
@Photon-GitHub Is this fixed?

**Comment by Photon-GitHub** [comment]
Still valid, takes way too long to detect (with ~ 50 hits I got vl 140).

**Comment by Photon-GitHub** [comment]
Only important for 1.9+

**Comment by CeIebrimbor** [comment]
This should be addressed in the move check for AAC v3.2.0+
