### ISSUE TITLE
NoFall / Water Bug

### ISSUE THREAD

**Issue by KlausTrophobie** [konsolas/AAC-Issues#361]
false/positive, shown here: (end of vid)
https://twitter.com/murmeltiergames/status/818805433234296832

Log:
[13:57:00] [Server thread/INFO]:  * [AAC] Murmeltiergames failed NoFall: Claimed to be on the ground midair [ping:10 tps:20.0] VL:1
[13:57:05] [Server thread/INFO]:  * [AAC] (NoFall) Dealing 26.944 damage to Murmeltiergames

### Core information
**Server version**: 1.8.8 spigot latest
**AAC version**: 3.0.1-b2
**ProtocolLib version**: 4.2.0

Special environment information

ViaVersion version: 1.0.1
ProtocolSupport version: none
ViaBackwards version: none
BungeeCord plugins: none

* Note date and time when the issue occurred here: 10/01/2017

**Comment by CeIebrimbor** [comment]
Hmm, I was going to say some epic lag, but log says that is not the case.

**Comment by geNAZt** [comment]
The tweet has been deleted. Basicly the FP is that you fall and touch a vine which resets your onground. But AAC does not register that and flag for NoFall

**Comment by Photon-GitHub** [comment]
I tested some jumping on vines and it I could not get NoFall to flag me for it. Therefore I will close this as fixed.
