### ISSUE TITLE
Killaura Heuristics FP | Sensitivity 3

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#363]
Going "hit for hit" triggers kill aura heuristic check.

Video: https://www.youtube.com/watch?v=GvBQWqDazJg&feature=youtu.be

Config: https://hastebin.com/ihaxagebux.bash

Server Version: PaperSpigot 1.8 (Image: https://gyazo.com/35040bc1eabd9120ffd795848001ccd1)
AAC version: Newest 3.01 (Image: https://gyazo.com/1d2b0118a03e050a77c9d24f55492007)
ProtocolLib version: Newest 4.20
Plugin list: 22 Plugins (Image: https://gyazo.com/2878bb99654c8feb8f18f00713aa534d)
Special environment information
ViaVersion version: None
ProtocolSupport version: 4.24
ViaBackwards version: None
BungeeCord plugins: 6 Plugins (Image: https://gyazo.com/c320565a7e3167b4aa518dd9535cc3d2)

**Comment by CeIebrimbor** [comment]
@SnakeDaoust1232 How do those Hitbox settings work out? I think the new default in 3.0.2 will be 1.0 and 3.25 where yours are .9 and 2.8. 

Successful?

**Comment by SnakeDaoust1232** [comment]
They are working fine so far. I tested with around 300ms and it had good lag compensation as well.

**Comment by CeIebrimbor** [comment]
Any false alerts (with exception of a few)? Ideally we find a perfect balance so it is safe to block false hits without fear of cancelling every 3rd hit (like the current default).

**Comment by SnakeDaoust1232** [comment]
My logs are flooded with me hacking :P I will do a test without me cheating and send those logs.

**Comment by CeIebrimbor** [comment]
Lol. No rush. Just curious as to what we can get away with and safely use the cancel feature.

**Comment by SnakeDaoust1232** [comment]
For a gapple fight, its just 8 entries, never exceeding violation level 2.

Although my debug log is spammed with: https://gyazo.com/4df69cbc59558ff54a102e445fceb721

Is that normal xD Or is it just because its debug mode.

**Comment by CeIebrimbor** [comment]
Don't read debug like verbose, no.

Hmm, 8 canceled hits and you have near flawless ping. Want to try 1.0 and 3.25 and see if you can get 0-1 false?

**Comment by SnakeDaoust1232** [comment]
Not 8 canceled, I have canceled hits off. I don't like my players knowing that the anti cheat is picking them up.

**Comment by CeIebrimbor** [comment]
Sorry, 8 detected hits. I want to find out the value that is safe to cancel on basically. Not by having you cancel, but see what 1.0 and 3.25 do.

**Comment by konsolas** [comment]
@SnakeDaoust1232 I will be modifying these two patterns in a general sense to reduce false positives, but we are not able to fully test the changes.

**Comment by SnakeDaoust1232** [comment]
I will test it to the best of my capabilities when you modify it. Thank you
