### ISSUE TITLE
World Downloader prevent request

### ISSUE THREAD

**Issue by arturek1666** [konsolas/AAC-Issues#366]
Hi can you please add something to prevent world downloading I know there is plugins for this as well however i would love to see this feature in AAC, as i don't really want to download extra plugin just for that. I would love to see that in next update.

Thank you 👍, I hope you will if you don't I will not mind I love your plugin anyway, it's just a request :).

**Comment by SnakeDaoust1232** [comment]
Sorry, i have to. You put ACC when its AAC. xD

**Comment by CeIebrimbor** [comment]
Get something dedicated to this task.

https://www.spigotmc.org/resources/ezprotector.12663/
