### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC java.lang.NullPointerException

### ISSUE THREAD

**Issue by MrBeefchop** [konsolas/AAC-Issues#367]
PLEASE read the guidelines for contributing which is linked above.

## **Description**
I am getting this error sometimes when a player joins the game.
**Error:** https://hastebin.com/axozayuqif.go
Maybe it has to do something with ForceResourcepacks, but I do not get the error everytime if a player is receiving a resourcepack

## **Core information**
**Server version**: 1.8.8 lastet Spigot

**AAC version**: 3.0.1b2

**ProtocolLib version**: 4.2.1-SNAPSHOT-b346 (lastest)

**Plugin list**: ForceResourcepack, Essentials, WorldEdit, WorldGuard,...

## **Reporting issues encountered on the test server has these additional rules:**

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here:

**Comment by CeIebrimbor** [comment]
Get build 341 of ProtocolLib. 346 is for 1.11 servers.

**Comment by MrBeefchop** [comment]
I used the other version of ProtocolLib and I still get the error.. sometimes.

**Comment by Janmm14** [comment]
@MrBeefchop Probably not the same error. If you updated to the correct protocollib version for your server, create a new issue with the new error.
