### ISSUE TITLE
Permission only for the AAC GUI : Violations

### ISSUE THREAD

**Issue by Felix5566** [konsolas/AAC-Issues#368]
Can you add a permission only for the AAC GUI : Violations. It can be reached with /aacadmin

I need this with the admins can look whether the players cheating without changing what on the plugin.
please add it

sorry for my bad englisch

MFG Felix5566 (on SpigotMC)

**Comment by Rqcco** [comment]
Possibly.

**Comment by Felix5566** [comment]
Will is it added?

**Comment by Felix5566** [comment]
This are the same: https://github.com/konsolas/AAC-Issues/issues/433 and https://github.com/konsolas/AAC-Issues/issues/412

**Comment by Felix5566** [comment]
Is the feature addet?

**Comment by Janmm14** [comment]
No, because this ticket is still open.

**Comment by Felix5566** [comment]
Do you add it?

**Comment by Janmm14** [comment]
Just konsolas is coding AAC

**Comment by Felix5566** [comment]
I would like to write with konsole, please :)

**Comment by Janmm14** [comment]
*konsolas
Joining the discord usually gives a higher chance to talk with konsolas if you @mention him

**Comment by Felix5566** [comment]
i need too download diskord?

**Comment by Felix5566** [comment]
now i have discord

**Comment by konsolas** [comment]
Adding AAC.manage permission
