### ISSUE TITLE
v3 Moving grounded inside water causes speed false positive

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#37]

**Comment by konsolas** [comment]
http://i.imgur.com/HTJjO5B.png

Test case.

**Comment by Janmm14** [comment]
Seems to only happen while being fully inside water

**Comment by Janmm14** [comment]
looks like the speed false positive onground while being in water only counts if there's also a water block above me

**Comment by konsolas** [comment]
Verified fixed.
