### ISSUE TITLE
Kill-Aura Heuristic Add-on | Must add

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#370]
I have it setup so that there is a delay on the heuristic ban but i just realized that if a player relogs, when they log back in, the heuristic doesn't keep going through, essentially allowing players to bypass the heuristic check.

Maybe make it so there is a spot where you can setup leave commands. So if a player leaves whilst the heuristic check is going through, it will run the commands. Or make it so that if a player is flagged for heuristics, when they log out, it saves the spot, then when they log back in, it picks up where it left off.

**Comment by CeIebrimbor** [comment]
You can just set it to kick on 1 (or 2-3) so it's quicker. heuristic is unique in that it doesn't matter when you kick. The default 10 is just to delay so the player doesn't know what they got caught for.

**Comment by SnakeDaoust1232** [comment]
I understand. The only reason i have it set to like 25 is so that they have the potential to get banned by something else. Since we dont have access to specifics on the heuristics, at least i know exactly why they are being banned for killaura if they are.

**Comment by CeIebrimbor** [comment]
Holy snap that's a long delay. I can see why you want this "feature" if that is the case.

**Comment by Michelele** [comment]
https://cdn.meme.am/cache/instances/folder19/500x/47200019/frenchy-heuristic-its-french-for-a-hack.jpg

**Comment by OWERLORD01** [comment]
There is a good plugin for you than
https://dev.bukkit.org/projects/command-delay.

**Comment by konsolas** [comment]
I'm going to close this as wontfix because there are much better ways to run delayed commands than relying on heuristic counting. For example, ConditionalCommands now provides the following:

- /ccmd {player} if 1=1 do /5000/ ban {player}

for a 250 second delay. 

Additionally, keeping violations on quit would be inconsistent with all other checks.
