### ISSUE TITLE
Add a average option to fastplace

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#372]
Currently fastplace diffs the timestamp of two Block placements. It can happen that players can reach a very short diff when building. But keeping that diff low is impossible. 

Our internal testing showed that a normal player can reach 50ms diff every now and then but never get a building diff (calculated with the placements over a whole second) of under 195ms. So maybe a "average" mode for the fastplace check would be good.

**Comment by CeIebrimbor** [comment]
Ditto for Fastbreak. Lenient single event sample and strict average(slow) sample.
