### ISSUE TITLE
Crashing Server Error

### ISSUE THREAD

**Issue by alexmarkey** [konsolas/AAC-Issues#373]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Began running AAC on our network, have had numerous server  crashes since, narrowed it down to AAC by manually removing all plugins.  Using the config made by Celebrimbor.

Crash has occurred ~5 times, in the past 5 days, generally once a day it occurs. 

Error - http://pastebin.com/Z2QvdJdF
Crash report - http://pastebin.com/s26qwZBS

### Core information
**Server version**:  CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**AAC version**: 3.0.1-b2

**ProtocolLib version**: 4.2.0 (Build 341)

**Plugin list**: 
Plugins (29): VoteCommand, VisloProBossMessage, WorldEdit, EnderPearlCoolDown, MCCAC, CosmeticSystem, LilyPad-Connect, StopHubServers, BossBarAPI, ColoredChat, PermissionsEx, QuickNoColon, ConditionalCommands, FriendSystem, CustomHelp, ViaVersion, HideStream, ChatManager, Punishment, SendInfoLobbies, DeadFrog, LilyAlert, ProtocolLib, TitleJoin, AAC, ClearCachepex, OfficialTabList, SendInfo, DuelsServer

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.0.3

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
Try temporarily disabling combat.Killaura; it messes around a lot with packets. I can't get much from that stack trace.

**Comment by Photon-GitHub** [comment]
Is this still valid @alexmarkey ?

**Comment by konsolas** [comment]
Closing due to no response.
