### ISSUE TITLE
Players Can't Move

### ISSUE THREAD

**Issue by 7r580** [konsolas/AAC-Issues#374]
AAC 3.01b2
Spigot 1.9.2

Something is going on that is causing players not to be able to move unless they sneak. (Hold down shift to walk.) I don't know what the issue is or what it could be conflicting with but it's happening on multiple 1.9.2 servers. We don't see it on 1.11.

**Comment by CeIebrimbor** [comment]
AAC is only compliant with 1.9.4 as is prominently mentioned on the AAC Overview.

Update to 1.9.4 or 1.10.x or 1.11.0 or 1.11.2 or downgrade to 1.8.8.

Then use the appropriate ProtocolLib.

**Comment by 7r580** [comment]
Correct, that is what we just noticed, that by upgrading to 1.9.4 the problem went away.
