### ISSUE TITLE
Speed on Ice (1.11.2)

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#378]
https://youtu.be/QZm-ibD7zzw

### Core information
**Server version**: 1.11.2

**AAC version**: 3.0.2

**ProtocolLib version**: 4.2.1

**Plugin list**: AAC and Perms

### Special environment information
NONE

**Comment by MeltedLux** [comment]
Also have this issue.

**Comment by CeIebrimbor** [comment]
Not fixed on 3.0.2-b1

It now happens without Speed potion.

**Comment by Zaino60** [comment]
It still happens, even without Speed Effect:
https://www.youtube.com/watch?v=J2f5IDmw9kE&feature=youtu.be
