### ISSUE TITLE
Trampled Crop SneakJump = Fly (1.11.2)

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#383]
https://youtu.be/sIpbScopAbw

Recently trampled crops while sneaking and jumping = Fly VL14

1.11.2

**Comment by Janmm14** [comment]
So its 1.11.2-only?

**Comment by CeIebrimbor** [comment]
No clue. Only tested 1.11 today since 1.11 is always an afterthought with development. Still seems to be the case.

**Comment by CeIebrimbor** [comment]
Not fixed in 3.0.2-b1

**Comment by Photon-GitHub** [comment]
I cannot reproduce this anymore, therefore I will close this as fixed.
