### ISSUE TITLE
Interact log spam (to death)

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#384]
https://youtu.be/KVvw7RbGdAc

I know it's not messing with players, but this is the difference of a 100mb log file and a 2000mb log file after 30 players are online for a day.

Can you fix this verbose spam?

**Comment by CeIebrimbor** [comment]
![image](https://cloud.githubusercontent.com/assets/14807889/22302025/fa3e5b32-e2e1-11e6-811d-e9899fcfabcd.png)

**Comment by Janmm14** [comment]
Let's apply some gzip compression :P

**Comment by Photon-GitHub** [comment]
This is annoying me a lot as well, the logs are partially unreadable for me if you do not know the name of the Player. As this is persisting for a long time now and lots of server owners are frustrated by this, I decidede to make this critical.
