### ISSUE TITLE
(Phase?) on soil to dirt change (1.11.2)

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#386]
As of 3.0.2, it seems like there is issues with Soil/Farmland changing to dirt. There is no phase verbose, but not sure what the issue is. It happens religiously.

https://youtu.be/th5p6i3jqyU

**Comment by konsolas** [comment]
This is actually just a 1.11.2 problem, not an AAC problem, if I recall correctly.
