### ISSUE TITLE
Jumping onto carpet on fence

### ISSUE THREAD

**Issue by Krymonota** [konsolas/AAC-Issues#388]
### Issue description
Jumping onto a carpet on a fence flags for Fly and sets back (high violation).

* Log: http://pastebin.com/spZ4QVz7
* Video: https://www.youtube.com/watch?v=ujRneV6qwZ8

### Core information
**Server version**: Spigot 1.8.8
**AAC version**: 3.0.2
**ProtocolLib version**: 4.2.0
**Plugin list**: AAC, ProtocolLib

**EDIT 1:**
It is strange that this issue does not always occur. Anyway, if you can not reproduce this - you will definitely notice some setbacks when jumping onto and around carpets on fences.

**EDIT 2:**
It looks like you can also be flagged for Speed if you jump exactly to the middle of the carpet on a fence.
[You can see it in @Rqcco's video at 0:05.](https://youtu.be/pTaxeIGrXso?t=5s)
This is what it looks like in logs:
`[22-01-2017 14:00:28.948] Krymonota failed Speed: moved too quickly: 0.413 blocks/tick (0.283) [ping:16 tps:19.99] VL:5`
`[22-01-2017 14:00:31.147] Krymonota failed Speed: moved too quickly: 0.333 blocks/tick (0.304)tg [ping:15 tps:19.99] VL:5`

**Comment by Krymonota** [comment]
It is strange that this issue does not always occur. Anyway, if you can not reproduce this - you will definitely notice some set backs when jumping onto and around carpets on fences.

**Comment by Krymonota** [comment]
It looks like you can also be flagged for Speed if you jump exactly to the middle of the carpet on a fence.
[You can see it in @Rqcco's video at 0:05.](https://youtu.be/pTaxeIGrXso?t=5s)

This is what it looks like in logs:
`[22-01-2017 14:00:28.948] Krymonota failed Speed: moved too quickly: 0.413 blocks/tick (0.283) [ping:16 tps:19.99] VL:5`
`[22-01-2017 14:00:31.147] Krymonota failed Speed: moved too quickly: 0.333 blocks/tick (0.304)tg [ping:15 tps:19.99] VL:5`

**Comment by Krymonota** [comment]
I checked it again. The fly flags could be my mistake, but the speed flags seem to be real.

**Comment by Janmm14** [comment]
Stepping on fences is a known issue for speed

**Comment by Photon-GitHub** [comment]
I can no longer reproduce this and therefore close this as fixed.
