### ISSUE TITLE
Bug when building + walking on the blocks

### ISSUE THREAD

**Issue by BlackDemonZetaxd** [konsolas/AAC-Issues#390]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

When i build and walk at the same moment on the blocks (Build UHC play mode) i get like returned to the block before. The bug just happens with new AAC version

Please include details like:
* AAC logs / Full console error
No Console Errors
* Video of the bug / bypass, best with verbose chat output
Bug Video: https://www.youtube.com/watch?v=kLJ7BJmENMY
Verbose: http://pastebin.com/8SgRn914
* The ingame name of the involved players
BlackDemonZ

### Core information
**Server version**: spigot-1.8.8

**AAC version**: The most new

**ProtocolLib version**: The test server protocol lib version

**Plugin list**: None that affects movement (i checked, i know what i do)

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: yes but not affecting movement (bug happening in new aac version)

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none that affects movement

**Comment by SnakeDaoust1232** [comment]
https://github.com/konsolas/AAC-Issues/issues/314

**Comment by MinecraftiUndCo** [comment]
Experiencing the same issue, very annoying when running away from someone and you want to build blocks at the same time. Would be nice if it will be fixed in one of the next updates. :)
