### ISSUE TITLE
NPE ProtocolLib AAC 3.0.2 aS.onPacketReceiving:9 & IllegalArgumentException: ClassCastException d.a:58

### ISSUE THREAD

**Issue by JuliCarles** [konsolas/AAC-Issues#391]
### Issue description

The following error happened on a 12-20 players server. Reported on Discord and asked to post it here.
http://pastebin.com/ecvWJYQG
Also this one, but it does not look that massive. http://pastebin.com/U8HPLz00
That's the full console error.

### Core information
**Server version**: 1.10.2

**AAC version**: Latest.

**ProtocolLib version**: Version 4.2.0 (latest)

**Plugin list**: TopLite, SkinsRestorer, PowerfulPerms, MVdWPlaceholderAPI, Languages, OldPvP, PlaceholderAPI, MysteryBoxes, ConditionalCommands, AntiForceOP, ProtocolSupport, MysteryRewards, MultiSkyWars, ViaVersion, ProtocolLib, AAC, AACAdditionPro.

### Special environment information

**ViaVersion version**: None

**ProtocolSupport version**: Latest version

**ViaBackwards version**: None

**BungeeCord plugins**: None affecting this kind of issues.

**Comment by konsolas** [comment]
This issue was closed because the code has changed so much, it is no longer likely to be valid. The stack trace no longer points to useful information.
