### ISSUE TITLE
Efficiency VI = Fastbreak

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#392]
Efficiency 6 seems to have been overlooked when 3.0.2 added recognition for unsafe enchants.

https://youtu.be/YosxHImA9q8
_Edit: Sorry about video darkness. Just know I was mining stone with an Efficiency 10 pick and then an Efficiency 6 pick. 10 did not flag Fastbreak and 6 got me kicked in about 2 seconds_

PaperSpigot 1.11.2
AAC 3.0.2-b1
ProtLib 4.2.1
Default config w/ verbose on (regened for test)

No Protocol Hacks or plugins outside AAC, ProtLib and Permissions plug.

**Comment by konsolas** [comment]
Disable fastbreak check for efficiency > 5?

Opinions?

**Comment by CeIebrimbor** [comment]
100%

**Comment by Sikatsu** [comment]
I would like to add onto this.

I have a rather basic survival server with McMMO. However fastbreak is acting quite aggresive even with efficieny < 5.

For example I just had 2 players being kicked for ''Breaking blocks to fast'' by just breaking gravel with the following spade: http://prntscr.com/e1w69p

The config is default. This is also basically the only issue I have with AAC.

**Comment by Photon-GitHub** [comment]
Should be done.
