### ISSUE TITLE
Speed bug while using a bow

### ISSUE THREAD

**Issue by LeoPantaniHD** [konsolas/AAC-Issues#393]
False positive (default config, sorry for my bad english, i'm Italian)
I get false positives while shooting a bow and running at the same time. (while rotating my head)
Also when a player joins, aac thinks that player is using badpackets (only on join, in the first 3/4 seconds - http://i.imgur.com/wmIdLLw.png)

Please include details like:
* LOG: http://pastebin.com/Gkp7pgfT
* YT Video: https://www.youtube.com/watch?v=ItAdfrloKwU&feature=youtu.be
* Nickname: LeoPantaniHD

### Core information
**Server version**: 1.8.8

**AAC version**: 3.0.2

**ProtocolLib version**: 4.2.0

**Plugin list**: AAC, clearlag, permissionsex, worldedit, viaversion, essentials, vault, essentialsspawn, fe, protocol lib and titlemanager

### Special environment information

**ViaVersion version**: 1.0.3

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Janmm14** [comment]
Regarding badpackets there exists issue #247

**Comment by Photon-GitHub** [comment]
This only causes low-level speed vls and is therefore considered unimportant now.
