### ISSUE TITLE
Depth Strider = Speed

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#394]
Depth Strider Incompatibility is back. Now at any enchantment level. Speed potions make it climb in VL faster, but not required to get fps.

https://youtu.be/WU16Q9CTyoI

PaperSpigot 1.11.2
AAC 3.0.2-b1
ProtLib 4.2.1
Default config w/ verbose on (regened for test)

No Protocol Hacks or plugins outside AAC, ProtLib and Permissions plug.

**Comment by CeIebrimbor** [comment]
This was only remedied by setting 'threshold' in **speed** to 0.08 (default 0.005).

I only accounted for Depth Strider III and Speed II, so not sure about Speed III+

**Comment by Photon-GitHub** [comment]
Should be done.

**Comment by CeIebrimbor** [comment]
Report that this is still an issue.

**Comment by RoyalRaid** [comment]
Im still having this issue, Here is a vid using depth strider 1 and speed 2
https://www.youtube.com/watch?v=KL6oBmY8-HU&feature=youtu.be

**Comment by Janmm14** [comment]
depth strider is really pesky
