### ISSUE TITLE
Removing water and swimming on top of it flags for fly

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#395]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

When you place a one block water source and jump into it and collect the water again the flowing water gives you fly vl when you try to stay on top of the water.

### Core information
**Server version**: 1.8.8

**AAC version**: 3.0.2b1

**ProtocolLib version**: 4.2.0

**Plugin list**: -

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.0.3

**ProtocolSupport version**: 4.2.0

**ViaBackwards version**: -

**BungeeCord plugins**: -

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here:

**Comment by CeIebrimbor** [comment]
Able to accumulate VL to teleport?

**Comment by geNAZt** [comment]
Kick yes. Like 80+ VLs depending on the height the players is in

**Comment by geNAZt** [comment]
https://youtu.be/jJdMdNuLe5U
