### ISSUE TITLE
BungeeCordfähigkeit fehlt

### ISSUE THREAD

**Issue by Letsplaybar** [konsolas/AAC-Issues#396]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.

We can't read your thoughts.

Please include details like:
* AAC logs / Full console error
* Video of the bug / bypass, best with verbose chat output
* The ingame name of the involved players

### Core information
**Server version**: insert
1.8.8 mit viaversion
**AAC version**: insert
3.0.2-b1
**ProtocolLib version**: insert
4.2.1-SNAPSHOT-b346
**Plugin list**: insert
Eigene***
### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: insert 1.0.4

**ProtocolSupport version**: insert no

**ViaBackwards version**: inserto

**BungeeCord plugins**: insert Eigene

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here: 

Problem mit bannen auf Bungecord system spieler wird nur von einem Server gebannt und nicht von allen genauso klappt es nicht mein Bungeebansystem zu implementieren durchs event...

**Comment by Janmm14** [comment]
Ther are plugins that can transport commands from bukkit to bungee. You can't listen to bukkit events on bungeecord.
