### ISSUE TITLE
Heuristic p/59 FPS

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#397]
Might be related to https://github.com/konsolas/AAC-Issues/issues/363. I think it has to do with accuracy.

Video: https://www.youtube.com/watch?v=i1jF1tNzshc&feature=youtu.be

Config: https://hastebin.com/ilehoqudaj.bash

Server Version: PaperSpigot 1.8 (Image: https://gyazo.com/35040bc1eabd9120ffd795848001ccd1)
AAC version: Newest 3.0.2 (Image: https://gyazo.com/758eff0c49db3c2667d6c4ff5c05c08a)
ProtocolLib version: Newest 4.20
Plugin list: 23 Plugins (Image: https://gyazo.com/8eabd7c61a96c187e005ceffefa79a99)
Special environment information
ViaVersion version: 1.0.3
ProtocolSupport version: 4.24
ViaBackwards version: None
BungeeCord plugins: 0 plugins (Clean for testing)

**Comment by Janmm14** [comment]
Unable to watch the video, but is that a combat normal players would actually have to that extend?

**Comment by SnakeDaoust1232** [comment]
Why aren't you able to watch the video? (Its unlisted, meaning you can watch it) And yes, i'm just fighting the other person normally. 

Pattern: p/59
