### ISSUE TITLE
Speed false positive 2

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#40]
When sprint-jumping from a normal block onto a soulsand block you'll get flagged for speed (vl:7)

**Comment by konsolas** [comment]
@Photon-GitHub Small thing, could you not use the planned or wontfix label in the future, since they indicate what sort of work I'm going to be doing?

**Comment by Photon-GitHub** [comment]
I just thought we should indicate you what is probably high priority and low priority with that.
I won't touch the planned and wontfix labels anymore.

**Comment by konsolas** [comment]
No problem 👍

**Comment by Photon-GitHub** [comment]
Well, we could introduce labels like high prio or low proi if it is possible, especially when aac3 is released it could be very helpful for you I think.

**Comment by CeIebrimbor** [comment]
Only one person deciding that and it's all in his head. Collaborators label things for what they are. Prioritizing and announcing yes or no is the dude doing all the work.

**Comment by Photon-GitHub** [comment]
Some pre-sorting might be useful, if this is released we maybe have to label ~20-50 issues / day (if his inbox is ~200) and some sorting will cost him a lot of time.

**Comment by konsolas** [comment]
This seems to be fixed.
