### ISSUE TITLE
Breaking block from tower flags for fly

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#400]
### Issue description

https://www.youtube.com/watch?v=yaZ4LUh5G-U
http://puu.sh/tzRxw/62cbdf67f6.jpg
http://puu.sh/tzRy5/7723083acb.jpg

### Core information
**Server version**: 1.8.8

**AAC version**: 3.0.2b1

**ProtocolLib version**: 4.2.0

**Plugin list**: -

### Special environment information
*not needed*

**Comment by CeIebrimbor** [comment]
Critical? Seeing as he wasn't kicked and he had to fake being pushed off the edge...but I already spoke my peace on the matter I suppose.

I see critical as huge, unavoidable kick or lagback while doing vanilla tasks.

**Comment by geNAZt** [comment]
It is an unavoidable kick. I stopped when got the "You glitch" message after 4 blocks.
