### ISSUE TITLE
1.11.2 Eltyra + Fireworks

### ISSUE THREAD

**Issue by MCFeelBoyYT** [konsolas/AAC-Issues#401]
When you use the rocket boost for the elytra in the 1.11.2, 
then you get stuck in air and bug to the ground.

Video: https://www.youtube.com/watch?v=sDUDhSRR_Ng&feature=youtu.be or https://youtu.be/sDUDhSRR_Ng

AAC debug log from the Player: http://pastebin.com/C0DuHqUe

**Server version**: 1.11.2 (Newest Spigot version)

**AAC version**: 3.0.3-b1 (Newest version)

**ProtocolLib version**: Build #347 (Newest version)

**Plugin list**: AAC

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

Created 14:00 26.1.2017 (German Clock)

**Comment by Sikatsu** [comment]
I can confirm Elytras and fireworks not working correctly.

Even when using the following settings, this is only partly fixed but still bugs a bit.

`fly:
   # Do you want to enable the fly check
   enabled: true

   # How strongly should AAC enforce fall speeds (smaller values are more accurate)
   tolerance: 0.015
   e_tolerance: 1.0

   # Multiplier of violation size to be added to VL level
   vl_multiplier: 6.0

   # Minimum violation level for a player to be teleported down. Only if teleport is true
   min_vl: 40`
