### ISSUE TITLE
AntiKnockBack works on Player.setVelocity and gives false positives due to that

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#402]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

AntiKnockBack detection works great with vanilla attacks, but it doesn't work if I give them a custom velocity.
I suggest you listening to Velocity packet or make a Velocity API.

### Core information
**Server version**: PaperSpigot 1.11.2

**AAC version**: 3.0.2 b1

**ProtocolLib version**: 4.2.1-SNAPSHOT-b346

### Special environment information
Insert 'none' if you don't use it

**ProtocolSupport version**: 4.25 b661

**Comment by Rqcco** [comment]
Anti-Knockback is very difficult to detect,

**Comment by Photon-GitHub** [comment]
Knockback check is deprecated now and replaced by velocity. Therefore I will close this as it is no longer valid.
