### ISSUE TITLE
Hunger is not checked in the Speed check

### ISSUE THREAD

**Issue by konsolas** [konsolas/AAC-Issues#404]
People are able to sprint if their food level is <= 6, when normal players cannot.

This is handled in AACAdditionPro, but the implementation there can be bypassed.

**Comment by NEZNAMY** [comment]
#404 lol

**Comment by Photon-GitHub** [comment]
Well, I told him that we should move this check over to aac because of the better movement handling and framework (the check is consisting of two lines of code in aac, and consisted of around 20 lines in AACAdditionPro).
