### ISSUE TITLE
[Suggestion] Kill Aura

### ISSUE THREAD

**Issue by Unforgivinq** [konsolas/AAC-Issues#409]
This is a PM I sent towards Konsolas on Spigot, I was redirected here to post it from the Discord Channel. If this is the incorrect place please tell me and I'll create another there!

> Hey I have a friend that has your newest AAC version (3.0 etc) and he says it works good but he would like a way to stop Kill Aura users so that their KA locks onto a entity. My idea for the entity was that when the Hacker reaches a specified threshold a entity spawns above them for X amount of seconds which can distract their Kill Aura good enough so that the player can record and show head snap proof. 
> 
> The entity can be 4.0 blocks above said hackers head which shifts around from below, to in front of the hacker to distract AIM locking KA and maybe moving close to the player to find out if the player has their priority set to near.
> 
> I currently posses a client called Vatic which is a private client that also has armor, health and more different types of priority. So maybe take them priorities into consideration! Thank you for reading and replying (if you did) If this seems like a good idea to you tell me and if it will be implemented!

**Comment by konsolas** [comment]
This was the check in 1.9.10; it has been removed in 3.0.x due to version compatibility and player satisfaction issues.

**Comment by Unforgivinq** [comment]
If that is the case is there any other way of having Kill Aura targeting signal disrupted or to target something else so the hacker cannot use it?
