### ISSUE TITLE
Custom commands for player violation list in GUI

### ISSUE THREAD

**Issue by timothydavidhart** [konsolas/AAC-Issues#412]
I would like some kind of config to the click to enter spec and tp so that I could maybe use my vanish plugin.

**Comment by Sikatsu** [comment]
Sounds like a nice minor addon. Would require changable text too if you want to use vanish plugins instead of spectator.

**Comment by Felix5566** [comment]
I would also like this, because the team members can look at which hacking level the players are. Without changing what's in the config.

**Comment by Janmm14** [comment]
Duplicated by #368
