### ISSUE TITLE
Killaura Heuristic FP p/59 | 3.0.3

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#413]
idk anymore xD

Video: https://www.youtube.com/watch?v=DfkI_q1zDa0&feature=youtu.be

Config: https://hastebin.com/uxemoremac.bash

Server Version: PaperSpigot 1.8 (Image: https://gyazo.com/35040bc1eabd9120ffd795848001ccd1)
AAC version: Newest 3.0.3
ProtocolLib version: Newest 4.20
Plugin list: 23 Plugins (Image: https://gyazo.com/8eabd7c61a96c187e005ceffefa79a99)
Special environment information
ViaVersion version: 1.0.3
ProtocolSupport version: 4.24
ViaBackwards version: None
BungeeCord plugins: 0 plugins (Clean for testing)

**Comment by konsolas** [comment]
at least p/58 was fixed, I guess :*(

**Comment by SnakeDaoust1232** [comment]
:P
