### ISSUE TITLE
Phase false positive when teleporting far away

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#414]
Image: https://gyazo.com/a7c6788d37f0910ad3d437a6eef0ae95

When you change worlds, or tp a distance away, it flags for fly.

Config: https://hastebin.com/uxemoremac.bash

Server Version: PaperSpigot 1.8 (Image: https://gyazo.com/35040bc1eabd9120ffd795848001ccd1)
AAC version: Newest 3.0.3
ProtocolLib version: Newest 4.20
Plugin list: 23 Plugins (Image: https://gyazo.com/8eabd7c61a96c187e005ceffefa79a99)
Special environment information
ViaVersion version: 1.0.3
ProtocolSupport version: 4.24
ViaBackwards version: None
BungeeCord plugins: 0 plugins (Clean for testing)

**Comment by Photon-GitHub** [comment]
No longer fly vl, but some low-level-phase  vl. I will therefore mark this as unimportant and change the title.
