### ISSUE TITLE
Eating and sprinting with Gapple FP

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#416]
When you sprint and eat a gapple, it gives false positives for speed. Might be related to https://github.com/konsolas/AAC-Issues/issues/340

Video: https://www.youtube.com/watch?v=6l3cR-ECJJ4&feature=youtu.be

Config: https://hastebin.com/uxemoremac.bash

Server Version: PaperSpigot 1.8 (Image: https://gyazo.com/35040bc1eabd9120ffd795848001ccd1)
AAC version: Newest 3.0.3
ProtocolLib version: Newest 4.20
Plugin list: 23 Plugins (Image: https://gyazo.com/8eabd7c61a96c187e005ceffefa79a99)
Special environment information
ViaVersion version: 1.0.3
ProtocolSupport version: 4.24
ViaBackwards version: None
BungeeCord plugins: 0 plugins (Clean for testing)

**Comment by CeIebrimbor** [comment]
Is #340
