### ISSUE TITLE
SpeedNuker (Wurst) in Spectate mode causes forcibly closed kick.

### ISSUE THREAD

**Issue by ssamjh** [konsolas/AAC-Issues#417]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.

We can't read your thoughts.

Please include details like:
* AAC logs / Full console error
* Video of the bug / bypass, best with verbose chat output
* The ingame name of the involved players

### Core information
**Server version**: git-Spigot-6de2fbc-80dd971 (1.11.2)

**AAC version**: 3.0.3

**ProtocolLib version**: "latest" http://ci.dmulloy2.net/job/ProtocolLib/346/

**Plugin list**: Plugins (9): PermissionsEx, ConditionalCommands, FairPlayMinecraft, Essentials, EssentialsSpawn, EssentialsChat, ProtocolLib, AAC, AACAdditionPro (this is a testing server)

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here: 31st Jan 2017 (not sure the hour)

https://paste.ssamjh.nz/view/raw/9c1f9651 (console log)
https://paste.ssamjh.nz/view/raw/ef75ba08 (aac log)

**Comment by Photon-GitHub** [comment]
It is a cheat nonetheless, so I will close this as won't fix.
