### ISSUE TITLE
Sneak Hack Rubberbanding

### ISSUE THREAD

**Issue by Unforgivinq** [konsolas/AAC-Issues#418]
Can you add in the feature that AAC 1.9.10 had that rubberbanded togglesneak/silentsneak?

**Comment by CeIebrimbor** [comment]
Need more info about the specific hack you know was physically blocked in 1.9.10 that is no longer blocked in 3.0

**Comment by Unforgivinq** [comment]
Basically if you have set speed checks to not ban/kick it rubberbands you when using speed but when togglesneak is active anyone can run around with togglesneak on in their client menu without being teleported to their last area.

**Comment by Photon-GitHub** [comment]
This is already covered by the max_sneak_toggles option in the config. Please make sure you have configured AAC properly.
