### ISSUE TITLE
KillAura Entity Activation

### ISSUE THREAD

**Issue by Unforgivinq** [konsolas/AAC-Issues#419]
This is something like I said in [this thread](https://github.com/konsolas/AAC-Issues/issues/409) but in more detail.

After a certain threshold is reached (can be configured) and AAC is certain that said player is using KillAura, it can spawn a entity for a couple of seconds (can be configured) which varies its movements to distract KillAura targeting (this can also help with Armor, health and more types of priority like in Vatic client).
The entities sole purpose is to distract and maybe even render KillAura useless as the targeting is destroyed.

Benefits:
Both hacker and normal player must fight without hacks
Allows the normal player to capture footage of headsnaps caused by the entity distracting the targeting system.
Creates fairer advantage for the normal player.
[if there are any more suggestions put them below]

Bad things:
Can annoy the players (hence why it can be configurable)
[if there are any more suggestions put them below]

**Comment by Acenox2** [comment]
Hello,

I agree with Unforgivinq, the killaura / ForceField is much longer than version 1.9.10 ... I have both versions on my servers because I still want to test AACV3 pa compared to version 1.9.10 . So please, please add an option to be able to have the entities! thank you very much :)

**Comment by Janmm14** [comment]
Entities are bypassed by so many hack clients, its basically useless. I already found Wurst not attacking some fake players.

**Comment by Unforgivinq** [comment]
I know but for those clients that dont bypass it that means atleast their targeting is messed up

**Comment by Unforgivinq** [comment]
And in addition the entities wont spawn until x amount of thresholds reached like how some anticheats have a command to force check for FF/KA except this just spawns entities to distract the targeting, some hackers wont think there is an anticheat as they'll see no entities

**Comment by CeIebrimbor** [comment]
This will likely be added in AACaddition Pro's new Killaura entities. I would not wait on AAC to add this since it is more heavily invested in the Heuristics method of checking Killaura.
