### ISSUE TITLE
[Bypass] Fastbreak bypass with short mining times

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#42]
If you use fastbreak on something you can break really fast (e.g. stone with a diamond pick) you can slightliy decrease your mining time with vanilla fastbreak.
NoHitDelay is not working, but you can use this on all fast-mined materials according to your current tool.
Not very important issue as the advantage is very small...

**Comment by konsolas** [comment]
Seems quite trivial, and could risk false positives if a fix is attempted. I will close as wontfix.
