### ISSUE TITLE
Setting player's velocity while climbing ladder causing FastLadder

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#424]
### Issue description

When I give a player a velocity like (0,1,0) while they are climbing ladder, they will be kicked for fast ladder

### Core information
**Server version**: 1.11.2

**AAC version**: 3.0.3

**Comment by CeIebrimbor** [comment]
Verbose? Video?

**Comment by CeIebrimbor** [comment]
Closing after a week of waiting for more info. 3.0.4 should fix most issues with climb speeds.
