### ISSUE TITLE
Sweeping Edge = Hitbox

### ISSUE THREAD

**Issue by MCFeelBoyYT** [konsolas/AAC-Issues#426]
When I hit mobs or player with sweeping edge then the player is suspected for killaura!

Server version: 1.11.2 (Newest Spigot version)

AAC version: 3.0.3-b1 (Newest version)

ProtocolLib version: Build #347 (Newest version)

Plugin list: AAC

ViaVersion version: none

ProtocolSupport version: none

ViaBackwards version: none

BungeeCord plugins: none

Created 14:00 3.2.2017 (German Clock)

**Comment by CeIebrimbor** [comment]
https://youtu.be/-8W8CcnD7xY

Can you make a video of this supposed false detection?

**Comment by CeIebrimbor** [comment]
I am changing this to false hitbox detection as I was only able to get Hitbox detection for massive groups of mobs. If @MCFeelBoyYT provides documentation of Killaura kicks then we can escalate this to include that check.

Hitbox check log with .6/2.6 Hitbox settings: https://hastebin.com/iqavalupim.pas

**Comment by MCFeelBoyYT** [comment]
217/5000
I could not show it in the video, but many players were kicked because of killaura and they told me that they hit a group of mobs on a block with a sweeping edge 3 sword.
https://www.youtube.com/watch?v=JcK_kKKp8oM&feature=youtu.be
The video still has to upload, but is online soon.

**Comment by MCFeelBoyYT** [comment]
i found this in my logs

[01-02-2017 17:35:19.277] Jannikimoh38 failed Hitbox: attacked an entity out of their line of sight [ping:31 tps:19.99] VL:3

**Comment by CeIebrimbor** [comment]
Looks like it is just Hitbox. If you can replicate or find evidence of players being kicked, then ok. Until then, this should be considered a minor detection bug that might be canceling a few hits.

You can set `min_vl` in `hitbox` to 4-6 to avoid the canceled hits for minor infractions.

**Comment by CeIebrimbor** [comment]
I do not think this is valid. @MCFeelBoyYT please provide more evidence of this claim if you would like it reopened.
