### ISSUE TITLE
Fly config feature

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#427]
Having some trouble with kit skills like kangaroo(high jump) and double jump skills. Before, we just increased max_jump to ignore up to 6 blocks high. Can we have that option back knowing it will only be used in limited application? Much like speed scalars.

**Comment by Janmm14** [comment]
Maybe it would be better to report the false positive of fly here instead, because the fly check got revamped in AAC 3 and implementing a max_jump option is not as easy as before.

**Comment by CeIebrimbor** [comment]
Things like this should be fixed with API I suppose.
