### ISSUE TITLE
PlayerMoveEvent Lag problem +130 online

### ISSUE THREAD

**Issue by craftrise** [konsolas/AAC-Issues#428]
###############################

PlayerMoveEvent Lag Problem +130 online

Enabled movements:
- Speed  -Fly -Phase -Derp -Nofall

Lag cause:
http://prntscr.com/e4gw04

###############################

### Core information
**Server version**: 1.8.8 PaperSpigot

**AAC version**: 3.0.3

**ProtocolLib version**: 4.2.0

**Plugin list**: -

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.0.4

**ProtocolSupport version**: -

**ViaBackwards version**: -

**BungeeCord plugins**: -

### Reporting issues encountered on the test server has these additional rules:

Created: 04.02.2017 20:46 (Turkey Clock)

**Comment by SnakeDaoust1232** [comment]
I was worried the new movements would cause lag.

**Comment by CeIebrimbor** [comment]
Could you provide a full timings report? We all know AAC is heavy, as in any anti-cheat.

**Comment by CeIebrimbor** [comment]
Closing after a week waiting for more info
