### ISSUE TITLE
java.lang.NoSuchFieldError: REL_ENTITY_MOVE_LOOK

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#429]
### Issue description

The console keeps spamming this:
http://pastebin.com/fqaMvLYK
### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 3.0.3

**ProtocolLib version**: 4.2.0-SNAPSHOT-b341

**Comment by konsolas** [comment]
Are you sure your ProtocolLib version is correct?

**Comment by CeIebrimbor** [comment]
Closing after a week for waiting for more info
