### ISSUE TITLE
v3 Knockback false positive when dying while being attacked

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#43]
For example if some zombies hit you and you die, antiknockback will report a false positive

**Comment by CeIebrimbor** [comment]
It think that had the potential to get to kick levels if a player (in some pvp situations) was being spawn killed. An uncommon situation, but some gametypes encourage spawn trapping as a tactic.

**Comment by konsolas** [comment]
This is fixed and queued for the test server.

**Comment by konsolas** [comment]
Verified fix.
