### ISSUE TITLE
Not swinging arm false positive (disable NoSwing on lower TPS)

### ISSUE THREAD

**Issue by Sikatsu** [konsolas/AAC-Issues#431]
### Issue description

Players are getting kicked for ''Not swinging arm'' when using a highly enchanted shovel and excavation from McMMO. Same with farming.

05.02 20:34:30 [Disconnect] User Falanxe has disconnected, reason: [AAC] > Not swinging arm 

### Core information
**Server version**:
05.02 20:35:01 [Server] INFO This server is running CraftBukkit version git-Spigot-4741400-a1d3777 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
05.02 20:35:01 [Server] INFO You are 1 version(s) behind
**AAC version**:
3.0.3-b1
**ProtocolLib version**:
4.2.0
**Plugin list**:
Is this really needed here? (McMMO)
### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
Logs from plugins/AAC/logs?

**Comment by Sikatsu** [comment]
I think this might be related to my TPS drops on the server when I check the logs. Or isn't that possible?

**Comment by Sikatsu** [comment]
No Swing notification messages appear quite frequently and seems to be to strict. I will attach a log, however I accidently removed the log with the kicks.

https://www.dropbox.com/s/jtetkk2bs2qgzhz/aac_2017-02-07_08-31-39.log?dl=0

Once someone gets kicked again I will attach that log to this issue.

**Comment by Sikatsu** [comment]
Must mention my TPS was pretty bad the past days. It's fixed now, but i'm not sure whether it's related to that as no one complained about lagg either from the 30+ players.

**Comment by Janmm14** [comment]
I don't know the internals of the check, but it might be tps-related. It seems to work without problems on many other servers however.
Maybe you could watch with which block noswing-players are interacting with if it occurrs again.

**Comment by Janmm14** [comment]
I don't know the internals of the check, but it might be tps-related. It seems to work without problems on many other servers however.
Maybe you could watch with which block noswing-players are interacting with if it occurrs again.

**Comment by Sikatsu** [comment]
I was also thinking it might be TPS related. Seems to happen mostly when farming crops or using a highly enchanted spade.

**Comment by CeIebrimbor** [comment]
I only see NoSwing fps when TPS drops below 17-18. Never see more than VL 6 or so.

**Comment by Sikatsu** [comment]
This seemed to be an TPS issue, now with new server hardware this seems to be fixed. Sorry! Will close this one.

**Comment by geNAZt** [comment]
Well when TPS drops to like 12-14 you see NoSwing all over the place. AAC should disable the Check when the TPS goes under 18 TPS since its not realibale then

**Comment by Sikatsu** [comment]
Oh, sorry. Sounds like a good plan :)

**Comment by CeIebrimbor** [comment]
@konsolas 
Add NoSwing to TPS disabling checks?

**Comment by konsolas** [comment]
NoSwing will now disable below TPS 17.5
