### ISSUE TITLE
MCMMO Block break abilities temporarily disable all checks.

### ISSUE THREAD

**Issue by Fonzee9** [konsolas/AAC-Issues#432]
Version: 3.0.3 b1 

How do you disable AAC with Mcmmo you ask? Simple step 1 rightclick with your fist and break blocks with mcmmo then try and fly hack and it will work as if aac is disabled.

**Comment by Fonzee9** [comment]
McMMO Version: 181

**Comment by Fonzee9** [comment]
McMMO Version: 181

**Comment by Matthew777k** [comment]
A video of the bug, this was tested on AAC v3 3.0.1.
https://youtu.be/mszQONN84KY

**Comment by Fonzee9** [comment]
I hope its fixed soon i cry cause i just bought this to find out i can't use it if its bypassable so easily..

**Comment by CeIebrimbor** [comment]
Confirmed. Holy sh*t....

**Comment by Fonzee9** [comment]
Sorry if i come across a bit inpatient but i was wondering how long until this is fixed? :)

**Comment by Matthew777k** [comment]
A temporary fix would be to disable the 'berserk' mcMMO ability.

**Comment by CeIebrimbor** [comment]
This is slated to be in the next patch release which is estimated to take place before this weekend. Consider temp disabling the activated skill. Players will still gain EXP so long as you just remove perm for the beserk skill itself.

**Comment by Fonzee9** [comment]
This problem is not fixed i just updated and tested it, the bypass still works!!! :(

**Comment by v0idst4r** [comment]
@Fonzee9 As everyone's been saying, just temporarily disabled the beserk ability

**Comment by Fonzee9** [comment]
I already did a long time ago... i only had it enabled on my test server i am a smart person.
