### ISSUE TITLE
PlayerMoveEvent NPE AAC 3.0.3 bH.a:285

### ISSUE THREAD

**Issue by Fluxty** [konsolas/AAC-Issues#434]
Bothersome spamming console: http://pastebin.com/yjwKvmcd

TacoSpigot 1.8.8 & appropriate protocollib - Using latest ViaVersion for up to 1.11.2 support.

**Comment by Fluxty** [comment]
More on this, this one seems to pop up multiple times on our SkyBlock server:

http://pastebin.com/b6kPXY3h

**Comment by konsolas** [comment]
This issue was closed because the code has changed so much, it is no longer likely to be valid. The stack trace no longer points to useful information.
