### ISSUE TITLE
Regular Slowness = Speed

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#435]
High level of Slowness potion (8+) will detect pretty consistently for Speed when sprint jumping and landing. Gets to kick levels. Kit being used applies Slowness 20 so it happens pretty quick in this case.

https://www.youtube.com/watch?v=PSdVITWHkgY&feature=youtu.be
Video shows with Speed potion as well, but not required to replicate detection.

Snip of some logs: https://hastebin.com/imobihizis.bash

### Core information
**Server version**: 1.8.8

**AAC version**: 3.0.3-b1

**ProtocolLib version**: 4.2.0

**Plugin list**: Kitpvp, but none changing movement in this case. Case only shows vanilla slowness potion at high levels.

### Special environment information
**ViaVersion version**: 1.0.4

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: https://gyazo.com/e7cdeb2b15b98aac1a6fade31868b092

**Comment by Zaino60** [comment]
Can confirm this is a valid bug!

**Comment by Janmm14** [comment]
I thought slowness starts to make players unable to move at level 5 or 6?

**Comment by CeIebrimbor** [comment]
Until you jump, yes? Which causes the reported issue.

**Comment by CeIebrimbor** [comment]
@konsolas This is active again after the 3.0.5 release.

Previously Slowness 7+ caused the issue in the video above. Now it's Slowness 2+...
