### ISSUE TITLE
AAC Notify on Bungeecord

### ISSUE THREAD

**Issue by Felix5566** [konsolas/AAC-Issues#436]
Can be made so that the hacking reports also go over Bungeecord? Like the plugin: https://www.spigotmc.org/resources/aacbungeeconnect.35611/
or made a addon...

THX

MFG Felix5566

**Comment by CeIebrimbor** [comment]
This is something there is no interest in focusing on adding/supporting. Use the linked plugin or something similar to accomplish those specific needs.
