### ISSUE TITLE
"you cannot teleport while falling" glitch

### ISSUE THREAD

**Issue by KillzyazMadness** [konsolas/AAC-Issues#439]
So my issue appears to be some kind of a glitch or conflict with another plugin.

Please include details like:
Video of issue: https://www.youtube.com/watch?v=pOH0SGC5RBo

### Core information
**Server version**: CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**AAC version**: 3.0.3

**ProtocolLib version**: ProtocolLib v4.2.0

**Plugin list**: (62): DiscoArmour, SimpleBroadcast, PlaceholderAPI, PlugMan, NametagEdit, ChatReaction, AlwaysDay, SuperTrails, ViaVersion, StaffApplication, HideStream, StaffPlus, BlocksAreBetter, FrameProtect, WorldEdit, Playtime, OpenInv, CombatLog, PlayerJoinCounter, ClearLag, ChatControl, BuycraftX, Votifier, ProtocolLib, NoCheatPlus, GuiRedeemMCMMO, ItemNameTag, PlayerAverageCounter, PermissionsEx, FeatherBoard, ConditionalCommands, mcMMO, SkyblockOres, Vault, LogBlock, Item2Chat, WorldGuard, AAC, ASkyBlock, PlayerVaults, PlayerHeads, boosCooldowns, Greenhouses, SpawnerShop, Essentials, CrateReloaded, SilkSpawners, Multiverse-Core, RedeemMCMMO, TradeMe, Auction, SilkSpawnersEcoAddon, OnTime, EssentialsChat, GAListener, MiniaturePets, HolographicDisplays, EssentialsGeoIP, EssentialsAntiBuild, EssentialsSpawn, TitleManager, ShopGUIPlus

### Special environment information
none

**ViaVersion version**: 1.0.4

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: movemenow-1.2-17.jar, nuvotifier-universal-2.3.3.jar, PartyAndFriendsCustom.jar, RedisBungee-0.3.10.jar, ServerListPlusUniversal-3.4.jar

**Comment by Janmm14** [comment]
Does this issue persist in latest AAC version?

Will close in about a week if no answer is given.

**Comment by tedyst** [comment]
I am pretty sure that this bug comes from ASkyBlock, because you probably disabled the teleportation in that plugin.

**Comment by Janmm14** [comment]
Okay, closing this as plugin compatibility issue aka aac can't execute setbacks and its stacking up
