### ISSUE TITLE
Suggestion: Split killaura-npc from killaura-heuristics

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#44]
Killaura-Heuristics are things where people like me are always careful as we don't know for sure whether one is hacking or not and therefore we set the commands lenient and let us inform about players which the heuristic flagged.
The killaura npc's however are a lot more safe to quickly ban for and therefore I request the command maps to be split.

I know I could increase the killaura npc threshold increase, but it does not give clear logs.

**Comment by Photon-GitHub** [comment]
There won't be a npc check in aac3 anymore.

**Comment by Janmm14** [comment]
I wrote to him yesterday and as far as I know he will leave the killaura npc.

**Comment by konsolas** [comment]
I'm not using the player NPC anymore, currently using a different one. Killaura heuristics are not present and will be moved to a different check.
