### ISSUE TITLE
[Feature] Anti InvWalk

### ISSUE THREAD

**Issue by MCFeelBoyYT** [konsolas/AAC-Issues#440]
English:
Can you add a anti InvWalk protection and a Anti AutoSing!

Deutsch:
Hallo Konsolas oder andere können Sie/Ihr bitte InvWalk und AutoSing blocken und vielicht noch andere kleinere Hacks?

9.2.2017 20:25 (German Clock)

**Comment by CeIebrimbor** [comment]
https://www.spigotmc.org/resources/aacadditionpro.33590/
