### ISSUE TITLE
AAC Bypass Exception

### ISSUE THREAD

**Issue by Schuchie** [konsolas/AAC-Issues#442]
### Issue description
Could it be that aac also check players with the bypass permission but does not punish them?
If it is true could you change it, that players with this permission are ignored from all checks?

### Core information
**Server version**: Spigot 1.8.8-R0.1

**AAC version**: 3.0.1

**ProtocolLib version**: 4.2.1-SNAPSHOT-b346

**Plugin list**: Just ProtocolLib, AAC,  AACAddition

### Special environment information

**ViaVersion version**: 1.0.4-SNAPSHOT

**Comment by Janmm14** [comment]
Where's the difference?

**Comment by CeIebrimbor** [comment]
Wants to be able to track players without adding VL causing kicks, notifications or canceled actions.

**Comment by Janmm14** [comment]
In that case an external plugin is required and can interact with AAC's api to achieve this behaviour.

**Comment by Schuchie** [comment]
No i dont want to be able to interact with the track players. I just wanted that the bypass permission check is before the violation check.

**Comment by Janmm14** [comment]
@Schuchie Well the question is why? Also neither me nor anyone else here knows the current order of the checks.

**Comment by Schuchie** [comment]
Because if i spawn fake players, aac throws arrows cause them.

**Comment by Schuchie** [comment]
@CeIebrimbor pls reopen this feature.

**Comment by Janmm14** [comment]
Why do people always need fake players out of the packet scope? I don't get it.

**Comment by Schuchie** [comment]
Cause i created a pvp bot.

**Comment by Photon-GitHub** [comment]
Then give those bots bypass permission as they obviously won't cheat and a check without any punishment is not sensible.
Furthermore it will save you some cpu and ram.

**Comment by Schuchie** [comment]
@Photon-GitHub they got the bypass permission. But as i said i throws errors for them in the movecheck cause you first check for "hack" and then check if the user has the bypass permission. Also i would improve the performance from aac with this little change.

**Comment by konsolas** [comment]
Are the movement checks triggered or do they throw errors?

**Comment by konsolas** [comment]
@Schuchie

**Comment by Schuchie** [comment]
@konsolas They should not be triggered because of the bypass permission, but they are triggered. No error, just some hashmaps piling up lots of garbage due to no real players (bots). Solution to the problem should be bypass permission bypassing the checks 100%. Currently it seems bypass permission just disables penalties but still checks player somehow, resulting in senseless cpu and ram usage.

**Comment by konsolas** [comment]
The problem is still unclear to me; can you show me some console output for the bots?

**Comment by Janmm14** [comment]
@konsolas
He thinks AAC does check all players regardless the bypass permission resulting in unneccessary cpu/ram usage by aac.

**Comment by konsolas** [comment]
They aren't.
