### ISSUE TITLE
AAC Bypass Hacked Client (HighJump)

### ISSUE THREAD

**Issue by Pluginsel** [konsolas/AAC-Issues#443]
Hello, i am tested AAC bypass hacked  client named LiquidBounce, version 1.8.8.
Please fix for AAC 3.0.5, Thanks!

Hacked Client Name: LiquidBounce - 1.8.8

Bypass: HighJump

Hacked Client Download Link: https://goo.gl/hEF8KY

Video Link: https://youtu.be/UIC_2mbKplk

Tested: Yes.

Server Version: 1.8-1.8.9

AAC Version: 3.0.4

ViaVersion: None

ProtocolLib: 4.1+

**Comment by Photon-GitHub** [comment]
Please provide both your log and your config when testing this as I think this is caused by an old tolerance defaut value.

**Comment by Pluginsel** [comment]
ok caused by server.
