### ISSUE TITLE
kick_ticks 0 still prevents players to login

### ISSUE THREAD

**Issue by wasder** [konsolas/AAC-Issues#446]
I need this to be disabled, sometimes our players can't connect due to this.

**Comment by Photon-GitHub** [comment]
Use kick_ticks: -1

**Comment by CeIebrimbor** [comment]
If you have a config that have errors, the console will spit out ugliness about your spacing errors and use the default config (which has the kick ticks). Make sure your console is clean when you reload AAC.

**Comment by wasder** [comment]
I set it to -1, but still got my players kicked.
![](http://i.imgur.com/OnK3MYl.png)

**Comment by CeIebrimbor** [comment]
Make sure you remove the Climb check from your config. See #451 

The climb check is still being added by default but is not recognized so it causes problems like you kick tick situation.

**Comment by wasder** [comment]
I don't have it there. It's 100% your optimized config.

**Comment by CeIebrimbor** [comment]
Hold up, `kick_ticks` does not kick players. Are you trying to disable kicking entirely? Now I'm confused as to what you think that setting accomplishes.

**Comment by wasder** [comment]
As it says:
```
# Time(ticks) since disconnect before a player can relog
# Blocked login message set in language.yml
# Default(120)
kick_ticks: -1
```
We got a bungeecord setup and sometimes our players got stucked trying to connect to server (screenshot above), cause AAC kicks them with relog_message.

Latest AAC with latest config.

**Comment by CeIebrimbor** [comment]
Do you get any errors in console when you /aacreload ?

**Comment by wasder** [comment]
Nope. 
![](http://i.imgur.com/xSxsY58.png)

**Comment by CeIebrimbor** [comment]
Oh my...basically everything is disabled...

Can you send me your current config in a PM on Spigot/Skype/Discord?
