### ISSUE TITLE
PlayerMovementEvent error

### ISSUE THREAD

**Issue by Sikatsu** [konsolas/AAC-Issues#448]
http://pastebin.com/vfv9iXzK

AAC version: 3.0.4
Protocollib version: 4.2.0

**Comment by Photon-GitHub** [comment]
Wrong protocollib version for the server version.
As you have 1.11 please use the latest Protocollib version and not 4.2.0

**Comment by Sikatsu** [comment]
Sorry, but what? http://prntscr.com/e7seox

4.2.0 claims to be updated for 1.11.

Also when I check their github, nothing 1.11 related came in 4.2.1-SNAPSHOT. (http://prntscr.com/e7sf2u)

**Comment by CeIebrimbor** [comment]
That note was back in December before 4.2.1 (for 1.11.x) was started and before AAC v3.0 was a thing. Use latest ProtLib for 1.11 server.

**Comment by Sikatsu** [comment]
When AAC 3.0 was released, everyone said to update to 4.2.0. What is different in 4.2.1 then?

**Comment by CeIebrimbor** [comment]
4.2.0= 1.8-1.10
4.2.1= 1.11

For now

**Comment by Sikatsu** [comment]
@CeIebrimbor @Photon-GitHub 

Updated protocollib now, but this error is still there: http://pastebin.com/CpDzngtJ
