### ISSUE TITLE
NPE error

### ISSUE THREAD

**Issue by Sikatsu** [konsolas/AAC-Issues#449]
Honestly have no idea how this error happened, seen this twice now so I thought to report it here.

http://pastebin.com/caPBSnUA

AAC version: 3.0.4
Protocollib: 4.2.0

**Comment by Photon-GitHub** [comment]
Wrong protocollib version for the server version.
As you have 1.11 please use the latest Protocollib version and not 4.2.0

**Comment by Sikatsu** [comment]
Sorry, but what? http://prntscr.com/e7seox

4.2.0 claims to be updated for 1.11.

Also when I check their github, nothing 1.11 related came in 4.2.1-SNAPSHOT. (http://prntscr.com/e7sf2u)

**Comment by Photon-GitHub** [comment]
The right Protocollib version for 1.11 is 4.2.1, just use it.
It has support for various 1.11 features and the coder claimed that 4.2.1 is for 1.11.

**Comment by Janmm14** [comment]
To give reference, here is the information from:
http://ci.dmulloy2.net/view/ProtocolLib/job/ProtocolLib/
