### ISSUE TITLE
3.0.4 still generates Climb check (causing issues)

### ISSUE THREAD

**Issue by marint94** [konsolas/AAC-Issues#451]
Server Version: SPIGOT LATEST 1.8.8
AAC Version: 3.0.4 (LATEST)

I have:
        `kill_loggers: false`

Yet players get killed.

FIX THIS ASAP.

**Comment by CeIebrimbor** [comment]
Confirm @Janmm14?

@marint94 `combat_time` set to 0

**Comment by Janmm14** [comment]
No confirmation, just applying labels based on the data given.

**Comment by CeIebrimbor** [comment]
More info please. Video?

**Comment by marint94** [comment]
Updated to latest ProtocolLib, fixed now.

**Comment by CeIebrimbor** [comment]
Let me see your anti-combat log plug config and your AAC config.

**Comment by marint94** [comment]
This is literally the plugin:

```
if (inBattle(pname, l) && p.hasPermission("muxsystem.antileftbypass") == false) {
	p.setHealth(0D);
	broadcastMessage("§6AntiLog> §7'" + pname + "' §4hat sich im Kampf ausgeloggt.", null, Priority.NORMAL);
}
```

AAC Config: http://pastebin.com/uYLNSe3T

**Comment by marint94** [comment]
You simply need to check the kill_loggers boolean and if it's false not give out any messages about combatlog. (Since it's turned off)

**Comment by CeIebrimbor** [comment]
combat_time: 0 _< Use that setting!_

Also, remove the climb check entirely. It is not a check.

**Comment by marint94** [comment]
combat_time: 0 and combat_time: -1 both don't help.
Messages still appear.

**Comment by i9hdkill** [comment]
Can confirm that.

Latest 1.8.8 with timings fix
'This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)'
PL 4.2 stable
'[ProtocolLib] Enabling ProtocolLib v4.2.0'

'kill_loggers: false'
doesn't stop people from getting killed

**Comment by CeIebrimbor** [comment]
Thank you for confirm @i9hdkill

**Comment by i9hdkill** [comment]
Woops. Still had climb in my config. Seems like that messed up stuff.
Works now.

Probably add a feature that scans config onEnable, that check for invalid config keys. For example in this case, climb.

Like that during startup:
AAC: Found unused config key "climb". Please remove it from your config otherwise AAC won't work properly.

**Comment by marint94** [comment]
Removing climb did the trick.
A freshly new generated config with AAC 3.0.4 contains climb:
so it might be good to update that otherwise AAC simply has weird bugs (like the ones I reported)

**Comment by CeIebrimbor** [comment]
Re-genned config generates climb????

**Comment by marint94** [comment]
@CeIebrimbor Yes
