### ISSUE TITLE
kick_ticks -1 still prevents players to login

### ISSUE THREAD

**Issue by marint94** [konsolas/AAC-Issues#452]
AAC Version: 3.0.4 (LATEST)
PROTOCOLLIB VERSION: b347 (LATEST)
SPIGOT VERSION: 1.8.8 (LATEST)

`kick_ticks: -1`

Players can't reconnect too fast, AAC prevents them from doing that.
I don't want this feature, as bukkit.yml already has connection-throttle

**Comment by marint94** [comment]
![Screenshot](https://abload.de/img/img_14022017_125428_0r8scd.png)

**Comment by CeIebrimbor** [comment]
You seriously have something that is forcing the combat log and kick_tick settings... I don't know what, but it's exclusive to you. Try `kick_ticks: 0`

**Comment by marint94** [comment]
I'm not the only one...
Take a look at: https://github.com/konsolas/AAC-Issues/issues/446

**Comment by CeIebrimbor** [comment]
They just asked how to disable and never got back after being told how to disable.

**Comment by marint94** [comment]
I just removed the **climb:** entry from the Config and did **/aacreload**
and now it's working.
I'm not sure which one of those actually did the trick.

**Comment by marint94** [comment]
Same thing for @ihd9kill
Removing climb: and doing /aacreload did the trick.
