### ISSUE TITLE
Server crash related to flying speed?

### ISSUE THREAD

**Issue by SecretlyJealous** [konsolas/AAC-Issues#453]
### Core information
**Server version**: 1.11.2

**AAC version**: 3.0.4

**ProtocolLib version**: Build #346

Server crashed, mentions something about speed and an AAC error appears before the crash occurs.
Server log: https://hastebin.com/qisakonolu.sql
AAC log: https://hastebin.com/agasebimot.sql

**Comment by CeIebrimbor** [comment]
Looks 100% unrelated. Plugin list please.

**Comment by SecretlyJealous** [comment]
Sorry, I guess I should have also made clear that I was using this plugin to prevent this crash from happening by enabling the speed checks, here's the crash without the plugin https://hastebin.com/fasonajiwu.md since it mentions something about flying too fast? Was hoping the logs would diagnose the issue. I've also attached my plugin list but many of them are custom.
![2017-02-15_09 48 49](https://cloud.githubusercontent.com/assets/10485646/22969305/f18891c6-f365-11e6-8684-022ac9be2622.png)

**Comment by konsolas** [comment]
The AAC error happens at least a minute before the crash, and appears to be benign. There are no violations from AAC around the time of crash, either. The AACTiming-Executor and AAC-LogWriter threads are both waiting + AAC appears nowhere else in the stack trace of the crash. 

I would suggest using the standard server help forums for this.
