### ISSUE TITLE
Wurst Multi_Aura Bypass (1.9+ combat)

### ISSUE THREAD

**Issue by wanted156** [konsolas/AAC-Issues#455]
I've installed the plugin on my server and then uploaded a config from Celebrimbor, which is working fine, but no killaura is being detected at all. At first it did detect some, but then nothing. Not even on default config. We tried with KillAura, MultiAura and KillAuraLegit. I've attached a link to the video i made, there you can also see the list of our plugins.

AAC log: https://hastebin.com/pobonaxezo.sql
Video: https://drive.google.com/file/d/0B6OFNMC-4UaIazBMcXFKNVgtLTA/view
In-Game names:
               "Hacker": Bolla4000
               Players: Tadumc412. XpZANpX

**Server version**: 1.11.2

**AAC version**: 3.0.4

**ProtocolLib version**: 4.2.1 - SNAPSHOT b347

**Plugin list**: http://prntscr.com/e9zdwc

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: http://prntscr.com/e9ze5k

Tried it yesterday, 17.2.2017 at ~22.44

**Comment by CeIebrimbor** [comment]
Probably time to spend time on revitalizing 1.9+ combat due to delayed attacking.

**Comment by CeIebrimbor** [comment]
v3.2.1 is adding a 1.9+ combat heuristic to address most bypasses related to the delayed 1.9 combat.
