### ISSUE TITLE
1.9+ Heuristic

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#456]
Due to the clear distinction between 1.8(spam clicking) and 1.9+(slow, timed hits), AAC should treat the combat detection differently based on server version.

Illegal hits for 1.9+ may register on AAC as illegal, but hack clients have all transitioned to correctly space the attack time to land a full strength hit instead of spamming just below legal click limits (1.8). As a result, AAC takes _way_ too long to detect for KA if the player is only fighting 1-2 players. Usually long enough where the combat is over before high enough detection or slow enough where VL is reduced in between naturally timed hits. I even see Wurst's Multi-Aura slip by(#455) while fighting 2 players.

I request you detect for the full strength hits and add extra weight to them. You can even ignore <30% charged hits since they are completely worthless in combat and that would prevent spam hits from counting towards violations(false kicks).

Something like:
<30% = 1VL/hit
31-99% = 2VL/hit
_(no hack client would use a less than full strength hit)_
100% = 6VL/hit

Can be applied to both Hitbox and KillAura. Since you would be developing to recognize charged hits, you can also toss in detection for time between full strength hits. Much like FastUse, cancel hits if the time between full strength hits is too quick. New check? Add to FightSpeed?

Both need option to disable since some 1.9+ servers force 1.8 mechanics.

**Comment by SnakeDaoust1232** [comment]
I agree. That would be awesome if the plugin was smart enough to change the way it acts based on server version.

**Comment by JuliCarles** [comment]
What if the server version is 1.9 but it's using a plugin to get back to the 1.8 combat mechanics?

**Comment by Pluginsel** [comment]
I agree. I hope the @konsolas confirm and add to AAC in the next updates. :)

**Comment by Janmm14** [comment]
Idk exactly, but I think its not possible to get full-strength hits faster with a cheat client.

**Comment by CeIebrimbor** [comment]
Closing #454 and modifying this request.

@konsolas 1.9+ heuristic? (as you said should happen)
