### ISSUE TITLE
False Positive | Cactus stair 

### ISSUE THREAD

**Issue by johand199** [konsolas/AAC-Issues#457]
Issue type (console error/false positive/bypass/other):
False Positive

Server version:
Spigot 1.8.8-R0.1-SNAPSHOT

ProtocolLib version:
4.2.0

AAC version:
AAC 3.0.4

ViaVersion version (if present):
1.0.3

A video proving the bypass/false positive if reporting a bypass/false positive:
https://www.youtube.com/watch?v=rBonaXfb_Pw

**Comment by Janmm14** [comment]
I blame spigot partly for this issue, however its aac's issue because it wants to built around the spigot issue.

**Comment by CeIebrimbor** [comment]
Video gone. Still valid? Crucial?

**Comment by SnakeDaoust1232** [comment]
?
