### ISSUE TITLE
Underwater sign speed fps

### ISSUE THREAD

**Issue by johand199** [konsolas/AAC-Issues#458]
Issue type (console error/false positive/bypass/other):
False Positive

Server version:
Spigot 1.8.8-R0.1-SNAPSHOT

ProtocolLib version:
4.2.0

AAC version:
AAC 3.0.4

ViaVersion version (if present):
1.0.3

A video proving the bypass/false positive if reporting a bypass/false positive:
https://www.youtube.com/watch?v=pAlM3Kd76nc

**Comment by Photon-GitHub** [comment]
I can no longer reproduce this and therefore close this as fixed.
