### ISSUE TITLE
Fly false positive

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#46]
If you break the blocks a player is standing on he'll get detected for fly.

**Comment by konsolas** [comment]
Tested on a cobblestone tower with efficiency 100, unable to reproduce.

**Comment by Photon-GitHub** [comment]
Wait a sec, I will join the test server

**Comment by konsolas** [comment]
So further clarification: 
Another player needs to break the blocks a player is standing on. Reproduced with a player on a cobblestone tower. Other player in creative breaking the blocks below.

**Comment by CeIebrimbor** [comment]
Nice...Tricky. You were resetting NoFall and Fly for a client block break? Now any break?

**Comment by konsolas** [comment]
If the block is directly below the client, I think.

**Comment by konsolas** [comment]
Added a generic solution for block breaking. Will also work with plugins that trigger the block break event.
