### ISSUE TITLE
AAC 3.0.4 2 crashes cv.a:16 (HashMap) + ai.a:3

### ISSUE THREAD

**Issue by SecretlyJealous** [konsolas/AAC-Issues#461]
### Core information
**Server version**: 1.11.2
**AAC version**: 3.0.4
**ProtocolLib version**: ProtocolLib v4.2.1-SNAPSHOT-b346
Crash log: https://hastebin.com/tovagaloya.md

**Comment by konsolas** [comment]
Can you estimate how long your server was running before this crash? 

_note: pvlg/cv_

**Comment by SecretlyJealous** [comment]
Yeah it was running for around 12 hours

**Comment by SecretlyJealous** [comment]
Here's another crash which seems similar: https://hastebin.com/gamoyipuqe.md
