### ISSUE TITLE
v3 Piston bug//speed

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#462]
Pretty sure there was a similar issue like this before, but it's back. When you activate a piston while standing on a it in a certain way, it will flag for speed and phase. https://www.youtube.com/watch?v=iUrwAgSVTrg

**Comment by Rqcco** [comment]
*Tested on the 1.8 Test server*

**Comment by konsolas** [comment]
Unclear if this is still an issue unfortunately, current piston tests seem to work.
