### ISSUE TITLE
Spam error console

### ISSUE THREAD

**Issue by duckweedvn** [konsolas/AAC-Issues#463]
Server version: Paper-Spigot 1.8.8
AAC version: 3.0.5
ProtocolLib version: ProtocolLib v4.2.0
picture : http://i.imgur.com/wRrQTYR.jpg
log : http://pastebin.com/fZrDSHqR

**Comment by xGodly** [comment]
I also have a "Could not pass event PlayerMoveEvent" D:

**Comment by Janmm14** [comment]
Please look up in logs recent after server start. Java optimizes the cause-stacktrace away when an error happens really often, so the real error is not visible in those logs anymore

**Comment by konsolas** [comment]
This issue was closed because the code has changed so much, it is no longer likely to be valid. The stack trace no longer points to useful information.
