### ISSUE TITLE
Low ping false positives 

### ISSUE THREAD

**Issue by dentoffe** [konsolas/AAC-Issues#464]
Hey I was on the test server with my friend who lives in AU I was hacking and he got kicked all time for no knock back and kill aura he did not hack I did so that's the weird thing

**Comment by SnakeDaoust1232** [comment]
The default configuration values are not that good. You might want to consult @CeIebrimbor for a custom config setup.

**Comment by CeIebrimbor** [comment]
AAC's default are really good at stopping maximum hacks, just sometimes touchy for the 200ms+ players. And basically unplayable for 400ms+

**Comment by CeIebrimbor** [comment]
If you can replicate false kicks that are not due to insane lag, please report with data.
