### ISSUE TITLE
Placing spawn eggs through walls

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#465]
Players are able to use freecam to place spawn eggs thru walls. All the player needs to do is break the blocks in freecam so that your client thinks that the blocks are actually broken when they're actually not, then the player just simply places the spawn egg on the opposite side of the wall and is able to ignite it. 

https://www.youtube.com/watch?v=_3ArRIku0_Q&feature=youtu.be

###Core information
Server version: Paperspigot-c0e7853 (1.8.8)

AAC version: 3.0.5

ProtocolLib version: 4.2.0

Plugin list: https://vgy.me/RAY2Rl.png

ViaVersion version: 1.0.3

**Comment by Mikgreg** [comment]
Not sure how relevant to the issue the server in the video is mine and here's the correct versioning info:

Server version: Paper 1060 (1.11.2)
AAC: 3.0.5
Protocollib: 4.2.1
Protocolsupport: 4.25
Viaversion: not present

**Comment by Janmm14** [comment]
This is possible due to `cancel_vl_place: 5` in the interact section of the default config.

**Comment by konsolas** [comment]
closing due to insufficient info (labelled by Janmm14)
