### ISSUE TITLE
High-Speed Stepping = Phase

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#466]
Players with high-speed potions trigger phase on steps and carpeted slabs.

Videos:
https://youtu.be/40h3FjzKMUc
https://youtu.be/I7LG_oXk7DY

Logs:
http://pastebin.com/gkBDL8Zd

**Core information**

Server version: 1.8.8

AAC version: 3.0.5

ProtocolLib version: 4.2.0

Plugin list: Just /effect applied Speed potion level 10

Special environment information

ViaVersion version: 1.0.4

ProtocolSupport version: none

ViaBackwards version: none

BungeeCord plugins: https://gyazo.com/e7cdeb2b15b98aac1a6fade31868b092

**Comment by Janmm14** [comment]
Same issue with knockback
