### ISSUE TITLE
Quick Switching | World teleport grace period

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#467]
I've been waiting for three of these to start using AAC on my network.
- QuickSwitching (https://github.com/konsolas/AAC-Issues/issues/340)
- World Teleport Grace Period (https://github.com/konsolas/AAC-Issues/issues/414)
- Killaura Heuristic Bypass (https://github.com/konsolas/AAC-Issues/issues/370)

Video: https://www.youtube.com/watch?v=BY3njV3a1Ts&feature=youtu.be

Config: https://hastebin.com/fotuxatuja.bash

Server Version: PaperSpigot/TacoSpigot 1.8

AAC version: Newest 3.0.5

**Comment by Janmm14** [comment]
The problem is that these heuristics are not made for fighting vs afk players.

**Comment by SnakeDaoust1232** [comment]
I understand it would be hard. Thats why im not really worried about the Heuristic false positives more-so the bypass if someone cheats a lot, then just relogs. And just for context, people arent "afk". Im simulating if you get someone in a combo and they are not able to hit you and you are able to just keep hitting them over and over, due to latency. Real world scenario: https://www.youtube.com/watch?v=gPtEWko_WoE I already explained my reasoning for having the Heuristics check so high (VL20). I "need" the others fixed though. 340, and 414.

**Comment by Janmm14** [comment]
Hmm, I don't know those heuristics either, but I see some differences in fighting afk players than that, but don't quote me there.
