### ISSUE TITLE
NoFall false positive

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#47]
If you break the blocks a player is standing on he'll get a ridiculous amount of fall damage (the complete fall even though he didn't fall all the way down and stopped sometimes)
-> The old NoFall digdown bug is back

**Comment by CeIebrimbor** [comment]
I tested this with Efficinecy 5, 20 and 50. 
Ping=170ms

I got a single Fly detection (VL3), but nothing for NoFall. I recall the bug you refer to, but I don't think that fall damage is AAC. I think you're just digging so fast that you're falling slower than you dig. I too got deadly damage with Efficiency 20 and 50.

**Comment by konsolas** [comment]
@CeIebrimbor do you think this is sufficient to close?

**Comment by CeIebrimbor** [comment]
I think there are NoFall issues to be discovered, but not here.
