### ISSUE TITLE
Hacks not blocked

### ISSUE THREAD

**Issue by DatJamaican** [konsolas/AAC-Issues#473]
I have been testing this pluging and it doesnt block this client well https://www.wizardhax.com/2016/07/08/minecraft-aristois-1-10-x-1-10-1-10-2-hacked-client-with-optifine-download/

**Comment by CeIebrimbor** [comment]
Please be specific. Hack bypassed, AAC settings, version, server version.

In other words, use the template you deleted.

**Comment by DatJamaican** [comment]
ok

**Comment by CeIebrimbor** [comment]
@DatJamaican I assume you lost interest in pursuing this? Please post more info to reopen or open a new report with supporting data if you want this addressed.
