### ISSUE TITLE
Error on startup Occasionally

### ISSUE THREAD

**Issue by alexmarkey** [konsolas/AAC-Issues#474]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Running AAC on ~400 minigame instances.  Occasionally after the recent updates 3.0.5+ the server will not start rarely, putting the server into a 'locked' phase.  This is the error fired on startup:

http://pastebin.com/LfvJ3n4F

All players attempting to log in will not be kicked for the reason "Server is starting up".
### Core information
**Server version**: http://prntscr.com/eewl0f

**AAC version**: 3.0.5b

**ProtocolLib version**: 4.2.0

**Plugin list**: http://prntscr.com/eewl6a

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.0.2

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Janmm14** [comment]
Try 3.0.5 instead of 3.0.5b1 then.

**Comment by alexmarkey** [comment]
Reproduced on 3.0.5 aswell.

**Comment by konsolas** [comment]
This issue was closed because the code has changed so much, it is no longer likely to be valid. The stack trace no longer points to useful information.
