### ISSUE TITLE
Tree Feller NoSwing check

### ISSUE THREAD

**Issue by Roadhog360** [konsolas/AAC-Issues#476]
### Core information
**Server version**: 1.8.8

**AAC version**: Latest

**ProtocolLib version**: Latest

**ViaVersion version**: Latest

**ProtocolSupport version**: Last version that works for 1.8.8

The Tree Feller plugin for Epic World Generator triggers AAC's NoSwing check. Please fix it so my players can chop trees.

**Comment by Janmm14** [comment]
Disable NoSwing or ask EpicWorldGenerator to hook into AAC I'll guess. AAC itself won't built in support for more plugins in the near future at least.

**Comment by Roadhog360** [comment]
If he wants a paid plugin, least he can do is add support for other plugins.
I did this and it still kicks people for using NoSwing.

**Comment by CeIebrimbor** [comment]
@Roadhog360 You want a single plugin to tie into 5 plugins(anti-cheats), or your anti-cheat to tie into 50,000 plugins?

**Comment by Roadhog360** [comment]
What does that have to do with the one plugin I'm reporting an issue for?

**Comment by Roadhog360** [comment]
And how exactly is AAC ignoring disabled checks 'unimportant' to you?

**Comment by CeIebrimbor** [comment]
You claim AAC should tie any plugin reported(I get you spent money and want special treatment). I'm not saying that will never happen, it's just not on top of priority things to do. Better solution is the plugin causing issues with anti-cheats (which hundreds of thousands of servers use) to tweak the single skill that conflicts with the anti-cheats.

Or...you can wait for AAC to tie into and plugin downloaded by 1,800 people.

**Comment by Roadhog360** [comment]
Okay. But can we still look into why checks aren't disabling? I disable NoSwing but it still checks for and punishes 'NoSwing'.

**Comment by CeIebrimbor** [comment]
That means you likely have a config error. Delete config, redownload latest AAC, restart server, disable NoSwing. See what happens?

**Comment by Janmm14** [comment]
Or watch console in case of a config error you will likely see the problematic line in it.

**Comment by Roadhog360** [comment]
I'm just switching to Spartan. It's already working better. There is no config error and at that you should be able to see the issue for yourself. And my config changes were working before I set NoSwing to false, so there's your proof it's not a config error.

**Comment by Roadhog360** [comment]
Just want to say I occasionally come back here to laugh at this plugin's support. Spartan is cheaper, has better support, and doesn't ask everyone else to fix their own plugin like you are. Treat your paying users like actual paying users instead of forking YOUR compatibility issues onto the hands of others. Besides, the TreeFeller dev doesn't want to add compatibility because he is arrogant and says all plugins are worse than his own.

**Comment by CeIebrimbor** [comment]
I just want to say I love getting update notifications for this issue so I can laugh about how important people think their opinions are. That they would take time out of their day to remind people they are still on strike a month later based solely on their superiority complex after being told their issue, inconveniencing _maybe_ .1% of server owners, was not escalated to the front lines in importance because they spent money.

Meanwhile, AAC sells on a 2(or 3):1 ratio to Spartan just based on the merit of the quality of development alone, regardless of cost. The value of your forfeited funds and comedic relief is much appreciated.

**Comment by Roadhog360** [comment]
The value of your comedic relief is also appreciated. Just because more people buy AAC doesn't make it better, and the fact you act like it does makes me laugh even more. Good day to you. One day you should do comedy.

**Comment by Janmm14** [comment]
@Roadhog360
Not like the overview is stating what is compatible.
Plugins not listed there and doing random things in game mechanics should be considered incompatible by default.

Might be that Spartan has better support and a better compatibility list, at least I don't care.
