### ISSUE TITLE
IllegalArgumentException: ClassCastException 3.0.5b1 bL.a:25

### ISSUE THREAD

**Issue by Tyloonie** [konsolas/AAC-Issues#477]
*Edit by staff: compacted the issue*
~~My Console is being spammed all the time because of this error. I am not sure what triggers it, I hope you can help me.~~
~~Error: https://hastebin.com/awepebuguf.css~~~
~~konsolas: ProtocolLib is not up to date.~~
ProtocolLib update fixed it.

The server is generating another error now: https://hastebin.com/mugozopoco.vbs

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 3.0.5-b1

**ProtocolLib version**: 3.6.5

**ViaVersion version**: 1.0.4

**Comment by Tyloonie** [comment]
Also, you need to update the default config on your Spigot page.

**Comment by konsolas** [comment]
ProtocolLib is not up to date.

**Comment by Tyloonie** [comment]
Okay, now it is up to date. The server is generating another error now.

https://hastebin.com/mugozopoco.vbs

**Comment by Janmm14** [comment]
Closing this because of #506 is apparantly the same issue, but in the newest aac version
