### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by NEZNAMY** [konsolas/AAC-Issues#478]
### Issue description

Error: http://pastebin.com/FhMV2dwE

### Core information

**Server version**: 1.11.2
**AAC version**: 3.0.5-b1
**ProtocolLib version**: build 345 (should I update ?)
**Plugin list**: WE, essentials, plotsquared, AAC, protocol lib, protocol support and my own

### Special environment information

**ProtocolSupport version**: build 25
**BungeeCord plugins**: skins restorer and my own

**Comment by Janmm14** [comment]
Closing because I decided that I centralize this issue at #492
