### ISSUE TITLE
Server still starting up error

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#479]
Error log: https://hastebin.com/joxogevufe.bash

Server version: 1.8.9 (lates)
AAC version: 3.0.5-b1
ProtocolLib version: 4.1.0

I have only sometimes/randomly the problem with the error

**Comment by CeIebrimbor** [comment]
ProtocolLib Version: http://ci.dmulloy2.net/job/ProtocolLib/341/

Request reopen if error still exists.
