### ISSUE TITLE
[Feature] An idea for a Forcefield check

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#48]
So when players are eating any type of food or have their bow drawn, if they're using aura they'll begin to hit while eating/drawing the bow which is 100% impossible to do legitly, which for the most case shows that they're using forcefield.

Why not have a check that spawns an NPC above/around the player while they're eating food/drawing their bow, it'd make for really clear evidence for a player using forcefield.

**Comment by CeIebrimbor** [comment]
Impossible Interact covers this @konsolas

**Comment by konsolas** [comment]
This is covered by impossibleinteract.

**Comment by konsolas** [comment]
Covered by impossibleinteract.
