### ISSUE TITLE
AAC and BukkiGames sometimes don't allow player to join

### ISSUE THREAD

**Issue by xion87** [konsolas/AAC-Issues#481]
PLEASE read the guidelines for contributing which is linked above.
### Issue description
I noticed if i install AAC on my bukkitgames games 1 time of 10 after a restart, player can't join the server, i dont' have any message on server, but only in bungee about connections/disconection from that server
I run AAC 3.0.5, server is under Waterfall and have these plugins SQLibrary, ViaVersion, 
mSkript, WildSkript, BountifulAPI, BukkitGames, BGAbilities, AAC, Protocollib

I am sure that is AAC or Protocollib because if i reverted to NCP, i stopped to have these issues

### Core information
**Server version**: 1.8.8

**AAC version**: 3.05

**ProtocolLib version**: 4.2.0

**Plugin list**: server is under Waterfall and have these plugins SQLibrary, ViaVersion, 
mSkript, WildSkript, BountifulAPI, BukkitGames, BGAbilities, AAC, Protocollib

### Special environment information

**ViaVersion version**: 1.0.4

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: skinsrestorer, litebans

**Comment by Janmm14** [comment]
Are you sure your bukkit/spigot server has no error in the console if that happens?

**Comment by xion87** [comment]
there is no error

**Comment by Photon-GitHub** [comment]
Is this still valid?

**Comment by xion87** [comment]
yeah is not solved

**Comment by CeIebrimbor** [comment]
Was there any more information about this other than "It might be AAC and it seems to not happen on NCP?"

**Comment by xion87** [comment]
well i put AAC = random player can't join until restart the server instead this don't happen with NCP,  (i think is a issue with some packets)

**Comment by konsolas** [comment]
As requested by OP

**Comment by Janmm14** [comment]
@xion87 Please create a new issue for that (and state more informatiom like your aac / protocollib version)

**Comment by konsolas** [comment]
Still invalid.
