### ISSUE TITLE
OP Efficiency = Fastbreak

### ISSUE THREAD

**Issue by Twi5TeD** [konsolas/AAC-Issues#482]
on my op prison i have high efficiency which is at 40 and when mining i get kicked ive bought the custom config from ] Celebrimbor and hes told me to  change let_ticks from 4 to 12 to see if i still get kicked which i do so that is why i have opened this report. 

Please include details like:
* AAC logs / Full console error
http://pastebin.com/2d8Gexia

### Core information
**Server version**: CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**AAC version**:
[PlugMan] Plugin Information: AAC
 Version: 3.0.5
Author(s): konsolas
Status: Enabled

**ProtocolLib version**: 
[PlugMan] Plugin Information: ProtocolLib
Version: 3.6.5
Author(s): dmulloy2, comphenix
Status: Enabled

**Plugin list**: 
Plugins (89): AAC, ActionAnnouncer, Alts, AnimatedNames, AutoSell, BankCheque, CategoryWarps, ChatControl, ChatItem, ChatReaction, ChestShop, Citizens, ClaimDonation, CleanroomGenerator, CoinFlip, CombatTagPlus, CommandNPC, ConditionalCommands, Core, CoreProtect, CrazyAuctions, CrazyCrates, CrazyEnvoy, DeathMessages, DeliveryMan, DeluxeChat, DeluxeJoin, DeluxeTags, DropParty, Essentials, EssentialsSpawn, EZBlocks, EZBlocksColourAddon, EZPrestige, eZProtector, EZRanksPro, FastAsyncVoxelSniper, FastAsyncWorldEdit, FeatherBoard, GAListener, GangsPlus, HelperChat, HolographicDisplays, CustomInvFull, KitPreview, CustomBlackList, CustomFreeze, CustomList, LiteBans, MCAuthenticator, MCDiscordIntegrator, MessageAnnouncer, CustomMineBows, MinecraftMarket, MineCrates, MOTDgdCommandAd, Multiverse-Core, MysteryBox, NamelessMC, CustomNoFly, PandorraBounty, ParticleAPI, PermissionsEx, CustomPickSell, PingManager, PlaceholderAPI, PlayerMention, CustomPlayTime, PlotMines, PlotSquared, PlugMan, PrisonMines, ProtocolLib, RankVouchers, ServerListPlus, SignEdit, TitleManager, TokenEnchant, TradePlus, Vault, ViaVersion, VKBackPack, VoidWorld, VoteParty, Votifier, VoxelSniper, WorldEdit, WorldGuard, YoutubersPlus

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 
[PlugMan] Plugin Information: ViaVersion
Version: 1.0.4
Author(s): _MylesC, Matsv
Status: Enabled

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by CeIebrimbor** [comment]
Please update to ProtocolLib version 4.2.0 and report back if/when issue still occurs. I doubt it will fix, but just making sure we have all the appropriate conditions.

**Comment by Twi5TeD** [comment]
[16:09:02] [Server thread/INFO]: [PlugMan] Plugin Information: ProtocolLib
[16:09:02] [Server thread/INFO]: - Version: 4.2.0
[16:09:02] [Server thread/INFO]: - Author(s): dmulloy2, comphenix
[16:09:02] [Server thread/INFO]: - Status: Enabled


updated it and still happens

**Comment by Twi5TeD** [comment]
any update on this?

**Comment by Photon-GitHub** [comment]
I can no longer reproduce this and therefore close this as fixed.

**Comment by Twi5TeD** [comment]
when was the new update for aac released so i can try as i cannot get on spigot as its down right now
