### ISSUE TITLE
Performance Issue/Suggestion

### ISSUE THREAD

**Issue by Tyloonie** [konsolas/AAC-Issues#483]
I must admit that a more performance friendly version of AAC would be much appreciated. I know the plugin "RunesEnchant" is using a lot of resources as well, I will be contacting him too. Anyways, could you maybe try and optimize the code? With more players, my server would end up lagging really fast with these high percentages AAC is producing.

Timings: https://timings.spigotmc.org/?url=pawacabafo

Server version: Spigot 1.8.8

AAC version: 3.0.5-b1

ProtocolLib version: 4.2.0

ViaVersion version: 1.0.4

**Comment by CeIebrimbor** [comment]
Your timings show AAC is not all that heavy considering it _should_ be the heaviest thing running on any server just due to the nature of what anti-cheats accomplish. You are not having any notable TPS loss based on that timings.

Future versions will reimplement some lost performance when Konsolas had to rewrite the obfuscation to appease Spigot. My recommendation is you downgrade to 3.0.5 since b1 was just the patch I just mentioned and will drop performance. 3.0.5 has the same features as well.

Request re-open if you feel as though AAC 3.0.5 is still the main cause for TPS loss after downgrading.

**Comment by Tyloonie** [comment]
Hi,

I now get this error in my Console...

`08.03 19:42:02 [Server] WARN Task #472 for AAC v3.0.5 generated an exception
08.03 19:42:02 [Server] INFO java.lang.IllegalArgumentException: java.lang.ClassCastException@4d48bb8
08.03 19:42:02 [Server] INFO at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
08.03 19:42:02 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
08.03 19:42:02 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
08.03 19:42:02 [Server] INFO at me.konsolas.aac.fs.a(fs.java:55) ~[?:?]
08.03 19:42:02 [Server] INFO at me.konsolas.aac.fs.a(fs.java:26) ~[?:?]
08.03 19:42:02 [Server] INFO at me.konsolas.aac.fs.a(fs.java:94) ~[?:?]
08.03 19:42:02 [Server] INFO at me.konsolas.aac.bf.a(bf.java:32) ~[?:?]
08.03 19:42:02 [Server] INFO at me.konsolas.aac.z.run(z.java:2) ~[?:?]
08.03 19:42:02 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.03 19:42:02 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.03 19:42:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.03 19:42:02 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.03 19:42:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.03 19:42:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.03 19:42:02 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

**Comment by Rqcco** [comment]
@Tyloonie Open a new issue
