### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mxngo** [konsolas/AAC-Issues#485]
ERROR [AAC] Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC
11.03 12:49:43 [Server] INFO java.lang.NullPointerException
11.03 12:49:43 [Server] INFO at me.konsolas.aac.q.onPacketReceiving(q.java:15) ~[AAC.jar:3.0.5]
11.03 12:49:43 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib%20(1).jar:4.2.1-SNAPSHOT-b350]
11.03 12:49:43 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib%20(1).jar:4.2.1-SNAPSHOT-b350]
11.03 12:49:43 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib%20(1).jar:4.2.1-SNAPSHOT-b350]
11.03 12:49:43 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib%20(1).jar:4.2.1-SNAPSHOT-b350]
11.03 12:49:43 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib%20(1).jar:4.2.1-SNAPSHOT-b350]
11.03 12:49:43 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib%20(1).jar:4.2.1-SNAPSHOT-b350]
11.03 12:49:43 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib%20(1).jar:4.2.1-SNAPSHOT-b350]
11.03 12:49:43 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib%20(1).jar:4.2.1-SNAPSHOT-b350]
11.03 12:49:43 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39) [ProtocolSupport.jar:?]
11.03 12:49:43 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-1.11.jar:git-Spigot-283de8b-eac8591]
11.03 12:49:43 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
11.03 12:49:43 [Server] ERROR Parameters: 
11.03 12:49:43 [Server] INFO net.minecraft.server.v1_11_R1.PacketPlayInArmAnimation@39a1c89a[
11.03 12:49:43 [Server] INFO a=MAIN_HAND
11.03 12:49:43 [Server] INFO ]

**Comment by Photon-GitHub** [comment]
Not all information which is needed is provided.
