### ISSUE TITLE
Could not pass event PlayerMoveEvent: Console Spam

### ISSUE THREAD

**Issue by xGodly** [konsolas/AAC-Issues#487]
Could not pass event PlayerMoveEvent:

Error: http://pastebin.com/KYwRG7SH

**Server version**: 1.11

**AAC version**: 3.0.5-B1

**ProtocolLib version**:  #newest

**Plugin list**: http://prntscr.com/eivi0m

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: none

**ProtocolSupport version**: 4.25

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Justinis77** [comment]
me too ...

**Comment by marint94** [comment]
me too

**Comment by Janmm14** [comment]
closing as duplicate of #492 (i know that issue was reported later on)
