### ISSUE TITLE
fightspeed consistent_check + mining = 20CPS + VL

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#488]
Player mining normally gets "CPS of 20" and unlimited increase in VL until kick.

Log+Config:
https://hastebin.com/ubacanufub.hs

**Server version**: 1.10.2

**AAC version**: 3.0.5-b1

**ProtocolLib version**: 4.2.0 (dev build 341)

**Plugin list**: VKBackPack, PlaceholderAPI, SkinsRestorer, ViaVersion, ViaBackwards, MinecraftMarket, AsyncWorldEditInjector, AnimationLib, Skript, VKAutoPickup, MineSecure, ProtocolLib, eZProtector, AsyncWorldEdit, PermissionsEx, FeatherBoard, ConditionalCommands, Tab, Vault, ServerListPlus, MassiveCore, CrazyCrates, FastLogin, MassiveCombat, AAC, GeneralMarket, EZPrestige, EZRanksPro, ShopGUIPlus, WorldEdit, MysqlPlayerDataBridge, Essentials, AnimatedNames, Citizens, TradeMe, AnimatedMenuPlus, PlotSquared, WorldGuard, EssentialsSpawn, EssentialsMysqlStorage, Multiverse-Core, MiniaturePets, AuthMe, HolographicDisplays, skRayFall, LeaderHeads, PrisonMines, AutoSell, LiteBans, DeluxeChat, MineCrates

Special cases:

**ViaVersion version**: 1.0.4

**ProtocolSupport version**: none

**ViaBackwards version**: 2.0

**BungeeCord plugins**: none

**Comment by Janmm14** [comment]
reproducible?

**Comment by CeIebrimbor** [comment]
Well, I put it to true after 3 months of it being false and 10 people confirmed "CPS 20" all day for mining. So pretty convinced. I haven't used consistent_check since 2015 because it's never been stable.

**Comment by konsolas** [comment]
honestly cannot reproduce this at all

**Comment by Janmm14** [comment]
@CeIebrimbor as you have 10 clients saying they have this false positive, please find similarities in their setup like: server version, client version, viaversion (version), protocolsupport (version), same other plugins in their plugin list.

I would call this a compability issue atm
