### ISSUE TITLE
[Feature] AACInfo

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#49]
**AAC Player Info**

Command: /aacinfo [Player]

What it does: This command would show the current violations that the player has flagged for, and the amount of times he/she has flagged for it. Similar to /ncp info.

**Comment by konsolas** [comment]
This is an idea that I want to do. To have something proper to work with, @Matthew777k can you come up with something more detailed about behaviour, chat format, and related?

**Comment by Matthew777k** [comment]
**(Note Chat Format # 1 is just NCP+'s chat format for NCPInfo, I just added it in so that you had more ideas in case you liked something about it.)**


**Chat Format # 1:**

AAC: Displaying [player's ign] violations...
AAC: [Time] [Check] [# of VL's]  

[Time] = The time that the player most recently flagged for that.
[Check] = The check/checks that the player has flagged for.
[# of VL's] = The number of times the player has flagged for that specific check.

Example:

AAC: Displaying Matthew777k's violations...
AAC: [19:38:10] forcefield VL 52
AAC: [19:42:29] noswing VL 22
AAC: [19:44:35] no knockback VL 31
AAC: [19:45:42] aimbot VL 62

http://i.imgur.com/j8MlWys.png


**Chat Format # 2:**

Retrieving [Player's name] info...
[Player]
[Player's UUID]
[Current status of the player] 
[LINE HERE] (&m----)
[Player's] violations:

[10:25:16] forcefield VL 268 

[10:22:48] criticals VL 120 

[10:16:29] autoclicker VL 16 

Example: 
http://i.imgur.com/KlBkZCQ.png


**Chat Format # 3:** 

Player: [Player]
Ping:
Violations - 

Example:
https://i.imgur.com/J6oyG5Z.png

**Comment by Matthew777k** [comment]
**Behavior:** 
The AACInfo starts off blank for every player until they flag for a cheat, once they flag for a cheat it gets logged into their AACInfo page. If they flag for that same exact cheat again it goes up to 2VL's, and so on. 

It could either be ordered by the most recent flag or just ordered by highest VL's to lowest VL's, doesn't really matter honestly.  

The main purpose of this command would be for staff wanting evidence for a ban, or for them wanting to double check a ban. Like lets say a staff member banned someone and is later having second thoughts on the player being banned, he/she would be able to /aacinfo the player and look and see whether or not the player was flagging for any cheats. If not, then it's clear that the player was probably not hacking. If so, then it's clear the player was indeed using cheats.

Also if a server is using AAC to autoban players, they would be able to double check bans with this to make sure that the player reached the correct # of VL's for AAC to autoban.

**Comment by konsolas** [comment]
Unsure about the merits of this in lieu of thew new GUI that has been implemented.

**Comment by Matthew777k** [comment]
That new GUI is basically what I was asking for, thanks a ton!

You can close this.
