### ISSUE TITLE
Suggestion: Make killing the player in /aackick configurable

### ISSUE THREAD

**Issue by MedicOP** [konsolas/AAC-Issues#490]

**Comment by CeIebrimbor** [comment]
What do you mean?

**Comment by MedicOP** [comment]
Currently the /aackick command kills the player and then kicks them. I suggest making the "killing the player" part configurable

**Comment by CeIebrimbor** [comment]
AACkick does not kill players unless you have `kill_loggers: true` which is false by default.

**Comment by MedicOP** [comment]
I thought kill_loggers was for combat loggers

**Comment by CeIebrimbor** [comment]
My config(which you use) tells you to use a dedicated plugin for combat logging. AAC's kills anyone who dealt or took damage from a mob or player and disconnected (or kicked) within the `combat_time` you set. It is VERY limited in configurability and is really considered an obsolete feature.

**Comment by MedicOP** [comment]
I have a custom combat logging plugin. You're misunderstanding my suggestion.

It says in the config.yml that the /aackick command kills players and then kicks them. It makes no sense to kill a player if they get kicked for for example spamming, hence why I'm suggesting to make it configurable.

It's also for compatibility reasons. Some minigames will break if you kill the player instead of just kicking them.
