### ISSUE TITLE
Suggestion: Log rotation

### ISSUE THREAD

**Issue by MedicOP** [konsolas/AAC-Issues#491]
The logs can take up quite a lot of space after a while, especially if verbose is enabled

**Comment by CeIebrimbor** [comment]
Maybe set a scheduled /aacreload every 24 hours?

**Comment by MedicOP** [comment]
My servers restart daily already, but the logs can still quickly take up a lot of space on the drive if old ones are not deleted.

**Comment by Photon-GitHub** [comment]
Maybe I should create a bot for stuff like that...

**Comment by MedicOP** [comment]
Since my server restarts daily, this is what I'm using now:

```java
long date = System.currentTimeMillis() - 10 * 24 * 3600 * 1000;

for (File file : new File("plugins/AAC/logs").listFiles()) {
            if (file.getName().endsWith(".log")) {
                if (file.lastModified() < date) {
                    file.delete();
                }
            }
        }
```

**Comment by Photon-GitHub** [comment]
![grafik](https://cloud.githubusercontent.com/assets/22870297/24067821/c635cd2a-0b81-11e7-86fe-74ee1b4c203d.png)
You should rather use this calculation...
I will add a logbot in the next update for both plugins.

**Comment by Photon-GitHub** [comment]
Will be in version 1.5 of AACAdditionPro.

**Comment by Photon-GitHub** [comment]
I added a LogBot to AACAdditionPro, you might want to take a look at this.
