### ISSUE TITLE
AAC disables itself without further notice (+ error in onDisable)

### ISSUE THREAD

**Issue by Zeyyphox** [konsolas/AAC-Issues#493]
### Issue description

Hey. I'm using this great plugin on my localhost server and, for test the anticheat with a friend, I decided to go on my real server (BoxToPlay). But, the plugin doesn't work on. The plugin file is the same... I don't understand.

* Console error : http://pastebin.com/pHFiM0J1

### Core information
**Server version**: Spigot-v1_8_8.jar

**AAC version**: 3.0.5-b1

**ProtocolLib version**: v4.2.1-SNAPSHOT-b350

**Plugin list**: TrainingPvP, AutoclickerVerif, KitBattle, Essentials, StaffPlus, GroupManager, EssentialsChat, ProtocolLib, SmoothKnockback, AAC (AAC in red)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Janmm14** [comment]
Use correct ProtocolLib version for your server version. Consult the overview for detailed information.

**Comment by Zeyyphox** [comment]
Nothing changes, the name of the plugin is still red.

**Comment by Zeyyphox** [comment]
Ok it's working now. I juste switched my server to paperspigot and boom it's working.

**Comment by Janmm14** [comment]
@Zeyyphox Strange. I am always using AAC on basic spigot 1.8.8 servers and had no problems so far.

**Comment by Zeyyphox** [comment]
Hmmm, strange yes xD. Thanks for your help dude 👍

**Comment by CeIebrimbor** [comment]
If this is still an issue on 3.1.6, please request reopen or open a new issue.
