### ISSUE TITLE
Fly 'invalid ability packets' if toggling fly with high latency

### ISSUE THREAD

**Issue by MedicOP** [konsolas/AAC-Issues#497]
Fly VL will skyrocket if a player lags while disabling fly mode.

**Example:** Player is currently flying. He deactives it using /fly command, but because of lag he continues being able to fly on his screen for 3 seconds. He proceeds to get banned for fly hacks. (invalid ability packets)

### Core information
**Server version**: 1.8.8

**AAC version**: 3.0.5-b1

**ProtocolLib version**: 4.2.0

**Plugin list**: Any /fly plugin, for example Essentials

**ViaVersion version**: 1.0.3

**Comment by Photon-GitHub** [comment]
I do not recommend to ban for fly and this is a known bug.

**Comment by CeIebrimbor** [comment]
@Konsolas add a brief delay in Violatikn accrual for the abilities portion of the check?

**Comment by Janmm14** [comment]
@CeIebrimbor @MedicOP 
This doesn't have to be an ability-packet violation skyrocket at all. Floating 3 seconds in-air will give 60 times at least 5 vl. (300 vl, likely more I guess)

You could maybe ask a developer to make a /fly command which disables fly only when the player is onground for the time until a fix is incoming. Alternatively you can also cancel the PlayerViolationEvent for Fly in case the external plugin detects low tps/lagging players who recently toggled of fly

**Comment by MedicOP** [comment]
@Janmm14 It is caused by invalid ability packets

**Comment by Janmm14** [comment]
uhm then maybe disable the invalid ability packet check. its not required to catch fly, it'll just kick wurst (and maybe some other similar clients) when one tries to enable vanilla fly

**Comment by MedicOP** [comment]
Yes, I have it disabled currently.

**Comment by MedicOP** [comment]
"Toggling fly whilst moving and switching gamemode"

Was this fixed? Or is that something else

**Comment by Janmm14** [comment]
@MedicOP This one is not fixed very liekly, but just the fly false positives when disabling fly whilst being in-air.

**Comment by konsolas** [comment]
Going to close because abilities is currently disabled by default.
