### ISSUE TITLE
Buying IT via 25€ PaySaveCard? 

### ISSUE THREAD

**Issue by Dad-Ju** [konsolas/AAC-Issues#499]
Hallo I only will Buy The plugin via PaySaveCard But I live in Germany so I only have an 25€ PaySaveCard so can I Buy IT By Sending The Code to You? 

PS:(Sry for my bad english) 

Good wishes Justin

**Comment by konsolas** [comment]
I'm afraid it's not possible to accept PSC with the logistics that go with it.
