### ISSUE TITLE
[Improvement] Detect fly ability packets (bad hack client instant detection)

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#5]
Fly ability packets seem to be sent by some bad hack clients and detecting them if they do not have the allowFlight flag might be a good idea if people really try to use Wurst (I've heard it would send such a packet)

**Comment by Photon-GitHub** [comment]
It not only sends one, but seven ability packets with no bits set.
Easy flag + kick 😄

**Comment by konsolas** [comment]
So yeah I just wrote this because why not.

**Comment by CeIebrimbor** [comment]
Lol... So VL 100 if a client sends a fly packet?

**Comment by konsolas** [comment]
yes :)
