### ISSUE TITLE
[Test-Server] [Feature] Install ProtocolSupport to support 1.8 & 1.9 hack clients

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#50]
ProtocolSupport does not limit things on the server for 1.10 players, it simply "translates" the packets for 1.9 and 1.8 clients (down to 1.4 I think)

**Comment by CeIebrimbor** [comment]
After v3 is solid on standard setup :+1:

**Comment by Janmm14** [comment]
Konsolas still wants to support 1.8,1.9 and 1.10 as far as I know.

**Comment by CeIebrimbor** [comment]
In a global jar running off latest Protocol. That is 100% confirmed.

As far as Protocol Hack support goes, that may be partially or entirely rules out (i.e. Maybe add support for 1.8-1.10 w/ ViaVersion but not 1.7 support in any form).

**Comment by Janmm14** [comment]
In normal ProtocolLib usage there might not be any changes needed when using ProtocolSupport or ViaVersion

**Comment by CeIebrimbor** [comment]
1.7 clients joining because of ProtocolSupport was definitely a disaster. ViaVersion worked out with the occasional exception to the phase check on soil.

**Comment by Janmm14** [comment]
Maybe its possible to limit ProtocolSupport to certain versions.

**Comment by CeIebrimbor** [comment]
He can even go as far to make AAC ignore 1.7 clients. Thus leaving it up to server owners to deal with the reluctant 1.7 clients who threaten to leave the server if they don't allow the unfair advantage for 1.7 pvp on a 1.8 server.

I think it's idiotic that 5% of a server's client spread can sway the motion of the entire server. Server owners are ready to either abandon AAC or let 1.7 clients cheat as an alternative to just removing obsolete client support. I really hope AAC doesn't waste time and effort or possibly open up reverse compatibility weaknesses to accommodate 1.7.

**Comment by konsolas** [comment]
I'll put up some 1.8 and 1.9 test servers on separate ports when we're comfortable that 1.10 is running well. ProtocolSupport probably isn't going to go well.
