### ISSUE TITLE
Suggestion/request addition for chest issues

### ISSUE THREAD

**Issue by Metisuneatn** [konsolas/AAC-Issues#500]
So I have tested this and I know for a fact this is an issue. Players using client side mods which tweak/organize inventories and chests automatically can crash servers. NoCheatPlus has some chest settings that control how fast and how many items can move at once. Is there any way to get a setting like that where it (I guess) limits the click speeds for items moving?

**Comment by CeIebrimbor** [comment]
https://www.spigotmc.org/resources/aacadditionpro.33590/

**Comment by Janmm14** [comment]
AAC will probably never include inventory checks.
Either use ViaVersion for a packet limit or NoCheatPlus/AACAdditonPro for basic inventory checks
