### ISSUE TITLE
Feature: ProtocolSupport & CrazyEnchantments

### ISSUE THREAD

**Issue by BoostedNetwork** [konsolas/AAC-Issues#507]
**Couldn't find a format, for feature requests**
Any chance you could implement compatibility for ProtocolSuport, as I run a 1.11.2 server but wish to have 1.8 clients join and ViaVersions doesn't support backwards compatibility, could you also add support for CrazyEnchantments, it does nearly have 40,000 downloads on Spigot, please.
**Currently my server runs:**
Latest PaperSpigot (1.11.2)
Latest ProtocolSupport
Latest ProtocolLib
Latest CrazyEnchantments

**Comment by OWERLORD01** [comment]
> Couldn't find a format, for feature requests
Any chance you could implement compatibility for ProtocolSuport, as I run a 1.11.2 server but wish to have 1.8 clients join and ViaVersions doesn't support backwards compatibility, could you also add support for CrazyEnchantments, it does nearly have 40,000 downloads on Spigot, please.
Currently my server runs:
Latest PaperSpigot (1.11.2)
Latest ProtocolSupport
Latest ProtocolLib
Latest CrazyEnchantments
AAC is compatible with protocolsupport (but you must block 1.7 and below with protocolblocker) but i still havent find any error with 1.7 and below XD So you can test, and if you find any error with 1.7 please block it with [protocolblocker](https://www.spigotmc.org/resources/protocolblocker.1170/)
@Konsolas said in FAQ:

> Will you make it work with 1.7? - No
