### ISSUE TITLE
Fly bypass | Step

### ISSUE THREAD

**Issue by OWERLORD01** [konsolas/AAC-Issues#508]
### Issue description

Please add an step check, pretty much every MC
client can bypass step! I dont even think that AAC
have anything to block Step... I tried to configure
fly, but i wasn't able to block step without false
positives :(

Please include details like:
* AAC logs / Full console error - No errors
* Video of the bypass, best with verbose chat output - i dont have time for to record it... But i tested and there is no VLs for fly after hacking, and nothing in verbose...

### Core information
**Server version**: TacoSpigot 1.11.2 - latest

**AAC version**: 3.1.0-b1

**ProtocolLib version**: Build [#348](http://ci.dmulloy2.net/job/ProtocolLib/348/) (Mar 1, 2017 5:03:42 PM)

**Plugin list**: AAC, Protocollib, AACAdditionPro, EssentialsX (+ spawn, protection and else), McMmo, and some others... Nothing special

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: none

**ProtocolSupport version**: [#38](https://build.true-games.org/job/ProtocolSupport/)

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Janmm14** [comment]
You could experimentally lower the tolerance of the fly check to block step. However lower tolerances than the default were not tested, so false positives could appear.

**Comment by CeIebrimbor** [comment]
User using leaked version of plugin, so closing this (and all issues from user).
