### ISSUE TITLE
Quick Switching | World Change Grace Period | Jumping speed false positive

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#509]
Notice: I've been waiting an extremely long time for a quick switching bug fix and an addition of a grace period on world change and/or teleporting a certain amount of blocks away. I've temporarily hot fixed the quick switching bug by changing the item scalar to .8 but the world change still flags for fly.

Main Bug: Jumping and sprinting with a speed 1 or 2 potion bans you. Yep, as simple as that.

Better Sprint Mod: https://minecraft.curseforge.com/projects/better-sprinting?comment=2

Video: https://www.youtube.com/watch?v=c4JopB5NgNo&feature=youtu.be

Core information

Server version:  TacoSpigot 1.8 (Bug persists on either 1.7 client or 1.8 client)
AAC version: 3.1.0b1
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/79111c31964e04b1631b0b36510e12ef

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/1a3e07fc5194de5dfeb3ffdd9684457c

**Comment by Janmm14** [comment]
Thanks for this bug report. I've already messaged konsolas about this issue directly.

**Comment by CeIebrimbor** [comment]
Is this really still valid? The video shows instant detection for speed 1 and jumping. Is it safe to say "this is fixable with a config tweak, so closing"?

@konsolas @Janmm14?

**Comment by SnakeDaoust1232** [comment]
A major config tweak that disable the ability for AAC to detect noslowdown. Needs to be fixed.

**Comment by Janmm14** [comment]
noslowdown aka item usage? setting item scalar to 1 should disable that

**Comment by SnakeDaoust1232** [comment]
@Janmm14 In order to compensate for the bug, you have to set the item scalar extremely high. And when you do that, AAC no longer picks up the noslowdown hack.
