### ISSUE TITLE
New velocity check | Bug

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#510]
Bug: Changing texture pack causing FP for velocity.

Video: https://www.youtube.com/watch?v=Y-WGOWxB8Yc&feature=youtu.be

Core information

Server version: TacoSpigot 1.8 (Bug persists on either 1.7 client or 1.8 client)
AAC version: 3.1.0b1
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/79111c31964e04b1631b0b36510e12ef

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/1a3e07fc5194de5dfeb3ffdd9684457c

**Comment by Janmm14** [comment]
Side note: It would also cause a false positive with the knockback check probably.

**Comment by konsolas** [comment]
I think I do want to do a fix for this - possibly in the next release

**Comment by konsolas** [comment]
This seems to be the only source of velocity false positives and also affects players with severe lag.
