### ISSUE TITLE
FEATURE | Phase alternate function

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#511]
Instead of running commands when the plugin detects you for phase it would be awesome if the plugin teleported you to the nearest "safe" area that wasn't in faction territory. I understand that the plugin prolly doesn't support factions right now but it would be awesome just for this one instance.

The positive to this is. If someone gets glitched into a block, and starts flagging for phase.. it doesn't ban them or kick them, rather just teleport them to a safe area.

**Comment by konsolas** [comment]
This could be implemented with the API by listening for PHASE violations, and then teleporting the player to a determined faction safe location.

Due to the multitude of factions plugins that exist (including custom, etc.), I'm not sure how realistic it is to build a hook into AAC.

**Comment by SnakeDaoust1232** [comment]
Just support the main two plugin massivecraft factions and factionsuuid. And tell people that xD
