### ISSUE TITLE
Speed false positive

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#513]
### Issue description

When I set a player's speed by player.setWalkSpeed(2.4) and give them jump boost level 1 effect, they get dragged back for speed hacking when they jump
This issue occurred since 3.1.0

### Core information
**Server version**: paperspigot 1.11.2 build 1076

**AAC version**: 3.1.0 b1

**ProtocolLib version**: build 353

### Special environment information

**ProtocolSupport version**: build 38

**Comment by Rqcco** [comment]
Try to make a video on it, I'll take your word for it though since another guy is having the same issue.

**Comment by Janmm14** [comment]
No need for video. Issue is known, probably patched on friday (tomorrow)

**Comment by MClausz** [comment]
This issue still happen in 3.1.1, video coming soon
