### ISSUE TITLE
Console Stack Trace

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#514]
Idk the trigger. We just got down with a duel and it teleported me to spawn.

Image: https://gyazo.com/1d09887d62714114fa8040bd5b5452e2

Core information

Server version: TacoSpigot 1.8 (Bug persists on either 1.7 client or 1.8 client)
AAC version: 3.1.0b1
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/79111c31964e04b1631b0b36510e12ef

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/1a3e07fc5194de5dfeb3ffdd9684457c

**Comment by Rqcco** [comment]
Is ViaVersion for 1.8-1.11 or 1.7-1.8?

**Comment by SnakeDaoust1232** [comment]
I believe its 1.8-1.11

**Comment by konsolas** [comment]
Stack trace no longer valid.
