### ISSUE TITLE
False speed hacking alert

### ISSUE THREAD

**Issue by Mxngo** [konsolas/AAC-Issues#515]
If I has Speed2 and ran and kept jumping
the player gets stuck and a hacker alert 
is notified to admins!

### Core information
**Server version**: 1.11

**AAC version**:   3.1.0

**ProtocolLib version**:  newest

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**:  none

**ProtocolSupport version**: yes

**ViaBackwards version**:  none

**BungeeCord plugins**:  none

**Comment by OWERLORD01** [comment]
> If I has Speed2 and ran and kept jumping
 the player gets stuck and a hacker alert
 is notified to admins!
Core information
Server version: 1.11
AAC version: 3.1.0
ProtocolLib version: newest
Special environment information
Insert 'none' if you don't use it
ViaVersion version: none
ProtocolSupport version: yes
ViaBackwards version: none
BungeeCord plugins: none

I havent got this issue on my server....

**Comment by MClausz** [comment]
I have the same issue (#513)

**Comment by Rqcco** [comment]
#513
