### ISSUE TITLE
AAC 3.1.0 Bypass...

### ISSUE THREAD

**Issue by Pluginsel** [konsolas/AAC-Issues#516]
1) Speed (25% faster) and LiquidWalk (Jesus) bypass.
Video : https://www.youtube.com/watch?v=Fd_XYQxXv4s
Client download: http://liquidbounce.net/
Version: 1.8.8
Tested: Yes.
Tested Server: ccbluex
Working on AAC 3.1.0 : Yes.

2) (nearly) perfect NoFall ++ LongJump ++ 2-Block-Jump / Step
Video: https://www.youtube.com/watch?v=2vgiJVTs_zY
Client: Private, this is not public.
Version: 1.8.8
Tested: No.
Tested Server on video: ccbluex
Working on AAC 3.1.0 : Yes.

3) AAC 3.1.0 FastClimb Bypass
Video: https://www.youtube.com/watch?v=TE5WI4wJb1E
Client Download: http://liquidbounce.net/
Version: 1.8.8
Tested: Yes.
Tested Server: ccbluex
Working on AAC 3.1.0 : Yes.

Waiting for fix on next update :)

**Comment by Marco-MC** [comment]
Yeaaaahhhh, patch my liquidbounce bypasses @konsolas. I find than new and neww annnnnnnnnnnnnnnnndddddddd newww.

**Comment by Pluginsel** [comment]
Lol, liquidbounce Did you code it?

**Comment by Spazzinq** [comment]
#3 Is AAC 3.0.5 
I'm not sure if that makes a difference just sayin

**Comment by Janmm14** [comment]
longjump is flaggy and not really far.
client updaze about point 2 got released.
