### ISSUE TITLE
EntityDamageByEntityEvent Error

### ISSUE THREAD

**Issue by Mxngo** [konsolas/AAC-Issues#517]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Seen this in console.

We can't read your thoughts.

Error:
* https://pastebin.com/ZV18KAwR

### Core information
**Server version**: 1.11

**AAC version**:  3.1.0-B1

**ProtocolLib version**: newest

**Plugin list**: Plugins (58): AdvancedLogin, CustomOreGen, PlaceholderAPI, PlugMan, ChatReaction, OldCombatMechanics, DeluxeTags, AutoRestart, WorldEdit, ClearLag, ChatControl, ArmorEquipEvent, BuycraftX, MessageAnnouncer, Votifier, ProtocolLib, GuiRedeemMCMMO, eZProtector, PermissionsEx, FeatherBoard, mcMMO, ServerListPlus, Vault, ProtocolSupport, CustomCommands, QAPlugin, WorldGuard, AAC, ASkyBlock, ChatItem, PlayerVaults, Essentials, AnimatedNames, LiteBans, SilkSpawners, Multiverse-Core, DeluxeChat, Citizens, CustomGUI, EssentialsChat, AuctionGUIPlus, SuperVanish, StackMob, ChestShop, NoFlyZone, HolographicDisplays, CoinFlip, CommandNPC, EssentialsSpawn, PvPManager, TitleManager, ShopGUIPlus, CrazyEnchantments, CrazyEnvoy, ProVotes, LeaderHeads, ProQuests, SpecializedCrates

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: none

**ProtocolSupport version**: yes

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Rqcco** [comment]
Perhaps one of your plugins are conflicting with AAC?

**Comment by Janmm14** [comment]
On the first glance this looks not like a plugin conflict.
On the second look it could be one theoretically.

**Comment by konsolas** [comment]
Going to close because this because modifications to the hitbox check mean that the method causing this error is no longer called.
