### ISSUE TITLE
Fly FP 

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#518]
The fly FP isn't that important since it doesn't seem to go above VL35 but i figured i should post it anyway.

Video: https://www.youtube.com/watch?v=CB_vqJDdJWQ&feature=youtu.be

Core information

Server version: TacoSpigot 1.8 (Bug persists on either 1.7 client or 1.8 client)
AAC version: 3.1.0b1
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/79111c31964e04b1631b0b36510e12ef

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/1a3e07fc5194de5dfeb3ffdd9684457c

**Comment by Janmm14** [comment]
I tested CheckerClimb in the LiquidBounce client some hours ago and I couldn't get it working because the phase check flagged me.

**Comment by SnakeDaoust1232** [comment]
Yep. Sorry about that. I forgot I had the phase check disabled.

**Comment by SnakeDaoust1232** [comment]
This is hella annoying. Still only gets up to under 50VL but it just spams verbose.

**Comment by SnakeDaoust1232** [comment]
In the most recent update 3.1.5, this has double in VL level. Getting over 100 at points.

**Comment by SnakeDaoust1232** [comment]
@konsolas If this was accounted for, it would prevent a lot of verbose/log spam.

**Comment by CeIebrimbor** [comment]
I believe this is no longer valid due to recommended min_vl and how infrequently it occurs. And it being 90% harmless when it does?

Request reopen if you feel as though this is definitely a bug plaguing players to a point of great annoyance.
