### ISSUE TITLE
[Feature] AAC AuraCheck

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#52]
**The command:** /aac auracheck [player]

**What it is:** This command would be a way to manually spawn 5 NPC's around a specific player. Once the command is typed into chat it would then spawn NPC's around the player 3 times, every 10 seconds for 30 seconds. Once it's done it would message the player that ran the command the outcome of it, something like..

**Test # 1:**
[Player] has hit 3/5 NPC's.

**Test # 2:** 
[Player] has hit 4/5 NPC's.

**Test # 3:**
[Player] has hit 4/5 NPC's.

The [Player] has a 73.3333333333% chance of using Aura.

**Comment by CeIebrimbor** [comment]
I think AAC v3 is 100% doing away with NPCs.

**Comment by konsolas** [comment]
This won't be very useful.

**Comment by Janmm14** [comment]
Already exists as a separate plugin called AntiAura with 6 npc's https://github.com/maciekmm/AntiAura
