### ISSUE TITLE
3.1.1 Speed false positive

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#521]
### Issue description

When I set a player's speed by player.setWalkSpeed(0.24) and give them jump boost level 1 effect, they get dragged back for speed hacking when they jump
This issue occurred since 3.1.0
Video: https://youtu.be/VzQ8v69KgYU

### Core information
**Server version**: paperspigot 1.11.2 build 1076

**AAC version**: 3.1.1

**ProtocolLib version**: build 353

### Special environment information

**ProtocolSupport version**: build 38

**Comment by MClausz** [comment]
Still not fixed in 3.1.3?
Please fix ASAP! This is urgent for me!

**Comment by MClausz** [comment]
Still not fixed in 3.1.4
...PLEASE?

**Comment by konsolas** [comment]
hm, I'll have to write a custom thing to test this apparently

**Comment by konsolas** [comment]
setWalkSpeed(2.4) is much faster than what you have in the video. Can I see the actual code used?

**Comment by konsolas** [comment]
@MClausz

**Comment by MClausz** [comment]
My bad... it was 0.24
https://pastebin.com/TcAgMFu0
I can also reproduce it by using Essentials's speed command and do a bunny hop

**Comment by MedicOP** [comment]
What is your item_scalar set to?

https://github.com/konsolas/AAC-Issues/issues/531

**Comment by MClausz** [comment]
item_scalar is commented out in my AAC's config file

**Comment by konsolas** [comment]
Fixed in 3.1.4-b2
