### ISSUE TITLE
Bypass Sprint AllDirection Working İce-SoulSand Etc

### ISSUE THREAD

**Issue by Teals53** [konsolas/AAC-Issues#526]
Test Server test.ccbluex.tk
Test Client LiquidBounce

**Comment by Photon-GitHub** [comment]
Test bypasses / bugs on the official test server.

**Comment by Teals53** [comment]
But AAC Offical Test Server İs Closed I Dont Test İt ?

**Comment by Janmm14** [comment]
Tested on local test server, not reproducible, I get setbacked for speed.

**Comment by Teals53** [comment]
Could you prove ?

**Comment by Janmm14** [comment]
I do not need to prove that. Also there is a bypass existing where the client will simply fake the direction you are looking to.
I asked konsolas already to start the official test server again.
