### ISSUE TITLE
Anti-Cactus Working

### ISSUE THREAD

**Issue by Teals53** [konsolas/AAC-Issues#527]
Test Server test.ccbluex.tk
Test Client LiquidBounce

**Comment by Photon-GitHub** [comment]
Test bypasses / bugs on the official test server.

**Comment by Teals53** [comment]
But AAC Offical Test Server İs Closed I Dont Test İt ?

**Comment by Janmm14** [comment]
Test it on your local server containing a valid copy of AAC or wait until the official test server at aac3.kons.co is reachable again.

**Comment by Teals53** [comment]
I Dont Have AAC But test.ccbluex.tk Have A AAC And İts A TestServer Dont Fake ?

**Comment by Janmm14** [comment]
Anti-Cactus is pretty much undetectable if you are not standing above a cactus anyway.

To get you a little satisfied I will try it out on my local test server

**Comment by Teals53** [comment]
But NCP Blocked ?

**Comment by Janmm14** [comment]
Well then why don't use NCP?

Additionally you should read what I am writing @Teals53

**Comment by Teals53** [comment]
I do not understand why you are so stubborn ?

**Comment by Teals53** [comment]
A little bona fide approach

**Comment by Teals53** [comment]
People say that if a body says something, they have a knowing
