### ISSUE TITLE
AAC Speed and Fly FP | Urgent

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#529]
Info: 
- When hitting someone near a block, it false bans for FLY. 
- *I think* The sudden change from speed 1/2 to speed 0 false bans for speed. Or, it could be some other bug that has to do with the usage of items.. kinda like the quick switching items bugs that still exists. 

Video: https://www.youtube.com/watch?v=d1Jar82l9ZE&feature=youtu.be

Speed Config: https://hastebin.com/hetinowohu.bash

Core information

Server version: TacoSpigot 1.8 (Bug persists on either 1.7 client or 1.8 client)
AAC version: 3.1.2
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/c17cf3dda13667a2bd5e5bb29c1b8271

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/1a3e07fc5194de5dfeb3ffdd9684457c

**Comment by SkillzGamingYT** [comment]
"When hitting someone near a block, it false bans for FLY." wait did kons fix that? https://github.com/konsolas/AAC-Issues/issues/480

**Comment by SnakeDaoust1232** [comment]
I have confirmed that if you have a speed potion, and if you are sprinting when that speed potion runs out... It false flags for speed. I've seen it go all the way up to 225 with someone that has high ms to the server.

**Comment by Janmm14** [comment]
Maybe you need to create more lenient configurations for high-ping-players about the potion stuff,

The fly issues when getting hit at a block should just appear if you are not moving your head more than 10 degree per tick while reaching the ground again. If that's the case I know where the issue is. If that's not the case, there's some other issue which needs to get adressed.

**Comment by SnakeDaoust1232** [comment]
If you look at my other post you see that the speed FP actually is a big issue. As well, this never used to be a thing, so it's prolly just some accounting missing in the code. Their is a certain point where configuration isn't a feasible option. Most FPs are in the code, not the configuration.

**Comment by Janmm14** [comment]
The problem about speed potions is that sine 3.1.0 the speed check is a lot more accurate and that is probably the root cause of the speed potion lag false positive.

**Comment by SnakeDaoust1232** [comment]
Regardless, I don't think it will be that hard to account for the one tick transition from speed 1/2 to speed 0.
