### ISSUE TITLE
Another Fly FP

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#530]
Info: 
- Spamming blocks in places that don't allow building (presumably over a certain height) give FPs for FLY

Video: https://www.youtube.com/watch?v=KL40pJIoaLg&feature=youtu.be

Fly Config: https://hastebin.com/vapohehoki.bash

Core information

Server version: TacoSpigot 1.8 (Bug persists on either 1.7 client or 1.8 client)
AAC version: 3.1.2
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/c17cf3dda13667a2bd5e5bb29c1b8271

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/1a3e07fc5194de5dfeb3ffdd9684457c

**Comment by Janmm14** [comment]
Its known due to serverside the block never existed, since the placement is cancelled. A player could theoretically get above a 2-block-wall where he normally should not be able to.

Maybe konsolas will add a config option to account for that however.

**Comment by konsolas** [comment]
This is "block glitching".

It's an illegal movement, and can in fact be used by hacked clients to fly/speed on anticheats which try to compensate for it. For example, block glitching can be used to go over a 2 high wall by spamming a block below you and jumping on it. Hacked clients can reliably get over a 2 block wall by pretending to do this.

AAC gets around this issue by treating block glitching as any other hack - the player is set back to their ground location and cannot get over the wall.

**Comment by SnakeDaoust1232** [comment]
Okay. That makes sense. Thanks
