### ISSUE TITLE
Speed Bug Explained | BHOP Speed bypass (LiquidBounceB22) | Killaura talk

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#532]
Info: 
- LiquidBounceb22's AAC Speed Bypass works
- Going from speed 1 or 2 to speed 0 causes false positives.

Video: https://www.youtube.com/watch?v=_6_KrvZD5xE&feature=youtu.be

Fly Config: https://hastebin.com/vapohehoki.bash
Speed Config: https://hastebin.com/hetinowohu.bash

Core information

Server version: TacoSpigot 1.8 (Bug persists on either 1.7 client or 1.8 client)
AAC version: 3.1.2
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/79111c31964e04b1631b0b36510e12ef

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/1a3e07fc5194de5dfeb3ffdd9684457c

**Comment by SnakeDaoust1232** [comment]
Video is processing, will be up very shortly.

**Comment by OWERLORD01** [comment]
> Info:
>
>LiquidBounceb22's AAC Speed Bypass works
Going from speed 1 or 2 to speed 0 causes false positives.
Video: https://www.youtube.com/watch?v=_6_KrvZD5xE&feature=youtu.be
>
>Fly Config: https://hastebin.com/vapohehoki.bash
Speed Config: https://hastebin.com/hetinowohu.bash
>
>Core information
>
>Server version: TacoSpigot 1.8 (Bug persists on either 1.7 client or 1.8 client)
AAC version: 3.1.2
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/79111c31964e04b1631b0b36510e12ef
>
>Special environment information
>
>ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/1a3e07fc5194de5dfeb3ffdd9684457c

I patched it on my server, its bypassing but it gets detected in a few seconds.... I hop @konsolas will patch it

**Comment by Janmm14** [comment]
When I checked the liquidbounce b22 update I tested the aac3bhop and it was as fast as a legit player.

**Comment by SnakeDaoust1232** [comment]
It bypasses for an unlimited time on my server. And Jan, if you drink a speed pot with it, it's much faster.

**Comment by OWERLORD01** [comment]
> When I checked the liquidbounce b22 update I tested the aac3bhop and it was as fast as a legit player.
>
>@OWERLORD01 I don't think you patched a speed which is not really faster than a legit player (like i could not see any difference in ~40 block test race

Its a little bit faster :P Look
https://hastebin.com/oramijerah.bash

**Comment by konsolas** [comment]
@SnakeDaoust1232 many speeds simply use FOV modifications to give the feeling that a speed is in effect, whilst, in fact, the speed improvement is negligible.

AAC's 1.8 test server has a race system with a redstone system to compare a speed hack with a legitimate player's speed over some distance. LiquidBounce's bhop did not achieve a noticable improvement in this test. Similarly with speed potions, the improvement is likely to be negligible (although I haven't tested this yet).

**Comment by SnakeDaoust1232** [comment]
Okay. Let us know when you test it out because now I'm curious. It wouldn't be the first time clients "lie" about being able to bypass.

**Comment by SnakeDaoust1232** [comment]
I did my own little test and it doesn't go any faster than someone with speed 2. Why release a speed hack, that doesn't give you an advantage? xD

**Comment by Janmm14** [comment]
@SnakeDaoust1232 pretending to have a speed bypass
