### ISSUE TITLE
Anti-Knockback shield bug

### ISSUE THREAD

**Issue by thedarthonian** [konsolas/AAC-Issues#535]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.

We can't read your thoughts.

Please include details like:
* AAC logs / Full console error
* Video of the bug / bypass, best with verbose chat output
* The ingame name of the involved players

### Core information
**Server version**: 1.11.2

**AAC version**: 3.1.2

**ProtocolLib version**: 4.2.0

**Plugin list**: http://prntscr.com/erhf9y

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: http://prntscr.com/erhfft

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here: 

Using a shield causes false anti-knockback checks.

**Comment by Photon-GitHub** [comment]
No check is false in AAC and Knockback is no longer supported. Use velocity instead.
Moreover your report is lacking information.
