### ISSUE TITLE
AAC error on move

### ISSUE THREAD

**Issue by tade159SK** [konsolas/AAC-Issues#536]
### Core information
**Server version**: Spigot 1.8.8 latest

**AAC version**: 3.1.2

**ProtocolLib version**: 4.2.0 (build 341)

**Plugin list**: Custom Plugins

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: latest

**ProtocolSupport version**: none
**ViaBackwards version**: none

**BungeeCord plugins**: Custom Plugins

### Error log:
https://pastebin.com/0EfFcqv1

**Comment by konsolas** [comment]
File corruption. Redownload please.
