### ISSUE TITLE
Nullpointer

### ISSUE THREAD

**Issue by SwiftSwamp** [konsolas/AAC-Issues#539]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.

We can't read your thoughts.

Please include details like:
* AAC logs / Full console error
* Video of the bug / bypass, best with verbose chat output
* The ingame name of the involved players

### Core information
**Server version**: insert
PaperSpigot 1.8 * 1.11

**AAC version**: insert
3.1.2

**ProtocolLib version**: insert
4.2.0 for PaperSpigot 1.8 then the latest for 1.11

**Plugin list**: insert

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: insert
v1.0.4 on the 1.8 server.

**ProtocolSupport version**: insert
Build 353 on the 1.11 server.

**ViaBackwards version**: insert
N/A

**BungeeCord plugins**: insert
Latest build as of today.

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here: 

ERROR: https://pastebin.com/WMQXJKtw https://pastebin.com/sxSCyBFF

**Comment by konsolas** [comment]
#554
