### ISSUE TITLE
some startup problems apparantly

### ISSUE THREAD

**Issue by Felix5566** [konsolas/AAC-Issues#541]
The Check to the AAC version is a mistake: https://hastebin.com/ikemelipif.css
I don't can start a Server with the newest AAC version. Please FIX IT!!!
FAST!!!

AAC Version: 3.1.2
MC Version: 1.8.8

**Comment by Janmm14** [comment]
Please show your full startup log.

**Comment by Felix5566** [comment]
https://hastebin.com/akayuyuyed.md

**Comment by konsolas** [comment]
That's version 3.1.1...

**Comment by konsolas** [comment]
Closing due to insufficient information.
