### ISSUE TITLE
AAC KillAura Bypass (AlphaCentauri)

### ISSUE THREAD

**Issue by Pluginsel** [konsolas/AAC-Issues#542]
Hello konsolas.
AlphaCentauri client is bypassing AAC killaura check.
Please test and fix!
Thank You.
NOTE: İs not tested, but some people say they bypassed it.
Client Version: 1.8
AAC Version: 3.1.2

**Comment by Photon-GitHub** [comment]
Not tested = unverified.
Please test the bypasses before putting them here.
You do not even provide a video...

**Comment by Pluginsel** [comment]
https://www.youtube.com/watch?v=0_RAnNCz1uA

**Comment by konsolas** [comment]
Closed due to insufficient information - no logs, etc.
