### ISSUE TITLE
Speed FP *Very Confused* | Video

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#543]
Info: 
- It looks like im just running around and it bans me. I think it may have something to do with slabs.

Video: https://www.youtube.com/watch?v=PmjIYSOLVBs&feature=youtu.be

Speed Config: https://hastebin.com/parogasapo.bash

Log: https://hastebin.com/apifenoqef.hs

Core information

Server version: Paperspigot 1.8.8
AAC version: 3.1.3
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/62230b456a22877a8803245f9132ccee

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/b5d2b4e81fd8ee3a44b7472e9caf939d

**Comment by Photon-GitHub** [comment]
I am not sure if AAC supports your setup to allow 1.7 clients join the server. Moreover did some people report problems with TacoSpigot. I am pretty sure that this is caused by your setup and not by AAC.

**Comment by SnakeDaoust1232** [comment]
I forgot to update the desc. On my KitPVP server I don't use tacospigot. As well, the bug was originally found on 1.8. I'll make another video and post It here on a 1.8 client.

**Comment by SnakeDaoust1232** [comment]
New Video on 1.8 client: https://www.youtube.com/watch?v=7WSn7r6YlP4&feature=youtu.be

**Comment by SnakeDaoust1232** [comment]
Another video: https://www.youtube.com/watch?v=Aihr9N65viw&feature=youtu.be

**Comment by SkillzGamingYT** [comment]
I **recommend** you to create a new issues this issues already closed and flagged as invalid. I **think** no one will care...

**Comment by SnakeDaoust1232** [comment]
It's not closed. It would have the label "closed"

**Comment by SkillzGamingYT** [comment]
I found that bug too try to remove all .dat in"playerdata" in your world
It's map speed bug...
https://www.youtube.com/watch?v=jSgpZBZ9fCs&feature=youtu.be << same?

**Comment by SnakeDaoust1232** [comment]
It's not the same. I don't want to sound mean but you sound uneducated on this github. You must be new. This is a bug with running up Slabs. In your video it could be related, but you are going down slabs.

**Comment by SnakeDaoust1232** [comment]
Removing the playerdata will have 0 effect on any of the anticheat checks.

**Comment by SkillzGamingYT** [comment]
instead of "Trying it" you just "fuck around" with people trying to help you....
And playerdata might been CORRUPTED by MCedit or Worldedit or when stopping, so player gain speed without a speed potion.

**Comment by SkillzGamingYT** [comment]
also i'm trying to help you, just try it before saying that someone is "uneducated" If it doesn't I'm sorry for wasting 5 min of your life

**Comment by SnakeDaoust1232** [comment]
I've been running serves for 5 years. That's is my justification for telling you it's not going to work. With that being said, I will do this tommorow in a video just so I can make you feel some type of way.

**Comment by SnakeDaoust1232** [comment]
My bug is different than yours. But they might be related. I tested the playerdata although I know that it has nothing to do with it because if i had "speed" effects of which I didn't realize, I would notice the change in FOV instantly.

**Comment by SkillzGamingYT** [comment]
No, The map will cause player speed packet to change, you will not see changes in your FOV.

**Comment by Janmm14** [comment]
This issue is not flagged invalid/is still open ?!
