### ISSUE TITLE
Could not pass event PlayerMoveEvent to AAC v3.1.3

### ISSUE THREAD

**Issue by AnthonyGriffith** [konsolas/AAC-Issues#544]
**Server version:** CraftBukkit version git-Spigot-625bc00-186c351 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**AAC version**: 3.1.3

**ProtocolLib version**: 4.2.0

**Plugin list**: AsyncWorldEditInjector, CoreProtect, WorldEdit, PlayerMention, ClearLag, PlugMan, PlayTime, ProtocolLib, WorldGuard, AsyncWorldEdit, PermissionsEx, EpicWorldGenerator, mcMMO, TreeFeller, Vault, MassiveCore, Essentials, HolographicDisplays, Citizens, EssentialsKitManager, CrazyAuctions, EssentialsChat, EssentialsSpawn, CratesPlus, Factions, FactionChat, OpenInv, AAC, Sentinel

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Reproducing the issue**:
According to my players this occurs when simply walking around and also running and jumping at the same time. 

**Actual Error**: https://hastebin.com/ecahoderah.sql
Note: The Error is spammed so much in the console when it occurs.

**Comment by konsolas** [comment]
Will suppress this.
