### ISSUE TITLE
Doesn't work, doesn't do anything

### ISSUE THREAD

**Issue by Sollembum78** [konsolas/AAC-Issues#545]
I tried several previous builds that did nothing but prevent players from hiting each other, in any conditions. Now I try latest build, with latest spigot, latest everything, and almost no plugins, that can interfere in process of catching cheaters.

What I get? I stand there with two instances of Wurst, hitting my other self for 5 minutes straight. Ok, maybe some YesCheat+ tweaks mask what's going on. I turn every tweak of wurst off, turn on criticals, simple and obvious classic killaura, multiaura, with no radius or whatever, and plugin does nothing. According to log it does detect something.. But no kick, no warn, nothing in console to let me know about cheaters. Is it something I'm missing? Default config for AAC, no changes at all. It's not enough?

Full server log
https://pastebin.com/skH4mSR7
AAC log
https://pastebin.com/Dawju7JK
AAC config
https://pastebin.com/PWgxkqZT

Version of server: git-Spigot-d276ab1-1f6c04c (MC: 1.11.2)

Plugins:
FastAsyncWorldEdit, PermissionsEx, hub, WorldBorder, mcMMO, Vault, SaneEconomy, HideStream, BlockedBlocks, ProtocolLib, AAC, WorldEdit, MysqlPlayerDataBridge, Essentials, Herochat, EssentialsAntiBuild, mcMMOAction, HolographicDisplays, EssentialsSpawn, WorldGuard, EssentialsProtect

BungeeCord plugins: BungeeAuthmeBridge, BungeeResourcepacks, CommandSyncServer, SkelletProxy, SkinsRestorer, Yamler-Bungee.

**Comment by Photon-GitHub** [comment]
You do not have the default config, otherwise you would get warnings. Did you think of bypass permissions / op status ? You maybe want to enable verbose.

**Comment by Sollembum78** [comment]
I had no AAC folder in my plugins when I started the server, config was generated by plugin, isn't is the default one? No warning in game coz both characters were just players, but nothing in console too. And, I'm fine with no warnings, but check out that logs, it goes to 189 vl but no kick or anything?

**Comment by Sollembum78** [comment]
If you insist, I can record the WHOLE PROCESS of me doing this, creating server from nothing, having no folder for AAC, joining with two characters, using cheats. Would that prove my point?

**Comment by Sollembum78** [comment]
Few lines from logs provided:

Создаю пустой конфигурационный файл: /home/desktop/minecraft/res1/plugins/Essentials/userdata/c0179ce9-8006-3d0a-9d3e-841218fa6867.yml
Создаю пустой конфигурационный файл: /home/desktop/minecraft/res1/plugins/Essentials/userdata/989e0109-7c76-3561-900e-8bc2efef1fac.yml
'c0179ce9-8006-3d0a-9d3e-841218fa6867/Mass' is a member of:
default (rank 8 @ default)
Mass's permissions: []
Mass's options: []
name = "Mass"
