### ISSUE TITLE
Errors - AAC-3.1.2 - UHC-reloaded TreeFaller

### ISSUE THREAD

**Issue by LazosPlaying** [konsolas/AAC-Issues#548]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Errors while breaking blocks using "tree faller" in [UHCreloaded](https://www.spigotmc.org/resources/✦ultra-hardcore-reloaded✦-the-best-uhc-uhcrun-of-spigot-new-optimized-chunk-loader.2900/)
After that server crashes (overload)

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypass.
Errors

We can't read your thoughts.

Please include details like:
* AAC logs / Full console error
* Video of the bug / bypass, best with verbose chat output
* The ingame name of the involved players
No AAC logs

Error paste: https://hastebin.com/tunedowoci.vbs

### Core information
**Server version**: 1.9.4

**AAC version**: 3.1.3

**ProtocolLib version**: 4.2.0

**Plugin list**: 
AAC, aacanticrash, BungeeTablistBukkitBridge, DeluxeChat
FastAsyncWE, FastCraftplus, ipwhitelist, LiteBans, MVDWpapi, MyCommand, NCP, PEX, PlaceholderApi, ProtocolLib, PwnFilter, ReporterGUI, SpigotBridge, TitleManager, UEAntiTab, UHC-reloaded,
Vault, ViaVersion, WorldBoarder, WorldEdit, WorldGuard

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.0.4

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: 
AntiBotDeluxeEX, BungeeAlias, bungeeAuthmeBridge, BungeeMSG, BungeePerms, BungeeserverManager, BungeeTablistPlus, FastLogin, MoveMeNow, NuVotifier, PartyAndFriends + (8 PAF modules), ServerListPlus, SkinsRestorer, wcnp (cmd blocker)

### Reporting issues encountered on the test server has these additional rules:
* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here:  9/4/2017; 14:29 (+1)

**Comment by Photon-GitHub** [comment]
This has nothing to do with AAC.

**Comment by LazosPlaying** [comment]
Sorry, pasted wrong error.
There was an error with AAC.
Here is the URL
https://hastebin.com/zedosixowu.vbs
