### ISSUE TITLE
UHC reloaded - (correct report, URL)

### ISSUE THREAD

**Issue by LazosPlaying** [konsolas/AAC-Issues#549]
### Issue description

Errors while breaking blocks using "tree faller" in [UHCreloaded](https://www.spigotmc.org/resources/✦ultra-hardcore-reloaded✦-the-best-uhc-uhcrun-of-spigot-new-optimized-chunk-loader.2900/)
After that server crashes (overload)

Errors

No AAC logs
Error paste: https://hastebin.com/rifuvelodo.vbs

### Core information

**Server version**: 1.9.4

**AAC version**: 3.1.3

**ProtocolLib version**: 4.2.0

**Plugin list**:
AAC, aacanticrash, BungeeTablistBukkitBridge, DeluxeChat
FastAsyncWE, FastCraftplus, ipwhitelist, LiteBans, MVDWpapi, MyCommand, NCP, PEX, PlaceholderApi, ProtocolLib, PwnFilter, ReporterGUI, SpigotBridge, TitleManager, UEAntiTab, UHC-reloaded,
Vault, ViaVersion, WorldBoarder, WorldEdit, WorldGuard

### Special environment information

Insert 'none' if you don't use it

**ViaVersion version**: 1.0.4

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**:
AntiBotDeluxeEX, BungeeAlias, bungeeAuthmeBridge, BungeeMSG, BungeePerms, BungeeserverManager, BungeeTablistPlus, FastLogin, MoveMeNow, NuVotifier, PartyAndFriends + (8 PAF modules), ServerListPlus, SkinsRestorer, wcnp (cmd blocker)

9/4/2017; 14:29 (+1)

**Comment by Janmm14** [comment]
Did you tested removing WorldGuard or AAC? Is this reproducible or random?

**Comment by konsolas** [comment]
stack trace is truncated.

**Comment by LazosPlaying** [comment]
@konsolas Sorry for not responding to the thread, if you can, please open it again.
@Janmm14 Yes i did try to remove both;
The issue occures ONLY when there is AAC plugin and "tree faller" function (in HUCreloaded) enabled

Regards.

**Comment by Janmm14** [comment]
@LazosPlaying
The stack trace is still truncated. To get a non-truncated stack trace, look into logs close to server start (java does remove important information if an exception is thrown often).

**Comment by LazosPlaying** [comment]
There are no issues at all when starting up.
I already checked the logs 😉

I will test with the latest AAC (at the moment latest) when i will have enough time.
For now i have other work to do...

Stay tuned for that, should be in next week, if not, please bump this thread (if you will remember)
Thank you 😃 

Regards.

**Comment by CeIebrimbor** [comment]
1 month later. Request reopen if still valid.
