### ISSUE TITLE
v3 Fastplace (ImpossibleInteract) when spam click

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#55]
https://vimeo.com/188452898

VL to band(cancel) mitigate this?

Edit: Sorry for perspective...I was in Survival.

**Comment by konsolas** [comment]
added: impossibleinteract.cancel_vl

**Comment by Janmm14** [comment]
Could you add a list of blocks which ignore the cancel_vl? For games like Bedwars or Cores where destroying specific blocks is the game target?
