### ISSUE TITLE
Velocity check does not perceive Entity.setVelocity from other plugins (using elytra)

### ISSUE THREAD

**Issue by wasder** [konsolas/AAC-Issues#550]
We have a plugin for boost by fireworks while flying with an elytra on a 1.9.4 server. It uses Entity.setVelocity. Players are kicked for using it.
```
double yaw = Math.toRadians((double)player.getLocation().getYaw());
                double pitch = Math.toRadians((double)player.getLocation().getPitch());
                double x = -Math.sin(yaw) * Math.cos(pitch);
                double y = -Math.sin(pitch);
                double z = Math.cos(yaw) * Math.cos(pitch);
                Vector velocity = player.getVelocity();
                player.setVelocity(velocity.add(new Vector(x, y, z)));
```

https://www.dropbox.com/s/fih10sg749bwv6u/2017-04-09_18-12-55.mp4
https://pastebin.com/WaAvwM7N
AAC version: 3.1.3
Protocollib: 4.2.0
Server version:
![](http://i.imgur.com/8qpqsFy.png)
Using Celebrimbor's  соnfig

**Comment by konsolas** [comment]
Example line: 
```
vasya failed Velocity: ignored server velocity (0.331,-0.187,-2.129/0.188, expected 0.504,-0.128,-2.175/0.100) [ping:68 tps:19.59] VL:8 [ping:68 tps:19.608]
```
Problem here is that the velocity registered is higher than the actual velocity used by the client.
