### ISSUE TITLE
Fly, Speed, Phase false positives, skyrocket when moving at max build height

### ISSUE THREAD

**Issue by MedicOP** [konsolas/AAC-Issues#552]
Very easy to reproduce, just walk around on y: 256. VL will skyrocket

AAC version: 3.1.2
Spigot: 1.8.8
ViaVersion: 1.0.3
ProtocolLib: 4.2.0

**Comment by guerryer** [comment]
Like that ? https://youtu.be/8lJCs1NzM3w

**Comment by MedicOP** [comment]
Yes
