### ISSUE TITLE
Velocity/Fly issues with Elytra

### ISSUE THREAD

**Issue by MatheweB** [konsolas/AAC-Issues#557]
There is a false positive whenever someone on the server without AAC bypass permissions flies on an elytra. There are several console errors, and I have fixed the problem temporarily by disabling the velocity check, as well turning all the T/F options in the fly check to False. Before turning off velocity, I was receiving WARN: player moved wrongly.

We can't read your thoughts.

Here are the logs when user Dogbutter999 tries to fly:
12.04 03:30:18 [Server] WARN java.lang.IllegalArgumentException: java.lang.ClassCastException@3d60279
12.04 03:30:18 [Server] WARN at sun.reflect.GeneratedMethodAccessor278.invoke(Unknown Source)
12.04 03:30:18 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12.04 03:30:18 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
12.04 03:30:18 [Server] WARN at me.konsolas.aac.bv.a(bv.java:225)
12.04 03:30:18 [Server] WARN at me.konsolas.aac.cJ.a(cJ.java:112)
12.04 03:30:18 [Server] WARN at sun.reflect.GeneratedMethodAccessor427.invoke(Unknown Source)
12.04 03:30:18 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12.04 03:30:18 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
12.04 03:30:18 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
12.04 03:30:18 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
12.04 03:30:18 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
12.04 03:30:18 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
12.04 03:30:18 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234)
12.04 03:30:18 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201)
12.04 03:30:18 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:197)
12.04 03:30:18 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:950)
12.04 03:30:18 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
12.04 03:30:18 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
12.04 03:30:18 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
12.04 03:30:18 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
12.04 03:30:18 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12.04 03:30:18 [Server] WARN at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
12.04 03:30:18 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
12.04 03:30:18 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
12.04 03:30:18 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
12.04 03:30:18 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
12.04 03:30:18 [Server] WARN at java.lang.Thread.run(Thread.java:745)

### Core information
**Server version**: Spigot version 1.11.2

**AAC version**: 3.1.3

**ProtocolLib version**: 4.2.0

**Comment by konsolas** [comment]
#550
