### ISSUE TITLE
Using tons of CPU (3.1.4) 

### ISSUE THREAD

**Issue by bob7l** [konsolas/AAC-Issues#560]
current version (3.1.4) is using a MASSIVE amount of CPU, approximately 4x the amount of resources of the prior releases. 

> AAC v3.1.4 Total: 5.174 s Pct: 22.22%
   Pct Total    Pct Tick       Total          Avg     PerTick         Count        Event
       8.02%       8.52%      1.87 s         4.26 ms      60          26.2k        bP::a(PlayerMoveEvent)
       7.03%       7.46%      1.64 s         3.73 ms      60          26.2k        bA::a(PlayerMoveEvent)
       6.36%       6.75%      1.48 s         3.38 ms      60          26.2k        bc::a(PlayerMoveEvent)
       0.35%       0.37%      0.08 s         0.18 ms      60          26.2k        bW::a(PlayerMoveEvent)`

I only have speed, jesus, and velocity enabled for the movement checks. Fly and the rest are disabled.

Here is NoCheatPlus (For comparison): 
`NoCheatPlus v3.15.0-SNAPSHOT-sMD5NET-b1063Total: 1.098 s Pct: 3.02%`

It's gotten to the point I can't even keep a stable 20 TPS anymore. I really hope this is high on the priority list because it's killing my servers performance.

Disabling AAC's heuristics check reduced the Per-tick total to only 6%. So I'm assuming the new changes to the heuristics are just extremely demanding now. 

### Core information
**Server version**: 1.8.8 Spigot

**AAC version**: 3.1.4

**ProtocolLib version**: ALWAYS LATEST

**Plugin list**: No others

### Special environment information
None

**Comment by konsolas** [comment]
New heuristics have ended up with several more atan2() calls

**Comment by konsolas** [comment]
I'm going to make as much of it async as possible.

**Comment by konsolas** [comment]
Actually, never mind. Apparently I parse integers in the player move event. This will be hotfixed.

**Comment by konsolas** [comment]
Fixed in 3.1.4-b1
