### ISSUE TITLE
Stack Trace

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#561]
Stack Trace: https://gyazo.com/439aae7de2a223c74b7cf5abf86686f5

Core information

Server version: Paperspigot 1.8.8
AAC version: 3.1.4b1
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/62230b456a22877a8803245f9132ccee

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/b5d2b4e81fd8ee3a44b7472e9caf939d

**Comment by MedicOP** [comment]
Probably same as #492
