### ISSUE TITLE
AAC KillAura Bypass

### ISSUE THREAD

**Issue by Pluginsel** [konsolas/AAC-Issues#562]
AAC KillAura Bypass
Tested on GommeHD server. (SurvivalGames)

## Client info

LiquidBounce V23.2
Minecraft Version: 1.8

## KillAura settings

MaxCPS = 10
MinCPS = 4
Range = 2.6
Priority = Health
TargetMode = Switch

ScreeShot of KillAura settings : http://prnt.sc/ew0scb
Client download link : https://mega.nz/#!yc8x3IqI!imnr8Vs_7dz7m8XiRcbfjVClxX2IsM0Z70uEhQC6tWQ

## AAC
AAC Version: 3.1.4

## GommeHD Server Info

BungeeCord : Yes
ViaVersion: Yes

**Comment by Eyremba** [comment]
GommeHD is using fucked up settings of AAC because their only target is to fully prevent false-bans.

That's why I would not call it a real bypass...

**Comment by konsolas** [comment]
Range=2.6, not really a killaura

**Comment by Pluginsel** [comment]
4.6 is really a killaura ?
