### ISSUE TITLE
HitBox Bug/FP

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#564]
Info: 
- It seems as if the hitbox is "lagging" behind the player causing inaccurate readings. Maybe the plugin should compensate for that. Its ALOT worse the worse your ping gets.
- I noticed that even with me setting the max reach at 3.8 and my leniency at 1.2, its still flagging for 3.5-3.7 reach.
- This effects the kill-aura check as well. The way the hitboxes lag behind the players. As well, with the killaura check, the higher your MS, the more likely you'll be false flagged.

Video: https://www.youtube.com/watch?v=w4kmjPVo77k&feature=youtu.be

Hitbox Config: https://hastebin.com/baruverahi.bash

Core information

Server version: Paperspigot 1.8.8
AAC version: 3.1.4b1
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/62230b456a22877a8803245f9132ccee

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/b5d2b4e81fd8ee3a44b7472e9caf939d

**Comment by SnakeDaoust1232** [comment]
Video added.

**Comment by SnakeDaoust1232** [comment]
The hit at 4:02 shows what im talking about with the killaura check.

**Comment by SnakeDaoust1232** [comment]
@konsolas This is related to the killaura check and the reach check.

Video: https://www.youtube.com/watch?v=CTsiz80fp-Q&feature=youtu.be

**Comment by SnakeDaoust1232** [comment]
@konsolas I feel like this should be a priority. I've had my hitbox check essentially disabled because of this ever since.

**Comment by CeIebrimbor** [comment]
Agreed...

**Comment by Janmm14** [comment]
the compensation `lenience` is adding is not counted towards the shown reach in verbose output as far as I know

**Comment by CeIebrimbor** [comment]
I my (and many other's) experiences, ping between 1-60 can get to VL 30 in Killaura with your typical spam-click pvp, ping 61-100 can get to 50/60 and the 100+ can get to 60/70. I neuter the KA check and only kick with not ping/TPS condition at VL 80. Even that sometimes proves to be troublesome.

Neuter defined:
min_dist: 2.5
max_diff: 0.14

**Comment by SnakeDaoust1232** [comment]
Yeah my KA is set to min_dist: 5 and max_diff: 10 and people get banned left and right on my server when they arent cheating.

**Comment by CeIebrimbor** [comment]
@SnakeDaoust1232 
I want to maybe say that setting such a high max_diff is problematic... What is that, like looking 10000 degrees off a player? Maybe stick to .30 and see what happens.

**Comment by SnakeDaoust1232** [comment]
@CeIebrimbor Yeah, the only reason i set it to that is because it was really messing with hit detection having it at default and thats what konsolas told me to set it to. Ill try setting it to .30 and let you know how it acts.

**Comment by CeIebrimbor** [comment]
Update @SnakeDaoust1232?

**Comment by SnakeDaoust1232** [comment]
@CeIebrimbor I'm waiting on @konsolas to roll out an update that fixes it. I think he mentioned that he was working on something. Idk though

**Comment by SnakeDaoust1232** [comment]
@konsolas You look into this issue yet? I really would like the hitbox and killaura check to be accurate so i can start using it properly.

**Comment by konsolas** [comment]
Hitbox being rewritten for 3.2.2

**Comment by SnakeDaoust1232** [comment]
@konsolas Will this fix the issue with the killaura check as well. The same "hitbox" stretching issue persists in the killaura check. This issue pertains to the killaura issue: https://github.com/konsolas/AAC-Issues/issues/581

**Comment by SnakeDaoust1232** [comment]
@konsolas I'm excited!
