### ISSUE TITLE
PlayerMoveEvent Exception

### ISSUE THREAD

**Issue by Schuchie** [konsolas/AAC-Issues#565]
### Issue description
I get a nullpointer exception on player movement. 

Log: https://pastebin.com/iPAewMFB

### Core information
**Server version**:  CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT

**AAC version**: 3.1.4

**AACAdditionPro version**: 1.7.2

**ProtocolLib version**: 4.2.1-SNAPSHOT-b346

**Plugin list**: -

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: ViaVersion v1.0.4-SNAPSHOT

**ProtocolSupport version**: -

**ViaBackwards version**: -

**BungeeCord plugins**: -

**Comment by konsolas** [comment]
We have a plugin: de.Zweieiig.Game
Which is firing player move events instead of the server.

**Comment by Schuchie** [comment]
@konsolas Since bypass permission Is true AAC should not care at all

**Comment by CeIebrimbor** [comment]
I want to suggest this is not valid since another plugin is causing the issue? Please request reopen or make a new issue if this evaluation is incorrect.
