### ISSUE TITLE
Velocity Bug

### ISSUE THREAD

**Issue by CodaMacroft** [konsolas/AAC-Issues#566]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.

When attacked by a zombie or any mob that does any sort of damage, I trigger the Velocity check. My first thought was to raise the Threshold and check_length. I did and it did nothing so I raised them more and more until finally I raised them up to very high numbers and then tested. Still, it was reporting false positives and kicking me for Velocity. I hope you can get this fixed as soon as possible. Thanks - Coda

We can't read your thoughts.

Please include details like:
* AAC logs / Full console error: 
[aac_2017-04-13_15-55-49.txt](https://github.com/konsolas/AAC-Issues/files/920993/aac_2017-04-13_15-55-49.txt)
* Video of the bug / bypass, best with verbose chat output: I can not send the video because GitHub will only allow a file size of 10MB and below. I tried multible times to shorten the video but failed. I can email it to you if you would like me to. I don't know you email.
* The ingame name of the involved players: CodaChaos
### Core information
**Server version**: Spigot 1.10.2

**AAC version**: AAC 3.1.4 B-1

**ProtocolLib version**: 4.2.0

**Plugin list**: I am a professional server and prefer to not share my plugin list. If this is 100% required and there is no other way you can fix the bug, then please contact me at colthale123@gmail.com and I will send you a screen shot of my plugin list. 

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.0.4

**ProtocolSupport version**: none

**ViaBackwards version**: 2.0

**BungeeCord plugins**: ViaVersion

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here:

**Comment by Janmm14** [comment]
Temporary "fix" would be to disable the velocity check and use the old knockback check instead.

**Comment by konsolas** [comment]
@CodaMacroft does this occur in any specific location?

**Comment by konsolas** [comment]
Fixed in 3.1.4-b2
