### ISSUE TITLE
Speed FP w/ item swapping & Quick blocking/unblocking 

### ISSUE THREAD

**Issue by SkillzGamingYT** [konsolas/AAC-Issues#568]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.
**False positive**

We can't read your thoughts.

Please include details like:
* AAC logs / Full console error
**https://hastebin.com/raw/dewiferode**
* Video of the bug / bypass, best with verbose chat output
**W/O Slot swapping** https://youtu.be/RRsSQgxOBSY
**W/ Slot swapping(more VL)** https://www.youtube.com/watch?v=Bi74Ia78lGU
* The ingame name of the involved players
Just me (SkillzGaming)
* Config
**https://hastebin.com/raw/uletidetij**

### Core information
**Server version**: 1.8.8 Spigot

**AAC version**:  latest (3.1.4-b1)

**ProtocolLib version**: v4.2.1

**Plugin list**: Nothing to do with this bug...

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: insert

**ProtocolSupport version**: insert

**ViaBackwards version**: insert

**BungeeCord plugins**: insert

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here: 

Attach files by **not** dragging & dropping,  Choose Files selecting them, or pasting from the clipboard.

**Comment by SnakeDaoust1232** [comment]
This is a really old bug I posted labeled "quick switching" Set your item scalar to .741

**Comment by SnakeDaoust1232** [comment]
If you want full 1.7 support on the speed check you need to set it to .947

**Comment by SkillzGamingYT** [comment]
It's NOT quick switching bug I try to blocking a sword and unblock it(without switch slot), its still work.

**Comment by SkillzGamingYT** [comment]
I tested it, doesn't work (Set item scalar to ".741")

**Comment by SkillzGamingYT** [comment]
UPDATE: FP doesn't come from "quick switching" FP
Video trying without switching slots: https://youtu.be/RRsSQgxOBSY

**Comment by SkillzGamingYT** [comment]
@CeIebrimbor I'M **NOT** USING 1.7 CLIENT, IT'S "**LABYMOD**" WHICH CHANGES ANIMATION TO 1.7 (CLIENTSIDE). AND "I**TEM SWAPPING" ISN'T THE CASE**, YOU **WILL STILL** GETTING VL W/O ITEM CHANGING. Video trying without switching slots: https://youtu.be/RRsSQgxOBSY

**Comment by CeIebrimbor** [comment]
Seems like a detection bug that you need to desperately try to replicate once you know about it. Definitely a bug though.
