### ISSUE TITLE
v3 Soil Phase

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#57]
https://vimeo.com/188453656

Only have Optifine btw

**Comment by konsolas** [comment]
Original issue fixed, but problems occur when a player jumps on SOIL, turning it into DIRT while they're still stuck inside.

**Comment by Janmm14** [comment]
Seems like you need to grab another event.

**Comment by konsolas** [comment]
yep.

**Comment by konsolas** [comment]
Fixed and tested.
