### ISSUE TITLE
Velocity false positive

### ISSUE THREAD

**Issue by wasder** [konsolas/AAC-Issues#570]
https://www.dropbox.com/s/l8g27hm9q0qnz1p/2017-04-14_15-08-33.mp4
https://pastebin.com/f2epCQCh

AAC version: 3.1.4-b3
Protocollib: 4.2.0
Server version:
![](http://i.imgur.com/8qpqsFy.png)

**Comment by CeIebrimbor** [comment]
I removed the config paste of my custom settings (thank you for posting them publicly and violating my ToS). Please contact me from your original purchasing contact method to validate the version of my config you are running (if you were using any of my configs from the last week this would not happen).

**Comment by wasder** [comment]
Oops, sorry. I thought that little part of config would be no harm, but helpful. I use your config  v3.1.x | 11 but with Velocity check enabled.
For some reason only that very player got wrongly detected. I asked him to switch different versions (with forge and without) but still no luck.

**Comment by CeIebrimbor** [comment]
My Velocity settings are the same as default in detection settings with a delay to applying artificial knockback (for reference to other collaborators).

Define what you mean by wrongly detected? What was the player doing? Can they replicate the action to cause detection? If it is unknown, then it is unknown...we just need to know what the direct cause is so it can be singled out.

Thank you.

**Comment by wasder** [comment]
It's all on the video. My guess that he is stuck in a block after a hit knockback.

**Comment by konsolas** [comment]
Closing in favour of #572
