### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by CodaMacroft** [konsolas/AAC-Issues#571]
Ok, I get tired of daily updating my practice plugin to get bug fixes and bypass patches. I'm not telling you not to update it, you are doing a awesome job at replying to bug reports and fixing the issue. So, I was wondering if you could make the plugin have a feature that auto updates itself or someone must type a command out like "/aac update" and it updates AAC. I would really appreciate it if you did add this to the plugin.
Thanks - Coda

**Comment by Janmm14** [comment]
Well as far as I know auto-updaters of premium plugins are not allowed since it would be impossible to determine who actually bought aac.

**Comment by Eyremba** [comment]
> Well as far as I know auto-updaters of premium plugins are not allowed since it would be impossible to determine who actually bought aac.

Yes, that's true. It would violate against the Premium Resource Guidelines of SpigotMC and it would make it much more easy for pirates to get new versions of AAC just by using an old leak of AAC.

**Comment by CodaMacroft** [comment]
Oh, ok that makes sense.

**Comment by konsolas** [comment]
Spigot guidelines as described above
