### ISSUE TITLE
Velocity Bug still accuring...

### ISSUE THREAD

**Issue by CodaMacroft** [konsolas/AAC-Issues#572]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.

We can't read your thoughts.

Description: 
     I don't feel the need to fill this part out because the video I provided should demonstrate exactly what is happening. I show you the Velocity configuration in the video. I also renamed the plugin to "The Alpha" or "Alpha" because I think it looks better.

Please include details like:
* AAC logs / Full console error: 
Logs: https://pastebin.com/v4F3KPrU
* Video of the bug / bypass, best with verbose chat output: https://www.dropbox.com/s/2g0di1h3xhaaij7/2017-04-14%2010-51-20.mp4?dl=0
* The ingame name of the involved players: CodaChaos

### Core information
**Server version**: 1.10.2

**AAC version**: 3.1.4-b4

**ProtocolLib version**: 4.2.0

**Plugin list**: I prefer not to release plugin list for personal reasons.

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.0.4

**ProtocolSupport version**: none

**ViaBackwards version**: 2.0

**BungeeCord plugins**: none

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here:

**Comment by SnakeDaoust1232** [comment]
Can you turn on verbose. Its hard to tell whats happening.

**Comment by CodaMacroft** [comment]
I had verbose on.

**Comment by SnakeDaoust1232** [comment]
No you didnt. Verbose spams your chat with what the anticheat is doing. There is nothing happening in your chat. Make sure you have the permission node AAC.verbose and you have verbose enabled in your config.yml

**Comment by CodaMacroft** [comment]
I am sorry, I didn't have it on in the config and btw, I am OP and owner so I had the permission node. Would you like me to make another shorter video with verbose on?

**Comment by SnakeDaoust1232** [comment]
No, its ok. I didnt see that you posted logs. This is a really weird bug though. You should set your teleport to 0 and see if its still persists. It could actually be a bug with the TP feature.

**Comment by CodaMacroft** [comment]
New video link: https://www.dropbox.com/s/fey5g7du16aeen6/2017-04-14%2013-58-00.mp4?dl=0
Also, here is everything in the console. I cleared it before I started making the video so it would only show what AAC spit out to it. 

14.04 11:58:40 [Server] WARN handleDisconnection() called twice
14.04 11:58:40 [Server] INFO See you soon CodaChaos!
14.04 11:58:37 [Server] INFO CONSOLE: CodaChaos seems to be ignoring velocity 
14.04 11:58:23 [Server] INFO Owner: ~CodaChaos
14.04 11:58:05 [Server] INFO Warning Ground items will be removed in 120 seconds!
14.04 11:58:05 [Multicraft] Skipped 72 lines due to rate limit (30/s)
14.04 11:57:25 [Server] INFO Warning Ground items will be removed in 160 seconds!
14.04 11:57:19 [Server] INFO Owner: ~CodaChaos
14.04 11:56:15 [Server] INFO Owner: ~CodaChaos
14.04 11:55:33 [Server] INFO CodaChaos has joined our Chaotic Factions
14.04 11:55:33 [Multicraft] CodaChaos ran command Message of the Day
14.04 11:55:33 [Connect] User CodaChaos, IP 50.142.0.49
14.04 11:55:32 [Server] INFO UUID of player CodaChaos is 84bcfb52-1b92-43ec-8095-2a98619473fe
14.04 11:55:21 [Server] WARN handleDisconnection() called twice
14.04 11:55:21 [Server] INFO See you soon CodaChaos!
14.04 11:55:21 [Server] INFO CodaChaos was slain by §620x §eZombie
14.04 11:55:17 [Server] INFO CONSOLE: CodaChaos seems to be ignoring velocity 
14.04 11:55:11 [Server] INFO Owner: ~CodaChaos

**Comment by CodaMacroft** [comment]
Oh, I didn't see what you recently posted before I posted my post sorry. I will try to set the tp to 0.

**Comment by CodaMacroft** [comment]
Nope, it still kicks me and does the same thing except it doesn't teleport me back. Also, the teleporting is a little bugged too. I noticed that it sometimes teleports me inside of blocks.

**Comment by konsolas** [comment]
Does your server use any form of custom knockback?

**Comment by SnakeDaoust1232** [comment]
I'm going to test this on my server and see what happens.

**Comment by CodaMacroft** [comment]
No, My server doesn't have any type of plugin that modifies knockback because I know stuff like this can happen if it does.

**Comment by CodaMacroft** [comment]
If you need a full list of my plugins I guess I could send a screenshot of what /plugins says... I don't really want to share my plugins unless it is 100% needed.

**Comment by konsolas** [comment]
Do your players have gear with a knockback resistance attribute by any chance?

I suspect this is a compatibility problem because, in your video, there is a false positive on practically every hit, on relatively flat, simple terrain. In the meantime, I struggle to reproduce a single false positive on perfectly flat terrain, in a similar scenario against zombies.

**Comment by SnakeDaoust1232** [comment]
Just tested it on my server and i have the same issue. Just mobs hitting you flags the velocity check.

**Comment by CodaMacroft** [comment]
Nope, there was 0 enchants what so ever on the armor. I had enchanted golden apples, regular diamond armor and gear, a bow and arrow, and that's it. Not counting a couple spawn eggs.

**Comment by konsolas** [comment]
At this point I'm starting to believe that the upload had some file corruption. Also can't reproduce #575 on my copy.

**Comment by CodaMacroft** [comment]
What do you mean by "file corruption"? Snake reproduced it and you didn't tell me how to fix it. I don't care about what is causing it, just tell me how to fix the issue please.

**Comment by CodaMacroft** [comment]
Ok, I tested it again, I redownloaded AAC 5 times, tried it, got kicked, 100% deleted AAC from my server, reinstalled it, tested it, and got kicked. If you would like me to simply not care about the horribly bugged Velocity check, I'm fine with that. I am almost 100% sure that this false positive is in your code and not my server. Also, one of the main reason I reported this bug and showed you the config file in my first video is because even though I set every single one of those velocity numbers up to around 300, 400, 700, NOTHING changed! It still kicked me, it still sent off alerts, and still triggered it. That is one of the main problems. Thanks for helping me if you are going to shove me in the back of your head. I may sound a bit angry or like a jerk in this message, I am sorry for that. I mean no hard feelings to you or anyone else in this conversation, it's just that you won't listen to me. You have only tried to blame the problem on other plugins or me errors when I know it is your errors and bugged Velocity code that is causing this issue. Anyway, I'm sorry for the dick message. Thanks for reading if you made it through or cared enough - Coda

**Comment by konsolas** [comment]
I wasn't blaming you; I was blaming my upload seeing as people who downloaded it off spigot got the problem, and it doesn't occur on any of my test servers. 

This is going to be rectified in the next update which is just being finalized right now. Feel free to send your IGN here if you want to be whitelisted to check the velocity check before release.

**Comment by CodaMacroft** [comment]
CodaChaos is my IGN. Also, I understand what you are saying now. I though Snake reproduced it on his server though... What is the test server IP so I may join?

**Comment by konsolas** [comment]
aac3.kons.co:25566

1.8/ViaVersion

**Comment by CodaMacroft** [comment]
Actually, I don't need to test it on your test server. I'll simply test it once it is released and yell at you if it still isn't working lol. Thanks for the offer though. Go ahead and release it.
