### ISSUE TITLE
Elytra With Fireworks causes Errors (Normal Elytra flying mechanic works fine...)

### ISSUE THREAD

**Issue by MatheweB** [konsolas/AAC-Issues#573]
When my players attempt to fly with an Elytra, they are teleported to the ground, suspected of flying, and the console gets spammed with WARN messages. Before, this happened even when flying with an elytra without rockets, but the most recent update has fixed that. The server is running at 19.9-20tps consistently.

LOG for Deathsipher:
14.04 17:01:00 [Server] WARN java.lang.IllegalArgumentException: java.lang.ClassCastException@510d3bd0
14.04 17:01:00 [Server] WARN at sun.reflect.GeneratedMethodAccessor342.invoke(Unknown Source)
14.04 17:01:00 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14.04 17:01:00 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
14.04 17:01:00 [Server] WARN at me.konsolas.aac.cK.b(cK.java:143)
14.04 17:01:00 [Server] WARN at me.konsolas.aac.S.a(S.java:283)
14.04 17:01:00 [Server] WARN at sun.reflect.GeneratedMethodAccessor416.invoke(Unknown Source)
14.04 17:01:00 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14.04 17:01:00 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
14.04 17:01:00 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
14.04 17:01:00 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
14.04 17:01:00 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
14.04 17:01:00 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
14.04 17:01:00 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234)
14.04 17:01:00 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201)
14.04 17:01:00 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:197)
14.04 17:01:00 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:950)
14.04 17:01:00 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
14.04 17:01:00 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
14.04 17:01:00 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
14.04 17:01:00 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
14.04 17:01:00 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14.04 17:01:00 [Server] WARN at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
14.04 17:01:00 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
14.04 17:01:00 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
14.04 17:01:00 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
14.04 17:01:00 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
14.04 17:01:00 [Server] WARN at java.lang.Thread.run(Thread.java:745)

### Core information
**Server version**: Spigot 1.11.2

**AAC version**: 3.1.4-b4

**ProtocolLib version**: 4.2.1

**Plugin list**: AAC

*date and time when the issue occurred here: April 14th, 11:10AM EST

**Comment by konsolas** [comment]
seems to be the same exception as the citizens error.
