### ISSUE TITLE
Fly false positive with slime piston

### ISSUE THREAD

**Issue by wasder** [konsolas/AAC-Issues#575]
Looks like another false positive: https://www.dropbox.com/s/x3vabukdfg1lbzt/2017-04-15_01-14-45.mp4
Debug: https://hastebin.com/mazufufoka.sql
Latest AAC 3.1.4-b4
Protocollib: 4.2.0
Spigot 1.9.4
Celebrimbor's config

**Comment by wasder** [comment]
Tried on the latest AAC today (3.1.5-b1) still the same.

**Comment by konsolas** [comment]
Just tested this for 3.1.6
