### ISSUE TITLE
AAC V3 Official test server suggestion (MC 1.8.8)

### ISSUE THREAD

**Issue by Pluginsel** [konsolas/AAC-Issues#576]
This issue is invalid, I know.

Please remove white-list on the AAC V3 official test server (1.8.8), or add me on the white-list. 
Nick name: PluginerTR

I have a question: White-List when to remove?

- Thank you.

**Comment by konsolas** [comment]
test.kons.co is a non-whitelisted 1.8.8 test server with viaversion.

**Comment by Pluginsel** [comment]
okay, thank you.
