### ISSUE TITLE
KillAura improvement

### ISSUE THREAD

**Issue by sKye27** [konsolas/AAC-Issues#577]
I have tried plugin with more hacks and observe version 3.0 have a bad detection rate of kill aura.If you use jigsaw, pandora flux or other premium clients for hacking it may possibly not detect kill aura. And many of this hacks have acc kill aura bypass.What i want to say: kill aura needs to be remaked or patched.In version 2.9 kill aura worked pretty well , but now he needs improvements.

**Comment by SnakeDaoust1232** [comment]
The only problem I'm still having is that if your KillAura attacks invisibles, AAC's KillAura check doesn't pick it up at all. The heuristic should pick it up fairly quickly though. Or at least on my server it does.

**Comment by sKye27** [comment]
I tried with maximum settings on jigsaw and i dont get detection

**Comment by SnakeDaoust1232** [comment]
Then you are doing something wrong xD

**Comment by Janmm14** [comment]
Version 3.0 is old and killaura heuristics got improved since then.

**Comment by konsolas** [comment]
Closing due to reasons mentioned above.
