### ISSUE TITLE
Could not pass event PlayerMoveEvent to AAC v3.1.5

### ISSUE THREAD

**Issue by FrankHeijden** [konsolas/AAC-Issues#578]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.

We can't read your thoughts.

Please include details like:
* AAC logs / Full console error
* Video of the bug / bypass, best with verbose chat output
* The ingame name of the involved players

### Core information
**Server version**: spigot 

**AAC version**: 3.1.5

**ProtocolLib version**: 4.2.1

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here: 

15.04 18:31:00 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
15.04 18:31:00 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-d276ab1-d219213]
15.04 18:31:00 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-d276ab1-d219213]
15.04 18:31:00 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-d276ab1-d219213]
15.04 18:31:00 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-d276ab1-d219213]
15.04 18:31:00 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-d276ab1-d219213]
15.04 18:31:00 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
15.04 18:31:00 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
15.04 18:31:00 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-d276ab1-d219213]
15.04 18:31:00 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.11.2.jar:git-Spigot-d276ab1-d219213]
15.04 18:31:00 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.11.2.jar:git-Spigot-d276ab1-d219213]
15.04 18:31:00 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:615) [spigot-1.11.2.jar:git-Spigot-d276ab1-d219213]
15.04 18:31:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-d276ab1-d219213]
15.04 18:31:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-d276ab1-d219213]
15.04 18:31:00 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-d276ab1-d219213]
15.04 18:31:00 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-d276ab1-d219213]
15.04 18:31:00 [Server] INFO org.bukkit.event.EventException
15.04 18:31:00 [Server] ERROR Could not pass event PlayerMoveEvent to AAC v3.1.5

**Comment by Mxngo** [comment]
same

**Comment by FrankHeijden** [comment]
Using the latest version of **AAC 3.1.5-b2** still got the error. Now its saying 'Task #64269 for AAC v3.1.5 generated an exception' and after that the common spam.

16.04 14:22:48 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
16.04 14:22:48 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2-2.jar:git-Spigot-54ec0b8-ac405c3]
16.04 14:22:48 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2-2.jar:git-Spigot-54ec0b8-ac405c3]
16.04 14:22:48 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-2.jar:git-Spigot-54ec0b8-ac405c3]
16.04 14:22:48 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2-2.jar:git-Spigot-54ec0b8-ac405c3]
16.04 14:22:48 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2-2.jar:git-Spigot-54ec0b8-ac405c3]
16.04 14:22:48 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2-2.jar:git-Spigot-54ec0b8-ac405c3]
16.04 14:22:48 [Server] INFO at me.konsolas.aac.cl.lambda$new$0(cl.java:137) ~[?:?]
16.04 14:22:48 [Server] INFO at me.konsolas.aac.cJ.a(cJ.java:60) ~[?:?]
16.04 14:22:48 [Server] INFO at me.konsolas.aac.aJ.a(aJ.java:37) ~[?:?]
16.04 14:22:48 [Server] INFO at me.konsolas.aac.aJ.a(aJ.java:14) ~[?:?]
16.04 14:22:48 [Server] INFO at me.konsolas.aac.aJ.a(aJ.java:43) ~[?:?]
16.04 14:22:48 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
16.04 14:22:48 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
16.04 14:22:48 [Server] INFO at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
16.04 14:22:48 [Server] INFO java.lang.IllegalArgumentException: java.lang.ClassCastException@1996e13b
16.04 14:22:48 [Server] WARN [AAC] Task #64269 for AAC v3.1.5 generated an exception
16.04 14:22:48 [Multicraft] Skipped 2319 lines due to rate limit (30/s)
16.04 14:22:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2-2.jar:git-Spigot-54ec0b8-ac405c3]
16.04 14:22:47 [Server] INFO org.bukkit.event.EventException
16.04 14:22:47 [Server] ERROR Could not pass event PlayerMoveEvent to AAC v3.1.5
16.04 14:22:47 [Server] INFO [AAC] AAC has been enabled.
16.04 14:22:47 [Server] INFO [AAC] Starting API...
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check world.Velocity
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check world.Interact
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check world.NoSwing
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check world.Nuker
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check world.FastPlace
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Check world.FastBreak is disabled
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check combat.Criticals
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check movement.Derp
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check movement.Jesus
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check movement.NoFall
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check movement.Fly
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check movement.Phase
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check movement.Speed
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check movement.BadPackets
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check combat.Heuristics
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check combat.Killaura
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check combat.FastUse
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check combat.Regen
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check combat.Knockback
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check combat.FightSpeed
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check combat.Fastbow
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check combat.Hitbox
16.04 14:22:47 [Server] INFO [AAC] (CheckManager) Enabling check chat.Spam

**Comment by konsolas** [comment]
-b2.

**Comment by FrankHeijden** [comment]
thats the problem :P it is in -b2
