### ISSUE TITLE
Memory leak for unloaded worlds causing OutOfMemory crashes

### ISSUE THREAD

**Issue by MedicOP** [konsolas/AAC-Issues#579]
**AAC version:** 3.1.4-b2

My SkyWars server has been crashing every day with OutOfMemory errors ever since I installed AAC.

Heap Dump analyzing is showing 459 objects of CraftWorld, they seem to be leaked by a HashMap<CraftBlock> called "l" in me.konsolas.aac.d6.

![screenshot_1](https://cloud.githubusercontent.com/assets/18251099/25065503/9b3917b6-2211-11e7-85ed-7ccb07cb04df.png)

Please make sure blocks are removed from this HashMap when a world is unloaded, as the minigame server these crashes are happening in require constant loading/unloading of worlds.

![2ab1e32cf37c45c58025b9a68f7b307c](https://cloud.githubusercontent.com/assets/18251099/25065521/be35da7e-2211-11e7-96c7-31faa26fd2a2.png)

**Comment by Pluginsel** [comment]
1.3.4 ? İs 3.1.4...

**Comment by MedicOP** [comment]
Fixed

**Comment by konsolas** [comment]
Fixed in 3.1.5-b3
