### ISSUE TITLE
Could not pass event PlayerTeleportEvent / Could not pass event PlayerMoveEvent

### ISSUE THREAD

**Issue by Mxngo** [konsolas/AAC-Issues#580]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Since today's updates, I'm getting "Could not pass event PlayerTeleportEvent AND Could not pass event PlayerMoveEvent" error every time someone's moves please fix can't see anything but that error in the console!

Please include details like:
* AAC logs / Full console error

PlayerTeleportEvent: https://pastebin.com/AEU1NNe1

PlayerMoveEvent: https://pastebin.com/3NzmEuuK

### Core information
**Server version**: 1.11

**AAC version**: 3.1.5-b1

**ProtocolLib version**: 4.2.1

**Plugin list**: insert

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: none

**ProtocolSupport version**: 4.25

**ViaBackwards version**: none

**BungeeCord plugins**: none

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here:

**Comment by konsolas** [comment]
-b2.
