### ISSUE TITLE
List of False Positives for AAC 3.1.5b1

### ISSUE THREAD

**Issue by guerryer** [konsolas/AAC-Issues#582]
- [x] https://youtu.be/jpLCQskm2V8 - Fly (1)
- [x] https://youtu.be/LhiCyeNH-Ls - Fly (2)
- [ ] https://youtu.be/mhZ4zpcyCx4 - Fly (3)
- [ ] https://youtu.be/T6uIGAIDbXU - Fly (4)
- [ ] https://youtu.be/krkKy_pV7Hs - Fly (5)

Additional Informations

You can get false kick for all false positives show in this list.
Minecraft Version use 1.8.9-OptiFine_HD_U_H7
Playlist : https://www.youtube.com/playlist?list=PLItmJx6Tis9KPa9zRtxh-ArmznVSCVY7e

**Comment by johand199** [comment]
Can confirm https://www.youtube.com/watch?v=bMIu0jQ7Qzw

**Comment by Pluginsel** [comment]
https://youtu.be/mhZ4zpcyCx4 is fixed on AAC V 3.1.5 version.

**Comment by guerryer** [comment]
No its not fix

**Comment by SnakeDaoust1232** [comment]
3.1.6 isnt out yet. Change the title to 3.1.5b1
