### ISSUE TITLE
COnsole spam

### ISSUE THREAD

**Issue by Owen1212055** [konsolas/AAC-Issues#583]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.

We can't read your thoughts.

Please include details like:
* AAC logs / Full console error
* Video of the bug / bypass, best with verbose chat output
* The ingame name of the involved players

### Core information
**Server version**: 1.11.2

**AAC version**: 3.1.5

**ProtocolLib version**: 4.2.1
--------------------------------------

The console gets spammed with

net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:615) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO org.bukkit.event.EventException
15.04 16:51:20 [Server] ERROR Could not pass event PlayerMoveEvent to AAC v3.1.5
15.04 16:51:20 [Server] INFO ... 15 more
15.04 16:51:20 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:20 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:20 [Server] INFO at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source) ~[?:?]
15.04 16:51:20 [Server] INFO at me.konsolas.aac.R.a(R.java:20) ~[?:?]
15.04 16:51:20 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:33) ~[?:?]
15.04 16:51:20 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:106) ~[?:?]
15.04 16:51:20 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:45) ~[?:?]
15.04 16:51:20 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:20 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:20 [Server] INFO at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) ~[?:?]
15.04 16:51:20 [Server] INFO Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@1fae2f3e
15.04 16:51:20 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
15.04 16:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
15.04 16:51:20 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
15.04 16:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:615) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:20 [Server] INFO org.bukkit.event.EventException
15.04 16:51:20 [Server] ERROR Could not pass event PlayerMoveEvent to AAC v3.1.5
15.04 16:51:19 [Server] INFO ... 15 more
15.04 16:51:19 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:19 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:19 [Server] INFO at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source) ~[?:?]
15.04 16:51:19 [Server] INFO at me.konsolas.aac.R.a(R.java:20) ~[?:?]
15.04 16:51:19 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:33) ~[?:?]
15.04 16:51:19 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:106) ~[?:?]
15.04 16:51:19 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:45) ~[?:?]
15.04 16:51:19 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:19 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:19 [Server] INFO at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) ~[?:?]
15.04 16:51:19 [Server] INFO Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@651b8c79
15.04 16:51:19 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
15.04 16:51:19 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:615) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO org.bukkit.event.EventException
15.04 16:51:19 [Server] ERROR Could not pass event PlayerMoveEvent to AAC v3.1.5
15.04 16:51:19 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at me.konsolas.aac.R.lambda$new$0(R.java:13) ~[?:?]
15.04 16:51:19 [Server] INFO at me.konsolas.aac.bG.a(bG.java:19) ~[?:?]
15.04 16:51:19 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:33) ~[?:?]
15.04 16:51:19 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:106) ~[?:?]
15.04 16:51:19 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:45) ~[?:?]
15.04 16:51:19 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:19 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:19 [Server] INFO at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) ~[?:?]
15.04 16:51:19 [Server] INFO java.lang.IllegalArgumentException: java.lang.ClassCastException@58f72102
15.04 16:51:19 [Server] WARN Task #75 for AAC v3.1.5 generated an exception
15.04 16:51:19 [Server] INFO ... 15 more
15.04 16:51:19 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:19 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:19 [Server] INFO at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source) ~[?:?]
15.04 16:51:19 [Server] INFO at me.konsolas.aac.R.a(R.java:20) ~[?:?]
15.04 16:51:19 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:33) ~[?:?]
15.04 16:51:19 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:106) ~[?:?]
15.04 16:51:19 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:45) ~[?:?]
15.04 16:51:19 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:19 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:19 [Server] INFO at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) ~[?:?]
15.04 16:51:19 [Server] INFO Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@69b91917
15.04 16:51:19 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
15.04 16:51:19 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:615) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO org.bukkit.event.EventException
15.04 16:51:19 [Server] ERROR Could not pass event PlayerMoveEvent to AAC v3.1.5
15.04 16:51:19 [Server] INFO ... 15 more
15.04 16:51:19 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:19 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:19 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]

15.04 16:51:17 [Server] INFO ... 15 more
15.04 16:51:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:17 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:17 [Server] INFO at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source) ~[?:?]
15.04 16:51:17 [Server] INFO at me.konsolas.aac.R.a(R.java:20) ~[?:?]
15.04 16:51:17 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:33) ~[?:?]
15.04 16:51:17 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:106) ~[?:?]
15.04 16:51:17 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:45) ~[?:?]
15.04 16:51:17 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:17 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:17 [Server] INFO at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) ~[?:?]
15.04 16:51:17 [Server] INFO Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@42c1fcfe
15.04 16:51:17 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
15.04 16:51:17 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
15.04 16:51:17 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
15.04 16:51:17 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:88) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:615) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO org.bukkit.event.EventException
15.04 16:51:17 [Server] ERROR Could not pass event PlayerMoveEvent to AAC v3.1.5
15.04 16:51:17 [Server] INFO ... 15 more
15.04 16:51:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:17 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:17 [Server] INFO at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source) ~[?:?]
15.04 16:51:17 [Server] INFO at me.konsolas.aac.R.a(R.java:20) ~[?:?]
15.04 16:51:17 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:33) ~[?:?]
15.04 16:51:17 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:106) ~[?:?]
15.04 16:51:17 [Server] INFO at me.konsolas.aac.bJ.a(bJ.java:45) ~[?:?]
15.04 16:51:17 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:17 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
15.04 16:51:17 [Server] INFO at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) ~[?:?]
15.04 16:51:17 [Server] INFO Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@45ec8634
15.04 16:51:17 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
15.04 16:51:17 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
15.04 16:51:17 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source)

**Comment by Owen1212055** [comment]
It causes my server to crash alot

**Comment by MClausz** [comment]
same issue

**Comment by MClausz** [comment]
@konsolas

**Comment by konsolas** [comment]
-b2
