### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by NEZNAMY** [konsolas/AAC-Issues#584]
### Issue description

Error: https://pastebin.com/8WbSuA0N

### Core information
**Server version**: 1.11.2

**AAC version**: 3.1.5-b1

**ProtocolLib version**: build 354

**Plugin list**: Really needed ?

### Special environment information
**ProtocolSupport version**: build 38
**BungeeCord plugins**: skinsrestorer and my own

//edit seems like a duplication of #583 , sorry

**Comment by konsolas** [comment]
#583
