### ISSUE TITLE
Check-based bypass permission

### ISSUE THREAD

**Issue by FrankHeijden** [konsolas/AAC-Issues#585]
Heya,

Ive got something in mind that could be useful for servers which are using plugins like superpickaxe (me too). I was thinking about some sort of bypass permission node for each AAC check, so that players with a rank are able to bypass fastbreak check, so they can use their superpickaxe without any problems. At the moment I've disabled the Fastbreak check for the whole server, but I think AAC would be so much better with permission nodes.

Greetings,
Frank

**Comment by Janmm14** [comment]
Stuff like that can be done with the API of AAC at the moment. so in case you can program in Skript (with LargeSk addon) or Java, you can use the PlayerViolationEvent to cancel for certain people.

**Comment by konsolas** [comment]
I'm going to leave this to be done with the API. Implementing it on AAC's end would probably involve adding a few classes that interact with the API anyway.
