### ISSUE TITLE
Climbing a ladder with a trapdoor at the top causes a lagback

### ISSUE THREAD

**Issue by Cryptite** [konsolas/AAC-Issues#587]
### Issue description

Title is the explanation. GIF provided below.
https://giphy.com/gifs/xUPGcLqTZEJmgFgyPe

### Core information
**Server version**: PaperSpigot git-Paper-1081 (MC: 1.11.2)

**AAC version**: 3.1.5-b2

**ProtocolLib version**: 4.2.1 b354

**Comment by konsolas** [comment]
1.11 exclusive bug. Will be fixed in next update
