### ISSUE TITLE
AAC (epicworldgenerator treefeller)

### ISSUE THREAD

**Issue by AmazedMender16** [konsolas/AAC-Issues#59]
Could you make it anyway possible to accept epicworldgenerators treefeller to be accepted and not that aac blocks it from using :( would appreciate if its possible to be added in the newer version

**Comment by AmazedMender16** [comment]
Anyway possible this can be done :( ?

**Comment by Janmm14** [comment]
@AmazedMender16 You need to ask the author of the addon to provide an API.

**Comment by AmazedMender16** [comment]
kinda rude to close a issue for that instead of helping and trying something dont you think, anyway is asked the dev if he can provide a api

**Comment by CeIebrimbor** [comment]
AAC can't add recognition for EWG without an API to hook. EWG needs to publish and API or change the block breaks to a "fake" break event.

Don't call it rude...he can't do anything.

**Comment by CeIebrimbor** [comment]
@amazedmender16
Request this be reopened or post another issue request of and when EWG posts a public API.
