### ISSUE TITLE
ERROR Plugin AAC v3.1.5 has failed to register events

### ISSUE THREAD

**Issue by CodaMacroft** [konsolas/AAC-Issues#590]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.

We can't read your thoughts.

Plugin error DESC: I started up my server and happened to look at the CONSOLE for any errors. I then saw that the console said "ERROR Plugin AAC v3.1.5 has failed to register events for class me.konsolas.aac.bx because com/gmail/nossr50/events/fake/FakeBlockBreakEvent does not exist.
" when starting up AAC. So, I thought you might want to know about this. Thanks - Coda

Please include details like:
* AAC logs / Full console error: 
Console Error (look at bottom of error): https://pastebin.com/6nqTi9tc 
* Video of the bug / bypass, best with verbose chat output: Simply a console error.
* The ingame name of the involved players: CodaChaos AKA Coda

### Core information
**Server version**: 1.10.2

**AAC version**: 3.1.5-b3

**ProtocolLib version**: 4.2.0

**Plugin list**: I prefer not to release plugin list for personal reasons.

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.0.4

**ProtocolSupport version**: none

**ViaBackwards version**: 2.0

**BungeeCord plugins**: none

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here:

**Comment by Janmm14** [comment]
This happens when AAC detected a plugin named MCMMO, but its either not that public mcmmo plugin or an old version not containing certain APIs.

**Comment by CodaMacroft** [comment]
Ok so I should what? Get a new version of McMMO?

**Comment by Janmm14** [comment]
Yep.

**Comment by CodaMacroft** [comment]
Ok, what version would you suggest?

**Comment by Janmm14** [comment]
The one fitting to your server's version: https://www.spigotmc.org/resources/mcmmo.2445/

**Comment by CodaMacroft** [comment]
I know why it is saying that now. I used an older version of McMMO from Bukkit because it was free. Will me having this version of McMMO affect AAC in any way?

**Comment by Janmm14** [comment]
@CodaMacroft if you take a little closer look, its still free.

**Comment by CodaMacroft** [comment]
Just tell me how to download it because I see no place where is says "HEY! CLICK HERE TO GET THE PLUGIN FREE!". Please just tell me what to click...

**Comment by Janmm14** [comment]
pls search on that page for `(Non-Paywalled)`
kthx

**Comment by CodaMacroft** [comment]
I knew you were going to say that... I use 1.10.2 version of MC...
kthx <3

**Comment by Janmm14** [comment]
apparantly https://ci.drtshock.net/job/mcMMO/ seems down :/

**Comment by CeIebrimbor** [comment]
Will reopen if it occurs with latest McMMO (and a re-open is requested). You can always purchase McMMO on Spigot to gain access to the latest version(s). AAC cannot bend to support obsolete McMMO because the avenue to bypass paying is not available.

**Comment by Janmm14** [comment]
(just a quick note, the download I linked above is now available again @CodaMacroft)

**Comment by CodaMacroft** [comment]
Ok, thank you.
