### ISSUE TITLE
Phase and Speed FP

### ISSUE THREAD

**Issue by Pluginsel** [konsolas/AAC-Issues#592]
Phase and Speed is causing false positives.

- [ ] https://youtu.be/xDDO-A8LxfQ (Phase)
- [ ] https://youtu.be/zgan05Ilb0s (Phase / Speed)
- [ ] https://youtu.be/R4FmeGMD9aY (Phase)

İ'm tested on AAC V3 official test server.

AAC Version: 3.1.5
Client : 1.8.9 OptiFine_HD_U_H7

**Comment by Janmm14** [comment]
Intended.
