### ISSUE TITLE
Error spam followed by a TPS drop.

### ISSUE THREAD

**Issue by JuliCarles** [konsolas/AAC-Issues#595]
One of my servers using AAC massively dropped TPS because of this two aac errors (I guess).
This two errors started to be spammed in console.
http://www.youscreenshot.com/ddec33279eedbe28b2ba24199916836e
http://www.youscreenshot.com/9fa61cd292a469a63ce61b518296d28b
TPS dropped to 4~7.

This is the first time this happens and we use the same version on every server, until now.

### Core information
**Server version**: 1.8.8

**AAC version**: Latest (3.1.5-b3)

**ProtocolLib version**: Latest, this new version released 4.2.1 that's compatible with 1.8.8 servers.

**Plugin list**: http://www.youscreenshot.com/ef3d9fa1b3ad5596c121e41d1862ee37

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: Latest

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none affecting

**Comment by SnakeDaoust1232** [comment]
Post the crash log.

**Comment by JuliCarles** [comment]
Sorry, it wasn't a crash, only a massive TPS drop. Still needs to be checked.

**Comment by CeIebrimbor** [comment]
@JuliCarles Can you provide the timings so the event causing the lag can be identified? May not be needed, but more info = easier to support/fix.

**Comment by JuliCarles** [comment]
Impossible, we had to reset the server, otherwise it would've crashed.

**Comment by Janmm14** [comment]
(If it happens again you can try creating a timings report)
