### ISSUE TITLE
Fly False Positive When Sleeping

### ISSUE THREAD

**Issue by SioWolf** [konsolas/AAC-Issues#598]
### Description
Whenever a player is sleeping in a bed their fly violation level continually climbs until they get kicked.

All config settings are default, and it does not matter where the bed is, how it was placed, or who is sleeping.

The issue was not present a couple weeks ago. I updated several plugins and the issue appeared. 

### Core information
**Server version**: PaperSpigot # 1083

**AAC version**: 3.1.5-b3

**ProtocolLib version**: 4.2.1

**Plugin list**: CleanroomGenerator, CommandSpy, CreeperHeal, AsyncWorldEditInjector, CoreProtect, dynmap, BetterBeds, ClearLag, ChatControl, SkyblockEco, WorldBorder, BuycraftX, Interactables, Votifier, ProtocolLib, CustomParticleEffects, AsyncWorldEdit, SeattleSummer, BlocksHub, PermissionsEx, ConditionalCommands, mcMMO, GAListener, Vault, PerWorldInventory, AAC, ASkyBlock, ChestCommands, WorldEdit, Orebfuscator4, PortalCommands, Essentials, Autorank, LiteBans, VoidSpawn, Citizens, Dynmap-Essentials, PlotSquared, WorldGuard, Shop, PvPManager, EssentialsSpawn, PremiumVanish, Multiverse-Core, Plot2Dynmap, GriefPrevention, HolographicDisplays, Dynmap-GriefPrevention, RandomTeleport, TitleManager, MyPet, AreaShop

### Special environment information
**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by CeIebrimbor** [comment]
Is this in every bed regardless of the blocks above and below the bed?

Better beds somehow manipulating the use of beds and making the player just hover?
