### ISSUE TITLE
[Bypass] Step bypass by sending 2/3 movement packets more

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#6]
Hack clients can send 2/3 packets more to bypass step detection.
Sure they get caught by speed later on, but if there are just some steps occasionally there is no problem.

Also what to do if hack clients only send 19 movement packets instead of 20 as a buffer for the speed detection after they used step...

**Comment by Photon-GitHub** [comment]
One of the hardest modules to detect, I would also categorize this as low priority compared to the speed/killaura bypasses.

**Comment by konsolas** [comment]
Closing this one as fixed as well.
