### ISSUE TITLE
McMMO Herbalism NoSwing False Positive

### ISSUE THREAD

**Issue by Sikatsu** [konsolas/AAC-Issues#600]
### Issue description

When you try to make mossy cobblestone with the McMMO herbalism skill, it will get you kicked for ''NoSwing''

I am using the latest configuration version (16) of Celebrimbor.

https://pastebin.com/xsQ9V252

### Core information
**Server version**: 1.11.2
**AAC version**: 3.1.5
**ProtocolLib version**: 4.2.1
**Plugin list**: AAC, McMMO

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by CeIebrimbor** [comment]
@Sikatsu 
Can you reproduce this yourself, or you saw a single kick? Why do I ask?

**105622.0** > 8000.0

The kick message you sent was for a player that supposedly had 105,622ms ping.

**Comment by Sikatsu** [comment]
Not a single kick, I wouldn't make a bug report for a single kick. This was just the earliest line I found in the logs. It's easy reproducable.

**Comment by CeIebrimbor** [comment]
Just clarifying, thank you.

**Comment by Sikatsu** [comment]
I understand!
