### ISSUE TITLE
Horse bug | velocity check (midair direction changed)

### ISSUE THREAD

**Issue by OWERLORD01** [konsolas/AAC-Issues#601]
## Issue description
When someone is riding a horse and jumping,
its triggering new velocity check (midair directions)

## Core information
**Server version**: 1.11.2

**AAC version**: 3.1.5

**ProtocolLib version**: latest

**Plugin list**: aac, protocollib

**Comment by CeIebrimbor** [comment]
What build of 3.1.5? If it is not b1 or higher, then this is likely already patched.

**Comment by SnakeDaoust1232** [comment]
I was unable to reproduce on 3.1.5b3

**Comment by CeIebrimbor** [comment]
Will reopen if evidence of bug exists on 3.1.5-b3 or higher.

**Comment by OWERLORD01** [comment]
I think it's patched ;D
