### ISSUE TITLE
Error console

### ISSUE THREAD

**Issue by JavituRec** [konsolas/AAC-Issues#603]
I see a error un my skywars server with las version AAC.

ERROR:

https://hastebin.com/revakuxuqo.bash

**Server version**: 1.8.8

**AAC version**: 3.1.5-b3

**ProtocolLib version**: 4.2.1

**Plugin list**: https://fotos.subefotos.com/77d915ea54158f9d043c5b84b6d11060o.png

**Comment by NEZNAMY** [comment]
Same here, server 1.11.2.

**Comment by campzazathelord** [comment]
same here!!!!
