### ISSUE TITLE
Add MySQL mode like Spartan

### ISSUE THREAD

**Issue by jQuery0** [konsolas/AAC-Issues#605]
Hi,

Can you add a MySQL feature like Spartan?

**Comment by Janmm14** [comment]
Why?

**Comment by jQuery0** [comment]
Log specific data in it like current violation level (and maybe keep it when switching server), and the ability to check players violation level without having to check the logs per server.

When you have more than 15+ servers, it's anoying to check every server to see the logs of a specific player.

Maybe have a command like NCP /aacinfo <player>

**Comment by Janmm14** [comment]
Could be done using the API of AAC.
For online players see /aacadmin for an overview of violations.

**Comment by jQuery0** [comment]
"Could be done using the API of AAC."
Doesn't mean that it can't be added? I think that it's an awesome, and helpful feature. @konsolas opinion?

**Comment by Janmm14** [comment]
>>"Could be done using the API of AAC."
>>_written by @Janmm14_
>
>Doesn't mean that it can't be added? I think that it's an awesome, and helpful feature. @konsolas opinion?
>
>_written by @jQuery0_

Nope, that means that it is possible to create an external plugin which will use the API of AAC to provide MySQL logging and vl synchronisation. (Its still possible to include that into AAC in theory)

**Comment by jQuery0** [comment]
No idea how to use the API. That's why I suggested to add this feature.

**Comment by konsolas** [comment]
Not planning to add this mysql mode because violation level doesn't matter long term - VL decay system is used in AAC.
