### ISSUE TITLE
/back not working with AAC enabled

### ISSUE THREAD

**Issue by Swede37** [konsolas/AAC-Issues#608]
### Issue description

When "BackTester" dies and does /back it takes her to spawn.  Also, if she runs in a long distance, back warps her back to a whole different area.  Here's a link to what is in the logs - the time before the fly problems on the horse it references "bad Packets"   https://hastebin.com/ebusuleyuj.pas

No console errors

-Spigot version:  9ba269b-c19c293 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT
-AAC version:  3.1.5-b3 with Celembrior's custom config ver:  v3.1.x | 15
-AACAdditionPro version:  1.8.2 with  Celembrior's custom config ver:  v1.8x | 1
-'Essentials-2.x-SNAPSHOT (build 20)*
-'EssentialsProtect-2.x-SNAPSHOT (build 20)*
-EssentialsSpawn-2.x-SNAPSHOT (build 20)*
-PermissionsEx-1.23.4
-Protocollib 4.2.1
If you really need a full list of all my plugins, I would prefer to send them privately if possible.
*just noticed there was a new build #21 issued 3 days ago

**Comment by konsolas** [comment]
-b3
