### ISSUE TITLE
Block Glitch | Feature (Pitch) 

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#609]
Info
- Change the users "pitch" to 0 when detected for this specific part of the fly check. It will make it really annoying to "try" to get banned for this.

Video: https://www.youtube.com/watch?v=CdfroySINjA&feature=youtu.be

Core information

Server version: Paperspigot 1.8.8
AAC version: 3.1.5b3
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/62230b456a22877a8803245f9132ccee

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/b5d2b4e81fd8ee3a44b7472e9caf939d

**Comment by konsolas** [comment]
Will be a config option in fly: reset_pitch, defaulting to false.
