### ISSUE TITLE
v3 Jump Potion + Block Edge

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#61]
You saw live on test server, just posting reminder.

False Fly detect when jumping on the very edge of any block with Jump potion. Tested Anvil, Leaves, Stairs, fence...pretty much all blocks.

**Comment by CeIebrimbor** [comment]
Similar to #53 I suppose. Something funky going on with block edges. #53 existed in the recent builds for 1.10 servers (I think all versions).

**Comment by konsolas** [comment]
Fixed and tested. (Test case: http://i.imgur.com/8vQdkst.png)
