### ISSUE TITLE
Still memory leak unloaded worlds causing OutOfMemory crashes

### ISSUE THREAD

**Issue by MedicOP** [konsolas/AAC-Issues#610]
**AAC version**: 3.1.5-b3

A memory leak is still present leaking unloaded worlds, it's different from #579.

This one is caused by ConcurrentHashMap<UUID, PlayerMoveEvent> called "b" in me.konsolas.aac.aS.

PlayerMoveEvent instances should be removed from this map when the world they reference is unloaded.

Please also check other maps that might have the same problem

**Comment by Janmm14** [comment]
Btw, issue might be superseded for 3.1.6 already.

**Comment by MedicOP** [comment]
idk what you mean

**Comment by Janmm14** [comment]
Superseded = Changes in anotger mazter were already done that the issue here is already invalid.
And I said that's maybe the case.
