### ISSUE TITLE
Liquid Bounce b24.3 Heuristic Bypass?

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#613]
Information:
- The newest liquid bounce bypasses the heuristics check fully it seems. I tried on the newest version, and pvpied for like 2 minutes with multiaura, and was not detected. I downgraded liquid bounce, used the same killaura settings and I was detected within seconds, for 94 confidence.

Kill Aura settings:
- 180 FOV, 180 Rotate Rate, Reach 4.3, AAC Bypass, KeepSprint, Multiaura, Vanilla, Direction, 20CPS (All entities)

Videos: 
- Version b24.3(Undetected): https://www.youtube.com/watch?v=-p57dsOBZpg&feature=youtu.be
- Version b23.2(Detected in seconds): https://www.youtube.com/watch?v=OHemjMSqmA0&feature=youtu.be

Core information

Configs:
AAC: https://hastebin.com/ejoropoqik.bash
AACAdditionpro: https://hastebin.com/qobuyegema.bash

Server version: Paperspigot 1.8.8
AAC version: 3.1.5b3
ProtocolLib version: 4.2.0
Plugin list: https://gyazo.com/62230b456a22877a8803245f9132ccee

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: https://gyazo.com/b5d2b4e81fd8ee3a44b7472e9caf939d

**Comment by jiangdashao** [comment]
AAC3s combat check is easy to bypass
Even worse than 1.9.10's combat check

**Comment by SnakeDaoust1232** [comment]
Im not talking about the killaura check, im talking about the heuristic check. Its not easily bypassed and is 100x better than 1.9.10

**Comment by SkillzGamingYT** [comment]
I want bot check back, it's good for detecting non blatant aimbot

**Comment by konsolas** [comment]
![image](https://cloud.githubusercontent.com/assets/9408210/25491784/df0a6ff2-2b68-11e7-8992-6eba79ee5226.png)

**Comment by SnakeDaoust1232** [comment]
Wrong on my end. Sry

**Comment by konsolas** [comment]
Confirmed as invalid by @SnakeDaoust1232
