### ISSUE TITLE
Heuristics and mob grinders | ASAP

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#614]
Info
- Grinding for mobs in a mob grinder flags several of the heuristic checks up to 95
- Running in circles around them clicking at around 12-14 cps

Fix:
- Maybe have the option to disable the heuristics on certain mobs. Or all mobs. Just having it active on players.

Patterns:
    - "P/92"
    - "P/90"
    - "P/02"
    - "P/09"
    - "P/20"
    - "P/29"
    - "P/93"
    - "P/98"

Screenshot of grinder:
- https://gyazo.com/2dde0a13e4a065635b6f0cd0bd9fcc69

Core information

Server version: TacoSpigot 1.8.8
AAC version: 3.1.5b3
ProtocolLib version: 4.2.0
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by jQuery0** [comment]
I can confirm this. Same for the Killaura check when a player has a ping of ~ 200/300+.
