### ISSUE TITLE
Interact FP | Mob grinder

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#615]
Info
- Grinding for mobs in a mob grinder flags for interact. Attacked a player-like through a wall.
- 12-14 cps
- ign SnurkADurk

Video: https://www.youtube.com/watch?v=dEGfNyd2w2Y&feature=youtu.be

Core information

Server version: TacoSpigot 1.8.8
AAC version: 3.1.5b3
ProtocolLib version: 4.2.0
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by SnakeDaoust1232** [comment]
@konsolas I think this is related as well. https://www.youtube.com/watch?v=HWey3Y0-Grg&feature=youtu.be

**Comment by SnakeDaoust1232** [comment]
@konsolas I think this is worthy of the next milestone as well.

**Comment by Photon-GitHub** [comment]
Is this still valid/reproduceable on the the lastest version?

**Comment by konsolas** [comment]
Confirmed by @Hydronymos
