### ISSUE TITLE
CRITICAL NETWORK ERROR: Check your hosts file

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#618]
AAC said that and then disable. Through my server has a normal internet connection, it happened today and no one touch the hosts file recently.
I think the target that AAC struggling to connect had blocked my server.
Server IP: 103.9.159.34

**Comment by SnakeDaoust1232** [comment]
need way more info please. Server version, error log, crash log, log in general of any sorts lol. Need a tun more info here.

**Comment by MClausz** [comment]
@SnakeDaoust1232  this is a network issue which has nothing to do with server version, and the only error log was the title.

**Comment by MClausz** [comment]
what is the server address that AAC says critical network error when it fail to connect?

**Comment by ItzSomebody** [comment]
Are you freakin' joking?

Give us your:

AAC version:
Logs:

Also, show us 'sudo nano /etc/hosts.allow'

**Comment by MClausz** [comment]
Version: 3.1.5-b3
Logs: CRITICAL NETWORK ERROR: Check your hosts file (stated in title)
https://pastebin.com/1LxBmtCX
hosts file have nothing but 127.0.0.1 localhosts
That's all
You thinks I'm stupid but you are the stupid one actually, what I want to know is if my server is blocked from AAC server as I provided my server IP and what is the server address that AAC says critical network error when it fail to connect to.

**Comment by ItzSomebody** [comment]
Why are you calling me stupid if you want me to help?

Anyways, that is a known bug with AAC v3.1.5-b3, use AAC v3.1.5-b2

**Comment by Janmm14** [comment]
For me and likely also for konsolas its not a known bug.

**Comment by SnakeDaoust1232** [comment]
Me either. Never seen it before

**Comment by ItzSomebody** [comment]
At least 3 people on Spigot get it.

**Comment by konsolas** [comment]
#668
