### ISSUE TITLE
v3 Elytra launchers

### ISSUE THREAD

**Issue by konsolas** [konsolas/AAC-Issues#62]
Elytra launcher made with boats on the test server. Triggers the fly check and phase. Extra code for entity bumping needed.

**Comment by konsolas** [comment]
THEY'RE WORKING NOW!!!!

YEAH!

**Comment by CeIebrimbor** [comment]
Yay! All done entity side?

**Comment by konsolas** [comment]
Yeah, entities are counted on the server and speed limits are changed :D
