### ISSUE TITLE
QuickSwitch, not fully using consumeable, fly pitch reset not always | 3.1.6

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#620]
Speed:
- Quick Switching (0s-17s)
- Using a item (potion,eating) rapidly without fully "using" the item. (17s-42s) (42s-1:02m)
Fly:
- The pitch doesn't "always" reset. Cant figure out why though. (1:03m-1:32m)

Video: https://www.youtube.com/watch?v=Z9mYIRanIDY&feature=youtu.be

Core information

Speed Config: https://hastebin.com/gutajefino.bash
Fly Config: https://hastebin.com/eyuxizelor.bash

Server version: PaperSpigot 1.8.8
AAC version: 3.1.6
ProtocolLib version: 4.2.0
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by CeIebrimbor** [comment]
Is this an issue plaguing servers? I'm not personally sure why reset pitch is a thing. I know spamming dumb behavior might toss a few flags, but can we close this? If not, is it really "Critical"?

**Comment by Rerd** [comment]
It would be great if this was fixed. It's really annoying when players spam shift.

**Comment by konsolas** [comment]
Seems to be an uncommon bug, and not sure if it applies to current versions.
