### ISSUE TITLE
McMMO/Fast Pickaxes | Annoying bug (3.1.5b3)

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#622]
Info
- When you mine with a fast pickaxe, sometimes the block glitches and make an "invisible" block causing players to get stuck in the block, kicking them for phase. I wouldn't be making a big deal about this, but my players are, since its happening to everyone who is trying to mine.

Video: https://www.youtube.com/watch?v=KAGeDYriv_M&feature=youtu.be

Core information

Fastbreak Config: https://hastebin.com/weqonuzego.bash

Server version: TacoSpigot 1.8.8
AAC version: 3.1.5b3
ProtocolLib version: 4.2.0
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by guerryer** [comment]
The Issue can be cause by the Interact Check or Minecraft itself.
Minecraft Issue Explained by mcMMO dev : https://github.com/mcMMO-Dev/mcMMO/issues/759

**Comment by SnakeDaoust1232** [comment]
I see. Its just really annoying. You can close this.

**Comment by SnakeDaoust1232** [comment]
I set this up. https://hastebin.com/punexucimi.bash

Informs the player what to do to fix the issue.
