### ISSUE TITLE
ERROR in Console

### ISSUE THREAD

**Issue by Felix5566** [konsolas/AAC-Issues#626]
### Core information
**Server version**: 1.8.8

**AAC version**: 3.1.6

**ProtocolLib version**: last

**ViaVersion version**: last

ERROR: https://hastebin.com/doyimofuki.go

**Comment by CeIebrimbor** [comment]
Could you try to run with ProtocolLib 4.2.0 (build 341) and see if this still occurs?

**Comment by Felix5566** [comment]
not 4.2.1?

**Comment by CeIebrimbor** [comment]
Correct. 4.2.0

4.2.1 has been known to cause issues with 1.8 servers. Even though ProtocolLib advertises to be cross-version compatible. It is something AAC needs to work on (why I still labeled with "Error"), but I just wanted to see if reverting to 4.2.0 would remedy the error.

**Comment by Felix5566** [comment]
ok, is the problem with the AAC Crash gefixt? Then i can remove the AAC-AntiCrash Plugin.

**Comment by Janmm14** [comment]
crash fixed, but that plugin is compatible with 4.2.0 too

**Comment by Felix5566** [comment]
ok is it better i don't remove it?

**Comment by Janmm14** [comment]
it doesn't hurt to have it, as far as I know AAC has this basically inbuilt now

**Comment by Felix5566** [comment]
ok, i leave the AAC anticrash plugin on my server.

**Comment by konsolas** [comment]
Question seems answered - protocollib version.
