### ISSUE TITLE
Speed FP/Bug

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#628]
Info:
- Teleporting into water? I'm not sure

Video: https://www.youtube.com/watch?v=hWsZ6Tul5Oc&feature=youtu.be

Core information

Speed Config: https://hastebin.com/udequzinut.bash
Take note of my item scalar. WAY above default. So yeah

Server version: TacoSpigot 1.8.8
AAC version: 3.1.6b1
ProtocolLib version: 4.2.1
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by Foulwerp** [comment]
Doesn't seem to be just teleporting into water, but jumping into water and moving around also.

**Comment by SnakeDaoust1232** [comment]
Weird, sure it will be fixed shortly.

**Comment by konsolas** [comment]
Will be hotfixed today

**Comment by konsolas** [comment]
3.1.6-b2
