### ISSUE TITLE
Error EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by Fages1** [konsolas/AAC-Issues#629]
Core information

Server version: paper 1.8.8

AAC version: 3.1.6

ProtocolLib version: last

ViaVersion version: last

ERROR: https://hastebin.com/epuvuxomav.vbs

Plugins:
![image](https://cloud.githubusercontent.com/assets/28231388/25567320/4a212f18-2e04-11e7-8bba-6559a4564be1.png)

**Comment by konsolas** [comment]
Please check your protocollib version.

**Comment by konsolas** [comment]
Closing - issue with user setup. Request this be reopened or join discord if downloading the correct ProtocolLib version does not fix the issue.
