### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by campzazathelord** [konsolas/AAC-Issues#631]
im getting this console error 

http://imgur.com/a/AeNi1
http://imgur.com/a/hjbMB
http://imgur.com/a/ESY1d

spigot 1.8.8 
aac 3.1.6b2
protocolib 4.2.1
plugi  list
http://imgur.com/a/JX3jP
http://imgur.com/a/sXWT4

**Comment by CeIebrimbor** [comment]
Could you try to run with ProtocolLib 4.2.0 ([build 341](http://ci.dmulloy2.net/job/ProtocolLib/341/)) and see if this still occurs?

**Comment by campzazathelord** [comment]
i think its fixed :)

**Comment by konsolas** [comment]
Closing due to incorrect protocollib version.
