### ISSUE TITLE
Fly FP and Velocity Bug | 3.1.6b2

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#633]
Video: https://www.youtube.com/watch?v=XXNI_Bq6RV8

Only happends when you crash a boat.

Core information

Server version: TacoSpigot 1.8.8
AAC version: 3.1.6b2
ProtocolLib version: 4.2.1
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by i9hdkill** [comment]
Same on 
spigot 1.11.2
AAC version: 3.1.6b2
ProtocolLib: Build354
ProtocolSupport: Build41

**Comment by Janmm14** [comment]
This looks like an issue related to AACAdditonPro <1.9 combined with AAC >3.1.5b3

**Comment by CeIebrimbor** [comment]
@Janmm14 
This issue was opened 2 days before AAC+ 1.9 existed.

**Comment by CeIebrimbor** [comment]
AACaddition v1.8.2 and AAC v3.1.5-b3 are still the recommended stable builds.

As I have said in other issues reports, downgrading is not a permanent solution, just trying to be helpful in the meantime.

**Comment by Janmm14** [comment]
>@Janmm14
This issue was opened 2 days before AAC+ 1.9 existed.
by @CeIebrimbor 

Not really relevant here?

I understand that the issue was valid at some point in the past.

Also I'm not closing it because AACAdditioPro was not mentioned by @i9hdkill.

**Comment by SnakeDaoust1232** [comment]
I don't have addition pro installed.

**Comment by i9hdkill** [comment]
We neither.

**Comment by CeIebrimbor** [comment]
@Janmm14
I removed my comment about versions the moment I hit "comment" (once I realized I misread yours). 

Why did you quote a non-existent comment?

**Comment by Janmm14** [comment]
@Celebrimbor I did not noticed it was removed @Celebrimbor.

I guess AAC 3.1.6 needs some important fixes.

**Comment by Justinis77** [comment]
Same 1.8.8 AAC:3.1.6b2 Aacad:1.9 pls fix

**Comment by Janmm14** [comment]
Use 3.1.5b3 for now I'd say

**Comment by konsolas** [comment]
-b3.
