### ISSUE TITLE
Getting hit out of Cobwebs flags for fly

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#635]
You get set backed for example to x: 0.669 y: 0 z: 0.042 (relative coords)
you would get hit into -x -z direction in my case, cobweb at x: 1 z: 1
you get contineously set backed

example verbose:
`* [AAC] Janmm14 failed Fly: moved unexpectedly: 0,275 (0,343->0,333 / -n-n16) [ping:0 tps:19.99] VL:187`

**Comment by Minemaniak** [comment]
1st anniversary of this issue now :D
