### ISSUE TITLE
Feature | ToggleSneak

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#636]
Maybe make is so we can disable the part of the speed check that checks to see if you are sneaking and walking/sprinting. To allow support for a plugin like this. A plugin like this is used on factions servers so players with access can be a little more hidden from the people around their base.

https://www.spigotmc.org/resources/togglesneak.5333/

**Comment by CeIebrimbor** [comment]
Better to tie into AAC's API for their side so you don't need to cripple the Speed check to allow that plugin's function. Assuming you would wish to ignore sneak speed in the config to allow that modified "sneak". Maybe I misunderstood the request or plugin.

**Comment by SnakeDaoust1232** [comment]
I see

**Comment by CeIebrimbor** [comment]
Just a recommendation, but I would assume this feature request would remain open for months (ignored)... XD
