### ISSUE TITLE
AAC block attack after using Fishrod

### ISSUE THREAD

**Issue by jiangdashao** [konsolas/AAC-Issues#638]
PLEASE read the guidelines for contributing which is linked above.
### Issue description
After play using fishrod to shot another player,he will be blocked attack action in few seconds by AAC.

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.

We can't read your thoughts.

Please include details like:
* AAC logs / Full console error
* Video of the bug / bypass, best with verbose chat output
* The ingame name of the involved players

### Core information
**Server version**: 1.8.8

**AAC version**: 3.1.6 b1

**ProtocolLib version**: 4.1.2

**Plugin list**: ,ProtocolLib,Viaversion,AAC,Vault,pex

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.0.4

**BungeeCord plugins**:  MultiLobby

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here:

**Comment by geNAZt** [comment]
Please give verbose Logs into the issue. We can't reproduce that behaviour without it

**Comment by craftrise** [comment]
I have same problem.

**Comment by konsolas** [comment]
insufficient information.
