### ISSUE TITLE
Separate permission for /aacstaffnotify command

### ISSUE THREAD

**Issue by MedicOP** [konsolas/AAC-Issues#639]
Can a separate permission be added for use of this command besides aac.notify? It doesn't really make sense to let staff members be able to use this command, especially if you already have in-game staff chat.

The command should only be used by AAC's config to broadcast possible hackers.

Or perhaps make it a config option?

**Comment by CeIebrimbor** [comment]
While it is pointless to allow the use of this command, it is also harmless. If it is harmful, then you should reevaluate who you trust to be staff xD
