### ISSUE TITLE
Liquidbounce 25.2 Bypasses

### ISSUE THREAD

**Issue by AirBrunt** [konsolas/AAC-Issues#640]
Aac aint detecting players hacks when they use liquidbounce 25.2.
Please include details like:
* No errors
* just use that client and youll see
* AirBrunt, DarcoXD...

### Core information
**Server version**: 1.11.2

**AAC version**: 3.1.6-b2 also tried 3.1.5

**ProtocolLib version**: 4.2.1

**Plugin list**: aac, conditionalcommands...

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here:

**Comment by CeIebrimbor** [comment]
Please be descriptive with the types of bypasses you are referring to (i.e. Killaura, b-hop, highjump, etc).

Also describe certain conditions that maybe be required to bypass (i.e. Killaura if reach is <4 or highjump up to 5 blocks high).

Or...
Shoot a quick video of bypasses if you can.

**Comment by AirBrunt** [comment]
I'm going to test it on the test server but it bypasses everythin on the list but nofall :/

**Comment by Janmm14** [comment]
In internal tests liquidbounce killaura got detected.

**Comment by CeIebrimbor** [comment]
I would like to add that detected could also mean "detected eventually". Just because a client can land 8-12 hits on a single entity, does not equate to a full bypass. 

30+ seconds of combat against multiple entities = Very noteworthy...

On a side note, 1.9+ combat is expected to be much slower in detection with them landing less illegal hits in slower patterns.

**Comment by Janmm14** [comment]
> I'm going to test it on the test server but it bypasses everythin on the list but nofall :/
> by @AirBrunt

How do you know whether it bypasses if you did not test it on the test server?

Many clients, also LiquidBounce, do have modules containing bypasses for older versions of AAC which are already patched.

**Comment by konsolas** [comment]
Closing due to insufficient information.
