### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by jQuery0** [konsolas/AAC-Issues#642]
Server version: Spigot 1.10.2
Plugins: Only ViaVersion and ProtoclLib

Error: https://pastebin.com/7K9QxrF1 (idk, this gets generated after the crash)
AAC latest version 3.1.6 b2

It crash my server randomly and then generates that file. It's mostly happens when someone is detected for hacking (speed/fly/killaura/badpackets)

**Comment by CeIebrimbor** [comment]
Version of ProtocolLib?

**Comment by jQuery0** [comment]
Latest version ^
It also happens when I spam /aacreload in-game

**Comment by CeIebrimbor** [comment]
Get ProtocolLib [4.2.0](http://ci.dmulloy2.net/job/ProtocolLib/341/) and request reopen if it re-occurs with the correct version of ProtLib.

Don't spam /aacreload ;)

**Comment by jQuery0** [comment]
Still happens with 4.2.0

**Comment by konsolas** [comment]
Definitely not valid. Check your version.

**Comment by jQuery0** [comment]
Re-downloaded and it worked
