### ISSUE TITLE
FASTPLACE check cancel doesn't work

### ISSUE THREAD

**Issue by wasder** [konsolas/AAC-Issues#643]
```  
@EventHandler
    void onAntiCheat(PlayerViolationEvent event)
    {
        if ((event.getHackType()== HackType.FASTPLACE || event.getHackType()== HackType.INTERACT) && beaconPlacers.contains(event.getPlayer()))
        {
            RandomCraft.tmpLog("cancel hack check"); //We actually got this text in console
            event.setCancelled(true);
        }
    }
```
But we still got FASTPLACE check fired on player. We are trying to create a 9x9x5 pyramide with BlockPlaceEvent by player

**Comment by konsolas** [comment]
Are you sure you registered the listener properly? Add debug messages. Is the event called?

**Comment by wasder** [comment]
We actually have a debug message in the code and it's fired several times, but then AAC blocks it and it is not called anymore.

**Comment by konsolas** [comment]
It's not possible for a check to be fired without an event being called. The only way a violation is created involves the firing of an event in code. 

Can you describe what happens with verbose enabled?
What happens after "cancel hack check"? Do you get a FastPlace entry in the logs?

**Comment by wasder** [comment]
1) We actually create and call BlockPlaceEvent in code, cause it's a safe way to allow different protection plugins (or else) to cancel the event.
2)  It logs the same number of times ``cancel hack check``, as blocks were actually placed, but not how it should be.
3)  We actually have ``FastPlace entry in the logs``
4) If we get this code in ``AACAPIProvider.getAPI().disableCheck(HackType.FASTPLACE);`` and ``AACAPIProvider.getAPI().enableCheck(HackType.FASTPLACE);``, then the building is placed correctly.

**Comment by CeIebrimbor** [comment]
@konsolas Bump

**Comment by CeIebrimbor** [comment]
Please open a new issue (and reference this) if you are still not able to implement the API properly and to your liking. Maybe a Feature request in order to get something added that is easier to accomplish your needs?
