### ISSUE TITLE
Sprinting and Jumping is detected as fly video proof.

### ISSUE THREAD

**Issue by Fonzee9** [konsolas/AAC-Issues#648]
https://www.youtube.com/watch?v=e-QKLrzOF4U

**Comment by SnakeDaoust1232** [comment]
Did you use a boat recently? I made a issue that looks similar. If not, remove aacadditionpro.. For some reasons the plugins aren't meshing properly.

**Comment by Fonzee9** [comment]
No i didn't use a boat recently

**Comment by SnakeDaoust1232** [comment]
https://github.com/konsolas/AAC-Issues/issues/633
It just looks like this a lot. Thats all

**Comment by Fonzee9** [comment]
Hey everyone, A temp fix for this is to disable Fly check in AAC and then put nocheatplus on your server and disable all checks in nocheatplus except fly so that way your server will be playable.

**Comment by Justinis77** [comment]
me too pls help

**Comment by Justinis77** [comment]
PLS fix

**Comment by Justinis77** [comment]
https://pastebin.com/k58zmW4k
Newest AAC Version

**Comment by Janmm14** [comment]
Using 3.1.5b3 is recommended atm due to the rewrite of movement in 3.1.6 still contains issues.

**Comment by Rerd** [comment]
No problems with default config...
https://gyazo.com/729e24ebba61d0dd3b3790b98129a5c5
https://gyazo.com/3ec03445b907e1231777c9d65d1ee731

**Comment by konsolas** [comment]
-b3.

**Comment by Janmm14** [comment]
@Justinis77 3.1.6b2 too :/

Should be fixed in b3 btw by fixing some inconsistent handling of teleport attempts.
