### ISSUE TITLE
/aacstaffnotify command does not show message for players with permission AAC.notify

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#649]
/aacstaffnotify command does not show message for players with permission AAC.notify

Server versions 1.8.8, 1.11.2
Latest AAC

**Comment by CeIebrimbor** [comment]
Permission plugin?

**Comment by Toshka17** [comment]
Own plugin

**Comment by konsolas** [comment]
Testing with PEX, the permission works. Check that your permissions plugin is working correctly.
