### ISSUE TITLE
v3 Ghosthand sensitivity

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#65]
https://giphy.com/gifs/l2JhnF71hsmoITgGc

**Comment by konsolas** [comment]
Ghosthand is similar to NCP's BLOCKINTERACT_VISIBLE, which throws an alert every time your cursor changes block. AAC does some suppressing of these, but the odd alert is unavoidable due to an inherent bug in the client.

**Comment by CeIebrimbor** [comment]
Does it cancel and hit?

**Comment by konsolas** [comment]
We have cancel_vl in there.
