### ISSUE TITLE
Velocity false positive

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#651]
Floating about a block above water and getting hit by an iron golem causes for false velocity flags. I was able to reproduce this on 1.8 - 1.11, on the most recent AAC version.

https://youtu.be/Y6Kzm02xgh4

**Comment by SnakeDaoust1232** [comment]
Does it work if you are not flying?

**Comment by Matthew777k** [comment]
Nah, I only seem to be able to reproduce it when I'm flying.

It's not an important issue at all. A few of our skyblock players noticed this happening to them so I just figured I'd report it.

**Comment by konsolas** [comment]
Velocity will no longer check flying players.
