### ISSUE TITLE
Snow FP

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#653]
Info:
- Running over snow flags for speed and fly.

Video: https://www.youtube.com/watch?v=u-nvotn-VT4&feature=youtu.be

Speed Config: https://hastebin.com/oqexukowow.bash
Fly Config: https://hastebin.com/gokucopuwo.bash

Core information

Server version: Spigot 1.8.8
AAC version: 3.1.6b3
ProtocolLib version: 4.2.1
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by Photon-GitHub** [comment]
Please test again on latest version with a vanilla client.

**Comment by SnakeDaoust1232** [comment]
Yep, still works with a vanilla client.

Tested on 1.8.8

**Comment by SnakeDaoust1232** [comment]
@Photon-GitHub Can you take the insufficient info off of this please.
