### ISSUE TITLE
Found a bug with a plugin

### ISSUE THREAD

**Issue by danielm175** [konsolas/AAC-Issues#655]
Hi,

This plugin here:  https://www.spigotmc.org/resources/customenchantments-1-7-1-11.18408/

Kicks people for mining or swimming fast while they got custom enchants on can you please fix this?

**Comment by SnakeDaoust1232** [comment]
It's up to that Dev to make his plugin compatible with AAC.

**Comment by danielm175** [comment]
Will he see this message?

**Comment by SnakeDaoust1232** [comment]
You have to take it to the Dev of customenchants

**Comment by CeIebrimbor** [comment]
Needs to be attacked by the Custom Enchatnt dev using AAC's public API.
