### ISSUE TITLE
Flight in water bypass?

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#66]
When you activate flight in water, it doesn't detect? (Kind of Minor) [https://www.youtube.com/watch?v=wbgFz_rotrA](url)

**Comment by Rqcco** [comment]
https://www.youtube.com/watch?v=wbgFz_rotrA The link above doesn't work for some reason, at-least for me.

**Comment by konsolas** [comment]
For some reason, AAC does not handle vertical water movement. 

This will be added.

**Comment by konsolas** [comment]
Written and tested.

**Comment by Rqcco** [comment]
#242
