### ISSUE TITLE
Weird bug with phase. Crashing clients?

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#660]
Info:
- Phase causes a client to crash.

Video: https://www.youtube.com/watch?v=S18iiAf2JUg&feature=youtu.be

Phase Config: https://hastebin.com/apapakukux.bash

Core information

Server version: Spigot 1.11
AAC version: 3.1.6b4
ProtocolLib version: 4.2.1
Plugin list: https://gyazo.com/300a8f5912cae4cfe4440ab99aac544d

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.25
BungeeCord plugins: https://gyazo.com/f67ee51a863c1cacc01a34b2fa40da39

**Comment by Janmm14** [comment]
Does it happen without AAC?

**Comment by SnakeDaoust1232** [comment]
No increased CPU usage and no it doesn't happen without AAC installed. I was forced to switch to spartan ACuntil it gets fixed.

**Comment by konsolas** [comment]
This _should_ no longer occur as the safety checks teleport the client.

There is a difference between the phase check and the speed safety checks - clients may glitch into a block and trigger Phase, but they are unlikely to trigger the safety checks which require them to move at 2000 blocks/sec. 

-b5

**Comment by SnakeDaoust1232** [comment]
@konsolas Not fixed. Still an issue with 3.2.1b1. It happends not only with phase, but with any movement check i believe. I was flagged while i was in the air, and since i was glitched in the same spot, it kicked me for flying, when i wasnt flying at all. It just "froze" my client in place.

**Comment by Janmm14** [comment]
VL logs again maybe?

**Comment by SnakeDaoust1232** [comment]
@Janmm14 The logs dont show much. As soon as a hack flags, just once, it lags the client out.
