### ISSUE TITLE
Depth Strider = Speed (same report with every movement rewrite)

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#665]
_This is actually a copy of an old report, but the detection bug is back in the same fashion it was months ago._

Depth Strider Incompatibility is back. Now at any enchantment level. Speed potions make it climb in VL faster, but not required to get fps.

https://youtu.be/WU16Q9CTyoI

PaperSpigot 1.11.2
AAC 3.1.6-b4
ProtLib 4.2.1
Default config w/ verbose on (regened for test)

No Protocol Hacks or plugins outside AAC, ProtLib and Permissions plug.

**Comment by konsolas** [comment]
-b5
