### ISSUE TITLE
CRITICAL NETWORK ERROR....

### ISSUE THREAD

**Issue by campzazathelord** [konsolas/AAC-Issues#669]
im getting a CRITICAL NETWORK ERROR and aac disables. i wondered if its by dedicated server network problem so i tried it on my home computer and the same thing happened..... so it;s the problem with the plugin not my server internet :(

**Comment by campzazathelord** [comment]
spigot 1.8.8
aac latest
protocollib 420
CRITICAL NETWORK ERROR check your hosts file. thats all it shows.

**Comment by HoverEpic** [comment]
Seems to be same as [#618](https://github.com/konsolas/AAC-Issues/issues/618).
I have this issue too on a Windows workstation.

**Comment by campzazathelord** [comment]
:(( it was working fine yesterday but now it doesnt work anymore. my internet connections are working fine. :(

**Comment by konsolas** [comment]
#668
