### ISSUE TITLE
Phase Perhaps??

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#67]
Basically, I don't really know if this counts as "phase", but I'm just going to put this up, since this all suggestions. When you jump into a block your able to get stuck in it, and jump to the other side. This isn't really major as well.  :)

https://www.youtube.com/watch?v=lkf558D9xUo

**Comment by Rqcco** [comment]
Once again, don't quote me on this.

**Comment by konsolas** [comment]
Going to mark this as wontfix since trying to handle glass pane hitboxes would be a waste of time, and require more processing.

**Comment by Photon-GitHub** [comment]
You can phase through the glass panes with this. I will reopen this issue, feel free to close it again if you think it is not important.

**Comment by Janmm14** [comment]
You could maybe look into minecraft coder pack decompilation to get the hitboxes correctly.

**Comment by v0idst4r** [comment]
@Janmm14 Mod coder pack* ;)

**Comment by konsolas** [comment]
Patched.

**Comment by v0idst4r** [comment]
konsolas on fire today
