### ISSUE TITLE
Velocity Bug | 3.1.6b4

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#670]
Info:
- When you pearl into a block it glitches you out and bans you for velocity.

Video: https://www.youtube.com/watch?v=xkzP2wL0Jho&feature=youtu.be

Core information

Velocity Config: https://hastebin.com/goleyufofo.bash

Server version: Spigot 1.8.8
AAC version: 3.1.6b4
ProtocolLib version: 4.2.1
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by konsolas** [comment]
#623
