### ISSUE TITLE
Switch to async update checker.

### ISSUE THREAD

**Issue by HoverEpic** [konsolas/AAC-Issues#671]
Hi AAC developers, I came back for the [issue #668](https://github.com/konsolas/AAC-Issues/issues/668), could you make the update checker asynchrone, there's no need to block server startup during response (or non response) time. In near future, we plan to open a Minecraft server with multiple spigot servers, and server startup time is very important for us, I've already made a local patch to avoid update check (patched host), but it's not a perfect solution.

Regards, a happy server owner (and AAC user).

**Comment by Janmm14** [comment]
As far as I know the check is already async.

**Comment by HoverEpic** [comment]
You're right, but the real problem is update checker wait for the http api response to enable the plugin, during this time, the server is online but the AAC engine if off and can't accept players. A possible solution can be check update async from the AAC startup or/and reduce HTTP timeout.

**Comment by Janmm14** [comment]
The update checking process includes security checks. Those are meant to be done before AAC starts up.

**Comment by CeIebrimbor** [comment]
This is clearly not something the developer is interested in pursuing at the moment. Closing for now.
