### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by TheFates123** [konsolas/AAC-Issues#672]
When I turn on the server with AAC ,its suddenly stop when loading plugins . When I turn on the server without AAC , the server runs normally !

The error : http://i.imgur.com/lCN3U9h.png

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 3.1.6-b4

**ProtocolLib version**: 4.2.0

**Plugin list**: AAC , EssentialsX , AACAdditionPro , PNCP , NoCheatPlus , PlayerVault , ProtocolLib , SkinsRestorer , ConditionalCommands

**Comment by konsolas** [comment]
This is not a problem with AAC. Make sure there has been no file corruption with craftbukkit/etc.
