### ISSUE TITLE
Could not pass event FakeBlockBreakEvent

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#679]
### Issue description

Continuous console spam with the following error:
https://gist.githubusercontent.com/andrewkm/93d8b24a2cbe90c71706bee643723d4f/raw/a814a09c50d43d0cb6f3450d5388f556c7d4ddd8/gistfile1.txt

### Core information
**Server version**: 1.11.2 - Spigot Build 1251

**AAC version**: 3.1.6-b5

**ProtocolLib version**: 4.2.1 Build 354

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by andrewkm** [comment]
Looking at the error it seems there is some problem with McMMO's compatibility with AAC. I did not experience this on previous AAC versions I believe though.

**Comment by CeIebrimbor** [comment]
Latest McMMO? I have not had this issue on my 1.11 server with recent builds of McMMO. Though, I am likely a few builds behind.

**Comment by andrewkm** [comment]
We are running the following McMMO build:

https://ci.drtshock.net/job/MCMMO/183/

**Comment by konsolas** [comment]
The error is incomplete, I need the full "Caused by" section. It may appear earlier in the log file.

**Comment by andrewkm** [comment]
@Konsolas here is a bigger section of the logs. Exactly when the console explosions started happening. If I was to paste the entire thing it would be like 5000x bigger (Not even exaggerating).

https://gist.github.com/andrewkm/5c906a93c6b59ab7fcb161991a6e7e77

Let me know if you want any further information.
