### ISSUE TITLE
Could not pass event BlockBreakEvent

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#680]
### Issue description

Continuous console spam with the following error:
https://gist.githubusercontent.com/andrewkm/c2b94e551b2de5fa27a65ee7004f76a8/raw/fa59eb61520d57b9f5ebe037ec3d56f8ee217402/gistfile1.txt

### Core information
**Server version**: 1.11.2 - Spigot Build 1251

**AAC version**: 3.1.6-b5

**ProtocolLib version**: 4.2.1 Build 354

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
The error is incomplete, I need the full "Caused by" section. It may appear earlier in the log file.

**Comment by andrewkm** [comment]
@Konsolas here is a bigger section of the logs. Exactly when the console explosions started happening. If I was to paste the entire thing it would be like 5000x bigger (Not even exaggerating).

https://gist.github.com/andrewkm/5c906a93c6b59ab7fcb161991a6e7e77

Let me know if you want any further information.
