### ISSUE TITLE
Constant full server crashses. java.util.NoSuchElementException. "Exception ticking world entities"

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#681]
### Issue description

Continuous server crashes with the following error:
https://gist.github.com/andrewkm/b4ed1b61741222dd621d5aa90846886a
&
https://gist.githubusercontent.com/andrewkm/df3a5ee5e58bac774d546cc6eb13ccae/raw/43bd1c7b4548163b49871247d879d135de4c016f/gistfile1.txt

Id like to reference this issue: https://github.com/konsolas/AAC-Issues/issues/551
It seems the above bug is back somehow. It's getting quite bad.

### Core information
**Server version**: 1.11.2 - Spigot Build 1251

**AAC version**: 3.1.6-b5

**ProtocolLib version**: 4.2.1 Build 354

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by andrewkm** [comment]
Thought I'd link this from md_5 if it's any help:
http://i.imgur.com/vkQ6eV0.png

**Comment by Janmm14** [comment]
Such things were thought to be resolved completely in the last updates of AAC.

**Comment by andrewkm** [comment]
Seems like they are not...

**Comment by MedicOP** [comment]
I reported the original issue #551

The bug may have been reintroduced in 3.1.6, as I'm still on 3.1.5-b3 and have not experienced any crashes.

**Comment by andrewkm** [comment]
I can confirm that 3.1.5-b3 did not have this issue as I was on this version for quite a while with no problem.

**Comment by OWERLORD01** [comment]
I had this issue in build 3.0.2, but only in world end...

**Comment by andrewkm** [comment]
Interesting, I too have the end world on my server, however not sure what is causing the initial crash.

**Comment by MedicOP** [comment]
It's not the end world. I had the crashes on many servers even though none of them had an End world

**Comment by andrewkm** [comment]
Hm interesting. Really hope this gets solved.

**Comment by andrewkm** [comment]
Looks like it just happened again, this time during our peak hours :(
Really bad issue, wish I can somehow get more information regarding it for you.

The log this time:
https://pastebin.com/raw/u5Kt3dQL

**Comment by andrewkm** [comment]
I'm going to remove AACAddition Pro and see if perhaps the crashes stop. This will at least rule out that it is not AACAddition Pro causing it.

**Comment by MedicOP** [comment]
Did you find anything?

**Comment by andrewkm** [comment]
Yes, I have pretty much confirmed with all certainty that this issue stems directly from AAC Addition pro. After removing it, I have not yet experienced a single crash. Meanwhile when AAC Addition Pro was on our server, we crashed once a day. I am unfortunately going to be dropping AAC Addition pro as it's been nothing but trouble for us :( Would love to revisit the usage of it in the future should these issues be resolved.

CC: @konsolas @CeIebrimbor @Photon-GitHub

**Comment by konsolas** [comment]
Moved to AACAdditionPro issue tracker. Issue remains here for reference.
