### ISSUE TITLE
Elytra fp

### ISSUE THREAD

**Issue by jQuery0** [konsolas/AAC-Issues#682]
**Information**
When spamming space bar (to get a boost with the elytra) you get flagged for speed and fly.

**Video:**
https://streamable.com/mb9sg

Server version: Spigot 1.9.4
AAC version: 3.1.6b5
ProtocolLib version: 4.2.1
Plugin list: ViaVersion, ProtocolLib, AAC

**Comment by CeIebrimbor** [comment]
Make sure you use ProtocolLib 4.2.0 w/ your 1.9 server.

**Comment by jonesdj1** [comment]
yeah happens on my latest 1.11.2 server with latest ProtocolLib

**Comment by CeIebrimbor** [comment]
Closed in favor of #773
