### ISSUE TITLE
Screen Glitching.

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#683]
### Issue description

Many users have been complaining about a screen glitching issue ever since adding AAC:
https://www.ecocitycraft.com/forum/threads/loading-bug.166174/
All the reports can be seen above. There are screenshots and other information in that thread.

### Core information
**Server version**: 1.11.2 - Spigot Build 1251

**AAC version**: 3.1.6-b5

**ProtocolLib version**: 4.2.1 Build 354

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by andrewkm** [comment]
I believe this has something to do with the fake entity that teleports to you to check for Kill Aura. The reason I say this is because players specify that they can see the entity at times, sort of as if it was teleporting to you.

**Comment by Janmm14** [comment]
1) AAC does not have visible entities
2) Are you using AACAdditionPro's pingspoof check?
3) Try using AAC 3.1.5b3

**Comment by andrewkm** [comment]
The AACAddition Pro Pingspoof check is disabled - issue continues to occur.

**Comment by OWERLORD01** [comment]
Disable AACAddititionPro Freecam check and you'll be good :)

**Comment by CeIebrimbor** [comment]
@andrewkm 
AACaddition's Freecam check physically moves players on the Y axis to reset position. Unfortunately, since Freecam is undetectable, all players that stand still will see this happen. My config delays it, but you can delay further or disable the check. Depends on the importance of blocking Freecam vs the annoyance.

**Comment by andrewkm** [comment]
Thank you @CeIebrimbor - I will be disabling the Freecam check.

**Comment by andrewkm** [comment]
@CeIebrimbor my users have all alerted me that even with freecam disabled, this issue persisted. I have now removed AACAddition Pro to monitor how it goes without the use of that plugin, and to see if using just AAC by itself would solve the issue.

**Comment by CeIebrimbor** [comment]
@andrewkm Is this the same report as the issue over in AAcaddition regarding glitched chunks? I thought you were referring to the slight movement of players every second if they stand still.

**Comment by andrewkm** [comment]
@Celebrimbor - this issue can remain closed. It is an AACAddition Pro issue CC: @Photon-GitHub 
Removing AACAddition Pro has completely solved our issues and users report no problems.
