### ISSUE TITLE
Interaction false positive

### ISSUE THREAD

**Issue by OWERLORD01** [konsolas/AAC-Issues#684]
## Issue description

I have very bad false positive with Interaction check...
here it is... https://youtu.be/xkG2V0PWLtg

So, when someone is interacting with a map that is
probably a few blocks away (but legit player still can reach it)
Interaction is detecting something unusual... Please
check the vid and hope you'll fix it soon.

P.S. Sorry for using hacked client, but I turned everything
off, and my legit players are getting flagged too.

Please include details like:
* https://youtu.be/xkG2V0PWLtg

## Core information
**Server version**: TacoSpigot 1.11.2 Build #101

**AAC version**: 3.1.6-b5

**ProtocolLib version**: Latest

**Plugin list**: not very important.

## Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: N/A

**ProtocolSupport version**: Latest

**ViaBackwards version**: N/A

**Comment by CeIebrimbor** [comment]
Make sure you don't actually use the "latest" ProtocolLib on 1.11.2. Use 4.2.1.

**Comment by OWERLORD01** [comment]
It's 100% not the problem with protocollib...

**Comment by CeIebrimbor** [comment]
Which is why I labeled as "bug" instead of "invalid". I was **not** informing him the improper version of ProtocolLib was the cause, just trying to be proactive with helping while labeling the issue.
