### ISSUE TITLE
Compatibility Request for Schematica

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#686]
Please consider adding hook to [Scematica Mod](https://minecraft.curseforge.com/projects/schematica) when it is applied server-side. Many servers use this and it requires them to disable portions of Interact, Fastplace and Speed in most cases.

**Comment by SnakeDaoust1232** [comment]
I agree.

**Comment by Janmm14** [comment]
Is there any spigot plugin for that? This looks like its just a client-side modification.

**Comment by jonesdj1** [comment]
the mod might sent a message packet

**Comment by Janmm14** [comment]
Is there some documentation for that?

**Comment by CeIebrimbor** [comment]
Source code?
https://github.com/Lunatrius/Schematica

**Comment by CeIebrimbor** [comment]
Giving up
