### ISSUE TITLE
/aacaddkickthreshold Command

### ISSUE THREAD

**Issue by ChavitaHD** [konsolas/AAC-Issues#687]
Possibly a new feature to allow the broadcast of the kick to be sent via the pre-existing ban/kick management plugin. (EX: LiteBans)

We can use our own multiline and customized kick message, while still counting the kicks towards banning the user.

**Comment by SnakeDaoust1232** [comment]
Dont use /aackick then. Just use /kick

**Comment by ChavitaHD** [comment]
"while still counting the kicks towards banning the user."

**Comment by SnakeDaoust1232** [comment]
Oh I didn't see that sorry.

**Comment by Janmm14** [comment]
Easist would be to have a command which just highers the kick threshold.

**Comment by ChavitaHD** [comment]
How would I do this?

This is new to me, sounds great!

**Comment by OWERLORD01** [comment]
There's option for it - aackick_broadcast: true

**Comment by konsolas** [comment]
Should be done with an alternative plugin. The aac punishment system is not designed to be comprehensive.
