### ISSUE TITLE
Phase mining fp

### ISSUE THREAD

**Issue by OWERLORD01** [konsolas/AAC-Issues#689]
## Issue description

When players are mining or digging down,
phase is detecting them... Here is the vid :)
https://youtu.be/wHugv9YQynE

## Core information
**Server version**: TacoSpigot #101, of course

**AAC version**: latest

**ProtocolLib version**: latest

**Plugin list**: I don't have any plugin that is effecting mining in any way

## Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: latest

**ViaBackwards version**: none

**BungeeCord plugins**: none

### Thanks

If the video is not working, please tell me :P

**Comment by CeIebrimbor** [comment]
Phase never kicks, so this will be a low priority issue.

**Comment by OWERLORD01** [comment]
> Phase never kicks, so this will be a low priority issue.

Yes, but it's annoying to players..

**Comment by CeIebrimbor** [comment]
Hmm, I didn't really see the annoyance. Was the player doing anything but falling down? I agree it's a bug and should be fixed, but just trying to prioritize based on severity. Critical comes first, then standard, then unimportant. If you think it is more critical (e.g, It is throwing players off their nerd poles, glitching players up and causing fly detection, etc), please say so and provide this evidence.

**Comment by SnakeDaoust1232** [comment]
@CeIebrimbor What he means by "annoying" is most likely people will get stuck in the air and will have to relog to fix them being stuck.

**Comment by CeIebrimbor** [comment]
@SnakeDaoust1232 What part of the video suggested this was the case? I watched with sound of (I'm at work), was it explained in voice audio?

From just watching the video w/o sound, it looks like a 90% harmless detection unless the config is set to kick, which is never advised for Phase.

**Comment by SnakeDaoust1232** [comment]
From past experience with phase thats just the issues that ive had. I think we've gotta wait for this guy to clarify.

**Comment by OWERLORD01** [comment]
@CeIebrimbor idk, but I set it to autoban players xD
It's detecting someone when he's mining and he must it teleports him, then he got stuck in this block for around 0.5 or 1 second, and then, he can move again. It happens only if player is very close to a block that he's mining. I want anticheat that is able to autoban players, so please fix it!
### Thanks

**Comment by CeIebrimbor** [comment]
@OWERLORD01 
It is unfortunate that you set Phase to ban when the default doesn't even kick. There are far too many situations, some known, most not, that cause Phase detection. Trap doors, claimed land(plugins), gltiched blocks, legal teleports, etc. Phase should never be set to run kick/ban commands, and if it is, it should be the default /kick command so it does not contribute to autoban.

This will remain an open issue because of the minor hovering of players, but will not become a priority issue unless substantial evidence is provided that makes the issue more than a harmless verbose.

**Comment by konsolas** [comment]
Vanilla minecraft would have a similar effect with "moved wrongly".
