### ISSUE TITLE
v3 Default config

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#69]
Request that you make these items off(false) by default. That way an owner can _choose_ to enable these surprising and in most cases undesirable features.

**1.** aackick_broadcast (see #68)
**2.** kill_loggers (remove entirely?)
- This one is rough when the owner has yet to config to their liking and false kicks start murdering all their players.

**3.** spam check (remove entirely?)

**Comment by konsolas** [comment]
Spam check will stay in there since I find it quite useful at times, without any major problems. The other suggested changes have been applied to the default config.
