### ISSUE TITLE
Frost Walker False Positive

### ISSUE THREAD

**Issue by OWERLORD01** [konsolas/AAC-Issues#692]
## Issue description

When using frost walker and jumping, AAC
can sometimes kick players (if reduce delay is 20, by default)
In this video, reduce delay is only 2, so it's not kicking them.
https://youtu.be/tucpHNPchMQ

## Core information
**Server version**: TacoSpigot 1.11.2 #101

**AAC version**: latest

**ProtocolLib version**: latest

**Plugin list**: nothing special to effect frost walker, I dont have any custom enchantments plugin too.

## Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: none

**ProtocolSupport version**: Latest

**ViaBackwards version**: none

**Comment by SnakeDaoust1232** [comment]
Frost walker is a custom enchant?

**Comment by CeIebrimbor** [comment]
@SnakeDaoust1232 
O.o

Do you even Minecraft?

**Comment by CeIebrimbor** [comment]
@OWERLORD01 
For the record, "latest version" for ProtocolLib = Incompatible with everything that is AAC and 1.11. I assume you mean 4.2.1 (build 354).

**Comment by SnakeDaoust1232** [comment]
@CeIebrimbor Wait, is "frost walker" a 1.12 enchant or something. I've rarely ventured past 1.8 jars. xD

**Comment by jonesdj1** [comment]
@SnakeDaoust1232 No like a 1.9 enchant lmao its old

**Comment by SnakeDaoust1232** [comment]
I'm actually dumbfounded. I didn't even know. What other enchants are out there like this?

**Comment by CeIebrimbor** [comment]
User using leaked version of plugin, so closing this (and all issues from user).
