### ISSUE TITLE
Glitching bug on every lagback (in water)

### ISSUE THREAD

**Issue by OWERLORD01** [konsolas/AAC-Issues#694]
## Issue description

When player gets detected so many times,
hes position gets stuck, but he originally can move, but
he counts he's not moving to other players. Also, AAC
starts detecting him for fly, and velocity, as he can not move (he can, but he's original possition is stuck)

### Sorry for my bad english :P
Here's vid https://youtu.be/TjlfKA_Jqxs

## Core information
**Server version**: TacoSpigot #101

**AAC version**: latest

**ProtocolLib version**: latest

**Plugin list**: Do I really need to them you all of them? (around 70)

## Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: none

**ProtocolSupport version**: latest

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by SnakeDaoust1232** [comment]
Once again. Thats a custom enchant. But regardless... the method of FP is very similar to my FP.

**Comment by jonesdj1** [comment]
@SnakeDaoust1232 No Its a minecraft enchantment since like 1.9

**Comment by OWERLORD01** [comment]
This is very critical bug, please fix it soon!

**Comment by OWERLORD01** [comment]
EDIT: When someone is in water and he got TELEPORTED down. He's no longer checked. He's original position is in water but player think that he can move, but he's in water for other players.

Proof: when you get teleported down, you can hack forever but you cant edit blocks when you move a few blocks from position where you get teleported down.

PLS PLS PLS fix it!

**Comment by OWERLORD01** [comment]
Thanks

**Comment by OWERLORD01** [comment]
Update:
Tested on 1.10 with older protocollib version, and newer version and issue is still same.
https://youtu.be/hzg8qG5dVKw (new video, it'll make thing more clear)

**Comment by OWERLORD01** [comment]
Update2:
The issue is not very big on 1.8 servers. On 1.8, when player got stucked and try to interact with block, he got normally lagbacked, but on 1.11 (and on 1.10 also, i think) you cant even break block and you will never be lagbacked.

**Comment by OWERLORD01** [comment]
I think it's fixed in the latest release. I'll still test it and reopen if the issue happen again.
