### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent) for AAC

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#695]
### Issue description

I'd like to reference this issue I made in AACAddition Pro:
https://github.com/Photon-GitHub/AACAdditionPro/issues/86

I am getting the same kind of error just now with AAC. Furthermore AACAddition Pro is currently NOT on the server receiving the error as I have removed that plugin to test a few things.

This likely means that the issues stems directly from AAC.
The error I'm getting:
https://pastebin.com/raw/gsNfG1hs

### Core information
**Server version**: 1.11.2 - Spigot Build 1251

**AAC version**: 3.1.6-b5

**ProtocolLib version**: 4.2.1 Build 354

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by konsolas** [comment]
Was fixed in 3.2.0, but forgot to close.

**Comment by andrewkm** [comment]
Started up again.
