### ISSUE TITLE
1.12 Update

### ISSUE THREAD

**Issue by OWERLORD01** [konsolas/AAC-Issues#697]
Can u update AAC to 1.12? It'll be nice :P

**Comment by CeIebrimbor** [comment]
AAC will update to 1.12. 

This will occur after it(1.12) becomes stable and stops changing. Keep in mind that this request/issue was made before 1.12 was even an official version. The typical update goes through a few weeks of major changes during the bug smashing process, so AAC will likely move to 1.12 1-3 weeks after it is the official version on Spigot. 

AAC also relies on ProtocolLib, so changes there may influence AAC's release.

**Comment by konsolas** [comment]
3.2.0 will add the first version of 1.12 support.
