### ISSUE TITLE
Slime Block Piston Launch Bug

### ISSUE THREAD

**Issue by Gonfonix** [konsolas/AAC-Issues#698]
@@# Issue description
When a player is standing on a slime back getting launched by a piston, they get sent back to the ground (or on the slime block) instead of getting launched. However, once I disable Fly Detection, they can get launched again.

Here is what I mean:
![2017-05-31_12 46 19](https://cloud.githubusercontent.com/assets/5055478/26643408/381bb8fc-45ff-11e7-90ce-965dae248cdb.png)

### Core information
**Server version**: Paper Spigot 1.11.2

**AAC version**: 3.1.6-b5

**ProtocolLib version**: 1.11 Version (Build #354)

**Plugin list**:
![screen shot 2017-05-31 at 12 40 49 pm](https://cloud.githubusercontent.com/assets/5055478/26643160/6dfaf9de-45fe-11e7-850c-126440bb8b6a.png)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by LogGits** [comment]
I believe this happens in aac 4.1.6 on paper 1.13.2 build 639
