### ISSUE TITLE
Fast Run Fly Bug

### ISSUE THREAD

**Issue by Gonfonix** [konsolas/AAC-Issues#699]
### Issue description
On the custom hacked client I coded myself, once I enable fly, I can run super fast (like I am in the air an inch off the ground), but as soon as I try to fly up I am kicked. Also speed detection is on, so it wouldn't be that.

_Celebrimbor Comment: My config, but Speed and Fly just lagback later. Only change to Speed detection is item_scalar._

Here is what I mean:
![2017-05-31_12 58 58](https://cloud.githubusercontent.com/assets/5055478/26643944/0a902dee-4601-11e7-99ff-7cba4540ee86.png)
![2017-05-31_12 59 21](https://cloud.githubusercontent.com/assets/5055478/26643943/0a80be2c-4601-11e7-93c7-61c85b78d509.png)

### Core information
**Server version**: Paper Spigot 1.11.2

**AAC version**: 3.1.6-b5

**ProtocolLib version**: 1.11 Version (Build #354)

**Plugin list**:
![screen shot 2017-05-31 at 12 40 49 pm](https://cloud.githubusercontent.com/assets/5055478/26643160/6dfaf9de-45fe-11e7-850c-126440bb8b6a.png)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Janmm14** [comment]
Can you please enable verbose and test it in a little video or telling me how fast the violation goes up for speed?

**Comment by Gonfonix** [comment]
Yes. I am currently sending a video to Celebrimbor on discord regarding the bug. It may though, just be his configuration.

**Comment by CeIebrimbor** [comment]
Confirmed not to be config related.
