### ISSUE TITLE
[Bypass] ImpossibleInteract not checking enough (ScaffoldWalk, BedFucker)

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#7]
ImpossibleInteract still allowes hack clients to reach through walls to break blocks and scaffoldwalk is still working.

HackClients only need to be in range and can look through other (full-solid) blocks to the target block as far as I observed hacks on the server I'm at.

Its also possible to look down to the block there one wants to place a block against without being over the edge of the block. Fixing this unfortunaly can cause some false positives on legit fast-bridging so there needs to be a cancelthreshold.

Maybe one could try setting a maximum of blocks per second being placed for a way.

Also it might be possible that there need to be some range checks for block breaking:
https://m.youtube.com/watch?feature=youtu.be&v=DMxhAw7JkJE
(Don't know whethrr its really AAC's fault)

**Comment by Photon-GitHub** [comment]
Also think of BlockBreaker, the player is starting a BlockBreak in range of the block, walks away but can still further break the block (at least also check the block-breaking-stop packet).

**Comment by Janmm14** [comment]
The video shows exactly that, @Photon-GitHub

Before creating a too strict implementation consider its possible to constantly jump to increase your block breaking range upwards.

**Comment by Photon-GitHub** [comment]
Sorry didn't check this exactly, but I think the only real possibility is to check the end of the block breaking (the player only sends 2 packets: DIGGING_START + DIGGING_STOP)

**Comment by Janmm14** [comment]
@konsolas fixed?

**Comment by Janmm14** [comment]
@konsolas Hello?

**Comment by konsolas** [comment]
I don't think this is done yet.

**Comment by konsolas** [comment]
Fix written and awaits testing on both the 1.8 and 1.10 servers.

Re-open if checking is unsatisfactory.
