### ISSUE TITLE
Custom kick command

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#70]
I would like to see a feature that makes changing the kick command possible.
In my case I use litebans and I wanted to see each aac-kick in the litebans history and therefore decided to change the aackick to litebans:kick, the problem was that the vl wasn't reset after the kick, therefore someone with nuker vl 3000 did not get kicked because the vl was simply too high after the relog.

**Comment by CeIebrimbor** [comment]
I'm not sure the Vl gets reset with AACkick either. I thought the only thing you lose is the auto-ban feature.

**Comment by Janmm14** [comment]
I thought vl resets always if you leave or get kicked

**Comment by CeIebrimbor** [comment]
No. Not in my experience with recent versions.

**Comment by konsolas** [comment]
VL is definitely reset on /aackick at this point.

**Comment by CeIebrimbor** [comment]
Yay!
