### ISSUE TITLE
Boat fly hack 

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#700]
**This is a bypass on AAC version 3.1.6 on a server sunknights.us.to involving the boat fly hack. This hack was used on the hacked client "Impact". The video was made for staff room in discord but has been reused to report the bypass here with a few ip cover ups. I do not own the server, I am head admin on it. The video was recorded on 5/29/17.**

Please include details like:
* AAC logs / Full console error **Any logs/console errors are in the video**
* Video of the bug / bypass, best with verbose chat output **https://youtu.be/UUNFOinKr-I**
* The in-game name of the involved players **"Slimerblue22ALT" (Cracked account)**

### Core information
**Server version**: 
![image](https://cloud.githubusercontent.com/assets/29098956/26644110/ab2ad77c-4601-11e7-86c2-70f4dcadb695.png)

**AAC version**: 
![image](https://cloud.githubusercontent.com/assets/29098956/26644157/cdcd18f8-4601-11e7-8a18-0a105d389294.png)

**ProtocolLib version**: 
![image](https://cloud.githubusercontent.com/assets/29098956/26644208/f81e2eee-4601-11e7-8216-06498ae1f86b.png)

**Plugin list**: 
![image](https://cloud.githubusercontent.com/assets/29098956/26644257/19fae160-4602-11e7-963a-8be2572ae83b.png)

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: ![image](https://cloud.githubusercontent.com/assets/29098956/26645961/e2028924-4607-11e7-812f-935a0e2afeb6.png)

**ProtocolSupport version**: **None**

**ViaBackwards version**: **None**

**BungeeCord plugins**: 
![image](https://cloud.githubusercontent.com/assets/29098956/26645935/cfd5c810-4607-11e7-9595-407b132d7efb.png)

**Comment by Slimerblue22** [comment]
My bad, as for the BungeeCord Plugins here is the list 
![image](https://cloud.githubusercontent.com/assets/29098956/26645749/3b572bfc-4607-11e7-9cad-0b99f8e40765.png)

**Comment by CeIebrimbor** [comment]
@Slimerblue22 No more info needed. Vehicle checks were damaged/removed recently so the boat fly is a known bypass (for now). Good that it is on the list though.

**Comment by SnakeDaoust1232** [comment]
I tried the boat hack from wurst and it was just freecam. You actually didn't fly anywhere. It was all client side. I suggest you test it and see if you actually fly places.

**Comment by Slimerblue22** [comment]
@SnakeDaoust1232 Wurst and Impact are two completely different hacked clients and will not always have the same outcome from a certain hack. It is not a "Freecam" mode or anything for Impact (Idk about Wurst)     ,but I definitely was moving as I didn't phase through anything and could interact with the world like normal.

**Comment by Janmm14** [comment]
Vehicle checks are just inactive in AAC 3.1.6

Use 3.1.5 if you care much or wait for 3.1.7
