### ISSUE TITLE
Reach not work

### ISSUE THREAD

**Issue by crimilo** [konsolas/AAC-Issues#701]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Describe your issue here, please try to structure your
issue like starting with general things, especially
mention whether it is a false positive or a bypaas.

We can't read your thoughts.

Please include details like:
* AAC logs / Full console error
* Video of the bug / bypass, best with verbose chat output
* The ingame name of the involved players

### Core information
**Server version**: insert

**AAC version**: insert

**ProtocolLib version**: insert

**Plugin list**: insert

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: insert

**ProtocolSupport version**: insert

**ViaBackwards version**: insert

**BungeeCord plugins**: insert

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here: 

Does not working the reach in killaura the config are default what can i do?

**Comment by SnakeDaoust1232** [comment]
https://www.youtube.com/watch?v=CTsiz80fp-Q&feature=youtu.be

**Comment by crimilo** [comment]
This is my config of killaura, like default config and the reach not works (i was tryed to hit from 7 block)

sorry for my bad english : c

# Killaura detects combat hacks which give an unfair advantage
killaura:
   # Do you want to enable the killaura check
   enabled: true

   # What % of the time should AAC do a check? 100
   check_chance: 100

   # Lag compensation paramters - try not to break 3 - 6
   check_delay: 3
   listen_delay: 6

   # How far away must 2 players be to be checked? 1.2
   min_dist: 1.2

   # How long should the check last? 20
   duration: 20

   # How much should the check be weighted? 4
   weight: 4

   # How far off should a player be able to look to allow the hit 0.11
   max_diff: 0.11

   # How far should the player be allowed to reach during the check 4.5
   max_reach: 4.5

   # Map of violation levels to commands
   thresholds:
      25: "aacstaffnotify {player} è sospettato di (Killaura B) P{ping} TPS{tps}"
      40: "aacstaffnotify {player} è sospettato di (Killaura B) P{ping} TPS{tps}"
      65: "aacban {player} Killaura/triggerbot"

**Comment by CeIebrimbor** [comment]
This issue makes my head hurt...

Were you or the person you tested with OP or have AAC.bypass?

**Comment by crimilo** [comment]
no , all other checks works only the reach

**Comment by CeIebrimbor** [comment]
We need more than "reach not work". Do you mean 3.7 block reach bypasses? 4.5 blocks? 9 blocks? Which hacked client? Video?

**Comment by crimilo** [comment]
https://youtu.be/DANlWLqOg0w

**Comment by CeIebrimbor** [comment]
Hmm. The video wasn't an extensive test really and 50% of your hits were basically legal range. AAC will not instant kick or block all reach. Can you try hitting a player 6+ blocks away 10+ times?

**Comment by CeIebrimbor** [comment]
After giving this 2 days, we can assume there was an alternate reason for every client on earth bypassing reach. If that was the case, there would be an onslaught of reports.
