### ISSUE TITLE
Add aac.violations permission

### ISSUE THREAD

**Issue by Fleodas** [konsolas/AAC-Issues#702]
It would be useful to allow staff other than admins to see the violations gui, it's actually very useful to check players before they are kicked and to find false positives.

I can't add the aac.admin permission to my whole staff because I don't want my mods to be able to toggle checks and reload AAC.

You could add an new command such as /aacviolations with aac.violations permission wich would open the violations menu.

**Comment by Photon-GitHub** [comment]
Duplicate of #368
