### ISSUE TITLE
PlayerMoveEvent + unable to calculate distance between 2 world console spam

### ISSUE THREAD

**Issue by aaa8881** [konsolas/AAC-Issues#703]
### Issue description

AAC often generate exception in playerMoveEvent and unable to calculate distance between a world and another world. I attached full log as it'll be easier to check that. I could not check if it cause any performance issue. 

Full Log: http://www.filedropper.com/showdownload.php/latest_17

### Core information
**Server version**: 1.10.2

**AAC version**: latest

**ProtocolLib version**: latest

**Plugin list**: http://imgur.com/a/rY5Wn

https://www.spigotmc.org/resources/bedwars-eggwars-solo-gameplay-teams-holograms-multiarena-generators-upgrades.28113/ is bedwars plugin, others are obvious I believe

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.0.4

**ProtocolSupport version**: 4.24

**ViaBackwards version**: latest

**BungeeCord plugins**: build#1232

**Comment by Janmm14** [comment]
It should not cause any issues neither detectionwise nor peformancewise usually

**Comment by Photon-GitHub** [comment]
Please use pastebin/hastebin for logs, makes it easier to work for konsolas.
