### ISSUE TITLE
Jesus Bypass

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#704]
**This is a bypass on AAC version 3.1.6 on a server sunknights.us.to involving the Flight hack. This hack was used on the hacked client "Impact". I do not own the server, I am head admin on it. The video was recorded on 6/2/17 (Today as of reporting this)**
Please include details like:
* AAC logs / Full console error **For some reason the log was corrupted** 
* Video of the bug / bypass, best with verbose chat output **https://youtu.be/4P-b37Gx5ho**
* The ingame name of the involved players **Slimerblue22ALT (Cracked Account)**

### Core information
**Server version**: ![image](https://cloud.githubusercontent.com/assets/29098956/26644110/ab2ad77c-4601-11e7-86c2-70f4dcadb695.png)

**AAC version**: ![image](https://cloud.githubusercontent.com/assets/29098956/26644157/cdcd18f8-4601-11e7-8a18-0a105d389294.png)

**ProtocolLib version**: ![image](https://cloud.githubusercontent.com/assets/29098956/26644208/f81e2eee-4601-11e7-8216-06498ae1f86b.png)

**Plugin list**: ![image](https://cloud.githubusercontent.com/assets/29098956/26644257/19fae160-4602-11e7-963a-8be2572ae83b.png)

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**:  ![image](https://cloud.githubusercontent.com/assets/29098956/26645961/e2028924-4607-11e7-812f-935a0e2afeb6.png)

**ProtocolSupport version**: **None**

**ViaBackwards version**: **None**

**BungeeCord plugins**: ![image](https://cloud.githubusercontent.com/assets/29098956/26645935/cfd5c810-4607-11e7-9595-407b132d7efb.png)

**Comment by Janmm14** [comment]
Doesn't look like a fly bypass, just jesus

**Comment by OWERLORD01** [comment]
Try to enable movement.jesus check. It can help with something like this...

**Comment by Slimerblue22** [comment]
@OWERLORD01 I will try that, I believe it is disabled by default I will turn it on and retry to see if it changes anything.

**Comment by Slimerblue22** [comment]
@Janmm14 The reason I put the flight part in is because it used the flight hack so I thought I would put it in

**Comment by OWERLORD01** [comment]
@Slimerblue22 Default (fly) jesus detection is bad, default jesus detection is better and can detect every bypass. I recommend you to turn it on :)

**Comment by Slimerblue22** [comment]
@OWERLORD01 I did and I could still bypass

**Comment by OWERLORD01** [comment]
@Slimerblue22 Ok, then, the only person who can fix it is @Konsolas :P

**Comment by Slimerblue22** [comment]
@OWERLORD01 Yea, hope it gets patched soon

**Comment by SnakeDaoust1232** [comment]
Jesus is disabled by default in the AAC config. Make sure you enable it to catch some other pesky jesus hacks.
