### ISSUE TITLE
Heuristic P/20 False Positive

### ISSUE THREAD

**Issue by OWERLORD01** [konsolas/AAC-Issues#705]
## Issue description

Hey, I have an false positive that can be very bad for factions servers.
Here it is... https://youtu.be/BAFEjmgRA9E

## Core information
**Server version**: TacoSpigot #101

**AAC version**: 3.1.6-b5

**ProtocolLib version**: latest release

## Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: latest

**ViaBackwards version**: none

EDIT: If the first link is not working, try this one https://youtu.be/BAFEjmgRA9E

**Comment by CeIebrimbor** [comment]
Video was taken down (both of them)

**Comment by konsolas** [comment]
Neither video works. Closing for the time being.

**Comment by Janmm14** [comment]
Little note: Both links are the same

**Comment by OWERLORD01** [comment]
Here's the new one. Something was wrong with YT
https://www.youtube.com/watch?v=kYH6yFxAfAM

**Comment by CeIebrimbor** [comment]
min_confidence was 63.5. With the recommended kick level being 80+, this is not a false detection. Please request re-open of this issue if you can get a false 80+ min_confidence.

**Comment by OWERLORD01** [comment]
Tested on 80 now, It's still happening, but player must be killing mobs for 5+ minutes.
