### ISSUE TITLE
Critical Bypass || AAC 3.1.7 Regen // GodMode

### ISSUE THREAD

**Issue by OWERLORD01** [konsolas/AAC-Issues#706]
Hey, please fix this before releasing AAC 3.1.7
https://www.youtube.com/watch?v=M8JLvh9duZ0

**Comment by Photon-GitHub** [comment]
3.1.7 is not even released and gomme has several config changes and doesn't kick for all checks.

**Comment by Janmm14** [comment]
Please do not spam this issue tracker with issues about unreleased versions. We can search Youtube ourselfs.
