### ISSUE TITLE
AAC 3.1.7 Bhop

### ISSUE THREAD

**Issue by OWERLORD01** [konsolas/AAC-Issues#707]
Pls fix it before releasing new version :P 
https://www.youtube.com/watch?v=FC-H9RzJgYk

**Comment by Photon-GitHub** [comment]
The bhop is hardly faster, not shown on longer distances and the video is of bad quality.

**Comment by konsolas** [comment]
Video is inconclusive and of low quality. Does not seem to be faster than normal players.
