### ISSUE TITLE
Fly false positive when strafing out of water

### ISSUE THREAD

**Issue by Photon-GitHub** [konsolas/AAC-Issues#71]
Like the title says, if you strafe on the edge of a water (parallel to the edge) and try to jump out when strafing (no other movement, only strafing) you will get flagged for fly and can be kicked.

xyz failed Fly: (LIQUID) moved unexpectedly: 0.34 VL:xyz
xyz failed Fly: (LIQUID) moved unexpectedly: 0.39 VL:xyz

**Comment by konsolas** [comment]
Fixed and tested.
