### ISSUE TITLE
Command block teleports are cancelled

### ISSUE THREAD

**Issue by Heroco** [konsolas/AAC-Issues#710]
It isn't possible to teleport a player using command blocks

Verbose message:
[AAC] Cancelled internal Bukkit setback of HeroCode in favour of AAC's checks

Core information
Spigot Version: CraftBukkit version git-Spigot-5f38d38-12698ea (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
AAC Version: AAC 3.1.7
ProtocolLib Version: 4.2.1
ViaVersion Version: 1.0.4

Plugin list: NoCheatPlus, Spartan AACAdditionPro (all are up to date)

**Comment by FinalPacket** [comment]
Why do you need 2 other anticheats?
I mean that can interfere with some of the checks and takes up more resources.

**Comment by Heroco** [comment]
@FinalPacket I don't think that NoCheatPlus or Spartan cause that problem. And there are no problems, because only one anticheat is active for a player. (Sadly AAC's bypass permisson does not disable the 'MOVE' check)

**Comment by Janmm14** [comment]
@Heroco AAC does not support your server.

**Comment by geNAZt** [comment]
We know this user is hosting a service against AAC ToS but still this is a valid bug report we need to solve.
