### ISSUE TITLE
No hack but trigger fastbow with Sustained injury using bow

### ISSUE THREAD

**Issue by waiching514** [konsolas/AAC-Issues#711]
When a player is exposed to a flame or poisoning with a bow, it will trigger fastbow

`[03:10:04 INFO]: [*] waiching514 may be using FastBow (ping = 270, tps = 19.84) `

**Server version**: 1.11.2

**AAC version**: 3.1.7

**ProtocolLib version**: 4.2.1

**Plugin list**:
![default](https://cloud.githubusercontent.com/assets/29138111/26758090/ebc0863a-4906-11e7-9c3a-17360f60669d.PNG)

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by SnakeDaoust1232** [comment]
What is the issue?

**Comment by OWERLORD01** [comment]
It happens so many times... Idk why and when it's happening.

**Comment by CeIebrimbor** [comment]
https://www.youtube.com/watch?v=G_Au8ugOvpM&feature=youtu.be
