### ISSUE TITLE
Hitbox error NPE@S.a:7

### ISSUE THREAD

**Issue by ItsMennyo** [konsolas/AAC-Issues#712]
### Issue description

Error: https://hastebin.com/ugepubamod.bash

### Core information

**Server version**: git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**AAC version**: 3.1.7-b1

**ProtocolLib version**: ProtocolLib v4.2.1-SNAPSHOT-b350

**Plugin list**: Plugins (4): PlugMan, AAC, ProtocolLib, ViaVersion

### Special environment information

**ViaVersion version**: ViaVersion 1.0.4

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by CeIebrimbor** [comment]
Please try ProtocolLib 4.2.0 (build 341) and confirm the same still occurs (if it does).

**Comment by ItsMennyo** [comment]
Same problem...
