### ISSUE TITLE
Failed to get thresholds for check MovementManager

### ISSUE THREAD

**Issue by irworks** [konsolas/AAC-Issues#713]
### Issue description

During startup AAC prints out 
`[WARN]: [AAC] (Punisher) WARN: Failed to get thresholds for check MovementManager`
tested with default config on clean server (deleted the AAC Folder in /plugins). Our users report multiple setback problems during jump and run game modes.

[Full Log](https://hastebin.com/alecujulev.md)

### Core information
**Server version**: 1.8.8-R0.1-SNAPSHOT

**AAC version**: 3.1.7-b1

**ProtocolLib version**: v4.2.1

**Plugin list**: AAC, ProtocolLib

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by CeIebrimbor** [comment]
It seems @konsolas forgot to tell AAC to ignore the fact that "move" is treated like its own check, but does not have thresholds like other checks. I expect this is 100% harmless. The move check just adds violations to the speed check.

**Comment by konsolas** [comment]
(Will be fixed in a default config generation update)
