### ISSUE TITLE
Eltry + Firework = Ban

### ISSUE THREAD

**Issue by OWERLORD01** [konsolas/AAC-Issues#714]
### Issue description

https://youtu.be/bPcmm6EVFdE (correctly uploading)

### Core information
**Server version**: TacoSpigot #101

**AAC version**: latest (3.1.7)

**ProtocolLib version**: latest build for 1.11

**Plugin list**: Nothing that can effect elytra of fly (using essentials for /fly)

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: none

**ProtocolSupport version**: latest (for 1.11)

**ViaBackwards version**: none

**BungeeCord plugins**: nothing special..

**Comment by OWERLORD01** [comment]
Edit: Updated to 3.1.7-b1 but still can happen.

**Comment by CeIebrimbor** [comment]
@konsolas 
Elytra is in need of attention (finally)
#382 and #682

**Comment by OWERLORD01** [comment]
Ok ok, but please make https://github.com/konsolas/AAC-Issues/issues/694 critical. It must be fixed soon.

**Comment by CeIebrimbor** [comment]
Closed in favor of #773
