### ISSUE TITLE
Cannot Destroy Enderchest Issue (FastBreak)

### ISSUE THREAD

**Issue by Gonfonix** [konsolas/AAC-Issues#716]
@@# Issue description
Sometimes when a player places an enderchest, they can't break it. It just never breaks then they get kicked for FastBreak. Then once they relog, they can break it easily.

Core information

Server version: Paper Spigot 1.11.2

AAC version: 3.1.7-b1

ProtocolLib version: 1.11 Version (Build #354)

Plugin list:
![screen shot 2017-06-04 at 5 10 29 pm](https://cloud.githubusercontent.com/assets/5055478/26765384/16b4d034-4949-11e7-98a8-8da5fabb96a4.png)

Special environment information

ViaVersion version: none

ProtocolSupport version: none

ViaBackwards version: none

BungeeCord plugins: none

**Comment by CeIebrimbor** [comment]
Possibly due to Grief Prevention claimed blocks?

**Comment by Gonfonix** [comment]
No. I have GriefPrevention disabled in all worlds atm (full grief and raid server).

**Comment by CeIebrimbor** [comment]
Can we see some AAC log verbose for this detection? A video? I have a feeling it may be a plugin, since a global bug where you couldn't break a specific block would be reported by lots of people.

**Comment by konsolas** [comment]
Getting a fastbreak change in 3.2.1
