### ISSUE TITLE
Teleport in-air bug

### ISSUE THREAD

**Issue by timothydavidhart** [konsolas/AAC-Issues#717]
### Issue description
If you teleport to someone who is flying when you dont have fly you get flagged for fly heavily if they are high enough you can get kicked

https://pastebin.com/E09uvMgb

### Core information
**Server version**: 1.8.8 latest paperspigot

**AAC version**: 3.1.7

**ProtocolLib version**: 4.2.0

**Plugin list**: [![https://gyazo.com/e53a8bcce900778c907666d78a3cdbb7](https://gyazo.com/e53a8bcce900778c907666d78a3cdbb7/raw)](https://gyazo.com/e53a8bcce900778c907666d78a3cdbb7)
[![https://gyazo.com/af6b028373bcd3649da067bf14dedf2d](https://gyazo.com/af6b028373bcd3649da067bf14dedf2d/raw)](https://gyazo.com/af6b028373bcd3649da067bf14dedf2d)

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.0.4

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: [![https://gyazo.com/965ed0df079a8def3032babc7ade82e3](https://gyazo.com/965ed0df079a8def3032babc7ade82e3/raw)](https://gyazo.com/965ed0df079a8def3032babc7ade82e3)

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here:

**Comment by timothydavidhart** [comment]
another thing if i try to use vanilla teleport command i get dragged back for [![https://gyazo.com/dc5b3aeb28e40018a492d54d8e057a84](https://gyazo.com/dc5b3aeb28e40018a492d54d8e057a84/raw)](https://gyazo.com/dc5b3aeb28e40018a492d54d8e057a84)

**Comment by Heroco** [comment]
> another thing if i try to use vanilla teleport command i get dragged back for 
https://github.com/konsolas/AAC-Issues/issues/710
