### ISSUE TITLE
Block break bug | BIG BUG!

### ISSUE THREAD

**Issue by craftrise** [konsolas/AAC-Issues#718]
### Issue description

When you install the AAC plugin, problems are starting.
When you delete the AAC plugin, the problems are resolved.

* AAC logs : https://hastebin.com/liladikepa.hs

* Video of the bug : https://www.youtube.com/watch?v=D3eY_OnE7WU&feature=youtu.be

### Core information
**Server version**: 1.8.8 - Spigot

**AAC version**: 3.1.7

**ProtocolLib version**: 4.2.0

**Plugin list**: Custom plugins

### Special environment information

**ViaVersion version**: 1.0.4

**ProtocolSupport version**: None

**ViaBackwards version**: None

**BungeeCord plugins**: Custom

Latest AAC 3.1.7 | 05.06.2017

**Comment by KennyTV** [comment]
Yep, same thing posted here https://github.com/konsolas/AAC-Issues/issues/715.
I hope it'll be fixed quite soon, else I have to use an older version.

**Comment by konsolas** [comment]
in favour of #715
