### ISSUE TITLE
Flying Elytra in Water Kicks You For Fly Hacks

### ISSUE THREAD

**Issue by Gonfonix** [konsolas/AAC-Issues#719]
Issue description
When flying with an elytra in the water, you get kicked for Fly Hacks or sometimes "Ping Spoofer Mod".

![2017-06-05_14 25 49](https://cloud.githubusercontent.com/assets/5055478/26797586/5a348054-49fb-11e7-99ad-0c8fb2532068.png)
![2017-06-05_14 26 02](https://cloud.githubusercontent.com/assets/5055478/26797585/5a33d280-49fb-11e7-99d9-f5ec62b676de.png)

Core information

Server version: Paper Spigot 1.11.2

AAC version: 3.1.7-b1

ProtocolLib version: 1.11 Version (Build #354)

Plugin list:
![screen shot 2017-06-04 at 5 10 29 pm](https://cloud.githubusercontent.com/assets/5055478/26797569/4cecd630-49fb-11e7-9048-6edbd04ac5b1.png)

Special environment information

ViaVersion version: none

ProtocolSupport version: none

ViaBackwards version: none

BungeeCord plugins: none

**Comment by CeIebrimbor** [comment]
Elytra handling definitely needs work.

[Elytra issues](https://github.com/konsolas/AAC-Issues/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20elytra)

**Comment by CeIebrimbor** [comment]
Closed in favor of #773

**Comment by Janmm14** [comment]
Sude note: Ping Spoofer Mod is nothing related to AAC.

**Comment by CeIebrimbor** [comment]
It was a misunderstanding by the OP when reading his logs while using my config. He saw some conditional command tests that related to ping spoof mod assumption. Unrelated...
