### ISSUE TITLE
AAC causes server crash

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#721]
https://pastebin.com/LATzmgWx
AAC 3.1.7 b1
Paperspigot 1.11.2
Default config
that's all

**Comment by CeIebrimbor** [comment]
ProtocolLib version?

Try redownloading.

**Comment by MClausz** [comment]
ProtocolLib 4.2.2-SNAPSHOT-b357
I don't think redownloading AAC would solve the problem.

**Comment by MClausz** [comment]
Tried updating ProtocolLib to latest version and redownloading AAC, doesn't help at all.
This is a serious issue now.

**Comment by konsolas** [comment]
Do you have AAC logs from just before the crash?

**Comment by MClausz** [comment]
nope.

**Comment by konsolas** [comment]
Do you have latest.log with log_console enabled?

**Comment by MClausz** [comment]
no, I will enable log_console and let you know if this happen again

**Comment by Janmm14** [comment]
Please also let me ask you what kind of graphical user interface is running at your server.

**Comment by MClausz** [comment]
Looks like it's my code causes AAC to crash (async teleport), I've fixed my code and it seems to be fine now, sorry.

**Comment by CeIebrimbor** [comment]
@MClausz What was your old code? New code?

**Comment by konsolas** [comment]
But it would still be useful to know what causes the crash @MClausz

**Comment by Janmm14** [comment]
@konsolas he wrote async teleport

**Comment by MClausz** [comment]
I teleport player in an async task, for testing purpose and for some reason I forgot to remove that line of my code.
In recently version of AAC it has a PlayerTeleportEvent exception (must be called in main thread) which is caused by my code. After removing that async teleport line the crash issue seems to be gone.

**Comment by konsolas** [comment]
Thanks.
