### ISSUE TITLE
LinkageError: attempted duplicate class definition for PacketAdapter

### ISSUE THREAD

**Issue by JampireX** [konsolas/AAC-Issues#722]
https://www.hastebin.com/ladazucime.md

server don't accepting connections after startup if this error ocurred.
players recieve **Server is still starting up** kick message

spigot 1.8.8
protocollib 4.2.0
viaversion 1.0.4
aac 3.1.7 b1

**Comment by Janmm14** [comment]
You do very likely have multiple versions of protocollib in your server.

**Comment by JampireX** [comment]
no, it's immpossible. only one plib version and don't have plugins with plib included.
this error very rarely (1 per 150 - 300 startups)

**Comment by JampireX** [comment]
![image](https://user-images.githubusercontent.com/24954035/26961238-f1c4c428-4ce5-11e7-82ad-0360cdd83447.png)
you can see size of plugins, no one have enought size to be containing plib in self

**Comment by CeIebrimbor** [comment]
Not sure ViaVersion (allowing 1.12 clients) is a great idea currently...For a long list of reasons, but mainly anti-cheat, protocol level stuff.

**Comment by Janmm14** [comment]
Java version? Maybe try updating to latest Java 8.

**Comment by JampireX** [comment]
![image](https://user-images.githubusercontent.com/24954035/27003734-c31528f0-4e04-11e7-90d1-007577a00870.png)
think update not needed

**Comment by Janmm14** [comment]
are you using some kind of external debugger / profiler?

**Comment by JampireX** [comment]
no

**Comment by Janmm14** [comment]
@JampireX Please provide output of /aac in a private message on spigotmc to me: https://www.spigotmc.org/conversations/add?to=Janmm14

**Comment by Janmm14** [comment]
User thinks issue is fixed.
