### ISSUE TITLE
a compatible bug

### ISSUE THREAD

**Issue by jiangdashao** [konsolas/AAC-Issues#723]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

I found 3.7.1-b1 have a bug,when player break the block under the foot,and other minigame plugin cancel the break event,AAC will still teleport player to under the ground
I tested BedwarsRel,after I broke the block under my foot,I will teleport into the under the ground

verbose:
[16:10:30 INFO]: [AAC] [VERBOSE] Cancelled internal Bukkit setback of jiang_da_s
hao in favour of AAC's checks
[16:10:30 INFO]: [AAC] [VERBOSE] Cancelled internal Bukkit setback of jiang_da_s
hao in favour of AAC's checks

### Core information
**Server version**: 1.8.8

**AAC version**: 3.1.7-b1

**ProtocolLib version**: 4.2.1

**Plugin list**: BedwarsRel,AAC,ProtocolLib,PermissionEX,CC3,etc

**ViaVersion version**: 1.0.4

**Comment by CeIebrimbor** [comment]
#715
