### ISSUE TITLE
Enderpearls broken | CRITICAL ASAP

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#725]
Info:
- Handling enderpearls are broke in 3.1.7b1. Not only does it allow you to pearl in regions that have enderpearls denied, but it thinks you are flying, phasing, and taking 0 kb. Debug: https://hastebin.com/sejosewera.apache
- Im having trouble recreating but that time from when the pearl hits, to where it tps you to the location of the pearl, if you sprint jump during that period, it flags for speed. Got up to 200vl
- If you throw a far pearl, you get this: https://gyazo.com/19284626ff46442bbba8eceb8742df98

Video: https://www.youtube.com/watch?v=iaeZwJZUO04&feature=youtu.be

Core information

Server version: Spigot, Paperspigot and Tacospigot 1.8.8
AAC version: 3.1.7b1
ProtocolLib version: 4.2.1
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by KennyTV** [comment]
@konsolas Could you name a period, when you are fixing the various (and also not small) move bugs like this or the phase bug? Just a simple guess when I could check again . _.

**Comment by CeIebrimbor** [comment]
@KennyTV 
I know you are frustrated. b2 development should start taking place soon. You _may_ consider moving to AAC 3.1.5-b3 (most stable recent build) for the time being.
