### ISSUE TITLE
Nether Portal dropping TPS?

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#726]
Info:
- Going through a netherportal drops your TPS immensely for a second.

Video: https://www.youtube.com/watch?v=_oa9Kq2qAdk&feature=youtu.be

Core information

Server version: Spigot, Paperspigot and Tacospigot 1.8.8
AAC version: 3.1.7b1
ProtocolLib version: 4.2.1
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by Gonfonix** [comment]
Well this is natural with MC though since it loads new chunks into your game, which can delay on the whole entire server as well. And the likely hood of illegal modifications being undetected during this would be unlikely as a hacker would continue bad behavior after the split seconds of TPS drop.

**Comment by SnakeDaoust1232** [comment]
All of the chunks in the nether are preloaded.

**Comment by CeIebrimbor** [comment]
Do you have WorldGuard (or another protection plugin)? WG has a config option to do safe portal events (checking spawn location of portal for claimed land) and if this is enabled, it is an extraordinarily heavy event that will spike any server out there.

Also, keep in mind that AAC's TPS monitor takes samples that are 1/4th the size of genuine TPS, so dropping to 17 TPS likely means that it was 17 TPS during 1/4th of a tick, which still equates to 19.99 TPS for a single tick.

**Comment by CeIebrimbor** [comment]
Discussed with Snake in Discord. Closing issue.
