### ISSUE TITLE
Switching from Spectator to Survival & Piling blocks Up = "Hitting the ground too hard"

### ISSUE THREAD

**Issue by Gonfonix** [konsolas/AAC-Issues#727]
Issue description
When a player switches from spectator to survival (and their real close to the ground), then they get killed for "hitting the ground too hard". Also sometimes (and this is doesn't happen often but occasionally) when a player is building up (or piling up) or when they're mining down, they "hit the ground too hard" and die.

Core information

Server version: Paper Spigot 1.11.2

AAC version: 3.1.7-b1

ProtocolLib version: 1.11 Version (Build #354)

Plugin list:

![screen shot 2017-06-07 at 8 47 19 pm](https://user-images.githubusercontent.com/5055478/26907633-f0f363ac-4bc2-11e7-8c42-1bfc975d7932.png)

Special environment information

ViaVersion version: none

ProtocolSupport version: none

ViaBackwards version: none

BungeeCord plugins: none

**Comment by OWERLORD01** [comment]
Try to use essentialsx for gamemode

**Comment by Gonfonix** [comment]
I don't use essentials.

**Comment by Janmm14** [comment]
AAC Logs / Verbose output of when this happens please.

**Comment by konsolas** [comment]
Not enough information.
