### ISSUE TITLE
Error spam PlayerMoveEvent Cannot measure distance between worlds

### ISSUE THREAD

**Issue by hlong1909** [konsolas/AAC-Issues#728]
My old topic had closed https://github.com/konsolas/AAC-Issues/issues/720

I had update ProtocalLib 4.2 but console have spam error
https://pastebin.com/V91T7awL
And lasted log file https://www.mediafire.com/?qwn07np7hgdgbnv
Please view it
Thanks you

**Comment by CeIebrimbor** [comment]
@konsolas Teleport between worlds still an issue. (maybe?)
