### ISSUE TITLE
Teleporting Bug | CRITICAL (Falling through blocks)

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#731]
Info:
- Since it cancels the bukkit teleport event, it doesn't handle stuff like this.
- It also freezes you in place kinda like that old velocity bug where i was a different location on the other players screen. You need to relog to fix it, but then you fall through the world again.

Video: https://www.youtube.com/watch?v=A7BGGSEjMSc&feature=youtu.be
- Another video: https://www.youtube.com/watch?v=FtK2tfKOi4Q&feature=youtu.be

Core information

Server version: Spigot, Paperspigot and Tacospigot 1.8.8
AAC version: 3.1.7b1
ProtocolLib version: 4.2.1
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by SnakeDaoust1232** [comment]
https://www.youtube.com/watch?v=diiwudK_hVs&feature=youtu.be

**Comment by JampireX** [comment]
have similar issue with this version.
often happens if floor have only one block and chunk not loaded before
