### ISSUE TITLE
Aristosis and winter bypasses  AAC

### ISSUE THREAD

**Issue by joshua31177** [konsolas/AAC-Issues#732]
[aac_2017-06-08_15-04-27.zip](https://github.com/konsolas/AAC-Issues/files/1062496/aac_2017-06-08_15-04-27.zip)

I can record footage since I don't have software for that. 
this is the client that bypasses: https://aristois.opentexon.com/

**Comment by SnakeDaoust1232** [comment]
I looked at the logs and i think the reason why you think there is bypass is because your server tps is below 15. After 17tps certain checks start to disable

**Comment by joshua31177** [comment]
my server tps is at 20 it was at 15 when I used world edit

**Comment by joshua31177** [comment]
i tested this client against AAC and most of them bypassed it ex: kill aura, flight.

**Comment by joshua31177** [comment]
do you want me to film it bypassing?

**Comment by Janmm14** [comment]
- Version of AAC used in testing?
- Did you test on your server?

Very likely the fly bypass is not working in the latest version of AAC.

About Killaura:
- Was the opponent another actively playing player?
- How long did you test? (One or two fights are often not enough)

**Comment by joshua31177** [comment]
i am using the latest version of AAC and yes i tested it on my server and i tested the kill aura for about 5 to 10 minutes.

**Comment by joshua31177** [comment]
Is there anything else that you need?

**Comment by Janmm14** [comment]
I ask 4 questions you answered 3 of them.

**Comment by joshua31177** [comment]
the 4th one is yes he is an active player.
