### ISSUE TITLE
3.1.7 Performance Issues

### ISSUE THREAD

**Issue by FrozenBeard** [konsolas/AAC-Issues#733]
PaperSpigot 1.11.2 latest.
AAC 1.3.7R-1
AAC Randomly took my server to about 300% CPU destroying performance over the last few days multiple times causing outrage. I have backdated to 3.1.5R3 for now.

http://i.imgur.com/8al6Ua1.png

**Comment by Janmm14** [comment]
Its not possible to clearly read the exact AAC classes of that screen.

**Comment by konsolas** [comment]
Small bug in the previous version caused performance issues during constant bukkit teleports.

3.2.0: 
 - No longer cancels bukkit teleports
 - Measured to have a performance improvement of ~40% over 3.1.7 (FFA server, 40 players)

@FrozenBeard
