### ISSUE TITLE
Hits aren't registering while an entity takes fire damage.

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#735]
Info:
- If you try to hit someone as they are taking fire damage, the hit wont register.

Video: https://www.youtube.com/watch?v=owq774fDdU0&feature=youtu.be

Core information

Server version: Spigot, Paperspigot and Tacospigot 1.8.8
AAC version: 3.1.7b1
ProtocolLib version: 4.2.1
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by SnakeDaoust1232** [comment]
So actually confirmed that this is not an AAC bug. Its not a viaversion bug either. Has it always been like this? lol wtf

**Comment by SnakeDaoust1232** [comment]
@CeIebrimbor ? Any ideas?

**Comment by Janmm14** [comment]
As far as I know this is a vanilla minecraft feature

**Comment by iConfueZ** [comment]
^^
That's vanilla minecraft.

**Comment by Janmm14** [comment]
Just adding here that the period of time an entity will be immune to damage after recieving damage can be altered by plugins on the server. If the period is disabled or too low, autoclickers are op.
