### ISSUE TITLE
Fishing Rod FP | 3.1.7b1

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#736]
Info:
- Video explains it

Video: https://www.youtube.com/watch?v=ldoT8e5TiXc&feature=youtu.be

Core information

Server version: Spigot, Paperspigot and Tacospigot 1.8.8
AAC version: 3.1.7b1
ProtocolLib version: 4.2.1
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by CeIebrimbor** [comment]
Closing in favor of #851
