### ISSUE TITLE
Teleportation using Commands isn't working

### ISSUE THREAD

**Issue by Heroco** [konsolas/AAC-Issues#741]
At least AAC stopped cancelling bukkit teleports...
Now you get flagged for it. (Move, Speed, Fly, Phase)

'/teleport [Player] [Player2] ' is working
'/teleport [Player] [Coordinates]' is not working

Core information
Spigot Version: CraftBukkit version git-Spigot-5f38d38-12698ea (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
AAC Version: AAC 3.2.0
ProtocolLib Version: 4.2.1
ViaVersion Version: 1.1.1

Plugin list: NoCheatPlus, Spartan AACAdditionPro (all are up to date)

**Comment by CeIebrimbor** [comment]
Having multiple anti-cheats all doing the same things is a poor choice. 

Please:
1. Remove all but AAC
2. Use ProtocolLib 4.2.0

Repost info after those have occured or let us know if that fixes it.

**Comment by Janmm14** [comment]
Guess what the obvious question is when you write "I'm getting flags for teleportation"

**Comment by SnakeDaoust1232** [comment]
Teleporting works fine for me. What server do you have that allows non-ops to teleport to anywhere around the map?

**Comment by Janmm14** [comment]
@SnakeDaoust1232 some kind of anticheat testing server where he maybe has teleport perms, but no bypass perms.

**Comment by CeIebrimbor** [comment]
#751
