### ISSUE TITLE
Cannot measure distances between worlds @b5.a:49

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#742]
### Issue description

During initial testing of 1.12 prior to our production launch which we have not done yet, I have noticed the following error show up twice. (I'm sure this would be much more frequent if running in production)

First time: https://pastebin.com/raw/1n021NBy
Second time: https://pastebin.com/raw/xdC0zvTL
PS: "rising" and "sg2" refer to two different worlds on our server. This seemed to happen when our Survival Games plugin teleported a player from sg2 world to rising world. This is my assumption.

Additional information available upon request as always :)

### Core information
**Server version**: 1.12 - Spigot Build 1309

**AAC version**: 3.2.0
**AAC config**: Celebrimbor's

**ProtocolLib version**: 4.3.0 Build 372

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Janmm14** [comment]
(Errors look identical on first glance)

**Comment by andrewkm** [comment]
They are... I included both instances because it happened twice during testing.

**Comment by andrewkm** [comment]
Misclicked close issue oops blame github mobile.
