### ISSUE TITLE
Add a option in the Config to disable Setback verbose messages

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#747]
Since the Bukkit Setbacks are part of verbose now our logs explode due to that. Please provide a way to disable this message.

**Comment by SnakeDaoust1232** [comment]
I agree!

**Comment by CeIebrimbor** [comment]
Also maybe #384 while you're at it? 384 was the highest contributor to verbose spam before the new Bukkit setback stuff.

**Comment by konsolas** [comment]
Moving to /aacdebug
