### ISSUE TITLE
When you set slipperiness to 0 you fall

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#749]
When setting block slipperiness to 0 you fall out of map and have no way of getting back, you don't die and are stuck randomly forever.

**Comment by w-o-a-h** [comment]
set the value with mcp and kicked me for invalid move packet then when i logged back on it was fine

**Comment by konsolas** [comment]
Confirmed by @geNAZt

**Comment by konsolas** [comment]
.-.
