### ISSUE TITLE
Fastbreak seems to not cancel correctly

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#752]
There seems to be an bypass where you can break blocks for the server. It triggers all actions inside BlockBreak events:

https://puu.sh/wdqkg/470bbd3aae.png

**Comment by CeIebrimbor** [comment]
@geNAZt 
Is this something AAC should concern itself with? "Break blocks for the server"???

I just see this has been open for months with no comment so just questioning if it is a legitimate, let alone "critical" issue.

**Comment by konsolas** [comment]
Fixed... some time ago
