### ISSUE TITLE
Jump bypass on test server 

### ISSUE THREAD

**Issue by Fages1** [konsolas/AAC-Issues#754]
video:
https://www.youtube.com/watch?v=up_OQCIEJUI&feature=youtu.be

Link to cheat:
https://yadi.sk/d/4pJZN1vp3JSmYg

**Comment by CeIebrimbor** [comment]
Versions? Modified config? Anything that suggests this is worth looking into?

**Comment by Fages1** [comment]
minecraft version 1.11.2
Tested on your server test.kons.co

**Comment by Janmm14** [comment]
test.kons.co is not up to date as far as I know...

Additionally this is working on the default config very likely just like highjump, because fly `min_vl` in the default config is too high (`28` instead of `12` like it was earlier)

**Comment by Fages1** [comment]
I do this in any amount of time, I do not suspect or kick
