### ISSUE TITLE
3.2.0 Move Check VL Decay

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#755]
Violations for the move check don't decay (it seems), so laggy players will eventually get to VL 500. I have seen 900+, it just depends on how long the player is connected. Only a matter of time.

Was reported on Gomme and another 1.8.8 ViaVersion server w/ Bungee.

**Comment by Janmm14** [comment]
Not seeing anything critical here since thresholds for move should be empty.

**Comment by CeIebrimbor** [comment]
From default config (as of 3.2.0)
`   # Map of violation levels to commands
   thresholds:
      200: "aacstaffnotify {player} is sending unusual movement information (ping = {ping}, tps = {tps})"
      500: "aackick {player} Sending unusual movement packets"`

**Comment by Janmm14** [comment]
Oh ok, didn't noticed there was such a change.
