### ISSUE TITLE
Chunk Reloading and NBT Tags?

### ISSUE THREAD

**Issue by Fluxty** [konsolas/AAC-Issues#756]
We seem to have a major issue with the latest version of AAC and SilkSpawners on TacoSpigot 1.8.8.. Now I can't pretend to know this is an AAC problem, but just humor the issue, if there's any chance some AAC update is the source of this a fix would be a huge stress off our shoulders and allow us to continue to progress with our network.

Players spawners are constantly turning from irongolem, silverfish, cow, chicken, etc. etc. into pig spawners, most commonly on chunk unload. What is with the sudden loss of NBT data for spawners? With the latest version of AAC the problem has seemed to really flare up hardcore and we're to the point where we are constantly running around confirming and fixing up broken spawners for players and can't really get any real work done.

Thank you for your time.

**Comment by CeIebrimbor** [comment]
Do you have AACaddition as well?

**Comment by Fluxty** [comment]
I do not

**Comment by Fluxty** [comment]
Update, signs are also becoming empty randomly? And chests just suddenly break and leave the contents all over the ground? I'm not sure what's going on here, something with tiles in general?

**Comment by Fluxty** [comment]
@CeIebrimbor I can now confirm this is an AAC isssue. On our servers, TacoSpigot 1.8.8, typing /aacrestorechunk <player> will make all of the items in all of the chests around the player pop out all over the place. It will also reset all signs, set spawners to pigs, set skulls to skeleton, etc. etc.

**Comment by Janmm14** [comment]
dont use the command i'd say

**Comment by Fluxty** [comment]
Yeah we're removing it from the phase and jesus checks in the config. So glad we found the source of this issue finally

**Comment by CeIebrimbor** [comment]
Why did you have it in those checks? I had those in my configs in pre AAC v3.0.5, but that command has been broken/abandoned for months.

**Comment by SnakeDaoust1232** [comment]
@CeIebrimbor Konsolas just did work for the aacrestorechunk command in the newest release i believe. Its still supported and i use it on my server and it has no issues.

**Comment by konsolas** [comment]
Closing in favour of #758
