### ISSUE TITLE
StackTrace (1) | 3.2.0

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#757]
https://gyazo.com/600cd67bd8c9381f922c749895dc1f67

**Comment by CeIebrimbor** [comment]
Same issue on ProtocolLib 4.2.0? It is still recommended you stay on 4.2.0 for 1.8-1.10

**Comment by SnakeDaoust1232** [comment]
crap, i keep forgetting. ill downgrade on that server and test. Closed for now
