### ISSUE TITLE
/aachunkrestore bugged | 3.2.0 | CRITICAL

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#758]
Reference: https://github.com/konsolas/AAC-Issues/issues/756

Info:
- Restoring the chunk the player is in takes any chest contents out of the chest and puts it on the ground, reverts player heads to skeleton skulls, removes any sign text, and changes spawners to pig. This is really bad because of people are flagged for phase in my spawn, where there are signs, they can remove all the text off of my signs.

Video: https://www.youtube.com/watch?v=PC4Kiysiihk&feature=youtu.be

Core information

Server version: Spigot, Paperspigot and Tacospigot 1.8.8
AAC version: 3.2.0
ProtocolLib version: 4.2.0
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by CeIebrimbor** [comment]
Should be removed or supported. (my opinion)

**Comment by SnakeDaoust1232** [comment]
I think supported, since there is this glitch: https://www.youtube.com/watch?v=mEKH-8yv_4w&feature=youtu.be

**Comment by Janmm14** [comment]
I think there are many more important issues.

**Comment by konsolas** [comment]
This was fixed in 3.2.2, but I forgot to add it to the milestone.
