### ISSUE TITLE
Fall through the blocks

### ISSUE THREAD

**Issue by Fages1** [konsolas/AAC-Issues#760]
Hi, I found a bug.
It is that you are falling through the block
The video is filmed on my server, it contains the latest version of AAC and ProtocolLib. Also there is a standard config.
https://www.youtube.com/watch?v=yrkYX_omKRs

**Comment by CeIebrimbor** [comment]
Is that a wand that creates glass at the player's feet? That is just not a good idea placing a transparent block right at a players feet while moving.

#753
