### ISSUE TITLE
AAC 3.2.0 FP Fly/PvP Bug

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#761]
* AAC logs / Full console error **AAC Verbose in video**
* Video of the bug / bypass, best with verbose chat output **https://www.youtube.com/watch?v=kf-EG06HrBw**
* The ingame name of the involved players **Killrex30 (Premium) Slimerblue22 (Cracked)** 

### Core information
**Server version**: 
![image](https://user-images.githubusercontent.com/29098956/27242684-5df3a6ca-52ac-11e7-8c28-2c4a41c016cf.png)

**AAC version**: **3.2.0**

**ProtocolLib version**: 
![image](https://user-images.githubusercontent.com/29098956/27241042-18c8633a-52a5-11e7-8536-cec36c5a7825.png)

**Plugin list**: 
![image](https://user-images.githubusercontent.com/29098956/27241006-fbab0956-52a4-11e7-8921-5f32910a31f5.png)

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**:  **viaversion-bungee-1.0.5-17w18b.jar**

**ProtocolSupport version**: **None**

**ViaBackwards version**: **None**

**BungeeCord plugins**: 
![image](https://user-images.githubusercontent.com/29098956/27240515-041d52da-52a3-11e7-85a0-68322eae9407.png)

**Comment by CeIebrimbor** [comment]
ProtocolLib 4.2.0 is for 1.8 servers. Use 4.2.1 and retest. This will be relabeled if the same detection occurs on the appropriate ProtLib.

**Comment by Slimerblue22** [comment]
@CeIebrimbor Ok, after updating to 4.2.1 it seamed to fix it for the most part. It would still trap him in place with the fly violation but only for about 1-2 seconds and it only happened once or twice during a 10 min battle.

**Comment by CeIebrimbor** [comment]
You may consider slightly raising the `min_vl` setting and/or lowering the `reduce_delay` setting to greatly reduce this probability without compromising the check. That's what I recommend to my config customers to resolve these minor annoyance issues.

**Comment by SnakeDaoust1232** [comment]
People report this same issue on my server. tacospigot 1.8.8 and protocollib 4.2.1. Imma downgrade to 4.2.0 and see if the issue persists.

**Comment by Janmm14** [comment]
I do not see any reason to close this one.

**Comment by konsolas** [comment]
No response for 8+ days, Slimerblue22 claims that the problem was fixed by the protocollib change, no additional information. Closing as invalid.
