### ISSUE TITLE
playerteleportevent big issue

### ISSUE THREAD

**Issue by LeoPantaniHD** [konsolas/AAC-Issues#764]
### Issue description

With the addiction of the new move check a lot of teleportation problems have occurred in ALL network:
For example when I teleport a player to the parkour location, the player gets teleported down of 1/2 blocks, or when a players finishes a match in pvp and he comes back to the lobby he spawns under the floor. Also in skywars when a player enter a game, when he is waiting that the game starts in the dome, he spawns litteraly 2 blocks under it and he can walk around the map even if the game is not started yet. There are no errors in console and phase check is disabled. If you need more informations do not hesitate to contact me, thanks!

(Please fix this bug, is very important!!)

Please include details like:
Config: https://hastebin.com/eributujit.bash
Screenshots: http://i.imgur.com/eAk5g00.png, http://i.imgur.com/eJHp4oe.jpg (note that the game is not started yet), http://i.imgur.com/RfH6Hqg.png, http://i.imgur.com/1yQUlvi.png

### Core information
**Server version**: 1.8

**AAC version**: 3.2.0

**ProtocolLib version**: latest

**Plugin list**: Custom

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: latest

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: custom

* Note date and time when the issue occurred here: 15/06/17

**Comment by SnakeDaoust1232** [comment]
This was an issue on 3.1.7b1, no on 3.2.0? 3.2.0 Fixed this issue for me.

**Comment by CeIebrimbor** [comment]
#753

**Comment by Janmm14** [comment]
The big problem you have here is that you disabled the phase check.
To prevent teleportation, AAC disables the inbuilt phase check of the server regardless whether the phase check in AAC is active.
