### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by jeinine** [konsolas/AAC-Issues#767]
Memory Leak, only when AAC is enabled.
![aac - copy](https://user-images.githubusercontent.com/18122285/27268331-5c15620a-5485-11e7-8af9-3b48804a6201.png)
![aac - copy 2](https://user-images.githubusercontent.com/18122285/27268334-5d828410-5485-11e7-9259-d2afe3c6f5a6.png)
Edit(New Image):
![objcountfix2](https://user-images.githubusercontent.com/18122285/27283532-2179b16e-54cb-11e7-92fa-c4147f1c3d05.png)

**No console Errors**

### Core information
**Server Version**: 1.8.8

**AAC version**: 3.2.0
AAC Logs: https://www.sendspace.com/file/uxioxr

**ProtocolLib version**: 4.2.0
![pluginlist](https://user-images.githubusercontent.com/18122285/27268484-2e34861c-5486-11e7-8630-c34f03e7335d.png)

**ViaVersion version**: 1.0.3 ( Still happens after i updated to the latest version )

**BungeeCord plugins**: SkinsRestorer

**Heap Dump**: 
*5gb Ram*: http://192.95.29.132/aacheapdump-1497902369445.hprof
*9gb Ram*: http://192.95.29.132/aacheapdump2-1497946461862.hprof

**Compressed heap dumps**:
https://janmm14.de/aacheapdump1.zip
https://janmm14.de/aacheapdump2.zip

Happens every time, the server is online with AAC, happens faster if more players are online.
100 players at day time, makes the server use 9gb/9gb of ram, and at night time when there are 3-5 players, the server keeps using 9gb/9gb of ram.

Note: The server with NoCheatPlus instead of AAC uses 3gb ram at most with 150players.
The server couldnt afford to have 150 players with aac due to the memory leaks dropping tps.

Spigot Id: Freelancer

Also, Every 45 minutes at almost 5 different times, there is CPU Spike using almost 700% of cpu, i disabled the "Chat check", of the antihack to lessen the effects, im pretty sure is related to aac, also.

**Comment by Janmm14** [comment]
You can hopefully understand that it is not that easy to track down memory leaks without a heap dump.

Compressing heap dumps with zip or similar tools usually get the size down by 90% in my experiences, maybe you are able to transfer a heap dump then. Alternatively as you seem to have a windows server, it might be a good idea to upload it directly from the windows server to dropbox/google drive/mega as the servers intenret connection should be stable enough.

**Comment by jeinine** [comment]
My computer is on windows, the servers are on Ubuntu.

identifying a memory leak is pretty simple when you are a developer on a small project.
pretty much of the data of AAC are stored in arrays of Objects, BigInteger, String, etc.
that only means that AAC, is not correctly freeing the objects.

**Comment by Janmm14** [comment]
We'll see what @konsoals can do.

**Comment by jeinine** [comment]
posted two heap dumps, i will not provide anymore data, i will stop using aac for the time being.

**Comment by Janmm14** [comment]
reasonable

**Comment by geNAZt** [comment]
Are you sure you unload your worlds? The Heapdumps you put up show that in the 9GB one 939 Worlds are loaded.

**Comment by jeinine** [comment]
@geNAZt that has to do with the SkyWars Plugin named "SkyWars Reloaded", that may be the count of the arenas played on that day, but the ram of these "arenas" and "worlds" are freed up on almost 99% of the ram unlike the issue with aac.

And also, if you see a big amount of chunks loaded, most of them are null inside.

the issue of the ram has stopped after removing aac, and using NCP instead.

**Comment by Janmm14** [comment]
An issue being added to the milestone means that its either fixed in code or going to be fixed in code.

**Comment by SnakeDaoust1232** [comment]
@konsolas I don't think this is fixed. I've ran tested, im going to PM you on discord about it.

**Comment by SnakeDaoust1232** [comment]
@jeinine Hi. Are you still having issues because i am having issues. Using the most recent update of AAC.

**Comment by jeinine** [comment]
I have not further issues with aac considering memory leaks.
