### ISSUE TITLE
Step Bypass

### ISSUE THREAD

**Issue by timothydavidhart** [konsolas/AAC-Issues#768]
PLEASE read the guidelines for contributing which is linked above.

Issue description

Step bypass

Please include details like:
IGN: 25GB
Recorded 2:30 AM PST 6/20/17
https://www.youtube.com/watch?v=jR_WiGfYJv0.

Core information

Server version: 1.8.8? it's your test server

AAC version: 3.2.0

ProtocolLib version: your server no idea

Plugin list: aac and protocollib?

**Comment by Janmm14** [comment]
#508
