### ISSUE TITLE
Soul Sand and Fences bug

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#77]
When you sneak on the edge of a fence right next to soulsand, it detects as speed. https://www.youtube.com/watch?v=Qo-Ai302DZQ

**Comment by CeIebrimbor** [comment]
Wait, you have a movements cheat activated. ???

**Comment by Rqcco** [comment]
No, I had no speed mod on.

**Comment by Janmm14** [comment]
But sprint?

**Comment by Rqcco** [comment]
Sprint is basically the same thing as sprint, if you go on the server you can test it out :)

**Comment by Rqcco** [comment]
Toggle sprint*

**Comment by konsolas** [comment]
Fixed.
