### ISSUE TITLE
Mining = "Constantly clicking at a CPS of 20"

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#772]
Consistent_Check works great for autoclicker detection related to fightbots, but has the tendency to flag(unlimited vl) for a consistent 20 CPS when a player is mining blocks like dirt, glowstone and grass with ~~various pick types and efficiencies~~ their bare hand(no pick or shovel).

This is great and not an issue for all pvp/minigame servers like Gomme, but prison/survival/faction/etc servers are screwed for doing a vanilla task :/

**Comment by CeIebrimbor** [comment]
Need to add. I tested 50+ different block/enchant/pick/potion combos and could not reproduce (I gave up).

But...a customer came to me and said players are getting kicked by Fightspeed for mining blocks with their hands

Logs of player mining dirt with hand:
https://pastebin.com/N7XiVv3N

**Comment by konsolas** [comment]
Next version will exclude animation check if the player is looking at a block.

Should be noted that I'm completely unable to reproduce this, and this change is being added without testing.
