### ISSUE TITLE
Elytra Bugs Consolidated | Elytra Check Rewrite

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#773]
Compilation of existing Elytra bugs

- [x] Flying in and around water (with and without firework boost)
Original Issues: #719 and #382 

- [ ] Firework boost straight up = kick
https://youtu.be/bPcmm6EVFdE
Original Issue: #714

- [ ] Jump/Fly spam = detection
https://streamable.com/mb9sg
Original Issue: #682 (Edit: Also see #829)

- [ ] High ping players get frequent (unplayable) detection and lagbacks
https://pastebin.com/2YfsVmP0
Original Issue: #947

**Comment by jQuery0** [comment]
@konsolas fix elytras plsss

**Comment by Janmm14** [comment]
Fixed with 3.3.0?

**Comment by Janmm14** [comment]
related: #829

**Comment by CeIebrimbor** [comment]
Water is fixed. 

Flying up with rockets is kinda better, but not fixed:
https://pastebin.com/jePkE8XC

Jump spamming is not:
https://pastebin.com/MuLbvqwX
