### ISSUE TITLE
[Suggestion] Multiple Commands on Ban

### ISSUE THREAD

**Issue by thedarthonian** [konsolas/AAC-Issues#776]
So currently under `ban_command:` you can only include on command. Could you add a feature so that we can do this:

ban_command: 
    - "tempban {player} Hacking"
    - "mail send _Darth {player} has been banned for hacking"

This is just an example, but it'd be handy incase we want to review evidence, or notify staff so they don't double ban.

**Comment by CeIebrimbor** [comment]
@konsolas 
I think the ";" separation for multiple arguments used to be supported in past AAC versions. Maybe you just make that accepted.  

If you run this in console, it works, but AAC does not like it:
"tempban Konsolas Hacking;mail send _Darth Konsolas has been banned for hacking"

**Comment by konsolas** [comment]
Actually, after rechecking the code, it turns out that multiple ban commands can be run if delimited by a semicolon.

Closing because the feature already exists.
