### ISSUE TITLE
False detections with potion effects

### ISSUE THREAD

**Issue by WhyUStealMyKIll** [konsolas/AAC-Issues#777]
I have found that my players get kicked and detected easaly when they have haste on (kill aura detections) when they have haste, and go mining, they get kicked, is there a plugin that can be used to test for potion effects before executing a command? or is this something that can be fixed. and the players have an average ping of 50-150

### Core information
**Server version**: 1.8.8

**AAC version**: 3.1.7

**ProtocolLib version**: 4.3.0

**Plugin list**: http://imgur.com/a/yaviY

### Special environment information
none

**ViaVersion version**: insert

**ProtocolSupport version**: insert

**ViaBackwards version**: insert

**BungeeCord plugins**: insert

### Reporting issues encountered on the test server has these additional rules:

* Make sure the bug is still present at time of submitting your issue
* Plugin list, log, AAC and ProtocolLib version not required
* Note date and time when the issue occurred here: 
2017/06/23

**Comment by CeIebrimbor** [comment]
Could you provide aac detection logs? Of KillAura detection while mining. Players should not be getting detected at all for this while mining so maybe it was a coincidence or misunderstood message.

**Comment by CeIebrimbor** [comment]
Please update to AAC 3.2.1 and downgrade your ProtocolLib to v4.2.0 (for 1.8).
