### ISSUE TITLE
Bad Lag | 3.2.1

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#778]
Info:
- When you login, it seems to lag you. Unable to type commands, and if you try moving, it seems to glitch/teleport you back to the block you logged in at.
- In the video, im logging in and typing /tps. I should be getting an instant response but its not instant. This happens on all the servers that i have updated to 3.2.1. Doesn't happen on 3.2.0

Video: https://www.youtube.com/watch?v=dl07qWx5VE4&feature=youtu.be

Core information

Server version: Tacospigot 1.8.8
AAC version: 3.2.1
ProtocolLib version: 4.2.0
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.1.1
ProtocolSupport version: 4.22.1
BungeeCord plugins: (Upon request)

**Comment by Janmm14** [comment]
Get some timings when some people join/leave please.

**Comment by SnakeDaoust1232** [comment]
@konsolas @Janmm14 Here is a timings report with verbon: https://timings.aikar.co/?id=6809d6929935493fa92e93f522447b24#plugins

**Comment by CeIebrimbor** [comment]
AAC::Task: me.konsolas.aac.aE$$Lambda$68/1611831285 (interval:1) (SELF)
That guy seems to be the one we are after. Average 29% consumption and up to %36 at the worst point.

**Comment by SnakeDaoust1232** [comment]
So i was doing some testing and it may be due to my spigot.jar. I will do some testing on my end and close this issue if it was on my end.

**Comment by SnakeDaoust1232** [comment]
Might be on my end. Will make a new issue if this is an issue.

**Comment by Janmm14** [comment]
This issue looks different. I thought I would see high usage on the PlayerJoinEvent, but its not.

Some questions:
- Does this happen always or just if you leave and rejoin within 10 minutes?
- Are you suspected cheating by AAC (any verbose output in your time being stuck)?
- Do you have AAC's phase check enabled?

**Comment by konsolas** [comment]
Seeing as AAC doesn't affect commands (apart from registering its own through bukkit), this is likely not an AAC issue.

**Comment by SnakeDaoust1232** [comment]
@konsolas https://timings.aikar.co/?id=25a2eda0cb5b4432b125ce5aa5c1e79c 45 players online
