### ISSUE TITLE
Custom Verbose

### ISSUE THREAD

**Issue by OWERLORD01** [konsolas/AAC-Issues#779]
I think that a good idea will be to make verbose messages customizable with
Placeholders like this: [AAC] {player} failed {check} [vl:{vl}, info:{info}, world:{world}, tps: {tps}, ping:{ping}]

**Comment by Janmm14** [comment]
I don't see a reason why you think you're in a position that you can make suggestions to AAC.

**Comment by CeIebrimbor** [comment]
I agree with the first statement.

I do like the idea though. Information is helpful and more placeholders are always nice. I am pretty bias towards more and more customizable options ;)
