### ISSUE TITLE
Cobweb Bug

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#78]
When you sprint into cobwebs, and spam the space bar, you get detected for speed. https://www.youtube.com/watch?v=W5uKWqWwuns

**Comment by konsolas** [comment]
Fixed and tested. (Test case: http://i.imgur.com/KZnIWNO.png)

**Comment by Rqcco** [comment]
#158

**Comment by v0idst4r** [comment]
For reference: http://youtu.be/W4Mg5BqzWok?hd=1

**Comment by Photon-GitHub** [comment]
Fixed, tested by me.
