### ISSUE TITLE
[Suggestion] custom AAC listener priority

### ISSUE THREAD

**Issue by jiangdashao** [konsolas/AAC-Issues#780]
I think AAC can add Listener-priority in **some checks**
such as FastBreak/FastPlace
AAC always use MONITOR priority, it will cause compatibility problem in some times.
for example:
  A mini-game plugin listen BlockBreakEvent in Normal priority,and it saves data to HashMap about player has breaked the block,but if AAC **cancel** the event in MONITOR priority....it will cause some blocks cant break

I suggest add listener pripority setting in FastBreak FastPlace Nuker check

**Comment by Janmm14** [comment]
AAC currently doesn'T use monitor for its listeners.

**Comment by Janmm14** [comment]
If you think its on monitor, I am going to mark this as a bug.

There is no support in craftbukkit's event systen for adjustable listener priorities.

**Comment by konsolas** [comment]
Listener priority for fastbreak is LOWEST, listener priority for fastplace is HIGHEST & ignoreCancelled (to improve compatibility with world protection plugins).
