### ISSUE TITLE
TP aura bypass

### ISSUE THREAD

**Issue by level147Missingno** [konsolas/AAC-Issues#781]
https://youtu.be/WrtBKNY4YKQ

JigSaw client
TP aura setting: http://imgur.com/a/1Dh8k
by the way, make sure target is set to players only or this bug will fail.

**Comment by byCaptain** [comment]
that's not the latest aac, try it on gommehd.net

**Comment by w-o-a-h** [comment]
its not bypassing at all you are flagging like crazy and on a server without latest aac

**Comment by Janmm14** [comment]
Can't reproduce on AAC 3.2.0 with jigsaw 0.25 for 1.8.8, it flags like hell and gets cancelled all over the place, regardless of settings used.

**Comment by Janmm14** [comment]
I can't properly test

**Comment by Janmm14** [comment]
fixed in 3.2.1-b1
