### ISSUE TITLE
Heuristic placeholder (pattern & confidence)

### ISSUE THREAD

**Issue by Games4k** [konsolas/AAC-Issues#784]
Hello
Can you please add heuristic pattern placeholder to let staff in aac staff notifications by what pattern player got detected.

Edit: confidence placeholder would be awesome too! I really hope you'll add it :)

Thanks :)

**Comment by konsolas** [comment]
Unfortunately the placeholders are handled separately from the checks, so a player might have no detections when the heuristic placeholder is used, so this wouldn't work.

**Comment by Janmm14** [comment]
In theory an external plugin could handle this by listening for the PlayerViilationEvent, providing a command for replacement, inserting `-` when there was no heuristic detection.
