### ISSUE TITLE
Entity speed and step bypass

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#786]
Please include details like:
* AAC logs / Full console error **In video**
* Video of the bug / bypass, best with verbose chat output **https://youtu.be/URmEH23I_LI**
* The ingame name of the involved players **Slimerblue22ALT (Cracked) Dark_Lord68 (Premium)**

### Core information
**Server version**: 
![image](https://user-images.githubusercontent.com/29098956/27549889-915819e4-5a6b-11e7-9a06-11abc5fbe37f.png)

**AAC version**: **3.2.1**

**ProtocolLib version**: 
![image](https://user-images.githubusercontent.com/29098956/27549913-a791667a-5a6b-11e7-92a4-5391ff21b7e2.png)

**Plugin list**: 
![image](https://user-images.githubusercontent.com/29098956/27549944-ca0778b6-5a6b-11e7-974b-829b31d6a4fd.png)

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 
![image](https://user-images.githubusercontent.com/29098956/27550053-32630f74-5a6c-11e7-959f-79c99fb04929.png)

**ProtocolSupport version**: **None**

**ViaBackwards version**: **None**

**BungeeCord plugins**: 
![27240515-041d52da-52a3-11e7-85a0-68322eae9407](https://user-images.githubusercontent.com/29098956/27550027-1c67c106-5a6c-11e7-9db2-2b1fd35f17a9.png)

**Comment by x0XP** [comment]
can u pls stop reporting my 1337 bypasses kthnxbai

**Comment by v0idst4r** [comment]
#843 duplicate?

**Comment by konsolas** [comment]
of #843

**Comment by Slimerblue22** [comment]
I thought the ones that got flagged as dupes were the newer ones not older? Well whatever as long as it is handled I don't think it matters

**Comment by Janmm14** [comment]
I guess that was a simple mistake, but it will be handled some time in the future.
