### ISSUE TITLE
Jigsaw's Ghost Aura fully bypassing

### ISSUE THREAD

**Issue by jQuery0** [konsolas/AAC-Issues#788]
**Information**
Not really much to say, Jigsaws Ghost Aura is fully bypassing the Killaura and Heuristics check.  

Server version: Spigot 1.9.4
AAC version: 3.2.1
ProtocolLib version: 4.2.1
Plugin list: ViaVersion, ProtocolLib, AAC

EDIT:
It's also bypassing on test.kons.co (official test server)

**Comment by SnakeDaoust1232** [comment]
video?

**Comment by jQuery0** [comment]
Go onto the test server and see it by yourself? Ain't recording 10+ minutes to show a bypass.

**Comment by Games4k** [comment]
Set heuristic confidence to 60 and you'll be good to go.
I'm using it on my server for more than 1 month and i'm not getting any false positives.

**Comment by jQuery0** [comment]
Nah, not doing that. I've tried setting it on 70 before and some good pvpers are getting flagged really fast

**Comment by SnakeDaoust1232** [comment]
I personally have got the heuristic check up to 82

I have mine set at 84 and have 0 FPs

**Comment by konsolas** [comment]
Closing as duplicate of #811
