### ISSUE TITLE
Teleport method Sag 0.5-2.0

### ISSUE THREAD

**Issue by MeowMiaoMiao** [konsolas/AAC-Issues#789]
AAC version: 3.2.1 
Server version: spigot 1.8.8
Please look at pictures

http://imgur.com/s8xKP32
http://imgur.com/ZyOAMRm

**Comment by w-o-a-h** [comment]
please upload to http://imgur.com/ because that website is very slow and wont load the images.

**Comment by MeowMiaoMiao** [comment]
http://imgur.com/s8xKP32
http://imgur.com/ZyOAMRm

**Comment by CeIebrimbor** [comment]
#753
