### ISSUE TITLE
AAC causing bad LAG | 3.2.1 (Critical)

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#790]
For some reason, AAC is causing extremely bad lag over time. To the point where eventually my server gets down to like 5 TPS then crashes. I think it could be related to this error that i posted, but im not sure. (https://github.com/konsolas/AAC-Issues/issues/787) I am going to post a 15 minute timings report that i gathered to show you what im talking about.

Note that this lag is happening with under 75 players online.
- TacoSpigot 1.8.8

Timings(15 Minutes): https://timings.aikar.co/?id=23eb6b28875946b99c168ed93c584573

- I tried disabling the speed and fly check but it only helped a bit. Server still was lagging alot.
- I tried to disable the movement manager to see if that would have an effect but everyone just started to get flagged for velocity so i had to re-enable it.

Update:
- I was forced to remove AAC from the server. I tried spartan but spartan also has its own lag issues. With all of this being said, i was forced to use a skidded janitor anti-cheat temporarily. Which i dont like very much.

**Comment by SnakeDaoust1232** [comment]
@CeIebrimbor @Janmm14 @konsolas

**Comment by freak-dk** [comment]
Experiencing similar results on 1.11.2 PaperSpigot 
https://prnt.sc/fppooq (90+ players online)

All movement and world checks disabled. 
I only use AAC for its combat checks atm.

**Comment by SnakeDaoust1232** [comment]
@konsolas As well. That "login" lag is still a thing when im using AAC 3.2.1. This whole update is full of performance issues. Lag, mem leak. :( Hopefully is fixed soon.

**Comment by konsolas** [comment]
-b1
