### ISSUE TITLE
Null Pointer Exception | While kicked for Velocity

### ISSUE THREAD

**Issue by FinalPacket** [konsolas/AAC-Issues#791]
PLEASE read the guidelines for contributing which is linked above.
### Issue description

Hello, I have recently purchased AAC to find, a bug, that when I am kicked for using a hack, it throws an error into the console for packet receiving. After the kick, I have also been flagged for sending unusual movement when I am not in the game, I cannot be kicked by AAC for some reason again while using the same hack (Speed), so I cannot reproduce it. I was kicked for Not taking knockback.

http://prntscr.com/fp9c5f

### Core information
**Server version**: Spigot 1.8.8-R0.1-SNAPSHOT

**AAC version**: 3.2.1

**ProtocolLib version**: 4.3.0

**Plugin list**: ProtocolLib, PermissionsEx, AAC (3.2.1)

### Special environment information

**ViaVersion version**: None

**ProtocolSupport version**: None

**ViaBackwards version**: None

**BungeeCord plugins**: None (But I do use BungeeCord)

**Comment by CeIebrimbor** [comment]
Please utilize ProtocolLib v4.2.0. AAC's 1.8.8 is still built on that. 4.3.0 is really only for 1.12 at the moment.
http://ci.dmulloy2.net/job/ProtocolLib/341/
