### ISSUE TITLE
AAC extreme lag and spam errors

### ISSUE THREAD

**Issue by Metisuneatn** [konsolas/AAC-Issues#792]
https://pastebin.com/TRdM9agV

Had to put it in pastebin, the errors are crazy long for only a small window. Several different exceptions in there so I just left the entire thing. 

Servers on 1.12 and we just put this in with the fresh config. Had done some minor changes and disabled some stuff on it. Had to remove the plugin right away due to extremely lag to the point where no one could do anything at all.  This was all yesterday, on the version avail on spigot.

**Comment by FinalPacket** [comment]
Are you using the right version of ProtocolLib?
Also, please use the issue template
https://github.com/konsolas/AAC-Issues/blob/master/ISSUE_TEMPLATE.md

**Comment by SnakeDaoust1232** [comment]
Same! On 1.8

**Comment by freak-dk** [comment]
Experiencing similar results on 1.11.2 PaperSpigot 
https://prnt.sc/fppooq

All movement and world checks disabled. 
I only use AAC for its combat checks atm.

**Comment by Metisuneatn** [comment]
server version: 1.12
aac version: the one on the spigot page (removed now, the server was unplayable)
protocollib version: 4.3.0

everything's updated

**Comment by konsolas** [comment]
-b1.
