### ISSUE TITLE
Feature: AACNotify On/Off

### ISSUE THREAD

**Issue by jeinine** [konsolas/AAC-Issues#793]
Hello, could it be possible to create a command to prevent Staffs with the permission aac.notify to receive AAC notifications & viceversa?

Many people find it annoying or at least on my server due to the amount of players.

**Comment by konsolas** [comment]
It could be possible to create a command that automatically toggles the permission for staff members. This won't be added to AAC because it doesn't seem necessary when compared to the spam one might get from verbose.
