### ISSUE TITLE
Vehicle check bug on horses 

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#794]
Please include details like:
* AAC logs / Full console error **In video**
* Video of the bug / bypass, best with verbose chat output **https://www.youtube.com/watch?v=IcYYHFDAtX8**
* The ingame name of the involved players **Slimerblue22ALT (Cracked)**

### Core information
**Server version**: ![image](https://user-images.githubusercontent.com/29098956/27549889-915819e4-5a6b-11e7-9a06-11abc5fbe37f.png)

**AAC version**: **3.2.1**

**ProtocolLib version**: ![image](https://user-images.githubusercontent.com/29098956/27549913-a791667a-5a6b-11e7-92a4-5391ff21b7e2.png)

**Plugin list**: ![image](https://user-images.githubusercontent.com/29098956/27549944-ca0778b6-5a6b-11e7-974b-829b31d6a4fd.png)

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: ![image](https://user-images.githubusercontent.com/29098956/27550053-32630f74-5a6c-11e7-959f-79c99fb04929.png)

**ProtocolSupport version**: **None**

**ViaBackwards version**: **None**

**BungeeCord plugins**: 
![27240515-041d52da-52a3-11e7-85a0-68322eae9407](https://user-images.githubusercontent.com/29098956/27550027-1c67c106-5a6c-11e7-9db2-2b1fd35f17a9.png)

**Comment by Slimerblue22** [comment]
@geNAZt Sorry to question you, why is the bypass label on this? I do not see how this is considered a bypass, if it is could you please explain it to me, thanks.

**Comment by konsolas** [comment]
Seems to be a mistake.
