### ISSUE TITLE
TacoSpigot causing severe performance issues

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#795]
~~Note: I haven't tested PaperSpigot 1.8.8 although TacoSpigot is just PaperSpigot with like 5 more config options... i think.... xD~~

I ran two timings, one on TacoSpigot 1.8 and one on regular Spigot 1.8. The results are shocking. TacoSpigot is causing AAC to lag the server like crazy whereas regular spigot "allows" AAC to have a very small footprint. Take note, these timings are taken when the server has under 50 players online. I am making this issue so that we can get to the bottom of this. Like i told @konsolas in DM, i need TacoSpigot for my factions server due to the hopper optimizations.

TacoSpigot 15 minute timings: https://timings.aikar.co/?id=6b9cd67be8bd48a89d1467eb8e3a7d09#timing
PaperSpigot 15 minute timings: https://timings.aikar.co/?id=e8ffa8047ecf47c6bb11e8dbf72eb275
Spigot 15 minute timings: https://timings.spigotmc.org/?url=rowejoteka

Link to TacoSpigot: 
 - GitHub: https://github.com/TacoSpigot/TacoSpigot
 - BuildServer: https://ci.techcable.net/job/TacoSpigot-1.8.8/

If you have any ideas as to why TacoSpigot may be causing this, please let me know.

**Comment by Hyronymos** [comment]
we had big performance problems with aac and tacospigot too

**Comment by SnakeDaoust1232** [comment]
@Hyronymos Noted.

**Comment by SnakeDaoust1232** [comment]
@konsolas I added a timings report for PaperSpigot just for reference.

**Comment by Janmm14** [comment]
Is this done with 3.2.1-b1? Is there any notable difference to 3.2.1 in TacoSpigot timings with same amount of users?

**Comment by SnakeDaoust1232** [comment]
Yes 3.2.1-b1. It happens in 3.2.1 as well. I haven't tested any versions prior to 3.2.1 though.

**Comment by CeIebrimbor** [comment]
Is this still relevant? I'm not sure AAC will be going out of the way to accommodate 🌮. But maybe recent builds of Taco, ProtocolLib and/or AAC have remedied the reported performance issues?

@SnakeDaoust1232 (or anyone using TacoSpigot)

**Comment by Janmm14** [comment]
Internal stuff of movement checking (causing most issues) was changed combined with performance improvements made by konsolas in cooperation with genazt.

Please create a new issue in case of performance problems with recent versions of AAC.
