### ISSUE TITLE
[Feature] Machine Learning Heuristic

### ISSUE THREAD

**Issue by Games4k** [konsolas/AAC-Issues#796]
One thing that I would be suprised to see in AAC is machinelearning heuristic. ( @konsolas already tried it before https://www.spigotmc.org/threads/anti-cheat-machine-learning-anti-killaura.145835/)

Good MachineLearning will probably fix all killaura/aimbot (and _probably_ some triggerbot) bypasses

I know its pretty hard to do something like this, but this is a great idea for AAC. I hope you'll release something like this in the futuer :)

Thanks

**Comment by jiangdashao** [comment]
ML is not good at killaura detection
it is slow,and maybe have false positives
and it even maybe have performence issue.

**Comment by CrackFileso** [comment]
I think it's bad for performence.

If aac has ML ,Might each server need to have i7 cpu >3

**Comment by Games4k** [comment]
> I think it's bad for performence.
>
> If aac has ML ,Might each server need to have i7 cpu >3

Everyone with slower server can turn it off.

**Comment by SnakeDaoust1232** [comment]
It already has machine learning.. right? @konsolas

**Comment by iConfueZ** [comment]
^
http://prntscr.com/fr8544

**Comment by konsolas** [comment]
combat.Heuristics already makes use of machine learning in some patterns.
