### ISSUE TITLE
[Feature Request] An option to disable update checker

### ISSUE THREAD

**Issue by UnioDex** [konsolas/AAC-Issues#8]
Sometimes AAC is starting too late because of update check proccess. Update site can be blacklisted or down. I already checking spigot every day so i dont need that auto check. So i want that add an option to disable update-check.

**Comment by Janmm14** [comment]
Remember startup will take more time even without update checking due to the antipiracy system.

**Comment by UnioDex** [comment]
Yes but it may reduce (hope).

**Comment by konsolas** [comment]
In view of what Janmm14 said, it will make pretty much no difference to disable the update checker, so there isn't much point.
