### ISSUE TITLE
NoClip Speed Bypass

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#80]
On the Impact Client, NoClip can be used like a speed bypass. https://www.youtube.com/watch?v=6155Pi49LX8

**Comment by konsolas** [comment]
It doesn't seem to be any faster than normal sprinting or sprint jumping.

1.

**Comment by Photon-GitHub** [comment]
Moreover I doubt that a mod that is made to walk through walls will increase your speed as it is harder to phase with high motion.

**Comment by Rqcco** [comment]
@konsolas This report that you closed seems to actually be faster than sprinting and jumping. Janmm14 and I tested it out.

**Comment by Rqcco** [comment]
NoClip is Still faster on the Impact Client, so It's still considered a "speed hack".

**Comment by Janmm14** [comment]
That NoClip speed is probably the same as #106, it simply is faster walk speed. @konsolas @Rqcco

**Comment by Photon-GitHub** [comment]
Still a thing

**Comment by konsolas** [comment]
Fixed and confirmed by Rqcco.
