### ISSUE TITLE
3.2.1 beta1 getting knocked off horses

### ISSUE THREAD

**Issue by Fonzee9** [konsolas/AAC-Issues#800]
It detects fly when riding a horse no logs needed just detects fly.

**Comment by Slimerblue22** [comment]
I've already reported this https://github.com/konsolas/AAC-Issues/issues/794

**Comment by Janmm14** [comment]
The `b` does not mean `beta`, but `build` and is meant for small changes that don't qualify for a next real version.

Closing as duplicate.
