### ISSUE TITLE
Detect step hacking

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#802]
### Core information
**Server version**: PaperSpigot 1.11.2

**AAC version**: 3.2.1 with default configuration

**ProtocolLib version**: 4.3.0 release

**Plugin list**: upon request

### Special environment information

**BungeeCord plugins**: upon request

Video: https://youtu.be/qUQsOACJZY0?t=2m21s (/aac at the begining of the video)

(Velocity Bypass - resolved) How I give players velocity (these lines are inside an async thread): https://pastebin.com/ApAjhi3x

**Comment by Janmm14** [comment]
Apart from the bukkit api should only be used synchronized except otherwise mentioned, the code looks ok.
Did you tried without the slowness effect?

**Comment by MClausz** [comment]
Tried with the synchronized code and the same result. I always use async thread if possible for performance reason.
Haven't tried it without the slowness effect, I cannot remove the slowness effect due to the game's rule.
Older version of AAC can detect velocity well, can't remember the exact version.

**Comment by MClausz** [comment]
After putting the set velocity part to the runnable like this, AAC can detect it well now.
https://pastebin.com/p6fs7s0E
Step can still be bypassed tho.

**Comment by Janmm14** [comment]
Step is officially not in the detected cheat list.
Although I think it should get detected soon.
