### ISSUE TITLE
Jump Potion Effect Detected as hacking!

### ISSUE THREAD

**Issue by BlackDemonZetaxd** [konsolas/AAC-Issues#804]
Hello Konsolas! I have a Skywars that have a feature to vote for Super Jump mode, the super jump mode applies a Jump potion effect very high, but its detected as fly and it gets back you down to the ground on jumping, hope you can fix this, a lot of people have this skywars plugin.
Thanks.

**Comment by CeIebrimbor** [comment]
I have gotten same reports. Many servers allow Jump III+, some much higher.

**Comment by Games4k** [comment]
I dont recommend using aac3 for skywars. Use aac2 or aac1 for it. They detect combat hacks more quickly and for fly bypasses just enable every component on normalmovements. For speed bypasses download old free version of aacaddition

https://www.spigotmc.org/resources/aacaddition.30217/history

Dont use version 0.9. Just use 1.8.2 for aac2, or if you installed aac1 use 0.8.2 - 1.8.8

P.S. Btw i dont know is it still possible to downlpad them :P Im correctly on my tablet, so i'll check when i get home :)

**Comment by Janmm14** [comment]
@Games4k I recommend to never use AAC 1 or AAC 2.
AACAddition does not fix all bypasses, Killaura detection is still useless.

@BlackDemonZetaxd 
If you have a developer, you could tell him to cancel the PlayerViolationEvent if the player has a certain jump potion effect.
He should check HackType and message to be equal to the corresponding jump potion level.

**Comment by BlackDemonZetaxd** [comment]
@Janmm14 i dont have a developer, thats why im asking here to ignore fly check with jumping with jump potion :c

**Comment by Janmm14** [comment]
What will happen hopefully in the next version that AAC adds in the correct calculation and its done for all jump potions. There will not be something like "ignore people with jump potions" inside aac, that usually just happend in really low-quality anticheats.

**Comment by konsolas** [comment]
Bounced around with jump boost 1-50 and had no issues.

**Comment by CeIebrimbor** [comment]
Maybe obsolete AAC or using another AC with AAC?
