### ISSUE TITLE
Aristois 1.12 seems to bypass AAC

### ISSUE THREAD

**Issue by ncf1** [konsolas/AAC-Issues#806]
'Observed client' admitted to and demonstrated multiple functions from Aristois 1.12 bypassing AAC. Speed, Extra Elytra, BowAimbot. Cannot provide video of testing on test server because there is no 1.12 test server.

**Comment by Janmm14** [comment]
Provide video on other server, provide download link, provide video of someone else showing the client bypassing.
Additionally, the elytra check in AAC is pretty lenient as far as I know.

**Comment by ncf1** [comment]
Will append with logs related to the various potential bypasses/ link to bypassing mod once the client with aristois returns.

Versioning for various plugins are all most recent release as of ~7/2/2017, plugin list as follows:
Spigot 1.12
http://i.imgur.com/LSnibx5.png
http://i.imgur.com/OZQ2Wxk.png
Current configuration (non vanilla- hence my desire for 1.12 test server, likely containing misconfigurations intended to handle unrelated false positives)
https://pastebin.com/f0NCa4ue

would be willing to reset to vanilla configuration if recomended, but this would also result in multiple unrelated issues- kicks for horse riding, kicks for treefeller, kicks for elytra + fireworks, possibly others i forgot, which are NOT related to this issue and should be disregarded for the purposes of this issue report.

video is currently beyond my means as i do not know anything about making videos, nor the hack in question- i am simply detailing what a user on my server is doing. client in question was willing to attempt to use these mods on a vanilla test server but one does not exist beyond version 1.8.8 that i am aware of.

**Comment by Games4k** [comment]
> 'Observed client' admitted to and demonstrated multiple functions from Aristois 1.12 bypassing AAC. Speed, Extra Elytra, BowAimbot. Cannot provide video of testing on test server because there is no 1.12 test server.

I tested Aristois 1.12 before and Speed is 100% not bypassing it... Speed is the worst speed ever, every anticheat can detect it. ExtraElytra is probably bypassing, AAC elytra check is not the best... And its not possible to block BowAimbot!

**Comment by ncf1** [comment]
in our testing, the client in question and myself came to agree that the bow aimbot is trash and not really an issue in actual play, just felt that it should be noted.

**Comment by ncf1** [comment]
The client in question has not returned since so i cant provide logs, but from memory of the initial event, i recall simply that there were no entries for this player when he was showing me his varying bypasses. Since i cannot provide the rest of the desired info i shall have to just hope this was a unique event.
