### ISSUE TITLE
Idea to improve MultiInteract check 

### ISSUE THREAD

**Issue by GeoGamerLP** [konsolas/AAC-Issues#808]
First I have to say that this IS bypassable, but it will detect most outdated client.

If you open a chest, the mouse is always a bit below its lowest slot row meaning that legits need a certain time to pick items from the upper ones near the "corners" (especially for a double chest).

Literally all cheststealers go from the first slot to the last one. Mostly the delay is so low that the item(s) of the upper slots near the "corners" are picked up faster than a legit could do -> Detection.

I know that you could bypass that like the old autoarmor check by waiting a bit before picking items or just go from the last slot to the first one, but something is better than nothing.

**Comment by CeIebrimbor** [comment]
AAC does not handle inventory checks
