### ISSUE TITLE
Interacting Suspiciously Bug 

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#81]
Every time you break leaves (While holding RIGHT click and LEFT click at the same time) it flags for interacting suspiciously. https://www.youtube.com/watch?v=rmuunR0yZnI

**Comment by konsolas** [comment]
You are interacting suspiciously by going through blocks.

ImpossibleInteract is a mitigation tool: if the block behind was a chest, you wouldn't have been able to open it. It doesn't kick, so this is intended behaviour.
