### ISSUE TITLE
Heuristics specially for "Ghost/Legit" auras

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#811]
Hello,

Title is pretty self explanatory, add some heuristics designed to detect Ghost/Legit-auras. Clients such as Flux, Liquid Bounce, Jigsaw have those auras and they fully bypass both Killaura normal and Heuristics.

Well, that's it...

**Comment by SnakeDaoust1232** [comment]
Lets get the hitbox issues with the hitbox check and the killaura check before there is any additions to it. Please? :(

**Comment by Games4k** [comment]
> Hello,
>
>Title is pretty self explanatory, add some heuristics designed to detect Ghost/Legit-auras. Clients such as Flux, Liquid Bounce, Jigsaw have those auras and they fully bypass both Killaura normal and Heuristics.
>
>Well, that's it...

Flux and jigsaw are blocked by combat.KillAura. Liquidbounce is blocked by heuristic. Tested (confidence 60). Idk if it blocks liquidbounce on confidence 80, but I'm sure AAC can block all of them really fast. It would be good to add some heuristic for vape and vega clients (aimassist). Also, heuristic can also block every type of aimbot/aimassist on liquidbounce and flux, so this is not very big problem :P

**Comment by iConfueZ** [comment]
> `Flux and jigsaw are blocked by combat.KillAura. Liquidbounce is blocked by heuristic. Tested (confidence 60). Idk if it blocks liquidbounce on confidence 80, but I'm sure AAC can block all of them really fast. It would be good to add some heuristic for vape and vega clients (aimassist). Also, heuristic can also block every type of aimbot/aimassist on liquidbounce and flux, so this is not very big problem :P`

The regular killaura is indeed blocked by combat.Killaura, however Ghost/Legit Aura isn't. I've tested it on my server and on test.kons.co. Setting Heuristics on confidence 60 isn't good, as I've seen a lot of people getting false banned on my server.

**Comment by Games4k** [comment]
Yes it is! And dont test it on test server, there are some problems with killaura. Killaura and Heuristic are different. Something is wrong there!

**Comment by Janmm14** [comment]
I personally would advice against confidence 60 and use 80 instead.

I don't know what you are experiencing with combat.Killaura exactly, but you can see it working if you turn on truesight and start fighting playersize like entities

**Comment by Games4k** [comment]
I know, I saw it but it wasnt detecting flux... Its not normal... (tested like a one month ago)... It might be fixed? Btw, confidence 60 is perfectly safe but ok...

**Comment by Janmm14** [comment]
@Games4k Maybe confidence 60 is safe for your playerbase, but in general terms, a confidence of 60 contains false positives. If you are not banning but letting your staff get notified, all is okay.

**Comment by konsolas** [comment]
New heuristics seem to detect jigsaw ghostaura at a confidence of around 79%.
