### ISSUE TITLE
Wurst Settings bypass all KA checks

### ISSUE THREAD

**Issue by thedarthonian** [konsolas/AAC-Issues#812]
### Issue description
Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: 1.12

**AAC version**: 3.2.1

**ProtocolLib version**: 4.3.0

**Plugin list**: n/a

### Special environment information
**ViaVersion version**: insert (or N/A) N

**ProtocolSupport version**: insert (or N/A) N

**ViaBackwards version**: insert (or N/A) N

**BungeeCord plugins**: insert (or N/A) N

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

Using these settings >> [http://prntscr.com/fth84z](url) on the latest version of wurst completely bypasses killaura checks. I've attacked players for about 10 mins of combat, and animals for about the same, and not even a staff notification has popped up.

**Comment by CeIebrimbor** [comment]
This report had zero effort or evidence...normally we would ask for more information, but there is nothing to even start off...
