### ISSUE TITLE
Citizens players async teleport

### ISSUE THREAD

**Issue by netbiosxx** [konsolas/AAC-Issues#813]
### Issue description
Here's the error,it's spamming the console: 
https://pastebin.com/r55r1yvA

### Core information
**Server version**: 1.12

**AAC version**: 3.2.1-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: Every server does the same problem (I have a network)

### Special environment information
**ViaVersion version**: 1.1.1 & Servers Without (also 1.12)

**ProtocolSupport version**: Nope

**ViaBackwards version**: Nope

**BungeeCord plugins**: ViaVersion (version above) || BungeeTabListPlus 2.7.4 || BungeeResourcePack || SkinsRestorer 13.1.2  || Italogin (custom made,only auth,no dependencies)

### Configuration

Default Config.

**Comment by Janmm14** [comment]
Answer already on spigotmc: https://www.spigotmc.org/threads/aac-advanced-anti-cheat-hack-kill-aura-blocker-paid.63195/page-419#post-2531100

**Comment by Janmm14** [comment]
Plugin MobHunting is teleporting Citizens players asynchroniously. The issue should be fixed inside thr MobHunting plugin.

This could also be a request to ignore Citizens players completely however.

**Comment by konsolas** [comment]
Wontfix due to async teleports not being supported.
