### ISSUE TITLE
Standing "in" a tower of certain non-full blocks makes insanely high highjumps possible (3.2.1+)

### ISSUE THREAD

**Issue by Nvaros** [konsolas/AAC-Issues#815]
This works for any semi-full block that doesn't completely fill a block (e. g. glass panes, iron fences, trap doors) except for cobblestone walls.
If you build a tower of these blocks, go down and move to that as close as you can (You have to go on the block the tower has been placed on!), you can jump higher than legit possible. The higher the tower is, the higher you can jump. I've tested a bit (testservers, Twerion and MCW) and got this "list"

Left = tower's height; right = The maximum jump height (approx.):

1 (only standing with the feet next to a non-full block) => ~2 blocks
2 => up to ~2 blocks
3 => up to ~5.5 blocks (somehow flags if you set your highjump too low)
4 => up to ~19.7 blocks
5 => up to ~39.7 blocks
6 => up to ~63.5 blocks
7 => up to ~94.4 blocks
8 => up to ~115.8 blocks
9 => up to ~148.8 blocks
10 => up to ~183.5 blocks
11 => up to ~218.2 blocks
12 => up to ~254 blocks

The phase detection (=> moved too far away from safe location) prevents that you can jump even higher. It doesn't work with all highjumps though, but for vanilla highjump it does
If anything is unclear, I can show you it on the mentioned servers.
EDIT: Seems to flag when you hit a block with your head.
Still critical.

**Comment by CeIebrimbor** [comment]
Was this with a client? Which? Client specific?

**Comment by GeoGamerLP** [comment]
It works with Jigsaw's vanilla airjump (jumping in midair flags though), Milky's highjumps and especially Liqiudbounce's vanilla one.

**Comment by GeoGamerLP** [comment]
@konsolas @CeIebrimbor Please reopen this. It's an other issue as #807. It's not fixed (3.3.1)

**Comment by Janmm14** [comment]
According to 198102928140009472 (1GuteAlternative#6561) this is not fixed yet.

**Comment by GeoGamerLP** [comment]
I am 1GuteAlternative, and yes, this is not fixed as I tested in on Gomme (min_VL: 12, shouldn't make a difference for this motion) and I could still jump very high using this "trick" (until Gomme's custom anti-stack plugin damages me).

**Comment by Photon-GitHub** [comment]
Please recheck on latest version.

**Comment by GeoGamerLP** [comment]
Same as above, it is still working on both servers (poke.sexy and GommeHD)
