### ISSUE TITLE
Knockback in water causes lagdown (Fly)

### ISSUE THREAD

**Issue by ProDash1998** [konsolas/AAC-Issues#816]
### Issue description

There is a problem with swimming on water. It detects it as a fly hack

### Core information
**Server version**:  1.12

**AAC version**: 3.2.1-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: insert

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**:  N/A

**ViaBackwards version**:  N/A

**BungeeCord plugins**: N/A

### Configuration
https://pastebin.com/PCwebLc4

**Comment by CeIebrimbor** [comment]
AAC logs please (or video with Verbose enabled). What conditions are needed to get detected? Knockback? Depth strider? Potions? Just straight vanilla swimming?

**Comment by ProDash1998** [comment]
Testet at plugins InfernalMobs.
https://youtu.be/vrc7nwddOHw - clear client

 And find bugs plugins or Wurst 
https://youtu.be/-tauQKMSOc0 - killaura

**Comment by ProDash1998** [comment]
And please add check ping to speed hack and flyhack

**Comment by CeIebrimbor** [comment]
> Testet at plugins InfernalMobs.
> https://youtu.be/vrc7nwddOHw - clear client
> https://youtu.be/ylaylmjRuFM
Looks like knockback in water maybe cause for Fly detection.



> And I find bugs plugins
> https://youtu.be/-tauQKMSOc0 - killaura
Is your account being hit an OP? Killaura/Reach will not be detected if the player being hit is OP or has the bypass permission.




> Przyspiesza czas = Speed Hack (badPackets)
> https://pastebin.com/bpWrSGg0
Where is the false detection for Speed that caused kick?




> And bad detect FastBow
> https://pastebin.com/2QQPDRPg config
> video https://youtu.be/1f-9hh76hJk
Looks like the player had a severe connection issue. Ping = 454,000ms.

**Comment by ProDash1998** [comment]
.... no this is bug for ping plugins. My internet DL  100Mb/s UP 20Mb/s

**Comment by CeIebrimbor** [comment]
For now, we will keep this issue focused on the Fly detection in water. Open another issue for unrelated detection issues or bypasses.

**Comment by ProDash1998** [comment]
Looks like knockback in water maybe cause for Fly detection?
i don't know 

Is your account being hit an OP? Killaura/Reach will not be detected if the player being hit is OP or has the bypass permission.

DAS haven't op and permission * 

Where is the false detection for Speed that caused kick?
i create new issues

**Comment by Games4k** [comment]
AAC is detecting Wurst aura, you're probably op? Also, sometimes you have to relogin after deoping your self or wait for 10 seconds before aac can detect you again

**Comment by ProDash1998** [comment]
Account DAS dont have op

**Comment by Games4k** [comment]
Its not possible. I tested wurst and it detected it in a few seconds... You probably did something wrong? Is killaura and heuristic enabled?

**Comment by LapizSeller** [comment]
i'm confirm this issue. Many players complain me about they lagdown when they on water.

**Comment by konsolas** [comment]
No new information was added regarding the original issue of water

**Comment by CeIebrimbor** [comment]
Will re-open if more info is added on the **original** issue.
