### ISSUE TITLE
Bad detection Cheats and bugs for check ping

### ISSUE THREAD

**Issue by ProDash1998** [konsolas/AAC-Issues#817]
### Core information
**Server version**: 1.12

**AAC version**: 3.2.1-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: insert

### Special environment information
**ViaVersion version**:  -

**ProtocolSupport version**:-

**ViaBackwards version**:-

**BungeeCord plugins**:  -

### Configuration
https://pastebin.com/PCwebLc4

last my issues https://github.com/konsolas/AAC-Issues/issues/816

videos 
Bug ping https://youtu.be/isGTHc1G7Ic
Bad detect cheats https://youtu.be/RVX07EKNYsA

These issues will be regular updated

**Comment by CeIebrimbor** [comment]
I see a really crummy hacked client (Wurst) being kicked for hacks (what even looks like attempts to rapidfire and bunnyhop).

Is this a claim about false kicks? Can you show it on a vanilla client?

**Comment by Photon-GitHub** [comment]
Partly invalid as speed can detect various fastbow-mods if they mess with packets.

**Comment by ProDash1998** [comment]
Celebrimbot

Vanilla client antycheat  "havent" bugs
hacked client  antycheat have bugs

**Comment by Games4k** [comment]
Lol I dont understand him at all xD

**Comment by konsolas** [comment]
Everything looks fine here.

**Comment by CeIebrimbor** [comment]
It seriously just sounds like the hacker gets kicked instantly and that is a problem somehow...maybe the language barrier.

**Comment by Janmm14** [comment]
The kick reasons of AAC might differ from the used cheats sometimes. That is not a bug.
