### ISSUE TITLE
NoSlowdown

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#818]
### Issue description
Bypass NoSlowDown exists on Impact and Matrix clients(maybe more). Eating, bow use, water movements (based on many reports).

### Core information
**Server version**: 1.11.2

**AAC version**: 3.2.1-b1

**ProtocolLib version**: 4.2.1

### Special environment information
None

### Configuration
`item_scalar` is set at .741, but the bypasses (after testing) still occur when setting back to .5. One user even tried .1 and still had the bypass.

`threshold` is default

**Comment by Slimerblue22** [comment]
If its when swimming in water no slowdown on Impact does work (I tried it with depth strider 3 idk if it works without the enchant) I was gonna make a report on it but it seams you got that one covered

**Comment by Janmm14** [comment]
Tested with Matix client (without r, is it the same?) - does only bypass like described in issue 934.

**Comment by CeIebrimbor** [comment]
My report was based on feedback from 2 clients 2 months ago when this was reported. I assume I misspelled the client. Nonetheless, NoSlowDown seems to have always been ignored or weak in AAC for a long time.

**Comment by konsolas** [comment]
At some point. Don't see clients with AAC noslow atm.
