### ISSUE TITLE
Criticals detecting on fences

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#82]
When you jump up and down on fences, it detects and kicks for Criticals https://www.youtube.com/watch?v=yaJq64RJK1A

**Comment by CeIebrimbor** [comment]
With or without combat hack on?

**Comment by Rqcco** [comment]
I had no combat/movement mod on

**Comment by CeIebrimbor** [comment]
Just helpful if you include that if you're recording with a hack mod. Or don't use mods when testing bugs XD

**Comment by Rqcco** [comment]
oh haha sorry I will start saying that in my posts, it displays all the mods in the top left, I was just using render mods (Like brightness, tracers, etc.)

**Comment by konsolas** [comment]
Fixed.
