### ISSUE TITLE
FastWeb, faster than normal players

### ISSUE THREAD

**Issue by MrKinau** [konsolas/AAC-Issues#822]
## **Issue description**

You can run much faster in cobwebs than legit players. You will be detected only at the beginning of the webs and after that you can run almost two times faster than legits. In the video below I compared a hacker (video maker) and another player (LlenniTv).

- You can see detection output and bug in video
- https://youtu.be/UnltcV0SBo0
- EaZy b21.54, Movement -> FastWeb

## **Core information**

Server version: 1.8.9
AAC version: 3.2.1-b1 (newest version)
ProtocolLib version: V.4.3.0
Plugin list: AAC, AACAdditionPro, ProtocolLib

Special environment information

ViaVersion version: none
ProtocolSupport version: none
ViaBackwards version: none
BungeeCord plugins: Our own plugins (should not affect aac in any way)

**Comment by Slimerblue22** [comment]
Re-open this issue? FastWeb still works on liquid bounce, I haven't tested other clients
