### ISSUE TITLE
Towering Up Triggers Fly

### ISSUE THREAD

**Issue by SioWolf** [konsolas/AAC-Issues#824]
Holding down jump and right click while looking down builds a tower. Doing this causes players to get flagged by fly.

Similar to #746, but you don't need to quickly look in a certain direction, just build the tower holding down the buttons.

### Core information
**Server version**: Paper-1147

**AAC version**: 3.2.1

**ProtocolLib version**: 4.3.0

**Plugin list**: N/A

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A 

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Using @CeIebrimbor's settings

**Comment by konsolas** [comment]
Having trouble reproducing this. Holding dirt and building a tower by looking down and holding space + right click.

**Comment by konsolas** [comment]
Could require more information on the exact circumstances or blocks used.

**Comment by konsolas** [comment]
Can't reproduce without changing view between block placements.

**Comment by SioWolf** [comment]
Very interesting. I am no longer able to replicate it after a server reboot. I had about 10 people able to consistently reproduce it before the reboot, so I will have to see if it comes back.
