### ISSUE TITLE
High JUMP Bypass

### ISSUE THREAD

**Issue by 02v** [konsolas/AAC-Issues#825]
https://youtu.be/7ZgkcNyBKjc?t=44s

Please fix 
xoxo

**Comment by Eyremba** [comment]
You can also see a Jesus bypass there...

**Comment by Janmm14** [comment]
Do you have AAC Logs around somewhere?
How high is the `min-vl:` in the `fly:` section of your config? If above `min-vl: 12`, highjumps will work.

**Comment by konsolas** [comment]
No configuration or logs. Not enough information to go on.

**Comment by v0idst4r** [comment]
Doesn't 2b2t use nocheatplus?

**Comment by w-o-a-h** [comment]
2b2t has been using aac mostly but sometimes spartan
