### ISSUE TITLE
Fly/Phase forces players through claims (WG and GriefPrev)

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#830]
### Issue description
Players who mine down while on claimed blocks (WorldGuard/GriefPrevention) get forced through blocks. I tested and saw Fly and Phase verbose. Tried disabling one at a time, but only disabling both checks stopped this from happening.

Log of player getting forced past/under claimed block by Fly:
https://hastebin.com/emoceyifiq.hs

Phase was just your typical verbose.

### Core information
**Server version**: 1.12 PaperSpigot (1152)

**AAC version**: 3.2.2

**ProtocolLib version**: 4.3.0

**Plugin list**: Grief Prevention (latest)

### Special environment information
None

### Configuration
Doesn't matter what I change Fly to. Even ~~removing~~ setting `teleport: false` in Fly makes it happen, so it has to do with the new safe teleport location after detection (or something like that).

**Comment by Janmm14** [comment]
Removing something from the config forces the default value. In case of the `teleport` setting in fly its `true`.

**Comment by CeIebrimbor** [comment]
> Removing something from the config forces the default value. In case of the teleport setting in fly its true.

I meant setting `teleport` to false. Sorry for the confusion.

**Comment by konsolas** [comment]
-b1
