### ISSUE TITLE
Elytra+ Bypass

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#831]
Hacked client: Impact
Server ip: Sunknights.us.to
Video: https://www.youtube.com/watch?v=vrOtrQhsWmM&feature=youtu.be
**Server version**: 
![image](https://user-images.githubusercontent.com/29098956/28390347-a45323ba-6ca7-11e7-810e-481f95ac62b6.png)
**AAC version**: 
![image](https://user-images.githubusercontent.com/29098956/28390379-d2ce0bc4-6ca7-11e7-92f6-ae26bebffb57.png)
**ProtocolLib version**: 
![image](https://user-images.githubusercontent.com/29098956/28390419-0066fd98-6ca8-11e7-9c1a-082f96deea4d.png)
**Plugin list**: 
![image](https://user-images.githubusercontent.com/29098956/28390485-3daddb90-6ca8-11e7-9563-ab58d3a614b7.png)
### Special environment information
**ViaVersion version**: **1.1.1**

**ProtocolSupport version**: **None**

**ViaBackwards version**: **None**

**BungeeCord plugins**: **AdvancedBan, Anti Bot Attack, BungeeAdminTools, BungeeAuthMeBridge, BungeeKick, BungeeMSG, BungeePerms, BungeePexBridge, BungeeTabListPlus, DiscordBridge, FastLogin, NuVotifier, PermissionsCord, PluginMetrics, ServerListPlus, SkinsRestorer, SkinsRestorer, WebSender**

**Comment by Slimerblue22** [comment]
I have legit no clue why it said something twice in the video

**Comment by konsolas** [comment]
This should have been closed in 3.3.5
