### ISSUE TITLE
SERVER STILL STARTING UP ERROR

### ISSUE THREAD

**Issue by byCaptain** [konsolas/AAC-Issues#832]
### Issue description
Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: PaperSpigot

**AAC version**: Latest

**ProtocolLib version**: insert

**Plugin list**: insert

### Special environment information
**ViaVersion version**: 1.8-1.11

**ProtocolSupport version**:  N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".
![image](https://user-images.githubusercontent.com/13721281/28403546-73910c8c-6d25-11e7-82e5-f14af4d73681.png)

Very often when the server starts, and the server is starting, not finished yet. I try to join, and in chat i got this message: "Server still starting up"

**Comment by Janmm14** [comment]
Make sure you do not have any type of profiler or java agent attached.

**Comment by konsolas** [comment]
Please do not completely ignore the issue template.

**Comment by byCaptain** [comment]
Core information

Server version: PaperSpigot 1.8.8

AAC version: Latest

ProtocolLib version: 4.2.0

Plugin list: insert

Special environment information

ViaVersion version: 1.8-1.11

ProtocolSupport version: - 

ViaBackwards version: -

BungeeCord plugins: -

**Comment by byCaptain** [comment]
can you work with this now?

**Comment by konsolas** [comment]
Please redownload AAC.
