### ISSUE TITLE
bug command /aac (no permision)

### ISSUE THREAD

**Issue by ProDash1998** [konsolas/AAC-Issues#834]
please add permission to command /acc because player can check the license key and anticheats versions

**Comment by Janmm14** [comment]
This is intended behaviour and will not be changed.

**Comment by GeoGamerLP** [comment]
This feature is not necessary.
1. (Hiding AAC version): This will not help much as hackers can still look at the anticheat's "behaviour" (e. g. dragging down for flying, teleporting for novelocity) to find out if the server uses AAC (if it doesn't have a custom AC) and then, they just test different bypasses to find out the AAC version (many bypasses are "downwards-compatible" though).
2. (Hiding license key): What's so bad with it? It's just one method of verifying your AAC so konsolas is the only one who can do something with it.

**Comment by ProDash1998** [comment]
Or lock this command in the script

**Comment by Janmm14** [comment]
As I already said, this command was created to be NOT removable.
