### ISSUE TITLE
Slime block push on ice

### ISSUE THREAD

**Issue by ghost** [konsolas/AAC-Issues#835]
### Issue description
Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**:1.8.8

**AAC version**: 3.2.2 b1

**ProtocolLib version**: 4.1.0

**Plugin list**: PEX, WorldEdit, ViaVersion, AAC, Multiverse, Protocollib

### Special environment information
**ViaVersion version**: 1.1.1

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever".

No Config Changes!! Just enabling verbose

I'm using btw Client: Optifine 1.11

Video: https://youtu.be/0s-CpiBDSqY
Debug-file: 
[byCaptain.debug.log.txt](https://github.com/konsolas/AAC-Issues/files/1164738/byCaptain.debug.log.txt)

I activated debug after the video, because i forgot it. but its still the same

**Comment by Photon-GitHub** [comment]
Due to the limited situations in which this bug will appear I marked it as unimportant.
