### ISSUE TITLE
Interact false positive during fast building.

### ISSUE THREAD

**Issue by byCaptain** [konsolas/AAC-Issues#836]
Debug file: 
[byCaptain.debug.log.txt](https://github.com/konsolas/AAC-Issues/files/1164797/byCaptain.debug.log.txt)
Video: https://youtu.be/PbuY50k99bc

Also tested on GommeHD.net, their Whereami: 
forgot the first one whereami :(
 JS-034:BW:52baee7d-5cf3-415f-9c1f-9c9faa26b0e0

Core information

**Server version**: 1.8.8

**AAC version**: 3.2.2 b1

**ProtocolLib version**: 4.1.0

**Plugin list**: PEX, WorldEdit, ViaVersion, AAC, Multiverse, Protocollib

**Special environment information**

**ViaVersion version**: 1.1.1

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

BungeeCord plugins: N/A

### Configuration
No config changes, just enabling verbose.

**Comment by Janmm14** [comment]
(The issue description should be at the top instead of the explanatory text which can be deleted just as the explanation at the configuration.)

**Comment by byCaptain** [comment]
sorry for that.

**Comment by Janmm14** [comment]
As interact VL only goes up to 5 in your debug log, I do not see anything to do here since the placement cancel vl is 5 by default, this should not cancel any block placements.
