### ISSUE TITLE
Critical velocity FP with sticks

### ISSUE THREAD

**Issue by byCaptain** [konsolas/AAC-Issues#837]
It's on GommeHD.net
Client: LabyMod 1.8.8
Video: https://www.youtube.com/watch?v=SVTSnSPmjss and https://www.youtube.com/watch?v=2xe2Usxedmc&feature=youtu.be
Just hitting with 15 CPS a player with a knockback stick. May incompatible?
@geNAZt

**Comment by Janmm14** [comment]
Anticheat Bugreports on GommeHD.net do not belong here but into GommeHD.net's bug tracker. Reason: Missing logs and other required information.
