### ISSUE TITLE
FastBreak check Compatibility Bug

### ISSUE THREAD

**Issue by jiangdashao** [konsolas/AAC-Issues#840]
### Issue description
In some plugin/minigame,plugin cancel player break some blocks(like Annihilation etc)
AAC will not check FastBreak
also no verbose

### Core information
**Server version**: 1.8.8

**AAC version**: 3.2.2**(this bug contians in every version)**

**Comment by CeIebrimbor** [comment]
Your description is far too lacking and very confusing. Not sure if you are reporting false block cancel or a bypass or both based on the single sentence.

Please provide a full issue report following the format and also a video and/or logs.

**Comment by jiangdashao** [comment]
@CeIebrimbor You can get a annihilation server to test fastbreak...............
You can use FastBreak to attack(Break) nexus(End stone block),and annihilation plugin will cancel you break,and AAC will not check you

**Comment by Janmm14** [comment]
maybe it can help to listen and cancel the blockbreakevent in priority highest

**Comment by jiangdashao** [comment]
@Janmm14 already in highest,but AAC still not check FastBreak

**Comment by CeIebrimbor** [comment]
I'm not sure why I removed the Insufficient Info tag 2 months ago...

As I retrace this issue, there is still nothing to go off other than "Fastbreak check might be broken". Is this still the case? Is it still broken on AAC 3.3.3 and the correct ProtocolLib? Is AAC even running on the server?

Please redescribe the issue and submit more information about AAC version, ProtocolLib version and a client that is bypassing (video would help).

**Comment by CeIebrimbor** [comment]
Will wait on more information and reopen if provided. Nobody seems to be reporting this and I'm still not sure what is even being reported.
