### ISSUE TITLE
large stack trace event, please advise

### ISSUE THREAD

**Issue by ncf1** [konsolas/AAC-Issues#841]
### Issue description
Issue unknown, server active with maybe 20-30 people, i was not around at the time of the event

https://pastebin.com/Adzx3br1

### Core information
**Server version**: spigot 1.12 few days old probably not current version but close

**AAC version**: 3.2.2-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: 

 CoreProtect, PlayerHeads, dynmap, LuckPerms, Disenchant, EggCatcher, antiraildupe, WorldBorder, Gringotts, PandaWire, ProtocolLib, DeathMessagesPrime, IntelliDoors, Greentext, AAC, SkinsRestorer, BlowableObsidians, FastAsyncWorldEdit, EpicWorldGenerator, Invsee, TreeFeller, Vault, ServerListPlus, ChairStairs, MassiveCore, BottledExp, EpicNetherGenerator, WorldEdit, Essentials, CurrencyDrops, BKCommonLib, SignChestShop, LightCleaner, MassiveLag, WorldGuard, Brewery, EssentialsChat, EssentialsGeoIP, MassiveBooks, EssentialsSpawn, AreaShop, AuthMe, Factions, CombatLogX, ChatControl, FactionChat, SilkSpawners, FactionsDynmap

### Special environment information
**ViaVersion version**: n/a

**ProtocolSupport version**: n/a

**ViaBackwards version**: n/a

**BungeeCord plugins**: n/a

### Configuration
config:
https://pastebin.com/iDDWTYDa

Of note, the AAC log created by the event is 512 MB. here is a snippet of that data, featuring the top and the bottom of the offending event. the event in this paste bin seems to have occured multiple times, but this pastebin only covers the one from 00:15am which correlates to the time frame of the above stack trace
https://pastebin.com/n1ELdYkT

**Comment by SlimeDog** [comment]
Same issue.

Spigot 1.12 latest (2017-07-25)
AAC 3.2.2-b1
ProtocolLib 4.4.0-SNAPSHOT-b379

**Comment by Janmm14** [comment]
@SlimeDog
You probably have a different error. Please post your stack trace too.
Additionally I advice to use ProtocolLib 4.2.0 for 1.8-1.10 and 4.3.0 for 1.11-1.12, otger people reported an error with ProtocolLib 4.4.0-SNAPSHOT already

**Comment by SlimeDog** [comment]
Reverted to ProtocolLib 4.3.0-b373 (recommended production build). No issues.

Since I'm running test servers presently, I tend to use snapshots. Someone has to test this stuff. :)

**Comment by CeIebrimbor** [comment]
Use 4.3.0 (b373) until a full release version of ProtocolLib is released.
