### ISSUE TITLE
Fly teleports players into block below them

### ISSUE THREAD

**Issue by SioWolf** [konsolas/AAC-Issues#842]
### Issue description

When players teleport they sometimes phase through the block beneath them. This happens most often when they teleport to the top of a layer only one block thick. I reported an issue a couple weeks ago (#824) about players setting off fly when towering up. It was closed without being able to be reproduced, I think these two are related.

I believe that fly is teleporting the players down into the block beneath them when they teleport or when they tower up. Disabling "teleport" for fly in the config fixed both of these issues for me.

### Core information
**Server version**: Paper-1153

**AAC version**: 3.2.2

**ProtocolLib version**: 4.3.0

**Plugin list**: Teleportation is done with Essentials /back, /tpa, and /spawn

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
I am using @CeIebrimbor 's AAC config.

**Comment by SioWolf** [comment]
https://www.youtube.com/watch?v=30QYBZWbioU&feature=youtu.be

**Comment by CeIebrimbor** [comment]
Something related to being phased through blocks was patched in 3.2.2-b1. Are you sure you updated?

**Comment by SioWolf** [comment]
@CeIebrimbor Ah, I guess the server didn't update! I will try this new build now, thank you.
