### ISSUE TITLE
Speed and Flight bypassed with various clients while inside vehicles and elytra.

### ISSUE THREAD

**Issue by zetglob** [konsolas/AAC-Issues#843]
Latest AAC version as of this writing, tested with default config and Celebrimbors config.

Several clients, some of which I don't know, and some paid clients I know (can send links to at request) are able to bypass AACs flight and speed check entirely, and players are able to go at any arbitrary speed they choose to while inside vehicles or using elytra, additionally infinite flight with elytra. from what I know this only works while inside vehicles and elytra.

No plugins that could interfere with AAC, it is a survival server with a few chat plugins.
PaperSpigot 1154
Protocollib 373 (4.3.0)

**Comment by ThorFTW** [comment]
Can you send me the clients, want to test it out with my config. 
Thank you!
