### ISSUE TITLE
@ issue

### ISSUE THREAD

**Issue by Carbonawk** [konsolas/AAC-Issues#845]
Hi there, this is probably ignorance on my side and not a problem with the plugin.

Anyway, I got 2  plugins that use the "@" symbol. AAC being one of them. Because of this. I have 2 plugins responding at the same time. Is it possible to disable or rather change to another symbol?

ow yeah, what does the "@" symbol do in AAC?

I have also uploaded a screenshot as an example of this.

![zontu7t 1](https://user-images.githubusercontent.com/25295327/28600811-d04883ea-71b4-11e7-9f80-991288556f67.png)

**Comment by Janmm14** [comment]
its staff chat (aac notify permission needed to use)
disable by editing messages.yml:
set the prefix to something nobody uses to disable

**Comment by Carbonawk** [comment]
I see. The file is called language.yml btw.

Thanks.
