### ISSUE TITLE
1.9+ charged hit violation multiplier

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#846]
For the Hitbox and Killaura checks.

Since 1.9 servers still have the option to spam click like 1.8 servers, we cannot simply decrease kick values on 1.9 to make detection more effective on the slower combat. This request is for the option to **x2 or x1.5** the violation gained by full power ("charged") hits in 1.9+, assuming that is something you can account for.

That way, spam clicking in 1.9+ **or** 1.9+ servers that revert to 1.8 combat **or** standard 1.8 server combat is detected normally with the minimum violation per hit, but servers with 1.9+ combat get a VL boost if said hits in violation are also fully charged.

This would help _drastically_ with clients bypassing with many KA and even some Multiaura simply because the number of hits are drastically reduced due to the spaced out hitting. The new heuristic might catch some clients if they have 2-3 fights back to back, but your standard fight is 5-10 seconds long.

**Comment by Games4k** [comment]
Hey, can you tell me just a one public client that is bypassing aac killaura checks? I never saw one of them. (every client that is bypassing gomme version of aac is not bypassing normal aac @ all, or is detected by heuristic)

**Comment by Janmm14** [comment]
@Games4k The identified problem of heuristics are too short fights on GommeHD.net

**Comment by CeIebrimbor** [comment]
> With the 1.9+ combat heuristic in place I do not see the need of this one.

So we should remove the Hitbox and Killaura checks for 1.8? Since there are 100 Heuristics for 1.8 combat? I do not follow your logic.

> Additionally you did not even mentioned the check which should gain a VL Boost.

Hitbox + Killaura

**Comment by Janmm14** [comment]
Its not about removing the stuff, but about the 1.9 heuristics doing things about fully charged hits.

I do not see how killaura and hitbox checks do suddenly have higher accuracy when those get triggered at fully charged hits, therefore giving increased VL at those points not automatically cause better detection of reach and killaura.

**Comment by CeIebrimbor** [comment]
It puts more weight on hits that are fully charged (hacked clients only do full charged) and while that would also increase VL accumulation for legal clients, the decay would also double.

It's only being brought up because Multiaura in 1.8 is detected and kicked for KA in 1.5 seconds and 1.9 will take up to 10 seconds and require 2+ targets, since the spread between hits is so long.

Essentially, if a client is hitting illegally AND is using full charged hits, kick him faster. If they are spamming, give them a buffer that is already built in. This only works if the decay is also doubled for legal fully charged hits.

**Comment by CeIebrimbor** [comment]
Maybe another time. There are not a plethora of aggressive hack clients that focus (or hackers that play) on 1.9+ servers. They all gravitate towards 1.8 and servers with reduced hit delay.
