### ISSUE TITLE
Console Error 

### ISSUE THREAD

**Issue by MrRobotMann** [konsolas/AAC-Issues#847]
### Issue description
I don't I was checking my console and randomly it poped up this error. https://hastebin.com/caqakuqegu.lua

### Core information
**Server version**: 1.8.8 PaperSpigot

**AAC version**: 3.2.2-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: -

### Special environment information
**ViaVersion version**: 1.1.1

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
I'm using an optimized config from Celebrimbor. I don't think its a good idea to paste it here :/

**Comment by Janmm14** [comment]
(About the config you're right. we can simply ask him in case anything is needed from your config, but it looks like nothing is needed)

**Comment by MrRobotMann** [comment]
If you want to I can tell you my server's plugins but not in here :/

**Comment by CeIebrimbor** [comment]
@MrRobotMann 
Just for the sake of stability (hopefully), give ProtocolLib 4.2.0 a try.

http://ci.dmulloy2.net/job/ProtocolLib/341/

**Comment by MrRobotMann** [comment]
But will it be compatible with AACAdditionPro ?

**Comment by Janmm14** [comment]
Yes

**Comment by MrRobotMann** [comment]
Oh nice thanks a lot!

**Comment by konsolas** [comment]
Seems solved?
