### ISSUE TITLE
Unhandled exception occured in onPacketSending

### ISSUE THREAD

**Issue by smartmadio** [konsolas/AAC-Issues#849]
### Issue description
Server console error message:

https://gist.github.com/anonymous/aac7946e5b531f89a8319320109875d0

### Core information
**Server version**: Spigot1.8.8

**AAC version**: 3.2.2-b1

**ProtocolLib version**: v4.3.0(#379)

**Plugin list**: AAC, ConsoleScheduler, DisableJoinMessage, HolographicDisplays, MiaoReplace, stp, PermissionsEx-1.23.2, PlaceholderAPI, ProtocolLib, SkinsRestorer-v12.9.5, Skywars, TitleManager-1.5.12, TpLogin, Vault, ViaVersion-1.1.1, VoidSpawn, worldedit-bukkit-6.1.2, worldguard-6.1.2

### Special environment information
**ViaVersion version**:1.1.1

**ProtocolSupport version**:N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
I've made no change to config.yml.

**Comment by Janmm14** [comment]
The ProtocolLib Version you said to have is not the ProtocolLib Version you actually have.

Use ProtocolLib 4.2.0 for 1.8 - 1.10
Use ProtocolLib 4.3.0 for 1.11 - 1.12
(4.3.0 also works for 1.8 - 1.10, but 4.2.0 is still recommended as 4.3.0 seems to have problems with reloading in my tests)
