### ISSUE TITLE
Horse Bug

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#85]
Every time you try to access a horse from 2 or 3 blocks below, you get flagged and kicked for flight. https://www.youtube.com/watch?v=ChythdFypHc

**Comment by CeIebrimbor** [comment]
He is rewriting vehicles I do believe.

**Comment by konsolas** [comment]
Fixed and tested. (Test case: http://i.imgur.com/9cgnw3x.png)
