### ISSUE TITLE
Fishing rod False positive/bug 

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#851]
Old Combat mechanics plugin: https://www.spigotmc.org/resources/oldcombatmechanics-disable-1-9-hit-cooldown.19510/
**Video containing verbose and issue (You might not need to watch the whole thing but you can if you want)** https://youtu.be/OG5yQFdFiDk
### Core information
**Server version**: 
![image](https://user-images.githubusercontent.com/29098956/28746949-80334542-7462-11e7-8959-fda497deff31.png)

**AAC version**: 
![image](https://user-images.githubusercontent.com/29098956/28746952-92415f26-7462-11e7-87aa-a84e6ae9818d.png)

**ProtocolLib version**: 
![image](https://user-images.githubusercontent.com/29098956/28746974-e00ee84a-7462-11e7-8aad-c1279deb0f75.png)

**Plugin list**: 
![image](https://user-images.githubusercontent.com/29098956/28746976-f2efc4a2-7462-11e7-933b-a05cac521a9c.png)

### Special environment information
**ViaVersion version**: 
![image](https://user-images.githubusercontent.com/29098956/28747000-50f87c9c-7463-11e7-984c-05c8360bcb59.png)

**ProtocolSupport version**: **None**

**ViaBackwards version**: **None**

**BungeeCord plugins**: 
![image](https://user-images.githubusercontent.com/29098956/28747066-ade18cfe-7464-11e7-955d-5819499ab59c.png)

### Configuration
**No change other than enabling verbose**

**Comment by Heliosard** [comment]
This problem is still present in the latest update (3.3.4-b1). Can you fix this please?

**Comment by Janmm14** [comment]
@Heliosard as this issue is not marked as solved, it is known that this is still an issue

**Comment by Rerd** [comment]
Players are getting really irritated by this issue because of the fact that it is a pvp server with rods that we are using it on.

**Comment by LinsaFTW** [comment]
Please fix it ;-; i beg of you , i was doing a tournament and everyone got kicked because someone started using the rod to bug the people to make them get kicked by the anticheat!

**Comment by Janmm14** [comment]
Solution: Don't make AAC kick for Fly

**Comment by LinsaFTW** [comment]
Thats not a solution , because they freeze until they get kicked , actually that means they cant move when they are rodded , and not kicking for fly will let players use fly bypass.

Isnt there still a estimated time for this fix? I think is Mega critical as it just ruins the pvp with rods instead of being 1vs1 is 1vs1vsAAC XD

**Comment by Janmm14** [comment]
Not kicking for fly doesn't allow players to bypass fly. Else there would be probably plenty videos showing working fly cheats on GommeHD.net with AAC 3.3.4

**Comment by LinsaFTW** [comment]
There are some clients that if AAC doesnt kick for fly they can make the anticheat teleport to wrong positions.

**Comment by LinsaFTW** [comment]
And as i said before they cant move when they get teleported and they take that bug as a advantage!

**Comment by Janmm14** [comment]
@LinsaFTW
Please name such clients, make sure your claims are based on the latest version of AAC and your tp threshold is at the default value.

**Comment by Rerd** [comment]
@Janmm14 idk what you’re not understanding. Having the tp threshold at default is the worst for rod pvp. Every time the player gets rodded, they are literally stuck in place for the rod. This is also a cause for Velocity false positives because the player doesn’t move. You don’t understand how big of a problem this is and needs to be fixed next update.


@konsolas please fix this.

**Comment by LinsaFTW** [comment]
Flux Jigsaw etc... + blink + timer every hack that moves really fast and generates lot of vls.

**Comment by Janmm14** [comment]
Are you both speaking about latest AAC?
If its happening on AAC 3.3.4-b1, please provide a `/aacdebug` log. They're saved in `plugins/ACC`.

**Comment by konsolas** [comment]
Wondering if anyone here is able to provide an /aacdebug log of this issue - that would significantly reduce the time required to fix it.

**Comment by Rerd** [comment]
Alright, I’ll do that when I get home.

**Comment by Rerd** [comment]
@konsolas here you go: [Gist](https://gist.github.com/Rerd/359a26299e74b3315b8203f58a2d9406)

**Comment by konsolas** [comment]
Thanks for the debug log.

**Comment by Rerd** [comment]
No problem. Thanks for finally getting around to fixing this.
