### ISSUE TITLE
reload error paperspigot/Tacospigot

### ISSUE THREAD

**Issue by ProDash1998** [konsolas/AAC-Issues#852]
### Issue description
I reload the server is what I show something like this https://hastebin.com/wucenibemu.php

### Core information
**Server version**:  1.12

**AAC version**:  3.2.2-b1

**ProtocolLib version**: lastes 4.3.0

**Plugin list**: 
AAC
antitab
AWD - AnwiWorldDownloader
LuckPerms
MaxBans
Multiverse-Core 2.5
Paintball
ProtocolLib
Skript
Valut
WE and WG 

### Special environment information
**ViaVersion version**: N/a

**ProtocolSupport version**:n/a

**ViaBackwards version**: n/a

**BungeeCord plugins**: insert (or N/A)

### Configuration

------

**Comment by CeIebrimbor** [comment]
/reload is not supported by AAC(most large plugins) and is actually not supported by Spigot anymore ("only for non-development servers/testing").

Please use full restarts for changes/updates to AAC.
