### ISSUE TITLE
Can't run movement checks with MOVE check turned off - Spam

### ISSUE THREAD

**Issue by pkt77** [konsolas/AAC-Issues#853]
### Issue description
Ever since updating to the latest version, this error has been spammed nonstop: https://pastebin.com/usqBKPaU

### Core information
**Server version**: 1.12

**AAC version**: 3.2.2

**ProtocolLib version**: 4.4.0-SNAPSHOT-b379

### Special environment information
**ProtocolSupport version**: 4.26

### Configuration
About half of the checks are turned off. No modifications to any of the thresholds.
Full config if needed: https://pastebin.com/swSkGq9b

**Comment by CeIebrimbor** [comment]
Use the 4.3.0 release of ProtocolLib instead of beta versions
http://ci.dmulloy2.net/job/ProtocolLib/373/

**Comment by pkt77** [comment]
Not the issue, problem still persists

**Comment by CeIebrimbor** [comment]
Is the "issue" disabling the Move check and losing the functionality of all other move related checks like Fly and Speed?

**Comment by pkt77** [comment]
We have Speed disabled, but yea I didn't even notice the fly check hasn't been alerting.
Does the move section have to be enabled for those two to work?

**Comment by CeIebrimbor** [comment]
Yes. 100% of AAC's move checks are dependant on the `move` check being activated. As mentioned in the config above the `enabled` option.

**Comment by pkt77** [comment]
Ah ok, I'll have that enabled from now on
