### ISSUE TITLE
Heuristics while mining

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#854]
### Issue description
Someone was mining with an iron pickaxe, he had lots of fastbreak flags and after around 2 minutes mining he got flagged by Heuristics for P/65 (confidence 78.0). His ping was around 600+ ms. And he wasn't even hacking at all nor pvping with a player.

### Core information
**Server version**: 1.9.4 (Paper)

**AAC version**: 3.2.2-b1

**ProtocolLib version**: 4.2.0

**Plugin list**: http://prntscr.com/g3sz61

### Special environment information
**ViaVersion version**: 1.1.1

**ProtocolSupport version**: N/A

**ViaBackwards version**:  N/A

**BungeeCord plugins**: Socket4MC, CommandDispatcher, ProtocolChanger (all other plugins are custom)

**Comment by CeIebrimbor** [comment]
@iConfueZ 
I would personally recommend you set Heuristics `min_confidence` at 80 to kick. 84 if you are not hosting an environment where stopping combat hacks ASAP is critical (e.g. A survival or prison server).

Also, compensating for something as uncommon as 600ms ping is a tricky thing. I would recommend you look into the plugin Conditional Commands on Spigot to limit kicking to players with <250ms ping (when considering higher sensitivity setting for Heuristics).

**Comment by konsolas** [comment]
Addressed in 3.3.0
