### ISSUE TITLE
ProtocolLib 4.4.0-SNAPSHOT public API not bytecode compatible

### ISSUE THREAD

**Issue by JamieSinn** [konsolas/AAC-Issues#855]
### Issue description
https://gist.githubusercontent.com/andrewkm/a1346cc60d22ba5f22b680ad797897e2/raw/ba1818d57e9993a5752811f60abeed1489c1088f/gistfile1.txt

**Comment by Janmm14** [comment]
ProtocolLib changed the public API.

**Comment by CeIebrimbor** [comment]
1.12.1 is not yet supported by AAC since the required ProtocolLib version changed the hook that is critical for AAC. It is recommended you stick with 1.12 until Konsolas returns from his vacation and has a chance to update.

**Comment by JamieSinn** [comment]
We'll be using NCP in the meantime, well wishes to konsolas on his travels.

**Comment by mikroskeem** [comment]
If anyone else gets here: ProtocolLib build [378](http://ci.dmulloy2.net/job/ProtocolLib/378/) is last working version with AAC right now.

Given build should work fine on 1.12.1 as well (Must note that I did not test everything 100% through)

**Comment by konsolas** [comment]
AAC currently doesn't support the dev version of protocollib. The stable 4.3.0 should work.

**Comment by konsolas** [comment]
Being looked at in dmulloy2/ProtocolLib#394

**Comment by dmulloy2** [comment]
Should be fixed now

**Comment by Janmm14** [comment]
Unfortunaly its not, further information at https://github.com/dmulloy2/ProtocolLib/issues/394#issuecomment-326748926

**Comment by Janmm14** [comment]
@dmulloy2 
Unfortunaly its not, further information at https://github.com/dmulloy2/ProtocolLib/issues/394#issuecomment-326748926

**Comment by CeIebrimbor** [comment]
This seems to be fixed with latest dev builds of ProtocolLib (the fix was on their end).

Please update:
http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/
