### ISSUE TITLE
AAC-Command form Player Bug

### ISSUE THREAD

**Issue by JoshuaPvP** [konsolas/AAC-Issues#856]
### Issue description
Hello, i use AAC and i cant use the /aac or other AAC commands as a Player.
I have a BungeeServer. I put AAC in all Plugins folder of all of my server´s.
I done have AACAditionPro. Only AAC default.
Wen i use a AAC command form a Player the comes a fake Message the Message: Unkow Coammand type '/help' for help.
Default ist this Message : Unkow Coammand type "/help" for help.

### Core information
**Server version**: 1.8.8

**AAC version**: 3.2.2

**ProtocolLib version**: Build 232

**Plugin list**: AAC, ProtokolLib, and self made Plugins...

### Special environment information
**ViaVersion version**: Not on this Server.

**ProtocolSupport version**: Not on this Server.

**ViaBackwards version**: Not on this Server.

**BungeeCord plugins**: BuyCraft, YALMAR-Bungee, BungeeYAML, SayNoToMCLeaks, Self made Bungee System...

### Configuration
I use the default AAC config but i make Knockback true and the Hacker will be kicked faster.

Thank you for your help.

**Comment by CeIebrimbor** [comment]
AAC is not running since you are using a wildly obsolete version of ProtocolLib. Use version 4.3.0 of ProtocolLib (aka build 371).
