### ISSUE TITLE
Error PlayerTeleportEvent

### ISSUE THREAD

**Issue by Henriks9** [konsolas/AAC-Issues#858]
Bild des Fehlers :https://prnt.sc/g4hwif 

### Core information
**Server version Debian 8
**AAC version**: AAC 3.2.2

**ProtocolLib version**: 4.3.0
**Plugin list**: Server API, QSG

### Special environment information
**ViaVersion version**: yes

**ProtocolSupport version**: 4.3.0

**ViaBackwards version**: insert no

**BungeeCord plugins**: insert yes

**Comment by Janmm14** [comment]
AAC does not support asynchronous teleports.

Additionally it is thought that server version is filled with your minecraft/spigot server version.

AAC unterstützt keine asynchronen Teleportationen, das Plugin manugun (QSG) probiert dies jedoch.

Außerdem ist gedacht, dass Server Version mit der Minecraft/Spigot Server Version gefüllt wird.
