### ISSUE TITLE
P/32 false positives (Heuristics)

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#859]
Server version: Spigot 1.8.8 with ViaVersion

AAC version: Latest

ProtocolLib version: 4.3.0

ViaVersion version: 1.1.2

AAC Heuristics config: https://pastebin.com/4ynK3pTL

Log of AAC (I deleted records about other players): https://pastebin.com/FamA47jT

Video: https://youtu.be/elVpQpt-ZDo?t=14m1s

**Comment by CeIebrimbor** [comment]
Your best bet is to exempt P/32. It seems to be the only known troubled heuristic.

**Comment by konsolas** [comment]
Video doesn't exist.

**Comment by Toshka17** [comment]
@konsolas I think that you should not close the thread because you did not have time to watch the video.
@CeIebrimbor Saw this video.

**Comment by Janmm14** [comment]
@Toshka17 With the video being unavailable there is nothing to work with.

**Comment by CeIebrimbor** [comment]
@Toshka17 I remember making a comment based off watching a video, but I don't recall the activities in the video. Those need to be seen so Konsolas can accurately modify the Heuristic instead of blind guessing or globally weakening it.

The logs are great, now we just need to see what caused it to trip.

**Comment by Toshka17** [comment]
It took too long and apparently the player removed this video

Especially nothing happened on the video. The player simply stood still and at the moment of the ban opened the chat and looked for a message.

**Comment by Janmm14** [comment]
Maybe you get another one with a recording some time in the future.
But hopefully noone without cheats.
