### ISSUE TITLE
Using LegitStep Lets You Walk Over Fences.

### ISSUE THREAD

**Issue by 10axl** [konsolas/AAC-Issues#861]
### Issue description
I was testing out AAC on the Official Test Server (test.kons.co) and was able to use LegitStep on Wolfram 9.4 for MC1.8 to just casually walk over fences. I know this is probably not ground breaking in most scenarios, but I though that I should report it anyway.

Video: https://www.youtube.com/watch?v=ZwSNq9y3Jcs
If you need better quality let me know. (Just used some nVidia Default)

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: AAC 3.2.2

**ProtocolLib version**: Official Test Server Version (*Don't have access to protocol.version)

**Plugin list**: Official Test Server Plugins: WorldEdit, MyChat, OMGiFFA, Essentials, EssentialsChat, PermissionsEX, MineSec, UltimateParticles, ViaVersion, pvpstats, Vault, EssentialsSpawn, ProtocolLib, WorldGuard, AAC, 1vs1.

### Special environment information
**ViaVersion version**: Official Test Server Version (*Can't Check)

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: Official Test Server (*Can't Check) *Not sure.

### Configuration
Official Test Server Version: so what was it default, except the ban threshold.

Please let me know if I can do anything to help.

Thank you,
10axl

**Comment by CeIebrimbor** [comment]
Due to sensitivity concerns, the default violation count to force players down was increased. If you want to stop step, you can set `min_vl: 12` in the Fly check. Unfortunately, you will need to prepare for frustrated players getting lagged back. Players on 1.9+ servers will commonly hit VL 50-80 for normal tasks.

**Comment by Photon-GitHub** [comment]
Still a 1.5 block step that a normal person is not able to do.

**Comment by NewbieOrange** [comment]
Using some other clients can easily(~90%) walk over fences by pressing w and jumping twice.

**Comment by Janmm14** [comment]
@konsolas my internal testing step can step 1.5 blocks high in case you want to fix this
