### ISSUE TITLE
P/09 false positive (Heuristics)

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#862]
### Issue description
P/09 flagged (default configuration)
https://streamable.com/yfunv (at the end)

### Core information
**Server version**: 1.9.4 (Paper)

**AAC version**: 3.2.2-b1

**ProtocolLib version**: 4.2.0

**Plugin list**: AAC and ViaVersion

### Special environment information
**ViaVersion version**: 1.1.1

**ProtocolSupport version**: N/A

**ViaBackwards version**:  N/A

**BungeeCord plugins**: N/A

**Comment by Janmm14** [comment]
Heuristics are not meant to fight versus afk players for ages.
