### ISSUE TITLE
Hitbox false positive

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#863]
### Issue description
Spamming your rod (right-click) while hitting the player (left-click) flags for killaura hitbox and normal by time (Hitbox # 2 around 30/60 seconds after, normal after a minute or so)
https://streamable.com/9745d

### Core information
**Server version**: AAC's test-server

**Comment by Photon-GitHub** [comment]
It seems like a player is lagging very much, which is a known issue that can potentially cause hitbox violations, thus I will mark this as unimportant.

**Comment by iConfueZ** [comment]
It also happens when someone is not lagging

**Comment by konsolas** [comment]
Moving to #873
