### ISSUE TITLE
AAC disables itself occasionally after start

### ISSUE THREAD

**Issue by irworks** [konsolas/AAC-Issues#864]
### Issue description
AAC v3.2.2 disables **sometimes** itself in `onEnable()`. Sadly I am currently unable to reproduce the issue reliably, but this is what I can provide at the moment: from time to time AAC fails to enable itself on a freshly deployed game server. All 100+ other game servers instances are totally fine.

```
[09:41:24] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.3.0
[09:41:24] [Server thread/INFO]: [AAC] Loading AAC v3.2.2
[09:41:24] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.3.0
[09:41:24] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[09:41:31] [Server thread/INFO]: [AAC] Enabling AAC v3.2.2
[09:41:32] [Server thread/INFO]: [Nick] Enabling Nick v1.0
[09:41:32] [Thread-57/INFO]: [AAC] Disabling AAC v3.2.2
[09:41:32] [Thread-57/INFO]: [AAC] Disabling checks...
[09:41:32] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[09:41:32] [Server thread/INFO]: Done (7.596s)! For help, type "help" or "?"
[09:41:32] [Server thread/INFO]: Using epoll channel type
[09:41:33] [Server thread/INFO]: ***::CLOUD ⟫ Updated GameServerState to JOINABLE
```

### Workaround
Since we are using a dynamic cloud setup I have written a function which checks after a 1.200 ticks delay if AAC is there, if not, it shuts the server down.
```
try {
   Class.forName("me.konsolas.aac.api.AACAPIProvider");
} catch (ClassNotFoundException exception) {
   System.out.println("CRITICAL::ERROR ⟫  AAC-API not found (ClassNotFoundException)");
   return false;
}

if (!AACAPIProvider.isAPILoaded()) {
   System.out.println("CRITICAL::ERROR ⟫ AAC-API failed to load.");
   return false;
}
```

### Core information
**Server version**: git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**AAC version**: 3.2.2.b1

**ProtocolLib version**: v4.3.0

**Plugin list**: AAC, ProtocolLib, custom

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: Only custom

### Configuration
Should be not important for this issue since all servers are using the same configuration and only some  instances fail to start up AAC.

**Comment by irworks** [comment]
I had to wait for this issue to re-occur since the last affected instance was deleted automatically. Sadly there isn't much I can show:

- AAC does not write a log file, when it disables itself on startup (only `banned.yml`,` config.yml` and `language.yml` in the _/plugins/AAC_ folder, yes I do have `log_file: true`)
- The server log does not feature any more relevant information, above the snippet you can find the world loading and our database connection, below you can find `java.lang.NoClassDefFoundError: me/konsolas/aac/api/AACAPIProvider, because at this time my workaround was not yet implemented and the _PlayerJoinEvent_ was depending on AAC.
- Unable to paste _/aac_ output since the plugin is not enabled when this issue occurs.

**Comment by irworks** [comment]
Since it is not possible to run the command from the console, here is a screenshot of the output: <img width="642" alt="screen shot 2017-08-11 at 17 42 42" src="https://user-images.githubusercontent.com/5793142/29220820-9c42d70c-7ebc-11e7-83ac-7be2b8d3fc03.png">

**Comment by Janmm14** [comment]
Thanks

**Comment by JuliCarles** [comment]
Experienced something similar but even weirder and happened only once.
Using version 4.2.1 and ProtocolLib 4.2.0.
`[16:09:09] [Thread-50/ERROR]: [AAC] 404 not found error
[16:09:09] [Thread-50/INFO]: [AAC] Disabling AAC v3.2.1
[16:09:09] [Thread-50/INFO]: [AAC] Disabling checks...`

It's somehow similar to what's being adressed here, that's why I post it here.

**Comment by CeIebrimbor** [comment]
Is anyone still experiencing this issue with the latest dev builds of ProtocolLib? Please report back. We will close this report in the next few days assuming that it was a freak incident or that later dev builds fixed the issue.

http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

**Comment by irworks** [comment]
Wie haven't experienced this issue in the last few weeks so from our perspective it seems fixed. Interestingly: as far as I know nobody updated ProtocolLib, only all recent AAC Updates have been installed. So @konsolas might "accidentally" fixed the issue, which is great! (I am not closing the issue while waiting for feedback by @JuliCarles)

**Comment by CeIebrimbor** [comment]
We can reopen if Juli has something to add.

**Comment by Janmm14** [comment]
According to konsolas, AAC disables itself just without further notice, if certain files inside AAC.jar were edited in a serious way, for example someone tries to create a new "knightfall".

**Comment by JuliCarles** [comment]
I haven't had this issue for a while as well. The issue was pretty random and only happened two times or so.
