### ISSUE TITLE
TNT Boost flags fly

### ISSUE THREAD

**Issue by geNAZt** [konsolas/AAC-Issues#865]
https://youtu.be/tMKfB10TtRs - https://www.youtube.com/watch?v=6ac8UFKxZog

If you jump and TNT explodes under you you get flagged for fly because of the TNT boosting you into the air. This only flags when jumping.

**Comment by konsolas** [comment]
This was opened last year in august. @geNAZt could you test it again with a more recent version?

**Comment by Hyronymos** [comment]
TNT explosions still flags for fly

[debug.60755857-edc7-4ab7-aa1e-301008298928.debug.log](https://github.com/konsolas/AAC-Issues/files/1649348/debug.60755857-edc7-4ab7-aa1e-301008298928.debug.log)

**Comment by konsolas** [comment]
Theoretically was fixed in 3.3.11
