### ISSUE TITLE
Blocking flying elytra

### ISSUE THREAD

**Issue by ProDash1998** [konsolas/AAC-Issues#866]
### Issue description

https://youtu.be/u2bG-EQ4UVk

### Core information
**Server version**: 1.12

**AAC version**: 3.2.2-b1

**ProtocolLib version**: 4.3.0

**Plugin list**:
http://imgur.com/a/Bcpma

### Special environment information
**ViaVersion version**: 1.1.0

**ProtocolSupport version**: n/a

**ViaBackwards version**: n/a

**BungeeCord plugins**: n/a

### Configuration
configuration default (translated notyfications)

**Comment by Photon-GitHub** [comment]
The general elytra handling needs a revamp, therefore I mark this issue as critical.

**Comment by ProDash1998** [comment]
and have next problem not work me aactoogle(verbose)

**Comment by CeIebrimbor** [comment]
Also see #773

**Comment by konsolas** [comment]
Closing as a duplicate of the elytra component in issue #773

#773 is now critical.
