### ISSUE TITLE
𝙋𝙚𝙧𝙒𝙤𝙧𝙡𝙙𝙋𝙡𝙪𝙜𝙞𝙣 ᴬᴷᴬ ℙ𝕎ℙ

### ISSUE THREAD

**Issue by PinoyLifeCraft** [konsolas/AAC-Issues#867]
Hello there Team_AAC,

I am currently having a conflict between AAC and PWP 🙁  when I join to my server it says " Server is starting up! " but the server load already, I also toggle to false this one

usetps: false
ℬℯ𝒸𝒶𝓊𝓈ℯ 𝒾𝓉 𝓈𝒶𝓎𝓈 𝓉𝒽𝒶𝓉 ℐ 𝒽𝒶vℯ 𝓉ℴ 𝒹𝒾𝓈𝒶𝒷𝓁ℯ 𝓉𝒽𝒾𝓈 𝒾𝒻 ℐ 𝒶𝓂 𝓊𝓈𝒾𝓃ℊ 𝒫𝒲𝒫

**Comment by Games4k** [comment]
Temporary fix would be to do aacreload after other plugins are loaded

**Comment by Photon-GitHub** [comment]
I close this issue as invalid as you should have read the incompatibilities on the overview.

`AAC may be incompatible with:
Any plugins that affect block breaking speed without vanilla enchants/potions.
Any plugins that damage other entities for a player (kitpvp abilities)
Any sort of protocol hack (apart from ViaVersion 1.8-1.11)
Any plugins that affect block interaction out of a player's line of sight.
Item Attributes (Speed attribute)
Bungeecord tab list/nametag plugins
**PerWorldPlugins**
Other plugins that make players seem like they're hacking
Non-vanilla enchantments`
