### ISSUE TITLE
Interact kick (High mcmmo axes)

### ISSUE THREAD

**Issue by AmazedMender16** [konsolas/AAC-Issues#868]
### Issue description
People are getting kicked while fighting in pvp with high mcmmo axes for interact. 100% they are not using hacked clients. All they use is optifine.

https://hastebin.com/asuruduwiv.cs
Its about player: LIINdd

### Core information
**Server version**: spigot 1.11.2

**AAC version**: 3.2.2-b1

**ProtocolLib version**: http://ci.dmulloy2.net/job/ProtocolLib/373/

**Plugin list**: Upon request

### Special environment information
**ViaVersion version**: Bungee viaversion: Latest version

### Configuration
Im using cel's configs all of them are the latest..

**Comment by Photon-GitHub** [comment]
Even though MCMMO is officially supported, this likely fits the "non-vanilla-enchantment" topic. Therefore I marked this as less important.

**Comment by AmazedMender16** [comment]
How can it be non vailla enchantments when its axes?

**Comment by Photon-GitHub** [comment]
High mcmmo axes have the same problem as axes with excessive efficiency regarding the interact check.

**Comment by CeIebrimbor** [comment]
Removing "Unimportant". If AAC advertises support, it should not intentionally ignore compatibility bugs (they should be treated as bugs). Otherwise, you should drop the support and not advertise.

**Comment by konsolas** [comment]
Annoyingly the hastebin link has disappeared.

**Comment by CeIebrimbor** [comment]
Original reporter says he hasn't seen this in a few weeks. Will re-open if someone provides recent verbose.
