### ISSUE TITLE
Suggestion: Permission | Colors | Messages

### ISSUE THREAD

**Issue by CryptoMorin** [konsolas/AAC-Issues#869]
Before i request these i would like to say that the features i'm going to ask are probably already added and i'm not just really focusing on them!

1.Add permission for aackick broadcast (I don't want normal players to see)

2.To be honest i think it's much better removing "aac_kick_broadcast" in language.yml and just using the same message given in the config.yml. So it can be an ability for each kick to have it own message! Same for /aacban ? "ban_message"

3. Add color support for aacmessage, aacstaffnotify and aacban.

Separated question:
What is the default config based on? I mean how is it made? Is it like for players that have 1~10 pings?

**Comment by Janmm14** [comment]
About 3.:
Color support is given by the actualy color char `§` which minecraft introduced and not the char `&` which many plugins internally replace with `§`.

The default config is made for people with a ping < 150 mostly I think.
Info: Changing the check parameters to fix false positives can sometimes lead to certain cheats being possible.

**Comment by CryptoMorin** [comment]
I guess Bump for the other 2?

Thanks Janmm14 it worked fine.

**Comment by konsolas** [comment]
Instead of broadcast, you could set up a multi command:

```
   threshold:
      200:
       - "aacstaffnotify {player} was kicked for X" # Only notifies people with AAC.notify permission
       - "aackick {player} using X" # And the player is also kicked.
```
