### ISSUE TITLE
Griefprevention fake Blocks produce glide messages

### ISSUE THREAD

**Issue by Phreag** [konsolas/AAC-Issues#87]
When players interact with griefprevention it shows up fake blocks for visualization.
If those fake blocks replace a non solid block (like one layer snow) players can stand on them, but aac tells that they use glide hacks because the are vidually flying 1 block above ground.

Can this be fixed in AAC or is it not possible?

**Comment by Janmm14** [comment]
Theoretically yes, maybe there's a GriefPrevention API for that, else AAC would have to packet sniff.

**Comment by CeIebrimbor** [comment]
The only issue I've seen was the jesus check with blocks on the water surface. I have never seen issue with GP blocks on land.

**Comment by RoboMWM** [comment]
This was discussed in the GP thread some time ago. If someone could dig that up, that'd be appreciated, as I said what needed to be said there.

**Comment by CeIebrimbor** [comment]
https://www.spigotmc.org/threads/griefprevention.35615/page-90#post-1274403

**Comment by RoboMWM** [comment]
Actually, if anticheat plugins detect issues like this, they could potentially resend/update the blocks near the player. Would also help alleviate other issues that could occur with "fake" blocks.

**Comment by konsolas** [comment]
Sounds like an idea, at X violations for a check resend the blocks near the player. The thing is, would this cause conflicts with other plugins such as Orebfuscator?

**Comment by Janmm14** [comment]
If ypu only send a small area, the impact of things partly not being obfuscated should be low.

**Comment by RoboMWM** [comment]
> The thing is, would this cause conflicts with other plugins such as Orebfuscator? 

Afaik, if we're triggering chunk updates, Orebfuscator will see this and obsfucate accordingly.

**Comment by Janmm14** [comment]
A command /aacrestorechunk has been created

**Comment by CeIebrimbor** [comment]
Jesus is the only check that had issues. Jesus is no longer a required check.
