### ISSUE TITLE
AAC Command bug

### ISSUE THREAD

**Issue by JoshuaPvP** [konsolas/AAC-Issues#870]
### Issue description
When i use a AAC command from my console than it works. But when i use it form a Player INGAME, than comes a fake Message: Unknow command type '/help' for help.
Normal Message:  Unknow command type ''/help'' for help.

You can see it on ''/help''. An example i can use aacban [Player] in the console of one of my server. But whith my normal Player Account.

Intall: i have a Bungee-Network and i load the AAC and ProtocolLib Plugins in all Plugin-Folders of the under-Servers (Not Bungee Server) SpigotServers

### Core information
**Server version**: 1.8.8

**AAC version**: 3.2.2 -b1

**ProtocolLib version**: 4.2.1

**Plugin list**: AAC, ProtocolLib, Worldedit, Worldguard, CoinsAPI, AntiXray(orebfuscator4), ChatEX, Buycraft, OnlyProxyJoin, ViaVersion, Multiverse-Core, PermissionsEx, Self coded Plugins(Freebuild-System)

### Special environment information
**ViaVersion version**: 1.0.4

**ProtocolSupport version**: -

**ViaBackwards version**: -

**BungeeCord plugins**: SayNoToMCLeaks, YamlerBungee, BungeeYAML, Buycraft, Self coded Plugins(Bann and Rank System)

### Configuration
Default AAC Config.

**Comment by Janmm14** [comment]
Likely a problem with your personal plugins.

**Comment by JoshuaPvP** [comment]
no this Plugin makes /day /night /sun /rain
an first join Iteams. Thats all of the Plguin

**Comment by konsolas** [comment]
Make sure you have the permissions from your player account, and that you're typing the commands correctly. AAC commands all work when executed as a player. For /aacadmin, execution as a player is necessary.

**Comment by JoshuaPvP** [comment]
I have OP on my Server. Also i have in permissionsEx the * Permission.
And i cant use the /aacadmin or the /aac command. All of the AAC commands dose not work form a Player. Only from my Console of the Server.

**Comment by JoshuaPvP** [comment]
I can use the AAC commands form a Player on a only Spigot Server but not on one of my underserver´s form BungeeCord Network.

**Comment by Janmm14** [comment]
1. Make sure you have set bungee config.yml `ip_forwarding: true` / spigot.yml `bungeecord: true`
2. Firewall your spigot servers if in production environment / ip is public.
3. Each spigot server needs AAC.jar in its plugins folder.

**Comment by JoshuaPvP** [comment]
Sorry for the Problem. But it is not fixed. I have a Bungee-Network and when i use /aac comes a fake message unknow Command but AAC workes. But i like to use /aacadmin. I can use all aac command only form Console. But i can use /aac commands when i have a singel spigot Server.

**Comment by Janmm14** [comment]
This is not a problem related to AAC in that case.
