### ISSUE TITLE
Glitched Liquid = MiniJump

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#871]
### Issue description
Stepping/swimming in a glitched lava source due to a world protection gets you kicked for minijump(Criticals) near instantly. Liquid sources sometimes get stuck on the client side, unlike full blocks.

Video: https://youtu.be/7WOqruQXeDM?t=4m6s

### Core information
**Server version**: 1.8.8

**AAC version**: 3.2.1.-b1

**ProtocolLib version**: 4.2.0

**Plugin list**: Typical world protection 

### Configuration
jump_delay: 4

**Comment by Janmm14** [comment]
Best option would be to not give players such liquids while not in adventure mode with proper nbt usage restrictions.
Alternatively one could build a simple plugin which will cancel criticals for a certain time after attempting to place liquids and being near the cancelled block placement.

I do not see a specific solution that is not opening bypasses.

**Comment by konsolas** [comment]
Similar answer to the one I give for block glitching under world protection plugins.
