### ISSUE TITLE
PlayerTeleportEvent to AAC 3.2.2

### ISSUE THREAD

**Issue by WeLoveSpigotPlugins** [konsolas/AAC-Issues#872]
https://pastebin.com/cpifexyd

### Core information
**Server version**:  1.8.8

**AAC version**: latest

**ProtocolLib version**: latest

**Plugin list**: SkyWars Plugin (Fail on Teleport)

### Special environment information
**ViaVersion version**: latest BungeeCord

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: Not relevant for AAC

### Configuration
Celebrimbor latest configuration

**Comment by MClausz** [comment]
one of your plugins teleports players asynchronously, contact the developer of that plugin
