### ISSUE TITLE
Hitbox move_compensation not working (causing FP)

### ISSUE THREAD

**Issue by SnakeDaoust1232** [konsolas/AAC-Issues#873]
Info:
- Hitbox check still having a heart attack when running behind someone and hitting them.

Video: https://www.youtube.com/watch?v=8_I6TebOxrw&feature=youtu.be

Core information

Hitbox Config: https://hastebin.com/ecuxaqudak.bash

Server version: Spigot, Paperspigot and Tacospigot 1.8.8
AAC version: 3.3.0
ProtocolLib version: 4.2.0
Plugin list: (Upon request)

Special environment information

ViaVersion version: none
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by CeIebrimbor** [comment]
This is related to Hitbox's inability to recognize velocity. It is also exacerbated with Speed potions. Without Speed potions, you typically see 3.6-4.5 block reach in a chase. 5+ with the potions.

**Comment by Janmm14** [comment]
There is no hitbox strechting happening. It looks more like a combination of a little lag and hitting in near 45°-angles in relation to the blocks

**Comment by SnakeDaoust1232** [comment]
@CeIebrimbor @Janmm14 You both agree that AAC needs to account for "this" either way though right?

**Comment by SnakeDaoust1232** [comment]
@konsolas The move_compensation isn't initiated or is not working at all. I just tested this issue on the same settings with 2.0 move comp and same results.

**Comment by CeIebrimbor** [comment]
What about 3.0 or 4.0 move comp? I set at 3.0 (which technically allows 4.6 reach when target is sprinting), and that seems to do the trick.

**Comment by SnakeDaoust1232** [comment]
@CeIebrimbor  I ended up setting it to 5 and nothing changed.

**Comment by SnakeDaoust1232** [comment]
@CeIebrimbor What server version are you on because its not working on 1.8.

**Comment by SnakeDaoust1232** [comment]
@konsolas I also was wondering if you have changed anything with the killaura check since there was hitbox issues with that as well.

**Comment by Cryptite** [comment]
This is still a major issue in 1.12.1, FWIW. Have had to disable the hitbox check as any sprinting will false positive most hits.

**Comment by CeIebrimbor** [comment]
@SnakeDaoust1232 
Can we have some new detection after the addition of `move_compensation`?


I have many users with limited issues on these settings. Only people who have issues are those with non-vanilla or "combo" pvp:
```
   lenience: 0.65
   max_reach: 3.45```

**Comment by SnakeDaoust1232** [comment]
@CeIebrimbor The logs don't change from move comp .1 to move comp 5.

**Comment by Cryptite** [comment]
I can concur with this; it's critical. If it's on, players can't hit each other just when sprinting after others. I've had to leave it off for some time now.

**Comment by CeIebrimbor** [comment]
Hmm, seems confirmed after asking around. The `move_compensation` does not do anything to modify the detection behavior... I have brought this to the forefront of Konsolas' attention...

**Comment by konsolas** [comment]
Hitbox is getting another rewrite, but I'll need to test it first before release.
