### ISSUE TITLE
Spider Problem

### ISSUE THREAD

**Issue by TrieuDepzai** [konsolas/AAC-Issues#876]
i think spider hack have an problem if block higher 2 , spider can't do anything 
but if just only 1 block spider will bypass this anti 
can you fix it ?
 
**Server version**: 1.8.8

**AAC version**: AAC 3.3.0-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: Viaversion | ProtocolLib | Essentials | AAC

**ViaVersion version**: 1.0.4

**Comment by Rerd** [comment]
whats the point of blocking 1 block high spider its just going to slow the player down

**Comment by Slimerblue22** [comment]
Do you know which client the spider hack your talking about is on? There are tons of diff clients and not all work the same.

**Comment by Games4k** [comment]
Its not really the best idea to block 1block spider... It can make a large amount of fp-s

**Comment by Janmm14** [comment]
I think it would not make false positives.
Spider 1 block is just like step cheats, right?

**Comment by CeIebrimbor** [comment]
1 block Spider is just a slow step. AAC doesn't detect/stop 1 block step.

**Comment by Janmm14** [comment]
By the way, this bypass should be fixed in newer AAC versions.
