### ISSUE TITLE
Ignore async teleport

### ISSUE THREAD

**Issue by MClausz** [konsolas/AAC-Issues#877]
Players can be teleported asynchronously now, but AAC doesn't like it, it spams the console every time a player teleported asynchronously.
Is it possible for AAC to ignore async teleport instead of throwing an exception?

**Comment by Janmm14** [comment]
@MClausz 
From bukikt's/craftbukkit's side it was always possible to teleport asynchroniously, although the API of the bukkit scheduler stated that it is not safe to interact with the bukkit api asynchroniously for nearly everything, see [BukkitRunnable#runTaskAsynchronously](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scheduler/BukkitRunnable.html#runTaskAsynchronously-org.bukkit.plugin.Plugin-).

I do not see any recent commits stating that teleportation behaviour got changed.

Even if such behaviour would have been changed, AAC still needs teleports to occurr synchroniously, becaue it calls some internal nms methods which - when used asynchroniously - can lead to server crashes - which occurred to some customers already.

**Comment by Janmm14** [comment]
Closing due to no answer of any changes to in relation asynchronous teleports in (paper)spigot or whatever fork.
