### ISSUE TITLE
Eating endfruit for multiple times may cause AAC speed check false positive.

### ISSUE THREAD

**Issue by smartmadio** [konsolas/AAC-Issues#878]
### Issue description
Eating endfruit for multiple times may cause AAC speed check false positive.

No console error.

### Core information
**Server version**: 1.12.1

**AAC version**: 3.3.0

**ProtocolLib version**: 4.4.0-b379

**Plugin list**: insert

### Special environment information
**ViaVersion version**: 1.2.0

**ProtocolSupport version**:  N/A

**ViaBackwards version**:  2.2.0

**BungeeCord plugins**: N/A

### Configuration
Default configuration

**Comment by Janmm14** [comment]
Please do not use ProtocolLib Dev builds currently, they are not compatible with AAC as far as I know.

**Comment by smartmadio** [comment]
All right ,problem solved.
