### ISSUE TITLE
EntityDamageByEntityEvent and PlayerInteractEvent spam

### ISSUE THREAD

**Issue by JuliCarles** [konsolas/AAC-Issues#880]
### Issue description
These errors are spammed in console:
http://www.youscreenshot.com/a533c101881135a73bd63f84cec6ba55
http://www.youscreenshot.com/62777b1b3e0d8db382d59e2e066a59e5
It's spammed like 2 times every 6 seconds.

That would be it.

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 3.3.0-b1

**ProtocolLib version**: 4.2.0

### Special environment information
**ViaVersion version**: Latest

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Not needed.

**Comment by konsolas** [comment]
of #881
