### ISSUE TITLE
Silent checking

### ISSUE THREAD

**Issue by Games4k** [konsolas/AAC-Issues#884]
Hello!
AAC was always a good anticheat, but when it comes to silent checking (ex. fly with teleportation: false, jesus with teleportation: false, or speed with minvl: 300+), it can make a large amount of false positives (every time someone gets VL1, vls will start climbing until he gets banned).

In my opinion, the best way to ban movement cheaters is silent checking, because when someone see that anticheat is lagging him down, he'll probably get better client, or try another settings until he finally bypass it, but when he dont see that server have anticheat, he will fly and fly and AAC will ban him in 5-6 seconds.

I really hope you'll improve silent checking and add normal teleport option to speed check!

Thanks :)

**Comment by CeIebrimbor** [comment]
Very possible with current config options. I do it for people all the time.

teleport: false
reduce_delay: 1
ban on 5000

**Comment by Games4k** [comment]
@CeIebrimbor, yes, i can set it to 5000, but its still really bad silent detection. Also, wirh reduce_delay: 1, they will probably be able to fly for 10-15 secs, and than stop flying for 1-5 secs, and they'll be able to fly normaly again!! On some other anticheats like spartan,silent detection is much better (tested on test server, cant remember the name). Spartan can block every cheat in silent detection normaly and without any false positives in 1-2 seconds. AAC is really good anticheat, and I dont know why cant it do the same thing? 

I hope you'll reopen my issue and make silent detection better!!

**Comment by Janmm14** [comment]
The reason for the bad silent checking is, that there was not put extended focus onto silent checking, more focus was put onto the setback system.
AAC uses similar math to the client's movement math which is heavily dependant on the previous movement.
I see some possibilities atm in my mind where the silent checking could be theoretically improved, but I can't make guarantees it will not open up attack vectors to the speed and fly check which will cause stuff to not get detected with the expected amount of vl.

**Comment by Games4k** [comment]
Thanks!

**Comment by GeoGamerLP** [comment]
I personally dislike silent checking as it has no real advantages if you think further.
The main arguments defending is that hackers don't know what they got kicked/banned for like they would if they get setbacks after x violations.
It will be definitely slower, but there will be some players testing every single module and settings of their client to look which hack autobans them with which settings. And if players find out that you are using AAC, then this advantage is gone immadietly anyway. 
In general, silent flagging is a bad option/decision imho. You need to think like a legit player. Even if hackers get banned fast, they still had an blatant advantage against legits for that time (at least for the cheats that are silent checked). As previously said, you will basically "lose" highjump and step check. It is not really less annoying for legits to get rekt by insane fly and speed (and some other hacks if you turn them silent too) hackers which might get banned faster than to play against a (way) less obvious hacker which can hack longer but doesn't have that much of an advantage.

**Comment by konsolas** [comment]
AAC will not focus on silent checking. The option is there if you want it, but the checks will be tuned to what would normally be expected of an anticheat.
