### ISSUE TITLE
WallSpeed, TeleportHit and KillAura works on AAC

### ISSUE THREAD

**Issue by TheTadeSK** [konsolas/AAC-Issues#885]
### Issue description
Hi, our player on our server has send us a video, where works WallSpeed, TeleportHit and KillAura

https://www.youtube.com/watch?v=V_3N3QPMUXg&t=25s
### Core information
**Server version**: Latest spigot 1.8.8

**AAC version**: Latest to date 19.8.2017

**ProtocolLib version**: recomended for spigot 1.8.8

**Plugin list**: Ask and i will give you...

### Special environment information
**ViaVersion version**: latest to date 19.8.2017

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: Ask and i will give you...

**Comment by Janmm14** [comment]
Are you sure your AAC version was 3.3.0 or 3.3.0-b1 at recording time?

**Comment by tade159SK** [comment]
Its 3.3.0-b1

**Comment by Janmm14** [comment]
do you have any chance of getting the aac log file or the console log file of that video?

**Comment by Slimerblue22** [comment]
Its this client https://www.youtube.com/watch?v=PHMXPRe-ZYU (Not sure if this is any help whatsoever but here anyways)

**Comment by tade159SK** [comment]
@Janmm14 we have over 50+ servers with BedWars, we don't know time when he was hacking

**Comment by tade159SK** [comment]
@Janmm14 i will send you a config file, but only privately

**Comment by Janmm14** [comment]
the config file is not important, except heuristics probability and speed min_vl

**Comment by tade159SK** [comment]
Working client with Wall Speed: https://mega.nz/#!5O5VgL7S!jEyXQijjG0XyrdxlkamCS6zo5BySJJ8gtLQzhYn9gAI

**Comment by onemoreplays** [comment]
Tade, nemáš oprávnění to video použít bez mého vědomí :)

**Comment by TheTadeSK** [comment]
Video je volne dostupne na yt, moze si ho najst kazdy

**Comment by onemoreplays** [comment]
Uvidíme co na to řekne GitHub podpora. Možná že mě pošlou někam, možná toto vymažou. Uvidíme :)

**Comment by onemoreplays** [comment]
btw, jsem u vás na TS ale nikdo neodpovídá :)

**Comment by PzoeCZ** [comment]
Lol to váše AAC stojí za hovno. :)

**Comment by iProEaZy** [comment]
Asi tak. A ten "váš" Doge tiež :)
