### ISSUE TITLE
SPAM IN CONSOLE

### ISSUE THREAD

**Issue by JavituRec** [konsolas/AAC-Issues#886]
I have several servers and the error occurs in all. Therefore it is a general error that we are probably having all the users that use the latest version.

1.- SPAM ERROR IN CONSOLE: https://hastebin.com/yamegireti.bash
2.- SPAM ERROR IN CONSOLE: https://hastebin.com/ejatutojis.vbs

Server version: 1.8.8

AAC versio: 3.3.0-b1

ProtocolLib version: 4.3.0

ViaVersion version: ViaVersion-1.2.0

**Comment by konsolas** [comment]
of #881
