### ISSUE TITLE
Sentinel Support

### ISSUE THREAD

**Issue by Malavent** [konsolas/AAC-Issues#889]
### Issue description
Current support for Sentinel with AAC is **not** supported.
### Core information
**Server version**: 1.8.8 PaperSpigot

**AAC version**: 3.3.0

**ProtocolLib version**: 4.3.0

**Plugin list**: AAC, Citizens 2, Sentinel

### Special environment information
**ViaVersion version**: 1.1.1

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/a

**BungeeCord plugins**: N/A

### Configuration
Nothing

**Comment by Janmm14** [comment]
What is not working exactly?

**Comment by CeIebrimbor** [comment]
See #365

**Comment by Janmm14** [comment]
Although stuff will be spammy in the console due to those exceptions, it will not break the check process of real players.
