### ISSUE TITLE
Cobble generator = Interact

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#891]
### Issue description
Stand at your typical cobble generator and mine while blocks spawn in front of you. Default config does not kick, but it would start blocking block breaks rather quick.

Typical generator:
https://gyazo.com/62bff88c073d6856d570da69b6358665

Detection Log:
https://pastebin.com/VtBZm3sU

### Core information
**Server version**: 1.12.1

**AAC version**: 3.3.0-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: Vanilla mechanic

### Special environment information
N/A

### Configuration
Not relevant for Interact check.

**Comment by konsolas** [comment]
Seems to no longer be an issue at the moment.
