### ISSUE TITLE
Remove outdated/pointless config options and features

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#892]
- [ ] Jesus Check _(edit: does fly need to adopt some checking first?)_
- [ ] Knockback Check
- [ ] `kill_loggers` (now 100% useless due to removal of `combat_time`)

 ❔ ~~Remove Spam Check?~~ Or make it disabled by default due to a _very_ limited use.

[Poll results](http://www.strawpoll.me/13773535/r) from just my clients regarding Spam check usage.

**Comment by SnakeDaoust1232** [comment]
@CeIebrimbor Keep the jesus check. Many clients bypass unless the jesus check is enabled.

**Comment by Janmm14** [comment]
watermovement check in speed or fly will soon hopefully be able to improve

**Comment by CeIebrimbor** [comment]
> And i use the spam check with my config....

The Spam check comments are just to make it disabled by default in the config, not to remove. Even if only 5% of people use it, it's worth keeping.

**Comment by MClausz** [comment]
the spam check is useful for me

**Comment by CeIebrimbor** [comment]
Understood. I am no longer putting "remove the spam check" on the table. It's clear that enough people find it useful. I was mearely curious and now I'm just suggesting it be false by default.

**Comment by Slimerblue22** [comment]
As for the Jesus check I have it on due to the fact with the Impact hacked client Jesus bypasses if on flowing  water, strange but true, the Jesus check stops it

**Comment by konsolas** [comment]
Jesus check will be enabled by default next update since most people seem to be using it anyway. Knockback check will stay just in case someone wants to use it, kill_loggers will be removed.
