### ISSUE TITLE
No Hit Delay False Positives

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#897]
### Issue description
When the server hit-delay is set to 0, you get Killaura flags (normal and hitbox). Your opponent will get Fly/Speed flags.

Video: https://youtu.be/sAWcjjFnBcU

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.1-b1

**ProtocolLib version**: 4.2.0

**Plugin list**: AAC, ViaVersion, 

### Special environment information
**ViaVersion version**: 1.1.1

**ProtocolSupport version**: N/A

**ViaBackwards version**:  N/A

**BungeeCord plugins**: N/A

**Comment by CeIebrimbor** [comment]
Definitely not recommended and I would not hold your breath on a fix for something like this.

**Comment by CeIebrimbor** [comment]
@iConfueZ Did you change the hit delay to something reasonable? Or are you still hoping for AAC to not detect hacks you are (basically) allowing? Just want to know if we could close the request since it's rare to see a server open the door to 0 tick hit delays and expect success.

**Comment by LinsaFTW** [comment]
I recommend you to set it to 2 or 3 delay it will reduce false positives with combat detections.

**Comment by iConfueZ** [comment]
@LinsaFTW not really, Killaura normal flags like hell, same for Fly.

**Comment by konsolas** [comment]
NoHitDelay compatibility will not be added.

**Comment by Minemaniak** [comment]
@konsolas Maybe could you add this https://github.com/konsolas/AAC-Issues/issues/1175 ? Then it woul be possible to not check people that are in nothitdelay combat, currently it's impossible even trough API because heuristics can't be restarted for certain player and it flags forever.
