### ISSUE TITLE
Ignoring Speed Attribute Modifier

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#898]
AAC is ignoring Movement Speed Attribute Modifiers. It will flag for Speed. I'm using this for a kit on my kitpvp server and this is needed for one of the kits.
Type this command in a commandblock and hold it, then walk around: https://hastebin.com/evunudofew.pl

### Core information
**Server version**: https://gyazo.com/4908c5e081232256270e3ed0526f4043

**AAC version**: 3.3.1-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: https://gyazo.com/e9808296a04642d9dd68e0ef434240d3

### Special environment information
**ViaVersion version**: 1.2.0

**ProtocolSupport version**: 4.23.dev

**ViaBackwards version**: N/A

**BungeeCord plugins**: When requested.

**Comment by CeIebrimbor** [comment]
Please see #206 

While this is (maybe) going to be supported at some point, it is best that your kits apply potion effects (which are supported).

**Comment by Rerd** [comment]
I sort of need it as soon has there's time because I have a kit that uses attribute modifiers to make players go faster and slower while holding certain items in their hand. It's much easier like this and using potion effects would be really hard to do for different ones by switching items in their hand. Currently I am having to turn the speed threshold up because of this.
