### ISSUE TITLE
Falling through the blocks after fly detection + Fly FP [the most important bug of AAC]

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#899]
Unfortunately this is not fixed. And it happens very often.
Without AAC, this never happens.
All the players on my server are just furious, it's been two months now.
This is unbearably hampering the play.

Latest AAC, 
Latest Spigot 1.12.1
Lastest ViaVersion + Latest ViaBackwards
It also happens on Spigot 1.8.8 + Latest ViaVersion

If necessary, I can attach logs, videos, screenshots. I have a lot of this.
In the falling into the blocks, the Fly check is to blame. Because in logs verbose it is fly check.

**Comment by RaynLegends** [comment]
It's ridiculous, it's literally made AAC unusable.

I can confirm that it "works" both using 1.8.8 + ViaVersion and 1.12.1 + ProtocolSupport, using the latest version of AAC (but it is present since May at least).

**Comment by Toshka17** [comment]
Video: https://youtu.be/DW1q_ZV72bQ
Log: https://pastebin.com/NTnhVjFe
[08:32:24 INFO]: Plugins (2): AAC, ProtocolLib
Spigot 1.12.1

**Comment by ItzSomebody** [comment]
Any version of AAC + ProtocolSupport can be expected to have problems do to ProtocolSupport doing something funny to the packets.

@Toshka17 there is no such thing as Spigot 1.8.9 lol.
@Toshka17 @RaynLegends what versions of ProtocolLib are you using for 1.12.1 and 1.8.8?

**Comment by Toshka17** [comment]
This occurs even without Protocolsupport or viaversion.
Look at my previous post: only AAC and ProtocolLib

**Comment by Toshka17** [comment]
Recommended 4.3.0 ProtocolLib (build #373)
@ItzSomebody You funny from a typo?

**Comment by ItzSomebody** [comment]
Some other people are having the same bug, hmm.

**Comment by ludgart** [comment]
I have the same problem.

Latest AAC
Spigot 1.8.9
ProtocolLib v4.2.1
ViaVersion: 1.1.1

**Comment by CeIebrimbor** [comment]
This bug is now known by hackers and is being used maliciously to get sucked under blocks and become invincible. As reported in #914.

**Comment by konsolas** [comment]
@Toshka17 are you able to provide a minimal, verifiable example? For example, a spigot server with only AAC and ProtocolLib, where /tp player <x> <y> <z> causes the bug to occur consistently?

**Comment by Toshka17** [comment]
@konsolas but I already did it, read my previous post on Aug 28, 2017...

Video: https://youtu.be/DW1q_ZV72bQ
Log: https://pastebin.com/NTnhVjFe
[08:32:24 INFO]: Plugins (2): AAC, ProtocolLib
Spigot 1.12.1

**Comment by konsolas** [comment]
I'm going to take a moment to rebuild 1.12.1 then, since I'm not having that issue

**Comment by Toshka17** [comment]
I will now record one more video.

**Comment by konsolas** [comment]
Fresh 1.12.1 build (since 5 minutes ago) with AAC 3.3.1 and ProtocolLib 4.3.0:

I ran this command in the console multiple times:
![image](https://user-images.githubusercontent.com/9408210/29996563-dfffd0e2-8ff8-11e7-8e95-01891996a22f.png)

which points to a grounded location, seen here: 
![image](https://user-images.githubusercontent.com/9408210/29996566-edf68790-8ff8-11e7-87df-49b3e115b1b3.png)

Each teleport to the location was successful, and I wasn't stuck under the ground, regardless of elevation or location before the teleport.

**Comment by Toshka17** [comment]
You have to teleport a long distance to get it

**Comment by konsolas** [comment]
How long?

**Comment by Toshka17** [comment]
5 thousand blocks are enough

**Comment by Toshka17** [comment]
https://youtu.be/IEUepn3kGCQ

**Comment by CeIebrimbor** [comment]
I was under the impression that the Fly setback was the main cause. Which just so happened to occur with most long range teleports

**Comment by Toshka17** [comment]
The most important problem is not in teleportation. Teleports only give false positives of fly check. The main problem is that fly check when you try to act on the player teleports it through the blocks.

If you find any other false positives of fly check, players will also teleport through the blocks.

**Comment by konsolas** [comment]
teleporting myself between -3000, 4, -3000 and 3000, 4, 3000

not only was I not sucked into any blocks, I didn't even get any fly violations

**Comment by konsolas** [comment]
@Toshka17 could you rebuild spigot 1.12.1, maybe that's the cause.

**Comment by konsolas** [comment]
Just added some generic code to prevent fly from teleporting into blocks, but I can't test it.

**Comment by Toshka17** [comment]
Okey, this does not happen with a clean spigot. But it still happens with viaversion.

**Comment by konsolas** [comment]
I thought your test case was just AAC and ProtocolLib?

**Comment by Toshka17** [comment]
Yes, it was so, but I pumped the last spigot and tried to repeat it many times - I did not succeed.

**Comment by Toshka17** [comment]
> Just added some generic code to prevent fly from teleporting into blocks, but I can't test it.

Can I somehow test this right away?

**Comment by konsolas** [comment]
Sure; do you have discord? Join the AAC server and send me a DM

**Comment by GeoGamerLP** [comment]
Just tried to do it again on GommeHD (QSG) and it seems to be fixed. I wasn't able to get sucked into a block.

**Comment by Toshka17** [comment]
But this does not mean that it does not exist
