### ISSUE TITLE
[Bypass] Yport speeds

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#9]
NoSlowdown seems to be bypassing by jumping while eating. Note that the jump is shorter in vanilla when eating, but that seens to not get checked.

**Comment by konsolas** [comment]
Could you clarify what you mean by this? Does sprint-jumping in general bypass?

**Comment by Photon-GitHub** [comment]
It is not only a NoSlowdown bypass but a complete AAC bypass (Y-Port speeds)
I fixed this by adding a long-term check to prevent too much jumps (I consider 8 jumps / 5 sec. as legit and flag everything above that value)

Slow example Speed mod:
`
if(mc.thePlayer.onGround)
			{
				mc.thePlayer.jump();
			}else
			{
				mc.thePlayer.motionY = -0.2;
				mc.thePlayer.motionX *= Cer.instance.optionManager.speedOptionManager.getSpeedFloatOption(SpeedMultiplier.class).getValue() / 5;
				mc.thePlayer.motionZ *= Cer.instance.optionManager.speedOptionManager.getSpeedFloatOption(SpeedMultiplier.class).getValue() / 5;
			}
`
To see the check feel free to decompile my plugin.

**Comment by Janmm14** [comment]
One hack client I have seems to simply toggle between y coordinates x.2 and x.0, spectating f3.

**Comment by Photon-GitHub** [comment]
Also be sure to think of height randomizations when fixing this and think of the fact that not all positions can be obtained legit, especially when having no velocity.

**Comment by konsolas** [comment]
I plan to create a whitelisted test server with a beta of the new version, for people to test these things before an eventual release.

Speed is getting a full rewrite, which also appears to deal with my implementation of yport.

**Comment by Photon-GitHub** [comment]
Fixed on the test-server, recommended to close this issue.

**Comment by Photon-GitHub** [comment]
This speed is still a thing.
You should take a look at my detection in AACAddition,
to reproduce take my client cer with following options:
Mode: Y-Port
Multiplier: 1.07 (something around 1)
Divider: same as Multiplier.

Works perfectly and is a lot faster than legit sprint-jumping.

**Comment by Photon-GitHub** [comment]
You can also use:
Mode: Minijump
Multiplier: something around 5
Divider: same as Multiplier.

**Comment by konsolas** [comment]
Tested both and are blocked. @Photon-GitHub will close for now, re-open if you find new settings.
