### ISSUE TITLE
Move check does not respect bypass permission, Op, or Spectator mode

### ISSUE THREAD

**Issue by Cryptite** [konsolas/AAC-Issues#900]
Quite simply, you will still get kicked for move violations (example being using a cam mod) regardless of having the bypass permission, being OP or being in Spectator mode.

**Comment by CeIebrimbor** [comment]
This is known and currently impossible to navigate around.

**Comment by Cryptite** [comment]
Could at least the bypass block the punish/kick aspect part of the check? I understand the data for tracking is required, but one would expect the aac.bypass permission to work as it claims.
