### ISSUE TITLE
Hitbox/Fightspeed FP?

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#903]
Latest AAC
Log: https://pastebin.com/VDKhGW0t

User "description": 5 minutes of killing mobs in a larger mob farm (skyblock)

**Comment by Photon-GitHub** [comment]
Seems pretty unlikely as he also got NoSwing and Fightspeed flags (who would have 16 cps in a mob farm)

**Comment by CeIebrimbor** [comment]
Assuming you are using my setup, you have a higher lenience too. For this to be looked into, we need a full report to include versions, and conditions (I.e. Spam clicking slimes from a tall angle).

**Comment by Hyronymos** [comment]
Video: http://plays.tv/video/59a4816f42c15d5202/skyblock
Log: https://hastebin.com/zivayamipi.hs

**Comment by CeIebrimbor** [comment]
FightSpeed: clicking with a **CPS of 78**

If you want to allow macros modifications, then disable the fightspeed check.
