### ISSUE TITLE
Jesus Bypass

### ISSUE THREAD

**Issue by MihaiMalos** [konsolas/AAC-Issues#905]
### Issue description (attention: bad english incoming)
I found Jesus bypass on the original test server with client Medusa b0.4.8
Video right here: https://youtu.be/m1ls_uWnYIQ

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.1 b1

**ProtocolLib version**: -

**Plugin list**: -

### Special environment information
**ViaVersion version**: -

**ProtocolSupport version**: -

**ViaBackwards version**: -

**BungeeCord plugins**: -

### Configuration
-
I am sorry if i did some mistakes, but is first time when i report something here

**Comment by SnakeDaoust1232** [comment]
@MihaiMalos The jesus check is disabled by default. Make sure you enable it.
