### ISSUE TITLE
Error while starting the Server

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#907]
Error: https://hastebin.com/ewafitowim.md

**Comment by CeIebrimbor** [comment]
Server, AAC and ProtocolLib version?

**Comment by Janmm14** [comment]
More important: JVM version? Debugger or any other kind of java agent used?

**Comment by Hyronymos** [comment]
Server: 1.8.8
AAC: latest 
ProtocolLib: 4.1.0

Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by CeIebrimbor** [comment]
ProtocolLib: 4.1.0
Please update to 4.2.0

**Comment by CeIebrimbor** [comment]
> ProtocolLib: 4.1.0

Please update to 4.2.0

**Comment by Janmm14** [comment]
Can you try updating java to the latest version? Does it happen always or jsut sometimes?

**Comment by Hyronymos** [comment]
just sometimes

**Comment by CeIebrimbor** [comment]
Same as #904?

**Comment by Janmm14** [comment]
Not the same error, but likely the same cause.

**Comment by Hyronymos** [comment]
Looks like  Protocollib 4.2.0 fixed the issue
