### ISSUE TITLE
TeleportCause.PLUGIN = Speed Kick

### ISSUE THREAD

**Issue by JamieSinn** [konsolas/AAC-Issues#909]
https://www.youtube.com/watch?v=Npta-Cq1urY

Seems to be related to teleporting. 

All plugin teleports are using TeleportCause.PLUGIN - including the event/system here. Should this be a different cause?

This only occurred since the 1.12.1 update.
AAC Version:
3.3.1|b1
Config: 
3.3.1|1-Config-Celebrimbor

ProtocolLib Version:
4.3.0-Dev-#373

Spigot Version:
BuildTools-Jenkins-#1391

**Comment by ItzSomebody** [comment]
Wouldn't this be a better question to ask in Celebrimbor's LT Discord?

**Comment by JamieSinn** [comment]
I'm not the owner of the server, only the developer. I don't have access to that discord.

**Comment by CeIebrimbor** [comment]
Config is not relevant here. Konsolas may have to comment on what you should do for the teleport because it's clearly not compliant.

**Comment by JamieSinn** [comment]
That's more or less what I expected. Considering the teleport reason being PLUGIN, I would expect AAC to conform to it, instead of the other way around.

**Comment by CeIebrimbor** [comment]
It would help to see a detection log, something I assume you don't have access to, but I would imagine it says something like "player failed Speed: Tried to move 481.88 blocks"

**Comment by JamieSinn** [comment]
I do have access to it. Will post relevant lines.

**Comment by JamieSinn** [comment]
```	Line 189696: [25-08-2017 16:04:58.316] CaptainDeath33 failed Speed: moved too quickly: 25.739 blocks/tick (0.297/-0.449)-n -n [ping:63 tps:20.0] VL:100
	Line 189700: [25-08-2017 16:04:58.366] CaptainDeath33 failed Speed: moved too quickly: 25.739 blocks/tick (0.297/-0.030)-n -n [ping:63 tps:19.98] VL:200
	Line 189702: [25-08-2017 16:04:58.415] CaptainDeath33 failed Speed: moved too quickly: 25.739 blocks/tick (0.297/0.131)-n -n [ping:63 tps:19.99] VL:300
	Line 189704: [25-08-2017 16:04:58.466] CaptainDeath33 failed Speed: moved too quickly: 25.739 blocks/tick (0.597/0.460)+n -n [ping:63 tps:19.99] VL:400
	Line 189706: [25-08-2017 16:04:58.516] CaptainDeath33 failed Speed: moved too quickly: 25.739 blocks/tick (0.434/0.156)+n -n [ping:63 tps:19.99] VL:500
	Line 189708: [25-08-2017 16:04:58.566] CaptainDeath33 failed Speed: moved too quickly: 25.739 blocks/tick (0.234/0.000)+n +n [ping:63 tps:19.99] VL:599```

**Comment by JamieSinn** [comment]
Full pastebin of the last few days with all speed violations >10 blocks per tick
https://pastebin.com/CnWAVkgD

**Comment by JuliCarles** [comment]
I'm running into similar issues with plugins running a Player#teleport.

**Comment by CeIebrimbor** [comment]
> Full pastebin of the last few days with all speed violations >10 blocks per tick
> https://pastebin.com/CnWAVkgD

Looks like your server has some ping issues. Most are either 0ms or 5000000000000000000000000000ms

Still, seems like some sort of teleport method incompatibility. We'll wait on developer to comment.

**Comment by konsolas** [comment]
I have tested locally - EssentialsX uses TeleportCause.PLUGIN (like most plugins), and everything functions normally.

There's clearly another factor here - could you please fill out the issue template with more server information?

**Comment by CeIebrimbor** [comment]
Except for config info. Konsolas has access to my config when it's relevant.

**Comment by jordinjm** [comment]
I would recommend not attempting to teleport with AAC as you have a higher chance of getting de-synced then getting properly teleported.

**Comment by JamieSinn** [comment]
The only thing I could see as relevant is the BungeeCord plugin list, as we don't have any other plugins listed. (ProtocolSupport, ViaVersion, etc) - If you need this, PM me on discord. - JamieSinn#6605

**Comment by CeIebrimbor** [comment]
@JamieSinn 
Should this be closed Or are you still looking for solutions as it related to plugin teleports?

**Comment by JamieSinn** [comment]
I'll close as I haven't seen any further issues. I'll re-open if it happens again.
