### ISSUE TITLE
WallSpeed Bypass AAC 3.3.1

### ISSUE THREAD

**Issue by TheTadeSK** [konsolas/AAC-Issues#911]
Found a bypass video of WallSpeed hack

Working on AAC 3.3.1 (latest to date 29.8.2017)

https://www.youtube.com/watch?v=p2jSJWUiRxc

**Comment by CeIebrimbor** [comment]
Modified config settings at all? Server and ProtocolLib version?

Better yet, can you test this on the official test server and record?

**Comment by konsolas** [comment]
No response from issue author.

**Comment by Janmm14** [comment]
Wallspeed was fixed in recent versions of AAC.
