### ISSUE TITLE
The server stops after AAC is activated. [CRITICAL] (3.3.1-b1)

### ISSUE THREAD

**Issue by craftrise** [konsolas/AAC-Issues#912]
### Issue description

When the AAC plugin is enabled, the server stops and stays.
This problem will not always happen. It happens only at certain times. (No information)

**ERROR INFO: https://hastebin.com/ibukiwiweg.md**

### Core information
**Server version**: 1.8.8 SPIGOT

**AAC version**: LATEST - 3.3.1 - BUILD 1

**ProtocolLib version**:  4.2.0

**Plugin list**: Custom plugins

### Special environment information
**ViaVersion version**: 1.1.1

**ProtocolSupport version**: NO

**ViaBackwards version**: NO

**BungeeCord plugins**: LATEST

**Comment by ItzSomebody** [comment]
Can you include more of the log?

There is usually a "Caused by...." right after that.

**Comment by craftrise** [comment]
@ItzSomebody 
I think the issue is related to the AAC API, I will wait a few days if I do not have a problem, I will close these "git issue".

**Comment by ItzSomebody** [comment]
Doesn't look like a problem with the API.

**Comment by CeIebrimbor** [comment]
of #904 and #907
