### ISSUE TITLE
AAC 3.1.1-b1 Stacktrace

### ISSUE THREAD

**Issue by Minemaniak** [konsolas/AAC-Issues#913]
https://scr.hu/GZP2L2 , it doesn't need explanation I think?

### Core information
**Server version**: Spigot 1.8.8

**AAC version**: 3.3.1-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: I can include if it does matter in this issue (or better, I'll send it in DM)

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: I can include if it does matter in this issue (or better, I'll send it in DM)

**Comment by ItzSomebody** [comment]
Try using the recommend ProtocolLib

**Comment by CeIebrimbor** [comment]
ProtocolLib 4.2.0 is recommended for 1.8.8 servers currently. Please request a reopen if you have the same issue after downgrading.

_Note: AAC will directly recommend in a version update notes to move to ProtocolLib 4.4.x (or 4.5) in the future if and when it becomes compatible. Until then, 4.2.0 for 1.8-1.9 servers and 4.3.0 for 1.10-1.12 servers._
