### ISSUE TITLE
FightSpeed detection false positive

### ISSUE THREAD

**Issue by LinsaFTW** [konsolas/AAC-Issues#916]
Right clicking and left clicking at the same time with rod or sword shows a really high amount of cps in verbose like 26 - 50cps

**Comment by CeIebrimbor** [comment]
Could we see the detection logs for this activity?

**Comment by Slimerblue22** [comment]
I can confirm this, it freaks out when right and left clicking at the same time

**Comment by CeIebrimbor** [comment]
Fair enough. 2 reports of something so easy to reproduce is good enough. Logs would still be appreciated.

**Comment by LinsaFTW** [comment]
Im sorry if i cant provide anything , im really busy rn maybe other day i can give all the proof i have for every false positive

**Comment by konsolas** [comment]
Going to be fixed by a default config update.
