### ISSUE TITLE
Fly check not working properly when ceiling near the player => Highjump [up to ~20 blocks]

### ISSUE THREAD

**Issue by Nvaros** [konsolas/AAC-Issues#918]
The fly check doesn't detect highjump (vanilla) up to a certain motion if there is a block one till three blocks above the player's head. Moreover, if you jump and break the block above you (it needs to be 3 blocks above you for that though) just before you hit its ceiling, you keep going up without getting flagged.

It looks like this:

B B
X B
X B
P B
P B       (p = player; b = blocks, x = air) [You don't need a wall for this]

With this "trick", you can jump up to 20 blocks high without flags (if you time it right) 
This may sound hard to do, but it's actually pretty easy with blocks that break instantly (Slime block, TNT)

Doesn't work for ladders, vines and any other semi blocks you can pass through.

**Comment by Janmm14** [comment]
Could you please retry with latest AAC and fly `min_vl: 10`.

**Comment by GeoGamerLP** [comment]
I did by retesting on Gomme today, and it's still not fixed. Their min_vl is 12, but that doesn't make a difference as I could do this twice a row without flags.
