### ISSUE TITLE
Phase bug

### ISSUE THREAD

**Issue by FrankHeijden** [konsolas/AAC-Issues#919]
### Core information
**Server version**: CraftBukkit version git-Spigot-65e8124-79e55b6 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**AAC version**: 3.3.1-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: N/A

### Special environment information
**ViaVersion version**: 1.2.1-SNAPSHOT

**ProtocolSupport version**: N/A

**ViaBackwards version**: 2.2.0

**BungeeCord plugins**: N/A

### Configuration
Cel's config

### Description
Some sort of glitchy block-removal when mining the block straight underbeneath you.
VL log: https://pastebin.com/YmKdcJkw

**Comment by CeIebrimbor** [comment]
@FrankHeijden I saw a very similar issue closed (mining down). Is this issue resolved in 3.3.4 by chance?

**Comment by FrankHeijden** [comment]
No, still occurring.

**Comment by Janmm14** [comment]
Can you create a debug log with AAC 3.3.4 please? Toggle debug logging with /aacdebug, make sure to keep the debug logging time short. Be the only player on your server while doing so. Please use https://gist.github.com to upload the debug log.

**Comment by FrankHeijden** [comment]
https://gist.github.com/FrankHeijden/80e3194c9dc6c973330673fac3f48a95

Don't mind the Ping of 700ms, its a spigot bugg. It is the same as a ping of 23ms. I do not know what's causing it, but its not relevant for this issue as it happened before this spigot bugg too.

video: https://www.frankheijden.net/s/8kZMxyB0pVQQztJ
