### ISSUE TITLE
Flux b11 aimassist bypass

### ISSUE THREAD

**Issue by Games4k** [konsolas/AAC-Issues#920]
Flux b11 AimAssist is bypassing AAC Heuristic, and its pretty op! Even on the max speed it's bypassing aac, and it gives hacker good adventage over other players, but I dont think its that much hard to block it :/

It looks so suspicious and it will be easy for @konsolas to block it

TESTED ON THE LATEST AAC WITH THE LATEST **STABLE** **VERSION** OF PROTOCOLLIB ON VERSION 1.8.x-1.12.1 tacospigot (primary 1.8 with the latest viaversion) and on confidence 62

**Comment by ItzSomebody** [comment]
Thumbs up, recommended version of ProtocolLib is 4.2.0 for 1.8.8.


If you look through logs, are any VLs for Heurisitics?

**Comment by Janmm14** [comment]
> LATEST PUPLIC VERSION OF PROTOCOLLIB
>
> *by @Games4k*

latest development build or latest stable protocollib (4.3.0)?

I can tell you the latest development build will likely produce errors in the console which likely also affect  nearly all aac detections.

**Comment by Games4k** [comment]
Nope, I'm using the latest stable build

**Comment by Games4k** [comment]
@ItzSomebody I dont think ots a big problem, because this bypass is working on my factions server too, which is 1.12.1

**Comment by iConfueZ** [comment]
Just tested it out, I seem to flag P/90 (confidence 88.9) within 30 seconds (with Flux b11 AimAssist)

**Comment by konsolas** [comment]
Not sure if this issue is valid or not. Can anyone provide more information?

**Comment by Games4k** [comment]
Here is the video. When this post comes out, video will probably still be uploading
It might take some time because I recorded it with fraps :/

https://youtu.be/l1ht7ZOj0Mw

**Comment by CeIebrimbor** [comment]
Video still not available @Games4k

**Comment by Janmm14** [comment]
@Games4k The video is not avaible.

**Comment by CeIebrimbor** [comment]
Closing until a working video is posted and @Games4k can provide evidence he is using the recommended build of ProtocolLib (4.2.0) for 1.8.8 and not the "latest stable build".
