### ISSUE TITLE
Opening chests through walls using freecam + freecam cregging

### ISSUE THREAD

**Issue by Matthew777k** [konsolas/AAC-Issues#921]
Players are able to use a cheat called 'freecam' and open up chests through walls. They're also able to place creeper eggs through walls and ignite them using the method below I'll be showing. Is it possible for a fix for this to be released? NCP+ has it patched somehow.

https://youtu.be/cBtJTgX-Ap4

https://youtu.be/lHRteIhzqbY

**Comment by w-o-a-h** [comment]
this can be fixed in aac by changing a value in the config forgot what one tho

**Comment by Janmm14** [comment]
in the interact section: 
```yaml
    cancel_vl_interact: 0
    cancel_vl_place: 0
```
Please be aware this might cancel some legit block placements.

**Comment by konsolas** [comment]
See the available configuration options above.
