### ISSUE TITLE
Flight Bypass (Only with Elytra on)

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#924]
**Video: https://www.youtube.com/watch?v=hlkCfFkEp84**

### Core information
**Server version**: 
![image](https://user-images.githubusercontent.com/29098956/30032074-e2c0fc10-9161-11e7-950c-f52625c9266f.png)

**AAC version**: 
![image](https://user-images.githubusercontent.com/29098956/30032087-f2f804fc-9161-11e7-9695-1ceffebc3376.png)

**ProtocolLib version**: 
![image](https://user-images.githubusercontent.com/29098956/30032102-02eca2b4-9162-11e7-84f0-1524c568c78d.png)

**Plugin list**: 
![image](https://user-images.githubusercontent.com/29098956/30032129-204f2868-9162-11e7-91d9-e6f743d3e536.png)

### Special environment information
**ViaVersion version**: 1.2.0

**ProtocolSupport version**: **None**

**ViaBackwards version**: **None**

**BungeeCord plugins**: **On request**

### Configuration
fly:
    Teleport the player down if detected?
   teleport: false

**Comment by Pluginsel** [comment]
This is very important bypass.
@konsolas can you fix for 3.3.5 version?
