### ISSUE TITLE
AAC is still blocking move packets aka can't see the client accepting the teleport

### ISSUE THREAD

**Issue by Xayanix** [konsolas/AAC-Issues#929]
Edit by @celebrimbor:
**`tp_accept_threshold: 0.8`** _(or higher) in the Move check fixes the teleport desync. [As reported](https://github.com/konsolas/AAC-Issues/issues/929#issuecomment-327449560)._

https://github.com/konsolas/AAC-Issues/issues/879
Still not fixed.

Video: https://www.youtube.com/watch?v=dkeQ2TS064M&feature=youtu.be

Rest of information are the same as in issue #879 

### Core information

Server version: PaperSpigot 1.12.1

AAC version: 3.3.2-b2

ProtocolLib version: 4.3.0

Plugin list: https://scr.hu/d5rMdy

Special environment information

ViaVersion version: nope

ProtocolSupport version: b114

ViaBackwards version: nope

BungeeCord plugins: SkinsRestorer

### Configuration

Default, newest one.

**Comment by CeIebrimbor** [comment]
I edited the post based on the other issue. Can you confirm you are using 3.3.2-b2 and not 3.2.2-b2 (as you originally posted). Also, are you using 1.12 or 1.12.1? Spigot? PaperSpigot?

**Comment by Xayanix** [comment]
Im using newest AAC (downloaded it about 1 hour ago) with PaperSpigot 1.12.1.

**Comment by CeIebrimbor** [comment]
@Xayanix 
In your move settings, can you try
`tp_accept_threshold: 0.005`
and report back?

**Comment by Xayanix** [comment]
I will do it tommorow.

**Comment by wulfwuud** [comment]
@CeIebrimbor 
Can confirm that problem persists with
`tp_accept_threshold: 0.005`
`tp_accept_threshold: 0.010`
using last aac \ last paperspigot & protocol support

**Comment by Janmm14** [comment]
Better try to put the tp_accept_threshold down to values like `0.1`, `0.2`, `0.3`, `0.4`, `0.5`.

**Comment by Xayanix** [comment]
Tested it and value of 0.8 is OK.
Everything below causes players to glitch.

**Comment by CeIebrimbor** [comment]
> Tested it and value of 0.8 is OK.
> Everything below causes players to glitch.

Good info. Keeping that value should not be harmful. This will get passed up to see if maybe some internal changes need to be made. Thanks for sticking through all of this.

**Comment by konsolas** [comment]
Fixable with configuration option. Defaults are not going to change.

**Comment by Janmm14** [comment]
Liekly finally fixed while fixing #1001.
