### ISSUE TITLE
Sprinting Backwards on AAC Test Server

### ISSUE THREAD

**Issue by Z609** [konsolas/AAC-Issues#93]
AAC version: 3.0.0 (test server)
ProtocolLib version: 4.1.0
Full plugin list: PermissionsEx, TestServerGui, Citizens, WorldEdit, Essentials, EssentialsChat, ProtocolLib, WorldGuard, AAC
Explanation of how to reproduce the issue: Use wolfram 1.10 and enable sprint. Sprint backwards.

Video demonstration: https://youtu.be/tjQPXUK0WYw

**Comment by Photon-GitHub** [comment]
Omnidirectional sprints will probably not be patched.

**Comment by konsolas** [comment]
Will close anyway.

**Comment by Photon-GitHub** [comment]
Omnidirectional Sprints are detected by AACAdditionPro.
