### ISSUE TITLE
ExtraElytra Bypass/Not Blocking

### ISSUE THREAD

**Issue by aquatrooper** [konsolas/AAC-Issues#931]
### Issue description
Hacked Client: Aristois
Video: https://www.youtube.com/watch?v=jwYf5sjk9fg

### Core information
**Server version**:
![screenshot_3](https://user-images.githubusercontent.com/31685930/30100178-40601df6-92e8-11e7-9c50-f83adbbb1149.png)

**AAC version**:
![screenshot_1](https://user-images.githubusercontent.com/31685930/30100144-1d60d00c-92e8-11e7-964c-f2473819d2a6.png)

**ProtocolLib version**:
![screenshot_2](https://user-images.githubusercontent.com/31685930/30100185-46e22408-92e8-11e7-9a39-93f2a2e4fdd5.png)

**Plugin list**:
![screenshot_4](https://user-images.githubusercontent.com/31685930/30100187-49daa81a-92e8-11e7-9d4b-0abd2bd0db10.png)

### Configuration
Celebrimbor's Optimized Config

**Comment by CeIebrimbor** [comment]
Also see #831
