### ISSUE TITLE
Sprint Jump Start/Stop on Ice = Speed

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#933]
### Issue description
Sprint jump takeoffs on ice semi-consistently flag for Speed. Enough to setback frequently and get in the 100+ VL if aggressively abused. No speed potions needed.

Video: https://www.youtube.com/watch?v=gL9r2U6WVmM&feature=youtu.be

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.2-b2

**ProtocolLib version**: 4.3.0

**Plugin list**: Vanilla movements

### Special environment information
Just Spigot 1.8.8

### Configuration
Higher `min_vl` and lower `reduce_delay` which don't do much, as you can see the VL skyrockets to the min_vl setting (60 in video).

**Comment by Slimerblue22** [comment]
Are you kidding me?!?!? I legit just made a video on this and was about to report it lol.

**Comment by w-o-a-h** [comment]
jumping on frosted ice from the frostwalker enchant that was added in 1.9 just gets you stuck

**Comment by CeIebrimbor** [comment]
Update: This will require a significant debugging session (estimated 1 hour) and is high priority, but the 3.3.4 release needed to happen without wrapping too much time into various bugs in order to be released sooner rather than later.

Updating to "Critical"

**Comment by Janmm14** [comment]
Another video from 1051: https://streamable.com/uze25

**Comment by Minemaniak** [comment]
Issue not fixed, please reopen.
Just tested on a LAN server (spigot 1.8.8, plugin list: https://i.imgur.com/maw2dOU.png), with a clear 1.8.9 client. Also happens without AACAP. Not computer or network related issue (LAN server + good enough computer). Using latest Celebrimbors config.

If you stup for about... 0.5 second or something like this, after starting again you get instantly flagged for speed to the point where AAC setbacks you.

**Comment by CeIebrimbor** [comment]
> Issue not fixed, please reopen.
> Just tested on a LAN server (spigot 1.8.8, plugin list: https://i.imgur.com/maw2dOU.png), with a clear 1.8.9 client. Also happens without AACAP. Not computer or network related issue (LAN server + good enough computer). Using latest Celebrimbors config.
> 
> If you stup for about... 0.5 second or something like this, after starting again you get instantly flagged for speed to the point where AAC setbacks you.

Could you provide a debug log and confirm you are running the latest AAC (released today)?

**Comment by Minemaniak** [comment]
Debug log from the issue: https://pastebin.com/Y1jPe14d
AAC 3.3.7, without -b1, does it really matter?

**Comment by CeIebrimbor** [comment]
> AAC 3.3.7, without -b1, does it really matter?

No.

**Comment by Minemaniak** [comment]
Still not fixed, seems to be a little bit better, but definitely not fixed. Server info same, AAC 3.3.8, Cel's config. Debug: https://pastebin.com/hzjqmiTt

**Comment by Minemaniak** [comment]
Nice, this time it really seems to be fixed :D
