### ISSUE TITLE
No slowdown bypasses naturally when a block is near above your head

### ISSUE THREAD

**Issue by Slimerblue22** [konsolas/AAC-Issues#934]
https://youtu.be/bsKICy8dtiE
### Core information
**Server version**: ![image](https://user-images.githubusercontent.com/29098956/30032074-e2c0fc10-9161-11e7-950c-f52625c9266f.png)

**AAC version**: 
![image](https://user-images.githubusercontent.com/29098956/30140437-8d37a4fa-9342-11e7-92bf-3675c7042c35.png)

**ProtocolLib version**: 
![image](https://user-images.githubusercontent.com/29098956/30032102-02eca2b4-9162-11e7-84f0-1524c568c78d.png)

**Plugin list**: ![image](https://user-images.githubusercontent.com/29098956/30032129-204f2868-9162-11e7-91d9-e6f743d3e536.png)

### Special environment information
**ViaVersion version**: **1.2.0**

**ProtocolSupport version**: **None**

**ViaBackwards version**: **None**

**BungeeCord plugins**: **On request**

### Configuration
Speed
```yaml
 thresholds:
      60: "aacmessage {player} It looks like you might be glitching, if you are elytra-hopping you may be kicked"
      150: "aacstaffnotify {player} is suspected for Speed hacking (ping = {ping}, tps = {tps})"
      350: "aacstaffnotify {player} is more than likely speed hacking"
      450: "aackick {player} Moved too quickly"
```
Fly
```
 thresholds:
      120: "aacstaffnotify {player} is suspected for Fly (ping = {ping}, tps = {tps})"
      210: "aacstaffnotify {player} is suspected for Fly #2 (ping = {ping}, tps = {tps}"
      300: "aackick {player} Moved unexpectedly"
```

**Comment by Janmm14** [comment]
The thresholds is the stuff we do not need to know, but all the other settings...

**Comment by CeIebrimbor** [comment]
Also see #818

**Comment by Janmm14** [comment]
This seems to be a conceptual issue, no specific bypass.

**Comment by Janmm14** [comment]
Why close?

**Comment by Slimerblue22** [comment]
Its been fixed hasn't it? @Janmm14
