### ISSUE TITLE
Horsefly Bypass Aristois

### ISSUE THREAD

**Issue by cfr** [konsolas/AAC-Issues#935]
### Issue description
~~Fly hack found here: https://youtu.be/k2oOG6ubBQA?t=2m53s~~
Available for download here: https://yadi.sk/d/BSI6aFcb3Lfdo5

**Update regarding horse bypass after investigation:**
Though, Aristois_1.12.1 still works on the horse: [debug log](https://hastebin.com/ozopivekaw.diff), [video](https://youtu.be/orluhmfCz14).

### Core information
**Server version**: CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**AAC version**: 3.3.2

**ProtocolLib version**: 4.3.0

**Plugin list**: LuckPerms, WorldEdit, PlaceholderAPI, ClearLag, BetterChairs, FastCraftPlus, WorldBorder, Multiverse-Core, WorldGuard, VoidGenerator, Multiverse-Inventories, TradePlus, Realistic_World, ViaVersion, Multiverse-Portals, Vault, ~~TreysDoubleJump~~, Essentials, ProtocolLib, AAC, Citizens, ConditionalCommands, ShopChest, CommandNPC, Multiverse-NetherPortals, EssentialsSpawn, PvPManager, VentureChat, AACAdditionPro, HolographicDisplays, dtlTraders, HolographicExtension

### Special environment information
**ViaVersion version**: 1.2.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**:
BungeeAdminTools-1.5.2-premium.jar
BungeeRcon-2.1.jar
BungeeTabListPlus-2.8.1.jar
commandsdispatcher-2.4.12.jar
LuckPerms-Bungee-3.3.14.jar
socket4mc-2.1.3.jar
VentureChat.jar
Yamler-Bungee-2.4.0-SNAPSHOT.jar

### Configuration
I use Celebrimbor's config for AAC and AACAdditionPro.

**Comment by cfr** [comment]
This fly hack also works https://yadi.sk/d/xdrFDY8W3MZdLV

**Comment by Janmm14** [comment]
Would be probably a good idea to link a video where someone is actually flying.

**Comment by cfr** [comment]
Players with this hacks can fly upwards, downwards and any other directions. [Aristois_1.12.1 hack video](https://www.youtube.com/watch?v=m_TIX28Go-8) and [Matrix 1.12 hack video](https://youtu.be/3SmP_eY7EEo).

**Comment by CeIebrimbor** [comment]
It looks like getting past the original setback is all it takes. The min_vl here is 60.

**Comment by Janmm14** [comment]
Something with the setup is not working.

I tested locally with AAC 3.3.2 and Spigot 1.12 on `min_vl:28` and `min_vl: 60` and could not reproduce.

**Comment by Janmm14** [comment]
@cfr Could you provide a `/aacdebug` log?
1. Type `/aacdebug <playername>`to start your debug log.
2. Then enable fly and start flying around.
3. Then type `/aacdebug` (without any parameter) to stop debugging and save the debug log.
4. Put your debug log on gist.github.com or pastebin.com

**Comment by cfr** [comment]
I have removed few plugins (ClearLag, FastCraftPlus, Realistic_World, ViaVersion, TreysDoubleJump, dtlTraders, HolographicExtension) and now it kicks players... Thanks!

**Comment by CeIebrimbor** [comment]
> TreysDoubleJump

Hmmm... xD

**Comment by cfr** [comment]
Though, Aristois_1.12.1 still works on the horse [log](https://gist.github.com/cfr/246a03726f37889a821620f76f31e652). Matrix 1.12 now does not works at all.

**Comment by Janmm14** [comment]
I did not tested horsefly. Additionally it looks like the vl for horsefly are a bit too low in your debug log.

**Comment by CeIebrimbor** [comment]
> vehiclefly is at a low priority for him.

Well, everything 1.9+ is low priority.
