### ISSUE TITLE
Item Frame exception NPE@U.b:61

### ISSUE THREAD

**Issue by FrankHeijden** [konsolas/AAC-Issues#936]
### Issue description
Hit an item frame xD
https://pastebin.com/Dfycc9Zu

### Core information
**Server version**: CraftBukkit version git-Spigot-65e8124-79e55b6 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**AAC version**: 3.3.2-b2

**ProtocolLib version**: 4.3.0

**Plugin list**: [x]

### Special environment information
**ViaVersion version**: N/A

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

**Comment by Janmm14** [comment]
Use 3.3.2 (b0) until stuff is fixed please.

**Comment by FrankHeijden** [comment]
same error, different mob:
https://pastebin.com/zsqHbHW1
