### ISSUE TITLE
NPE@?:? (EntityDamageByEntityEvent) iDusguise

### ISSUE THREAD

**Issue by MatheweB** [konsolas/AAC-Issues#938]
A player claimed to see a burning Ocelot in lava, and then this error occurred:

https://hastebin.com/okavuhuyid.vbs

### Core information
**Server version**: Latest Spigot 1.12.1

**AAC version**: Latest

**ProtocolLib version**: Recommended Version for Latest AAC

**Plugin list**: AACAdditionPro, Worldguard

**Comment by CeIebrimbor** [comment]
idisguise? Might be at fault here (and why the "plugin list" is relevant)

Also, please edit the report to show _actual_ versions of AAC and ProtocolLib. "Recommended" and "Latest" might mean the incorrect version when it comes to compatibility and can become very confusing if this is not directly addressed in the very next update.

The actual recommended version of ProtocolLib for 1.12.1 is 4.3.0. Even though the ProtocolLib dev lists a different version compatibility recommendation.

**Comment by CeIebrimbor** [comment]
Also note:
A downgrade to AAC 3.3.2 (b0) should temporarily fix this error.

**Comment by CeIebrimbor** [comment]
This is linked to iDisguise (the developer doesn't want to do anything about it).

**Comment by Janmm14** [comment]
Exception is truncated.
Start your server with the `-XX:- OmitStackTraceInFastThrow` jvm option (add it before the -jar argument) or search for this error from the start of the log file at last server start.

**Comment by konsolas** [comment]
No useful stacktrace in this one. Moving to #944
