### ISSUE TITLE
Killaura heuristics false positive

### ISSUE THREAD

**Issue by iConfueZ** [konsolas/AAC-Issues#941]
### Issue description
Title is pretty self explanatory. 

Video: https://www.youtube.com/watch?v=xatHMr901o8&feature=youtu.be

### Core information
AAC's test-server

**Comment by JuliCarles** [comment]
It's not a Heuristics false positive but a KillAura normal false positive.

**Comment by iConfueZ** [comment]
> It's not a Heuristics false positive but a KillAura normal false positive.
It is - https://youtu.be/xatHMr901o8?t=50s

**Comment by JuliCarles** [comment]
Ouch, I was looking at the last seconds, seems to be both of them.

**Comment by Janmm14** [comment]
I guess those false positives are less likely to occurr in pvp situations.

**Comment by konsolas** [comment]
Need to know what the pattern is, at the very least.

**Comment by konsolas** [comment]
Heuristics are getting modifications in the next release.
