### ISSUE TITLE
Two AAC exceptions.

### ISSUE THREAD

**Issue by JuliCarles** [konsolas/AAC-Issues#942]
### Issue description
Found two exceptions being randomly appearing in my server.
~~1) http://www.youscreenshot.com/5723fa8a0527c58de9616db518f5bb9e~~ See #926
2) http://www.youscreenshot.com/a333c9d54ccd64802e5bce3f71c14c6e

Those are the full errors.

### Core information
**Server version**: 1.8.8

**AAC version**: Latest (3.3.2-b2)

**ProtocolLib version**: 4.2.0

**Plugin list**: Ask if needed.

### Special environment information
**ViaVersion version**: Latest

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: Ask if needed.

### Configuration
Cel's config.
I guess configuration is not the thing here.

**Comment by CeIebrimbor** [comment]
1. #926 
2. Yet another Skyblock teleport sync issue?

**Comment by JuliCarles** [comment]
No, both errors were in our SkyWars server. Using SkyWarsX plugin by Wazup92.
