### ISSUE TITLE
CME@s.a:16, NPE@ci.onPacketRecieving:17 (ArmAnimation)

### ISSUE THREAD

**Issue by craftrise** [konsolas/AAC-Issues#944]
### Issue description

**Error 1:**  https://hastebin.com/pujabutexa.bash
**Error 2:**  https://hastebin.com/ekosocevet.bash
**Error 3:**  https://hastebin.com/uhuronazih.bash

### Core information
**Server version**: 1.8.8 PaperSpigot

**AAC version**: 3.3.2

**ProtocolLib version**: 4.2.0

**Plugin list**: CUSTOM

### Special environment information
**ViaVersion version**: LATEST

**ProtocolSupport version**: NO

**ViaBackwards version**: NO

**BungeeCord plugins**: CUSTOM

**Comment by CeIebrimbor** [comment]
Possibly 1-2 dupes of already reported errors, but I can't find all of them.
