### ISSUE TITLE
Elytra false kicks with high ping

### ISSUE THREAD

**Issue by FrankHeijden** [konsolas/AAC-Issues#947]
### Issue description
Player reaches very high violation levels when having a high ping + flying with elytra
https://pastebin.com/2YfsVmP0

### Core information
**Server version**: CraftBukkit version git-Spigot-da42974-876d22c (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**AAC version**: 3.3.2-b2

**ProtocolLib version**: 4.3.0

**Comment by Janmm14** [comment]
Do you think this is a ping-only issue?

**Comment by FrankHeijden** [comment]
yes, as i didnt notice it this bad with players without a high ping. There were some violations, but they never reached a kicking VL. e.g. the player in this log was kicked 3x bcs he had reached a very high VL level in a really short amount of time

**Comment by CeIebrimbor** [comment]
Confirmed. Any significant lag (300ms+) combined with rocket boosts and normal flight will get you to VL 30+ constantly and 1000+ if you are persistent (I've had a player get there twice). This critical detection bug only seemed to occur after the update that addressed Elytra flight (if was recent).

**Comment by Janmm14** [comment]
I guess the problem is that with some lag added, AAC can't precisely see when exactly the rocket boost was added - AAC needs to use the packet instead of the event or wait until the movement looks like the boost was used atter aac noticed the boost was used.

**Comment by CeIebrimbor** [comment]
Additionally: 
Seemingly more severe than initially anticipated. Ping >100ms (mostly 150+) is getting VL 300 regularly. I don't start lagging back until 1200 because of so many bugs, but I've seen laggy players (160ms) get to VL 800.

**Comment by CeIebrimbor** [comment]
Sucked into #773
