### ISSUE TITLE
Add support for exempting players from checks via metadata

### ISSUE THREAD

**Issue by RoboMWM** [konsolas/AAC-Issues#948]
NCP checks the player's metadata to see if any exemptions are set -  the keys it looks for are the same as the permission exemptions. Could you add support for this as well (or point me to the documentation that lists the metadata AAC looks for)?

You could also add `nocheat.exempt` if you want compatibility with plugins that already exempt players from NCP entirely as well.

**Comment by Janmm14** [comment]
One could simply create a plugin using AAC's API to add this functionality.

**Comment by RoboMWM** [comment]
Yes, but that requires adding AAC as a dependency, which I'd like to avoid.

**Comment by Janmm14** [comment]
A potential plugin providing that functionality would not require any maven presence, also see #950

**Comment by RoboMWM** [comment]
Still, if I want my plugin to be able to be built with maven, I'd have to include that jar in my repo unless it's hosted on a maven repo.

Either way, metadata is an easy and excellent option when it comes to small things like this.

**Comment by Janmm14** [comment]
@RoboMWM Here is your maven repo: https://repo.janmm14.de/artifactory/public/

**Comment by konsolas** [comment]
AAC can use permissions, which behave in a similar way to nocheat.exempt

Additionally, @Janmm14 has kindly provided an API jar if more fine-grained control is required.

**Comment by RoboMWM** [comment]
I really would not like to deal with permissions in my plugin, especially since I'm doing this temporarily. (I'm calling a fake event, so I'm adding and removing the exemption in the same tick.)

**Comment by Janmm14** [comment]
I don't see why AAC shozld natively support exempt strategies by other antichrat plugins, since other antichrat plugins will have other issues with stuff plugins are doing and therefore exemptions by thosr plugins should stay bound to the anticheat implementation.
Additionally AAC has more checks and more fine-grained checks for cheats than nocheatplus. Which ones should be exmept for exactly?
This means that this feature request is in my opinion out of AAC's scope.

**Comment by RoboMWM** [comment]
> I don't see why AAC should natively support exempt strategies of other anticheat plugins

If you're talking about me asking if `nocheat.exempt` should be supported, that was just a suggestion. The **primary request** was to check metadata just like permissions are for exemption strings.

> Additionally AAC has more checks and more fine-grained checks for cheats than nocheatplus. Which ones should be exempt for exactly?

Literally the same things supported in permissions. The check for metadata is exactly the same, API-wise, for checking permissions. (To contrast, it's not as easy to set a permission vs. setting metadata).
