### ISSUE TITLE
Killaura Issues

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#953]
### Hitbox:
[Video here](https://youtu.be/Sl-mr7H7pao)

_Reach:_ [(01:48-01:57, 02:07, 02:15 02:29, and more after that)](https://youtu.be/Sl-mr7H7pao) I feel that this move compensation STILL doesn't work. With default config, I am having issues with the hitbox check if I ever get in a combo. It happens much more often with a player that I'm fighting but my friends weren't on at the time of me recording this. (Made a separate thread about move compensation: #960) 

_Lenience:_ [(00:05, 00:12, 00:19, 00:27, 00:34, 01:02, 04:25)](https://youtu.be/Sl-mr7H7pao)

### Heuristics _(UNIMPORTANT)_:
Just a few issues with patterns 01, 02, 04, 06 and 09. Really unimportant and isn't a priority at all.

### Normal _(Extra)_ :
Killaura Normal is basically worst for pvping while you're legit. Because Normal spawns invisible mobs inside of the player, when you get someone in a combo, your sprint isn't stopped like it does normally because you are not actually hitting the player, but you are hitting the mobs. This can ruin combos and affect pvp on the server. Another issue with it is that since the Normal check spawns mobs that are a little bit outside of the player on each side, this can actually increase hitbox size and maybe even reach distance because they are spawned a bit too far out of the player. I know that can be fixed by changing the config, but it would be great to have it fixed with the default config. My recommendation that will fix the first issue with the sprint stopping is instead of spawning mobs inside of players, we should spawn players inside of players. 

_**EDIT**_
[Part 2 Video Here](https://youtu.be/U9ALImgs15I): With this video, and the way I am hitting the player, it looks like the Killaura Normal mobs are actually expanding the hitbox enough where I can look up and hit the other player. This is not really as important and would most likely be fixed with a Killaura Normal rework, but the one above might not.

### Core information
**Server version**: Latest PaperSpigot

**AAC version**: Latest

**ProtocolLib version**: 4.2.0

**Plugin list**: If Requested

### Configuration
Default Configuration

**Comment by Janmm14** [comment]
Sprint stop should work regardless of the entity hit being invisible or not. Additionally one could hold the sprint key and simply sprint on.

**Comment by Rerd** [comment]
When you hit a **player**, not a **mob or animal** while sprinting, your speed is actually multiplied by 0.6 for a certain amount of time, which doesn’t happen if you hit **mobs or animals**.

Killaura Normal hitbox expansion is much more than 0.05. Just from looking in the config of Normal, it seems to be about 0.11. I still stand with my original thought of spawning players inside of players and also by default making the max diff to be 0.02 or something close.

**Comment by Rerd** [comment]
[Video here](https://youtu.be/kEobC_LELzA)

Here shows the sprint multiplying that I said 3 hours ago. From 00:00-00:20, you can see that the sprint is stopped (multiplied by 0.6) every second because of the Killaura Normal check lasting for 20 ticks (1 second). If you look from 00:30-00:49, you can see that every single hit I get on the player the sprint is stopped (multiplied by 0.6). This is the main annoyance that I have of Killaura Normal (other than hitbox expanding).

**Comment by Janmm14** [comment]
Sprint stop does not equal to xz motion multiplied by 0.6

**Comment by Rerd** [comment]
[This is what happens when you hit a player.](https://gyazo.com/ad672a962b7202745e39308d66a094cc)
This clearly is not happening in the video I made comparing with Killaura Normal and without while it was enabled. When you hit a mob, I think only the setSprint is set to false (don’t quote me), but I know for sure the same thing isn’t happening as it is when you hit a player. This is effecting pvp in a few different ways like Knockback, Combos and **possibly** hit detection could be different. Knockback is affected because let’s say you are getting knocked backwards and while you are you hit a **player**, this will actually make you take **less knockback** because your XZ motion is being multiplied by 0.6. This is different with the current Killaura Normal check because if you are in a combo and you get hit while the Killaura Normal check is currently active, you wont take less knockback because you are hitting a **mob**. Combos are affected because some people like me abuse the XZ motion multiplication to slow down while in a combo to keep a good distance away from the player that you are comboing to make sure they can’t hit you. This isn’t possible while hitting a mob which is forcing you to W tap to stay away from the player, but that also makes the other player take **more knockback** which some players don’t do.

**Comment by Janmm14** [comment]
That code is executed everytime a player hits an enemy and

* the target can recieve damage at all and is not invulnerable
* your attack damage is higher than 0
* you are sprinting or the item you hold has a knockback enchantment

-> it should also works against mobs

(The `setSprint(false)` is pretty much useless when people use the sprint key instead of double tapping.)

**Comment by Rerd** [comment]
Okay, I will record another video showing the difference between butterfly clicking a player and a mob.

**Comment by Janmm14** [comment]
Why you don't add a simple debug output to that code part to test it?

**Comment by Rerd** [comment]
Not sure what that means. I don't know much about debugging. I found that code that I showed in a video that Tenebrous made about Knockback and how higher CPS can make you take less Knockback.

[Video here](https://youtu.be/R6_mb5Q_WHk)
Okay, if you look very closely at the screen you can see that while I am butterfly clicking the sheep (same goes for zombies, creepers, etc.), my FOV is not changing rapidly, but when I am butterfly clicking the player, the FOV is changing on every single hit that I land on the player.

**Comment by Rerd** [comment]
Okay, the Killaura Normal issue is actually a serious problem that is really affecting pvp. Not only is the multiplication of the XZ motion not happening because of hitting mobs and not players, but the hitboxes of the mobs are way too big and the entities are offset too far off of the opponent.

[Video Here](https://youtu.be/qsCDfEdLZ-U)

From [00:00 to 00:45](https://youtu.be/qsCDfEdLZ-U), I am testing hitboxes with Killaura Normal disabled. From [00:50 to 01:40](https://youtu.be/qsCDfEdLZ-U) I am testing hitboxes with Killaura Normal enabled. Now, from [01:40 to 02:40](https://youtu.be/qsCDfEdLZ-U) shows mostly how broken this check is. Both of the clients do not have any sort of reach or hitbox modifications enabled, yet the one with the Normal check **currently active** (mobs inside opponent) can hit **further** than the one without it active. Having this happen can basically increase the reach of players when they are in a combo, making it even harder for the opponent to get out of the combo. Another problem with this could be Killaura Hitbox false positives because they are hitting further than usual. From [02:50 to 03:40](https://youtu.be/qsCDfEdLZ-U) I am showing the  hitboxes of the invisible mobs inside of the opponent. This is just more proof that Killaura Normal really needs a complete rework.

**Comment by konsolas** [comment]
The sprinting/blocking seems to be a fundamental issue with the the idea behind the killaura check, and doesn't seem fixable without huge modifications - this is unlikely to be completed in the near future. 

The heuristics mentioned will be modified for the next release to prevent false positives.

Will keep further discussion on hitbox at #960

**Comment by Rerd** [comment]
Do you have an estimate on when it will be changed?

**Comment by SnakeDaoust1232** [comment]
Yeah ive had killaura disabled since AAC3.0 came out because of the pvp issues.

**Comment by Janmm14** [comment]
I think this issue might get closed as "wontfix" soon.

**Comment by Minemaniak** [comment]
Konsolas said it won't be changed in the near future, not that it won't be changed at all, so why close?

**Comment by Rerd** [comment]
Merging with #1201.
