### ISSUE TITLE
Fly FP in water with tick damage

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#955]
This also does happen with level 1, 3 and over of wither or poison.

[Video Here](https://youtu.be/DnuGTLGfLLo)

### Core information
**Server version**: PaperSpigot Latest

**AAC version**: Latest

**ProtocolLib version**: 4.2.0

**Plugin list**: If Requested

### Configuration
Default Configuration

**Comment by CeIebrimbor** [comment]
Noticed with fire as well, though not reproduced 100% of attempts.

**Comment by Slimerblue22** [comment]
Seems like any sort of ticking damage
