### ISSUE TITLE
Phase works very well (client: Exeterb13)

### ISSUE THREAD

**Issue by Xayanix** [konsolas/AAC-Issues#956]
### Core information
**Server version**: 1.8.8

**AAC version**: newest

**ProtocolLib version**: valid for 1.8.8

**Plugin list**: i will post it if necessary

### Special environment information
**ViaVersion version**: newest

Video: https://screenhunters.com/d5ALpy
Contact me if need more details.

**Comment by GeoGamerLP** [comment]
Which phase mode? Do you just have to go straight or do you also have to jump/sneak/whatever? Because I can't recreate it.

**Comment by Xayanix** [comment]
Go straight like on movie.

**Comment by GeoGamerLP** [comment]
> Go straight like on movie.

Which phase mode did you use? Or didn't you change it?

**Comment by CeIebrimbor** [comment]
I think it's a side effect of the recent attempts to fix setback issues. I noticed players in a protected/claimed area that were spam opening a door while moving forward were getting setback 1-4 times, but then they pass through the door as if the setback failed or assumed a safe location was past the door.

I want to assume it's only a bypass for a single block thickness?

**Comment by Xayanix** [comment]
CeIebrimbor i will try to make a lot more detailed issue report, but i don't have time now.
I can phase even for 10 blocks (just very rarely got kicked for velocity).

**Comment by Minemaniak** [comment]
Xayanix what is your tp_accept_threshold in Move config? If it's something big (not 0.001), then when server teleports client he can teleport not to that exact position but this value off from the position, so he can ignore some teleports or phase to blocks.

**Comment by Xayanix** [comment]
6.5.

**Comment by Minemaniak** [comment]
This is probably the reason. When you teleport someone now, he can teleport not to the exact position, but anywhere in radius 6.5, so cheat client is probably easily able to phase trough anything. Try with tp_accept_threshhold set to 0.001

**Comment by konsolas** [comment]
This is due to the config change.
