### ISSUE TITLE
AAC is pretty laggy with ~250 players

### ISSUE THREAD

**Issue by Xayanix** [konsolas/AAC-Issues#957]
Timings: https://timings.aikar.co/?id=ab998492b9354cb9a789dce9f5a34d75
AAC: 3.3.2-b2
MC: 1.8.8

**Comment by SnakeDaoust1232** [comment]
Make sure you aren't using tacospigot. Refer to: https://github.com/konsolas/AAC-Issues/issues/795

**Comment by Xayanix** [comment]
PaperSpigot 1.8.8

**Comment by CeIebrimbor** [comment]
I have had many reports of the more recent AAC version being 30-50% more heavy than 3.2.x versions.

**Comment by konsolas** [comment]
That task just runs all of the movement checks. Not much can be done in general about the performance since AAC needs to check the actions of every player on the server.
