### ISSUE TITLE
Speed FPs

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#958]
[Video Here](https://youtu.be/qeXWADXRWm0)

Kicks more often when switching between two items that slow you down. Shifting fast can kick often but it didn't work the time I recorded it. Rapidly right clicking on an item that slows you can also kick sometimes.

### Core information
**Server version**: Latest PaperSpigot

**AAC version**: Latest

**ProtocolLib version**: 4.2.0

**Plugin list**: If Requested

### Configuration
Default Configuration

**Comment by CeIebrimbor** [comment]
#620
