### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to AAC v3.3.2

### ISSUE THREAD

**Issue by andrewkm** [konsolas/AAC-Issues#959]
### Issue description

https://pastebin.com/raw/EiLXXSnq

### Core information
**Server version**: 1.12.1 - Spigot Build 1399

**AAC version**: 3.3.2|b2
**AAC config**: 3.3.2|2-Default-Celebrimbor

**ProtocolLib version**: 4.3.0 Build 373

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by CeIebrimbor** [comment]
#938
