### ISSUE TITLE
Trap doors

### ISSUE THREAD

**Issue by Rqcco** [konsolas/AAC-Issues#96]
Trap doors seem to be really glitchy. If you open a trap door that is on the ground and shut it while your in it, it will flag as phase. https://www.youtube.com/watch?v=j_k5czZWGK4. Also, another bug would be if you jump into them from 2 blocks above https://www.youtube.com/watch?v=GyGoAOlWZlE

**Comment by Janmm14** [comment]
To get out, you can jump so you land above, but you can't walk out.

**Comment by Janmm14** [comment]
If you have it like this you're also bugging in them and don't get out:
![](http://i.epvpimg.com/QMwYg.png)

**Comment by konsolas** [comment]
Fixed.
