### ISSUE TITLE
Hitbox's Reach Move Compensation still broken

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#960]
### Issue description
[Video Here](https://youtu.be/zXELNJYRY-Y)

I was using the default config with the move compensation at 100.0. I'm also guessing that the third number being added on the verbose for Hitbox is the move compensation which never goes over 0.

**EDIT**
[Video while player was sprinting](https://youtu.be/N0Xl4WpEd0w)

### Core information
**Server version**: Latest PaperSpigot (Also happens on Spigot)

**AAC version**: Latest

**ProtocolLib version**: 4.2.0

**Plugin list**: If Requested

### Configuration
Default Config with Move Compensation set to 100.0.

**Comment by CeIebrimbor** [comment]
Wrong video? There is nothing in the video that relates to the title.

**Comment by Rerd** [comment]
Thanks for the heads up. One sec.

**Comment by Rerd** [comment]
Added correct video. In the video there, the other player wasn't sprinting but I just tested with sprinting and it still says that there is no move comp.
