### ISSUE TITLE
Enderpearl bug

### ISSUE THREAD

**Issue by Pikuuu** [konsolas/AAC-Issues#961]
AAC version: Latest
ProtocolLib:  4.2.1
Full plugin list Core, protocallib, bungeetablistplus, permissionex, world edit, world guard

When throwing an "enderpearl" into a deep hole, the player will bump and roll back. It will help you to migrate to "/ spawn"

**Comment by Janmm14** [comment]
Writing "latest" as version is not good as "latest" can change.

**Comment by Pikuuu** [comment]
AAC version: 3.3.2-b2
ProtocolLib: 4.2.1
Full plugin list Core, protocallib, bungeetablistplus, permissionex, world edit, world guard

**Comment by Pikuuu** [comment]
Video: http://www26.zippyshare.com/v/novnfsV6/file.html

**Comment by CeIebrimbor** [comment]
Stop posting the same bug over and over
https://github.com/konsolas/AAC-Issues/issues?utf8=✓&q=is%3Aissue%20author%3APikuuu%20
