### ISSUE TITLE
Mining down bug

### ISSUE THREAD

**Issue by FrankHeijden** [konsolas/AAC-Issues#963]
### Issue description
When you mine down with your bare hand or another tool on a dirt tower e.g. you really get a weird animation/buggy mine experience. some blocks even gets cancelled, and you will be teleported back on the block with a random yaw/pitch (position youre looking).

Some detections:
https://pastebin.com/UrmSnHfR

### Core information
**Server version**: CraftBukkit version git-Spigot-da42974-876d22c (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**AAC version**: 3.2.2-b2

**ProtocolLib version**: 4.3.0

**Comment by aquatrooper** [comment]
I'm getting this aswell, all the time.

**Comment by konsolas** [comment]
Going to move this over to #1000 because the issue number is cooler (and because there's a video).
