### ISSUE TITLE
AAC antiknockback false positive

### ISSUE THREAD

**Issue by Xayanix** [konsolas/AAC-Issues#965]
**Server version**: 1.12.1

**AAC version**: 3.3.2-b2

**ProtocolLib version**: newest

**Plugin list**: not neccessary

Video: https://www.youtube.com/watch?v=Glgom6n1F0w&feature=youtu.be

**Comment by Spazzinq** [comment]
I don't believe Antiknockback receives support due to it being legacy.

**Comment by konsolas** [comment]
no response from issue author, issue template ignored, no logs.
