### ISSUE TITLE
kon pleas read

### ISSUE THREAD

**Issue by TornadoClientDev** [konsolas/AAC-Issues#966]
Im a anticheat dev and im trying to bypass a glide bypass that i cant patch please help me the glide code is
mc.theplayer.motiony = -0.16;
i cant patch it and i need help
i work on my anticheat 24/7 my server ip is
stormanticheat.g-s.nu 
there is no fly bypass right now only this one thanks!

**Comment by konsolas** [comment]
This is an issue tracker for AAC.
