### ISSUE TITLE
Error: Cannot measure distance between worlds

### ISSUE THREAD

**Issue by alexmarkey** [konsolas/AAC-Issues#968]
### Issue description
Errors in console, not too sure what the result of this error is however - https://gist.github.com/alexmarkey/6e867b32d7674ab1ca4788f88988d2ba
~~https://gist.github.com/alexmarkey/aeea1dd436c5bb7c183445d68ddf137e~~

### Core information
**Server version**: PaperSpigot 1.8.9

**AAC version**: 3.3.2

**ProtocolLib version**: 4.3.0

**Plugin list**: 
VoteCommand, Companions, WorldEdit, InvClose, ItemFrameProtection, EnsureBlocks, MCCFreeze, Essentials, ChatLimiter, WorldBorder, BuycraftX, WorldReset, Multiverse-Core, WorldGuard, VPNGuard, LilyPad-Connect, WorldEditCrashFix, PermissionsEx, QuickNoColon, BroadcastColor, CapsGuard, FriendSystem, CustomHelp, ViaVersion, JoinAnnouncerMYSQL, HideStream, FastPot, DeadFrog, SendInfoLobbies, MCCAC, LilyPad-Portal, StopHub, LilyHub, GlobalAnnouncer, LilyAlert, ProtocolLib, TitleJoin, AAC, ClearCachepex, ConditionalCommands, Punishment, StaffMode, AACAdditionPro, HolographicDisplays, NPCCommand, DuelServer, CompanionTool, CosmeticSystem

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: N/A

### Configuration
Currently using Celebrimbor's optimized config.  Only modification we have made to it is changing the aackick command to our own custom kick command.

**Comment by Janmm14** [comment]
Second error is already in another issue.

**Comment by JuliCarles** [comment]
The second error was already reported by me in #942 and it was added by konsolas to the 3.3.3 milestone.
