### ISSUE TITLE
v3: Speed false positives when sprintjumping on beds

### ISSUE THREAD

**Issue by Janmm14** [konsolas/AAC-Issues#97]
Reported message:
up to 0.615 block/ticks instead of 0.424 block/ticks (up to vl 7/8), but I think its more an issue that it does not correctly recognize the height of a closed trapdoor.

Trapdoor height: 0.1875 blocks

The issue is only happening when trapdoors are closed and placed on the bottom of blocks.

Trapdoor block data logic: http://minecraft.gamepedia.com/Trapdoor#Data_values

Fly also reports moved unexpectedly -0.08 instead of -0.12 (vl: 2) when running down the way into the test center on the middle on the test server, but I think its the same issue internally.

Edit: Same issue when jumping on beds

**Comment by Janmm14** [comment]
Speed detection seems to be fixed for trapdoors.

**Comment by konsolas** [comment]
Fixed for beds too now.
