### ISSUE TITLE
[Suggestion] AutoBlock Check

### ISSUE THREAD

**Issue by Games4k** [konsolas/AAC-Issues#970]
_Hey, can you add autoblock (auto sworld block) check. That will probably stop 90% of killauras (if hackers dont turn it off)._

**Comment by Janmm14** [comment]
I want to underline that this will not stop killaura in any way, shape or form, just the autoblock part of it.
Cheat client creators and cheaters will quickly note that there is an autoblock check and it will just temporarily increase ban percentages.

**Comment by w-o-a-h** [comment]
AutoBlock already flags for "Speed: tried to toggle use too quickly"

**Comment by Slimerblue22** [comment]
Sometimes flags for interacting while blocking or something like that

**Comment by Games4k** [comment]
I told that it will stop 90% of killauras
> (if hackers dont turn autoblock off).

**Comment by Janmm14** [comment]
> I told that it will stop 90% of killauras

That is what you are thinking, but as I already wrote, it is wrong and it will just give you a small temporary boost of bans (1-2 weeks) until many cheat clients and cheaters (especially german cheaters) know that (and they will see any new cheat detection in aac) and they will simply disable the autoblock option in their killaura - I know also many cheat videos where the killaura is already set to not use autoblock.

**Comment by konsolas** [comment]
An auto-block specific check will not be added. Impossible actions related to autoblock are flagged by fightspeed, speed and interact.
