### ISSUE TITLE
Using Depth Strider 3 and Speed 2 in water triggers rubber banding

### ISSUE THREAD

**Issue by FrozenBeard** [konsolas/AAC-Issues#971]
I am using Celebrimbor config (as its paid I cant post it).
Latest AAC/PaperSigot on a bungee network on a dedicated server.

This has been a Major issue for months for false kicks.

From what I can figure out, **Depth Strider** enchantments on Armour trigger the anti-cheat underwater. 
using default game mechanics, no other plugins creating custom speed changes or any weird stuff, its triggering for default game mechanics.

here is a video of it happening.

https://www.youtube.com/watch?v=aEiowuINWbQ&feature=youtu.be

**Comment by Janmm14** [comment]
Issue is known for years and such "enchantments" are marked as not compatible in the AAC Overview (`Item Attributes (Speed attribute)`)

Additionally there is already an issue about that: #206

**Comment by Rerd** [comment]
This needs to be a feature soon. It's really annoying not being able to use Attribute Modifiers.

**Comment by FrozenBeard** [comment]
Woah what? I don't have any custom enchants from other plugins, this is all DEFAULT game mechanics **Depth Strider**. its Depth Strider thats triggers it.

**Comment by Rerd** [comment]
`any speed enchantments on Armour`
you meant Depth Strider?

**Comment by FrozenBeard** [comment]
@Rerd Yeah I commented afterwards and updated my main ticket as I think this just got assumed it was a custom third party plugin changing speed or something, its not this is default minecraft mechanics that are getting triggered.

**Comment by Rerd** [comment]
@Janmm14 re-open?

**Comment by FrozenBeard** [comment]
Bump, I noticed that the player mentions they have a speed 2 potion on too. So maybe its Speed 2 + Depth Strider 3 that's causing it. AAC not tested with default enchantments and potions.

**Comment by w-o-a-h** [comment]
this also happens without speed
