### ISSUE TITLE
Speed, NoWeb, NoSlowDown and Killaura Heuristics Bypass's

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#972]
[Download for client and also video of the bypasses.](https://www.youtube.com/watch?v=XxJkkLUIQLk)

NoSlow: AAC Mode On
NoWeb: AAC 3.3.0 or AAC TP
Speed: AAC Bhop or AAC YPORT
Killaura: Range = 1.0, Delay = 4.0, Crack Size = 1.0, Aiming = 4.4 and all other settings off
(or just toggle on Autoconfig for gommehd)

**Comment by Games4k** [comment]
Gommehd is not using default aac... heuristic and speed checks are different.
Try testing on default aac test server

**Comment by Janmm14** [comment]
gomme is using a valid aac setup, however such stuff will be handled internally and not here.
