### ISSUE TITLE
Fly FP with Rod

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#980]
### **Critical issue**
[Video](https://youtu.be/TBTPyfHrlwc)

Basically you just need to hold right click or spam right click with a rod on another player. This is critical because I've just recently got AAC added onto a bit of a larger pvp server and the rods are causing serious issues.

### Core information
**Server version**: Latest Spigot

**AAC version**: 3.3.2 (works on 3.3.3)

**ProtocolLib version**: 4.2.0

**Plugin list**: If requested.

### Configuration
Default

**Comment by Slimerblue22** [comment]
I think you linked the wrong video

**Comment by Rerd** [comment]
Correct, I did. Fixed.

**Comment by CeIebrimbor** [comment]
#851

**Comment by Rerd** [comment]
@CeIebrimbor this is completely different from that one. In this Issue I am using completely vanilla rods, in #851, they are using modified rods for 1.9.

**Comment by CeIebrimbor** [comment]
I think the plugin is irrelevant. It was reported as if it were a compatibility thing, but that's just a coincidence.

**Comment by Rerd** [comment]
This issue is really critical for servers that use rods for pvp.
