### ISSUE TITLE
Failed to pull entity hitboxes from NMS

### ISSUE THREAD

**Issue by JuliCarles** [konsolas/AAC-Issues#981]
### Issue description
Hey everyone. This error started to appear once I updated to 3.3.3.
It's rare and it pops up occasionally, however, it should be checked.
http://www.youscreenshot.com/edf84ecec73775e2a43f0706f3f0e6b2
Thanks.

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.3

**ProtocolLib version**: 4.2.0

**Plugin list**: Ask if needed.

### Special environment information
**ViaVersion version**: Latest (allowing 1.12.2

**ProtocolSupport version**: N/A

**ViaBackwards version**: N/A

**BungeeCord plugins**: Ask if needed.

### Configuration
Celebrimbor configuration 3.3.3 | 1.

**Comment by JuliCarles** [comment]
It seems to be something related on player login.
http://www.youscreenshot.com/749b1076412211f4e2d92a5cc1e0b09e
As **everytime** the error appears, there a
`logged in with entity id`
above of it.

**Comment by Janmm14** [comment]
This error does not harm and should only occurr shortly after player join (for the just joined player).
Related: #926

**Comment by CeIebrimbor** [comment]
@JuliCarles 
Confirmed still happening on [latest dev build](ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/) of ProtocolLib?

**Comment by JuliCarles** [comment]
I will try as soon as I can.

**Comment by Janmm14** [comment]
even on latest protocollib this notice will likely occurr sometimes, since there was nothing changed there.
it just means that for some milliseconds after joining the player might be able to use some cheats

**Comment by konsolas** [comment]
There won't be any problems because the default hitbox is used.
