### ISSUE TITLE
NoFall Bypass 6 Lines EZ

### ISSUE THREAD

**Issue by TornadoClientDev** [konsolas/AAC-Issues#982]
### Issue description
Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g. screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substitued for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be pasted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: 1.8.8

**AAC version**: 3.3.2

**ProtocolLib version**: idk

**Plugin list**: why

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: idk

**ViaBackwards version**: idk

**BungeeCord plugins**: idk

### Configuration
so its pretty ez xdddddxxxxxx meme

**Comment by Janmm14** [comment]
no further information given - closing

**Comment by w-o-a-h** [comment]
whats the point of this what lol

**Comment by Janmm14** [comment]
he seems to come every couple weeks making an useless issue just for his own fun

**Comment by ItzSomebody** [comment]
Probably has something to do with the fact that he is dev of Storm anticheat

**Comment by Janmm14** [comment]
#966 shows that he is having issues patching a simple glide in his anticheat:
> Im a anticheat dev and im trying to bypass a glide bypass that i cant patch please help me the glide code is
> mc.theplayer.motiony = -0.16;
> i cant patch it and i need help
> i work on my anticheat 24/7 my server ip is
> stormanticheat.g-s.nu
> there is no fly bypass right now only this one thanks!

I do really ask me why he says oh woah here I have this private nofall code which works according to my claims while he can't patch a simple glide in his own anticheat - and I think he does not have features like correct dragging down of the player when he tries to fly or even a nofall detection which works without problems.
