### ISSUE TITLE
ISE: Duplicate key (probably Collectors.toMap())

### ISSUE THREAD

**Issue by JavituRec** [konsolas/AAC-Issues#984]
### Issue description
I see the log and found this big spam error: https://hastebin.com/axudexepus.bash
I don't know cause.

### Core information
Server version: 1.8.8

AAC version: 3.3.3

ProtocolLib version: 4.3

Plugin list: http://subirimagen.me/uploads/20170927141053.png

### Special environment information
ViaVersion version: 1.3.0

AACAdditionPro: 3.2.3

BungeeCord plugins: Last

Sincerely.

**Comment by CeIebrimbor** [comment]
Try ProtocolLib 4.2.0.

Do you have KillauraEntity in AACadditionPro enabled? If so, try disabling and see what happens.

**Comment by ItzSomebody** [comment]
Looks like AAC is trying to write duplicate entries into a HashMap, did you try restarting your server?

**Comment by JavituRec** [comment]
I try restarting but I get a spam error yet.

**Comment by Janmm14** [comment]
This is likely not protocollib nor aacadditonpro related.

**Comment by CeIebrimbor** [comment]
Commonalities between this report and #997:
- Both 1.8.8 w/ latest ViaVersion
- Both have WorldEdit (doubt it's cause)

Differences(confirming @Janmm14's suspicions):
- One has latest dev build and on has older (likely not ProtLib related)
- One has AACaddition and other does not

**Comment by Janmm14** [comment]
The error is inside AAC and is caused by behaviour from java konsolas did not expect to happen.

**Comment by JavituRec** [comment]
The problem persist yet.

**Comment by marint94** [comment]
100MB+ logs thanks to this :(

**Comment by JavituRec** [comment]
I have removed AACAdittionPro but I get a big spam error yet, this cause lag.

[https://hastebin.com/oquxuyevuf.bash](url)

**Comment by ItzSomebody** [comment]
It's an issue with AAC writing duplicate keys into key-and-value map.

**Comment by konsolas** [comment]
will be fixed next update.
