### ISSUE TITLE
Phase Check? I want to stop phasing through all blocks

### ISSUE THREAD

**Issue by LunarCP** [konsolas/AAC-Issues#985]
### Issue description
I am trying to stop people from being able to phase through blocks. I am using a factions server and want it so people can't "glitch" into others bases.

### Core information
**Server version**: Paper Spigot 1.8.8

**AAC version**: 3.3.2

**ProtocolLib version**: 4.2.0

**Plugin list**: NoHunger, PandasSponge, FactionsFly, AntiSpam, EasySetSpawn, combatTracker, Ingot, InstaBreak, ViaVersion, AsyncWorldEditInjector, PotionStacker, LuckPerms, eZRename, Skript, FlatlandsBuilder, Craft_TNT, SpawnerTiers, AntiBow, FactionsHomes, CannonBasics, Chargedcegg, Multiverse-Core, ProtocolLib, DeathMessagesPrime, HCTeamsFreeze, PacketWrapper, KeepTheWeather, NoHopperCraft, CleanroomGenerator, Genbucket, PlaceholderAPI, OldMechanisms, NoDupe, MakeYourOwnCommands, TnTFill, HideAndCustomPlugins, NoFall, StopProxy, VoxelSniper, Reloader, OppleCooldown, NoNaturalSpawning, TagsGUI, EpicWorldGenerator, ItemFilter, MOTD, CreeperDrop, FixFreecam, WorldEdit, HealthBar, BountifulAPI, Vanish, WorldBorder, BuycraftX, JellyLegs, HarvesterHoes, Votifier, BlowableObsidians, AsyncWorldEdit, DupeFix, IPWhitelist, ActionAnnouncer, Vault, MassiveCore, ProVotes, AntiTab, MoneyPouch, Holograms, AAC, PlayerVaults, AACAdditionPro, CrazyCrates, ClearChat, WorldGuard, AuctionHouse, BetterRTP, Essentials, AdvancedRepair, UltimateCasino, ConditionalCommands, MythicMobs, HardHat, EssentialsChat, RankVouchers, MythicMobs188, Factions, FactionUUIDLogout, MobStacker2, FBasics, CombatTagPlus, Ace-Outposts, FactionsTop, LinkItem, SilkSpawners, CrazyEnchantments, WGCustomFlags, WGFlyFlag, WildTP, CommandAliases

### Special environment information
**ViaVersion version**: 1.3.0

**ProtocolSupport version**: NA

**ViaBackwards version**: NA

**BungeeCord plugins**: NA

### Configuration
Default Phase Settings

**Comment by Janmm14** [comment]
Did you edit any setting of the move check?

**Comment by Slimerblue22** [comment]
I know some phase hacks work but do flag so I have my config to kick for phase at VL 25 (It sometimes kicks for ghost blocks though)

**Comment by CeIebrimbor** [comment]
tp_accept_threshold: 0.001
@Janmm14 

Unless he changed it and didn't inform.

**Comment by konsolas** [comment]
Need information about what bypasses.

**Comment by Slimerblue22** [comment]
This was awhile ago so not sure if it still works but I know WolfRam's phase would work (Flagged like all heck though)

**Comment by CeIebrimbor** [comment]
@Slimerblue22 
So you got flagged, but after persistently attempting phase, you eventually pass through?

I'm not sure this is an actual bypass report by the OP or a simple question about phase checking and they were new to AAC. I am inclined to close the issue because the OP seems to have made the report and logged off forever.
