### ISSUE TITLE
AAC blocking player respawn movements?

### ISSUE THREAD

**Issue by Hyronymos** [konsolas/AAC-Issues#986]
Video: https://www.youtube.com/watch?v=ou-VvcL0ZU0&feature=youtu.be
AAC-Log: https://pastebin.com/22BBVm3G
Server-Log: https://pastebin.com/EP9UYdjr

**Comment by CeIebrimbor** [comment]
Video "unavailable"

**Comment by Hyronymos** [comment]
ups, done

**Comment by CeIebrimbor** [comment]
Is this something that happens frequently or was this a freak instance? Possibly a teleport desync? What is your `tp_accept_threshold` setting in "move"?

**Comment by CeIebrimbor** [comment]
Labeling Insufficient for now.

**Comment by Hyronymos** [comment]
tp_accept_threshold: 0.001 still happened with tp_accept_threshold: 0.08

**Comment by Janmm14** [comment]
Best possibility for debugging in that case is `/aacdebug playername` - it will genrate a file showing why AAC thinks it has to block all movements of a player because he did not arrived at his respawn/teleport location yet.

**Comment by Hyronymos** [comment]
I will try it

**Comment by Janmm14** [comment]
Similar issues are being looked at currently.

**Comment by Janmm14** [comment]
Possibly a duplicate of #1001.
In case this issue is not fixed by AAC 3.3.4, please request a reopen.

**Comment by Janmm14** [comment]
Discussion can go on at issue 1035.
