### ISSUE TITLE
E-Pearl through bedrock?

### ISSUE THREAD

**Issue by Pikuuu** [konsolas/AAC-Issues#987]
Server: 1.8.8
AAC: 3.3.3
ProtocolLib: 4.2.0

During a bedrock fight, the player sometimes discards the map

**Comment by CeIebrimbor** [comment]
What AAC detection causes the player to be sent through the map?

**Comment by Janmm14** [comment]
Verbose output what happens exactly?

**Comment by Rerd** [comment]
A video of this happening with verbose enabled would be great.

**Comment by Slimerblue22** [comment]
What the heck is a bedrock fight? Are they fighting at Y1? Also by discards the map are you meaning leaves the map or falling through the world?

**Comment by Pikuuu** [comment]
Yes, Y1. During the fight, we just fall into the ground and die.  Also
when, for example, I throw "enderpearl" in the wall somewhere a couple of
times I'm penetrating through walls, or it bugs me and I can do nothing

2017-09-30 3:25 GMT+02:00 Slimerblue22 <notifications@github.com>:

**Comment by Slimerblue22** [comment]
So this only happens with Epearls? Might not be AAC then. Throwing Epearls fast enough can cause you to glitch up or through blocks.

**Comment by Pikuuu** [comment]
If i delete AAC is good.

01.10.2017 2:19 PM "Slimerblue22" <notifications@github.com> napisał(a):

**Comment by CeIebrimbor** [comment]
This is now pending close since no information (video, log, check causing issue, etc) has been added. Please add more info if this is a legitimate issue. Or better yet, follow the reporting template.

**Comment by Pikuuu** [comment]
"Enderpearl bug"

04.10.2017 8:33 PM "Celebrimbor" <notifications@github.com> napisał(a):

**Comment by konsolas** [comment]
I still have no idea what's going on here. Please follow the issue template when reporting an issue here. 

Closing due to insufficient information.
