### ISSUE TITLE
AAC Error, didn't load... :(

### ISSUE THREAD

**Issue by Benjamin1121YT** [konsolas/AAC-Issues#994]
### Issue description
Please include a detailed description of the issue, instructions to reproduce it, client names/links (if applicable), and a relevant paste from plugins/AAC/logs. Please include as much information as possible, including anything about the environment that may be relevant (e.g., a screenshot of the location). A video with (config.yml:verbose -> true) is useful but not required. It should not be substituted for a description.

If you a reporting a console error, take the earliest version in the console log to make sure none of the error is cut off.

Large blocks of text should be posted on https://gist.github.com/ or within markdown code blocks. 

### Core information
**Server version**: insert
1.12
**AAC version**: insert
3.3.3
**ProtocolLib version**: insert
Newest Avitabile
**Plugin list**: insert
Coreprotect, world edit, picture login, TitleWelcomeMessage, reports, Multiverse-Sign-Portals, Multiverse-Core, PEX, apply MC. CreeperHeal, Custom Join Items, SimpleHelpOp, Vault, ChairStairs, Global Execute, Essentials, Ultra Cosmetics, Citizens, ChestCommands, and essentials spawn.
### Special environment information
**ViaVersion version**: insert (or N/A)
NA
**ProtocolSupport version**: insert (or N/A)
NA
**ViaBackwards version**: insert (or N/A)
NA
**BungeeCord plugins**: insert (or N/A)
BungeePexBrige, BuycraftX, and GlobalExecute (bungee)
### Configuration
Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check unless you are reporting a false kick/ban. 

For the lazy, you may use this [online diff tool](https://www.diffchecker.com/) - make sure you select "Store forever."

**Comment by Janmm14** [comment]
1. Newest is no version.
2. You failed to provide logs.
3. You are suppoed to replace the informative text between "Issue description" and "Core information"

**Comment by CeIebrimbor** [comment]
This is being closed due to inactivity and the fact that there is nothing to go off. 

Please open a new issue and actually fill out the information (including a description and console startup output) or request re-open here if you edit the existing post.
