### ISSUE TITLE
Flux b12 Killaura Bypass

### ISSUE THREAD

**Issue by Rerd** [konsolas/AAC-Issues#995]
Flux b12's Killaura bypasses Heuristics. (Make sure to have Mob, Player and Invisible toggled on in the settings for killaura) Anything that doesn't flag Normal and Hitbox will work fine.

[Video Here](https://youtu.be/LiUIaf7Rt-M)

If you need a leaked download of the client (because it's paid) you can look in the description of the video.

### Core information
**Server version**: git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**AAC version**: 3.3.3

**ProtocolLib version**: 4.2.0

**Plugin list**: If Requested

### Configuration
Default Config

**Comment by Slimerblue22** [comment]
Could you try this while being attack and with a moving player?

**Comment by w-o-a-h** [comment]
it most likely works because multi aura in flux does not aim at anything and you are manually aiming at the player so its like a bad triggerbot now

**Comment by Games4k** [comment]
Try in real pvp

**Comment by Rerd** [comment]
Didn’t realize I had multi on, sorry.

**Comment by w-o-a-h** [comment]
yeah the Heuristics use aiming patterns and stuff i think

**Comment by ItzSomebody** [comment]
Heuristics supply the program with a best guess if a player is hacking or not

**Comment by Rerd** [comment]
This actually still works even without Mutli on. Just realized. Re-open?

**Comment by Hyronymos** [comment]
It's invalid. Fluxb12 does not bypass latest AAC Version

**Comment by Janmm14** [comment]
Either accidentally fixed or invalid from the beginning.
