### ISSUE TITLE
Walking on farmland detects as flying

### ISSUE THREAD

**Issue by Shieldtrain** [konsolas/AAC-Issues#996]
When a player of mine walks on farmland they get kicked and teleport back
Note: it only happens for me on 1.9-1.12.2 players

Pictures

Player view

![2017-10-03_16 36 53](https://user-images.githubusercontent.com/27511113/31150619-f30436be-a859-11e7-91b8-db7c18018e6a.png)

![2017-10-03_16 37 33](https://user-images.githubusercontent.com/27511113/31150646-0ebe6528-a85a-11e7-956d-c141819be454.png)

![2017-10-03_16 37 39](https://user-images.githubusercontent.com/27511113/31150653-17daec4e-a85a-11e7-894f-cf53df38f9b5.png)

Staff View

![2017-10-03_16 37 21](https://user-images.githubusercontent.com/27511113/31150816-b4d87e80-a85a-11e7-9f2e-ccfaadc47f51.png)

![2017-10-03_16 37 26](https://user-images.githubusercontent.com/27511113/31150898-ff322274-a85a-11e7-8514-e3ba9c5bfefd.png)

![2017-10-03_16 46 33](https://user-images.githubusercontent.com/27511113/31150957-39681296-a85b-11e7-9f1c-f46eca8998d5.png)

Server information
**Server version**: 1.8-1.12.2 (1.8.8)

**AAC version**: 3.3.2

**ProtocolLib version**: 4.3.0

**ProtocolSupport**: Not using that

**Comment by Janmm14** [comment]
little note: `latest` is no valid version

**Comment by Shieldtrain** [comment]
Then 4.3.0
protocolLib

**Comment by Shieldtrain** [comment]
Fixed,
thanks!

**Comment by ItzSomebody** [comment]
3.3.2 or 3.3.3?

3.3.3 shows as 3.3.2 because konsolas forgot to change version number

**Comment by CeIebrimbor** [comment]
#922

**Comment by Shieldtrain** [comment]
No its not done @CeIebrimbor I was talking about a error in my report
@ItzSomebody its 3.3.2 of version 3.3.2-b2
ill try the new version and see if it still goes on

**Comment by Shieldtrain** [comment]
Its seems to be fixed
