### ISSUE TITLE
Fly Detection False Positives

### ISSUE THREAD

**Issue by LinsaFTW** [konsolas/AAC-Issues#998]
~~Rodding someone makes him rubberband.~~ #851

Swimming on water rubberbands yourself.

###Core information

Server version: 1.8.8 TacoSpigot

AAC version: 3.3.3

ProtocolLib version: Latest dev build (389)

Plugin list: EnchantLimiter, StrDis, WorldEdit, SpawnTP, vAntiPearlGlitch, zPermissions, EPearlCooldown, WorldGuard, MVdWPlaceholderAPI, MinecartElevator, AutoRestart, DeathMessages, FeatherBoard, HCTeamsFreeze, MicroJump, Tab, AntiPortalTrapping, ViaVersion, Vault, EZBlocks, ColoredAnvils, Lores, NoGodApple, boosCooldowns, RedstoneClockPreventer, StackMob, Essentials, AnimatedNames, KillerMoney, ProtocolLib, TagSpawnProtection, AAC, Citizens, DeathBan, ChestCommands, EssentialsChat, CommandNPC, ChatGuard, CombatLogX, EssentialsMysqlStorage, HolographicDisplays, LiteBans, Factions, LeaderHeads, RandomTeleport

###Special environment information

ViaVersion version: Latest

ProtocolSupport version: N/A

ViaBackwards version: N/A

BungeeCord plugins: N/A

###Configuration

I only have increased thresholds because of all the false positives and decreased the tolerance and e_tolerance because the false positives made everyone teleport

It is detecting only fly , doing like "dolphin" on water.

It seems it only happens on my server xD but there isnt any plugin that can be inheriting and the config cant be interfering too

**Comment by CeIebrimbor** [comment]
Please use issue template.

https://github.com/konsolas/AAC-Issues/blob/master/ISSUE_TEMPLATE.md

**Comment by LinsaFTW** [comment]
Its just not necessary. Tested on my server with several people and tested on official test server.

And about the rod Knockback this started happening on 3.3.0

**Comment by CeIebrimbor** [comment]
#851 = Rod report

Need more info about the water detection and how to reproduce. Is it knockback in water, speed potion, depth strider potion, simple swimming?

Thus the reason for requesting more info. You should state that it is on the test server, but you need to say how to reproduce and if you can, replicate on your server and provide detection verbose.

**Comment by LinsaFTW** [comment]
Core information

Server version: 1.8.8 TacoSpigot

AAC version: 3.3.3 (It shows 3.3.2 but i think that its another bug because the downloaded jar is of the latest release on spigot)

ProtocolLib version: 4.3.0

Plugin list: EnchantLimiter, StrDis, WorldEdit, SpawnTP, vAntiPearlGlitch, zPermissions, EPearlCooldown, WorldGuard, MVdWPlaceholderAPI, MinecartElevator, AutoRestart, DeathMessages, FeatherBoard, HCTeamsFreeze, MicroJump, Tab, AntiPortalTrapping, ViaVersion, Vault, EZBlocks, ColoredAnvils, Lores, NoGodApple, boosCooldowns, RedstoneClockPreventer, StackMob, Essentials, AnimatedNames, KillerMoney, ProtocolLib, TagSpawnProtection, AAC, Citizens, DeathBan, ChestCommands, EssentialsChat, CommandNPC, ChatGuard, CombatLogX, EssentialsMysqlStorage, HolographicDisplays, LiteBans, Factions, LeaderHeads, RandomTeleport

Special environment information

ViaVersion version: Latest

ProtocolSupport version: N/A

ViaBackwards version: N/A

BungeeCord plugins: N/A

Configuration

I only have increased thresholds because of all the false positives and decreased the tolerance and e_tolerance because the false positives made everyone teleport


It is detecting only fly , doing like "dolphin" on water.

It seems it only happens on my server xD but there isnt any plugin that can be inheriting and the config cant be interfering too

**Comment by LinsaFTW** [comment]
PD: The rod happens on the test server too

https://hastebin.com/oxazafogeq.bash this is my fly config

**Comment by CeIebrimbor** [comment]
Not that it's the definite cause/solution, but you are using an unrecommended ProtocolLib version for 1.8.8 servers. It is recommended you use 4.2.0 or you use the [latest stable dev build](http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/) which re-added compatibility lost in builds between 4.2.0 and 4.4.0-SNAPSHOT

Please report back if the issue is still happening after using the correct ProtocolLib. If so, is it just normal speed swimming (holding swim/jump and moving forward)?

**Comment by LinsaFTW** [comment]
Ok thanks ill update and tell you how it goes 👍

**Comment by LinsaFTW** [comment]
Still detecting :/ i updated to the Latest stable dev build

**Comment by CeIebrimbor** [comment]
Please provide the detection verbose you get as it correlates to actions in water. Or a video.

**Comment by LinsaFTW** [comment]
I found another fly false positive when going downstairs on slabs.

How do i publish images here? so i can show the verbose

**Comment by LinsaFTW** [comment]
Water:
![2017-10-04_19 36 20](https://user-images.githubusercontent.com/25271111/31202978-5a6a2b24-a93b-11e7-91c8-81c6e5f721a5.png)

Slabs:
![2017-10-04_19 35 26](https://user-images.githubusercontent.com/25271111/31202979-5be1f2ac-a93b-11e7-875c-2255da602752.png)

**Comment by CeIebrimbor** [comment]
What does plugin MicroJump do?

**Comment by LinsaFTW** [comment]
Jump between bungee servers duh xD

**Comment by LinsaFTW** [comment]
False Positive when walking on Grass:

![2017-10-04_20 13 47](https://user-images.githubusercontent.com/25271111/31204119-a03bf8f8-a940-11e7-8f87-a43272587e6e.png)

**Comment by LinsaFTW** [comment]
False Positive when going downstairs blocks and slabs:

![2017-10-04_20 19 18](https://user-images.githubusercontent.com/25271111/31204236-508f2888-a941-11e7-8974-018f59f43e81.png)

**Comment by LinsaFTW** [comment]
Jumping and walking on any surface: (This happens only to few players but its a annoying)

![2017-10-04_21 24 05](https://user-images.githubusercontent.com/25271111/31205850-7d72d508-a94a-11e7-87fe-711ff16a855e.png)

**Comment by LinsaFTW** [comment]
@CeIebrimbor This happened when decreasing tolerance to low values. Does that mean it was my fault? Or the tolerance is bugged? (If it was my fault im sorry i tough tolerance means less teleport)

**Comment by CeIebrimbor** [comment]
Put tolerance at default. Lowering thresholds is never the answer to fix bypasses or increase effectiveness of checks.
