### ISSUE TITLE
Errors spam and FP of FightSpeed

### ISSUE THREAD

**Issue by Toshka17** [konsolas/AAC-Issues#999]
PaperSpigot 1.12.1
AAC 3.3.3

Log: https://pastebin.com/UmvQgj0b

**Comment by CeIebrimbor** [comment]
Not sure where the evidence of the Fightspeed FP is, but the error is #984. If you want to address the Fightspeed, please open a new report and actually use the issue reporting template.

**Comment by Toshka17** [comment]
The proof is in the log.
Every time this error occurs, all players on the server get a kick for FightSpeed

**Comment by Rerd** [comment]
Maybe FightSpeed isn’t getting disabled (or disabled fast enough) when the server lags?

**Comment by CeIebrimbor** [comment]
I see that players are kicked for Fightspeed after the error occurs. Seeing as how the issue is tied to the error, it is still a duplicate of #984
